### ISSUE TITLE
Renaming a .cs file when updating a .csproj file reference

### ISSUE THREAD

**Issue by jrieken** [dotnet/vscode-csharp#10]
_From @RockyTV on December 31, 2015 14:30_

If you open a C# project path with VSCode, then rename a file that is used by a C# Project, the reference in the .csproj file will not be updated.

_Copied from original issue: Microsoft/vscode#1724_

**Comment by JoeRobich** [comment]
Most SDK style projects use the default file globbing instead of individual `<Compile />` entries in this project. I do not expect us to invest in project manipulation for the C# extension. This functionality may be covered with C# DevKit.
