### ISSUE TITLE
C#: No symbols matching

### ISSUE THREAD

**Issue by CIPop** [dotnet/vscode-csharp#1038]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview2-003133)

Product Information:
 Version:            1.0.0-preview2-003133
 Commit SHA-1 hash:  74df06500c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14989
 OS Platform: Windows
 RID:         win10-x64
```
VS Code version:
```
Version 1.7.2
Commit 7ba55c5860b152d999dda59393ca3ebeb1b5c85f
Date 2016-11-21T22:06:37.428Z
Shell 1.3.8
Renderer 52.0.2743.82
Node 6.5.0
```
C# Extension version: `1.5.3`

## Steps to reproduce
1. git clone https://github.com/dotnet/corefx.git
2. code .\src
3. Ctrl+T HttpClient

## Expected  behavior
The HttpClient symbol is found in multiple files.

## Actual behavior
"No symbols matching" even if the only file opened contains the type definition:
![image](https://cloud.githubusercontent.com/assets/8635911/21164589/e383dd5e-c14e-11e6-9217-9fe13c7573a6.png)

**Comment by DustinCampbell** [comment]
Hi -- sorry for taking so long to get to this!

It looks to me like the repro steps aren't complete. At the very least, I see failures when we're loading projects that init-tools.cmd needs to be run first. Will try that.

**Comment by DustinCampbell** [comment]
It looks to me like there is just such a sheer number of projects in core\fx\src that the OmniSharp server times out before it gets everything loaded. The default timeout is 60 seconds. I increased that to 600 on my machine by setting the "omnisharp.projectLoadTimeout" setting in VS Code and it finished properly. I couldn't get Ctrl+T to show anything, but I'm not surprised given the sheer size of what was thrown at it. :smile:

I *was* able to get hover tool tips and intellisense working however. I suspect there's likely some performance work that can be done for to make symbol search work properly. However, it functioned as best as it could.

**Comment by CIPop** [comment]
With the latest VSCode release I noticed that after the C++ extension (using CLang) is installed, C++ symbols work. Sadly, C# still doesn't work.

I'm working around this by using Sublime and its integrated parser (Ctrl+Shift+R will correctly find the symbols without the Omnisharp plugin installed).

**Comment by JoeRobich** [comment]
Closing as a lot has changed since this issue was opened. Please open a new issue if you are still having issues with symbols.
