### ISSUE TITLE
Built-in property and method help should include fully qualified type name

### ISSUE THREAD

**Issue by pcgeek86** [dotnet/vscode-csharp#1118]
## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
```

VS Code version: 1.8.1
C# Extension version: 1.6.2

## Expected  behavior

When examining the built-in help documentation for C# properties and methods, the fully qualified type name of the member should be shown.

For example, in the following screenshot, only the `RegionEndpoint` type name is shown, but that type belongs to the Amazon namespace. So, the help docs should show: `Amazon.RegionEndpoint`. 

It should also show the type's type as well: eg. `struct`, `class`, `enum`, etc.

![2017-01-13_11-37-59](https://cloud.githubusercontent.com/assets/466713/21941219/f4be8ba2-d984-11e6-8e80-d1dad86ca11e.png)

http://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/Amazon/TRegionEndpoint.html

## Actual behavior

Only the type name is shown, omitting the namespace that it belongs to, and type (class, enum, struct, etc.) .

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by DustinCampbell** [comment]
Thanks for the note. We'll have much better support for the text in tooltips once the new Quick Info API is available from Roslyn (https://github.com/dotnet/roslyn/pull/13623)

**Comment by rchande** [comment]
@DustinCampbell @akshita31 It looks like Dustin's PR https://github.com/dotnet/roslyn/pull/20554. We can probably replace the existing TypeLookup code with.

**Comment by DustinCampbell** [comment]
@rchande, looking closer at the screenshot, does this look like a hover tooltip or the completion list?

**Comment by rchande** [comment]
@DustinCampbell You're right, that does look like a completion list. I think we still have a separate work item to go consume your quickinfo API. Thoughts?

**Comment by DustinCampbell** [comment]
Yeah, I was planning to work on supporting the new Quick Info API once the 2.9.0 Roslyn packages show up on NuGet (they're not there yet).

**Comment by rchande** [comment]
@DustinCampbell I know @akshita31 wanted to start doing more work on the omnisharp-roslyn side. Do you think this would be a good workitem for her to pick up?

**Comment by JoeRobich** [comment]
Closing as Hover and Completion documentation is much improved since this issue was opened. Please open a new issue if you run into problems with documentation.
