### ISSUE TITLE
The C# extension does not start unless *.cs file is opened or the workspace contains a project.json

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/vscode-csharp#1150]
It should also launch if the workspace contains an .sln or .csproj file.

**Comment by DustinCampbell** [comment]
The simplest fix is blocked by https://github.com/Microsoft/vscode/issues/944.

**Comment by JerryNixon** [comment]
Here's a repro to creating the error message in Visual Studio Code. Please notice that the entire scenario takes place in the Visual Studio Code terminal. There is no `cmd` shell. This means opening a `.cs` file is not a certainty in the developer's workflow. Also, notice a `.cs` file is NEVER opened before a debug is attempted.

> launch: launch.json must be configured. Change 'program' to the path to the executable file that you would like to debug

![netcore](https://cloud.githubusercontent.com/assets/1749983/22308859/faa12e1e-e305-11e6-90d3-1a968b0df6a7.gif)

If the user manually edits the value of `program` in `launch.json` then this error can be resolved. The error message clearly states that. However, this manual extra step is certainly a confusing one in light of how automated the rest of the workflow is. I would also argue that such a path is prone to error. 

**workaround**

Just switching into the project and also opening a `.cs` file will cause the tooling to handle this properly. This needs to be done prior to the first debugging session. Probably most developers won't realize the subtly of this requires step, but at least there's a way.

![netcore3](https://cloud.githubusercontent.com/assets/1749983/22309215/8aaba678-e307-11e6-865f-7d8530e0f4f5.gif)

**Comment by DustinCampbell** [comment]
Unfortunately, this won't make it for our 1.7 release as we're blocked waiting for changes to VS Code in support of this scenario.

**Comment by DustinCampbell** [comment]
OK. Thanks to @eamodio's PR for VS Code, we're able to improve the experience here a bit. However, this particular repro is still problematic. Essentially, we can now update the extension to activate when the workspace contains a *.csproj or *.sln (using wildcards). However, that only activates an extension when a folder is *opened*. In this particular scenario, the folder is already open, so the extension still won't activate until you open a .cs file.

**Comment by eamodio** [comment]
@DustinCampbell That is only because there was no other projects or anything opened beforehand to have the extension activate correct? FYI, https://github.com/Microsoft/vscode/issues/28122 is a feature request to have it detect when new files are added.

**Comment by DustinCampbell** [comment]
Thanks for the pointer @eamodio! I think that would address this.

**Comment by akshita31** [comment]
@DustinCampbell This is fixed now right ?

**Comment by JoeRobich** [comment]
Closing as this is now fixed.
