### ISSUE TITLE
The editor jumps up and down while typing when recalculating the "# references"

### ISSUE THREAD

**Issue by ZurielCorrea** [dotnet/vscode-csharp#1173]
## Environment data
`dotnet --info` output:
VS Code version: 1.8.1
C# Extension version: 1.7.0-beta2

## Steps to reproduce
In VSCode the recalculation of the "# references" text that goes on top of properties and methods makes the user experience somewhat jumpy.
So while I'm typing in a new line the "# references" text disappears, then when I finish the line the lines in the screen move again to re-accommodate the "#references".

## Expected  behavior
I would prefer if the lines of code doesn't move up and down as much while I'm typing.

## Actual behavior
The editor keeps moving the lines when the "# references" text appears and disappears.

**Comment by DustinCampbell** [comment]
We should recalculate code lens on a delay to improve some of the jumpiness while typing.

**Comment by tetious** [comment]
I think part of the problem is that the lens text is removed and then re-inserted when the code recalc takes place. 

I'm not sure it is possible, but it would be nice if the lens text **updated in-place** instead. This would prevent jumping on re-calc, which is especially annoying when switching editor tabs. :)

**Comment by DustinCampbell** [comment]
Totally agree. Thanks for the comment @tetious

**Comment by theiviaxx** [comment]
A similar distraction is going between files.  The reference lines are not present then "pop" in which is really distracting.  It would be cool if they were just always there at 0 references and update in place as tetious has suggested.

**Comment by JoeRobich** [comment]
CodeLens seems fairly stable at this point. Reopen if this is still an issue.
