### ISSUE TITLE
Use jsonc-parser for parsing JSON

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/vscode-csharp#1237]
This is the JSON scanner that is used in VS Code for parsing JSON files that include comments. We should use that instead of our home-rolled scanner.

**Comment by DustinCampbell** [comment]
We should also remove the json.tolerantParse(...) API in favor of this. (https://github.com/OmniSharp/omnisharp-vscode/issues/1076)

**Comment by JoeRobich** [comment]
Closing as it seems the jsonc-parser was adopted at some point.
