### ISSUE TITLE
CPU over 200% when open new File on Mac pro

### ISSUE THREAD

**Issue by ChongWangUBI** [dotnet/vscode-csharp#1240]
## Environment data
`dotnet --info` output: 1.0.0-preview2-003121
VS Code version: 1.9.1
C# Extension version: 1.8.0-beta1

## Steps to reproduce
Open new C# File, Quickly Scroll to the File End

## Expected  behaviour
set "editor.codeLens": false  seem better

## Actual behavior
<img width="725" alt="f875ec95-ba75-4870-bcfa-2a49a13664b6" src="https://cloud.githubusercontent.com/assets/16005289/22987935/5845388a-f3eb-11e6-96bf-0084df7acaad.png">

did i have any wrong version sdk?

**Comment by DustinCampbell** [comment]
Did you open a project in VS Code?

**Comment by ChongWangUBI** [comment]
open Unity sln project.
in old version, ominsharp seem use .net(mac) version for mac.
when open new file,do not slow like current version.

current version, let me can not coding..

**Comment by ChongWangUBI** [comment]
<img width="587" alt="mac" src="https://cloud.githubusercontent.com/assets/16005289/23039486/9395c02a-f4c8-11e6-9593-3aaf58b0811e.png">
my mac info.

my project info
Starting OmniSharp server at 2/17/2017, 4:28:04 AM
    Target: /Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client

OmniSharp server started wth Mono
    Path: /Users/wangchong/.vscode/extensions/ms-vscode.csharp-1.8.0-beta1/bin/run
    PID: 1767

OmniSharp: -s /Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client --hostPID 1755 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
﻿﻿{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.Startup","Message":"Omnisharp server running using Stdio at location '/Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client' on host 1755."},"Seq":1,"Type":"event"}
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in /Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update project /Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Assets/ThirdParty/protobuf-net
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Add project /Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Assets/ThirdParty/protobuf-net/project.json => 80873152-6d41-462d-8836-2e988c07e1ed
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Add project /Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Assets/ThirdParty/protobuf-net/project.json => c8628d14-2b29-43f8-9dad-ecc3605fd4b3
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Add project /Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Assets/ThirdParty/protobuf-net/project.json => 20b1bc10-1fc6-487b-9f2a-4fc08fa4c4c3
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Add project /Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Assets/ThirdParty/protobuf-net/project.json => ac28623a-90ac-4c08-8621-b902d4336aa7
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.DotNet.DotNetProjectSystem
          Processing [ProjectState] protobuf-net/.NETFramework,Version=v4.0
[info]: OmniSharp.DotNet.DotNetProjectSystem
            Added 5 and removed 0 file references
[info]: OmniSharp.DotNet.DotNetProjectSystem
            Added 89 and removed 0 documents.
[info]: OmniSharp.DotNet.DotNetProjectSystem
          Processing [ProjectState] protobuf-net/.NETFramework,Version=v4.5
[info]: OmniSharp.DotNet.DotNetProjectSystem
            Added 6 and removed 0 file references
[info]: OmniSharp.DotNet.DotNetProjectSystem
            Added 89 and removed 0 documents.
[info]: OmniSharp.DotNet.DotNetProjectSystem
          Processing [ProjectState] protobuf-net/DNX,Version=v4.5.1
[info]: OmniSharp.DotNet.DotNetProjectSystem
            Added 6 and removed 0 file references
[info]: OmniSharp.DotNet.DotNetProjectSystem
            Added 89 and removed 0 documents.
[info]: OmniSharp.DotNet.DotNetProjectSystem
          Processing [ProjectState] protobuf-net/.NETPlatform,Version=v5.4
[info]: OmniSharp.DotNet.DotNetProjectSystem
            Added 8 and removed 0 file references
[info]: OmniSharp.DotNet.DotNetProjectSystem
            Added 89 and removed 0 documents.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        MSBUILD_EXE_PATH environment variable set to /Users/wangchong/.vscode/extensions/ms-vscode.csharp-1.8.0-beta1/bin/omnisharp/msbuild/MSBuild.dll
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        MSBuildExtensionsPath environment variable set to /Users/wangchong/.vscode/extensions/ms-vscode.csharp-1.8.0-beta1/bin/omnisharp/msbuild
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        MSBuildSDKsPath environment variable set to /Users/wangchong/.vscode/extensions/ms-vscode.csharp-1.8.0-beta1/bin/omnisharp/msbuild/Sdks
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Detecting projects in '/Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Client.sln'.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project from '/Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Assembly-CSharp-firstpass.csproj'.
Discovered Mono file path: /usr/local/bin/mono
Resolved symbolic link for Mono file path: /usr/local/Cellar/mono/4.6.2.16/bin/mono-sgen
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Add project: /Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Assembly-CSharp-firstpass.csproj
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project from '/Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Assembly-CSharp.csproj'.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Add project: /Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Assembly-CSharp.csproj
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project from '/Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Assembly-CSharp-Editor-firstpass.csproj'.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Add project: /Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Assembly-CSharp-Editor-firstpass.csproj
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Loading project from '/Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Assembly-CSharp-Editor.csproj'.
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Add project: /Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Assembly-CSharp-Editor.csproj
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Update project: Assembly-CSharp-firstpass
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Update project: Assembly-CSharp
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Unable to resolve assembly '/Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Temp/bin/Debug/Assembly-CSharp-firstpass.dll'
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Update project: Assembly-CSharp-Editor-firstpass
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Unable to resolve assembly '/Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Temp/bin/Debug/Assembly-CSharp-firstpass.dll'
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Update project: Assembly-CSharp-Editor
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Unable to resolve assembly '/Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Temp/bin/Debug/Assembly-CSharp-Editor-firstpass.dll'
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Unable to resolve assembly '/Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Temp/bin/Debug/Assembly-CSharp-firstpass.dll'
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Unable to resolve assembly '/Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Temp/bin/Debug/Assembly-CSharp.dll'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Startup
        Configuration finished.

**Comment by ChongWangUBI** [comment]
<img width="699" alt="cpu" src="https://cloud.githubusercontent.com/assets/16005289/23040294/c81e7e1a-f4cb-11e6-97bd-ad171ef097f3.png">
pls help me, it always like this. almost 1 min,when open new file, scroll down to the file end.

**Comment by konistehrad** [comment]
I'm seeing the same issue on a Unity project of my own. Is there any data I can provide the team that would help to debug the issue?

**Comment by jxncyjq** [comment]
> <img alt="mac" width="587" src="https://cloud.githubusercontent.com/assets/16005289/23039486/9395c02a-f4c8-11e6-9593-3aaf58b0811e.png">
> 
> my mac info.
> my project info Starting OmniSharp server at 2/17/2017, 4:28:04 AM Target: /Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client
> 
> OmniSharp server started wth Mono Path: /Users/wangchong/.vscode/extensions/ms-vscode.csharp-1.8.0-beta1/bin/run PID: 1767
> 
> OmniSharp: -s /Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client --hostPID 1755 --stdio DotNet:enablePackageRestore=false --encoding utf-8 --loglevel information formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4 ﻿﻿{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.Startup","Message":"Omnisharp server running using Stdio at location '/Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client' on host 1755."},"Seq":1,"Type":"event"} [info]: OmniSharp.DotNet.DotNetProjectSystem Initializing in /Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client [info]: OmniSharp.DotNet.DotNetProjectSystem Auto package restore: False [info]: OmniSharp.DotNet.DotNetProjectSystem Update workspace context [info]: OmniSharp.DotNet.DotNetProjectSystem Update project /Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Assets/ThirdParty/protobuf-net [info]: OmniSharp.DotNet.DotNetProjectSystem Add project /Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Assets/ThirdParty/protobuf-net/project.json => 80873152-6d41-462d-8836-2e988c07e1ed [info]: OmniSharp.DotNet.DotNetProjectSystem Add project /Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Assets/ThirdParty/protobuf-net/project.json => c8628d14-2b29-43f8-9dad-ecc3605fd4b3 [info]: OmniSharp.DotNet.DotNetProjectSystem Add project /Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Assets/ThirdParty/protobuf-net/project.json => 20b1bc10-1fc6-487b-9f2a-4fc08fa4c4c3 [info]: OmniSharp.DotNet.DotNetProjectSystem Add project /Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Assets/ThirdParty/protobuf-net/project.json => ac28623a-90ac-4c08-8621-b902d4336aa7 [info]: OmniSharp.DotNet.DotNetProjectSystem Resolving projects references [info]: OmniSharp.DotNet.DotNetProjectSystem Processing [ProjectState] protobuf-net/.NETFramework,Version=v4.0 [info]: OmniSharp.DotNet.DotNetProjectSystem Added 5 and removed 0 file references [info]: OmniSharp.DotNet.DotNetProjectSystem Added 89 and removed 0 documents. [info]: OmniSharp.DotNet.DotNetProjectSystem Processing [ProjectState] protobuf-net/.NETFramework,Version=v4.5 [info]: OmniSharp.DotNet.DotNetProjectSystem Added 6 and removed 0 file references [info]: OmniSharp.DotNet.DotNetProjectSystem Added 89 and removed 0 documents. [info]: OmniSharp.DotNet.DotNetProjectSystem Processing [ProjectState] protobuf-net/DNX,Version=v4.5.1 [info]: OmniSharp.DotNet.DotNetProjectSystem Added 6 and removed 0 file references [info]: OmniSharp.DotNet.DotNetProjectSystem Added 89 and removed 0 documents. [info]: OmniSharp.DotNet.DotNetProjectSystem Processing [ProjectState] protobuf-net/.NETPlatform,Version=v5.4 [info]: OmniSharp.DotNet.DotNetProjectSystem Added 8 and removed 0 file references [info]: OmniSharp.DotNet.DotNetProjectSystem Added 89 and removed 0 documents. [info]: OmniSharp.MSBuild.MSBuildProjectSystem MSBUILD_EXE_PATH environment variable set to /Users/wangchong/.vscode/extensions/ms-vscode.csharp-1.8.0-beta1/bin/omnisharp/msbuild/MSBuild.dll [info]: OmniSharp.MSBuild.MSBuildProjectSystem MSBuildExtensionsPath environment variable set to /Users/wangchong/.vscode/extensions/ms-vscode.csharp-1.8.0-beta1/bin/omnisharp/msbuild [info]: OmniSharp.MSBuild.MSBuildProjectSystem MSBuildSDKsPath environment variable set to /Users/wangchong/.vscode/extensions/ms-vscode.csharp-1.8.0-beta1/bin/omnisharp/msbuild/Sdks [info]: OmniSharp.MSBuild.MSBuildProjectSystem Detecting projects in '/Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Client.sln'. [info]: OmniSharp.MSBuild.MSBuildProjectSystem Loading project from '/Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Assembly-CSharp-firstpass.csproj'. Discovered Mono file path: /usr/local/bin/mono Resolved symbolic link for Mono file path: /usr/local/Cellar/mono/4.6.2.16/bin/mono-sgen [info]: OmniSharp.MSBuild.MSBuildProjectSystem Add project: /Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Assembly-CSharp-firstpass.csproj [info]: OmniSharp.MSBuild.MSBuildProjectSystem Loading project from '/Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Assembly-CSharp.csproj'. [info]: OmniSharp.MSBuild.MSBuildProjectSystem Add project: /Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Assembly-CSharp.csproj [info]: OmniSharp.MSBuild.MSBuildProjectSystem Loading project from '/Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Assembly-CSharp-Editor-firstpass.csproj'. [info]: OmniSharp.MSBuild.MSBuildProjectSystem Add project: /Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Assembly-CSharp-Editor-firstpass.csproj [info]: OmniSharp.MSBuild.MSBuildProjectSystem Loading project from '/Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Assembly-CSharp-Editor.csproj'. [info]: OmniSharp.MSBuild.MSBuildProjectSystem Add project: /Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Assembly-CSharp-Editor.csproj [info]: OmniSharp.MSBuild.MSBuildProjectSystem Update project: Assembly-CSharp-firstpass [info]: OmniSharp.MSBuild.MSBuildProjectSystem Update project: Assembly-CSharp [warn]: OmniSharp.MSBuild.MSBuildProjectSystem Unable to resolve assembly '/Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Temp/bin/Debug/Assembly-CSharp-firstpass.dll' [info]: OmniSharp.MSBuild.MSBuildProjectSystem Update project: Assembly-CSharp-Editor-firstpass [warn]: OmniSharp.MSBuild.MSBuildProjectSystem Unable to resolve assembly '/Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Temp/bin/Debug/Assembly-CSharp-firstpass.dll' [info]: OmniSharp.MSBuild.MSBuildProjectSystem Update project: Assembly-CSharp-Editor [warn]: OmniSharp.MSBuild.MSBuildProjectSystem Unable to resolve assembly '/Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Temp/bin/Debug/Assembly-CSharp-Editor-firstpass.dll' [warn]: OmniSharp.MSBuild.MSBuildProjectSystem Unable to resolve assembly '/Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Temp/bin/Debug/Assembly-CSharp-firstpass.dll' [warn]: OmniSharp.MSBuild.MSBuildProjectSystem Unable to resolve assembly '/Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client/Temp/bin/Debug/Assembly-CSharp.dll' [info]: OmniSharp.Script.ScriptProjectSystem Detecting CSX files in '/Users/wangchong/Documents/SourceCode/DnH/DNF_Project_Client_11/trunk/Program/Client'. [info]: OmniSharp.Script.ScriptProjectSystem Could not find any CSX files [info]: OmniSharp.Startup Configuration finished.

you have .abs file?

**Comment by JoeRobich** [comment]
This could be an issue with O# on Mono. If this is still a problem, open an issue at https://github.com/OmniSharp/omnisharp-roslyn/issues.
