### ISSUE TITLE
The namespace *namespace* Already contains a definition for *Controller*

### ISSUE THREAD

**Issue by mjbvz** [dotnet/vscode-csharp#1402]
_From @Cnordbo on April 18, 2017 19:52_

- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|gitignore|codezombiech|0.5.0|
|vscode-express|Compulim|0.0.5|
|git-project-manager|felipecaputo|1.2.1|
|vscode-nuget-package-manager|jmrog|1.1.2|
|mssql|ms-mssql|0.3.0|
|csharp|ms-vscode|1.8.1|
|vscode-icons|robertohuertasm|7.5.1|
|gitblame|waderyan|1.3.0|;

---

Steps to Reproduce:

1. Create a new Controller (C#, MVC app, im using the template from "dotnet new react"
2. Delete the controller
3. Re-create it

Error: 
Says that it already exists, and shows an error in the UI

_Copied from original issue: Microsoft/vscode#24970_

**Comment by Cnordbo** [comment]
I will throw in a temp fix as well: **restart vscode**.

**Comment by DustinCampbell** [comment]
Invoking the "Restart OmniSharp" command will also fix it as a workaround.

**Comment by DustinCampbell** [comment]
This is probably a special case of https://github.com/OmniSharp/omnisharp-vscode/issues/785.

**Comment by ehajri** [comment]
Not sure if it is related to this issue, but I was playing with xUnit (install, uninstall, create diff project within the same solution, removed old xUnit, etc..).

dotnet info:
```
.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.2/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```


OmniSharp/C# version:
<img width="468" alt="screen shot 2017-11-17 at 7 36 13 pm" src="https://user-images.githubusercontent.com/1648916/32975615-a009deee-cbce-11e7-9733-07f4b59b571c.png">

Got this:
![rename error](https://user-images.githubusercontent.com/1648916/32975624-b49f1496-cbce-11e7-88b7-55bac4abbd81.png)

However, after restarting OmniSharp:
![after omni restart](https://user-images.githubusercontent.com/1648916/32975628-c0ec36ca-cbce-11e7-8107-9391bd77f916.png)

**Comment by ehajri** [comment]
It happened again. I just moved the entire solution into another file:
```
- Solution
 - .sln
 - project1
 - project2
```
To:
```
- Folder
 - Solution
  - .sln
  - project1
  - project2
```
and the same error `The namespace .. already contains a definition for ..`

**Comment by DustinCampbell** [comment]
cc @rchande

**Comment by Gaulomatic** [comment]
Any solution other than restarting OmniSharp? This is not critical but really annoying since OmniSharp needs a reasonable amount of time to restart on larger solutions.

**Comment by ethan-deng** [comment]
Restarting Omnisharp worked for me. Press CTRL + SHIFT + P, then select 'Restart Omnisharp' from the list

**Comment by ghandmann** [comment]
Since recently i get the same error/behavior for **every** new file with a new C# class i create. The moment i finish my `public class MyClass { }` ceremony i get the error `The namespace 'Blah' already contains a definition for 'MyClass'`. Restarting Omnisharp makes the error go away.

Adding another new class in the already existing file after restarting Omnisharp does not trigger the error again.

**Comment by BabyboB1994** [comment]
Had the same issue. Restarting the VS Code has fixed it.

**Comment by Kazinix** [comment]
It seems to happen when I connect my account for VSCode -- I use GitHub account. What's weirder is, after connecting/disconnecting the account, I have to test and restart VSCode twice or thrice for the problem to happen/not happen.  My test involves creating a .cs file then creating a class in that file.

I'm still trying to figure out if it has something to do with syncing OmniSharp settings.

**Comment by cossieB** [comment]
This happens every time I create a new class in a new file. Restarting OmniSharp works but it gets tedious really quickly. 

So I've had to resort to workarounds like creating my classes in bulk before restarting and putting related ones in the same file.

v1.25

**Comment by MrStLouis** [comment]
FWIW I was able to resolve the issue via the option `OmniSharp: Select Project` where any selection "fixed" it.

**Comment by blogcraft** [comment]
Every time I create, move, rename a class, interface etc. this happens... to be able to work I have to restart omnisharp 50 times a day....

**Comment by jano-petras** [comment]
This issue does not happen if a new .cs file is added from elsewhere, not from Visual Studio Code.
I use `touch MyNewFile.cs` from terminal. It appears in VS Code automatically, and adding class definition into this file does not cause this issue.

**Comment by mikadumont** [comment]
We've made lots of updates to the C# extension since this issue was filed. Please file a new issue if you're still experiencing this with updated logs.
