### ISSUE TITLE
Handle CREFs in Quick Info tooltips

### ISSUE THREAD

**Issue by richlander** [dotnet/vscode-csharp#1403]
This is what I see today in Code ... "see" XML for type references:

<img width="577" alt="screen shot 2017-04-18 at 1 18 49 pm" src="https://cloud.githubusercontent.com/assets/2608468/25151217/9c76e05c-2439-11e7-92bd-d0f9070c1f65.png">

This is what I see in VS for the same thing:

![image](https://cloud.githubusercontent.com/assets/2608468/25151241/b73698a6-2439-11e7-9718-0b711159a0ee.png)

Here's what I'd like:

Step 1 - Remove the XML experience - show me the type name (fully qualified is fine).
Step 2 - build a colorized experience like VS.
Step 3 - Profit.

I also note that the argument description is missing. That would be good to have, too, but is a different issue.

**Comment by JoeRobich** [comment]
For Roslyn LSP and O#, the CREF type name is now displayed as text.
