### ISSUE TITLE
Add Project View (Tree Explorer API)

### ISSUE THREAD

**Issue by Avatarchik** [dotnet/vscode-csharp#1442]
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:

## Actual behavior

Simple https://twitter.com/k_cieslak/status/798607133248016386, Hi! Can you do this? Or in which direction to dig to implement?

**Comment by DustinCampbell** [comment]
The API is still in preview, so we won't be able to use it yet.

**Comment by RichardD012** [comment]
@DustinCampbell is this something that will be able to pull in references outside of the current project or is that a VSCode proper issue/request?

I see in the latest beta builds you have added support for processing external references (https://github.com/OmniSharp/omnisharp-vscode/issues/963) but there really isn't a clear path on how to get this to work "properly".  Ideally if I load a csproj with an external reference it would load that into the solution tree.  I've tried to hack around this by creating symlinks and nesting accordingly and opening but the syntax highlight around the above referenced issue doesn't do what you'd expect it to do.  For instance, Project A references Project B and a error in project B fails.  In the problems dialog or even cmd+clicking in the code that calls Project B, the source file loaded shows compile issues.  If I go to a symlinked file in the file explorer, that file doesn't look to be processed and shows no syntax highlighting.

I don't really think this is the fault of omnisharp as much as how VSCode handles folders in general.  

Not sure if this is the right avenue to discuss but I didn't want to open a new issue if it wasn't even something you're capable of doing.

**Comment by DustinCampbell** [comment]
> @DustinCampbell is this something that will be able to pull in references outside of the current project or is that a VSCode proper issue/request?

This request is just about visualizing the csproj/sln that is loaded, which VS Code wouldn't do. So, it's definitely a request for us.

The work that I've recently done to make OmniSharp handle project references external to the currently opened folder would play into this. My vision of this project view would be to show all of the projects loaded by OmniSharp, even those loaded from outside of the current VS Code workspace.

**Comment by RichardD012** [comment]
Then it seems you and I shared the same vision.  I mentioned having a weird structure that I think is definitely me playing around with too much locally but currently the only real way is to put everything in a root directory above everything and assume your structure is correct below.  That *seems* to work and you can switch projects as to what is active.

**Comment by ambroselittle** [comment]
This issue seems more specific than mine but related, so I'll start here. 

Basically, if I tell VS which solution to load, I'd like it to filter the Explorer file list by that solution (similar to VS view vs All Files view). My repo happens to have multiple, tangentially related solutions. Anyhow, I used the built-in file exclusion list to achieve the desired result, but it occurred to me this might be a nice feature for this extension. Lemme know if I should open a different issue or if it's similar enough to just stay here. TIA.

**Comment by JoeRobich** [comment]
Closing as this feature can be found in the C# DevKit extension.
