### ISSUE TITLE
IntelliSense handles conditional references like non existing ones

### ISSUE THREAD

**Issue by Shekesh** [dotnet/vscode-csharp#1479]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0
```

VS Code version: 1.12.1
C# Extension version: 1.9.0

## Steps to reproduce
Add a conditional reference to your .csproj file like so
```
<Choose>
        <When Condition=" '$(Configuration)'=='Release' ">
          <ItemGroup>
            <PackageReference Include="SomeProject">
              <Version>1.0.6</Version>
            </PackageReference>
          </ItemGroup>
        </When>
        <When Condition=" '$(Configuration)'=='Debug' ">
           <ItemGroup>
            <ProjectReference Include="..\SomeProject\SomeProject.csproj" />
          </ItemGroup>
        </When>
  </Choose>
```
## Expected  behavior
IntelliSense optimally uses the Debug reference (project) to do it's work
(works in Visual Studio but not in Visual Studio Code)
Alternatively it should support the `<otherwise></otherwise>` tag if assuming 'Debug' as default configuration is not an option.
[https://msdn.microsoft.com/en-us/library/ms164282.aspx](url)

## Actual behavior
IntelliSense acts like there is no reference at all

**Comment by JoeRobich** [comment]
There have been a lot of changes to the O# project system since this issue was open. If you are still experiencing this issue, please reopen.
