### ISSUE TITLE
Wrong comment symbol used for markup when comment line with hotkey in razor based *.cshtm files

### ISSUE THREAD

**Issue by ivankarpey** [dotnet/vscode-csharp#1510]
currently if select some peace of markup in *.cshtml file and press comment hotkey it will be commented out with:

`<-- bla-bla-bal -->`

however Razor did still parse this markup, so this could couse exception and UI artifact.

So should be `@* bla-bla-ba *@`

env: latest vs code + C# ext. 1.10-beta4, Ubuntu 16.04

**Comment by JoeRobich** [comment]
Cannot reproduce with the current release.
