### ISSUE TITLE
omnisharp downloading .net 4.6.x failed

### ISSUE THREAD

**Issue by OliverLeitner** [dotnet/vscode-csharp#1523]
## Environment data
`dotnet --info` output:

```
C:\Program Files\dotnet>dotnet --info
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4
```

VS Code version: 1.12.2

C# Extension version:

`C:\Windows\Microsoft.NET\Framework64\v4.0.30319`

## Steps to reproduce

1. start visual studio code
2. install c# support
3. open any .cs file

## Expected  behavior

download omnisharp .net 4.6.x finished

## Actual behavior
```
Updating C# dependencies...
Platform: win32, x86_64

Downloading package 'OmniSharp (.NET 4.6 / x64)' failed (error code '407')
Failed at stage: downloadPackages
407

Finished
```

ive actually commented on a closed ticket about this a few minutes ago... (silly me...)

https://github.com/OmniSharp/omnisharp-vscode/issues/579#issuecomment-304590225

**Comment by DustinCampbell** [comment]
@OliverLeitner: Did this work before? Error code '407' is "proxy authentication required"

**Comment by DustinCampbell** [comment]
@OliverLeitner: Did you see my question above?

**Comment by OliverLeitner** [comment]
hi Dustin, just saw it now...

not at my workplace, yes, its auth required, which i actually provided, still no pass through...

**Comment by taranttini** [comment]
Open VS Code
Go to Menu:
- File / Preferences / Settings

add lines:
```javascript
    "http.proxy": "http://USERNAME:PASSWORD@PROXY_IP:PROXY_PORT",
    "http.proxyStrictSSL": false,
```

**Comment by JoeRobich** [comment]
Closing as acquisition has changed quite a bit since this issue was opened.
