### ISSUE TITLE
Introduce build configuration drop down

### ISSUE THREAD

**Issue by eByte23** [dotnet/vscode-csharp#1541]
Hi all,

Experience something the other day where I had and ifdef for when !DEBUG

The code that I had in there was incorrect. As expected it should compile and run in debug but when in release it did not.
I realised there is currently no way to set the mode to release in vscode.

I am happy to work on the solution, I was think of adding a mode selector in the bottom tray next to project selector.

Thoughts?

**Comment by DustinCampbell** [comment]
This is definitely something I want to do. It goes hand-in-hand with https://github.com/OmniSharp/omnisharp-vscode/issues/310 and should also include a way to pick target framework and architecture.

**Comment by christianrondeau** [comment]
Since this would have been very useful to me, I wanted to maybe suggest having at least a workspace setting for selecting the build configuration? It's not as practical but at the same time, defining a default build configuration would be useful anyway.

**Comment by JoeRobich** [comment]
For O#, the Configuration can be set in the omnisharp.json.  see https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options#msbuild
