### ISSUE TITLE
Rename tuple field

### ISSUE THREAD

**Issue by andy-hanson** [dotnet/vscode-csharp#1589]
## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     linuxmint
 OS Version:  18.1
 OS Platform: Linux
 RID:         linuxmint.18.1-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0-preview1-005977/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983
```

VS Code version: 1.14.0-Insider
C# Extension version: 1.10.0

## Steps to reproduce

* Paste this code:
```cs
int f((int a, int b) tuple) =>
	tuple.a + tuple.b;
```
* Try to rename `a`.

## Expected  behavior

Successful rename:
```cs
int f((int x, int b) tuple) =>
	tuple.x + tuple.b;
```

## Actual behavior

`No result.`

I can't get it to work by renaming the access either.

**Comment by filipw** [comment]
This is blocked by https://github.com/dotnet/roslyn/issues/14115

**Comment by DustinCampbell** [comment]
Right. I don't believe this works in VS either.

**Comment by JoeRobich** [comment]
Closing as this is an external issue.
