### ISSUE TITLE
Make use of tasks-api

### ISSUE THREAD

**Issue by jrieken** [dotnet/vscode-csharp#1608]
Since [today](https://github.com/Microsoft/vscode/issues/29835) and with the June release, VS Code will have API to programmatically contribute and refine tasks. With that API parts of the asset-generator should become obsolete. Feel free to ping me or @dbaeumer or drop some details about how the task.json is generated today and we might be able to do a PR for that.

**Comment by DustinCampbell** [comment]
Awesome -- thanks @jrieken!

**Comment by JoeRobich** [comment]
The C# DevKit makes use of the tasks api.
