### ISSUE TITLE
Add option to support project load warnings

### ISSUE THREAD

**Issue by Hsn723** [dotnet/vscode-csharp#1610]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4
VS Code version: 1.13.1
C# Extension version: 1.11.0
## Steps to reproduce
Set `"omnisharp.loggingLevel": "critical"` in user settings.
Load a project that has some warnings (ex: Roslyn).

## Expected  behavior
No warnings shown, only critical items.

## Actual behavior
I constantly get `warn` messages saying "Some projects have trouble loading. Please review the output for more details."

Alternatively, an option to turn off logging would also be good.

**Comment by DustinCampbell** [comment]
The `"omnisharp.loggingLevel"` setting controls the output of the OmniSharp server in the OmniSharp Log. It doesn't control the message that appears in C# for VS Code to alert the user that there was a problem processing the project. That really isn't related to logging behavior -- it's about letting the user know that the extension likely isn't going to work properly for a particular project. Does that make sense?

That said, adding an option to suppress project load warnings is a good request.

**Comment by Hsn723** [comment]
Ah yes, that makes sense thanks for the clarification. And yes such an option would be pretty appreciated :)

**Comment by JoeRobich** [comment]
The C# extension now supports project load warning notifications.
