### ISSUE TITLE
[question] Can we generate a missing function?

### ISSUE THREAD

**Issue by jabbalaci** [dotnet/vscode-csharp#1613]
Say I call a function and I want to implement it right after. Can VS Code generate a half-ready function from my function call? Eclipse had this feature and I miss it. Thanks.

**Comment by DustinCampbell** [comment]
Yes, this works in C# for VS Code:

![image](https://user-images.githubusercontent.com/116161/27844097-9d3fe694-60d1-11e7-956f-f3c290b637f1.png)

**Comment by jabbalaci** [comment]
Thanks! It was not obvious and this is how it works for me: the missing method is underlined in red. If I click on the method's name, a light bulb icon appears left to the line numbers. Clicking on this icon "extract method" and "generate method" appear in a popup, as shown on the screenshot in the previous answer.

**Comment by DustinCampbell** [comment]
Excellent!
