### ISSUE TITLE
Find-all-references for `[Foo]` does not show reference to `FooAttribute`

### ISSUE THREAD

**Issue by andy-hanson** [dotnet/vscode-csharp#1639]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     linuxmint
 OS Version:  18.1
 OS Platform: Linux
 RID:         linuxmint.18.1-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0-preview1-005977/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983
```
VS Code version: 1.15.0-Insider
C# Extension version: 1.11.0

## Steps to reproduce

```cs
using System;

class FooAttribute : Attribute {}

class C
{
	[Foo]
	void m() {}

	void n(FooAttribute f) {}
}
```

Find-all-references at `Foo`.

## Expected  behavior

Find all 3 references.

## Actual behavior

Only get references to `[Foo]` and the definition for `FooAttribute`, but not the use `FooAttribute f`.

**Comment by filipw** [comment]
The reason is `[Foo]` is a constructor symbol not a type symbol, so finding references to it doesn't return the usages of `FooAttribute` type. Instead it would be fine here:

```csharp
    class FooAttribute : Attribute { }

    class C
    {
        [Foo]
        void m() { }

        void n() { var x = new FooAttribute(); }
    }
```

@DustinCampbell Visual Studio behaves the same way, it won't find inline usages of an attribute type from the annotation, it would however report constructor usages. So all things considered, is this something we ought to be addressing in OmniSharp?

**Comment by DustinCampbell** [comment]
@fillipw: I'd be surprised if VS works that way. If it does, it'd be a bug (@Pilchie, is that the case?). VS (and Roslyn) "cascades" between type and constructor symbols. When I looked at OmniSharp, it appeared to have it's own logic for Find All References rather than using the Roslyn API.

**Comment by filipw** [comment]
at least this is what I see in VS when the caret is on `[Foo]`:

<img width="515" alt="screenshot 2017-07-24 15 23 45" src="https://user-images.githubusercontent.com/1710369/28525325-18a9ed90-7084-11e7-82e9-3a4bbd42a791.png">

on the other hand, when moving to `FooAttribute` parameter, find references finds everything correctly:

<img width="471" alt="screenshot 2017-07-24 15 24 24" src="https://user-images.githubusercontent.com/1710369/28525406-6c2a12a6-7084-11e7-871b-a6902ddd600f.png">

**Comment by Pilchie** [comment]
Today we do a FAR to the *constructor*, and that doesn't cascade to the type, though it does cascade in the reverse direction.  See https://github.com/dotnet/roslyn/issues/3225.

**Comment by DustinCampbell** [comment]
OK. So that's consistent with @filipw's screenshots.

**Comment by JoeRobich** [comment]
This could be an issue with the O# server. If it is still a problem, please open an issue at https://github.com/OmniSharp/omnisharp-roslyn/issues
