### ISSUE TITLE
F12 won't take some of the classes in Libraries to their definition provided by metadata

### ISSUE THREAD

**Issue by cateyes99** [dotnet/vscode-csharp#1656]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1
```
VS Code version: `1.14.2`
C# Extension version: `1.11.0`

## Steps to reproduce
1. Create some code in a C# class like this:
```C#
List<int> il;
IList<int> il2;
```
2. Hit <kbd>F12</kbd> on `List<int>` and `IList<int>` separately.
## Expected  behavior
Both should jump to the definition provided by their **metadata**

## Actual behavior
Only for `IList<int>` it will jump to the definition provided by **metadata** as below, but `List<int>` won't, instead shows a bubble saying `No definition found for 'List'`!
```C#
namespace System.Collections.Generic
{
    //
    // Summary:
    //     Represents a collection of objects that can be individually accessed by index.
    //
    // Type parameters:
    //   T:
    //     The type of elements in the list.
    [DefaultMember("Item")]
    public interface IList<T> : ICollection<T>, IEnumerable<T>, IEnumerable
    {
        //
        // Summary:
        //     Gets or sets the element at the specified index.
```

**Comment by DustinCampbell** [comment]
This is working for me in a .NET Core console app. Do you have a project that you could provide that reproduces the issue?

**Comment by cateyes99** [comment]
Here is one, thx
[OmnisharpF12Test.zip](https://github.com/OmniSharp/omnisharp-vscode/files/1167110/OmnisharpF12Test.zip)

**Comment by DustinCampbell** [comment]
Thanks! I can reproduce this on OSX.

**Comment by kadkin** [comment]
+1

**Comment by JoeRobich** [comment]
Cannot reproduce with the latest release.
