### ISSUE TITLE
Unit tests aren't running when clicking on "Run Test" 

### ISSUE THREAD

**Issue by danielransom100** [dotnet/vscode-csharp#1666]
## Environment data
`dotnet --info` output: 

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4

VS Code version: 1.0.4
C# Extension version: 1.110

## Steps to reproduce
Go to unit test.
Click on Run Test

## Expected  behavior
Unit test runs

## Actual behavior
Error Debugger is Null

Omnisharp Error:
```[fail]: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware
An unhandled exception has occurred: Only one usage of each socket address (protocol/network address/port) is normally permitted
System.Net.Sockets.SocketException (0x80004005): Only one usage of each socket address (protocol/network address/port) is normally permitted at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at OmniSharp.DotNetTest.TestManager.Connect()
   at OmniSharp.DotNetTest.Services.BaseTestService.CreateTestManager(String fileName)
   at OmniSharp.DotNetTest.Services.BaseTestService`2.Handle(TRequest request)
   at OmniSharp.Middleware.Endpoint.EndpointHandler`2.<HandleSingleRequest>d__18.MoveNext()
```

**Comment by DustinCampbell** [comment]
Seems like it's failing in OmniSharp here: https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.DotNetTest/TestManager.cs#L97

A couple of questions:
* Is there anything particular about your setup that might make sockets fail?
* Your repro instructions are a bit confusing. "Error Debugger is Null" should never appear if you specifically click "run test"

**Comment by danielransom100** [comment]
Hi Dustin.

Nothing in particular would be different in my setup. 

It seems to fall over when I click Debug test first and then try and run the test afterwards. 

If it helps I'm using xUnit for tests. I've added the VS Code GUI Error below
![issue](https://user-images.githubusercontent.com/9955238/28630851-51d888ce-7223-11e7-8560-2969b9dd2499.PNG)

**Comment by DustinCampbell** [comment]
Are you waiting for "debug test" to finish before clicking "run test"?

**Comment by mmulhearn** [comment]
I'm seeing this as well.  Seems to occur if a `Debug Test` errors out.  Would seem that resources are not cleaning up.  If you wait a few minutes, eventually `Debug Test` works again.

**Comment by mmulhearn** [comment]
Still seeing this and it's making debugging extremely painful.  Closing all instances of VSCode doesn't fix it and I can't nail down a process I should terminate to resolve.

```
Failed to start debugger: "System.Net.Sockets.SocketException (0x80004005): Only one usage of each socket address (protocol/network address/port) is normally permitted\r\n   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)\r\n   at System.Net.Sockets.Socket.Bind(EndPoint localEP)\r\n   at OmniSharp.DotNetTest.TestManager.Connect() in D:\\a\\1\\s\\src\\OmniSharp.DotNetTest\\TestManager.cs:line 117\r\n   at OmniSharp.DotNetTest.Services.BaseTestService.CreateTestManager(String fileName) in D:\\a\\1\\s\\src\\OmniSharp.DotNetTest\\Services\\BaseTestService.cs:line 24\r\n   at OmniSharp.DotNetTest.Services.DebugTestService.Handle(DebugTestGetStartInfoRequest request) in D:\\a\\1\\s\\src\\OmniSharp.DotNetTest\\Services\\DebugTestService.cs:line 34\r\n   at OmniSharp.Endpoint.EndpointHandler`2.<GetFirstNotEmptyResponseFromHandlers>d__19.MoveNext() in D:\\a\\1\\s\\src\\OmniSharp.Host\\Endpoint\\EndpointHandler.cs:line 198\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at OmniSharp.Endpoint.EndpointHandler`2.<HandleRequestForLanguage>d__20.MoveNext() in D:\\a\\1\\s\\src\\OmniSharp.Host\\Endpoint\\EndpointHandler.cs:line 230\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at OmniSharp.Endpoint.EndpointHandler`2.<Process>d__16.MoveNext() in D:\\a\\1\\s\\src\\OmniSharp.Host\\Endpoint\\EndpointHandler.cs:line 131\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at OmniSharp.Stdio.Host.<HandleRequest>d__13.MoveNext() in D:\\a\\1\\s\\src\\OmniSharp.Stdio\\Host.cs:line 215"
```

**Comment by gregg-miskelly** [comment]
This isn't my area of expertise, but looking at [the code](https://github.com/OmniSharp/omnisharp-roslyn/blob/07141ba5604a9256f6cf3136197d95326b5b8610/src/OmniSharp.DotNetTest/TestManager.cs#L194) I don't see anything wrong -- it is asking the OS for a free port, and then using it.

My guess: do you have some sort of network security or VPN software installed? Are you on Windows?

Unfortunately the Windows ecosystem has a lot of network security software that breaks sockets. So if you are on Windows and have anything like that running I would try disabling it and see if this issue goes away.

**Comment by mmulhearn** [comment]
Hi @gregg-miskelly, yes I'm on Windows 10.  I don't think its a security issue.  The test runner does run, but then something under the hood happens and it no longer does and results in that error.  If I leave it alone, it'll correct itself, like it's getting disposed and releasing resources or something.  Not sure.

**Comment by schaveyt** [comment]
@gregg-miskelly - disabling my company's VPN did the trick for me on this. yay!

**Comment by JoeRobich** [comment]
@danielransom100 Are you still able to reproduce this on latest builds? If so, can you provide more information? Thanks

**Comment by JoeRobich** [comment]
Closing as this could be an O# issue. If this is still a problem, open a new issue at https://github.com/OmniSharp/omnisharp-roslyn/issues
