### ISSUE TITLE
High CPU usage on every modification to a buffer

### ISSUE THREAD

**Issue by peppy** [dotnet/vscode-csharp#1675]
## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.4
```

VS Code version: Version 1.15.0-insider (1.15.0-insider)
C# Extension version: 1.11.0

## Steps to reproduce

- Load https://github.com/ppy/osu (or other medium-sized project).
- Open any `.cs` file and make a change in the buffer (add a newline).

## Expected  behavior

- CPU should remain relatively idle.

## Actual behavior

- After a few seconds, CPU usage will increase for 5-20 seconds (`mono.osx` using 400-500% CPU).

While this does not affect interactions with the UI, on a laptop, developing using VSCode + OmniSharp results in around 2 hours battery, while using Visual Studio 2015 in a VM gets over 8 hours. I can reproduce this across multiple machines.

The only way to avoid this is to unload OmniSharp.

**Comment by JoeRobich** [comment]
This could be an issue with O# running on Mono. If it is still a problem, open a new issue at https://github.com/OmniSharp/omnisharp-roslyn/issues
