### ISSUE TITLE
Consider auto-restore or no restore

### ISSUE THREAD

**Issue by richlander** [dotnet/vscode-csharp#1731]
I frequently open up Code at a spot on disk that has multiple .NET Core projects. I imagine many people do this. When that happens, I see many requests to restore projects. It would be great if that didn't happen, particularly since restore is no longer important with the .NET Core 2.0 SDK.

I imagine that restore is required to provide intellisense. Is it possible to have a setting that auto restores, potentially not until first click into a .cs (or pick your lang) file within a given directory with a .NET Core msbuild file?

The C# plug-in downloads a pile of stuff to my machine for its own purposes automatically already, so it would be great if restore was the same.

**Comment by DustinCampbell** [comment]
Auto-restore is fairly a large and tricky endeavor that I would not be able to get to any time soon. That said, you might just consider setting the `csharp.suppressDotnetRestoreNotification` VS Code setting to true. That way, you don't get any restore messages at all and can control it manually.

**Comment by richlander** [comment]
I'll do that.

W/o restore, will I still get intellisense for .NET Core types but just not NuGet dependencies?

**Comment by DustinCampbell** [comment]
You will get IntelliSense for references that MSBuild is able to resolve. I expect that without an assets file, that would be nothing.

**Comment by DustinCampbell** [comment]
Note: This is also related to https://github.com/OmniSharp/omnisharp-vscode/issues/141, which might improve your experience quite a bit. That issue is about batching the restore prompts better so that you don't get individual prompts for each project.

**Comment by DustinCampbell** [comment]
One final comment: performing a restore is about getting the correct references to the C# compilation in order to provide _any_ IDE functionality at all. It's not just about IntelliSense. An un-restored project will have no navigational features (Go To Definition, Find All References), squiggles will appear everywhere, etc., etc.

**Comment by richlander** [comment]
> performing a restore is about getting the correct references to the C# compilation in order to provide any IDE functionality at all

Makes sense. Yes, my comment about intellisense was way too narrow.

> This is also related to #141, which might improve your experience quite a bit. 

Yes, that would be a big step forward.

**Comment by forki** [comment]
Dotnet restore in the background is a very important feature. Given that VS2017 and Ionide support it, I think OmniSharp should do it in vscode as well.

**Comment by Deilan** [comment]
Yep, that's a crucial one. :)

**Comment by kyro-dev** [comment]
Will this be implemented?

**Comment by JoeRobich** [comment]
Closing as auto restore is supported.
