### ISSUE TITLE
XUnit debug of non-public class produces unreasonable error message

### ISSUE THREAD

**Issue by inossidabile** [dotnet/vscode-csharp#1737]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```
VS Code version: 1.15.1 (1.15.1)
C# Extension version: 1.12.1

## Steps to reproduce
I have a ASP.NET Core MVC project with the following folders in root:
```
/app - application itself
/app/app.csproj
/test - xunit-based test suite
/test/test.csproj
```

This is the contents of `/test/test.csproj`:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="xunit" Version="2.2.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\app\app.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="xunit.runner.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
```

With this I create a very basic test:
```
class Test {
  [Fact]
  public void Test() {
    var controller = ... // breakpoint here
    ...
  }
}
```

That leads to method receiving active links: "run test, debug test". Then I press "debug test".

## Expected  behavior

Project builds and then debug fails somehow pointing out that the requested test entry is not found.

## Actual behavior

Project builds successfully but then says "Error processing launch options at field: program" offering to edit `launch.json` which is quite misleading.

**Comment by DustinCampbell** [comment]
Thanks for doing a bit more investigation and updating the title. That definitely helps narrow down the issue.

**Comment by pnloyd** [comment]
@DustinCampbell I'm getting this same `Error processing launch options at field: program` when debugging a project that does not use xUnit. I've gotten this message on both vscode.csharp v1.12.0 and v1.13.0 beta3. Is this likely the same problem or maybe something else I'm doing wrong? (I so far haven't been able to debug anything without this error)

# Environment
`
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
`

VS Code version: 1.16.1
C# Extension version: 1.13.0 beta3

**Comment by JoeRobich** [comment]
Unable to reproduce with the current release.
