### ISSUE TITLE
IntelliSense errors in ASP.NET Core 2.0, targeting full .NET Framework

### ISSUE THREAD

**Issue by dsteinweg** [dotnet/vscode-csharp#1750]
I'm getting IntelliSense errors while attempting to author an ASP.NET Core 2.0 application on Windows, targeting the full .NET Framework (not .NET Core).  IntelliSense tells me I need to add a reference to `netstandard, Version=2.0.0.0`, which seems odd, as .NET Standard is an "interface" not an implementation.  If anything I'd expect it to instruct me to add a reference to `mscorlib` or something. The project builds and runs just fine from the command line.

I've uploaded a repro project here, which includes screenshots:  [https://github.com/dsteinweg/vscode-netcore2](https://github.com/dsteinweg/vscode-netcore2)

Hopefully this is the right place for this issue, and hopefully I'm not just missing something simple.  Thanks in advance, loving the full ecosystem of .NET Core tooling!

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

VS Code version: `1.15.1 41abd21afdf7424c89319ee7cb0445cc6f376959`, 64-bit
C# Extension version: `1.12.1`

## Steps to reproduce

1. Create a new ASP.NET Core 2.0 project on Windows with `dotnet new web`
2. Change the TargetFramework in .csproj to `net461` or `net47`
3. Remove `Microsoft.AspNetCore.All` PackageReference (this new meta-package only seems to apply if you're targeting .NET Core)
4. Add PackageReferences for `Microsoft.AspNetCore` and `Microsoft.AspNetCore.Mvc`, version 2.0.0

## Expected  behavior
VS Code IntelliSense works as you'd expect, with hover support, "dotted" completion, etc.

## Actual behavior
VS Code IntelliSense shows red squiggly errors, mentioning that you must add a reference to `netstandard, Version=2.0.0.0`.

**Comment by DustinCampbell** [comment]
Thanks for the clear repro steps. I can definitely reproduce this issue. Taking a look...

**Comment by DustinCampbell** [comment]
Hmmm... I was able to repro it once but couldn't repro it again after performing a dotnet restore from the command line.

**Comment by DustinCampbell** [comment]
Ah, I see the difference. If I load it from a VS 2017 Developer Command Prompt, it works fine because MSBuild loads its toolset from VS 2017.

**Comment by dsteinweg** [comment]
Could it be that the version of MSBuild.exe that is installed with OmniSharp doesn't support .NET Core/Standard 2.0..?

I see this in the OmniSharp Log:
```
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Omnisharp will use local MSBuild.
    MSBUILD_EXE_PATH: C:\Users\dsteinweg\.vscode\extensions\ms-vscode.csharp-1.12.1\.omnisharp\msbuild\MSBuild.exe
    MSBuildExtensionsPath: C:\Users\dsteinweg\.vscode\extensions\ms-vscode.csharp-1.12.1\.omnisharp\msbuild
```
Sadly I can't execute MSBuild.exe at that location to call `--version` or equivalent [0], but the Details tab from right-click Properties shows File version of `15.3.388.41745`, Product version `15.3.388-preview+g11a3c31abc`.

By contrast, MSBuild.exe in the VS2017 15.3 installation folder at C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin shows File version `15.3.409.57025`, Product version `15.3.409+gc1de301405`, which seems to be a higher version than OmniSharp's MSBuild.

[0]:
```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Main()
```

**Comment by DustinCampbell** [comment]
OmniSharp contains a bare-bones MSBuild that's a bit older. I'm updating that to see if it addresses the problem.

Normally, OmniSharp will try to locate VS 2017 on your box and use the MSBuild there if possible. However, it appears that isn't working. Could you try launching VS Code form your VS 2017 Developer Command Prompt? That should give OmniSharp the context it needs to locate the MSBuild within VS 2017.

**Comment by dsteinweg** [comment]
Aha!  That works!  I see this in the OmniSharp log now, it's using VS2017's MSBuild instead of OmniSharp's:
```
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        OmniSharp initialized with Visual Studio MSBuild.
```

And those red squigglies are gone.

Could it simply be that VS2017's MSBuild.exe isn't in my PATH?

**Comment by dsteinweg** [comment]
Hmm, adding `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin` to my path didn't cause OmniSharp to find VS2017's MSBuild.exe.

Maybe setting the MSBuildSdksPath in omnisharp.json, [as you indicated here](https://github.com/OmniSharp/omnisharp-vscode/issues/1727)...

**Comment by dsteinweg** [comment]
Hmm, didn't seem to help.  I tried 3 different values for `MSBuildSdksPath` in omnisharp.json at the root of my project, they all resulted in this error [0]:

- C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin
- C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0
- C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks


[0]:
```
Microsoft.Build.Exceptions.InvalidProjectFileException: The SDK 'Microsoft.NET.Sdk.Web' specified could not be found.  c:\github\vscode-netcore2\vscode-netcore2.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.LoadProject(String filePath, String solutionDirectory, String sdksPath, ILogger logger, MSBuildOptions options, ICollection`1 diagnostics, ImmutableArray`1& targetFrameworks)
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Create(String filePath, String solutionDirectory, String sdksPath, ILogger logger, MSBuildOptions options, ICollection`1 diagnostics)
   at OmniSharp.MSBuild.MSBuildProjectSystem.LoadProject(String projectFilePath)
```

**Comment by DustinCampbell** [comment]
Adding folders to your path wouldn't do the trick. Instead, you can set the following environment variables that MSBuild uses from the VS Developer Command Prompt:

* Set `VSINSTALLDIR` to your VS installation directory. From your comments above, it looks like that should be: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise`
* Set `VisualStudioVersion` to `15.0`

**Comment by DustinCampbell** [comment]
FWIW, I wouldn't recommend setting `MSBuildSdksPath` as I mentioned in that other thread. In this case, the person who filed the issue was using a highly customized set up.

**Comment by DustinCampbell** [comment]
This is just a workaround. I've discovered what the issue is, but need to spend some time considering what the best fix would be.

**Comment by dsteinweg** [comment]
Setting those two environment variables works!  That's a better workaround than launching Code from the Developer Command Prompt every time.  Thanks for the sleuthing Dustin, I'll be able to continue working in VS Code for now (yay!).

Since you were able to reproduce it initially on your machine, I take it that means it's not a machine-specific (mis-)configuration on our machines, and that there is an underlying problem somewhere?

Also, I've only been testing this on my Win7 work machine thus far, but I can try from my personal machine tonight (Ubuntu 16.04) to see if the same problem exists.  Of course, one can't install VS2017 on Linux, so I don't imagine this environment variable workaround would work.

**Comment by DustinCampbell** [comment]
Nope this isn't machine specific. It's related to a bunch of complexity added that allows .NET Framework TFMs to target netstandard2.0. I'm trying to figure out the best way to include this in OmniSharp.

No, the environment variable trick wouldn't work on Linux. It *might* (with many caveats) work if you have Mono 5.2.0 or later installed, but I haven't verified that.

**Comment by btory** [comment]
Any workarounds that don't rely on VS2017?

**Comment by stefan-schweiger** [comment]
I was experiencing the same issue and starting VS Code via the Developer Command Promt is working for me. But I've installed VS2017 and setting the environment variables doesn't do the trick for me.

```
SET VSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\
SET VisualStudioVersion=15.0
```

Are there any additional steps or things to consider when having installed multiple versions of Visual Studio?

**Comment by JoeRobich** [comment]
There have been lots of improvements since this issue was opened. Please open a new issue with logs if you are still running into this.
