### ISSUE TITLE
Completion: Use trigger character API to refine scenarios where the completion list is triggered on SPACE

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/vscode-csharp#1765]
https://github.com/Microsoft/vscode/issues/752

**Comment by DustinCampbell** [comment]
I think we've got the trigger character working. However, should we do something about the sort order per https://github.com/Microsoft/vscode/issues/35551?

**Comment by Novack** [comment]
Hello peps, any news on this? Thanks!

**Comment by JoeRobich** [comment]
A lot has improved with O# completion. Closing this out.
