### ISSUE TITLE
Omnisharp doesn't start up when c# project is in OneDrive folder with "File On-Demand" on

### ISSUE THREAD

**Issue by RickyLin** [dotnet/vscode-csharp#1825]
## Environment data
`dotnet --info` output: __2.0.2__
VS Code version: __1.17.2__
C# Extension version: __1.12.1__
Windows Version: __Windows 10 1709 (OS Build 16299.19)__ It has a new OneDrive feature "File On-Demand"

## Steps to reproduce
1. Close all VS Code windows/applications if any.
2. Make sure the OneDrive Setting "Files On-Demand" is on.
    ![image](https://user-images.githubusercontent.com/1393989/32204746-031b4380-be26-11e7-9203-164d80ef6f42.png)
3. Create a simple "Hello World" console app in OneDrive folder: `dotnet new console`
    ![image](https://user-images.githubusercontent.com/1393989/32204814-8e899d72-be26-11e7-89e4-efa02b73177c.png)
4. Open the new created project in VS Code, open "Program.cs" file

## Expected  behavior
OmniSharp should start up.

![image](https://user-images.githubusercontent.com/1393989/32204989-9a1281a8-be27-11e7-9126-d36dc06307c9.png)
I moved the "HelloWorld" project out of OneDrive folder, then it worked.

## Actual behavior
OmniSharp doesn't start up.

![image](https://user-images.githubusercontent.com/1393989/32204925-479f8678-be27-11e7-8e0e-e632c72f79f5.png)

Visual Studio 2017 has similar problem when a project is in OneDrive folder no matter if "File On-Demand" is on or off. I guess Omnisharp would not start up as long as the project is in OneDrive folder even if "File On-Demand" is off.

**Comment by DustinCampbell** [comment]
FWIW, this is probably an issue for VS Code and not OmniSharp or C# for VS Code. I would expect a fix to support OneDrive "File-On-Demand" would be handled invisibly for VS Code extensions. It looks like there has been some traffic in VS Code issues on this problem. @bpasero, @jrieken -- do you know anything about this?

**Comment by bpasero** [comment]
@DustinCampbell yes, we had to pull in a fix from libuv in order to get this right (see https://github.com/Microsoft/vscode/issues/27285). It should be fixed in VS Code since 1.17.2 though, so that is weird...

**Comment by DustinCampbell** [comment]
This is with OneDrive's new "Files-on-Demand" feature. Are you certain that's fixed?

**Comment by DustinCampbell** [comment]
FWIW, I had heard recently that OneDrive feature also doesn't work in VS. My assumption is that the feature just shipped more broadly

**Comment by bpasero** [comment]
> This is with OneDrive's new "Files-on-Demand" feature. Are you certain that's fixed?

Yes, I am. Unless another Windows or OneDrive update caused the bug to appear again. If that was the case however, we could hear about it in VS Code issue tracker very quickly. 

Is it possible to get an actual error message to understand what goes wrong?

**Comment by RickyLin** [comment]
@bpasero How can I get something such as logs or error messages from VS Code or OmniSharp? I opened output window and the dropdown only contains "Extensions", "Search", "Tasks" and "Git".

**Comment by RickyLin** [comment]
In addition, I only selected a few of OneDrive folders synchronized to local computer, this was configured before upgrading to Windows 10 1709 (was 1703).

**Comment by pmalecka** [comment]
Same on my end, vscode x64 1.18.0

**Comment by mmgil** [comment]
same situation here.

in VSCode and in Visual Studio Community 2017

**Comment by marco-carvalho** [comment]
i'm having this problem right now; when I open the solution with VSCode on Ubuntu, Omnisharp doesn't start, but when I do it on Windows, it works

**Comment by JoeRobich** [comment]
Closing as a lot has improved with VS Code and the C# extension since this issue was opened.
