### ISSUE TITLE
OmniSharp reports errors on opening a directory with templates that looks like csproj/cs files

### ISSUE THREAD

**Issue by evil-shrike** [dotnet/vscode-csharp#1894]
I open a directory with a yeoman generator. It contains several templates. One of templates is a csproj file. But it's not a valid csproj file as it has `<%` sections inside it (it's a template).
VSCode while opening that directory reports errors in output like this:
```
[warn]: OmniSharp.MSBuild.MSBuildProjectSystem
        Failed to load project file 'c:\Work\R-n-D\xfw3_webclient_tools\generator-croc-webclient\server\templates\_Server.csproj'.
c:\Work\R-n-D\xfw3_webclient_tools\generator-croc-webclient\server\templates\_Server.csproj(1,1)
Microsoft.Build.Exceptions.InvalidProjectFileException: The project file could not be loaded. Name cannot begin with the '%' character, hexadecimal value 0x25. Line 6, position 21.  c:\Work\R-n-D\xfw3_webclient_tools\generator-croc-webclient\server\templates\_Server.csproj ---> System.Xml.XmlException: Name cannot begin with the '%' character, hexadecimal value 0x25. Line 6, position 21.
```

It'd be nice to allow to mark a directory as "content" to tell VSCode not to parse files inside.

- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.026Z)

https://github.com/Microsoft/vscode/issues/39283

**Comment by rchande** [comment]
@evil-shrike Thanks for reporting this. This is probably something that we would want to fix in OmniSharp. It should probably just skip over projects with parse errors and revert to a "misc files" experience if you happen to open a .cs file in the same directory. Thoughts @DustinCampbell ?

**Comment by DustinCampbell** [comment]
@rchande : MSBuild doesn't really provide any information about parsing problems. Also, I think there are valid situations where a user might want skip over some set of projects/folders when those projects are perfectly valid. There are already requests for such a feature (such as https://github.com/OmniSharp/omnisharp-vscode/issues/1694)

Having a "miscellaneous files" experience for C# files that aren't included in a project is a good idea, but I think that's a feature that would have merit on it's own.

**Comment by JoeRobich** [comment]
The O# project loader could be updated to handle this more gracefully. If this is still a problem, please open an issue at https://github.com/OmniSharp/omnisharp-roslyn/issues
