### ISSUE TITLE
Still stuck on 407 (both dotnet and nuget CLI / Team fixed it)

### ISSUE THREAD

**Issue by tebeco** [dotnet/vscode-csharp#1896]
This issue was created when dotnet CLI was still in beta and i was asked to create the issue there.
As you can see it is now fixed for `dotnet.exe` and `nuget.exe`
So i am back here as we use VsCode at work and we have to 

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.3)

Product Information:
 Version:            2.0.3
 Commit SHA-1 hash:  12f0c7efcc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.3\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
```

VS Code version: Latest insider as of 
```
Version 1.19.0-insider
Commit 6e90f8995da4bd999e8983b8e480a34045c1dfcf
Date 2017-11-29T05:14:15.979Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

C# Extension version: `1.13.1`

## Steps to reproduce
* Setup a NTLM Proxy on your network
* Setup the proxy on windows settings
* Create a a csproj / sln (could be netcoreapp / standard / netfx)
* Use either `dotnet restore` or `nuget restore`
* works (both CLI read that windows settings (no magic EnvVar, wich is good)
* Install VsCode
* Open the previous solution 
* DO NOT SETUP PROXY IN VsCode
* Add C# Extension (works <== VsCode also fixed that because it was failling 1 year ago)
* Open the `Output` window
* Select `OmniSharp` (F1 > reload )
* then you might see C# trying to Download 2 zip for Omnisharp
* FAIL with 407 on the proxy 

## Expected  behavior
* Should works out of the box using windows proxy (it's a .pac file that change)
* DO NOT ASK for Env Var like `HTTP_PROXY` as it will mess with other tools

## Actual behavior
* Error Http 407 > try to go straight to internet without using Os Proxy Settings

## Workaround 
* Type the password in clear text in proxy settings like this :
`http://usename:password@proxyUrl:port`
Doing that in VsCode proxy settings + Reload VsCode and open a C# file will re-trigger the download and make it work

## Dilema
* Do i let the password in clear to get update ?
* Do i remove it and i do not update
* Do i tell my colleague the workaround so they can see other user password when the forget to Lock the computer ?

**Comment by rchande** [comment]
@tebeco Thanks for filing this. We have other plans around improving the omnisharp download process and will visit this at that time.

**Comment by tebeco** [comment]
hello @rchande 
I'm going through ny "github open issues list" and saw this one

I'm curious about that very old issue, as of today I'm not sure if the other suggested plan landed or not, I could not find alternative
* still have to set proxy in clear text
* change it when password change => or it will lock AD account because of "too many attempt" :(

**Comment by tebeco** [comment]
if the binaires are shipped as "dotnet tool"
Would it be possible to do like Fake or Paket for example that relies on nuget feed ?

and then the settings.json would allow us to specify a "nuget feed url"

the default value would obviously be
https://api.nuget.org/v3/index.json

multiple enhancement :
* you could change the feed to point to "preview channel"
* you could also add a "version" in the settings to "rollback" or test preview
* you could unpublish version
* user with proxy would just use their internal "nuget feed"
