### ISSUE TITLE
Suggest correct types when using new keyword

### ISSUE THREAD

**Issue by icyh4mmer** [dotnet/vscode-csharp#1898]
VS Code version:
1.18.1
C# Extension version:
1.13.1
## Steps to reproduce
For example, write "int[] intArray = new" and then press control + space, there is no int[] suggested.

## Expected  behavior
I would expect for "int[]" to pop out first like it does in visual studio.

## Actual behavior
Here is an image of current behaviour:
![image](https://user-images.githubusercontent.com/11890420/33394515-e22698c6-d542-11e7-9076-43bd53b6b463.png)

**Comment by DustinCampbell** [comment]
I believe `int[]` is in the list but it isn't selected. Is that correct? Otherwise, this is tracked with https://github.com/OmniSharp/omnisharp-vscode/issues/1765.

**Comment by icyh4mmer** [comment]
`int[]` is not in the list. Even if I suggest an int it won't suggest array: 
![image](https://user-images.githubusercontent.com/11890420/33424467-3cf64282-d5bc-11e7-911c-3212473d4528.png)

**Comment by DustinCampbell** [comment]
Actually, I was incorrect. Visual Studio (and thus VS Code) doesn't show `int[]` in the list. However, it should preselect `int` so that you can keep typing. That's the bit that is being tracked by #1765. Is that right @rchande?

**Comment by rchande** [comment]
@DustinCampbell Correct the trigger is wired up, but there's some more work to be done with preselection. Also, there's ongoing discussion with VSCode about whether they want to support a C#-style preselection experience. The only way to do something like preselection right now is to manipulate the sort text of your best item so it gets sorted to the top of the list. There's no support for what we do in VS where the list comes up scrolled to a particular item.

**Comment by rchande** [comment]
@akshita31 The appropriate VS Code API has been implemented for us to support this (https://github.com/Microsoft/vscode/issues/35551#issuecomment-398100658). Let's chat about what we need to do to get this feature working.

**Comment by JoeRobich** [comment]
Cannot reproduce on current release.
