### ISSUE TITLE
Unable to retrieve an unfiltered list of symbols in workspace.

### ISSUE THREAD

**Issue by craig006** [dotnet/vscode-csharp#1904]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

VS Code version: 1.18.1
C# Extension version: 1.13.0

## Steps to reproduce
1. Run this code from an extension in a C# project in VS Code:

```
commands.executeCommand('vscode.executeWorkspaceSymbolProvider', "").then(result => {
     console.log(result)           
})
```

## Expected  behavior
An **unfiltered** array of all symbols printed to the console.

## Actual behavior
Exception is thrown
```
Error: Running the contributed command:'vscode.executeWorkspaceSymbolProvider' failed. Illegal argument 'query' - Search string
codeActionProvider.js:249
    at e.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:411939)
    at e.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:411279)
    at Object.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:488349)
```

I have logged an issue with VS as well but seems like the error is not generated by vs code: https://github.com/Microsoft/vscode/issues/39522

## Desired outcome
Allow the user to select a symbol from any symbol in the current workspace and return the selected symbol to the executing code for further processing. So similar behaviour to `Go to symbol in workspace`, except don't navigate away to the file, rather return the result.

**Comment by DustinCampbell** [comment]
It looks like this fails in VS Code before C# for VS Code is called: https://github.com/Microsoft/vscode/blob/4b91235ba2c49da4b1a12b22d2ab046eb3f27b50/src/vs/workbench/api/node/extHostCommands.ts#L118. @jrieken: does that look right to you?

**Comment by jrieken** [comment]
Not sure... We have been there and as long as the parameter is a string, it should work. Our constraint is just defined just as a string: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostApiCommands.ts#L37

**Comment by jrieken** [comment]
That might be just us

**Comment by JalmarazMartn** [comment]
Still remains the same issue, A can´t find how to get an unfiltered list of symbols. Can I? is it possible now? Thanks in advance.

**Comment by JoeRobich** [comment]
This could be a VS Code issue. If this is still a problem, please open an issue at https://github.com/microsoft/vscode/issues
