### ISSUE TITLE
[BUG]从Unity 打开工程会出现报错

### ISSUE THREAD

**Issue by talentJian** [dotnet/vscode-csharp#1910]
## Environment data
`dotnet --info` output:
VS Code version:1.18.1
C# Extension version:1.13.1

## Steps to reproduce
从Unity里面点击打开C# 文件会出现错误
Open C# Project From Unity 2017.2.0 
如
 a namespace cannot directy contatin member such as fields or methods
Unexpected character '??'
Unexpected character '??'

但是当我随便输入一个字符，或者更改 LR/CRLF,这个文件就会突然正常。
但是关闭vs code 重新打开后，问题依然存在

**Comment by JoeRobich** [comment]
Please try the new Unity extension for VS Code. See https://code.visualstudio.com/docs/other/unity
