### ISSUE TITLE
Feature Request: Consume-First Mode

### ISSUE THREAD

**Issue by NakOh** [dotnet/vscode-csharp#1950]
## Environment data
`dotnet --info` output:

VS Code version: 1.19.1

C# Extension version: 1.13.1

## Steps to reproduce
![2018-01-04 11 02 11](https://user-images.githubusercontent.com/7420198/34547469-c0006f48-f13e-11e7-9d1c-c2082697365f.png)

I want to write only 'u' 

but recommend 'uint' 

So I put space, 

![2018-01-04 11 03 02](https://user-images.githubusercontent.com/7420198/34547482-d807dde2-f13e-11e7-92c9-87c05b215a16.png)

Help me.. I annoyed..

## Expected  behavior

![2018-01-04 11 03 31](https://user-images.githubusercontent.com/7420198/34547491-eb3e4266-f13e-11e7-8e76-380e05c24d1d.png)

i want only 'u'

**Comment by rchande** [comment]
This is a request for "suggestion mode" like Visual Studio has.

**Comment by TheRealPiotrP** [comment]
@DustinCampbell is this going to be covered by the upcoming Completion Service PR?

**Comment by DustinCampbell** [comment]
No. There will need to be some extra work to enable this.

**Comment by JoeRobich** [comment]
Cannot reproduce this in the current release.
