### ISSUE TITLE
Report lots of "The type or namespace name 'Azure' does not exist in namespace 'Microsoft'" in Azure Function .csx file

### ISSUE THREAD

**Issue by adashen** [dotnet/vscode-csharp#1959]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2\

Microsoft .NET Core Shared Framework Host
  Version  : 2.0.0  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```
VS Code version:

C# Extension version:
1.13.1

## Steps to reproduce
1. Follow the steps in https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-deploy-function#create-a-function-project to create a .csx azure function. 
2. Lots of errors like the following shown in problem tab
 'The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?) 
'The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?) 
![csx](https://user-images.githubusercontent.com/1872137/34867186-339443ae-f7ba-11e7-94d4-74d097d14edc.png)

## Expected  behavior
Based on https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-csharp#referencing-external-assemblies These references are valid, so there should not be errors

**Comment by rchande** [comment]
Thanks @adashen. We'll take a look.

**Comment by DustinCampbell** [comment]
cc @filipw as well

**Comment by rchande** [comment]
This is actually an issue with the azure function template. It doesn't include a csproj or project.json, so there's no way to run nuget restore. @TheRealPiotrP Do we have any contacts in azure functions?

**Comment by adashen** [comment]
@rchande  I could also reproduce this issue in a simple .csx script (not a azure function)
![image](https://user-images.githubusercontent.com/1872137/37729028-15bd101c-2cf9-11e8-984a-7744e50f09b6.png)

The code just ref a nuget package AutoMapper, 6.2.2. And the code could run, but the intellense does not work.

**Comment by bertique** [comment]
@rchande, same issue here as well. Getting this in log

`
[info]: OmniSharp.Script.ScriptProjectSystem
        Found 1 CSX files.
[info]: OmniSharp.Script.ScriptProjectSystem
        Searching for compilation dependencies with the fallback framework of 'net46'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Unable to find dependency context for CSX files. Will default to non-context usage (Desktop CLR scripts).
`

**Comment by DustinCampbell** [comment]
@filipw: Any thoughts here?

**Comment by shizn** [comment]
@rchande Do we have an ETA for this issue?

**Comment by rchande** [comment]
Ping @filipw

**Comment by filipw** [comment]
We do not support Azure Functions at the moment - this is tracked by https://github.com/OmniSharp/omnisharp-roslyn/issues/779.

The other stuff (support for #r "nuget:...") that should work out of the box, as long as  .NET SDK is installed on the machine.

If something is not working, it would be great to get the repro script and the full OmniSharp debug output - thanks!

**Comment by 401asfg** [comment]
Was a solution ever found? I'm having the exact same problem, except with:

using Azure.Core.Pipeline;
using Azure.DigitalTwins.Core;
using Azure.DigitalTwins.Core.Serialization;
using Azure.Identity;

**Comment by ameypimpley** [comment]
My guess of the issue is that the older KeyVault package (v3) has an internal dependency on an earlier storage package version. My belief would be to update KeyVault to V4 which we are previewing alongside the Storage V12 library. Below are pointers to the libraries.

$> dotnet add package Azure.Storage.Blobs --version 12.0.0-preview.4
$> dotnet add package Azure.Storage.Blobs.Batching --version 12.0.0-preview.4
$> dotnet add package Azure.Storage.Queues --version 12.0.0-preview.4
$> dotnet add package Azure.Storage.Files --version 12.0.0-preview.4

$> dotnet add package Azure.Security.KeyVault.Secrets --version 4.0.0-preview.5
$> dotnet add package Azure.Security.KeyVault.Keys --version 4.0.0-preview.5
$> dotnet add package Azure.Security.KeyVault.Certificates --version 4.0.0-preview.5

**Comment by JoeRobich** [comment]
There have been lots of improvements since this issue was opened. Please open a new issue with logs if you are still running into this.
