### ISSUE TITLE
Wrong autocomplete for predicates

### ISSUE THREAD

**Issue by squalsoft** [dotnet/vscode-csharp#1974]
## Environment data
`dotnet --info` output:
```
Программы командной строки .NET (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

VS Code version:
C# Extension version:
1.13.0
## Steps to reproduce
Type ( in collections and then letter c.

## Expected  behavior
No intellisense suggestions

## Actual behavior
Autocomplition for c = char. And if i type "c=>c." it will complete with "c=>char". How to disable that?

<img width="767" alt="2018-01-23 14 43 24" src="https://user-images.githubusercontent.com/1629660/35275841-1b2c4276-0052-11e8-9538-a6e82a8f075c.png">

**Comment by DustinCampbell** [comment]
@rchande : This *should* work, as we've got special code in completion that will avoid setting SPACE as a commit character if OmniSharp reports that we're in suggestion mode: https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/features/completionItemProvider.ts#L68-L70. (That is, if the completion API returns a list with a `SuggestionModeItem`.)

**Comment by JoeRobich** [comment]
Could not reproduce this behavior with the current release.
