### ISSUE TITLE
Adopt VSCode 1.20's new CodeAction type

### ISSUE THREAD

**Issue by mjbvz** [dotnet/vscode-csharp#1981]
VS Code 1.20 adds a new [`CodeAction`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L1897) type that attaches additional metadata to code actions. This additional information will be used in a few places in VS Code:

* `CodeAction.kind` describes the kind of a code action (extract refactoring, quickfix, ...) Kinds are used for VS Code's new `refactor` command, and they are used to [setup keybindings for specific code actions](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_20.md#keybindings-for-quick-fixes-and-code-actions)

* `CodeAction.diagnostics` tells which errors a quickfix addresses. This is used to order quickfixes by severity

I suggest that you migrate this extension's `CodeActionProvider` to use the new `CodeAction` type in order to enable support for these new features. It should be fairly straightforward change, and I can submit a PR that does this once VS Code 1.20 is released

Please let me know if you have any question or concerns about the CodeAction API

**Comment by JoeRobich** [comment]
CodeActionProvider uses the CodeAction type.
