### ISSUE TITLE
VS Code does not load "header" information for local references on Mac High Sierra

### ISSUE THREAD

**Issue by geoeo** [dotnet/vscode-csharp#1988]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

VS Code version:
C# Extension version:

## Steps to reproduce -Edited
create sln `dotnet add Test.sln`

open current folder `code .`

create a local project `dotnet new console CONSOLE` in a folder e.g. CONSOLE/
create a local library `dotnet new library LIB` in a folder e.g. LIB/

add the LIB as reference to CONSOLE `dotnet add CONSOLE reference LIB`
restore via `dotnet restore`

## Expected  behavior

The vs code project should have header information loaded immediately to correctly reference namespaces/autocomplete etc.

## Actual behavior

Build compiles! BUT namespaces in references project are incorrectly flagged by vs code as not present. 

After adding the namespace, referencing the namespace and building vs code will eventually load the referenced namespace

Thank you for this tool.

Best,
Marc

**Comment by DustinCampbell** [comment]
@geoeo: I'm using macOS High Sierra and can't repro this issue. Could you provide your OmniSharp Log from VS Code after opening your project?

**Comment by geoeo** [comment]
How do I do that?

Best, Marc

**Comment by DustinCampbell** [comment]
1. In VS Code, load your project
2. Select View->Output from the menu.
3. In the Output pane, select "OmniSharp Log" from the dropdown in the top-right corner.

**Comment by geoeo** [comment]
## OmniSharp Log

Starting OmniSharp server at 2018-2-1 21:54:48
    Target: /Users/marchaubenstock/Workspace/DotNet/Test/Test.sln

OmniSharp server started wth Mono
    Path: /Users/marchaubenstock/.vscode/extensions/ms-vscode.csharp-1.13.1/.omnisharp/omnisharp/OmniSharp.exe
    PID: 537

﻿[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 10.13.3 (x64)
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 15.0 - "/Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/msbuild/15.0/bin"
            2: StandAlone 15.0 - "/Users/marchaubenstock/.vscode/extensions/ms-vscode.csharp-1.13.1/.omnisharp/omnisharp/msbuild/15.0/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 15.0 - "/Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/msbuild/15.0/bin"
            CscToolPath = /Users/marchaubenstock/.vscode/extensions/ms-vscode.csharp-1.13.1/.omnisharp/omnisharp/msbuild/15.0/Bin/Roslyn
            CscToolExe = csc.exe
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/marchaubenstock/Workspace/DotNet/Test'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in /Users/marchaubenstock/Workspace/DotNet/Test
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.MSBuildProjectSystem
        Detecting projects in '/Users/marchaubenstock/Workspace/DotNet/Test/Test.sln'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/marchaubenstock/Workspace/DotNet/Test'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Stdio.Host
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Stdio.Host
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/marchaubenstock/Workspace/DotNet/Test' on host 512.

## Addendum

For me this is completely reproducible.  I think the important part is that vs code **has to be open** while the commands are entered in the shell. If I close vs code and open in again, all name spaces are correctly loaded.

<img width="356" alt="screen shot 2018-02-01 at 22 11 08" src="https://user-images.githubusercontent.com/1128542/35703579-d5690e20-079c-11e8-8765-795f2740fec3.png">


<img width="1039" alt="screen shot 2018-02-01 at 22 06 39" src="https://user-images.githubusercontent.com/1128542/35703555-b7c926c0-079c-11e8-856e-759ca197682a.png">

<img width="1036" alt="screen shot 2018-02-01 at 22 06 46" src="https://user-images.githubusercontent.com/1128542/35703564-c63c88dc-079c-11e8-99cc-5804f4126898.png">

**Comment by DustinCampbell** [comment]
Thanks for the additional information. This is actually working as designed, though it's not very intuitive. The OmniSharp server doesn't locate new projects as their added on disk. However, you can force it to reload by using the "OmniSharp: Restart OmniSharp" command is VS Code or, as you discovered, simply restarting.

**Comment by geoeo** [comment]
Thanks for "OmniSharp: Restart OmniSharp".

**Comment by cartermp** [comment]
Re-tagging this as a project system problem.

**Comment by JoeRobich** [comment]
Closing as answered.
