### ISSUE TITLE
F12 in Linux opens terminal instead of Go To Definition by default

### ISSUE THREAD

**Issue by vsccarl** [dotnet/vscode-csharp#2019]
## Environment data
`dotnet --info` output: 
```
CLI: 2.1.4
Commit: 5e8add2190
.NET Core 2.0.5
Build: 17373eb129b05aa18ece963f8795d65ef8ea54
Runtime: ubuntu 16.04 x64
```
VS Code version: `1.20.0`
C# Extension version: `1.14.0-beta4`

## Steps to reproduce
1. Open a C# file/project
2. Highlight a method call
3. Press F12

## Expected  behavior
Goes to definition

## Actual behavior
By default in Linux pressing F12 opens up a terminal window.

**Comment by DustinCampbell** [comment]
Thanks for pointing this out @vsccarl.

@rchande: This issue should probably be moved to the VS Code repo. We don't define this command or keybinding in C# for VS Code.

**Comment by JoeRobich** [comment]
Closing as this appears to be an issue with VS Code keybindings.
