### ISSUE TITLE
No omnisharp log when opening folder only containing sln file that references a outside csproj

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/vscode-csharp#2024]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

VS Code version: 1.20.0
C# Extension version: 1.40.beta4

## Steps to reproduce
In a console window:
dotnet core new console -n proj1
md tempSln
cd tempSln
dotnet new sln -n tempSln
dotnet sln add "..\proj1\proj1.csproj
Open vscode
Open the folder containing just the sln file. (tempSln)
## Expected  behavior
Folder is opened, Omnisharp log is available and the proj1 is loaded as well.

## Actual behavior
Log isn't available. No way to tell if the project is loaded.

**Comment by rchande** [comment]
This might be a (minor) but. Theoretically, package.json says we should get activated if there's a .sln present in the folder.

**Comment by JoeRobich** [comment]
extension activation now requires a .csproj to be beneath the open folder not just a .sln file. Closing as designed.
