### ISSUE TITLE
Trailing semicolon prevents signature help from displaying

### ISSUE THREAD

**Issue by vsccarl** [dotnet/vscode-csharp#2025]
## Environment data
`dotnet --info` output: 
```
CLI: 2.1.4
Commit: 5e8add2190
.NET Core 2.0.5
Build: 17373eb129b05aa18ece963f8795d65ef8ea54
Runtime: Windows 10 / ubuntu 16.04 x64
```
VS Code version: `1.20.0`
C# Extension version: `1.14.0-beta4`

## Steps to reproduce
In a C# file add this code
`Console.WriteLine;`
Add opening parenthesis bracket in front of the semicolon

## Expected  behavior
Signature help should give you some information about `Console.WriteLine()`

## Actual behavior
The trailing semicolon is preventing the dialog from being presented. This case works correctly in VS.

**Comment by JoeRobich** [comment]
Cannot reproduce with the current release.
