### ISSUE TITLE
T4 Template Support

### ISSUE THREAD

**Issue by mika76** [dotnet/vscode-csharp#2031]
## Environment data
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

VS Code version: 1.20

## Expected  behavior
T4 templates could run whenever there is a change to the .tt file just like in Visual Studio. 

## Actual behavior
Nothing?

**Comment by rchande** [comment]
@mika76 Thanks for the suggestion. Note that C# extension for VS Code doesn't have real-time support for other file generators, like .resx, either.

**Comment by mika76** [comment]
@rchande Thanks. Maybe it would be better to rename this issue to "File Generator Support"?

**Comment by JoeRobich** [comment]
Closing as T4 support is not planned. The C# extension currently support Source Generators.
