### ISSUE TITLE
Where can I set environment variable for test from codelens?

### ISSUE THREAD

**Issue by Thaina** [dotnet/vscode-csharp#2033]
I try to run unittest with codelens. If I run unittest from vscode I could write test command in `tasks.json` to set env variable that will execute on launch. Is there equivalence functionality for pressing codelens command?

**Comment by rchande** [comment]
@Thaina Unfortunately, I don't think that's currently possible.

**Comment by Thaina** [comment]
@rchande Did your unittest command or nuget itself would read some config file in the project that contain env var and/or other config on their own?

Another thing I would like is to set output file. If it not possible would you pleased to include in that config file feature?

**Comment by JoeRobich** [comment]
![Image](https://github.com/user-attachments/assets/b97c08e5-2bdd-4c89-a23f-b223f57cfb60)
You can configure a .runsettings file to be used when running your unit tests. In the .runsettings file you can configure environment variables. See https://learn.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2022#specify-environment-variables-in-the-runsettings-file
