### ISSUE TITLE
OmniSharp.exe uses 10 GB RAM and 50% CPU

### ISSUE THREAD

**Issue by UnderHeavyDevelopment** [dotnet/vscode-csharp#2041]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

VS Code version: 1.20.1
C# Extension version: 1.14

## Steps to reproduce
Edit C# code with Visual Studio Code

## Expected  behavior
Low CPU and RAM usage

## Actual behavior
Unacceptable

![vscc](https://user-images.githubusercontent.com/3192279/36257535-9ccd641a-1257-11e8-813f-22c5ccd9c05b.png)

**Comment by rchande** [comment]
@UnderHeavyDevelopment Can you comment on the size of your project?

**Comment by UnderHeavyDevelopment** [comment]
@rchande It is round 100 projects (.csproj) and about 10k LOC. In Visual Studio 2017 runs smoothly. In VS Code I had this issue once so far and after restart OmniSharp.exe was about 500 MB memory. Looks like sudden memory leak loop.

**Comment by yuribudilov** [comment]
FWIW - I have some dumps (Windows 10, 64-bit) exhibiting similar bad behavior re leaking memory and chewing up CPU, see my Issue if interested in the dumps. My project is extremely simple using the latest versions of everything.

**Comment by UnderHeavyDevelopment** [comment]
Similar issue https://github.com/OmniSharp/omnisharp-vscode/issues/1913

**Comment by rchande** [comment]
@UnderHeavyDevelopment I would appreciate it if you could capture a trace to help me analyze what's happening. Please use PerfView to capture ~30 seconds when you see this high-CPU + memory allocation (http://www.philosophicalgeek.com/2012/07/16/how-to-debug-gc-issues-using-perfview/), upload the trace to OneDrive (or equivalent) and send me a link at Ravi.Chande@microsoft.com.  Thanks!

**Comment by riezebosch** [comment]
<img width="728" alt="screen shot 2018-09-12 at 15 43 52" src="https://user-images.githubusercontent.com/1427334/45429018-b60c0b80-b6a2-11e8-97a0-e74e12570396.png">
The fan of my MacBook starts to spin like crazy when having VSCode open.

**Comment by bakintunde** [comment]
Hi, 

I'm also experiencing this issue now with Visual Studio Code while editing/running C# code on max os x

@rchande How could I get more stats/info required for further investigation?

Find below the output of dotnet --info on my computer as well

`.NET Core SDK (reflecting any global.json):
 Version:   2.1.402
 Commit:    3599f217f4

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.402/

Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

.NET Core SDKs installed:
  1.0.0-preview2-003131 [/usr/local/share/dotnet/sdk]
  1.0.0-preview2-1-003177 [/usr/local/share/dotnet/sdk]
  2.0.0 [/usr/local/share/dotnet/sdk]
  2.1.3 [/usr/local/share/dotnet/sdk]
  2.1.4 [/usr/local/share/dotnet/sdk]
  2.1.301 [/usr/local/share/dotnet/sdk]
  2.1.302 [/usr/local/share/dotnet/sdk]
  2.1.402 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download`

**Comment by fiigii** [comment]
I'm also experiencing this issue when I developing https://github.com/dotnet/coreclr

**Comment by riezebosch** [comment]
The issue (for me) seems to be related to dotnet itself and not this extension. In the meantime, I switched to Rider and also to another (older model) MacBook and once in a while, my fan starts to blow like crazy. All I have to do then is invoke a `killall dotnet` and everything is smoothing down within seconds.

**Comment by vitek-karas** [comment]
Reliable repro for this problem (on Windows):
Clone the dotnet/coreclr repo.
Build it - follow the instructions how to build the repo. (without building it OmniSharp seems to work OK).
Open VS Code and point it to the root of the coreclr repo.
Wait a couple minutes - OmniSharp process is using one core 100% and grows memory seemingly indefinitely (had to kill it when it reached cca 10 GB).

**Comment by rchande** [comment]
@vitek-karas Since you're on Windows, can you please record a trace with perfview and share it with me?

**Comment by fiigii** [comment]
Don't you guys have a plan to replace mono by .NET Core? AFAIK, mono's compiler and runtime is not good for performance...

**Comment by vitek-karas** [comment]
@rchande any instructions how to take the trace? (perfview has way too many options for me to know what you need).

**Comment by jcreek** [comment]
I've been experiencing similar behaviour on Linux, crashing my original PC. Now upgraded and found the same issue. The project works totally fine in Visual Studio on a virtual machine with significantly less RAM.

**Comment by vitek-karas** [comment]
I would love to help get this fixed... can you please let us know what kind of trace you're looking for?
(Also - I still think that it would be much easier for you to work with actual live repro  -which is very easy to setup using the coreclr repo mentioned above).

**Comment by 23phy** [comment]
Are there any updates regarding this issue?

**Comment by cartermp** [comment]
There's no updates to share at this time. I expect that this will be a very difficult and time-consuming problem to make progress on, if the performance work done for Visual Studio is any indication.

**Comment by ffMathy** [comment]
I am experiencing this too. Any progress?

Mine is a .NET 5 project with around 10K lines of code.

Latest Omnisharp, latest VS Code.

**Comment by markusschaber** [comment]
Do you happen to have the SonarLint plugin installed? Maybe this is related to: https://community.sonarsource.com/t/omnisharp-using-tons-of-memory-while-using-rider/61184

**Comment by ffMathy** [comment]
Yes, I did at the time. That makes sense then.

**Comment by jcreek** [comment]
I did not have SonarLint installed, so the issue has been present for me without that.

**Comment by lixaotec** [comment]
+1

**Comment by Cerberus1746** [comment]
Yeah, I have the exact same issue.

![Screenshot_2022-11-11_17-37-24](https://user-images.githubusercontent.com/291051/201427956-68a1c404-3d44-4b24-8813-5f42f4c6e0a0.png)

I don't think it should be using more CPU and memory than an entire game engine.

**Comment by Cerberus1746** [comment]
> Yeah, I have the exact same issue.
> 
> I don't think it should be using more CPU and memory than an entire game engine.

Did some more testing, it seems like the culprit in my case is the Async Completion. Disabled it and the usage is more reasonable.

**Comment by lixaotec** [comment]
> > Yeah, I have the exact same issue.
> > I don't think it should be using more CPU and memory than an entire game engine.
> 
> Did some more testing, it seems like the culprit in my case is the Async Completion. Disabled it and the usage is more reasonable.

How to disable Async Completion?

**Comment by Cerberus1746** [comment]
> How to disable Async Completion?

In the settings of the C# extension, there's a option called "[BETA] Async completion." or something like that.

**Comment by SlashScreen** [comment]
I too have SonarLint and it's made everything so much worse

**Comment by JoeRobich** [comment]
There have been lots of improvements since this issue was opened. Please open a new issue with logs if you are still running into this.
