### ISSUE TITLE
"new" Keyword suggestion only working on non-generic class

### ISSUE THREAD

**Issue by potterdai** [dotnet/vscode-csharp#2044]
## Environment data
`dotnet --info` output:
VS Code version: 1.20.1
C# Extension version: 1.14.0

## Steps to reproduce
`List<string> l = new ` -> suggest `string` instead of `List<string>()`
`TestClass tc = new ` -> suggest `TestClass` as expected
So `new` keyword suggestion only works on non-generic class

**Comment by JoeRobich** [comment]
Cannot reproduce with the current release.
