### ISSUE TITLE
Unable to debug test using code lens with net46 framework 

### ISSUE THREAD

**Issue by preetipadalia** [dotnet/vscode-csharp#2055]
We are trying to debug the nunit test in VScode in net46 framework but even if change the target framework from netcoreapp2.0 to net46 it still picking the dll present inside netcoreapp2.0 folder.

Test -> f:\Automation_Framework\12022018\GTS_CS_FWK\Test\bin\Debug\net46\Test.dll

Build succeeded.
0 Warning(s)
0 Error(s)

Time Elapsed 00:00:00.79

NUnit Adapter 3.9.0.0: Test discovery starting
NUnit Adapter 3.9.0.0: Test discovery complete
[xUnit.net 00:00:00.9136379] Discovering: Test
[xUnit.net 00:00:00.9341569] Discovered: Test
Started debugging process #14184.
NUnit Adapter 3.9.0.0: Test execution started
Debugging selected tests in f:\Automation_Framework\12022018\GTS_CS_FWK\Test\bin\Debug\netcoreapp2.0\Test.dll
NUnit3TestExecutor converted 1 of 1 NUnit test cases
NUnit Adapter 3.9.0.0: Test execution complete
Debugging complete.

If we remove the folder netcoreapp2.0 then unable to debug the code.

kindly help.

thanks

**Comment by rchande** [comment]
Note that this doesn't appear to work in Visual Studio either. @pp1609 Is your csproj an "SDK" project?

**Comment by gregg-miskelly** [comment]
If your scenario fits within the limitations on Desktop .NET Framework debugging (see [here](https://github.com/OmniSharp/omnisharp-vscode/wiki/Desktop-.NET-Framework)), then you can make this work by opening your VS Code preferences file and adding `"csharp.unitTestDebuggingOptions.type": "clr"`.

**Comment by pp1609** [comment]
Hi @gregg-miskelly thanks for the reply. I tried the solution u suggested but not able to proceed with the debugging.
I am getting "Error processing launch options at field: program" error now.

**Comment by gregg-miskelly** [comment]
Sounds like there are multiple issues then. This means that the extension didn't provide the program to launch to the debugger.

**Comment by SSK00111** [comment]
Is there a plan to fix this issue. Any workaround for this yet?

**Comment by toebens** [comment]
i also can not start debugging a nunit3 unit test via code lens in vs code (using net472 or netcoreapp2.2). 

BTW calling "Run test" via code lens also isn't working

**Comment by JoeRobich** [comment]
A lot has changed with debugging and testing since this issue was opened. Please reopen with current details if it is still a problem.
