### ISSUE TITLE
While solving merge conflicts in .cs files with C# addon enabled "Accept changes" bar dissapears.

### ISSUE THREAD

**Issue by adamulicki** [dotnet/vscode-csharp#2076]
## Environment data
`dotnet --info` output:
```
Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

VS Code version:  1.20.1
C# Extension version: 1.14.0

## Steps to reproduce
While solving merge conflicts in VS code with C# extension enabled. (tested with .cs files)

## Expected  behavior
The bar with "Accept Current Change | Accept Incoming Change..."  appears, is constantly visible and buttons are clicable.

## Actual behavior
 Bar blinks breafly and dissapears. Disabling C# extension fixes this issue. (bar is constantly visible).

**Comment by markau** [comment]
Confirming this bug. VSCode 1.21.1 (32 bit)

````
Product Information:
 Version:            2.1.2
 Commit SHA-1 hash:  5695315371

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
````

**Comment by DustinCampbell** [comment]
I've noticed this as well. I wonder if VS Code is waiting for the C# extension to initialize (which it probably shouldn't). @jrieken: is there an appropriate person on VS Code who could help us look at this?

**Comment by jrieken** [comment]
We shouldn't wait but @joaomoreno would know

**Comment by joaomoreno** [comment]
This is the merge extension by @chrmarti

**Comment by chrmarti** [comment]
Sounds like the C# extension does something that triggers a bug in the presentation. The merge-conflict extension does not have any listeners that would trigger on another extension, so it seems this is an issue in the core.

Does the C# extension add any decorations or code lenses? What if these are disabled?

**Comment by DustinCampbell** [comment]
@chrmarti: We do add code lens for references and running/debugging tests.

@adamulicki: Do you still see this problem if you change the following settings like so?

```
"csharp.referencesCodeLens.enabled": false
"csharp.testsCodeLens.enabled": false
```

**Comment by adamulicki** [comment]
Will confirm tomorrow.

**Comment by adamulicki** [comment]
Issue is still present with those 2 options unfortunately.

**Comment by chrmarti** [comment]
Could you share a file that reproduces the problem? (I tried with a simple example, but it did not show the reported issue.)

**Comment by adamulicki** [comment]
Faced this issue in multiple .cs files throughout a multi-project solution. It was not file specific, every .cs file with a conflict reproduced the issue. Anything in the solution that I could look for?

**Comment by DustinCampbell** [comment]
@chrmarti : It's all about the size of what's being loaded. I see this when editing merge conflicts in https://github.com/dotnet/roslyn.

**Comment by rowandh** [comment]
Confirming this still exists with VS Code 1.25.1 and C# Extension 1.15.2

**Comment by JoeRobich** [comment]
Cannot reproduce with latest release.
