### ISSUE TITLE
Unity Project have some trouble. 

### ISSUE THREAD

**Issue by NakOh** [dotnet/vscode-csharp#2088]
## Environment data

`dotnet --info` output:
```
Product Information:
 Version:            2.1.2
 Commit SHA-1 hash:  5695315371

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.2/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
```
VS Code version:

Version 1.20.1(1.20.1)

C# Extension version:

1.14.0

## Steps to reproduce

Open Project -> 

![2018-03-05 9 42 58](https://user-images.githubusercontent.com/7420198/36952984-e07fb202-2059-11e8-963a-41c5f722fec5.png)

## Expected  behavior

Don't Error

## Actual behavior

Log : 
```
Starting OmniSharp server at 2018-3-5 09:42:49
    Target: /Users/minsookim/GitHub/PlayHoldemClient/PlayHoldemClient.sln

OmniSharp server started wth Mono
    Path: /Users/minsookim/.vscode/extensions/ms-vscode.csharp-1.14.0/.omnisharp/omnisharp/OmniSharp.exe
    PID: 1766

﻿[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 10.13.2 (x64)
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 15.0 - "/Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/msbuild/15.0/bin"
            2: StandAlone 15.0 - "/Users/minsookim/.vscode/extensions/ms-vscode.csharp-1.14.0/.omnisharp/omnisharp/msbuild/15.0/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 15.0 - "/Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/msbuild/15.0/bin"
            CscToolPath = /Users/minsookim/.vscode/extensions/ms-vscode.csharp-1.14.0/.omnisharp/omnisharp/msbuild/15.0/Bin/Roslyn
            CscToolExe = csc.exe
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/minsookim/GitHub/PlayHoldemClient'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Initializing in /Users/minsookim/GitHub/PlayHoldemClient
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Auto package restore: False
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Update workspace context
[info]: OmniSharp.DotNet.DotNetProjectSystem
        Resolving projects references
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/Users/minsookim/GitHub/PlayHoldemClient/PlayHoldemClient.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/minsookim/GitHub/PlayHoldemClient/Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/minsookim/GitHub/PlayHoldemClient/Assembly-CSharp-firstpass.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/minsookim/GitHub/PlayHoldemClient/Assembly-CSharp-Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/minsookim/GitHub/PlayHoldemClient/Assembly-CSharp-Editor-firstpass.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/minsookim/GitHub/PlayHoldemClient'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/minsookim/GitHub/PlayHoldemClient/Assembly-CSharp.csproj
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.Stdio.Host
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.Stdio.Host
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/minsookim/GitHub/PlayHoldemClient' on host 1744.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/minsookim/GitHub/PlayHoldemClient/Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/minsookim/GitHub/PlayHoldemClient/Assembly-CSharp-firstpass.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/minsookim/GitHub/PlayHoldemClient/Assembly-CSharp-firstpass.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/minsookim/GitHub/PlayHoldemClient/Assembly-CSharp-Editor.csproj
[warn]: OmniSharp.MSBuild.ProjectLoader
        The referenced project 'Assembly-UnityScript-Editor-firstpass.csproj' does not exist.
/Users/minsookim/GitHub/PlayHoldemClient/Assembly-CSharp-Editor.csproj

[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/minsookim/GitHub/PlayHoldemClient/Assembly-CSharp-Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/minsookim/GitHub/PlayHoldemClient/Assembly-CSharp-Editor-firstpass.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/minsookim/GitHub/PlayHoldemClient/Assembly-CSharp-Editor-firstpass.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Assembly-CSharp
[warn]: OmniSharp.MSBuild.ProjectManager
        Unable to resolve assembly '/Users/minsookim/GitHub/PlayHoldemClient/Temp/bin/Debug/Assembly-CSharp-firstpass.dll'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Assembly-CSharp-firstpass
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Assembly-CSharp-Editor
[warn]: OmniSharp.MSBuild.ProjectManager
        Unable to resolve project reference '/Users/minsookim/GitHub/PlayHoldemClient/Assembly-UnityScript-Editor-firstpass.csproj' for 'Assembly-CSharp-Editor'.
[warn]: OmniSharp.MSBuild.ProjectManager
        Unable to resolve assembly '/Users/minsookim/GitHub/PlayHoldemClient/Temp/bin/Debug/Assembly-CSharp-Editor-firstpass.dll'
[warn]: OmniSharp.MSBuild.ProjectManager
        Unable to resolve assembly '/Users/minsookim/GitHub/PlayHoldemClient/Temp/bin/Debug/Assembly-CSharp-firstpass.dll'
[warn]: OmniSharp.MSBuild.ProjectManager
        Unable to resolve assembly '/Users/minsookim/GitHub/PlayHoldemClient/Temp/bin/Debug/Assembly-CSharp.dll'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Assembly-CSharp-Editor-firstpass
[warn]: OmniSharp.MSBuild.ProjectManager
        Unable to resolve assembly '/Users/minsookim/GitHub/PlayHoldemClient/Temp/bin/Debug/Assembly-CSharp-firstpass.dll'
```

**Comment by NakOh** [comment]
Occurs after updating to the latest VS Code.

**Comment by rchande** [comment]
@NakOh If you `dotnet build` your project, are there any errors?

**Comment by DustinCampbell** [comment]
This looks like a Unity project rather than a .NET Core project, so I'd expect `dotnet build` to fail.

@NakOh: Have you tried building your Unity project?

**Comment by aohajin** [comment]
@DustinCampbell building the unity project will not help.

**Comment by DustinCampbell** [comment]
@aohajin : Why would it not help? Based on the error, my assumption is that the project is expecting to find a binary on disk that isn't present.

**Comment by NakOh** [comment]
How to build dotnet Build? 

.NET Core용 Microsoft (R) Build Engine 버전 15.5.179.9764
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1011: 사용할 프로젝트 또는 솔루션 파일을 지정하십시오. 이 폴더에 프로젝트 또는 솔루션 파일이 두 개 이상 있습니다.

It's korean.

It means. One More Project or Solution in Folder

And 

.NET Core용 Microsoft (R) Build Engine 버전 15.5.179.9764
Copyright (C) Microsoft Corporation. All rights reserved.

/Users/minsookim/GitHub/PlayHoldemClient/PlayHoldemClient.sln : 솔루션 파일 error MSB5004: 솔루션 파일에 이름이 "PlayHoldemClient"인 프로젝트가 두 개 있습니다.

빌드하지 못했습니다.

/Users/minsookim/GitHub/PlayHoldemClient/PlayHoldemClient.sln : 솔루션 파일 error MSB5004: 솔루션 파일에 이름이 "PlayHoldemClient"인 프로젝트가 두 개 있습니다.
    경고 0개
    오류 1개
It means Two Project in same file...

**Comment by DustinCampbell** [comment]
@NakOh: @rchande's suggestion won't work. Building a Unity project with `dotnet build` will not work. Have you tried building it with `xbuild` from your Mono installation?

**Comment by aohajin** [comment]
@DustinCampbell because the dll required was not at the place where omnisharp thought it should be..
for my case
![image](https://user-images.githubusercontent.com/502988/37700734-935f589e-2d27-11e8-8fcc-be479b701aac.png)

but Unity(5.6.5f1) actually put the dll here:
C:\xiimoon\Ngame\Library\ScriptAssemblies\Assembly-CSharp.dll

**Comment by DustinCampbell** [comment]
FWIW, to work with Unity, I recommend installing mono from brew like so:

```
brew cask install mono-mdk
```

rather than

```
brew cask mono
```

The latter does not include large swaths of Mono, including Mono's msbuild (which OmniSharp will use if present).

**Comment by Leopotam** [comment]
@DustinCampbell  standard `mono` package was broken half year ago, now it works, I use it instead of `cask mono-mdk`:
```
brew install mono
```

**Comment by DustinCampbell** [comment]
it works now? Cool! I haven't looked at it in quite awhile.

**Comment by Leopotam** [comment]
```
> brew info mono
mono: stable 5.4.1.6 (bottled)
```
+ 2 packages:
```
brew cask install dotnet
brew cask install dotnet-sdk
```

**Comment by DustinCampbell** [comment]
I just tried `brew install mono` and it still doesn't include Mono's MSBuild. So, installing the MDK is still needed to allow more project types to work with C# for VS Code. However, if it works for you -- great!

**Comment by Leopotam** [comment]
Well, it works for unity projects on osx, I dont care about vscode as standalone C# development editor, only as IDE-companion for unity.

**Comment by Leopotam** [comment]
@DustinCampbell btw, I checked omnisharp log, it filled with warnings too, but no errors and intellisense works correctly.

**Comment by NakOh** [comment]
OK. I installed 

brew install mono
brew cask instasll dotnet
brew cask install dotnet-sdk
brew cask install mono-mdk 

There was no problem with the original operation, but I was constantly concerned about this warning.

![2018-03-22 9 47 17](https://user-images.githubusercontent.com/7420198/37745059-1e5a155e-2db6-11e8-9812-fa7f010c78d2.png)

I will give up and just use vsCode..

**Comment by NakOh** [comment]
@Leopotam 
Yeah. No Error Yes Warning. 
I might ignore this problem.
but I do not want to see the warning.
Why should I look at the warning text that there are no problems?

i want to fix this problem..

**Comment by Leopotam** [comment]
I dont remember (I dont see any settings at my prefs about it), but there is "gear" button at notification window, maybe you can tweak this behaviour through some settings there?

**Comment by NakOh** [comment]
@Leopotam 
It is only a temporary solution, and I want a fundamental solution.
I hope that OmniSharp's Development Team will be able to solve this problem.

**Comment by Leopotam** [comment]
@NakOh ahaha, you have the sense of humor :D You can check last year of development in commits list - they fixed only unit-tests support, nothing more. All critical fixes were did by community PRs. So, if you want to see how MS-team works - you will die for age first. If you want to see solution - you should doing it by yourself and make PR.

**Comment by NakOh** [comment]
@Leopotam 
I am grateful for the good points and will try to solve the problem.
Thank you~

**Comment by rchande** [comment]
Hi @NakOh @Leopotam The warning about project load issues may or may not reflect a problem. OmniSharp raises this warning if there are actual issues loading the project, or if there are MSBuild warnings when building/restoring the project. We plan to fix this via https://github.com/OmniSharp/omnisharp-vscode/issues/2110. 

You can verify that these warnings are ignorable by building/restoring your project and seeing if there are any warnings or errors. If there are, this is what OmniSharp is prompting for. I agree that this behavior is annoying and that's why we plan to fix it.

**Comment by iambumblehead** [comment]
I've been trying to setup vscode for use with an existing project and am having the same issue as @aohajin [above][0].

My system, `Darwin x86_64`
mono: `5.10.1.47`
dotnet: `2.1.4`
VS Code C#: `1.15.2`

[0]: https://github.com/OmniSharp/omnisharp-vscode/issues/2088#issuecomment-374868443

**Comment by JamesYFC** [comment]
> ...
> I believe if you change your OutputPath in your .csproj files that should fix your problems, though!

@TheWanderingBen I tried this and it worked for a while, until those lines got switched back again in my .csproj files later on the same day :/
Is there a way to make the change permanently?

**Comment by MJLeeKor** [comment]
@NakOh It's so long time ago but for the others, 
just using 'Debugger for Unity' extension, since than everything is good.
 - I want to share this, because I took 3days for solving this, bye

**Comment by lugehorsam** [comment]
I use Debugger for Unity and still have this issue.

**Comment by LoranceChen** [comment]
warning still here after reinstall vscode and mono :-(
![image](https://user-images.githubusercontent.com/8775828/55524696-c3312c00-56c0-11e9-8143-d415febe3b3a.png)

I'm suppose a reference find fail problem affect by this one.
![image](https://user-images.githubusercontent.com/8775828/55524781-130ff300-56c1-11e9-800b-368d9a1acded.png)

Ready to abandon VS code for my Unity develop.

**Comment by Leopotam** [comment]
@LoranceChen its because `omnisharp-vscode` dev-team dont want to support updating `*.csproj` files in old format (before .net std) if you will add new `*.cs`-file right inside `vscode`. You can fix this behaviour with switching to `unity` (it should start compilation + `*.csproj`-files will be regenerated with links to new `*.cs`-files), then switch back to `vscode` and run command `reload window` from command palette. `vscode` will restart plugins and `omnisharp-vscode` will get new list of project `*.cs`-files.

**Comment by LoranceChen** [comment]
@Leopotam, Thanks. `reload window` fix the problem. But it's not a normal develop workflow.It seems VS Code not ready for Unity develop yet :-(

**Comment by Leopotam** [comment]
@LoranceChen shit happens, its my standard workflow on osx last 3 years. Custom codestyle formatting - same thing, no any progress from `omnisharp-vscode` team last 3 years :)
But `vs for mac` still worse than `vscode + omnisharp` - slower, consumes more resources, etc.
`JetBrains Rider` much better with code analytics, but worst IDE for performance reasons. But it will be my next choice if they will release community edition.

**Comment by schplorg** [comment]
> I'm getting the wrong directory issue too. dlls and such are expected to be in temp/bin, are actually in library/ScriptAssemblies instead.
> 
> > ...
> > I believe if you change your OutputPath in your .csproj files that should fix your problems, though!
> 
> @TheWanderingBen I tried this and it worked for a while, until those lines got switched back again in my .csproj files later on the same day :/
> Is there a way to make the change permanently?

I got it working by dropping a symbolic link of Library/ScriptAssemblies into Temp/bin named Debug.
It's possible via cmd or with this neat shell extension:
http://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html
It's a dirty hack and I wish someone could point me to the real solution to this issue ❤️

**Comment by JamesYFC** [comment]
> 
> 
> > I'm getting the wrong directory issue too. dlls and such are expected to be in temp/bin, are actually in library/ScriptAssemblies instead.
> > > ...
> > > I believe if you change your OutputPath in your .csproj files that should fix your problems, though!
> > 
> > 
> > @TheWanderingBen I tried this and it worked for a while, until those lines got switched back again in my .csproj files later on the same day :/
> > Is there a way to make the change permanently?
> 
> I got it working by dropping a symbolic link of Library/ScriptAssemblies into Temp/bin named Debug.
> It's possible via cmd or with this neat shell extension:
> http://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html
> It's a dirty hack and I wish someone could point me to the real solution to this issue ❤️

Nice solution.

Did you get it to last any decent amount of time?
My symlink keeps getting deleted.

**Comment by RunninglVlan** [comment]
@schplorg, for me symbolic links didn't help. It just removed "Unable to resolve assembly" warnings =(
I tried these commands: `mklink /J "c:\<project>\Temp\bin\Debug" "C:\<project>\Library\ScriptAssemblies"`, `mklink /D "c:\<project>\Temp\bin\Debug" "C:\<project>\Library\ScriptAssemblies"`
What's interesting, I have the same project at home and at work, and definitions started not working only at work. =(

**Comment by dvgco** [comment]
same issue for me, can not found the assembles in Temp/bin/Debug
so, the intellisense could not work.

**Comment by RunninglVlan** [comment]
Thanks, @filipw, adding `"omnisharp.path": "latest"` to global (user) settings.json fixed the issue.

**Comment by RunninglVlan** [comment]
v1.21.5 is out in the Marketplace 🎉

**Comment by filipw** [comment]
yes correct it was published yesterday 👍

**Comment by JoeRobich** [comment]
Please use the new Unity extension for VS Code. See details at https://code.visualstudio.com/docs/other/unity
