### ISSUE TITLE
Filter Intellisense, sort by most likely action wanted

### ISSUE THREAD

**Issue by ruant** [dotnet/vscode-csharp#2107]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```
VS Code version:
```
Version 1.21.0
Commit 9a199d77c82fcb82f39c68bb33c614af01c111ba
Date 2018-03-07T11:04:09.969Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```
C# Extension version: 1.14.0

## Steps to reproduce
```
public class TestModel {
  public string Test { get; set; }
}

public class Test {
  var model = new TestModel
  {
    [ctrl+space]
  }
}
```
## Expected  behavior
I would expect `Test` to be at the top of the list, since this is the most likely thing I'm after.

## Actual behavior
Alphabetically ordered list with A LOT of crappy suggestions.

**Comment by rchande** [comment]
Sounds like we need to implement "object initializer" completion like Roslyn has. @DustinCampbell Would this be covered by your CompletionService PR?

**Comment by DustinCampbell** [comment]
> @DustinCampbell Would this be covered by your CompletionService PR?

Yes.

**Comment by dubeg** [comment]
Would that be the issue for what's shown below..

**Visual Studio**
![vs-intellisence](https://user-images.githubusercontent.com/6020602/45589872-860b7500-b8fb-11e8-936e-9c5e0d308ef0.png)

**VS Code**
![vscode-intellisence](https://user-images.githubusercontent.com/6020602/45589876-93286400-b8fb-11e8-97e7-4924cccab821.png)

VS Code's list is full of keywords and snippets that I'm not particularly interested when in an object initializer

**Comment by ruant** [comment]
@dubeg
That's exactly what this is for. Thanks for the screenshots.

@rchande @DustinCampbell 
Any news on the PR? No PR number was mentioned.

**Comment by rchande** [comment]
@ruant That would be this PR: https://github.com/OmniSharp/omnisharp-roslyn/pull/884

**Comment by JoeRobich** [comment]
Closing as settable object properties are not sorted to the top of the completion list.
