### ISSUE TITLE
VSCode insists on complaining if dotnet cli is not on the path in non-dotnet project

### ISSUE THREAD

**Issue by tsalinger** [dotnet/vscode-csharp#2115]
>This issue has been moved from [Microsoft/vscode/](https://github.com/Microsoft/vscode/issues/44388)
Original author is <a href="/zivcaspi">
      <img class="avatar rounded-1" height="44" width="44" alt="@zivcaspi" src="https://avatars0.githubusercontent.com/u/3773221?s=88&amp;v=4">
    </a>@zivcaspi
---
### Issue Type
Bug

### Description

Open VSCode. If dotnet cli is not on the path, VSCode complains (even if there's nothing related to dotnet open). If some extension has failed, VSCode complains. In many cases, the console pane opens up automatically for apparently no reason (and with no relations to what I want to do with VSCode).

When I open VSCode with some file, I want to edit that file. I'm not interested in reconfiguring my system of learning about all things that various extensions complain about. Get them outside the view.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:33:21.935Z)
OS version: Windows_NT ia32 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|Memory (System)|31.91GB (18.10GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.13.0
vscode-rust|kal|0.4.2
codeshell|Kip|0.2.2
vscode-antlr4|mik|1.2.9
python|ms-|2018.1.0
cpptools|ms-|0.15.0
csharp|ms-|1.14.0
PowerShell|ms-|1.6.0

</details>
Reproduces only with extensions

---

**Comment by DustinCampbell** [comment]
@zivcaspi: You can disable this warning in your VS Code settings by setting `"csharp.suppressDotnetInstallWarning"` to `false`.

**Comment by zivcaspi** [comment]
Doesn't work -- I have this in my user settings, and I'm still getting this from the C# extension (ms-vscode.csharp). This happens even if there's no tab open on a .cs file, BTW. If VSCode thinks I'm in the context of some C# project, I'm getting this warning (now displayed on the bottom right). Strangely, there's no option to "close" the workspace while leaving the "scratch" tabs (editor tabs that I have not saved), so if I want to get rid of the "open a new instance of vscode, have this warning displayed" condition I need to either save the open editor tabs and explicitly close the default (sticky) workspace or complain :)

{
//...
"csharp.suppressDotnetInstallWarning" : false
}

**Comment by DustinCampbell** [comment]
Sorry, that was my bad. I said `false`, but it should have been `true`. You _want_ to suppress it.

**Comment by JoeRobich** [comment]
Closing as answered.
