### ISSUE TITLE
Download size is 6X bigger

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/vscode-csharp#2140]
The difference in size between 1.5.0-beta2 and 1.5.0-beta3 is 884 KB -> 5.67 MB. This is pretty significant! I'm assuming that this is the addition of rxjs. If that's the case, is there a smaller module that we can reference rather than the whole thing?

cc @TheRealPiotrP

**Comment by colombod** [comment]
Rx can be imported with the part needed instead of all of it.

**Comment by TheRealPiotrP** [comment]
Update: we removed some unnecessary dependencies and added a size release gate test. We are down to 3.2 mb and have a gate at 5. 2.5 mb of rxjs is still a lot, but we will need to explore bundling options to bring this down further. Vsce is very greedy...
