### ISSUE TITLE
Missing .NET Core metadata documentation in VS Code

### ISSUE THREAD

**Issue by lfr** [dotnet/vscode-csharp#2175]
## Environment data

![image](https://user-images.githubusercontent.com/6348118/38611850-2266affc-3d85-11e8-9094-4f2a43e0bc2b.png)

VS Code version:

![image](https://user-images.githubusercontent.com/6348118/38611819-0bb92988-3d85-11e8-96a5-e01ea9c5e185.png)

C# Extension version:

![image](https://user-images.githubusercontent.com/6348118/38611806-02bc8ff0-3d85-11e8-840d-82cd7af9cb8d.png)

## Steps to reproduce

Call a BCL class member within a method and place the cursor over it to get some member info.

## Expected  behavior

Expected some documentation on BCL class members like in VS2017:

![image](https://user-images.githubusercontent.com/6348118/38611739-c72c7338-3d84-11e8-8a2b-5b41d121678b.png)

## Actual behavior

There's no BCL metadata comments / XML doc:

![image](https://user-images.githubusercontent.com/6348118/38611637-8b5cc6d2-3d84-11e8-8684-429577267e62.png)

**Comment by lferrao** [comment]
Also of note, F12 takes me to metadata that is indeed missing the comments.

**Comment by devel0** [comment]
That's a problem for me too, xml documentation isn't included within dotnet sdk as far I realized, so I found that follow [repository](https://github.com/dotnet/dotnet-api-docs) contains all xml files ( zip file about 70mb unpacked about 800mb ); but now I wondering where I have to place that in order to allow omnisharp recognize and search for it.

**Comment by FelschR** [comment]
I only see documentation for my own XML headers. For standard functions like `IEnumerable.Any` there is no documentation shown in the popover.

**Comment by devel0** [comment]
I had the same issue and as hugly workaround I converted my lib to a netcore app while in a project netstandard used to build only library from csproj file I included cs files and excluded Program.cs; this allowed me to work using intellisense working from netcoreapp type workspace and vscode to shown xml documentation referring correct assembly through F12 ( eg. System.Threading.dll ) while from netstandard project it shown a fake one ( netstandard.dll )

example netstd csproj

```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>8.0</LangVersion>
        <RootNamespace>myns</RootNamespace>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>
    <ItemGroup>
...
    </ItemGroup>
    <ItemGroup>
        <Compile Include="../server-lib/*.cs" />
        <Compile Remove="Program.cs" />
    </ItemGroup>
</Project>
```

**Comment by JoeRobich** [comment]
Cannot reproduce with the current release.
