### ISSUE TITLE
Curly braces, no direct explanation on how to include new user settings

### ISSUE THREAD

**Issue by joejyong** [dotnet/vscode-csharp#2187]
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:

## Steps to `reproduce`
I have recently moved to Visual Studio code and for the life of me I cannot get curly braces to move to a new line at the end of functions and variables. Could any one help explain the steps I am meant to take to resolve this? 
Previous versions of VS simply had it in tools options and all I can find only for VSCode and Omnisharp are conflicting posts on forums that don't accurately describe how to change these settings. Apologies if this is a redundant question or I have missed an obvious answer somewhere. 
Thanks

**Comment by DustinCampbell** [comment]
The answer that you're looking for is here: https://github.com/OmniSharp/omnisharp-vscode/issues/1506#issuecomment-303390666.

**Comment by JoeRobich** [comment]
Closing as answered.
