### ISSUE TITLE
Autocomplete for Unity events not working

### ISSUE THREAD

**Issue by ZeldaZocker** [dotnet/vscode-csharp#2197]
## Environment data
dotnet --info output:
```
.NET-Befehlszeilentools (2.1.103)

Product Information:
 Version:            2.1.103
 Commit SHA-1 hash:  60218cecb5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   D:\Program Files\dotnet\sdk\2.1.103\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d
```
VS Code version: 1.22.2
C# Extension version: 1.14.0

## Steps to reproduce

   1. Open Unity project in VS Code.

   2. Try to type "On..."
![code_2018-04-16_19-12-52](https://user-images.githubusercontent.com/34456207/38824659-41080928-41aa-11e8-8094-133497b2ad32.png)

## Expected  behavior
Show autocomplete for Unity events like "OnTriggerEnter(Collider col)" or "Update()".

## Actual behavior
Doesn't show autocomplete.

**Comment by DustinCampbell** [comment]
Marking this as a feature request as it is for custom completion support for Unity.

**Comment by SirIntruder** [comment]
There are many snippet packs which approximate this functionality when you search for "unity snippets" in extensions manager. 
Most popular one: https://github.com/YclepticStudios/vscode-unity-snippets.
Fork without xml docs: https://github.com/lionize/vscode-unity-snippets

**Comment by MiguelMoll** [comment]
Just ran into the same issue. Checking to see if there's something I've missed. Will checkout the snippets suggested above.

**Comment by JoeRobich** [comment]
Recommend using the Unity extension for VS Code.
