### ISSUE TITLE
The behavior is changed when opening a lua file in a c#-lua mixed unity project

### ISSUE THREAD

**Issue by ltccss** [dotnet/vscode-csharp#2198]
## Environment data
`dotnet --info` output:
VS Code version:1.22.2
C# Extension version:1.14.0

## Steps to reproduce
Set VS Code as the default editor for .lua in windows

Open a unity5 project that containing some c# and lua files

Set VS code as the default editor through Unity Menu : Editor-Preference-External Tools-External Script Editor

Double click any lua file showed in "Project", 

## Expected  behavior
In the previous version of c# extension, when VS Code is opened, it can be showed like this:

![qq 20180417014631](https://user-images.githubusercontent.com/33274372/38826098-66a7a7c4-41e1-11e8-95b7-057af4fee827.png)

The unity project folder is passed in

## Actual behavior
In the lastest c# extension:
![qq 20180417014649](https://user-images.githubusercontent.com/33274372/38826189-ad6d2bca-41e1-11e8-9577-6eaa2ebe7c0c.png)

No folder can be found.

**Comment by ltccss** [comment]
Could you keep the feature that regarding those script languages which are used to embed into other languages as something works in the same folder as the host language does?
It's a good experience I felt.

**Comment by JoeRobich** [comment]
This is a problem in the Unity editor and not the C# extension. The Unity editor is what is providing the path to open to VS Code.
