### ISSUE TITLE
VS 2017 + Unity + Mac OS high sierra (10.13.4) soft links not working

### ISSUE THREAD

**Issue by AlexeyIS** [dotnet/vscode-csharp#2202]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.1.103)

Product Information:
 Version:            2.1.103
 Commit SHA-1 hash:  60218cecb5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.103/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d

VS Code version: 1.22.2 (1.22.2)
C# Extension version:

## Description 

Hi all,

I am using VS code on mac with Unity3d. I have a project where different files and folders are soft linked (aliased) in to the project folder. The problem is that VS code doesn't index those files, meaning that there is no autocompletion or visibility of other classes outside the current open file. The projects builds without problems, but there is no support when typing. Before High Sierra I could use hard links and that worked fine, but since High Sierra has apple file system, which doesn't support hard links, so I had to use soft links. Did anybody had this issue or knows where to look and what to try?

Thanks!

**Comment by JoeRobich** [comment]
A lot has changed with project loading since this issue was opened. If you are still running into problems, please open a new issue.
