### ISSUE TITLE
Automatic select project

### ISSUE THREAD

**Issue by troydai** [dotnet/vscode-csharp#227]
After open a `project.json` project in VS code, it requires user to explicitly choose a project using the "Select project" drop box on the bottom right. There is a few problems here:
1. The button locates at the corner and is easily ignored;
2. It is not quiet intuitive especially when there is one `project.json` or `global.json` at the root. It is natural to expect the VS code to recognize it automatically or at least prompt user to choose a project.

**Comment by JoeRobich** [comment]
The extension will now automatically select the solution to open or open a prompt when there are multiple.
