### ISSUE TITLE
Hover mouse over a method name didn't highlight multiline xml document comments correctly.

### ISSUE THREAD

**Issue by pengzhisun** [dotnet/vscode-csharp#2293]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.1.0-preview1-006723)

Product Information:
 Version:            2.1.0-preview1-006723
 Commit SHA-1 hash:  7e1fe7eba7

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.0-preview1-006723/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
VS Code version: Version 1.23.1 (1.23.1)
C# Extension version: 1.15.1 (May 11, 1018)

## Steps to reproduce

add a multiline `<param>` comments like following:

        ```csharp
        /// <summary>
        /// Test method.
        /// </summary>
        /// <param name="defaultValue">
        /// The default parameter value description
        /// break in two lines.
        /// </param>
       public void TestMethod(string defaultValue)
       {
       }

       public void TestMethodCaller()
       {
              // hovering mouse over the TestMethod
              TestMethod(string.Empty);
       }
       ```

## Expected  behavior
hovering mouse over the TestMethod, the defaultValue parameter description should highlight correctly: "The default parameter value description break in two lines.", just like what visual studio supported.

## Actual behavior
only the first line "The default parameter value description" was highlighted.
<img width="437" alt="vscode" src="https://user-images.githubusercontent.com/764635/39954496-382194fc-55f3-11e8-9ff7-61540135c4a4.png">

**Comment by DustinCampbell** [comment]
@rchande / @akshita31 : FWIW, I would expect this to go away when Roslyn 2.9.0 ships with a new public API for Quick Info.

**Comment by JoeRobich** [comment]
Cannot reproduce with latest release.
