### ISSUE TITLE
Better auto-complete for generic methods

### ISSUE THREAD

**Issue by bugproof** [dotnet/vscode-csharp#2350]
Visual Studio does this:

![image](https://user-images.githubusercontent.com/3116731/40643432-72607810-6320-11e8-814c-2570b0a8cdcb.png)

Visual Studio Code shows this in a different way, but still, it seems a bit like unrecognized and it's not too obvious.

![image](https://user-images.githubusercontent.com/3116731/40643728-5b8bee16-6321-11e8-81b8-d8235d90b51d.png)

When typing `services.AddSingleton<` in VS it automatically recognizes that there's generic method and does something like `services.AddSingleton<|>`

This also works nicely in JetBrains Rider:

![image](https://user-images.githubusercontent.com/3116731/40652617-ff963630-6338-11e8-9dfc-1810bfc96a11.png)

In vs code it takes much longer to discover and is frustrating

It seems like vscode autocompletion is still far from perfect despite using vscode is super lightweight.

**Comment by ayepirate** [comment]
https://github.com/OmniSharp/omnisharp-vscode/issues/851

**Comment by JoeRobich** [comment]
Completion list behavior now matches VS.
