### ISSUE TITLE
[Feature-Request] New options for interface auto-implementation

### ISSUE THREAD

**Issue by Veruthas** [dotnet/vscode-csharp#2392]
I don't believe these options exist yet, but when auto-implementing interfaces (using the hover over interface and selecting from menu), would it be possible to have settings to:

- Choose whether to add implemented methods with body or lambda ({} or =>)
- Choose whether to add all methods with methods etc., or on bottom of class (potentially within a #region)

**Comment by DustinCampbell** [comment]
@rchande: should this be tracked on the roslyn repo?

**Comment by rchande** [comment]
Filed an issue against Roslyn for the second point. C# extension would need to surface the first point.

**Comment by geirsagberg** [comment]
Also would be great if properties from interfaces were implemented as auto-properties, not getters and setters that `throw new NotImplementedException()`, as I suspect auto-properties will be correct in 99% of the cases.

**Comment by JoeRobich** [comment]
This is configurable via .edtorconfig.
