### ISSUE TITLE
Create a new class file and change it base class Unparsing

### ISSUE THREAD

**Issue by fjqingyou** [dotnet/vscode-csharp#2401]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

VS Code version: 1.24.1
C# Extension version: 1.15.2

## Steps to reproduce
Sorry , My english is very bad, so i'm recording screen, forgive me!

//this recording screen video file.
//i using Mac OS system "QuickTime Player" play it
[Test.mov.zip](https://github.com/OmniSharp/omnisharp-vscode/files/2153671/Test.mov.zip)

## Expected  behavior
create a new empty class file, don't have error

## Actual behavior
it have a error for now

**Comment by rchande** [comment]
@fjqingyou What namespace is your type `ReadOnlyAttribute` defined in? Do you need to add a using?

**Comment by fjqingyou** [comment]
No, My Test class and ReadOnlyAttribute class namespace is empty , i'm not defined it, so I No need using!

Test.cs and ReadOnlyAttribute.cs file in same folder

**Comment by fjqingyou** [comment]
@rchande My English is very bad, Sorry!

**Comment by fjqingyou** [comment]
video start is ReadOnlyAttribute.cs file defined!

**Comment by JoeRobich** [comment]
A lot has changed with project file watching since this issue was opened. If you are still seeing problems, please open a new issue.
