### ISSUE TITLE
Formatter not working with mocking complex objects

### ISSUE THREAD

**Issue by enum01** [dotnet/vscode-csharp#2421]
## Environment data 
`dotnet --info` output: 
.NET Core SDK (reflecting any global.json):
 Version:   2.1.301
 Commit:    59524873d6

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.301/

Host (useful for support):
  Version: 2.1.1
  Commit:  6985b9f684

.NET Core SDKs installed:
  2.1.200 [/usr/local/share/dotnet/sdk]
  2.1.301 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

VS Code version: 1.25.1
C# Extension version: 1.15.2

## Steps to reproduce
Build out a C# object with multiple sub-entities and properties.

## Expected  behavior
The given object should format to:

```
new Example
{
    Id = 12,
    Name = "My test",
    FirstList = new List<Person> 
    {
        new Person(),
        new Person(),
        new Person
        { 
            IsDone = true
        },
    },
    Areas = new List<Area> 
    {
        new Area
        {
            thingys = new List<thing>
            {
                new widget  
                { 
                    Id = 5,
                    InnerThings = new List<InnerThing>
                    { 
                        new InnerThing
                        {  
                            Text = "some text",
                            Values = new List<Value>
                            {
                                new Value
                                {
                                    ValuesValue = "some value"
                                }
                            }
                        }
                    }
                },
            }
        }
    }
};
```

## Actual behavior
The formatting here is wrong clearly, and when I format the document it does not format the object at all.

```
new Example
{
    Id= 12,
    Name= "My test",
    FirstList=new List<Person> {
        new Person(),
        new Person(),
        new Person
        { IsDone= true
        },
    },
    Areas= new List<Area> {
        new Area
        {
            thingys= new List<thing>
            {
                new widget  { Id= 5,
                    InnerThings= new List<InnerThing>
                    { new InnerThing
                        {  Text = "some text",
                            Values= new List<Value>
                            {
                                new Value
                                {
                                    ValuesValue="some value"
                                }
                            }
                        }
                    }
                },
            }
        }
    }
};
```

**Comment by DustinCampbell** [comment]
@rchande : This may be by design. I don't believe the C# formatter ever formats code inside initializers. So, anything inside the collection initializers in this example might not get formatted (and wouldn't in VS either). cc @pilchie and @jinujoseph

**Comment by JoeRobich** [comment]
Roslyn does not support formatting initializers.
