### ISSUE TITLE
sln version for Unity Code

### ISSUE THREAD

**Issue by ghost** [dotnet/vscode-csharp#2422]
## Environment data
`dotnet --info` output:
VS Code version:1.25.1
C# Extension version:1.15.2

## Steps to reproduce
Set Code as Unity's Code Editor, And Open C# Code by Unity。Then version of sln if 11.0，but I need 12.0 for MSBuild

## Expected  behavior
Can I choose then newer version of sln?

**Comment by rchande** [comment]
@RCBelmont if I understand your question, I think you should be able to tell unity to use version 12.

**Comment by JoeRobich** [comment]
Recommend using the new Unity extension for VS Code.
