### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by ghost** [dotnet/vscode-csharp#2423]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.1.202)

Product Information:
 Version:            2.1.202
 Commit SHA-1 hash:  281caedada

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.202\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.9
  Build    : 1632fa1589b0eee3277a8841ce1770e554ece037

VS Code version: 1.25.1
C# Extension version: 1.15.2

## Steps to reproduce
Create and build any Core project. Currently the issue is present for me in a project with a "web" template with NuGet for Microsoft.EntityFrameworkCore installed. The project literally has five code files with nothing interesting going on inside of them.

## Expected  behavior
OmniSharp working as usual.

## Actual behavior
About 10 minutes after launching the VSCode with the project opened in a Workspace, OmniSharp uses 350 MB of RAM and VSCode in total using 500.
Withing the time it took me too write this much (5 minutes tops?) the usage has grown to 500 and 850 MB for OmniSharp and VSCode respectively. And that is inactive time of the IDE just sitting in the background.
In my experience I tend not to pay much attention to this, until the entire system starts to lag, at which point I notice that VSCode is now sitting at some 2 GB of RAM usage. It takes 30 minutes to an hour for it to reach such state. Quitting obviously does the job of cleaning up, as does reloading the studio (like the reload one can perform after installing another extension).

I've also noticed strange activity in OmniSharp's log, but I do not have enough knowledge to identify an issue. The logs go as follows. After finishing configuration it adds my .csproj file:
[info]: OmniSharp.MSBuild.ProjectManager Adding project 'FooBar.csproj'
And then it starts to get strange for me. It tries to update the project:
[info]: OmniSharp.MSBuild.ProjectManager Update project: FooBar
Only to find that some caches are missing, which I do not particularly understand:
[dbug]: OmniSharp.Services.MetadataFileReferenceCache Cache miss \dotnet\sdk\NuGetFallbackFolder\microsoft.applicationinsights.dependencycollector\2.4.1\lib\netstandard1.6\Microsoft.AI.DependencyCollector.dll

This goes on for a while, as every reference added has a missed cache.
Then it eventually queues update for a project and tries to load it:
[info]: OmniSharp.MSBuild.ProjectManager Queue project update for 'FooBar.csproj'
[info]: OmniSharp.MSBuild.ProjectManager Loading project: 'FooBar.csproj'

And then it just starts doing it over and over again---update, queue update, load project, update, queue update, load project. In fact, as I'm finishing this issue, I've spent roughly 30 minutes writing it and OmniSharp now sits at 1.5+ GB of RAM. And it just keeps growing.

So I understand that something (like inability to properly process my .csproj) causes it to start over and eventually bloat, but I have no clue why.

**Comment by rchande** [comment]
@Heagon Please use Task Manager or Visual Studio to capture a dump of the "omnisharp.exe" process so we can analyze the memory usage.

**Comment by rchande** [comment]
Also @Heagon, could you please share your full o# log?

**Comment by Heagon** [comment]
@rchande I can share a log, sure. But the memory dump could be a problem. I mean, I got several, but they are growing to 300 MB within literal seconds of me launching the studio.
[OmniSharp.log](https://github.com/OmniSharp/omnisharp-vscode/files/2214948/OmniSharp.log)

**Comment by bakintunde** [comment]
Hi @rchande This is still an issue for me on vscode, mac os x

**Comment by jcreek** [comment]
Also an issue for me on Ubuntu 19.04.

**Comment by madiron** [comment]
Hi, I have same problem.

I have a large solution with thousands classes and ram grows indefinitely.

![image](https://user-images.githubusercontent.com/6757315/115264141-53226100-a136-11eb-8340-1b13c5d7aa5f.png)

this is an example but the ram also reaches 20 gigabytes.

**Comment by JoeRobich** [comment]
There have been lots of improvements since this issue was opened. Please open a new issue with logs if you are still running into this.
