### ISSUE TITLE
csharp.unitTestDebuggingOptions and args property

### ISSUE THREAD

**Issue by Sbou** [dotnet/vscode-csharp#2435]
## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.302/

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.202 [/usr/share/dotnet/sdk]
  2.1.302 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

VS Code version:
1.25.1
C# Extension version:
1.15.2

## Steps to reproduce
Create an MSTest project.
Create a runsettings file with parameters.
Add this settings to the workspace settings
`"csharp.unitTestDebuggingOptions":{
        "args":["--settings:myfile.runsettings"]
    }
`

## Expected  behavior
The parameters are loaded to the TestContext.Properties.

## Actual behavior

Unable to access this parameters when I debug the test when reading TestContext.Properties.

**Comment by akshita31** [comment]
@rchande I investigated further into this and realised that we are only reading the "unitTestDebuggingOptions" to create a launch configuration for debugging. We do not have any mechanism to accept the settings for running the test and passing it to omnisharp. 

IMO, we should pass these options along with the "RunTest" request and add code in omnisharp that reads these settings and passes them on to the cli process. Thoughts ?

**Comment by rchande** [comment]
@gregg-miskelly Cool, thanks for clarifying that. It would probably make sense to have some kind of explicit "testSettings" option that you could set. 

OmniSharp.json might be a better location for the setting simply because it's always a file in the repo. We wouldn't want users to accidentally configure this setting in their workspace settings in VS Code (as oppposed to putting a .vscode settings file in their repo). What do you think?

**Comment by gregg-miskelly** [comment]
Yes, that was my thinking as well.

**Comment by AOne-T** [comment]
Any progress on that issue?

**Comment by dgileadi** [comment]
My use case is that I'd like to run plain NUnit tests in a Unity project. The Unity vscode integration generates several .csproj files, along with one .sln file. When I click a Run Test link, I get:

> MSBUILD : error MSB1011: Specify which project or solution file to use because this folder contains more than one project or solution file.

I'm hoping the fix to this ticket would allow me to solve the above error. Alternately some built-in support for running tests out of the box in Unity projects wouldn't be bad :)

**Comment by jkoritzinsky** [comment]
I've started hitting this issue working on the DllImportGenerator project in dotnet/runtimelab.

**Comment by JoeRobich** [comment]
Runsettings files can be configured through VS Code settings ![Image](https://github.com/user-attachments/assets/d6380719-c035-4c1d-8b51-5de6da67b7ab)
