### ISSUE TITLE
The Format document command does not work in multi root workspaces

### ISSUE THREAD

**Issue by Martin00001** [dotnet/vscode-csharp#2468]
Issue Type: <b>Bug</b>

The command Format Document does not work in every project folder when there is multi-root workspace.

Extension version: 1.15.2
VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790S CPU @ 3.20GHz (8 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (12.57GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by DustinCampbell** [comment]
Hi @Martin00001, you right that this does not work today. https://github.com/OmniSharp/omnisharp-vscode/issues/1889 will need to be fully implemented before that can happen.

**Comment by JoeRobich** [comment]
Closing as issue can be tracked by #1889
