### ISSUE TITLE
Rename file according to class using the codelens results in two files

### ISSUE THREAD

**Issue by akshita31** [dotnet/vscode-csharp#2482]
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version: 1.16.0-beta3

## Steps to reproduce
1. open a project for the first time
2. the project has a class called C in a file called C.cs
3. open C.cs
4. rename the class C to B
5. save the file
6. You will get a lightbulb offering to rename the from C.cs to B.cs to match the name you just used
7. Use it and then Ctrl+T

## Expected  behavior
Only B.cs should remain 

## Actual behavior
Classes called C and B will both appear in the search window and symbols from both are shown on Ctrl+T

**Comment by akshita31** [comment]
cc @rchande

**Comment by akshita31** [comment]
@rchande I installed 1.15.1 version of the extension and seems that this error was already present in that as well. Here is roughly how the Renaming works:

1. The existing file "C.cs" is deleted and a file "B.cs" is added to the workspace using the BufferManager UpdateWorkspaceAsync method(using the filewatcher that is set up by the MSBuildSystem)
2. However somehow the extension is sending an UpdateBufferRequest to Omnisharp after the rename is complete which is leading to a file being added to the workspace by the buffer manager.
3. This is even leading to the diagnostics `{
	"resource": "/c:/Users/akagarw/Desktop/hello_world/foo/hello2.cs",
	"owner": "csharp",
	"code": "undefined",
	"severity": 8,
	"message": "The namespace '<global namespace>' already contains a definition for 'hello' [foo]",
	"startLineNumber": 2,
	"startColumn": 7,
	"endLineNumber": 2,
	"endColumn": 12
}` because there are two files that contain the same code.

I am investigating further.

**Comment by akshita31** [comment]
It is strange. When I run the extension from the extension host I dont get that error however the vsix has it.

**Comment by akshita31** [comment]
On investigating further I _think_ the problem is with the extension and not omnisharp. So what is happening is that when the file "B.cs" is deleted, we are invoking two end points from the extension:
1. Update buffer : https://github.com/OmniSharp/omnisharp-vscode/blob/d00799a71eda341d22515c05a66bcab82c6c50e7/src/features/changeForwarding.ts#L26 due to the `fileChangedEvent` from the workspace.

2.FileChanged: https://github.com/OmniSharp/omnisharp-vscode/blob/d00799a71eda341d22515c05a66bcab82c6c50e7/src/features/changeForwarding.ts#L44 due to the watcher being set.

So in the **normal case** when we delete a file,  **1 is invoked before 2**, so omnisharp updates the buffer and then deletes the file, hence there is no problem of extra file.

However in this specific case, **2 is invoked before 1**, hence omnisharp first deletes the file and then calls updateBuffer which then thinks that a file is a fresh file that doesn't exist in the workspace and adds it as a transient document hence leading to the diagnostics and the problems.

**Comment by JoeRobich** [comment]
A lot has changed with CodeActions since this issue was opened. If you are still seeing problems, please open a new issue.
