### ISSUE TITLE
OmniSharp does not set SolutionDir variable

### ISSUE THREAD

**Issue by braunsonm** [dotnet/vscode-csharp#2484]
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.1.202)

Product Information:
 Version:            2.1.202
 Commit SHA-1 hash:  281caedada

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.202\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.9
  Build    : 1632fa1589b0eee3277a8841ce1770e554ece037
```

VS Code version: Latest Stable
C# Extension version: 1.15.2

## Steps to reproduce
Setup a CSproj with something like this for example:
```
  <PropertyGroup> 
     <CodeAnalysisRuleSet>$(SolutionDir)\Example.ruleset</CodeAnalysisRuleSet> 
     <Features>IOperation</Features> 
     <NoWarn></NoWarn>   
  </PropertyGroup>  
```

## Expected behavior
The extension should at least set the variable to your workspace root or have the option too. This is the default behavior of Visual Studio 2017 and will cause issues with anyone that thinks they can easily move to VSCode.

## Actual behavior
You'll get errors that it can't find the file on build:
```
C:\Program Files\dotnet\sdk\2.1.202\Microsoft.CSharp.CurrentVersion.targets(134,9): warning MSB3884: Could not find rule set file "\Example.ruleset". [E:\Development\Example\Source\Cooker\Cooker.csproj]
    1 Warning(s)
    0 Error(s)
```

**Comment by ChaosCA** [comment]
As a user fix, you can add this to your build task:

```
    "options": {
        "env": {
            "SolutionDir": "${workspaceFolder}"
        }
    },
```

**Comment by ChaosCA** [comment]
I also believe it doesn't set the `ConfigurationName`

**Comment by vdimov-gcmlp** [comment]
Environment variable can be set in tasks.json, but it doesn't seem like it can be set for running tests using Code Lens. Currently, "env" is not an option in `csharp.unitTestDebuggingOptions` config.

reference: [run and debug unit tests](https://github.com/OmniSharp/omnisharp-vscode/wiki/How-to-run-and-debug-unit-tests)

**Comment by JoeRobich** [comment]
A lot has changed with O# project loading since this issue was opened. If you are still having problems, please open an issue at https://github.com/OmniSharp/omnisharp-roslyn/issues
