### ISSUE TITLE
When writing C# for Unity, VSCode changes my "return" statements to "ref"

### ISSUE THREAD

**Issue by dan-modsi-io** [dotnet/vscode-csharp#2493]
Issue Type: <b>Bug</b>

1.  Create a project in Unity 2017 editor.  
(I'm doing this on a mac, don't know about Windows or Linux)
(this may happen for other project types, I don't know)

2.  Add a c# Script to your Unity project using the Unity editor.

3.  Create a new empty function.. something like:
public float GetCost() {

}

4.  Place your cursor inside the function braces and type "return " without the quote marks.  Note the space on the end.

5.  Observe that "return" has changed to "ref".

6.  Press Command-Z until "return" is restored, indicating that you did indeed type "return".

7.  Be (mildly) annoyed and file a bug report.

Extension version: 1.15.2
VS Code version: Code 1.27.0 (7b9afc4196bda60b0facdf62cfc02815509b23d6, 2018-09-05T05:22:06.672Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (4.81GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_254014|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by SirIntruder** [comment]
same issue as this https://github.com/OmniSharp/omnisharp-vscode/issues/2472
