### ISSUE TITLE
Annotation-defined inheritance

### ISSUE THREAD

**Issue by fjqingyou** [dotnet/vscode-csharp#2506]
## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

VS Code version: 1.27.1
C# Extension version: 1.15.2

## Steps to reproduce
Enter the code below

```
public interface ITest{
    /// <summary>
    /// This a test method
    /// </summary>
    void TestMethod();//A comment has been assigned to this method interface
}

public abstract class TestBase : ITest{
    public abstract void TestMethod();//This method must reassign comments

    /// <summary>
    /// This a test other method
    /// </summary>
    public void TestOtherMethod(){

    }
}

public class Test : TestBase{
    public override void TestMethod(){//This method must also reassign comments

    }
}
```

## Expected  behavior
Mouse move to  TestMethod in 'Test' and 'TestBase' class,can prompt the last comment information defined for the method

## Actual behavior
not prompt

**Comment by JoeRobich** [comment]
Recommend using `<inheritdoc>`. See https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#inheritdoc
