### ISSUE TITLE
IntelliSense strings are localized

### ISSUE THREAD

**Issue by Spike2D** [dotnet/vscode-csharp#2513]
Yesterday my VS Code updated Omnisharp, since then my intellisense and debugging messages are being outputted in another language from English, there doesn't seem to be any way to configure or change that behaviour.

**Comment by gregg-miskelly** [comment]
Can you give us some examples of intellisense strings?

I know the debugger hasn't yet done the work to ship any localized strings. So if you are getting localized debugger strings they must be from VS Code itself. I am not sure if there are any parts of the language service that have localization yet.

**Comment by Spikent** [comment]
You were right, I could fix the intellisense, however I still get this:
With 1.32.3-beta.9:
![1 32 3-beta 9](https://user-images.githubusercontent.com/24965188/45421233-bc8f8880-b68c-11e8-8ae3-731af1d05c28.png)

Meanwhile with 1.32.4 or 1.32.5:
![1 32 5](https://user-images.githubusercontent.com/24965188/45421266-cadda480-b68c-11e8-80e5-30e67da9540e.png)

**Comment by gregg-miskelly** [comment]
@rchande @akshita31 any ideas?

**Comment by rchande** [comment]
@Spikent We need more info--what OS are you on? If you're on Windows, what is your language is your system set to use? This looks like a Unity project--what language is Unity configured to use?

**Comment by Spikent** [comment]
@rchande I'm running Windows 10 Pro, and it's locale is set to Spanish, which I'm guessing it's what Omnisharp is picking up on recent updates to set it's locale to...

The Project is a Godot project, it's running on c#.

**Comment by tyraeltyro** [comment]
I have the same problem on polish version of the Windows 10 system.

**Comment by rchande** [comment]
This is essentially a feature request for us to set the locale of OmniSharp based on the VS Code language configuration.

**Comment by rchande** [comment]
@Spikent Thank you for the feature request. What's happening here is that one of OmniSharp's dependencies recently implemented localization for error messages, meaning that they will now be printed in your system language instead of English. To work around this (and get English error messages), you can delete the OmniSharp localization files:

Open your "OmniSharp" log and find the path to OmniSharp from the beginning of the log, eg:
```
OmniSharp server started.
    Path: C:\Users\rchande\.vscode-insiders\extensions\ms-vscode.csharp-1.16.1\.omnisharp\1.32.5\OmniSharp.exe
    PID: 144684
```
Navigate to the directory eg `C:\Users\rchande\.vscode-insiders\extensions\ms-vscode.csharp-1.16.1\.omnisharp\1.32.5`, and enter the subfolder that corresponds to your system language. In @Spikent's case, the folder would be "es" because the system language is Spanish. Remove all the DLLs whose name starts with `Microsoft.CodeAnalysis`. 

This should result in English error messages.

**Comment by gregg-miskelly** [comment]
@chinaq you can follow the work around that @rchande gave above for now.

**Comment by Novack** [comment]
Same problem for me on VSCode 1.30.1:
Im getting error and warning hints on spanish, despite having VSCode locale to "en_US". 
Cant find any option to change this behavior.

Any news on this?

**Comment by henioStraszny** [comment]
I believe that for most of the developers, the fact of having error messages in one language - English - is really a big benefit.

Please be aware that the amount of information you can google with Polish, Chech, or other similar language is minimal. Amount of information in English is huge. Translating error messages or other related information to my mother language makes my work much much harder.

Please do not change my development language to anything different then English by default.

**Comment by imba-tjd** [comment]
In VS, there is a `Option-International Settings`. If it is set to English, both the UI and intellisence info are set to English and thus ignore Windows locale settings.
For myself, while I agree English is the basic skill for programmers, I would still like to have a setting to determine the language of intellisence info. But it's also OK totally corresponding to VSC's UI language.

**Comment by felipeoriani** [comment]
> Navigate to the directory eg `C:\Users\rchande\.vscode-insiders\extensions\ms-vscode.csharp-1.16.1\.omnisharp\1.32.5`, and enter the subfolder that corresponds to your system language. In @Spikent's case, the folder would be "es" because the system language is Spanish. Remove all the DLLs whose name starts with `Microsoft.CodeAnalysis`.
> 
> This should result in English error messages.

Yes, this workaround worked, but it would be great to have a user friendly configuration :D ... consider it on the next version. Thank you.

**Comment by rickyah** [comment]
I have the same problem on mac os Mojave (10.14.3) with dotnet 2.1.504 installed.

The omnisharp server prints all messages in spanish, although I have english as locale for the terminal and vscode. Unfortunately the workaround is not working, as on mac the Microsoft.CodeAnalysis dlls are not located on the omnisharp installation folder

**Comment by nim** [comment]
I have the same problem Terminal and IntelliSense https://i.imgur.com/GoxqoRx.png

**Comment by Eagle3386** [comment]
Almost one year later, this bug (yes, it's a bug as a) OmniSharp ignores VSC's language setting and b) has no option for setting its own language either) still is unresolved.

If one might outline to some extend how to fix that (besides the mentioned awesome workaround by @rchande above), I'd love to implement it.

**Comment by rchande** [comment]
@Eagle3386 OmniSharp is just using the users's language setting. To alter this you would need to change the C# extension (https://github.com/OmniSharp/omnisharp-vscode) to read the VS Code setting and pass it to the server (https://github.com/OmniSharp/omnisharp-roslyn) which would also have to be changed to respect that configuration.

**Comment by Eagle3386** [comment]
Alright, I'll try and see if I can handle that. Wish me luck, cause up to now, I've only fixed MS docs.. 🤣

**Comment by Eagle3386** [comment]
While I've managed to add an option and extend unit tests without much work, I seem unable to find docs about the needed variable name for `dotnet` ([OmniSharpServer -> server.ts, line 304](https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/omnisharp/server.ts#L304), seems to enable direct "pass-through" for `dotnet`'s settings).

Any help would be greatly appreciated! 👍

**Comment by Eagle3386** [comment]
**Update:** Found it while adding `"terminal.integrated.env.windows": { "DOTNET_CLI_UI_LANGUAGE": "en" },` (or `en-us`) to my user/workspace `settings.json` file to fix terminal output, too.
Maybe setting environment variable prior to to launching omnisharp-roslyn / dotnet via child thread already solves the issue.. 🤔

**Comment by imba-tjd** [comment]
> 
> 
> **Update:** Found it while adding `"terminal.integrated.env.windows": { "DOTNET_CLI_UI_LANGUAGE": "en" },` (or `en-us`) to my user/workspace `settings.json` file to fix terminal output, too.
> Maybe setting environment variable prior to to launching omnisharp-roslyn / dotnet via child thread already solves the issue.. 🤔

I had found this on the above comment. It doesn't work.

**Comment by Eagle3386** [comment]
> I had found this on the above comment. It doesn't work. You can try by setting it in Windows' environment variable.
For the (external) terminal panel, it definitely works.

Regarding OS-roslyn, it clearly can't work up to now as there's no code for reading the environment variable and then passing it into the child thread's environment and/or launch arguments.. 😉

**Comment by Phloog** [comment]
Any news on this? Is there a better solution than the workaround yet available?

**Comment by MeowKim** [comment]
Wow.. It's middle of 2020 now. 
I can't believe this is not solved yet. 😨

**Comment by lucianotres** [comment]
> **Update:** Found it while adding `"terminal.integrated.env.windows": { "DOTNET_CLI_UI_LANGUAGE": "en" },` (or `en-us`) to my user/workspace `settings.json` file to fix terminal output, too.
> Maybe setting environment variable prior to to launching omnisharp-roslyn / dotnet via child thread already solves the issue.. 🤔

Yes, the easiest way 🙌

**Comment by ercanerdogan** [comment]
Where is this settings.json file ?  Could you write full-path?

**Comment by ercanerdogan** [comment]
Yeah, I have found that where is "%APPDATA%\Code\User" settings.json file is here.

**Comment by BoraKaraca** [comment]
This solution work for me  Source:https://superuser.com/a/1512105/1346669

Close VS Code
Enter the system language found in this path inside the folder.I use Turkish language on windows
C:\Users\PC\.vscode\extensions\ms-dotnettools.csharp-1.23.11\.omnisharp\1.37.8\tr
![image](https://user-images.githubusercontent.com/23034393/118160231-bd24e200-b426-11eb-9884-7569652d4eba.png)

Remove all dll files starting with 'Microsoft.CodeAnalysis'
(Please notice that some folder names in the path might vary due to different versions)
Open VS Code its work 
![image](https://user-images.githubusercontent.com/23034393/118160454-feb58d00-b426-11eb-9d30-de1aad1af380.png)

**Comment by Ejd3rE** [comment]
> This solution work for me Source:https://superuser.com/a/1512105/1346669
> 
> Close VS Code
> Enter the system language found in this path inside the folder.I use Turkish language on windows
> C:\Users\PC.vscode\extensions\ms-dotnettools.csharp-1.23.11.omnisharp\1.37.8\tr
> ![image](https://user-images.githubusercontent.com/23034393/118160231-bd24e200-b426-11eb-9884-7569652d4eba.png)
> 
> Remove all dll files starting with 'Microsoft.CodeAnalysis'
> (Please notice that some folder names in the path might vary due to different versions)
> Open VS Code its work
> ![image](https://user-images.githubusercontent.com/23034393/118160454-feb58d00-b426-11eb-9d30-de1aad1af380.png)

thank you, it worked for me. I've been calling a lot.

**Comment by jcbritobr** [comment]
We are mid 2021 and this was not solve yet... 
Must be a very difcult issue to solve. OMG.

**Comment by onurtr** [comment]
Well well... Who knows after hours of searching, it' s fixed by dll deletion.

**Comment by Eagle3386** [comment]
> Well well... Who knows after hours of searching, it' s fixed by dll deletion.

By no means shall this method be called "fix". It's nothing but a _tremendously_ dirty hack to say the least!

**Comment by twoco** [comment]
Today ...

![image](https://user-images.githubusercontent.com/53160891/136565400-79b6e34e-16c5-4052-bc52-28c700004d85.png)

Seems to be related to it. I clicked on "Don't show again." (on the gear icon). 
Btw. a complete other topic but slighly related to it: The latest Chromium DevTools also now annoys with language packs. Have you already seen it? Argh, let me develop in english please. 😢 😆

**Comment by markusroessler** [comment]
In addition to @Spikent's workaround (https://github.com/OmniSharp/omnisharp-vscode/issues/2513#issuecomment-423270085):
If you also want the debugger output to appear in english, remove all DLL files from the following directory:
`C:\Users\mroessler\.vscode\extensions\ms-dotnettools.csharp-1.23.16\.debugger\{LCID}`
You can find the LCID for your system language here: https://docs.microsoft.com/en-us/openspecs/office_standards/ms-oe376/6c085406-a698-4e12-9d4d-c3b0ee3dbc4a

**Comment by sqwwwok** [comment]
> 

![image](https://user-images.githubusercontent.com/52393426/154433612-0d1c450a-7f4e-463d-af57-fdcf0fedc222.png)
Try to change the display language of vscode to en, which worked on my mac. But the effects will be global in the editor.

**Comment by jcbritobr** [comment]
> ![image](https://user-images.githubusercontent.com/52393426/154433612-0d1c450a-7f4e-463d-af57-fdcf0fedc222.png) Try to change the display language of vscode to en, which worked on my mac. But the effects will be global in the editor.
> 
> > Would be great if somebody would advise how to solve this on MacOS.

doesn't work.

**Comment by Prashanth-BC** [comment]
For mac this worked for me:

- Uninstall the dotnet extensions (c#)
- Change the region to US. Restart the machine.
- Install the extension.
You can revert the region to your previous country.

**Comment by PaulARoy** [comment]
Hi,
Issue is still here, the workaround to delete the localized DLL worked for me.
I think locale should be configurable and/or mapped to the vs code locale.

**Comment by Ducki** [comment]
This still being unsolved officially is baffling and shows just how much Microsoft cares about C# development in VS Code.

**Comment by lghtcrss** [comment]
Issue is still there as of 02/2023. After each update I have to delete the .dlls. Please give us a possibility to set the language for omnisharp-vscode.

**Comment by domints** [comment]
+1 - what is also weird, it worked on my Mac until like... few days ago. Today I want to write some code and out of the blue all messages are in Polish. Terrible UX, amount of resources available in languages other than English are so minuscule it only makes everything harder.

**Comment by Shepherdsinan** [comment]
Hello,
I have linux Os and look path not found dll??

**Comment by In-Wake** [comment]
I'm still here in 20 24

**Comment by In-Wake** [comment]
I'm still here at 20 24

**Comment by JoeRobich** [comment]
O# does not set the CurrentUICulture so it defaults to your system locale. If this is still a problem, please open an issue at https://github.com/OmniSharp/omnisharp-roslyn/issues
