### ISSUE TITLE
Clarify Intellisense support for .NET Framework in readme

### ISSUE THREAD

**Issue by hickford** [dotnet/vscode-csharp#2523]
Hi. I think it could be helpful to clarify in the readme that the extension supports traditional .Net Framework projects. In particular, that IntelliSense, Go to Definition, Find All References work as in Visual Studio. This would be reassuring to new users who aren't familiar with .Net Core.

I remember being confused when I first tried Visual Studio Code whether Intellisense would work for .NET Framework projects. The description "Lightweight development tools for .NET Core" made me think it was .Net Core only. I was pleasantly surprised.

https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp

The guide at https://code.visualstudio.com/docs/languages/csharp could also be clarified.

**Comment by hickford** [comment]
A neat way to convey this information could be in a table

| Feature | .Net Core  | .Net Framework |
| ------ | ------------- | ------------- |
| Syntax highlighting | ✓  | ✓  |
| Intellisense  | ✓  | ✓ |
| Go to definition | ✓ | ✓ |
| Find all references | ✓ | ✓ |
| Debugger | ✓ | [*Limited*](https://github.com/OmniSharp/omnisharp-vscode/wiki/Desktop-.NET-Framework), 64-bit only |

**Comment by rchande** [comment]
@hickford Great idea! We take pull requests... 😄

**Comment by JoeRobich** [comment]
Closing due to lack of activilty.
