### ISSUE TITLE
BreadCrums class/method names are too long

### ISSUE THREAD

**Issue by Jonatthu** [dotnet/vscode-csharp#2527]
VsCode 1.27.2
Extension 1.16.1

Class names
![image](https://user-images.githubusercontent.com/3742176/45515508-32fbbb80-b75d-11e8-8c6c-c68790b6d2a8.png)

It should have only the class name `GenMockEntityUseCaseBuilder<TEntity>` instead `InterfaceFluentApi.Extensions.GenMockEntityUseCaseBuilder<TEntity>`.

Method Names
![image](https://user-images.githubusercontent.com/3742176/45515575-64748700-b75d-11e8-925e-bc191e6e4fc0.png)

It should have something like `NavigationConfig(GenMockEntityUseCaseBuilder...)`
And do ellipsis for long parameters names.

In General when names too long why not to do ellipsis on parameters or generic arguments as well.

**Comment by JoeRobich** [comment]
Cannot reproduce with current release.
