### ISSUE TITLE
extension unable to find files with incorrect case in extension

### ISSUE THREAD

**Issue by aileronajay** [dotnet/vscode-csharp#2531]
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:

## Steps to reproduce

Create a sln file and change the case in extension to "Sln"

## Expected  behavior

The extension should be able to load the Sln file with different case

## Actual behavior

The search does not find project files with incorrect case in extension. The repo i currently work with has project files with extension "Sln" instead of "sln". The omnisharp extension is unable to find these files. I can see that the search is driven by this code here, 

https://github.com/OmniSharp/omnisharp-vscode/blob/250f0288666e0630e863d7eace70ddbb16b18bbd/src/omnisharp/launcher.ts#L44

There does not seem to be an easy fix for this as I was unable to find a flag that would ignore case

**Comment by akshita31** [comment]
Unfortunately, vscode doesn't provide the capability to do a case insensitive find files. The corresponding feature request is here: https://github.com/Microsoft/vscode/issues/8666.

**Comment by JoeRobich** [comment]
Closing as this is an issue with VS Code. Track progress at https://github.com/microsoft/vscode/issues/10633
