### ISSUE TITLE
Interpolated strings: variables inside curly brackets are highlighted as regular text

### ISSUE THREAD

**Issue by Marko-Petek** [dotnet/vscode-csharp#2541]
Issue Type: <b>Bug</b>

Write code to print out an interpolated string, e.g.:
```C#
int x = 3, y = 5;
WriteLine($"Result: {{{{{x}, {y}}}, {{{y}, {x}}}}}");
```
Variables {x} and {y} are highlighted like surrounding text, making it hard to read interpolated strings with many escaped curly braces.

Extension version: 1.16.1
VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:11:15.873Z)
OS version: Linux x64 4.15.0-34-generic

**Comment by akshita31** [comment]
@rchande Should this be ported to the https://github.com/dotnet/csharp-tmLanguage repo ?

**Comment by JoeRobich** [comment]
Cannot reproduce with current release.
