### ISSUE TITLE
Provide the Package Manager Console

### ISSUE THREAD

**Issue by FranklinYu** [dotnet/vscode-csharp#2564]
This is a feature request.

It would be very helpful if this extension can provide the [Package Manager Console](https://docs.microsoft.com/en-us/nuget/tools/package-manager-console). I love PowerShell Core and it is easier to remember `Install-Package` than `dotnet package add` because I get auto-completion for free. Also compare `Add-Migration` and `dotnet ef migrations add`.

**Comment by JoeRobich** [comment]
Project and Solution manipulation features would be added to the C# DevKit extension. For C# on its own, it is recommended to use the dotnet CLI from the terminal.
