### ISSUE TITLE
Real Time Compile and Error reporting not working

### ISSUE THREAD

**Issue by RMacfarlane** [dotnet/vscode-csharp#2578]
_From @motor75 on October 2, 2018 16:22_

Issue Type: <b>Bug</b>

It seems that since I have introduced solution files (.sln) into my projects, the red squiggles that show errors as you're coding has stopped altogether.  I have multiple projects in which this is occurring.  It had been working, but seems to have stopped since I put existing projects in solutions.  I had created an ASP.NET Core Web API project and wanted to add a Unit Test project to it - thus the need for a solution file.  However, that seems to be when this issue started.  I have not yet tried uninstalling and reinstalling Visual Studio Code because I wanted to report the issue and have it be replicated so that a fix can be made. 

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2697 v3 @ 2.60GHz (2 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|8.00GB (3.99GB free)|
|Process Argv|C:\Users\moserk\AppData\Local\Programs\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nuget-package-manager|jmr|1.1.6
csharp|ms-|1.16.1

</details>

_Copied from original issue: Microsoft/vscode#59836_

**Comment by akshita31** [comment]
@motor75 What is the C# extension version you are using? Also could you post the output from your OmniSharp log(View--> Output--> OmniSharp log)

**Comment by akshita31** [comment]
@motor75 It seems that the OmniSharp process is crashing for some reason, due to which you are losing the intellisense. We have seen this issue in Mac/Linux , but this is the first time the error reproduces on Windows. Can you provide a minimum repro project that would help us debug the issue.

Also can you set, Omnisharp.logginglevel--> Debug and then "Restart OmniSharp" and then paste the output from omnisharp log when the crash happens.

**Comment by motor75** [comment]
@akshita31 The projects that I'm working on contains confidential information that I would not be able to share.  However, I have set the logging level to debug and will post the Omnisharp logs when the issue reoccurs.  Thanks!

**Comment by motor75** [comment]
@akshita31 The error has reproduced itself.  I have attached the log file - if you open it up, near the top the issue starts at line 316 (around 16:28 10-19-2018).    Below I pasted what's showing in the OmniSharp log (as you can see, there's no errors).  

Just FYI - this is happening on the 3 projects/solutions that I work on - so I don't think this is a problem with the projects. 

Starting OmniSharp server at 10/19/2018, 3:01:32 PM
    Target: c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest.sln

OmniSharp server started.
    Path: C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\.omnisharp\1.32.5\OmniSharp.exe
    PID: 2644

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Enterprise 2017 15.7.27703.2018 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin"
            2: StandAlone 15.0 - "C:\Users\moserk\.vscode\extensions\ms-vscode.csharp-1.16.2\.omnisharp\1.32.5\msbuild\15.0\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Enterprise 2017 15.7.27703.2018 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest\cdmrest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest.tests\cdmrest.tests.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm' on host 8700.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest\cdmrest.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest\cdmrest.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest\cdmrest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest.tests\cdmrest.tests.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest\cdmrest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest\cdmrest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest\cdmrest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest\cdmrest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest.tests\cdmrest.tests.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest.tests\cdmrest.tests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: cdmrest
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: cdmrest.tests
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.RunCodeActionService
        Applying code action: using Microsoft.Extensions.Configuration;
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.RunCodeActionService
        Applying code action: using CDMRest.Controllers;
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.RunCodeActionService
        Applying code action: using Moq;
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.RunCodeActionService
        Applying code action: using Microsoft.Extensions.Logging;
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.RunCodeActionService
        Applying code action: using CDMRest.Repositories;
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest.tests\cdmrest.tests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest.tests\cdmrest.tests.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest.tests\cdmrest.tests.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: cdmrest.tests
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.RunCodeActionService
        Applying code action: using Microsoft.AspNetCore.Mvc;
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.RunCodeActionService
        Applying code action: using System.Net;
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.RunCodeActionService
        Applying code action: using Microsoft.AspNetCore.Http;
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest.tests\cdmrest.tests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest.tests\cdmrest.tests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest\cdmrest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest\cdmrest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest.tests\cdmrest.tests.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest\cdmrest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest.tests\cdmrest.tests.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest\cdmrest.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest\cdmrest.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: cdmrest.tests
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: cdmrest
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest\cdmrest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest.tests\cdmrest.tests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest\cdmrest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest.tests\cdmrest.tests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest\cdmrest.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest\cdmrest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest\cdmrest.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest.tests\cdmrest.tests.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest.tests\cdmrest.tests.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: cdmrest
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: cdmrest.tests
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest\cdmrest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest\cdmrest.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest\cdmrest.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: cdmrest
[info]: OmniSharp.DotNetTest.VSTestManager
        read: {"MessageType":"TestSession.Connected","Payload":null}
[info]: OmniSharp.DotNetTest.VSTestManager
        read: {"MessageType":"ProtocolVersion","Payload":1}
[info]: OmniSharp.DotNetTest.DebugSessionManager
        Debug session started.
[info]: OmniSharp.DotNetTest.DebugSessionManager
        Debug session ended.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest\cdmrest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest\cdmrest.csproj
[info]: OmniSharp.DotNetTest.VSTestManager
        read: {"MessageType":"TestSession.Connected","Payload":null}
[info]: OmniSharp.DotNetTest.VSTestManager
        read: {"MessageType":"ProtocolVersion","Payload":1}
[info]: OmniSharp.DotNetTest.DebugSessionManager
        Debug session started.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\moserk\Documents\GitHub\CDM .NET Core\eti-cdm\cdmrest\cdmrest.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: cdmrest
[omnisharp_errors.txt](https://github.com/OmniSharp/omnisharp-vscode/files/2497305/omnisharp_errors.txt)

**Comment by akshita31** [comment]
@motor75 Did you set omnisharp.loggingLevel --> Debug ?

**Comment by motor75** [comment]
I had only the user setting set to debug; workspace was set to informational.  I set both to debug as I assume that the workspace setting overrode the user setting (although that isn't entirely clear on the settings U/I).

**Comment by motor75** [comment]
@akshita31 The issue has come up again - I attached the log (Window) output and the Omnisharp Log output.  Let me know if you need anything further from me.  Thanks!
[omnisharp_errors.txt](https://github.com/OmniSharp/omnisharp-vscode/files/2567273/omnisharp_errors.txt)
[Uploading omnisharp_log.txt…]()

**Comment by akshita31** [comment]
@motor75 Are you working with the latest version of the extension ?

**Comment by motor75** [comment]
@akshita31 - I'm back to getting errors in the logs with real time compiling and error reporting not working.  I get no intellisence either.  I completely uninstalled Omnisharp, deleted the extensions directories in my .vscode folder under my user and reinstalled the extension but that did nothing to change the issue.  Attached is the error log.  Any thoughts as this is getting to make this extension not usable.  
[omnisharp_errors.txt](https://github.com/OmniSharp/omnisharp-vscode/files/2814047/omnisharp_errors.txt)

**Comment by akshita31** [comment]
@motor75 Do you have an [OmniSharp log](https://github.com/OmniSharp/omnisharp-vscode/wiki/Reporting-Issues#omnisharp-and-c-log). Please post the output from that and sorry I couldnt keep track of this one

**Comment by motor75** [comment]
@akshita31 I only have what I provided above unless you can point me somewhere on my HDD where the log is located.

**Comment by JoeRobich** [comment]
A lot has changed with project loading since this issue was opened. If you are still running into problems, please open a new issue.
