### ISSUE TITLE
Spurious warnings from automatically generated files

### ISSUE THREAD

**Issue by PeteX** [dotnet/vscode-csharp#2581]
## Environment data
`dotnet --info` output:

.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.403/

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.403 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

VS Code version: 1.27.2
C# Extension version: 1.16.1

## Steps to reproduce

Turn "Suppress Hidden Diagnostics" off in the VSCode C# extension.

Use `dotnet new` to create the ASP.NET Core Empty project type.  Run the project and open it in VSCode.

## Expected  behavior

Warnings about "unnecessary using directives" should only be displayed for source code which is intended to be edited by the programmer.

## Actual behavior

Warnings are displayed for various automatically generated files.

I understand that some people dislike the warnings about unnecessary using directives, and that's why they are hidden by default.  Personally though I feel that unused imports represent untidy code and should be removed.  Obviously I don't hold automatically generated files to the same standard, but it's distracting if I get warnings about those files, given that I'm unable to fix the problem.

I would be happy if the C# extension worked the same way as the Typescript one, showing unnecessary imports in a darker colour, without any actual diagnostic.  As I understand it, though, this is not possible with C# at the moment.  You only have the option of a diagnostic message or nothing, and if there is no message at all, it's difficult to work out which directives are needed and which are not.

Thank you for all your work on VSCode and I hope this report is helpful.

**Comment by JoeRobich** [comment]
A lot has changed with how O# determine diagnostics since this issue was opened. If you are still running into problems, please open a new issue.
