### ISSUE TITLE
Go to Implementation should consider generic type arguments

### ISSUE THREAD

**Issue by RoarkeRandall** [dotnet/vscode-csharp#2598]
## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.302/

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.300 [/usr/local/share/dotnet/sdk]
  2.1.302 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

VS Code version: Version 1.27.2 (1.27.2)
C# Extension version: 1.16.2

## Steps to reproduce
1. Create an interface such as:

```
 IMapper<TSource, TDestination>
```

2. Implement IMapper more than once with different types for TSource and TDestination
3. have a member of a class be of type IMapper<SomeSourceType, SomeDestinationType> that was implemented in step 2.
4. Initiate "go to implementation" on the member from 3

## Expected  behavior
Only the implementation of IMapper with the correct type arguments results should show up in the results of go to implementation

## Actual behavior
All classes that implement IMapper (any type arguments) will show up in the results.

**Comment by motion-x86** [comment]
Any updates on this thread? This feature is hugely needed! Currently it is extremely painful to navigate code which uses generic interfaces.

**Comment by JoeRobich** [comment]
The O# behavior matches the Roslyn LSP. This would be a request for Roslyn. Feature requests can be made at https://github.com/dotnet/roslyn/issues
