### ISSUE TITLE
Problems are only reported on currently open files (Unity?)

### ISSUE THREAD

**Issue by AgStarRay** [dotnet/vscode-csharp#2627]
## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.403\

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
VS Code version: 1.28.2
C# Extension version: 1.17.0-beta7

## Steps to reproduce
This issue might be in just Unity projects, but the Problems section is always empty until I open a file with problems in it.
1. Create a Unity project.
2. Open the project folder in VS Code (so that Omnisharp loads the .sln).
3. Create a C# class and add syntactically incorrect code. Notice that it's red underlined and reported in Problems.
4. Close the file. The Problems section empties out.
5. Open the file again. The problem reappears.

## Expected behavior
Problems should be reported from any file in the .sln.

## Actual behavior
Problems are only reported in opened files in the folder, making you more likely to create problems in other files that depend on what you edited without you knowing.
I would like to point out that I opened up an old project in VS Code. The project had like 310 problems without any files open, and when I opened the project with a newer version of Unity, it went back to 0 problems and the behavior explained above. So it could be an incompatibility with Unity 2018.2.13f1 (or it could be Unity's fault).

**Comment by rchande** [comment]
@akshita31 Can you try to reproduce this?

**Comment by wraithseeker** [comment]
I'm also having the same problem on Unity 2017.4.10f1.

**Comment by Perdek** [comment]
Same problem on Unity 2018.1.9f1 with VSCode 1.29.1 and C# 1.17.1

**Comment by akshita31** [comment]
@RayRay26 Is it possible to provide a sample repro project to help me understand the issue better?

**Comment by mim889** [comment]
Same problem on Unity 2018.1.9f1 with VSCode 1.29.1 and C# 1.17.1

**Comment by JoeRobich** [comment]
A lot has changed with how O# performs analysis. If you are still having problems, please open a new issue. Recommend using the Unity extension for VS Code.
