### ISSUE TITLE
Set root namespace of a project

### ISSUE THREAD

**Issue by roblourens** [dotnet/vscode-csharp#2675]
_From @ruimaciel on November 13, 2018 11:43_

When using VS Code 1.28.2 to work on C# projects, apparently the default root namespace adopted by a project is deduced from the project tree structure.  However, some projects happen to have root namespaces that don't match the projec tree.  It would be nice if VS Code enabled developers to specify the root namespace of a project.

Some online comments mention the existence of an option labelled `RootNamespace` supported by csproj files.  However, the contents of that variable have no effect on VS code commands such as "new C# class". 

It would be very helpful if VS Code offered a way to configure the root namespace of a project, or even the default namespace used in specific folders of a project.  Supporting third-party data sources such as the contents of csproj files would be ideal, but being able to specify this sort of option in the contents of .vscode would work as well. 

_Copied from original issue: Microsoft/vscode#63018_

**Comment by taylordevereaux** [comment]
Is this ever going to be worked on?

**Comment by WellspringCS** [comment]
Agreed, this would be a nice feature. I assumed it was present, but upon finding this issue, I guess I assumed too much.

**Comment by CrossBound** [comment]
upvote... I would love to have this feature

**Comment by DominicBoettger** [comment]
Any news here?

**Comment by JoeRobich** [comment]
The RootNamespace property is a supported property. For instance, when generated code such as Resource (.resx) classes are generated, they are generated under that root namespace. Another example is the sync namespace refactoring also uses this property.

In the dotnet/format project I added `Foo` as the RootNamespace and this is the suggested refactoring.
![image](https://user-images.githubusercontent.com/611219/81601968-a580cc80-9380-11ea-8bec-17a5dbd721fc.png)


The `New C# Class` command in question is not part of this extension, instead it seems to be from an extension called "C# Extensions".
![image](https://user-images.githubusercontent.com/611219/81593408-42893880-9374-11ea-8321-c23d30226b11.png)

**Comment by KreativJos** [comment]
This has been resolved in the 'C# extensions' extension. 
I still think these commands should be included in the omnisharp-vscode extension.

**Comment by SheepReaper** [comment]
I have v2.0.283 pre release. Had to upgrade to work with new .net8 stuffs and things. This caused a lot of confusion for me. Many of the project templates don't include <RootNamespace> as it's assumed to be the assembly name (default). All the intellisense is broken in the blazor template if your project is located anywhere besides the workspace root. Adding the RootNamespace key in the project file fixes it, though technically it's redundant as that's already the implicit value when not specified. I'd like the extension to mimic the visual studio behavior where the RootNamespace is the assembly name if not specified.

**Comment by dibarbet** [comment]
Closing.  This is resolved in C# Dev Kit via the specialized add file commands in the solution explorer.  The class templates will respect the `RootNamespace` property, see the following gif.

![cdk_rootnamespace](https://github.com/user-attachments/assets/ea396f2c-8700-4def-9393-3f98d173c030)

The C# extension standalone does not add any special new file commands beyond what VSCode offers, and as far as I know there is no way for the extension to customize the built in add file commands.

If you're having specific issues with the C# Dev Kit new file commands, please file an issue at https://github.com/microsoft/vscode-dotnettools/issues.

If the C# extension isn't respecting the root namespace it in some manner (for example in a code actions), please file a new issue in this repo.  

Thanks!
