### ISSUE TITLE
Validate OmniSharp payload

### ISSUE THREAD

**Issue by rchande** [dotnet/vscode-csharp#2694]
https://github.com/OmniSharp/omnisharp-vscode/issues/2690 is an example of an issue where the OmniSharp download was either incomplete or did not extract properly. Let's consider adding a mechanism to validate that the download resulted in the correct directory structure.

**Comment by rchande** [comment]
@akshita31 Any big brainthoughts here?

**Comment by akshita31** [comment]
Steps:

- [ ] Add the check in the extension for the integrity
- [ ] Update omnisharp to produce the integrity check sum
