### ISSUE TITLE
VSCode spawns a dontet process which locks dotnet obj folder

### ISSUE THREAD

**Issue by alexr00** [dotnet/vscode-csharp#2701]
_From @ivaylo5ev on November 22, 2018 13:17_

- VSCode Version: 
    1.29.1
- OS Version: 
    Windows 7 Professional
    Windows 8.1 Home

Steps to Reproduce:

1. Open a VSCode workspace or a folder with dotnet projects/solutions
2. At some point a child dotnet process is being spawned (process explorer would show it under some of the VSCode's sub-processes)
3. Some of the project's obj directory remains locked. This results in the following issues:
    - manual package updates, for instance when using paket would fail (ex. `paket update` / `paket install` )
    - manual `dotnet restore` calls would fail
4. Killing the dotnet process would resolve the issue -- the above commands would then run successfully, but the dotnet process is being immediatelly restarted and would cause the lock again after some time

Does this issue occur when all extensions are disabled?: No

It is inthuitive to believe this is caused by an extension that supports dotnet development, but I have quite a few of them installed -- OmniSharp, Ionide-FSharp and so on. Is there a way to determine which one of them is calling the misbehaving dotnet process, so at least the issue would be directed at the extension developer?

_Copied from original issue: Microsoft/vscode#63649_

**Comment by alexr00** [comment]
_From @vscodebot[bot] on November 22, 2018 13:17_

(Experimental duplicate detection)
Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
- [Using Dotnet Core in WSL causes VSCode to highlight everything (#57698)](https://www.github.com/Microsoft/vscode/issues/57698)

**Comment by alexr00** [comment]
_From @alexandrudima on November 23, 2018 12:42_

@alexr00 @ivaylo5ev  This should be moved to https://github.com/OmniSharp/omnisharp-vscode

**Comment by rchande** [comment]
@ivaylo5ev Are you using the "run unit tests" code lens? I don't think OmniSharp starts dotnet.exe until you do that.

**Comment by ivaylo5ev** [comment]
@rchande, no. I mostly use it as a text editor. In my setup I have a solution with multiple projects, some of them in C#, some in F# (so it could be an FSharp extensions starting it). Furhtemore, I am using the new dotnet sdk for all projects and am targetting multiple framework versions. Not sure if the last info could help

**Comment by JoeRobich** [comment]
A lot has changed with project loading and watching since this issue as opened. If you are still running into problems, please open a new issue.
