### ISSUE TITLE
Snippet completions appear inside comments.

### ISSUE THREAD

**Issue by pushqrdx** [dotnet/vscode-csharp#2765]
## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.101
 Commit:    236713b0b7

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.101/

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  2.2.101 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

VS Code version: 1.30.1
C# Extension version:  1.17.1

## Steps to reproduce
Inside comments i get snippet completions, I have no C# related extensions installed other than omnisharp.

## Expected  behavior
In comments there shouldn't be any completions at all or at least upon manually invoking them.

## Actual behavior
Snippet completions appear inside comments.

**Comment by sanboxrunner** [comment]
Deeply irks me. Periods in comments always end up `.abstract`

**Comment by rchande** [comment]
@akshita31 Can you figure out if we're providing these or if VS Code is?

**Comment by ru-ace** [comment]
Not only comments.  stings also affected:
![image](https://user-images.githubusercontent.com/10783157/50763999-7cc75f00-1282-11e9-9392-2f2456dd29a3.png)

**Comment by ru-ace** [comment]
And my favorite - just reaction on space
![image](https://user-images.githubusercontent.com/10783157/50764112-ce6fe980-1282-11e9-857d-6b2b37030ccf.png)

**Comment by ru-ace** [comment]
@rchande  This is extension: if i disable this behavior disappears.

**Comment by ru-ace** [comment]
Found quick fix until this issue will fixed:
Set in settings `"editor.snippetSuggestions": "none"`

**Comment by pushqrdx** [comment]
@ru-ace I can live without snippets for the time being, because having auto complete popping up on every space bar is so annoying 😂

**Comment by SittenSpynne** [comment]
I had inadvertently filed this against VSCode and they insist it's the extension. (See also for a screen capture of the issue in action: https://github.com/Microsoft/vscode/issues/67271)

It's really frustrating.

**Comment by sanboxrunner** [comment]
It is 100% this extension. It is sending out snippets and not respecting
VSC's "snippets should not block autocomplete" setting

**Comment by rchande** [comment]
@jrieken We provide snippets in the form of json files/snippets entry in our package.json (https://github.com/OmniSharp/omnisharp-vscode/blob/master/snippets/csharp.json) and (https://github.com/OmniSharp/omnisharp-vscode/blob/master/package.json#L830). They seem to show up in comments even though we don't provide any other C# intellisense in comments. I think this is happening because
* C# intellisense isn't provided in comments, so VS Code provides token-based intellisense (see screenshot)
* The snippet completion provider detects a non-empty list and provides snippets

![image](https://user-images.githubusercontent.com/3751401/52010136-94f95b00-2489-11e9-9058-479164e089dd.png)


What can we do to make this not happen? This basically seems like a limitation in the VS Code platform to me--I don't see anything in the docs that allows us to control where a snippet is shown.

**Comment by sanboxrunner** [comment]
Thank you for the work on this!

**Comment by pushqrdx** [comment]
@rchande disabling snippets globally does affect lots of other languages, it becomes so frustrating if you do anything besides C# in vscode. I hope it gets fixed 😅

**Comment by JulianGmp** [comment]
I'm not sure if this is conneced to this issue, but I sometimes get similar behaviour with dots, which gets a bit frustrating when working with C# 8 Ranges.

For example, typing `0..^2` might become `0.Equals.^2`.

**Comment by pushqrdx** [comment]
@JulianGmp yeah they closed the issue while it's not solved, i get the same behavior, other language servers don't seem to exhibit this behavior

**Comment by JulianGmp** [comment]
@pushqrdx this issue isn't closed though? Or do you mean a different one?

**Comment by pushqrdx** [comment]
@JulianGmp you know what, i totally flopped, i literally thought my issue was close sorry for that
