### ISSUE TITLE
Lag in updating the problems windows in vscode

### ISSUE THREAD

**Issue by guylando** [dotnet/vscode-csharp#2773]
Using dotnet 2.1.500 and c# extention 1.17.1.
There is a substantial delay between the time I type code until problems detected are shown in the problems windows and same delay between the time I fix code problem and the problem being removed from problems window. Any way to fix this to make the problems window linting more real-time?

**Comment by kevin-grey-genesys** [comment]
any update on this? I am seeing a problem when switching branches. The problems window errors seem to relate to code from the other branch. If I run a reload window from the command palette then this clears the problems

**Comment by geekley** [comment]
See also #4867

**Comment by JoeRobich** [comment]
A lot has changed with code analysis since this issue as opened. If you are still running into problems, please open a new issue.
