### ISSUE TITLE
Configuration variable not set to default value Debug

### ISSUE THREAD

**Issue by donile** [dotnet/vscode-csharp#2783]
## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.1.502
 Commit:    c74ce8f29f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.502\

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

VS Code version: 1.30.1

C# Extension version: 1.17.1

## Steps to reproduce
1. Construct MSBuild files (.csproj, Directory.Build.props, etc.) omitting Configuration variable
2. Start (or restart) Omnisharp
3. Output and intermediate files copied to path omitting Configuration variable

From Directory.Build.props
`<BaseOutputPath>../../artifacts/bin/$(Configuration)/$(MSBuildProjectName)</BaseOutputPath>`

From .csproj file
`<OutputPath>$(BaseOutputPath)</OutputPath>`

## Expected  behavior
Executing `dotnet build` from the command line sets the MSBuild configuration variable to Debug by default

Binary files output to:
`./artifacts/bin/Debug/<MSBuildProjectName>/<TargetFramework>`

## Actual behavior
Binary files output to path omitting Configuration variable:
`./artifacts/bin/<MSBuildProjectName>/<TargetFramework>`

**Comment by JoeRobich** [comment]
Build configuration can be set as part of the MSBuild options in your omnisharp.json. See https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options#msbuild
