### ISSUE TITLE
Intellisense brings up list when pressing "space" which is not intelligent

### ISSUE THREAD

**Issue by sanbox-irl** [dotnet/vscode-csharp#2789]
## Environment data
`dotnet --info` output:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.101
 Commit:    236713b0b7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.101\

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

VS Code version: 1.30.2
C# Extension version: 1.17.1

## Steps to reproduce
When typing, hitting space brings up a list of common control phrases (things like "if" "do" else" etc.). This makes it so when I type, for example, a parameter type which is not a basic type, and then hit space, I want to type one letter (such as `BaseCursor baseCursor`) and get the autocomplete to finis hthat up for me. Unfortunately, I have this list of basic control words. I don't get the intellisense that I want until I hit escape or type through all the control words, then omnisharp will recompute more intellisense which will be appropriate. Here's a GIF to make it clear what I'm doing:

![fctpsmcmnm](https://user-images.githubusercontent.com/31973761/51061744-3b0c2080-15c2-11e9-83b0-b613af0d7fed.gif)

Notice how after hitting space after typing "Coordinate" I didn't get "coordinate". 

## Expected  behavior
I except to get intellisense mixed in with the basic control phrases.

## Actual behavior
I only get the control phrases.

**Comment by sanboxrunner** [comment]
That does fix it, and thank you for htat, but this is definitely different behavior from other VSC extensions, like the native JS/TS server. Nonetheless, I do appreciate the advice!

**Comment by sanboxrunner** [comment]
Yes, as I review this, this behavior is definitely sub-optimal. By removing the snippets, I now do have a more comfortable typing experience, but, of course, I've lost the snippets! Sometimes those are useful -- control keywords still do appear, but not the snippets themselves.

Other services, like the TS engine, provide the snippets and the intellisense together. Changing all relevant VSC settings doesn't produce that behavior

**Comment by Marchyello** [comment]
Thank you so much for this. This has been bothering me to no end lately. Was sure it was a bug, turns out *it's not a bug, it's a feature*. :)

**Comment by JoeRobich** [comment]
A lot has changed with completion since this issue was open. If you are still seeing problems, please open a new issue.
