### ISSUE TITLE
Feedback on VS Code proposed Code Action Auto Fix APIs

### ISSUE THREAD

**Issue by mjbvz** [dotnet/vscode-csharp#2796]
Hi, I'm on the VS Code team. We are exploring extending VS Code's code actions to support automatic fixes and auto fix on save. You can find the two current proposal [here](https://github.com/Microsoft/vscode/issues/62110#issuecomment-454182230)

Your extension is a large user of code actions so we'd appreciate your feedback on these API proposals. Here are example use cases for these two areas:

- For auto fix: I write the c# `Consoul.WriteLine("Hello World!");` and see red squiggle in the editor. I F8 to the error and then use a single keyboard shortcut to auto correct `Consoul` to `Console`. This spelling fix has been marked as the preferred auto fix by your extension. If I wanted to instead apply one the `Generate` quick fixes, I could use the existing lightbulb menu

- For fix all: I'm writing some C# code but forget about adding semicolons and now I've written one hundred lines of semicolon-less code. Thankfully, I've enabled `"editor.codeActionsOnSave": { "source.autoFix": true }` and your extension provides an `autofix` code action. This autofix action looks through the entire document and fixes all trivial errors (such as adding semicolons in safe places) in a single pass. All I need to do is save the file and the semicolons are magically added!

[This guide](https://code.visualstudio.com/api/advanced-topics/using-proposed-api) covers how to use VS Code's proposed APIs. Please let me know if you have any questions about these proposals, feedback on the API, or ideas for other auto-fix scenarios that you would like to see supported in VS Code

**Comment by JoeRobich** [comment]
Fix all is supported in the current release.
