### ISSUE TITLE
Doesn't show references to symbols in referenced projects.

### ISSUE THREAD

**Issue by Fritzoid** [dotnet/vscode-csharp#2800]
Hi, 

I have a solution with several projects, and everything loads fine. The projects reference each other, like normal solutions usually do. All files seem to find references and shows them in the UI. 

I've noticed that the references to symbols shown in the UI only reference 
inside the same project. Cross project references are never shown, so you cant see if another project uses class x etc.

Is that the intended behavior?  If no, what could be wrong?

**Comment by rchande** [comment]
@fritzoid Do you mean references in the "References code lens" or in the "Find all reference" view?

**Comment by Fritzoid** [comment]
Hi :) I mean the references that show up as 'x references' above ie. classnames. I guess that's the reference code lens?

**Comment by Fritzoid** [comment]
Just had an idea. Could it be because all project references are direct dll references pointing at the output dir? I have another codebase thats pure dotnet core and using project references that point to the project file where everything seems to work properly.

**Comment by Fritzoid** [comment]
Oh, but it is. Bigger projects like that one usually do it that way. At least, thats what ive seen many times. We have 900+ projects, and we dont even have a solution file. I made the sol file myself in the root folder. 

Anyways, is that way of doing it not supported? In visual studio 2017 with resharper, it 'works'. At least until it crashes ;) The good thing is in vscode, it doesnt crash, and seems to work well since it loads all the projects. But the referencing is bugging me, because the reason i wanted to try this is to have a tool where you can say 'Where is this class used', short of grepping it out, which is limited.

**Comment by JoeRobich** [comment]
A lot has changed since this issue was opened. If you are still seeing problems, please open a new issue.
