### ISSUE TITLE
Code Lens does not accurately count override references.

### ISSUE THREAD

**Issue by JonathanPalmerGD** [dotnet/vscode-csharp#2810]
## Environment data
`dotnet --info` output:

VS Code version: Code - Insiders 1.30.2 (user setup)
commit: 61122f8
Date: 2019-1-07
Chrome: 61.0.3163.100
OS: Windows_NT x64 10.0.17763

C# Extension version: 1.17.1

## Steps to reproduce
Create an empty Unity Project (U2018.2 for my test case). Unity may or may not be a related part of the problem.
Create a script, make it an abstract base class. Give it an abstract public function.
Create a child class script. Have it override the abstract function.
Create a third class, it utilizes the child class's override function.

Code Lens should show all 3 references of that function's override hierarchy, instead it will only show the utilizer's reference if you click on the grey Code Lens text of (1 reference).

Here is an example:
![image](https://user-images.githubusercontent.com/2644214/51647253-e5743400-1f30-11e9-866a-5f59e638dd2f.png)

![image](https://user-images.githubusercontent.com/2644214/51647245-dee5bc80-1f30-11e9-9fd8-7532448603ff.png)

## Expected  behavior
In my given example, you should see three references, once to the abstract class, once to the override and once to the usage.

## Actual behavior
Only the implementation is displayed in the dropdown window.
See example image.

**Comment by SirIntruder** [comment]
You can find overrides in child classes through "find implementations" command, which is usually binded to ctrl+shift+f12. Implementations are not counted toward normal references in shift+f12, and I suspect "find all references" is executed by vscode as a superset of those two commands.

It would be nice if c# extension had an option for implementations code lens, as in typescript:

![2019-02-07_20-28-34](https://user-images.githubusercontent.com/5102661/52437357-fe770a80-2b16-11e9-9892-8f78c757abd3.png)

**Comment by JoeRobich** [comment]
A lot has changed since this issue was opened. If you are still having problems, please open a new issue.
