### ISSUE TITLE
Feature request: inline parameter name hints

### ISSUE THREAD

**Issue by cilerler** [dotnet/vscode-csharp#2823]
Please implement [inline parameter name hints](https://blog.jetbrains.com/dotnet/2018/11/27/inline-parameter-name-hints-c-vb-net-resharper-rider/)

Here is a comparison between Visual Studio w/ Resharper and VSCODE on inline parameter name hints.

the (2) demonstrates `eventType:` which is manually added by me and if you save the file and open it from **Notepad**, it will not be there.

the (1) demonstrates `message:` as automatically added by IDE and it is just a virtual thing.  If you save the file and open it from **Notepad**, it will not be there.

![image](https://user-images.githubusercontent.com/385958/51806890-93dbea00-224d-11e9-94fa-e3376dc277e9.png)

**Comment by bzrncev** [comment]
I just switched to VS Code and was missing this feature, so I implemented it myself. Still in beta, but workable: https://marketplace.visualstudio.com/items?itemName=BobbyZrncev.intellij-parameter-hints

**Comment by dmedeiros777** [comment]
Ótimo recurso. Faz muita falta para desenvolvedores .NET

**Comment by petr166** [comment]
Please add this, it would be very helpful 👍

**Comment by ZacharyPatten** [comment]
whenever this feature is added, I'm hoping we could also get type hints too

type hints would fill in "TYPE" in the following:
```cs
var TYPE a;
string b = new TYPE();
Func<int, int> c = TYPE x => x;
```

**Comment by azunyuuuuuuu** [comment]
As of version 1.65.0 of VS Code the API is finalized. See here for the relevant release notes: [https://code.visualstudio.com/updates/v1_65#_inlay-hints](https://code.visualstudio.com/updates/v1_65#_inlay-hints)
