### ISSUE TITLE
Make OmniSharp "latest" more reliable

### ISSUE THREAD

**Issue by johnnyasantoss** [dotnet/vscode-csharp#2834]
I'm using the settings `"omnisharp.path": "latest"` and my VS Code can't download the latest version and it might be related to the CDN that provides the download files.
I've search a bit and found that this already happened a few times (#2681, #2738 & #2741).

#### Omnisharp Log:
```log
Error occured in loading omnisharp from omnisharp.path
Could not start the server due to Error: 404
```
#### C# Log:
```log
Getting latest OmniSharp version information
Downloading package 'Latest OmniSharp Version Information' (1 KB).................... Done!
Installing OmniSharp Version = 1.32.11-beta.1...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64), Version = 1.32.11-beta.1' Failed to download from https://roslynomnisharp.blob.core.windows.net/releases/1.32.11-beta.1/omnisharp-win-x64.zip. Error code '404')
Failed at stage: downloadAndInstallPackages
404
```

#### The output from URL (https://roslynomnisharp.blob.core.windows.net/releases/1.32.11-beta.1/omnisharp-win-x64.zip)
```log
BlobNotFoundThe specified blob does not exist.
RequestId:39f4cf1b-101e-005b-4a7c-b9e374000000
Time:2019-01-31T15:50:50.9362539Z
```

**Comment by FomTarro** [comment]
I too am experiencing this as of today. I suspect this is related to the CDN. even using older specified versions produces the same result.

**Comment by akshita31** [comment]
Getting latest OmniSharp version information
Downloading package 'Latest OmniSharp Version Information' (1 KB).................... Done!
Installing OmniSharp Version = 1.32.11-beta.1...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64), Version = 1.32.11-beta.1' (30604 KB).................... Done!
Installing package 'OmniSharp for Windows (.NET 4.6 / x64), Version = 1.32.11-beta.1'

Finished

Please feel free to reopen if it occurs again

**Comment by johnnyasantoss** [comment]
Today it is working 🤔 
That's a very weird behavior for an automated process (deploy to CDN)

**Comment by johnnyasantoss** [comment]
Thank you @akshita31 😃

**Comment by apkd** [comment]
Omnisharp has stopped working for me after installing (and removing) the .NET Core 3.0 preview a few weeks ago, and using "latest" was the only way I could get it to work (re-installing the C# vscode extension didn't help).

Now (since yesterday) I can't even download the "latest" build. Thus, I am currently completely unable to use Omnisharp because of this issue.

```
Getting latest OmniSharp version information
Downloading package 'Latest OmniSharp Version Information' (1 KB).................... Done!
Installing OmniSharp Version = 1.32.12-beta.51...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.6 / x64), Version = 1.32.12-beta.51' Failed to download from https://roslynomnisharp.blob.core.windows.net/releases/1.32.12-beta.51/omnisharp-win-x64.zip. Error code '404')
Failed at stage: downloadAndInstallPackages
404
```
```
Error occured in loading omnisharp from omnisharp.path
Could not start the server due to Error: 404
```

**Comment by FomTarro** [comment]
Same. It's infuriating that VS can't cache a version.

**Comment by NTaylorMullen** [comment]
Could have a 12-24 hour delay after receiving a new "potential latest" to then promote it to a latest available version. I'd be shocked if cdns didn't pick that up by then.

**Comment by filipw** [comment]
I restarted the build, and the latest is available now - sorry for the trouble.

**Comment by FomTarro** [comment]
Seems to be down again. Was working for most of this evening, but the 404 error has returned. Is there really no way to cache this? Seems weird to require server auth just to use an IDE.

Or maybe I misunderstand.

**Comment by Fubuchi** [comment]
You guys can check for all available version here : https://roslynomnisharp.blob.core.windows.net/releases?restype=container&comp=list

The latest beta version available for windows is `1.32.12-beta.51` so set `"omnisharp.path": "1.32.12-beta.51"` do the trick and allow you to continue your work while waiting for the fix.

**Comment by stijnherreman** [comment]
https://github.com/OmniSharp/omnisharp-roslyn/releases/tag/v1.37.6 was released 4 days ago, but it doesn't seem to be available yet in Blob Storage.

> Installing OmniSharp Version = 1.37.6...
> Platform: linux, x86_64, name=debian, version=10
> 
> Downloading package 'OmniSharp for Linux (x64), Version = 1.37.6' Failed to download from https://roslynomnisharp.blob.core.windows.net/releases/1.37.6/omnisharp-linux-x64.zip. Error code '404')
> Failed at stage: downloadPackage
> 404

Only the betas are available according to the list.

**Comment by JoeRobich** [comment]
Cannot reproduce with the current release.
