### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by nbonacchi** [dotnet/vscode-csharp#2847]
- Issue Type: `Performance`
- Extension Name: `csharp`
- Extension Version: `1.17.1`
- OS Version: `Linux x64 4.18.0-15-generic`
- VSCode version: `1.31.0`

[ms-vscode.csharp-unresponsive.cpuprofile.txt](https://github.com/OmniSharp/omnisharp-vscode/files/2846466/ms-vscode.csharp-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by akshita31** [comment]
@nbonacchi Can you try upgrading to the latest mono version as suggested [here](https://github.com/OmniSharp/omnisharp-vscode/issues/2794#issuecomment-457050038) and checking if the problem still persists.
Also, we have a [beta release](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.18.0-beta7) containing major improvements on the code load times. You can install it by following the instructions [here](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases). Please let us know if that helps.

**Comment by JesseTG** [comment]
I have this same issue with Mono 5.18.

**Comment by joshampton** [comment]
* Issue Type: `Performance`
* Extension Name: `csharp`
* Extension Version: `1.18..0-beta7`
* OS Version: `Windows_NT x64 10.0.17134 `
* VSCode version: `1.31.0 (user setup)`

Here's my omnisharp configuration:

**Comment by akshita31** [comment]
@jrieken I downloaded the profile above that @joshampton uploaded and 96% of the time is consumed by (program). As per https://stackoverflow.com/questions/3847954/what-is-program-in-chrome-debugger-s-profiler this is the program itself. Does that mean it is vscode that is consuming time here ?

**Comment by jrieken** [comment]
Hard to say, generally it should be understood as time is spend outside JS-land, eg inside native land. This can be garbage collection or IPC message overflow. If you zoom in a lot you that some calls are interleaved with something I suspect as omnisharp message handling. Would it be possible that the omnisharp server send a lot of data?

<img width="645" alt="screenshot 2019-02-13 at 08 44 27" src="https://user-images.githubusercontent.com/1794099/52694955-9471c180-2f6b-11e9-9bdc-e9cfe8dce200.png">

**Comment by akshita31** [comment]
@jrieken Yeah omnisharp pushes a lot of messages and that might be the reason for this. I will investigate further into this. Thanks!

**Comment by floyd-may** [comment]
Does anyone have any recommendations for a workaround? I've got both Windows and Mac users on my team that are experiencing issues.

**Comment by akshita31** [comment]
@floyd-may I suspect the slow down maybe because omnisharp is sending a lot of messages. Could you try setting "omnisharp.loggingLevel" : error and restart vscode. That way it will only log error messages and might be faster

**Comment by floyd-may** [comment]
After a couple hours (I set it to `warning` because I have issues with following instructions 🙃 ) it's behaving better. Seems to be a reasonable workaround. I'll report back if I have more issues.

**Comment by joshampton** [comment]
despite setting the logging level to error, I'm still running into the same symptoms. Curiously, I'm running into this on my mac at work. Curiously it looks like `mono-sgen64` is eating a ton of CPU.
![Screen Shot 2019-04-16 at 1 02 53 PM](https://user-images.githubusercontent.com/5491371/56236940-105db800-6048-11e9-9517-e6449aa8f3d8.png)

**Comment by michaelstaib** [comment]
> despite setting the logging level to error, I'm still running into the same symptoms. Curiously, I'm running into this on my mac at work. Curiously it looks like mono-sgen64 is eating a ton of CPU. It seems to be triggered by intellisense. If I just type and never hit ctrl+space it seems to be fine.

I am having the same.

**Comment by turowicz** [comment]
I get the same with #3336

**Comment by rhyswat** [comment]
I got this horribly with recent versions of VS Code inc. 1.40.2 on Ubuntu 18.04

I installed mono globally and set VS Code's extension to always use it.

```
OmniSharp server started with Mono 6.4.0.
    Path: /home/xyz/.vscode/extensions/ms-vscode.csharp-1.21.8/.omnisharp/1.34.8/omnisharp/OmniSharp.exe
```

**Comment by michaelstaib** [comment]
@rhyswat did it fix things?

**Comment by rhyswat** [comment]
@michaelstaib yes, so far so good. I've only just done it, but VS Code is now useable again.

**Comment by michaelstaib** [comment]
@rhyswat thanks for your feedback. Will try it out. It is sometimes strange these CPU peaks come and go. I have some files that I cannot open in VSCode, or if I do then the mono exe goes wild. Really annoying. Will try out if that works.

**Comment by andrehaupt** [comment]
This seems to have worked for me too.

On MacOS:

- Download [mono](https://www.mono-project.com/download/stable/).
- Open: /Users/yourname/Library/Application Support/Code/User/settings.json
- Add the following tags:
    "omnisharp.useGlobalMono": "always",
    "omnisharp.monoPath": "/Library/Frameworks/Mono.Framework/Versions/Current/",

**Comment by CrandellWS** [comment]
on Ubuntu with `Mono JIT compiler version 6.12.0.122` setting the logging level to error seems to help a lot... but i made a few other adjustments as well. Setting the `Max Project File Count for Diagnostic Analysis` to 100 instead of 1000 and `Max Find Symbols Items` also changed to 100 from 1000

**Comment by FrancescoValletti** [comment]
@michaelstaib exactly the same problem, only on some files, the cpu for the mono process goes up incredibly, did you then manage to solve it by putting mono global?

**Comment by JoeRobich** [comment]
A lot has changed with O# and mono since this issue was opened. If you are still seeing problems, please open a new issue.

**Comment by floyd-may** [comment]
I have for the most part abandoned O# for JetBrains Rider. However, this is the second issue today that I've seen closed for the same reasons, and it gives me a little bit of hope. If I were to consider switching back, is there a good place to look for advice on how to do that?

**Comment by JoeRobich** [comment]
@floyd-may I don't have a good resource off hand but happy to share some details. Also see the [Getting Started](https://code.visualstudio.com/docs/csharp/introvideos-csharp) guide.

The 2.x version of the C# extension now defaults to using Roslyn's LSP. This should provide more VS like intellisense as it is mostly the same code driving VS. The focus is on .NET projects but there is still support for .NET Framework. There is also a C# DevKit extension which aims to provide even more VS functionality (Solution Explorer, Project/File Templates, Test Runner, etc..) but that is optional.

If you are not using the C# DevKit and prefer O# to Roslyn, you can configure `dotnet.server.useOmnisharp` to `true` in settings. I recommend also setting `omnisharp.useModernNet` to `true`, if you are working with SDK-style projects. Generally the speed and stability is much better when the language server is running on .NET as it does for Roslyn LSP and O# (modern).
