### ISSUE TITLE
Needed multiple framework support.

### ISSUE THREAD

**Issue by fatihtatoglu** [dotnet/vscode-csharp#2850]
While using VS Code,

I develop multiple framework libraries. 
<TargetFrameworks>net452;net461;netstandard2.0</TargetFrameworks>

I needed handle multiple framework with #if, #elif, #else, and #endif Directives. While developing net452 intellisense works will be worked for net452. While developing netstandard2.0 the intellisense works will be for netstandard2.0.

I visual studio I can select on editing code, I need in Visual Studio Code same feature.

**Comment by smeesseman** [comment]
+1 ^

**Comment by JoeRobich** [comment]
duping against this tracking issue https://github.com/dotnet/vscode-csharp/issues/3754
