### ISSUE TITLE
Feature request: able to select project via context menu

### ISSUE THREAD

**Issue by cilerler** [dotnet/vscode-csharp#2852]
I would like to be able to select the project via context menu.

Especially on a heavy Workspace it becomes very difficult to select a specific SLN file,  please

- allow to pick one through right click _(context menu)_ 

and/or

- allow to write the full path to the `Select Project` option

**Comment by JoeRobich** [comment]
Enabling the O# option to load projects on demand would likely help your scenario.
![Image](https://github.com/user-attachments/assets/065a3fab-0523-4f8a-9525-37063658c5ea)
