### ISSUE TITLE
Automatic vertical alignment of multiline function parameters

### ISSUE THREAD

**Issue by nikomikulicic** [dotnet/vscode-csharp#2864]
## Issue Description ##

A feature request for automatic vertical alignment of function parameters when they are spread out across multiple lines.

Suggestion: each new line is aligned with first parameter after opening bracket.
<img width="926" alt="screenshot 2019-02-20 at 12 31 32" src="https://user-images.githubusercontent.com/19579227/53089349-9cea6f00-350c-11e9-85ff-3924af59cea1.png">

Current default automatic indentation (without inserting manual indentations). Each new line is aligned with beginning of the previous line.
<img width="970" alt="screenshot 2019-02-20 at 12 38 53" src="https://user-images.githubusercontent.com/19579227/53089847-fbfcb380-350d-11e9-919d-47513fdf18a4.png">

It would be nice to have the ability to configure such behaviour.

Also a suggestion for cursor behaviour.
Suggestion: cursor could vertically align with first parameter when "enter" is pressed
<img width="775" alt="screenshot 2019-02-20 at 12 45 29" src="https://user-images.githubusercontent.com/19579227/53089914-2babbb80-350e-11e9-8c0c-6c835b905309.png">

Current: cursor is positioned at the beginning of the line.
<img width="780" alt="screenshot 2019-02-20 at 12 45 11" src="https://user-images.githubusercontent.com/19579227/53089920-2ea6ac00-350e-11e9-8289-ab93669021e4.png">

## Environment information ##

**VSCode version**: 1.31.1
**C# Extension**: 1.17.1

<details><summary>Mono Information</summary>
        OmniSharp using global mono :5.12.0</details>
<details><summary>Dotnet Information</summary>
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.17.1|
|csharpextensions|jchannon|1.3.0|
|gitlens|eamodio|9.5.1|
|material-icon-theme|PKief|3.6.3|
|mono-debug|ms-vscode|0.15.8|
|shaderlabvscodefree|amlovey|1.1.3|
|unity-code-snippets|kleber-swf|1.3.0|
|unity-debug|Unity|2.6.6|
|vscode-solarized|Braver|2.0.2|
|vscode-todo-highlight|wayou|1.0.4|
|xcode-keybindings|stevemoser|1.3.0|;

</details>

**Comment by JoeRobich** [comment]
Parameter wrapping is supported through CodeActions
![Image](https://github.com/user-attachments/assets/8604fcd6-67d8-42ed-a84a-a6647acbb4cc)
