### ISSUE TITLE
XML Summary Block Comments and Autocomplete

### ISSUE THREAD

**Issue by spiritedsnowcat** [dotnet/vscode-csharp#2867]
## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.2.102
 Commit:    96ff75a873

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.102\

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.2.102 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

VS Code version: 1.13.1
C# Extension version: 1.13.1

## Steps to reproduce
1. Start typing a [summary comment block](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/summary) in a C# file.
2. When typing, notice autocomplete pops up per word.
3. When pressing period, followed by a space, the first word in autocomplete will be inserted into the comment erroneously. 

Example code:
```
/// <summary>
/// Typing here.abstract When I type a period, autocomplete fills in a word.abstract 
/// "Abstract" just so happens to be the first word in the autocomplete list.abstract 
/// </summary>
```

## Expected  behavior
Lines that start with /// (3 forward slashes) should not open autocomplete, or autocomplete should be filtered to only show autocomplete for XML tags when starting with < (but no autocomplete is a lot better than what is currently provided).

## Actual behavior
Lines that start with /// (3 forward slashes) brings up autocomplete and fills in suggestions when not desired.

**Comment by garethjensen** [comment]
Additional information: Looks like this happens with regular comments as well, but it doesn't make a suggestion after a period, so it doesn't do an autocomplete fill-in. It's annoying that it suggests C# keywords at you when typing comments, but not too impactful.

For example:
```
// This is a comment. After a period, it doesn't autocomplete, but it does suggest words as I type.
```

**Comment by cosinekitty** [comment]
I am running into this problem too. I have to disable the OmniSharp extension while typing all of my /// xml documentation because the autocomplete keeps mangling my text and slowing me down.

**Comment by JoeRobich** [comment]
There have been lots of improvements since this issue was opened. Please open a new issue with logs if you are still running into this.
