### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by afrahshahrani** [dotnet/vscode-csharp#2907]
- Issue Type: `Performance`
- Extension Name: `csharp`
- Extension Version: `1.17.1`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.30.2`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/afrahalshahrani/ms-vscode.csharp-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by akshita31** [comment]
@afrahshahrani Can you try with the latest version of the extension(1.18.0) and check if the problem still persists ?

**Comment by JoeRobich** [comment]
Closing due to lack of response.
