### ISSUE TITLE
Text editors indentation settings are ignored

### ISSUE THREAD

**Issue by WebFreak001** [dotnet/vscode-csharp#2918]
## Environment data
`dotnet --info` output: dotnet core not installed
VS Code version: 1.32.3 (user setup)
C# Extension version: 1.17.1

## Steps to reproduce
1. Open a document
2. Convert indentation using vscode's indentation settings in the status bar

![image](https://user-images.githubusercontent.com/2035977/54514628-ecc92400-495a-11e9-95d8-70f205640aea.png)

3. Format the document

![image](https://user-images.githubusercontent.com/2035977/54514745-40d40880-495b-11e9-9cb9-9597275414d3.png)

## Expected  behavior
I expect OmniSharp to format the document using the settings I have configured just now.

## Actual behavior
OmniSharp seems to always indent using tabs.

While I prefer tabs better too, some source files have already existing formatting using spaces. I don't think it's a good idea if OmniSharp just ignores the user's settings here. This also breaks with other plugins editing code relying on the current indentation. Even built-in stuff like pressing tab to indent and the snippets are affected by this. I think the format settings in the status bar should be the ultimate source of truth and not be overridable by any other settings as they are determined by vscode with all relevant settings in mind.

There are #1632 #1574 #1290 #93 which are all closed and supposed to fix indentation for over a year, however using the latest version this is still happening.

Tried on Windows and Linux

**Comment by JoeRobich** [comment]
O# formatting is controlled first by any applicable .editorconfig, then by settings in omnisharp.json, then by settings in the IDE. It seems that formatting options are being set prior to the falling back to the IDE settings.
