### ISSUE TITLE
vscode FileSystem Extensions (is supported?)

### ISSUE THREAD

**Issue by chswin** [dotnet/vscode-csharp#2940]
Is this supposed to support *.sln and *.csproj files on remote file filesystems (filesystem extensions)?

**Comment by akshita31** [comment]
@chswin Omnisharp supports running and debugging for projects that have either sln or csproj. I am not sure I understand what do you mean by support on remote file systems. Can you elaborate a bit ?

**Comment by chswin** [comment]
I have a webapi that allows the users to author controllers at runtime. I use roslyn for compilation and currently have a self authored winform based IDE. I have written a remote filesystem provider for VS Code -> https://github.com/Microsoft/vscode-extension-samples/tree/master/fsprovider-sample .
  
It works well and was simple to author as it wired up nicely to my existing management controllers. The provider exposes the all the code as *.cs files, dynamically creates *.sln and *.csproj files on the fly accordingly. But it seems the omnisharp/vscode plugin does not acknowledge it... it is as if it only can handle local "stuff".

**Comment by filipw** [comment]
OmniSharp doesn't use VS Code abstractions to talk to the filesystem, it accesses the file system directly, so at the moment the in-memory VS Code filesystem would not work with OmniSharp.

**Comment by JoeRobich** [comment]
Closing as answered.
