### ISSUE TITLE
Automatically add .gitignore

### ISSUE THREAD

**Issue by metoly** [dotnet/vscode-csharp#2945]
the C# extension needs to offer inserting a valid .gitignore for ASP.NET projects, if it detects the repo is git initialized.

**Comment by gregg-miskelly** [comment]
To me, this feels like something that should be in `dotnet new` rather than in the C# extension.

**Comment by rchande** [comment]
@metoly I believe when we discussed this, we concluded that this made sense as a part of the `dotnet new` templating engine. Do we need this bug agains the C# extension?

**Comment by spboyer** [comment]
related https://github.com/dotnet/cli/issues/9705

**Comment by metoly** [comment]
I will take this up with the dotnet CLI team, but the idea is to surface the "dotnet new gitignore" command in VS Code once it is added to the CLI.

**Comment by metoly** [comment]
This is now in the 3.0 CLI.

**Comment by JoeRobich** [comment]
Closing as this would be external to the C# extension.
