### ISSUE TITLE
New files showing type or namespace not found but it is their

### ISSUE THREAD

**Issue by LoranceChen** [dotnet/vscode-csharp#2961]
warning still here after reinstall vscode and mono :-(
![image](https://user-images.githubusercontent.com/8775828/55524781-130ff300-56c1-11e9-800b-368d9a1acded.png)
The problem occurred when create a new .cs file and it code reference some existing class.

For detail message:  
![image](https://user-images.githubusercontent.com/8775828/55524934-93ceef00-56c1-11e9-9693-0a21c9cf0acf.png)

mono and dotnet version:
![image](https://user-images.githubusercontent.com/8775828/55524696-c3312c00-56c0-11e9-8143-d415febe3b3a.png)

Some warning about OmniSharp:
![image](https://user-images.githubusercontent.com/8775828/55525167-967e1400-56c2-11e9-838c-dd73ff0dde43.png)

**Comment by akshita31** [comment]
@LoranceChen  Does the UniRx.dll exist in the path as mentioned above ?

**Comment by SirIntruder** [comment]
Those warnings happen all the time in all Unity projects, and are harmless from what I can tell.
Issue is, as always, that omnisharp puts new files in *all* of the projects, as seen in this screenshot:

![alt text](https://user-images.githubusercontent.com/8775828/55524934-93ceef00-56c1-11e9-9693-0a21c9cf0acf.png "")

What unity3d/users really want is for the new file to be in "Assembly-Csharp.csproj", and nowhere else. That's the only project that has access to the "INetwork" (and other user provided code in "Scripts" folder).

Most recent omnisharp version should know to disappear those errors as soon as Unity3d gets focused, but I don't know if fix for that landed in some official release. Setting omnisharp path to the "latest" in the settings should help.

**Comment by LoranceChen** [comment]
@akshita31, No.those warning `.dll` files is generated by Unity.

As SirIntruder said, Assembly-Csharp.csproj seems important at this stage.

There are another issue also discuss the problem:
https://github.com/OmniSharp/omnisharp-vscode/issues/2088#issuecomment-479722092

**Comment by akshita31** [comment]
@LoranceChen Can you try setting "omnisharp.path" : "latest" and restarting vscode ?

**Comment by akshita31** [comment]
@SirIntruder I am not very much aware of the Unity system. Why doesnt that file INetwork belong to the Assembly-Csharp.csproj automatically ? And if not what is needed on omnisharp side ?

**Comment by LoranceChen** [comment]
@akshita31 , after try a setting `"omnisharp.path" : "latest"`:
![image](https://user-images.githubusercontent.com/8775828/56072949-522ff980-5dcf-11e9-99f8-da11ade8ecb1.png)
and restart Code, the omnisharp warning is disappear!

But problem also exist.
![image](https://user-images.githubusercontent.com/8775828/56072988-dedab780-5dcf-11e9-88fa-5a70cdf847bd.png)

Besides, at the time, `Assembly-Csharp.csproj` contained the new file `InitNet.1.cs`:
![image](https://user-images.githubusercontent.com/8775828/56073014-5577b500-5dd0-11e9-8847-bdf4f94fcf06.png)

**Comment by LoranceChen** [comment]
with three times test, I have found .csproj will generate `<Compile Include .../>` description for a new file when return to Unity Editor. But OmniSharp only reload the new file when restart OmniSharp.  
I'm not sure it will take any effect for the problem.

**Comment by JoeRobich** [comment]
A lot has changed with O# project loading since this issue was opened. If you are still having problems, please open a new issue. Also, recommend using the Unity VS Code extension.
