### ISSUE TITLE
Clicking quick fix in vscode doesnt work

### ISSUE THREAD

**Issue by akshita31** [dotnet/vscode-csharp#2981]
![QuickActionBug](https://user-images.githubusercontent.com/12554141/56004740-be044c00-5c81-11e9-9bad-22ac1c3e0652.gif)

We need omnisharp to return the codeaction kind and consume that and return the codeaction with the appropriate code action on the extension side

**Comment by stephaneclotilde** [comment]
Since the issue is still opened, shouldn't this be changed to a new milestone ? @akshita31

**Comment by JoeRobich** [comment]
Cannot reproduce with the current release.
