### ISSUE TITLE
Incorrect auto - complete in lamda expressions

### ISSUE THREAD

**Issue by erammos** [dotnet/vscode-csharp#3018]
1.19.0 vers.
![Screen Shot 2019-04-23 at 13 30 20](https://user-images.githubusercontent.com/10757118/56574597-511b7b00-65cc-11e9-82ac-e076318f8cdb.png)

**Comment by mario195** [comment]
Facing the same issue.....
![Screenshot_20190426_211427](https://user-images.githubusercontent.com/24294286/56831044-63194a00-6868-11e9-94b4-bdff26adcb55.png)

**Comment by JoeRobich** [comment]
A lot has changed with O# completion since this issue was opened. If you are still seeing this problem, please open a new issue.
