### ISSUE TITLE
Combine C# Extensions package

### ISSUE THREAD

**Issue by jchannon** [dotnet/vscode-csharp#3035]
Hi all,

I'm going to put to rest my C# Extensions package https://marketplace.visualstudio.com/items?itemName=jchannon.csharpextensions to rest or transfer it someone else but before I do that I was wondering if you wanted to copy some of the features to this project and if so I'll take down my package, if not I'll try and transfer ownership to someone else

**Comment by felipecaputo** [comment]
Just to add my two cents on this, this extensions, and the `new C# class` and `new C# Interface` are really helpfull for example

**Comment by jchannon** [comment]
No takers?

**Comment by dylinmaust** [comment]
I'd also like to see this extension integrated into Omnisharp, solely for `New C# Class` and `New C# Interface` although it would be nice to add support for the `RootNamespace` csproj property which is currently missing.

**Comment by jchannon** [comment]
@filipw 👀

**Comment by filipw** [comment]
This is a question to @rchande or @akshita31 I only work on the server side 😀

**Comment by JoeRobich** [comment]
Closing as there are no plans to do this at this time.
