### ISSUE TITLE
syntax highlighting fails in new anonymous object with LINQ

### ISSUE THREAD

**Issue by vispariana** [dotnet/vscode-csharp#3044]
Defining a new anonumous object having a field valued by LINQ breaks syntax highlighting.

Steps to reproduce: write the following code

```
public class Program {
    [Attribute1]
    [Attribute2(P = 1)]
    public static void Main(string[] args) {
        for(int i = 0; i < 10; i++) {}
        var a = new {Field1 = from a in b select a}};
        for(int i = 0; i < 10; i++) {}
    }
    [Attribute1]
    [Attribute2(P = 1)]
    public static void Method() {
    }
}
```
Note: found out that if i put parentheses around the LINQ it is fixed, but i think it should be working without the parentheses either, because the code also works that way!

**Comment by victormikael** [comment]
It´s not just with Linq, it happens with any anonymous type.

![image](https://user-images.githubusercontent.com/38520757/155993624-236be0f9-c97f-4d6c-ba22-edb22f24acfb.png)

**Comment by juriy-zn** [comment]
happening here as well
![image](https://user-images.githubusercontent.com/11260077/173213975-20b2aeaf-a8e5-46e6-af9e-53d8bc2ef271.png)

**Comment by victormikael** [comment]
Any update on this?

**Comment by JoeRobich** [comment]
Since this issue was opened we have added semantic highlighting support as well as a much improved textmate grammar.
