### ISSUE TITLE
Changing default "publish" task to "Release" results in duplicate attribute errors

### ISSUE THREAD

**Issue by ejizba** [dotnet/vscode-csharp#3050]
## Steps to Reproduce ##
1. Run `dotnet new console`
1. When prompted, select "Yes" to add missing files to debug/run
1. Modify the "publish" task in "tasks.json" to run against "Release" configuration
1. Run the build task
1. Run the publish task

Here are my files:

<details>
<summary>cs2.csproj</summary>

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

</Project>
```

</details>

<details>
<summary>Program.cs</summary>

```
using System;

namespace cs2
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
```

</details>

<details>
<summary>tasks.json</summary>

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "command": "dotnet",
            "type": "process",
            "args": [
                "build",
                "${workspaceFolder}/cs2.csproj"
            ],
            "problemMatcher": "$tsc"
        },
        {
            "label": "publish",
            "command": "dotnet",
            "type": "process",
            "args": [
                "publish",
                "${workspaceFolder}/cs2.csproj",
                "--configuration",
                "Release"
            ],
            "problemMatcher": "$tsc"
        },
        {
            "label": "watch",
            "command": "dotnet",
            "type": "process",
            "args": [
                "watch",
                "run",
                "${workspaceFolder}/cs2.csproj"
            ],
            "problemMatcher": "$tsc"
        }
    ]
}
```

</details>

## Expected Behavior ##

No errors in "Problems" panel

## Actual Behavior ##

Multiple errors like this (sometimes it takes about 30-60 seconds to show up):
```
Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute (CS0579) [cs2]
```

I believe this is because there is a `cs2.AssemblyInfo.cs` file in both `obj\Debug\` and `obj\Release\`. I looked into using `files.exclude` to exclude the `obj` folder, but that doesn't hide errors due to https://github.com/OmniSharp/omnisharp-vscode/issues/1694. Looking even further into that issue, @DustinCampbell had this to say about the `obj` folder:

> I should mention that this particular feature request is about using files.exclude to help inform the projects that OmniSharp processes. It isn't about getting it to somehow ignore files in processed projects that might contain files that belong to the project. OmniSharp will always process files in "obj" because MSBuild will use it when processing the project. Ignoring files in "obj" could introduce errors in other files for certain project types.

Can we do anything to hide these errors? Maybe make it only run intellisense against one configuration instead of both Debug and Release? I'm honestly not entirely sure if this is a project config issue, msbuild issue, or VS Code issue.

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.34.0-insider
**C# Extension**: 1.19.1

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.106
 Commit:    aa79b139a8

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.106/

Host (useful for support):
  Version: 2.2.4
  Commit:  f95848e524

.NET Core SDKs installed:
  2.0.0 [/usr/local/share/dotnet/sdk]
  2.1.403 [/usr/local/share/dotnet/sdk]
  2.2.106 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.8.2|
|csharp|ms-vscode|1.19.1|
|java|redhat|0.44.0|
|python|ms-python|2019.4.12954|
|remote-containers|ms-vscode-remote|0.49.0|
|remote-ssh|ms-vscode-remote|0.35.0|
|remote-ssh-edit|ms-vscode-remote|0.34.0|
|remote-ssh-explorer|ms-vscode-remote|0.34.0|
|vscode-azureappservice|ms-azuretools|0.14.0|
|vscode-azurefunctions|ms-azuretools|0.17.0|
|vscode-azurestorage|ms-azuretools|0.7.0|
|vscode-cosmosdb|ms-azuretools|0.10.2|
|vscode-docker|PeterJausovec|0.6.2|
|vscode-java-debug|vscjava|0.18.0|
|vscode-typescript-tslint-plugin|ms-vscode|1.0.0|;

</details>

**Comment by mikadumont** [comment]
We've made lots of updates to the C# extension since this issue was filed. Please file a new issue if you're still experiencing this with updated logs.
