### ISSUE TITLE
[Feature Request] Stop OmniSharp

### ISSUE THREAD

**Issue by lonix1** [dotnet/vscode-csharp#3058]
### Background
When coding I often need to consult other projects / repos / branches / examples / samples / whatever - so I have multiple vscode windows open. And because they don't have all the dependencies installed, OmniSharp complains, makes everything red, and grinds down my CPU.

I think consulting other repos while coding is something many devs do, so this is a common problem.

### Proposal
Please add a new command to the vscode palette: `OmniSharp: Stop Server`.

If I open a temporary project, I'd immediately run that command to prevent the problems mentioned above.

**Comment by akshita31** [comment]
![image](https://user-images.githubusercontent.com/12554141/58597364-7aaf6e00-822c-11e9-83a9-b0c0ed5e524a.png)

@lonix1 We already have a setting called Omnisharp:AutoStart. If you disable that in the workspace settings for those particular projects, does it solve the issue ?

**Comment by lonix1** [comment]
That would be very helpful in some use cases. In my use case it wouldn't because I would be going in and out of various projects throughout the day. So if I permanently stop omnisharp I'd need to remember to also start it.

Anyways, I know this is probably a way out there request, so feel free to close, and consider it again if others want it.

Thanks for the advice!

**Comment by akshita31** [comment]
@lonix1 For the folders for which you dont want omnisharp to light up you can specify the workspace settings there. Workspace settings only apply to that particular workspace and not to all other vscode instances - https://code.visualstudio.com/docs/getstarted/settings

**Comment by lonix1** [comment]
Yep I know, but I'll use that workspace now, and later maybe not. Multiple projects may be current at the same time - e.g. backend, frontend, mobile, etc. So permanently disabling is not an option - and the workspace-config solution is not applicable.

But, like I said, if you feel this is a weird request, let's close it and reconsider if other people also want it?

**Comment by bestknighter** [comment]
Another use case: I increased the project load timeout to try and debug some omnisharp behavior for bug report. The problem was that I mistyped 3600 instead of 360 and the only way I managed to stop it was by restarting my computer. Which I personally believe to be far from ideal.

**Comment by JoeRobich** [comment]
Closing as there are no plans to make improvements here at this time.
