### ISSUE TITLE
Adding link to user feedback for extension users

### ISSUE THREAD

**Issue by metoly** [dotnet/vscode-csharp#3066]
Pop up a toast message  pointing users to a feedback survey after a couple of days of usage.

Add this message to the readme.md:
If you run into any issues or have suggestions for us, please file [issues and suggestions on GitHub](https://github.com/OmniSharp/omnisharp-vscode/issues). If you haven’t already provided us feedback, please take this [quick survey](https://go.microsoft.com/fwlink/?linkid=2092238) and let us know what you think!).

https://go.microsoft.com/fwlink/?linkid=2092238

**Comment by JoeRobich** [comment]
No changes for this are planned.
