### ISSUE TITLE
Errors in obj/project_xxxxxxxx_wpftmp_AssemblyInfo.cs

### ISSUE THREAD

**Issue by SupinePandora43** [dotnet/vscode-csharp#3082]
## Issue Description ##
9 errors: "repeating attribute 'Assembly...'" in file ${projectName}/obj/Debug/netcoreapp3.0/${projectName}_xxxxxxxx_wpftmp_AssemblyInfo.cs,
sometimes show errors in other AssemblyInfo files
## Steps to Reproduce ##
open dotnet c# wpf project, run command "dotnet build"
## Steps to FIX ##
in vscode run command "Omnisharp: Restart Omnisharp"
## Environment information ##

**VSCode version**: 1.34.0
**C# Extension**: 1.19.1

<details><summary>Dotnet Information</summary>
����� SDK ��� .NET Core (��ࠦ��騩 �� global.json):
 Version:   3.0.100-preview-009812
 Commit:    e3abf6e935

�।� �믮������:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x86
 Base Path:   F:\Program Files\dotnet\sdk\3.0.100-preview-009812\

Host (useful for support):
  Version: 3.0.0-preview-27122-01
  Commit:  00c5c8bc40

.NET Core SDKs installed:
  3.0.100-preview-009812 [F:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.0 [F:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.0 [F:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-18579-0056 [F:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.0 [F:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27122-01 [F:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-alpha-27128-4 [F:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|auto-using|Fudge|0.7.8|
|better-comments|aaron-bond|2.0.5|
|bracket-pair-colorizer-2|CoenraadS|0.0.28|
|cfg-games-support|joelcancela|0.1.2|
|color-highlight|naumovs|2.3.0|
|color-info|bierner|0.5.1|
|csharp|ms-vscode|1.19.1|
|dotnet-test-explorer|formulahendry|0.7.0|
|EditorConfig|EditorConfig|0.13.0|
|githistory|donjayamanne|0.4.6|
|gitlens|eamodio|9.7.4|
|insert-unicode|brunnerh|0.6.0|
|markdown-all-in-one|yzhang|2.3.1|
|material-icon-theme|PKief|3.7.0|
|material-icons|Archety|0.2.0|
|msbuild-project-tools|tintoy|0.2.54|
|regex|chrmarti|0.2.0|
|sln-support|logerfo|0.0.1|
|svg-font-previewer|nkokhelox|1.1.4|
|todo-tree|Gruntfuggly|0.0.132|
|vsc-material-theme|Equinusocio|2.8.2|
|vscode-gutter-preview|kisstkondoros|0.19.0|
|vscode-language-pack-ru|MS-CEINTL|1.34.2|
|vscode-pull-request-github|GitHub|0.6.0|
|vscode-svgviewer|cssho|2.0.0|
|vscode-taskexplorer|spmeesseman|1.18.10|
|vscode-wakatime|WakaTime|2.1.1|
|vscode-xml|redhat|0.5.1|
|vscode-yaml|redhat|0.4.0|
|vscodeintellicode|VisualStudioExptTeam|1.1.6|;

</details>

**Comment by JoeRobich** [comment]
A lot has changes with O# code analysis since this issue was opened. If you are still seeing problems, please open a new issue.
