### ISSUE TITLE
error parsing glob '!**/SyncToy**': invalid use of **; must be one path component

### ISSUE THREAD

**Issue by mrmowji** [dotnet/vscode-csharp#3107]
## Issue Description ##
Omnisharp extension doesn't auto-complete. I only get the highlighting.
After the dot, I only get keywords already used in my current file, nothing more.

## Steps to Reproduce ##

1. Install VS Code.
2. Install C# extension by Microsoft.
3. Create a new ASP.Net Core web app.

## Expected Behavior ##
It should do the auto-complete and provide related properties and methods of the object before the dot.

## Actual Behavior ##
Nothing is shown.

`Omnisharp: Select Project` command gets me this error:
```
command failed with error code 2: error parsing glob '!**/SyncToy**': invalid use of **; must be one path component
```
I've installed SyncToy to regularly backup my files, but I don't know how it got there.

### OmniSharp log ###
It's empty.

### C# log ###
It's empty.

## Environment information ##
**VSCode version**: 1.35.0
**C# Extension**: 1.19.1

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.102
 Commit:    96ff75a873

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\PROGRAM FILES\DOTNET\sdk\2.2.102\

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\PROGRAM FILES\DOTNET\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\PROGRAM FILES\DOTNET\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\PROGRAM FILES\DOTNET\sdk]
  2.2.102 [C:\Program Files\dotnet\sdk]
  2.2.102 [C:\PROGRAM FILES\DOTNET\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [C:\PROGRAM FILES\DOTNET\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\PROGRAM FILES\DOTNET\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [C:\PROGRAM FILES\DOTNET\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\PROGRAM FILES\DOTNET\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\PROGRAM FILES\DOTNET\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\PROGRAM FILES\DOTNET\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\PROGRAM FILES\DOTNET\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\PROGRAM FILES\DOTNET\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.19.1|
|nativescript|Telerik|0.10.1|
|vetur|octref|0.21.0|
|vscode-todo-plus|fabiospampinato|4.13.0|;

</details>

**Comment by rchande** [comment]
@mrmowji Can you share a screenshot that shows the paths we display? Hard to diagnose what's happening without seeing the paths.

**Comment by mrmowji** [comment]
@rchande Sorry. I didn't get what you mean by the "paths". Would you please elaborate?

**Comment by JoeRobich** [comment]
It appears the VS Code `file.excludes` setting may include an invalid glob.
