### ISSUE TITLE
Intellisense stops working occasionally

### ISSUE THREAD

**Issue by omerciftcibasi** [dotnet/vscode-csharp#3108]
## Actual Behavior ##
Intellisense stops working occasionally. When it stoped, even if I restarted my computer it didn't work, when I disabled and enabled the extension, it started to work somehow.
### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.33.1
**C# Extension**: 1.19.1

<details><summary>Mono Information</summary>
        OmniSharp using global mono :5.20.1</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.106
 Commit:    aa79b139a8

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.106/

Host (useful for support):
  Version: 2.2.4
  Commit:  f95848e524

.NET Core SDKs installed:
  2.2.106 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|auto-close-tag|formulahendry|0.5.6|
|auto-rename-tag|formulahendry|0.1.0|
|beautify|HookyQR|1.5.0|
|cpptools|ms-vscode|0.23.1|
|csharp|ms-vscode|1.19.1|
|gitlens|eamodio|9.8.2|
|JavaScriptSnippets|xabikos|1.7.2|
|mssql|ms-mssql|1.6.0|
|vetur|octref|0.21.0|
|vscode-docker|PeterJausovec|0.6.2|
|vscode-eslint|dbaeumer|1.9.0|
|vscode-peacock|johnpapa|2.3.0|
|vscode-trello-viewer|Ho-Wan|0.6.0|;

</details>

**Comment by omerciftcibasi** [comment]
I have mac and following worked for me

VS Code Settings.

`omnisharp.useGlobalMono = never `

**Comment by JoeRobich** [comment]
There have been lots of improvements since this issue was opened. Please open a new issue with logs if you are still running into this.
