### ISSUE TITLE
IntelliSense completion for unimported types

### ISSUE THREAD

**Issue by natanfudge** [dotnet/vscode-csharp#3112]
Since [Visual Studio 2019 version 16.1 preview 3](https://devblogs.microsoft.com/visualstudio/visual-studio-2019-version-16-1-preview-3/) Visual Studio supports completions for unimported types. See the blog post for most information.
Please implement this feature in Visual Studio Code.

**Comment by filipw** [comment]
This is tracked in OmniSharp by https://github.com/OmniSharp/omnisharp-roslyn/issues/1482

**Comment by JoeRobich** [comment]
This is in the current release.
