### ISSUE TITLE
Run and debug test that needs a msbuild variable set

### ISSUE THREAD

**Issue by tobiaszellner** [dotnet/vscode-csharp#3148]
## Issue Description ##
I have a dotNet Core project with tests. To run the compile on Linux using the dotnet command line tool, I do the following:
```sh
dotnet build -p:LinuxOnlyBuild=true  path/to/my.sln
```
To run the tests I use this comand:
```sh
dotnet test -p:LinuxOnlyBuild=true  path/to/my.sln
```
The "-p:LinuxOnlyBuild=true" parameter is needed because otherwise the *.sln file will try to load code that can only work on Windows.

Within VS Code I try to run/debug one of the existing tests, using the buttons provided by the Code Lens ("Run Test" or "Debug Test"). But this does not work since I can not pass the needed  "-p:LinuxOnlyBuild=true" parameter through to the call. Whenever I click these buttons, I get the same compile error as I would get when trying to compile without the parameter. 

To be able to see the Code Lens in my files, I needed to configure a .vscode/launch.json file with the content below:
```javascript
{
   "version": "0.2.0",
   "configurations": [
        {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            // If you have changed target frameworks, make sure to update the program path.
            "program": "${workspaceFolder}/src/GenericPackageManager.Logic.Test/bin/Debug/netcoreapp2.1/Siemens.Automation.Buildtools.GenericPackageManager.Logic.Test.dll",
            "args": ["-p:LinuxOnlyBuild=true"],
            "cwd": "${workspaceFolder}/src/GenericPackageManager.Logic.Test",
            // For more information about the 'console' field, see https://aka.ms/VSCode-CS-LaunchJson-Console
            "console": "internalConsole",
            "stopAtEntry": false
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:pickProcess}"
        }
    ]
}
```
So, there I was able to add my needed parameter to the args array. But I can not find out how I can configure this for the call, the Code Lens sends out when I click on it.

## Expected Behavior ##
A way to configure parameters that will be sent to the dotnet tool, whenever it is called.

## Actual Behavior ##
I can not find a place to configure it.

## Environment information ##

**VSCode version**: 1.35.1
**C# Extension**: 1.20.0

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.300
 Commit:    73efd5bd87

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         debian.9-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.300/

Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  2.2.300 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.20.0|
|markdown-all-in-one|yzhang|2.4.0|
|markdown-preview-enhanced|shd101wyy|0.4.2|;

</details>

**Comment by JoeRobich** [comment]
There is now a setting to specify a .runsettings file to use for unit tests.
![Image](https://github.com/user-attachments/assets/7ef6df28-e8cf-447c-b2ab-cc838bcf43d8)
