### ISSUE TITLE
VSCode gets really slow and has about 80% constant cpu usage if more that 30 interfaces are implemented

### ISSUE THREAD

**Issue by michaelstaib** [dotnet/vscode-csharp#3156]
## Issue Description ##
```csharp
public class SyntaxNodeVisitor
        : ISyntaxNodeVisitor<DocumentNode>
        , ISyntaxNodeVisitor<OperationDefinitionNode>
        , ISyntaxNodeVisitor<VariableDefinitionNode>
        , ISyntaxNodeVisitor<SelectionSetNode>
        , ISyntaxNodeVisitor<FieldNode>
        , ISyntaxNodeVisitor<ArgumentNode>
        , ISyntaxNodeVisitor<FragmentSpreadNode>
        , ISyntaxNodeVisitor<InlineFragmentNode>
        , ISyntaxNodeVisitor<FragmentDefinitionNode>
        , ISyntaxNodeVisitor<DirectiveNode>
        , ISyntaxNodeVisitor<NamedTypeNode>
        , ISyntaxNodeVisitor<ListTypeNode>
        , ISyntaxNodeVisitor<NonNullTypeNode>
        , ISyntaxNodeVisitor<IValueNode>
        , ISyntaxNodeVisitor<ObjectValueNode>
        , ISyntaxNodeVisitor<ObjectFieldNode>
        , ISyntaxNodeVisitor<ListValueNode>
        , ISyntaxNodeVisitor<StringValueNode>
        , ISyntaxNodeVisitor<IntValueNode>
        , ISyntaxNodeVisitor<FloatValueNode>
        , ISyntaxNodeVisitor<BooleanValueNode>
        , ISyntaxNodeVisitor<EnumValueNode>
        , ISyntaxNodeVisitor<VariableNode>
        , ISyntaxNodeVisitor<SchemaDefinitionNode>
        , ISyntaxNodeVisitor<OperationTypeDefinitionNode>
        , ISyntaxNodeVisitor<ScalarTypeDefinitionNode>
        , ISyntaxNodeVisitor<ObjectTypeDefinitionNode>
        , ISyntaxNodeVisitor<FieldDefinitionNode>
        , ISyntaxNodeVisitor<InputValueDefinitionNode>
        , ISyntaxNodeVisitor<InterfaceTypeDefinitionNode>
        , ISyntaxNodeVisitor<UnionTypeDefinitionNode>
        , ISyntaxNodeVisitor<EnumTypeDefinitionNode>
        , ISyntaxNodeVisitor<EnumValueDefinitionNode>
        , ISyntaxNodeVisitor<InputObjectTypeDefinitionNode>
        , ISyntaxNodeVisitor<DirectiveDefinitionNode>
        , ISyntaxNodeVisitor<SchemaExtensionNode>
        , ISyntaxNodeVisitor<ScalarTypeExtensionNode>
        , ISyntaxNodeVisitor<ObjectTypeExtensionNode>
        , ISyntaxNodeVisitor<InterfaceTypeExtensionNode>
        , ISyntaxNodeVisitor<UnionTypeExtensionNode>
        , ISyntaxNodeVisitor<EnumTypeExtensionNode>
        , ISyntaxNodeVisitor<InputObjectTypeExtensionNode>
        , ISyntaxNodeVisitor<NameNode>
    {
       ....
    }

```

## Steps to Reproduce ##

The interface basically has two methods `Enter` and `Leave`. When I open this in vscode mono-sgen64 goes wild and uses about 80% of the cpu. This only happens when I open this class of the project.

https://github.com/ChilliCream/hotchocolate/blob/visitors/src/Core/Language/Visitors/SyntaxNodeVisitor.cs

If I close this file and reopen it again everything is fine.

## Expected Behavior ##

Process does not flip out.

## Actual Behavior ##

Process mono-sgen64 makes vscode unusable

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.36.0
**C# Extension**: 1.20.0

<details><summary>Mono Information</summary>
        OmniSharp using global mono :5.18.1</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview4-011223
 Commit:    118dd862c8

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100-preview4-011223/

Host (useful for support):
  Version: 3.0.0-preview4-27615-11
  Commit:  ee54d4cbd2

.NET Core SDKs installed:
  2.1.301 [/usr/local/share/dotnet/sdk]
  2.1.302 [/usr/local/share/dotnet/sdk]
  2.1.401 [/usr/local/share/dotnet/sdk]
  2.1.500 [/usr/local/share/dotnet/sdk]
  2.1.503 [/usr/local/share/dotnet/sdk]
  2.1.504 [/usr/local/share/dotnet/sdk]
  2.1.505 [/usr/local/share/dotnet/sdk]
  2.2.103 [/usr/local/share/dotnet/sdk]
  2.2.106 [/usr/local/share/dotnet/sdk]
  3.0.100-preview-010184 [/usr/local/share/dotnet/sdk]
  3.0.100-preview4-011223 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-19075-0444 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview4-19216-03 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27324-5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview4-27615-11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|awesome-material-theme|marcosfede|0.12.0|
|beautify|HookyQR|1.5.0|
|cake-vscode|cake-build|0.12.0|
|csharp|ms-vscode|1.20.0|
|docomment|k--kato|0.1.8|
|dop|josenzo|1.1.2|
|dotnet-test-explorer|formulahendry|0.7.1|
|EditorConfig|EditorConfig|0.13.0|
|flow-for-vscode|flowtype|1.1.4|
|git-project-manager|felipecaputo|1.7.1|
|githd|huizhou|2.1.0|
|githistory|donjayamanne|0.4.6|
|gitlens|eamodio|9.8.2|
|java|redhat|0.46.0|
|msbuild-project-tools|tintoy|0.2.55|
|mustache|dawhite|1.1.1|
|omnipascal|Wosi|0.17.1|
|powershell|ms-vscode|2019.5.0|
|prettier-vscode|esbenp|1.9.0|
|sublime-babel-vscode|joshpeng|0.2.10|
|theme-material-theme|jprestidge|1.0.1|
|theme-onedark-sublime|joshpeng|0.3.7|
|theme-tomorrowkit-sublime|joshpeng|0.1.1|
|vscode-coverage-gutters|ryanluker|2.4.0|
|vscode-docker|ms-azuretools|0.6.4|
|vscode-graphql|Prisma|0.2.1|
|vscode-great-icons|emmanuelbeziat|2.1.47|
|vscode-java-debug|vscjava|0.20.0|
|vscode-java-dependency|vscjava|0.5.1|
|vscode-java-pack|vscjava|0.7.1|
|vscode-java-test|vscjava|0.18.1|
|vscode-markdownlint|DavidAnson|0.28.0|
|vscode-maven|vscjava|0.17.1|
|vscodeilviewer|josephwoodward|0.0.1|
|vscodeintellicode|VisualStudioExptTeam|1.1.7|
|vsliveshare|ms-vsliveshare|1.0.488|;

</details>

**Comment by rchande** [comment]
@michaelstaib Does it help if you set the option `"csharp.referencesCodeLens.enabled": false`?

**Comment by JoeRobich** [comment]
A lot has changed with O# and mono since this issue was opened. If you are still having problems, please open a new issue.
