### ISSUE TITLE
C# Extendation wiht Unity

### ISSUE THREAD

**Issue by MrAlfo** [dotnet/vscode-csharp#3157]
I want to Unity and C# Debugger and this extentation, but in VS Code, i cant use components and hints like "RigitBody2d". Normally, it should be automaticly. And I have a error message like ".net cli tools cannot be located" etc.
Please help me.

**Comment by rchande** [comment]
@MrAlfo Please share your "OmniSharp Log" (Output Windows > Select OmniSharp Log from dropdown)

**Comment by JoeRobich** [comment]
It is recommended to use the Unity extension for VS Code.
