### ISSUE TITLE
Disabling implicit evaluation of properties and functions during debugging

### ISSUE THREAD

**Issue by anuchandy** [dotnet/vscode-csharp#3173]
Do we've equivalent to visual studio option `Debugging > General > Enable property evaluation and other implicit function calls`? I'm looking for a way to disable implicit evaluation of properties and functions.

Visual studio doc for this is here: https://docs.microsoft.com/en-us/visualstudio/debugger/error-evaluating-the-function-process-exited?view=vs-2019#solution-2-disable-all-implicit-evaluation

**Comment by gregg-miskelly** [comment]
Unfortunately, no, we don't have an option to set this in VS Code. Though we definitely should.

**Comment by gregg-miskelly** [comment]
Implementation note: the fix for this is to set `DkmEvaluationFlags::NoFuncEval`

**Comment by gregg-miskelly** [comment]
In the next version of the C# extension, this can be controlled using the following in launch.json, or the identically named VS Code user preference.

```json
    "expressionEvaluationOptions":{
        "allowImplicitFuncEval": false
    }
```
