### ISSUE TITLE
VSCode shows squiggly lines on the wrong line in C# file that uses #line directive

### ISSUE THREAD

**Issue by asklar** [dotnet/vscode-csharp#3190]
Issue Type: <b>Bug</b>

When using #line in a C# project, the editor doesn't using the mapped line to figure out where the error occurred

Extension version: 1.21.0
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) m3-7Y30 CPU @ 1.00GHz (4 x 1608)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.93GB (0.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by asklar** [comment]
The compile error happens in line 37 (the Children object doesn't have an AddRange method). However because of the #line directive, the line where the editor shows the squiggly is wrong - it shows it as being in line 25

![image](https://user-images.githubusercontent.com/22989529/61821571-6347c800-ae0c-11e9-8de8-8fe7cfbb292f.png)

**Comment by JoeRobich** [comment]
This is a O# issue. If you are still seeing this problem, please open a new issue at https://github.com/OmniSharp/omnisharp-roslyn/issues
