### ISSUE TITLE
Minimum .NET Core SDK should be a supported version

### ISSUE THREAD

**Issue by richlander** [dotnet/vscode-csharp#3200]
At present, Omnisharp [checks for a minimum .NET Core SDK version of 1.0.0](https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/coreclr-debug/util.ts#L12). .NET Core 1.0 is no longer supported and that particular servicing version hasn't been supported for multiple years.

The min-supported .NET Core version should align with the highest security patch for the oldest supported .NET Core SDK version. Right now, that would be `2.1.801`. I'm not suggesting a hard-line to updating this version on a schedule, but updating it to whatever is the correct version every time we publish a new omnisharp version.

We would probably need to [update the message](https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/coreclr-debug/util.ts#L109-L110) to make it more descriptive for the UX.

**Comment by rchande** [comment]
@richlander I think what you've written is actually a feature request to notify the user that the detected .NET Core SDK is no longer supported. I don't believe we'll be able to provide a good implementation of this by adding/updating constants to our code. Rather, this should be data-driven by data we get from the CLI somehow. Thoughts?

As a footnote, I don't know why the min version is set to 1.0.0, but I'm also not sure why we would choose to fail project load/throw errors if someone was on an out of date SDK.

**Comment by richlander** [comment]
You are right. Changing constants for this purpose is a bad idea. In fact, the constant can likely be removed entirely. It's not providing any obvious value.

Visual Studio does a good job of helping you keep up to date on SDKs. Part of that is keeping you secure but an equal part is that our test matrix is quite shallow between VS and .NET Core versions. That's presumably the case here as well.  I assume we no longer test omnisharp with .NET Core 1.0.0.

Let's assume we had a CLI API to give us any information we wanted. I think we'd want to do the following:

- Log that you were not using the latest SDK for your target framework, tell you which version you are are using, and what the latest is, and how to download it.
- Provide a visual way of showing you that there is a newer .NET Core SDK version available (maybe a little circle on top of the omnisharp icon, much like how VS Code does it for updates) that would open the browser when clicked.
- Prompt you to download the .NET Core SDK when you don't have one installed, either at all, or that is compatible with your current project.

**Comment by gregg-miskelly** [comment]
I believe that check was just there to warn users back when there was a breaking changing to CLR startup which broke debugging. For debugger scenarios, that was a long time ago and the code could just be deleted. Though, as Rich said, we may want to change it and keep it for language service scenarios.

**Comment by JoeRobich** [comment]
This would be better sourced through the .NET SDK extension.
