### ISSUE TITLE
the extern alias 'XXX' was not specified in a /reference option

### ISSUE THREAD

**Issue by seanmars** [dotnet/vscode-csharp#3218]
## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012821
 Commit:    6348f1068a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview7-012821\

Host (useful for support):
  Version: 3.0.0-preview7-27912-14
  Commit:  4da6ee6450

.NET Core SDKs installed:
  3.0.100-preview7-012821 [C:\Program Files\dotnet\sdk]
```
VS Code version:
```
Version: 1.36.1 (user setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```
C# Extension version: 1.21.0

## Steps to reproduce

- Create a visual studio project A.
- Add project B reference to project A
- Add an alias
- Put using statement at the top using with alias

## Expected  behavior

No error

## Actual behavior

Get errors: `The extern alias 'xxx' was not specified in a /reference option (CS0430)`

**Comment by rchande** [comment]
@seanmars I'm having trouble reproducing this; can you share a repro project?

**Comment by seanmars** [comment]
@rchande Here is my test project
https://github.com/seanmars/omnisharp-roslyn-alias-test

**Comment by rchande** [comment]
@seanmars Thanks, looks like OmniSharp is doing something weird here.

**Comment by filipw** [comment]
we have a test for this, and the test passes. I had a quick look and in the test setup, the msbuild property resolves differently than when running against the standalone/VS msbuild provider

**Comment by JoeRobich** [comment]
A lot has changed with O# project loading and watching since this issue was opened. If you are still seeing this problem, please open a new issue at https://github.com/OmniSharp/omnisharp-roslyn/issues
