### ISSUE TITLE
The wrong behavior of autocomplete

### ISSUE THREAD

**Issue by AlexRj0130** [dotnet/vscode-csharp#3219]
## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.2.301
 Commit:    70d6be0814

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.301\

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.2.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

VS Code version:
1.36.1
x64

C# Extension version:
1.21.0

## Steps to reproduce
Just add a method of class that named "Add" and then type the bracket character "(" instead of any characters else, then you will get a method which named "AppDomainUnloadedException()" instead of "Add()".

## Expected  behavior
Keepping the typping result named  "Add()"  instead of replacing it.

## Actual behavior
Get the wrong result named "AppDomainUnloadedException()" which was given by the provider.

**Comment by rchande** [comment]
@AlexRj0130 Can you share the text of the file when you're in this state?

**Comment by JoeRobich** [comment]
Cannot reproduce this with the current release.
