### ISSUE TITLE
Smarter behavior in sln with multitargetted projects

### ISSUE THREAD

**Issue by AndrewTriesToCode** [dotnet/vscode-csharp#3288]
Hello,

I develop a library which targets multiple .Net core frameworks/standards. In the same solution I have a samples folder for example projects that target only netcoreapp2.2.

If the library project uses `<TargetFrameworks>netcoreapp3.0;netcoreapp2.2</TargetFrameworks>` and a sample project uses `<TargetFramework>netcoreapp3.0</TargetFramework>` everything is good.

However if a sample project only targets netcoreapp2.2 and has a `<ProjectReference>` to the library VS Code flags all sorts of errors in the sample project. Omnisharp-vscode seems to only see the referenced project as targettiing the first framework listed in its `<TargetFrameworks>` entry.

This has left me in a position where my project has hundreds of errors in "normal" state while opened in VSCode but where a `dotnet build` runs perfectly on the command line.

If it helps my project is https://github.com/Finbuckle/Finbuckle.MultiTenant

Clone that and open the sln in VSCode and you will see what I mean.

**Comment by achandlerwhite** [comment]
Also I'll add that the `obj` folders some target frameworks are flagged for errors but the first listed target framework's obj folder is correctly ignored,

**Comment by cartermp** [comment]
Yeah, this is a pretty big project system-level feature. Currently OmniSharp just loads the first target specified. It doesn't have a robust system for handling multiple targets like the Visual Studio project system does.

**Comment by xqrzd** [comment]
Thanks for the info, I was able to fix my issue by rearranging my target frameworks so the newest framework is first.

**Comment by candoumbe** [comment]
Hi !
As I'm running into the same kind of using on one of my project ... Is there any news on addressing this issue ?
I'm about to move away from Windows as my dev OS and this is very critical to me.

Thanks in advance for your answer and keep up the good work

**Comment by JoeRobich** [comment]
This is an O# issue. If you are still running into this problem, please open a new issue at https://github.com/OmniSharp/omnisharp-roslyn/issues
