### ISSUE TITLE
Hanging on Installing package OmniSharp for Linux. No features work.

### ISSUE THREAD

**Issue by MeepTech** [dotnet/vscode-csharp#3345]
3. Type `CSharp: Report an issue`
^This gives me:
`command 'csharp.reportIssue' not found`

## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  95a0a61858

.NET Core SDKs installed:
  3.0.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

VS Code version:
1.40.0-insider
C# Extension version:
newest (today)
## Steps to reproduce
Install vscode. Install c# extension from the extensions interface in vscode.

## Expected  behavior
omnisharp should install on my wsl; machine and c# extension should work.

## Actual behavior
```
Installing C# dependencies...
Platform: linux, x86_64, name=ubuntu, version=18.04

Downloading package 'OmniSharp for Linux (x64)' (43726 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package 'OmniSharp for Linux (x64)'

```
The code seems to hang here with no errors warnings or log info, I even left it overnight to install with no success.

**Comment by scottpage** [comment]
Same here, except it only does it in a remote container (Remote - Containers extension).

**Comment by scottpage** [comment]
I rolled back to 1.21.3 and then 1.21.2.
No change, same issue.

**Comment by ed-alertedh** [comment]
I switched back to the regular VS Code release and it seems to work again. This is OK for me because the remote development extensions no longer require VS Code Insiders. I think insiders pulls a dev version of this extension and it looks like recent changes to the omnisharp zip layout might be the underlying issue that breaks the installation.

**Comment by jtsom** [comment]
Trying to report an error on this extension and am getting this error. Environment:
Version: 1.47.0-insider
Commit: 0913b1aa43191d8af0ccb4a133d9a8d7c1a81d69
Date: 2020-06-23T09:38:28.751Z
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Darwin x64 19.5.0

C# extension: 1.22.1
