### ISSUE TITLE
The comments in the snippets configuration file csharp.json contain broken links

### ISSUE THREAD

**Issue by ghost** [dotnet/vscode-csharp#3373]
## Environment data
VS Code version: 1.39.2
C# Extension version: 1.2.5

## Steps to reproduce

1. Create a new C# code file
2. Set the cursor to the editor
3. Trigger IntelliSense by typing Ctrl+Space
4. Filter on the string "attribute" or "Equals"
5. Give focus to the snippet items "attribute" or "Equals"
6. Copy the links which are part of the comments
7. Paste the copied links in a browser and try to navigate to them

## Actual behavior

When the user tries to navigate to the pages http://go.microsoft.com/fwlink/?LinkID=85237 and http://go.microsoft.com/fwlink/?LinkID=85238) the server redirects the client to the Microsoft API and reference catalog page as the requested page is moved temporarily.

When the user tries to navigate to the page http://go.microsoft.com/fwlink/?LinkId=85236 the server redirects the client to the page https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/attributes.

## Expected  behavior

When the user tries to navigate to the pages http://go.microsoft.com/fwlink/?LinkID=85237 and http://go.microsoft.com/fwlink/?LinkID=85238 he should land on the pages containing the originally described content. 

For the page http://go.microsoft.com/fwlink/?LinkID=85237 this could be the page  https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/equality-operators#equality-operator-.

For the page http://go.microsoft.com/fwlink/?LinkID=85238 it's hard to determine what the content of the page originally was.

When the user tries to navigate to the page  http://go.microsoft.com/fwlink/?LinkID=85236 he should land the directly on the page without a redirect as the redirect may not work forever. The URL of the new page is https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/attributes.

Before changing links the added value of including links in comments should be taken into account. Currently only two code snippets contain links which can be considered as a form of consistency and the presence of them in these two snippets seems to be arbitrary. Secondly: including them means that they need to be maintained which requires some manual involvement what makes this task error-prone.

**Comment by JoeRobich** [comment]
Cannot reproduce with the current release.
