### ISSUE TITLE
The IntelliSense list does not display items of the type snippet when it's not filtered

### ISSUE THREAD

**Issue by ghost** [dotnet/vscode-csharp#3374]
## Environment data
VS Code version: 1.39.2
C# Extension version: 1.21.5

## Steps to reproduce

1. Open any C# code file
2. Set the cursor at any place in the editor window
3. Hit the keys Ctrl + space to open the IntelliSense window

## Actual behavior
The items of the type snippet are not displayed in the menu. But: they are displayed when the user enters a character to filter the list. For example: when the user hits the key 'f' the list of items is filtered and the default snippets 'for', 'foreach' and 'forr' are displayed while they are not when the user scrolls to their index in the list.

## Expected  behavior
The items of the type snippet are displayed in the menu (e.g.: the items  'for', 'foreach' and 'forr') also when the user does not apply a filter on the list of items in the menu.

## Additional information

I verified how this works in Visual Studio 2019 Community Edition. In this application the snippet items are loaded by the IntelliSense window when it's opened without applying a filter.

I deliberately have chosen to create an issue within this repository and not in the vscode repository as i could not reproduce this behavior when i disabled this vscode extension and therefore I assume that this extension can be considered as the responsible component of this described behavior.

**Comment by cartermp** [comment]
Thanks for filing @dennisseders - this will reproduce at first, but eventually the snippets will appear in the completion window. This indicates that there's some kind of delay going on, which we should investigate.

**Comment by JoeRobich** [comment]
Could not reproduce with the current release.
