### ISSUE TITLE
Warnings trigger some projects have trouble loading notifications

### ISSUE THREAD

**Issue by harry-cpp** [dotnet/vscode-csharp#3391]
## Steps to reproduce

Have a project that gives a warning on dotnet restore.

ie. Use a nuget package that targets net framework in a net core app (MonoGame.Extended for example).

## Expected  behavior

No notification.

## Actual behavior

You get a "Some projects have trouble loading. Please review the output for more details." notification but the project and extension load and function just fine.

**Comment by chances** [comment]
Is this related to #1610?

**Comment by JoeRobich** [comment]
This could be an issue with the O# project system. If you are still seeing problems, then open a new issue at https://github.com/OmniSharp/omnisharp-roslyn/issues
