### ISSUE TITLE
Intellisense does not honour entered text!

### ISSUE THREAD

**Issue by khteh** [dotnet/vscode-csharp#3394]
The problem is it does not choose the the text entered by me after the <SPACE> key input when there is no valid selection from the list! In the attached picture below I entered "Id" and press <SPACE> and the text that appears is "IndexOf" instead of my selected text "Id"! So I have to press <BACKSPACE> many times, repeat the text I entered and, fingers-crossed, remember to press <ESCAPE> to cancel the bad suggestion!
![IntellisenseSucks](https://user-images.githubusercontent.com/3871483/68186329-db628400-ffde-11e9-8321-5674b729318f.png)

https://github.com/OmniSharp/omnisharp-vscode/issues/3296

**Comment by cartermp** [comment]
Labeling this as a feature request to enable a "suggestion only mode" for completion, since this will not commit IntelliSense suggestions aggressively like the default does today.

**Comment by JoeRobich** [comment]
@khteh [VS Code provides a couple settings](https://code.visualstudio.com/docs/editor/intellisense#_settings) for completion. Try setting `editor.acceptSuggestionOnCommitCharacter` to `false` and see if that improves your experience.

**Comment by JoeRobich** [comment]
A lot of improvements have been made to O# completion since this issue was opened. If you are still running into problems, please open a new issue at https://github.com/OmniSharp/omnisharp-roslyn/issues
