### ISSUE TITLE
OmniSharp can't find sdks, never

### ISSUE THREAD

**Issue by ghost** [dotnet/vscode-csharp#3450]
## Issue Description ##
OmniSharp can't fiind sdks, sometimes change some setting flower issues can fix it, but next version of omnisharp or C# extension or dotnet-sdk all will be break, how omnisharp can work like that worse. And now I have to say that Java extension works more and more better than C# extension.

## Logs ##
> dotnet --list-sdks
3.0.101 [C:\Users\wenqi\AppData\Local\Scoop\apps\dotnet-sdk\current\sdk]
### OmniSharp log ###
Starting OmniSharp server at 12/10/2019, 3:38:25 PM
    Target: c:\Users\**\Source\Temp\blazorTest

OmniSharp server started.
    Path: C:\Users\***\.vscode\extensions\ms-vscode.csharp-1.21.8\.omnisharp\1.34.8\OmniSharp.exe
    PID: 13428

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.3 - "c:\Users\***\.vscode\extensions\ms-vscode.csharp-1.21.8\.omnisharp\1.34.8\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'c:\Users\***\.vscode\extensions\ms-vscode.csharp-1.21.8\.omnisharp\1.34.8\.msbuild\Current\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.3 - "c:\Users\***\.vscode\extensions\ms-vscode.csharp-1.21.8\.omnisharp\1.34.8\.msbuild\Current\Bin"
            CscToolExe = csc.exe
            CscToolPath = c:\Users\****\.vscode\extensions\ms-vscode.csharp-1.21.8\.omnisharp\1.34.8\.msbuild\Current\Bin\Roslyn
            MSBuildExtensionsPath = c:\Users\***\.vscode\extensions\ms-vscode.csharp-1.21.8\.omnisharp\1.34.8\.msbuild
            MSBuildToolsPath = c:\Users\***\.vscode\extensions\ms-vscode.csharp-1.21.8\.omnisharp\1.34.8\.msbuild\Current\Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\wenqi\Source\Temp\blazorTest'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Users\wenqi\Source\Temp\blazorTest'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\wenqi\Source\Temp\blazorTest\blazorTest.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\wenqi\Source\Temp\blazorTest'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\wenqi\Source\Temp\blazorTest\blazorTest.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\wenqi\Source\Temp\blazorTest' on host 15164.
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\wenqi\Source\Temp\blazorTest\blazorTest.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\wenqi\Source\Temp\blazorTest\blazorTest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: blazorTest
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.40.2
**C# Extension**: 1.21.8

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.0.101
 Commit:    bc5f8df0f5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\wenqi\AppData\Local\Scoop\apps\dotnet-sdk\current\sdk\3.0.101\

Host (useful for support):
  Version: 3.0.1
  Commit:  32085cbc72

.NET Core SDKs installed:
  3.0.101 [C:\Users\wenqi\AppData\Local\Scoop\apps\dotnet-sdk\current\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.1 [C:\Users\wenqi\AppData\Local\Scoop\apps\dotnet-sdk\current\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.1 [C:\Users\wenqi\AppData\Local\Scoop\apps\dotnet-sdk\current\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.1 [C:\Users\wenqi\AppData\Local\Scoop\apps\dotnet-sdk\current\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.21.8|
|vscode-icons|vscode-icons-team|9.6.0|;

</details>

**Comment by JoeRobich** [comment]
Hi @wenqiangxie, 
Sorry you are running into issues. It appears that maybe you installed the .NET Core SDK using Scoop. We recommend using the official installer for you platform to install the .NET Core SDK. 
You can find the installer [here](https://dotnet.microsoft.com/download).
-Joey

**Comment by spVierSechs** [comment]
In case anyone is browsing this issue at a later point and using Linux, building `msbuild` myself helped resolve the issue.

**Comment by flaprano** [comment]
> In case anyone is browsing this issue at a later point and using Linux, building `msbuild` myself helped resolve the issue.

Could you provide more info on what was the solution ?
I'm facing the same problem on Ubuntu (installing .net core with apt or asdf) and Omnisharp can't find the sdk.

**Comment by JoeRobich** [comment]
Hi @flaprano,

If you have followed [the instructions](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1904) on installing .NET Core SDK and still having issues, could you open a new issue and include your logs?

**Comment by flaprano** [comment]
> Hi @flaprano,
> 
> If you have followed [the instructions](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1904) on installing .NET Core SDK and still having issues, could you open a new issue and include your logs?

Of course.
The problem is basically the same described here and on a lot of other issues but I will open a new one. :)

**Comment by AndreiLima9** [comment]
> > Hi @flaprano,
> > If you have followed [the instructions](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1904) on installing .NET Core SDK and still having issues, could you open a new issue and include your logs?
> 
> Of course.
> The problem is basically the same described here and on a lot of other issues but I will open a new one. :)

Do you solve this problem ?

**Comment by flaprano** [comment]
> > > Hi @flaprano,
> > > If you have followed [the instructions](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1904) on installing .NET Core SDK and still having issues, could you open a new issue and include your logs?
> > 
> > 
> > Of course.
> > The problem is basically the same described here and on a lot of other issues but I will open a new one. :)
> 
> Do you solve this problem ?

Not exactly.
I found out that it doesn't work well with asdf and installed sdk just by apt.
In the end it worked.

**Comment by joaomarcos96** [comment]
@flaprano I got it working with `asdf`. I just added the following line to my `.zshrc`:

```zsh
export MSBuildSDKsPath="$ASDF_DIR/installs/dotnet-core/3.1.202/sdk/3.1.202/Sdks"
```

**Comment by flaprano** [comment]
> @flaprano I got it working with `asdf`. I just added the following line to my `.zshrc`:
> 
> ```shell
> export MSBuildSDKsPath="$ASDF_DIR/installs/dotnet-core/3.1.202/sdk/3.1.202/Sdks"
> ```

Thanks.
I will test again.
I remember testing it that way and it didn't work. Perhaps in some update it has been corrected.

**Comment by joaomarcos96** [comment]
@flaprano Please let me know if it worked when you try.

**Comment by lzocateli00** [comment]
@joaomarcos96 I faced the same problem, that is, using Asdf on Linux Ubuntu 20.04, OmniSharp caused the error when opening the program, and did not allow, for example, navigation with F12 between classes. includes the environment variable as you indicated, and it worked, thanks.

**Comment by flaprano** [comment]
> @flaprano Please let me know if it worked when you try.

Hi @joaomarcos96 , sorry on the delay on giving you a feedback.
I changed between projects on my company and now I'm more focused on ruby than c#.
I tried setting the env and in my case it didn't worked.
As your answer has helped others I think the problem may be on my installation or another library that I'm loading on my system.

![image](https://user-images.githubusercontent.com/4006679/91617834-4494f880-e95f-11ea-817e-ff38f9dd76d9.png)

**Comment by mabo3n** [comment]
I also wasn't able to make it work on my Linux machine while managing versions with asdf. Tried most workarounds I found:

- Setting the MSBuildSDKsPath on my .bashrc, as suggested [here](https://github.com/OmniSharp/omnisharp-roslyn/issues/1394#issuecomment-480792868)
- Flagfing UseLegacySdkResolver on .omnisharp.json file as decribed [here](https://github.com/OmniSharp/omnisharp-roslyn/issues/1313#issuecomment-429039879) (tried within each project dir, within the solution dir, and the home dir as the docs [points out](https://github.com/OmniSharp/omnisharp-vscode/wiki/Troubleshooting:-'The-.NET-Core-SDK-cannot-be-located.'-errors#special-instructions))
- Symlink asdf's dotnet-core directory to possible original locations (/usr/share/dotnet/ and /usr/local/bin/dotnet pointing to $ASDF_DIR/installs/dotnet-core/), after seeing [this](https://github.com/OmniSharp/omnisharp-roslyn/issues/1394#issuecomment-494141929) comment.

Maybe that's a compatibility issue with the SDK or OS versions?

 <details> <summary> my dotnet --info output </summary> 

```
NET Core SDK (reflecting any global.json):
 Version:   2.2.207
 Commit:    f7b16a2cd5

Runtime Environment:
 OS Name:     linuxmint
 OS Version:  19.1
 OS Platform: Linux
 RID:         linuxmint.19.1-x64
 Base Path:   /home/marcelbornancin/.asdf/installs/dotnet-core/2.2.207/sdk/2.2.207/

Host (useful for support):
  Version: 2.2.8
  Commit:  b9aa1abc51

.NET Core SDKs installed:
  2.2.207 [/home/marcelbornancin/.asdf/installs/dotnet-core/2.2.207/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.8 [/home/marcelbornancin/.asdf/installs/dotnet-core/2.2.207/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.8 [/home/marcelbornancin/.asdf/installs/dotnet-core/2.2.207/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [/home/marcelbornancin/.asdf/installs/dotnet-core/2.2.207/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

</details>

Anyway, it's not the first time I face problems managing dotnet versions with asdf. I would just follow my rule of thumb of using the mainstream install for dotnet core, and using asdf to anything else.

**Comment by kaiokot** [comment]
@mabo3n  try this
https://github.com/OmniSharp/omnisharp-vscode/issues/2970#issuecomment-541516806
works here!

**Comment by JoeRobich** [comment]
A lot has changed with SDK resolution since this issue was opened. If you are still seeing problems, please open a new issue.
