### ISSUE TITLE
Code completion no longer work for Unity's JobComponentSystem.Entities.ForEach

### ISSUE THREAD

**Issue by CreepGin** [dotnet/vscode-csharp#3469]
## Issue Description ##

Starting from 1.21.8, code completion no longer works inside lambdas from Unity's JobComponentSystem.Entities.ForEach(lambda). https://docs.unity3d.com/Packages/com.unity.entities@0.2/manual/entities_job_foreach.html

1.21.7 and before works fine.

## Steps to Reproduce ##

Please just see 5argon's comment below for pure dotnet sample project (w/o dependency on Unity).

1) Create a new Unity Project
2) Use the Package Manager (inside Unity) to install the Entities package.
3) Create a struct implementing IComponentData:

```c#
public struct Foo : IComponentData {
    public int index;
}
```

3) Create an empty JobComponentSystem.
4) Inside OnUpdate, do 

```
Entities.ForEach((in Foo foo) => {
    foo.
});
```

## Expected Behavior ##

`foo.` should have code completion suggestion for `index`

## Actual Behavior ##

no completion suggestion for `index`

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.41.0
**C# Extension**: 1.21.7

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.2 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.21.5|
|expand-region|letrieu|0.1.4|
|markdown-all-in-one|yzhang|2.6.1|
|mermaid-markdown-syntax-highlighting|bpruitt-goddard|1.0.2|
|unity-debug|Unity|2.7.2|
|vscode-icons|vscode-icons-team|9.6.0|
|vscode-mermaid-preview|vstirbu|1.4.0|
|vscode-test-toggle|smontanari|0.1.1|
|xml|DotJoshJohnson|2.5.0|;

</details>

**Comment by 5argon** [comment]
Any lambda with overload choice as a delegate with input argument cause this issue.
Here's a pure dotnet project that reproduce it : [lambda.zip](https://github.com/OmniSharp/omnisharp-vscode/files/3976514/lambda.zip)

```csharp
using System;

namespace lambda
{
    interface INTERFACE { }

    struct STRUCT : INTERFACE { public int v; }

    class Program
    {
        delegate int DLG<T>(T A) where T : INTERFACE;
        static void Lambda<T>(DLG<T> l) where T : INTERFACE { }

        static void Main(string[] args)
        {
            STRUCT aaOutside = default;
            Console.WriteLine(aaOutside.v);

            Lambda((STRUCT aa) =>
            {
                Console.WriteLine(aa.v);
                return 1;
            });
        }
    }
}
```

<img width="947" alt="Screenshot 2019-12-18 10 23 26" src="https://user-images.githubusercontent.com/5653276/71053472-12e95200-2181-11ea-9df8-009c94175394.png">

<img width="943" alt="Screenshot 2019-12-18 10 23 37" src="https://user-images.githubusercontent.com/5653276/71053476-15e44280-2181-11ea-8962-55e8b67cc1f0.png">

The one inside do not suggest its `public` field `v`, yet if you type that it is a valid code.

**Comment by JoeRobich** [comment]
This appears to be an issue in Roslyn itself. See https://github.com/dotnet/roslyn/issues/40337#issuecomment-566684975

**Comment by filipw** [comment]
nice find

**Comment by jprob** [comment]
Is there a workaround until this is fixed?

**Comment by JoeRobich** [comment]
Closing as the tracking issue has been completed.
