### ISSUE TITLE
Omnisharp support for .NET Core localized Intellisense

### ISSUE THREAD

**Issue by vivmishra** [dotnet/vscode-csharp#3488]
Can Omnisharp team help confirm if it supports the new localized Intellisense for .NET Core in VS Code that was released earlier this month or there needs to be a fix taken to make the localized Intellisense work? 

Guidance: https://docs.microsoft.com/en-us/dotnet/core/install/localized-intellisense
Related Issue: https://github.com/dotnet/core/issues/4032#issuecomment-568908920 

The localized XMLs are located in the following subdirectory (as per language code) for say .NET Core 3.0: 
       _...\dotnet\packs\Microsoft.NETCore.App.Ref\3.0.0\ref\netcoreapp3.0\<lang code>_

**Comment by JoeRobich** [comment]
@vivmishra I downloaded the .NET Core 3.1 French language pack and installed it according to the guidance. Opening a netcoreapp3.1 project in VS Code I do not see localized intellisense. I can see from the OmniSharp log that it is running with the French culture.

<details>
  <summary>OmniSharp Log</summary>
Starting OmniSharp server at 07/01/2020 à 12:28:04
    Target: c:\Users\jorobich\source\repos\test1

OmniSharp server started.
    Path: C:\Users\jorobich\.vscode-insiders\extensions\ms-vscode.csharp-1.21.9\.omnisharp\1.34.9\OmniSharp.exe
    PID: 3924

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 5 MSBuild instance(s)
            1: Visual Studio Enterprise 2019 16.5.29521.150 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin"
            2: Visual Studio Enterprise 2017 15.9.28307.960 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin"
            3: Visual Studio Enterprise 2019 16.5.29703.146 - "C:\Program Files (x86)\Microsoft Visual Studio\Preview16\Enterprise\MSBuild\Current\Bin"
            4: Visual Studio Enterprise 2019 16.4.29613.14 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin"
            5: StandAlone 16.3 - "C:\Users\jorobich\.vscode-insiders\extensions\ms-vscode.csharp-1.21.9\.omnisharp\1.34.9\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Enterprise 2019 16.5.29521.150 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\jorobich\source\repos\test1'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Users\jorobich\source\repos\test1'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\jorobich\source\repos\test1\test1.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\jorobich\source\repos\test1'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\jorobich\source\repos\test1\test1.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\jorobich\source\repos\test1' on host 11356.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\jorobich\source\repos\test1\test1.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\jorobich\source\repos\test1\test1.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: test1
[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
        Solution initialized -> queue all documents for code analysis. Initial document count: 3.
</details>

**Comment by vivmishra** [comment]
Thanks for the follow-up. Maybe we can then keep this issue open for tracking the work to get this working.
