### ISSUE TITLE
Wrong color coding 

### ISSUE THREAD

**Issue by gsscoder** [dotnet/vscode-csharp#3490]
It's more easy to see this [shot](https://imgur.com/a/MeU9ouK).
`foreach` should be violet, I suppose.
My system is **macOS**.

Greetings and thank you for excellent job!

**Comment by JoeRobich** [comment]
The C# extension now supports semantic highlighting and the C# textmate grammar is much improved since this issue was opened. If you are still running into problems, please open a new issue.
