### ISSUE TITLE
"Allow unsafe code in this project" does nothing on Linux

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/vscode-csharp#3525]
### Environment
- Linux Mint 64 bits (Bionic) with Cinnamon
- VS Code 1.41.1
- .NET Core 3.1
- Official C# extension installed: ms-vscode.csharp 1.21.9

### Repro steps

1. Created a C# project using "dotnet new console".
2. In Program.cs, I added an "unsafe" method.
3. VS Code adds the red squiggly line on my new method. I click on the lightbulb and the popup menu says "Allow unsafe code in this project".

#### Expected
The .csproj file will be modified, and the `<AllowUnsafeBlocks>true</AllowUnsafeBlocks>` line will be added
-or-
The build .json file will have the "/unsafe" argument automatically added.
Either way, I was expecting VS Code to be able to _automatically_ remove that error. I don't really mind if the problem is fixed instantly or the next time I build.

#### Actual
Nothing happens - the .csproj and the .json file are unmodified. If I try to build, I get a build error that unsafe code is not allowed unless I add "/unsafe".

### Partial workaround
I had to add `<AllowUnsafeBlocks>true</AllowUnsafeBlocks>` manually to my .csproj, and the project can now build successfully, but the red squiggly line is still under my unsafe method.

Edit:
This issue from Oct 2019 seems to be related, but only talks about the squiggly line not going away: https://github.com/OmniSharp/omnisharp-vscode/issues/3349

@filipw asked for the code that reproes it, here's mine (the squiggly red line shows up on top of `Test`):

```cs
namespace Test
{
    class Program
    {
        unsafe void Test()
        {
        }

        static void Main()
        {
        }
    }
}
```

**Comment by filipw** [comment]
So what you are saying is that it works correctly if it's started/restarted with `<AllowUnsafeBlocks>true</AllowUnsafeBlocks>` set in csproj, it's just that if that setting is not there in the first place (when OmniSharp starts):

a) the code fix doesn't update the csproj correctly
b) even if csproj is updated manually, there is no effect on language services until the restart

Right?

**Comment by carlossanlop** [comment]
@filipw. Yes, the code fix (right clicking on the lightbulb suggestion) does not do the expected automatic change in the csproj, and manually updating the csproj file fixes the issue but VSCode keeps reporting a problem.
Apologies for the late reply, @filipw. I went on vacation and missed this notification somehow.

**Comment by carlossanlop** [comment]
@filipw did you get a chance to look into this? Is there a chance this is an issue on VS Code and not in OmniSharp?

**Comment by Shadowblitz16** [comment]
I can confirm this
I am under kubuntu 20.10 and clicking on the lightblub and allow unsafe doesn't get rid of the errors

**Comment by nonsensation** [comment]
This also happens to me on Windows 10:

```
Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
```


**VSCode version**: 1.63.2
**C# Extension**: 1.23.17


<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  5.0.403 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.23.17|;

</details>

**Comment by JoeRobich** [comment]
This looks to be an issue with O#. If you are still running into this problem, please open a new issue at https://github.com/dotnet/csharp-tmLanguage/issues
