### ISSUE TITLE
The SDK 'Microsoft.NET.Sdk' specified could not be found

### ISSUE THREAD

**Issue by shanekunz** [dotnet/vscode-csharp#3541]
## Issue Description ##
OmniSharp cannot load the project file because it cannot find the .NET SDK.

I know this is not the first time this issue has been posted, but it is not fixed and I believe it's a critical issue. If users cannot properly open a C# project in VS Code with the C# extension, they won't use C# period. I've been ignoring this issue for a while, but it's harder to ignore when working with new code bases.

99% of beginners will give up before solving this issue. You have to open a console tab, scour the internet for error keywords, filter and test dozens of ad hoc GitHub comments, and hope you find this solution. And who knows if the placement of this `omnisharp.json` file varies by operating system. Again, just tough love, but if the C# extension doesn't work out of the box, it means a lot less people will use C#.

I'm happy to help fix this issue once and for all in the code base if someone can give me direction.

## Steps to Reproduce ##
Run Windows OS.
Download latest dotnet core.
Download latest VS code.
Install the latest C# extension.
Open a .csproj project.
Both my Azure Functions projects and ASP.NET Core projects are affected.
Yes, I have .NET Core 2.2 installed, but it fails even if I uninstall.
Then if I create a file `C:\Users\Shane\.omnisharp\omnisharp.json` with the following contents:
```
{
   "MSBuild": {
       "UseLegacySdkResolver": true
   }
}
```
and restart VS Code, OmniSharp starts working.

## Expected Behavior ##
OmniSharp run successfully when opening a project not requiring any obscure troubleshooting.

## Actual Behavior ##
The C# extension, specifically OmniSharp fails to load by default.

### OmniSharp log ###
<details>Starting OmniSharp server at 1/30/2020, 11:23:17 PM
    Target: c:\Users\Shane\Desktop\Azure_Funtion_Test

OmniSharp server started.
    Path: C:\Users\Shane\.vscode\extensions\ms-vscode.csharp-1.21.9\.omnisharp\1.34.9\OmniSharp.exe
    PID: 3192

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Build Tools 2019 16.4.29728.190 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
            2: StandAlone 16.3 - "C:\Users\Shane\.vscode\extensions\ms-vscode.csharp-1.21.9\.omnisharp\1.34.9\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Build Tools 2019 16.4.29728.190 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\Shane\Desktop\Azure_Funtion_Test'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Users\Shane\Desktop\Azure_Funtion_Test'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\Shane\Desktop\Azure_Funtion_Test\Azure_Funtion_Test.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\Shane\Desktop\Azure_Funtion_Test'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\Shane\Desktop\Azure_Funtion_Test\Azure_Funtion_Test.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\Shane\Desktop\Azure_Funtion_Test' on host 6240.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Users\Shane\Desktop\Azure_Funtion_Test\Azure_Funtion_Test.csproj'.
c:\Users\Shane\Desktop\Azure_Funtion_Test\Azure_Funtion_Test.csproj(1,1)
Microsoft.Build.Exceptions.InvalidProjectFileException: The SDK 'Microsoft.NET.Sdk' specified could not be found.  c:\Users\Shane\Desktop\Azure_Funtion_Test\Azure_Funtion_Test.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at OmniSharp.MSBuild.ProjectLoader.EvaluateProjectFileCore(String filePath) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectLoader.cs:line 129
   at OmniSharp.MSBuild.ProjectLoader.BuildProject(String filePath) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectLoader.cs:line 72
   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Load(String filePath, ProjectIdInfo projectIdInfo, ProjectLoader loader) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectFile\ProjectFileInfo.cs:line 98
   at OmniSharp.MSBuild.ProjectManager.LoadOrReloadProject(String projectFilePath, Func`1 loader) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectManager.cs:line 308

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\Users\Shane\Desktop\Azure_Funtion_Test\Azure_Funtion_Test.csproj
</details>

### C# log ###
<details>** No log in console **</details>

## Environment information ##

**VSCode version**: 1.41.1
**C# Extension**: 1.21.9

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\Program Files (x86)\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.2.207 [C:\Program Files (x86)\dotnet\sdk]
  3.1.101 [C:\Program Files (x86)\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|auto-close-tag|formulahendry|0.5.6|
|auto-using|Fudge|0.7.9|
|azure-account|ms-vscode|0.8.8|
|beautify|HookyQR|1.5.0|
|bracket-pair-colorizer|CoenraadS|1.0.61|
|bracket-pair-colorizer-2|CoenraadS|0.0.29|
|code-settings-sync|Shan|3.4.3|
|code-stats-vscode|riussi|1.0.17|
|csharp|ms-vscode|1.21.9|
|dotenv|mikestead|1.0.1|
|github-markdown-preview|bierner|0.0.2|
|gitlens|eamodio|10.2.0|
|graphql-for-vscode|kumar-harsh|1.15.3|
|indent-rainbow|oderwat|7.4.0|
|markdown-checkbox|bierner|0.1.3|
|markdown-emoji|bierner|0.0.9|
|markdown-preview-github-styles|bierner|0.1.6|
|markdown-shortcuts|mdickin|0.12.0|
|markdown-toc|AlanWalk|1.5.6|
|markdown-yaml-preamble|bierner|0.0.4|
|mdmath|goessner|2.4.0|
|path-intellisense|christian-kohler|1.4.2|
|reactnextjssnippets|iJS|1.1.0|
|remote-containers|ms-vscode-remote|0.94.0|
|remote-ssh|ms-vscode-remote|0.48.0|
|remote-ssh-edit|ms-vscode-remote|0.48.0|
|remote-wsl|ms-vscode-remote|0.41.7|
|shopify-liquid|sissel|2.3.0|
|theme-monokai-pro-vscode|monokai|1.1.14|
|vetur|octref|0.23.0|
|vscode-azurefunctions|ms-azuretools|0.20.2|
|vscode-cloak|johnpapa|0.2.0|
|vscode-eslint|dbaeumer|2.0.15|
|vscode-firefox-debug|firefox-devtools|2.6.1|
|vscode-graphql|Prisma|0.2.2|
|vscode-import-cost|wix|2.12.0|
|vscode-markdownlint|DavidAnson|0.33.0|
|vscode-npm-script|eg2|0.3.10|
|vscode-remote-extensionpack|ms-vscode-remote|0.19.0|
|vscode-tailwindcss|bradlc|0.2.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.4|
|vsliveshare|ms-vsliveshare|1.0.1510|
|wordcount|ms-vscode|0.1.0|;

</details>

**Comment by filipw** [comment]
please post your OmniSharp log at debug level - `"omnisharp.logginglevel":"debug"`

**Comment by cartermp** [comment]
@shaneMLK do you see this happen with the latest .NET SDK (3.1.x) and plugin?

**Comment by RedQuark** [comment]
@cartermp I see this happen with:

> .NET Core SDK (reflecting any global.json):
>  Version:   3.1.102
>  Commit:    573d158fea
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.18363
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\3.1.102\
> 
> Host (useful for support):
>   Version: 3.1.2
>   Commit:  916b5cba26
> 
> .NET Core SDKs installed:
>   3.1.102 [C:\Program Files\dotnet\sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

and

> OmniSharp server started.
>    Path: C:\Users\Mark\.vscode\extensions\ms-dotnettools.csharp-1.21.15\.omnisharp\1.34.14\OmniSharp.exe
>    PID: 8556

Bless you @shaneMLK for telling me where to put omnisharp.json on Windows!

**Comment by vsalvino** [comment]
Ditto this issue for me as well.

* Windows 10
* .NET Core 3.1 with an ASP.NET project

Creating `~/.omnisharp/omnisharp.json` as described above fixed the issue!

**Comment by JoeRobich** [comment]
@RedQuark @vsalvino It is unlikely to not be there, but is 'C:\Program Files\dotnet\' included in your Environment Path variable? You can print the contents of your Path variable with powershell by entering `echo $Env:Path.split(';')`

**Comment by RedQuark** [comment]
> @RedQuark @vsalvino It is unlikely to not be there, but is 'C:\Program Files\dotnet' included in your Environment Path variable? You can print the contents of your Path variable with powershell by entering `echo $Env:Path.split(';')`

'C:\Program FIles\dotnet' is indeed included in my path as reported by PowerShell.

**Comment by vsalvino** [comment]
@JoeRobich yes it is on the PATH, the `dotnet` commands all work perfectly fine from any shell as well.

**Comment by ofadieiev** [comment]
I have this problem. Debug logs show a couple of errors about absent DLL:
```
FAILURE: Could not locate 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.CodeAnalysis.Workspaces.resources.dll'
```

And this is true: there is no `Microsoft.CodeAnalysis.Workspaces.resources.dll`, however this library is located here:

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\ManagedLanguages\VBCSharp\LanguageServices\cs
```
I tried to fix it via `$HOME\.omnisharp\omnisharp.json` as suggested [here](https://github.com/OmniSharp/omnisharp-vscode/issues/3360#issuecomment-551274035), BUT OmniSharp then tries to find `Microsoft.Build.resources.dll` in `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\`, and there is no such file, however the file is located in the other directory:

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\en
```

Trying to add this directory to `omnisharp.json` doesn't help.

**Comment by filipw** [comment]
the resources dlls are optional - they do not cause  any failures.

however if you have this issue please post your omnisharp log to get help

**Comment by ofadieiev** [comment]
@filipw Yeah, thanks, as a cross-check I just found that Visual Studio 2019 cannot open the project as well. So seems like there is some issue with the project. (P.S.: I removed my message before I saw your answer. Thanks either way.)

**Comment by JoeRobich** [comment]
There have been lots of improvements since this issue was opened. Please open a new issue with logs if you are still running into this.
