### ISSUE TITLE
vs code omnisharp not working when using a custom csproj name

### ISSUE THREAD

**Issue by wihu** [dotnet/vscode-csharp#3600]
## Issue Description ##
Normally when working with a Unity game project, vs code omnisharp works fine and i get auto complete when typing codes, however, when working on a Unity Package and by specifying asmdef with custom package name e.g. X so it creates X.csproj, omnisharp fails to pick up the project file and instead giving these warns:

```
[warn]: OmniSharp.MSBuild.ProjectSystem
Found project that doesn't exist on disk: /Users/a/MyProject/Assembly-CSharp.csproj
[warn]: OmniSharp.MSBuild.ProjectSystem
Found project that doesn't exist on disk: /Users/a/MyProject/Assembly-CSharp-Editor.csproj
```

## Steps to Reproduce ##
1. Create a Unity Project with asmdef.
2. Open project with vs code.

## Expected Behavior ##
OmniSharp intellisense working.

## Actual Behavior ##
OmniSharp intellisense not working.

### OmniSharp log ###
Starting OmniSharp server at 2/23/2020, 5:46:55 AM
    Target: /Users/a/MyProject/X.sln

OmniSharp server started with Mono 6.4.0.
    Path: /Users/a/.vscode/extensions/ms-vscode.csharp-1.21.12/.omnisharp/1.34.13/omnisharp/OmniSharp.exe
    PID: 2503

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 10.14.6 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 16.4 - "/Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin"
            2: StandAlone 16.4 - "/Users/a/.vscode/extensions/ms-vscode.csharp-1.21.12/.omnisharp/1.34.13/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 16.4 - "/Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin"
            CscToolExe = csc.exe
            CscToolPath = /Users/a/.vscode/extensions/ms-vscode.csharp-1.21.12/.omnisharp/1.34.13/omnisharp/.msbuild/Current/Bin/Roslyn
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/a/MyProject'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/Users/a/MyProject/X.sln'.
[warn]: OmniSharp.MSBuild.ProjectSystem
        Found project that doesn't exist on disk: /Users/a/MyProject/Assembly-CSharp.csproj
[warn]: OmniSharp.MSBuild.ProjectSystem
        Found project that doesn't exist on disk: /Users/a/MyProject/Assembly-CSharp-Editor.csproj
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/a/MyProject'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.EditorConfigWorkspaceOptionsProvider, Order: 200
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/a/MyProject' on host 2200.

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.42.1
**C# Extension**: 1.21.12

<details><summary>Mono Information</summary>
        OmniSharp using global mono :6.4.0</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.2.104 [/usr/local/share/dotnet/sdk]
  2.2.105 [/usr/local/share/dotnet/sdk]
  3.0.100 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.26.3|
|csharp|ms-vscode|1.21.12|
|unity-code-snippets|kleber-swf|1.3.0|
|unity-debug|Unity|2.7.2|
|vscode-docker|ms-azuretools|0.10.0|;

</details>

**Comment by JoeRobich** [comment]
@wihu Sorry things aren't working. Have you checked in Finder that those project files exist under '/Users/a/MyProject/'? Can you also paste the contents of the .sln file?

**Comment by wihu** [comment]
Thank you for prompt response. I intentionally removed default project files (Assembly-CSharp.csproj and Assembly-CSharp-Editor.csproj) because I thought I don't need them, as I am working on a different Package which has its own Assembly definition (asmdef in Unity). 

But now that I put them back, OmniSharp intellisense seems to work (although i got a bunch of warns telling me I load some references that are redundant) . 

So now my conclusion is OmniSharp needs those default csproj files which has references to other csproj files (e.g. X.csproj) and which in turns load them into vs code. Which won't work otherwise.

so I have two sln files now: Assembly-CSharp.sln and X.sln
```

Microsoft Visual Studio Solution File, Format Version 11.00
# Visual Studio 2010
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Assembly-CSharp", "Assembly-CSharp.csproj", "{5642deff-96d8-5f41-19a3-551e281b403a}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Assembly-CSharp-Editor", "Assembly-CSharp-Editor.csproj", "{e77d729d-0f98-20fc-83bd-95d3ec0ad55b}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{5642deff-96d8-5f41-19a3-551e281b403a}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{5642deff-96d8-5f41-19a3-551e281b403a}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{5642deff-96d8-5f41-19a3-551e281b403a}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{5642deff-96d8-5f41-19a3-551e281b403a}.Release|Any CPU.Build.0 = Release|Any CPU
		{e77d729d-0f98-20fc-83bd-95d3ec0ad55b}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{e77d729d-0f98-20fc-83bd-95d3ec0ad55b}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{e77d729d-0f98-20fc-83bd-95d3ec0ad55b}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{e77d729d-0f98-20fc-83bd-95d3ec0ad55b}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
EndGlobal
```
```

Microsoft Visual Studio Solution File, Format Version 11.00
# Visual Studio 2010
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "X", "X.csproj", "{14c153af-0692-e806-88da-c5d528330677}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "X.Editor", "X.Editor.csproj", "{436562a4-ad9c-193c-edf3-d25eaa33b505}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{14c153af-0692-e806-88da-c5d528330677}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{14c153af-0692-e806-88da-c5d528330677}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{14c153af-0692-e806-88da-c5d528330677}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{14c153af-0692-e806-88da-c5d528330677}.Release|Any CPU.Build.0 = Release|Any CPU
		{436562a4-ad9c-193c-edf3-d25eaa33b505}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{436562a4-ad9c-193c-edf3-d25eaa33b505}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{436562a4-ad9c-193c-edf3-d25eaa33b505}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{436562a4-ad9c-193c-edf3-d25eaa33b505}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
EndGlobal

```

**Comment by cartermp** [comment]
Labeling as needs-investigation; this might be a bug but it might also be lacking a design to handle a particular unity scenario

**Comment by JoeRobich** [comment]
Closing as the issue was the missing .csproj files. Also, recommended to use the Unity extension for VS Code.
