### ISSUE TITLE
Could you support the jupyter notebook for c# in VS Code?

### ISSUE THREAD

**Issue by Color-Dark** [dotnet/vscode-csharp#3618]
Issue Type: <b>Feature Request</b>

The python extension has support jupyter notebook, would c# extension support jupyter notebook in the furture?

Extension version: 1.21.12
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.19569

**Comment by JoeRobich** [comment]
@jonsequitur With all the work on dotnet interactive, seems like something we could work on?

**Comment by filipw** [comment]
this is a great idea 👍

**Comment by biiiipy** [comment]
Please do!

**Comment by dharmaturtle** [comment]
We have this in the meantime: https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.dotnet-interactive-vscode

**Comment by mzhukovs** [comment]
Any updates on this? Would be great!

**Comment by heartacker** [comment]
notebook format, we need this

**Comment by mikadumont** [comment]
C# is supported in the polyglot notebooks: https://code.visualstudio.com/docs/languages/polyglot
