### ISSUE TITLE
Colorization does not handle @$

### ISSUE THREAD

**Issue by 333fred** [dotnet/vscode-csharp#3654]
## Issue Description ##

`$@` strings are correctly recognized as multi-line interpolated string literals, but `@$` strings are not.

## Steps to Reproduce ##

Make a string with `@$`, put some escaped braces in it (`{{` and `}}`), and type between them. They will be recognized and colorized as if they were in a regular block.

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.43.0
**C# Extension**: 1.21.13

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.102
 Commit:    573d158fea

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.102/

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.102 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 3.1.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|auto-close-tag|formulahendry|0.5.6|
|auto-rename-tag|formulahendry|0.1.1|
|azure-account|ms-vscode|0.8.8|
|azure-pipelines|ms-azure-devops|1.165.1|
|code-settings-sync|Shan|3.4.3|
|cpptools|ms-vscode|0.26.3|
|csharp|ms-dotnettools|1.21.13|
|EditorConfig|EditorConfig|0.14.4|
|gitignore|codezombiech|0.6.0|
|gitlens|eamodio|10.2.1|
|language-haskell|justusadam|2.7.0|
|ocean-dark-extended|kleber-swf|1.5.0|
|path-intellisense|christian-kohler|1.4.2|
|powershell|ms-vscode|2020.3.0|
|remote-ssh|ms-vscode-remote|0.50.0|
|remote-ssh-edit|ms-vscode-remote|0.50.0|
|vim|vscodevim|1.13.0|
|vscode-hexdump|slevesque|1.7.2|
|vscode-icons|vscode-icons-team|10.0.0|
|vscode-il|soltys|0.0.1|
|vscode-pull-request-github|GitHub|0.14.0|
|vsonline|ms-vsonline|1.0.1736|
|xml|DotJoshJohnson|2.5.0|;

</details>

**Comment by JoeRobich** [comment]
Closing as this was fixed in the textmate grammar.
