### ISSUE TITLE
Add references and NuGet packages via light bulb

### ISSUE THREAD

**Issue by jrieken** [dotnet/vscode-csharp#366]
_From @lfrodrigues on May 19, 2016 9:39_

Is there a way to configure Visual Studio Code so that the intellisence will automatically inset "using" statements (reference to class library) just like in Eclipse or Visual Studio does?

In Visual Studio we can use SHIFT + ALT + F10:

![image](https://cloud.githubusercontent.com/assets/301004/15389248/da270b7c-1dad-11e6-8d39-1a8bbd65cfd5.png)

_Copied from original issue: Microsoft/vscode#6524_

**Comment by jrieken** [comment]
VS Code as the [apis](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3439) for this and now it's up to the extension to this. Moving this item to omnisharp-vscode.

**Comment by JoeRobich** [comment]
The C# extension will now offer to add a using directive if you reference a class name from the BCL or NuGet packages used in your project. It will do this from a Code Action and through the Completion list.
