### ISSUE TITLE
Everytime Visual Studio code update itself, Omnisharp installed again and again?

### ISSUE THREAD

**Issue by anirugu** [dotnet/vscode-csharp#3683]
I was using Visual studio on 2 of my machine and I see similar behavior on both machine. Suddenly I close the Visual studio code and it's get updated and now I need to wait for getting omnisharp setup again. What it does is downloading things again to make it work. Can not it just enabled the last one and than update to  the latest one.

This thing cause a problem like if I am on slow internet, it will take time. I reported similar behavior on VS code also https://github.com/microsoft/vscode/issues/92682

**Comment by NTaylorMullen** [comment]
@JoeRobich if we move a lot of our stuff over to the https://github.com/dotnet/vscode-dotnetcore infrastructure this will be resolved significantly

**Comment by JoeRobich** [comment]
The packaging and acquisition of dependencies has changes since this issue was opened. If you are still seeing problems, please open a new issue.
