### ISSUE TITLE
Switch snippets autofill not working

### ISSUE THREAD

**Issue by sartubakia** [dotnet/vscode-csharp#3689]
## 3689  Issue Description ##
Switch statement snippets does not autofill enum variables.
## Steps to Reproduce ##
Simple create enum then try to autofill cases with switch snippets
https://i.gyazo.com/116a2b8c11e3c8ab4603e2304000f1e4.mp4
## Expected Behavior ##
Switch statement should add all cases from enum after enter variable name and hit tab
## Actual Behavior ##
snippets just add default: 
### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.43.1
**C# Extension**: 1.21.15

<details><summary>Mono Information</summary>
        OmniSharp using global mono :6.6.0</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.102
 Commit:    573d158fea

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.102/

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.101 [/usr/local/share/dotnet/sdk]
  3.1.102 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.21.15|
|csharp-code-snippets|Somejack|0.0.1|
|csharpextensions|jchannon|1.3.1|
|csharpfixformat|Leopotam|0.0.84|
|material-theme|zhuangtongfa|3.2.4|
|unity-code-snippets|kleber-swf|1.3.0|
|unity-tools|Tobiah|1.2.3|;

</details>

**Comment by JoeRobich** [comment]
@sartubakia That would be a nice experience to have. As a workaround for now you can invoke the 'Add missing cases' refactoring from the switch keyword.

![image](https://user-images.githubusercontent.com/611219/77591714-c57e2e80-6ead-11ea-95b2-6fab882f5d6c.png)

**Comment by JoeRobich** [comment]
Closing as snippets are static and do not have the ability to perform differently based on the context of the code. A code fix exists to provide this functionality.
