### ISSUE TITLE
Intellisense does not show xml doc lists properly

### ISSUE THREAD

**Issue by DanielLidstromTicket** [dotnet/vscode-csharp#3693]
## Issue Description ##

Intellisense does not show xml doc lists properly. Visual Studio does a much better job.

## Steps to Reproduce ##

This class:

```csharp
    /// <summary>
    /// Represents a Room.
    /// <list type="bullet">
    /// <item>
    /// <term>RoomId</term>
    /// <description>int (int)</description>
    /// </item>
    /// <item>
    /// <term>RoomCode</term>
    /// <description>varchar(100) (string)</description>
    /// </item>
    /// <item>
    /// <term>Area</term>
    /// <description>int (int)</description>
    /// </item>
    /// </list>
    /// </summary>
    public class DbRoom
    {
        /// <summary>
        /// int.
        /// </summary>
        public int RoomId { get; set; }

        /// <summary>
        /// varchar(100).
        /// </summary>
        public string RoomCode { get; set; } = null!;

        /// <summary>
        /// int.
        /// </summary>
        public int Area { get; set; }
    }
```

## Expected Behavior ##

Like Visual Studio:

![image](https://user-images.githubusercontent.com/60345105/77734641-5cabc900-7009-11ea-8756-da77a84d0777.png)

## Actual Behavior ##

![image](https://user-images.githubusercontent.com/60345105/77734671-6a614e80-7009-11ea-8943-74d5528a276f.png)

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.43.2
**C# Extension**: 1.21.15

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.21.15|
|Ionide-fsharp|Ionide|4.8.1|
|markdown-all-in-one|yzhang|2.7.0|
|plantuml|jebbs|2.13.6|
|powershell|ms-vscode|2020.3.0|
|vscode-docker|ms-azuretools|1.0.0|
|vscode-markdownlint|DavidAnson|0.34.0|
|vscode-xml|redhat|0.11.0|;

</details>

**Comment by JoeRobich** [comment]
cannot reproduce with the latest release.
