### ISSUE TITLE
No useful replacement for "GetHashCode can be simplified"

### ISSUE THREAD

**Issue by dlidstrom** [dotnet/vscode-csharp#3698]
Issue Type: <b>Bug</b>

The suggestion to simplify GetHashCode does not have a useful replacement, as the replacement causes a compilation error.

Extension version: 1.21.15
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.17763

## Description

I have a class that has operator== operator!= overridden. Intellisense now suggests to override GetHashCode and someone on the teams has overridden it like this:

```csharp
public override int GetHashCode()
{
    return base.GetHashCode();
}
```

Now Intellisense is suggesting a code action to simplify this implementation. However, what is compilable turns into a compiler error.

## Actual Results

These images show the interaction taking place.

### 1

![image](https://user-images.githubusercontent.com/371713/77884278-089d2080-7265-11ea-927e-0f22b8f2aeb8.png)

### 2

![image](https://user-images.githubusercontent.com/371713/77884304-1783d300-7265-11ea-81df-22829b6b1ef0.png)

### 3

![image](https://user-images.githubusercontent.com/371713/77884360-2ec2c080-7265-11ea-90c1-01a16ae0774f.png)

At this point I revert, since I have no idea how to use HashCode.Combine.

## Expected Results

Not sure what is expected, but I don't want a code replacement that turns a compilable statement into one that isn't compilable.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (1.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by JoeRobich** [comment]
Hi @dlidstrom, I would have expected the CodeAction to update your GetHashCode methods to look like

```c#
public override int GetHashCode()
{
    return HashCode.Combine(base.GetHashCode());
}
```

I am seeing the code above be generated. If you are seeing it generate different code, then could you try installing the [1.21.16 pre-release](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.16) from the .vsix and test again ([Installation instructions](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases))?

Before the System.HashCode api was added, implementations of GetHashCode typically looked something like this:
![image](https://user-images.githubusercontent.com/611219/77972148-6f422e80-72a5-11ea-8d96-586bbb52b3f6.png)

But the implementation with HashCode.Combine is simplified to:
```c#
public override int GetHashCode()
{
    return HashCode.Combine(RealNumber, ImaginaryUnit);
}
```

**Comment by DanielLidstromTicket** [comment]
Ok, I got it @JoeRobich. However, I don't get why `HashCode.Combine(base.GetHashCode())` is a simplification over `base.GetHashCode()`?
I don't really like to have beta software installed, as I prefer stability over features. I'll wait for the update and see how it performs.

**Comment by MWFIAE** [comment]
It would be a simplification if there is more than one value that needs to be considered for the hashcode. 
So not really much won in this case as it is. 
However it would be a lot easier to expand the method in the future and plug additional parameters into it.

**Comment by JoeRobich** [comment]
This issue will be resolved by https://github.com/dotnet/roslyn/pull/43700 which will be in the next release of the C# extension.

**Comment by JoeRobich** [comment]
closing as resolved.
