### ISSUE TITLE
Feature Request: Add New Class

### ISSUE THREAD

**Issue by turowicz** [dotnet/vscode-csharp#3713]
`Add New Class` from `C# Extensions` doesn't work when using `Remote - Containers` extension. Can you please add `Add New Class` to the base functionality of Omnisharp? It's actually very strange that such a basic thing does not exist and relies on a 3rd party extension which may work or not. 

## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.103
 Commit:    b7ef045669

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.103/

Host (useful for support):
  Version: 3.0.3
  Commit:  c03f2fe626

.NET Core SDKs installed:
  3.0.103 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
VS Code version: 1.43.2
C# Extension version: 1.21.16

## Steps to reproduce
1. Install `Remote - Containers`
2. Install `C#`
3. Install `C# Extensions`
4. Open a project in a container.
5. Try add new class using the context menu in Explorer.

## Expected  behavior
A new file with new class to appear.

## Actual behavior
Nothing happens.

**Comment by cartermp** [comment]
This would be an interesting feature. It makes sense on the surface, but is more challenging if we think about how the item templates (or equivalents) get distributed. Ideally they would come as a part of the .NET SDK, but that isn't the case today. So there's perhaps a more general question of distributing these assets so plugins like thiscan make use of them.

**Comment by turowicz** [comment]
At least make an "official" Omnisharp edition of "C# Extensions". All we need is ability to add a New Class/Interface that will have the right namespace and name.

**Comment by KreativJos** [comment]
The extension you are using is probably the original one, which has some issues. 
I have forked it and some fixes have been made. Try the 'C# Extensions' by JosKreativ.

But it would be nice indeed if those simple features would be included in Omnisharp.

**Comment by turowicz** [comment]
@KreativJos I've tried all of the forks, none of them work with Containers extension

**Comment by JoeRobich** [comment]
Closing as there are no plans to these commands to the C# extension. It is recommended to use the dotnet CLI from the Terminal to generate new templated files.
