### ISSUE TITLE
Launching from terminal

### ISSUE THREAD

**Issue by elizabethdinella** [dotnet/vscode-csharp#3720]
Hello,

Is there a way to launch the extension via terminal?
I would like to interact with the extension without VScode by attaching to the specified port. Is this possible?

## Environment data
.NET Core SDK (reflecting any global.json):
 Version:   3.1.200
 Commit:    c5123d973b

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /home/edinella/.dotnet/sdk/3.1.200/

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.200 [/home/edinella/.dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [/home/edinella/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [/home/edinella/.dotnet/shared/Microsoft.NETCore.App]
VS Code version:
C# Extension version:

Thanks!

**Comment by deitry** [comment]
Are you looking for something like https://github.com/OmniSharp/Omnisharp-vim ?
Here are common integrations of Omnisharp: http://www.omnisharp.net/#integrations

**Comment by elizabethdinella** [comment]
I'm looking to programmatically access the refactorings through my own script (not an IDE). Is this possible with any of the integrations?

**Comment by cartermp** [comment]
Hey @elizabethdinella, thanks for filing the issue. This isn't considered in scope for the plugin. However, there is a different tool called `dotnet-format` that we're planning on having run analyzers and code fixes from the command-line. The issue tracking that is here: https://github.com/dotnet/format/issues/416 

If you have requirements about what the tool should do and want to help out with it at all, the folks involved would love to hear about it!

I'll close the issue out in favor of dotnet-format.
