### ISSUE TITLE
omnisharp Extension taking 5 Gb of RAM. So VS code is hanging

### ISSUE THREAD

**Issue by vinothmahalingam** [dotnet/vscode-csharp#3737]
## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.102 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

## Actual behavior

I am having 8 Gb of RAM in my system it that 5Gb occupied by Omnisharp.

Because of that when i start to debug my Visual studio code goes to not responsding.

**Comment by SuperDIMMaX** [comment]
some problem. "hellow world" app - "using OpenGL.NET" - 100% of 1 core and memory leak  - once i see 1.5+ gb
i not do anyfing.. not coding, debug, etc... project just opened in background
_Windows 7_ - _.NET 5.0 prev3_ - probality not depended on NET and Windows version

**Comment by JoeRobich** [comment]
Closing as there have been no recent reports. If you are still seeing problems, please open a new issue with updated logs.
