### ISSUE TITLE
Add "Suppress" to quick actions

### ISSUE THREAD

**Issue by RussKie** [dotnet/vscode-csharp#3811]
## Environment data
`dotnet --info` output: .NET 5 P6
VS Code version: 1.43

## Steps to reproduce

Have a C# code that is violating some Roslyn rule, and there is a quick action is available for.
There is an option to fix the violation, but there is no option to suppress it (which sometime may be necessary). The same functionality is provided by VS:

![image](https://user-images.githubusercontent.com/4403806/83089340-73d66800-a0d9-11ea-994b-e3fe03bad79b.png)

## Actual behavior

The quick action context menu look almost identical to VS's, just missing the "Suppress" option
![image](https://user-images.githubusercontent.com/4403806/83089349-78028580-a0d9-11ea-847c-de20a40a6775.png)

**Comment by JoeRobich** [comment]
Suppress code actions are available when using the Roslyn LSP.
