### ISSUE TITLE
Semantic highlighting is incorrect when viewing diffs

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/vscode-csharp#3820]
See example below. Note that symbol info is also wrong when viewing a diff. It makes me wonder if perhaps semantic information should be disabled in certain "derived" documents.

![image](https://user-images.githubusercontent.com/5833655/83432086-30d40780-a3ed-11ea-9a5a-ff56d990c1bf.png)

Note that symbol info is also wrong when viewing a diff. It makes me wonder if perhaps semantic information should be disabled in certain "derived" documents. e.g.

![image](https://user-images.githubusercontent.com/5833655/83432227-6d9ffe80-a3ed-11ea-8b83-4a4a02f3833e.png)

/cc @JoeRobich

**Comment by JoeRobich** [comment]
This has been resolved and does not reproduce in the current release.
