### ISSUE TITLE
Doesn't look for closest global.json file

### ISSUE THREAD

**Issue by fsigalov** [dotnet/vscode-csharp#3859]
Please paste the output from your clipboard
## Issue Description ##
In dotnet. it looks for global.json starting from current directory and walking up. It looks like omnisharp is going in the opposite direction
## Steps to Reproduce ##
This is roughly my folder structure. Folder project is open.
|- global.json <2.1.509>
|-project
|--global.json <2.1.802>

## Expected Behavior ##
It should use the closest global.json, which is 802 in this case
## Actual Behavior ##
In vs code I get errors complaining about 509

## Logs ##
A compatible installed .NET Core SDK for global.json version [2.1.509] from [/mnt/e/depot/mtmain2/global.json] was not found
### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>
OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/mnt/e/depot/mtmain2/private/mt/test/TextSegmentationUnitTests' on host 6464.
A compatible installed .NET Core SDK for global.json version [2.1.509] from [/mnt/e/depot/mtmain2/global.json] was not found
Install the [2.1.509] .NET Core SDK or update [/mnt/e/depot/mtmain2/global.json] with an installed .NET Core SDK:

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.46.1
**C# Extension**: 1.22.1

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.200
 Commit:    c5123d973b

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.200/

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  2.1.802 [/usr/share/dotnet/sdk]
  2.1.805 [/usr/share/dotnet/sdk]
  3.1.200 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.17 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.17 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azds|azuredevspaces|2.0.220200611|
|azure-account|ms-vscode|0.8.11|
|csharp|ms-dotnettools|1.22.1|
|python|ms-python|2020.6.88468|
|python|tht13|0.2.3|
|vscode-aks-tools|ms-kubernetes-tools|0.0.6|
|vscode-kubernetes-tools|ms-kubernetes-tools|1.2.1|
|vscode-yaml|redhat|0.8.0|;

</details>

**Comment by JoeRobich** [comment]
OmniSharp itself is started in the root of the workspace, so whichever global.json applies to that directory. To get the behavior you want you could open the project folder instead.
