### ISSUE TITLE
Support for local function syntax

### ISSUE THREAD

**Issue by Vivraan** [dotnet/vscode-csharp#3869]
```cs
void OnCollisionEnter(Collision other)
{
    int currentSceneIndex = SceneManager.GetActiveScene().buildIndex;
    if (state == State.Alive)
    {...
    }

    void Died()
    {...
    }

    void LevelCleared()
    {...
    }

    IEnumerator LoadSceneAfter(int sceneIndex, float delaySeconds)
    {...
    }
}
```
is rendered as
![image](https://user-images.githubusercontent.com/12777564/85366316-b9554c00-b544-11ea-831f-bac1e822bca8.png)
No matter the theme I select. Please fix.
Also, please add the `value` and `default` keywords too.

**Comment by JoeRobich** [comment]
C# extension now ships with semantic highlighting support as well as an improved textmate grammar.
