### ISSUE TITLE
Using .sln AND workingdirectory at the same time

### ISSUE THREAD

**Issue by iwt-christianseidlitz** [dotnet/vscode-csharp#3870]
## Issue Description ##
In our team we use mixed environments for development. 
Some prefer vscode, some use Visual Studio

We have added a normal Visual Studio sln file to our folder which references all relevant projects for code editing.

Now with this file active, you have no choice but to load OmniSharp for the solution.
When there are projects in the folder, that are not included in the solution, they wont get code analysis, completion and so on.

I cannot chose the root folder from the solution selector. Only the sln file is selectable.
I have to change the sln ending to something else in order to work with c# projects that are not included in the solution.

## Steps to Reproduce ##
- Add sln file
- Reload folder
- Open solution selector dropdown (only sln visible, but should show folder + sln)
- Rename .sln -> .sln.bak
- Reload folder
- Open solution selector dropdown (only root folder visible)

## Expected Behavior ##
In the solution selector dowpdown, the working directory is shown and selectable just like the sln.

## Actual Behavior ##
When a sln is found, only the sln is shown in the solution selector.

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.46.1
**C# Extension**: 1.22.1

<details><summary>Dotnet Information</summary>
.NET Core SDK (gem�� "global.json"):
 Version:   3.1.300
 Commit:    b2475c1295

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  1.1.14 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|back-n-forth|nick-rudenko|3.0.2|
|bracket-pair-colorizer-2|CoenraadS|0.1.4|
|code-settings-sync|Shan|3.4.3|
|csharp|ms-dotnettools|1.22.1|
|csharpextensions|jchannon|1.3.1|
|docomment|k--kato|0.1.12|
|fakesharper|fakesharper|0.3.0|
|gitattributes|hashhar|0.4.1|
|githistory|donjayamanne|0.6.5|
|github-markdown-preview|bierner|0.0.2|
|gitignore|codezombiech|0.6.0|
|highlight-dodgy-characters|nachocab|1.0.0|
|html-preview-vscode|tht13|0.2.5|
|markdown-checkbox|bierner|0.1.3|
|markdown-emoji|bierner|0.0.9|
|markdown-preview-github-styles|bierner|0.1.6|
|markdown-yaml-preamble|bierner|0.0.4|
|mssql|ms-mssql|1.9.0|
|ng-template|Angular|0.901.11|
|powershell|ms-vscode|2020.6.0|
|vs-deploy|mkloubert|14.0.0|
|vsc-rename-terminal-button|sketchbuch|1.1.1|
|vscode-angular2-emmet|jakethashi|2.0.3|
|vscode-diff|fabiospampinato|1.4.0|
|vscode-docker|ms-azuretools|1.3.1|
|vscode-favorites|howardzuo|1.8.0|
|vscode-html-format|mohd-akram|0.0.4|
|vscode-icons|vscode-icons-team|10.1.1|
|vscode-json|andyyaldoo|1.5.0|
|vscode-yaml|redhat|0.8.0|
|vsonline|ms-vsonline|1.0.2390|
|xml-format|mikeburgh|1.0.2|;

</details>

**Comment by JoeRobich** [comment]
Folders containing project files are now shown along with solution files in the dropdown.
