### ISSUE TITLE
Issue with having many .csproj files and Omnisharp loading times

### ISSUE THREAD

**Issue by hybridherbst** [dotnet/vscode-csharp#3875]
## Environment data
VS Code version: 1.46.1
C# Extension version: 1.22.1

I'm using VSCode with Omnisharp for Unity projects, as it's one of the recommended IDEs for Unity.
With the introduction of "packages" and "assembly definitions" there, a medium-sized project can easily have > 100 .csproj files in a single solution. Unity is often touching and changing the csproj files from outside VSCode (e.g. when creating or renaming a script in Unity).

The issue now is that the loading time of Omnisharp seems to increase linearily not with the amount of code, but with the amount of .csproj files. E.g. having all code in a single .csproj takes mere seconds to load, while having the code distributed in those 100 .csproj files (as Unity recommends doing) results in "time from double-clicking a file to having Intellisense/Omnisharp ready" of somewhere around 2-5 minutes. With the frequent changes that Unity is doing to the csproj files (which are not properly updated in VSCode, but requires reopening it right now), this is a really huge workflow issue.

## Steps to reproduce
Create a Unity project on 2019.4
Make sure VSCode is set as external editor
Import a couple of packages from Unity Package Manager
double-click a script file

## Expected  behavior
Quick startup, Omnisharp works after a short wait/load time

## Actual behavior
Omnisharp takes a very long time to load on every change

**Comment by JoeRobich** [comment]
Recommend using the new Unity extension for VS Code.
