### ISSUE TITLE
Wrong syntax highlighting when using `await using`

### ISSUE THREAD

**Issue by gidoca** [dotnet/vscode-csharp#3914]
When creating a simple file that uses the `await using` [construct](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync#using-async-disposable), syntax highlighting is broken below the point where it is used. For example, keywords like `public` are no longer displayed in dark blue, see screenshot below. This is a simple example code:

```csharp
using System;
using System.Threading.Tasks;

namespace vscode_await_using_bug
{
    class Program : IAsyncDisposable
    {
        static async Task Main(string[] args)
        {
            await using (var v = new Program())
            {
                Foo();
            }
        }

        public async ValueTask DisposeAsync()
        {
            await Task.Delay(50);
            Console.WriteLine("Byebye");
        }

        public static void Foo()
        {
            Console.WriteLine("Hello World!");
        }
    }
}
```

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.301/

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  3.1.301 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

VS Code version:
1.47.1

C# Extension version:
1.22.1

## OmniSharp log
Starting OmniSharp server at 7/16/2020, 5:33:04 PM
    Target: /home/gidoca/src/vscode-await-using-bug

OmniSharp server started.
    Path: /home/gidoca/.vscode/extensions/ms-dotnettools.csharp-1.22.1/.omnisharp/1.35.3/run
    PID: 264088

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on ubuntu 20.4 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.4 - "/home/gidoca/.vscode/extensions/ms-dotnettools.csharp-1.22.1/.omnisharp/1.35.3/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/home/gidoca/.vscode/extensions/ms-dotnettools.csharp-1.22.1/.omnisharp/1.35.3/omnisharp/.msbuild/Current/Bin/MSBuild.dll'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.4 - "/home/gidoca/.vscode/extensions/ms-dotnettools.csharp-1.22.1/.omnisharp/1.35.3/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            MSBuildToolsPath = /home/gidoca/.vscode/extensions/ms-dotnettools.csharp-1.22.1/.omnisharp/1.35.3/omnisharp/.msbuild/Current/Bin
            CscToolPath = /home/gidoca/.vscode/extensions/ms-dotnettools.csharp-1.22.1/.omnisharp/1.35.3/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /home/gidoca/.vscode/extensions/ms-dotnettools.csharp-1.22.1/.omnisharp/1.35.3/omnisharp/.msbuild
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/gidoca/src/vscode-await-using-bug'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/home/gidoca/src/vscode-await-using-bug'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/gidoca/src/vscode-await-using-bug'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/gidoca/src/vscode-await-using-bug' on host 263959.

## Steps to reproduce
* Create a file named Program.cs with the content above.

## Expected  behavior
The syntax highlight is the same as synchronous `using`.
![image](https://user-images.githubusercontent.com/241466/87693366-2b5c3200-c78d-11ea-8fe9-c61752cb44f5.png)

## Actual behavior
The syntax highlighting no longer marks keywords correctly. `using` is yellow, `public` and `static` are light blue.
![image](https://user-images.githubusercontent.com/241466/87693321-1da6ac80-c78d-11ea-9c9c-15669e813283.png)

**Comment by JoeRobich** [comment]
@gidoca To workaround some of the limitations of our C# textmate theme, you can enable `editor.semanticHighlighting.enabled` and `csharp.semanticHighlighting.enabled`. It required using a theme that supports semantic highlight. You can try our Visual Studio 2019 Dark theme if you like, or you can tell VS Code that you current theme supports semanticHighlighting by following the instructions here (https://github.com/microsoft/vscode/issues/92740#issuecomment-600100176) to update your "editor.tokenColorCustomizations".

**Comment by JoeRobich** [comment]
The textmate grammar has been updated to fix this problem.
