### ISSUE TITLE
omnisharp.testRunSettings in settings.json

### ISSUE THREAD

**Issue by standstonecraft** [dotnet/vscode-csharp#3916]
## Environment data
`dotnet --info` output:
.NET Core SDK (global.json を反映):
 Version:   3.1.301
 Commit:    7feb845744

ランタイム環境:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.301\

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  3.1.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]       
  Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]       
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]        
  Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
VS Code version: 1.47.2
C# Extension version: v1.22.1

## OmniSharp log
(none)

## Steps to reproduce
1. Open settings.json
2. Type 'omnisharp'

## Expected  behavior
'omnisharp.testRunSettings' key is suggested.

## Actual behavior
'omnisharp.testRunSettings' key is not suggested.
(but work properly.)

![omnisharp-testRunSettings](https://user-images.githubusercontent.com/7663652/87843023-da168480-c8eb-11ea-89c9-d6e2b601ab77.png)

**Comment by JoeRobich** [comment]
closing as resolved.
