### ISSUE TITLE
I wonder why Intellisense doesn't work.

### ISSUE THREAD

**Issue by HemyO** [dotnet/vscode-csharp#3945]
After I created a new project and tried to code something else.
I found Snippets are working, but Intellisense aren't.
![CSharp-Problem](https://user-images.githubusercontent.com/67676350/89097482-d1f13580-d411-11ea-971b-5ba346afa5c8.png)
How should I do next?

**Comment by JoeRobich** [comment]
@HemyO, Sorry you running into issues. Can you please share the complete OmniSharp Log from the Output pane?

**Comment by HemyO** [comment]
Sure.
![Capture](https://user-images.githubusercontent.com/67676350/89097354-ce10e380-d410-11ea-90af-3fdffca850e1.PNG)

**Comment by JoeRobich** [comment]
@HemyO It looks like there was an installation issue and OmniSharp wasn't installed after you installed the extension. Any luck if you uninstall C# and reinstall?
