### ISSUE TITLE
intellisense not working 

### ISSUE THREAD

**Issue by sypo-x** [dotnet/vscode-csharp#3955]
Issue Type: <b>Bug</b>

i have problem with auto complete (intellisense) after i downloded targeting pack "4.7.1" it worked on the project i was working on but whenever i create a new project or go to any other project the intellisense won't work .. so its only working on one project.

Extension version: 1.22.1
VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4310U CPU @ 2.00GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.91GB (6.38GB free)|
|Process Argv|C:/Users/Dell/New 3d -g C:\Users\Dell\New 3d\Assets\move.cs:1:0|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by JoeRobich** [comment]
@sypo-x Can you please share the OmniSharp Log from the output pane for a project that isn't loading properly?

**Comment by LeonardoHabitzreuter** [comment]
Same error here. I'm tryin' to downgrade the dotnet-runtime pkg to version 3.1.4 but everytime I do that the sdk is installed :/

**Comment by Luciden** [comment]
Same issue

**Comment by abitcons** [comment]
same issue

**Comment by JoeRobich** [comment]
Closing due to lack of response.
