### ISSUE TITLE
Random loading problem.

### ISSUE THREAD

**Issue by abdelmonem0** [dotnet/vscode-csharp#3963]
## Issue Description ##
Sometimes when opening vscode for the first time after opening the unity project, OmniSharp  doesnt load, so I have to close vscode and reopen it, but sometimes this doesnt solve the issue so uninstalling Omnisharp and reinstalling it solves the problem. but its a waste of time. thanx. 
### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.47.3
**C# Extension**: 1.22.1

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.22.1|
|html-snippets|abusaidm|0.2.1|
|JavaScriptSnippets|xabikos|1.8.0|
|unity-code-snippets|kleber-swf|1.3.0|
|unity-debug|Unity|2.7.5|
|unity-tools|Tobiah|1.2.3|
|vscode-intelephense-client|bmewburn|1.5.3|
|vscodeintellicode|VisualStudioExptTeam|1.2.9|;

</details>

**Comment by cartermp** [comment]
@mon3om sorry for the issue - could you post an omnisharp log the next time you see this? Unfortunately without the log there's no telling what the problem might be.

**Comment by mon3om** [comment]
Can you please tell me how to get the log?

**Comment by cartermp** [comment]
You can find more info here: https://github.com/OmniSharp/omnisharp-vscode/wiki/Reporting-Issues

**Comment by JoeRobich** [comment]
Recommend using the Unity extension for VS Code.
