### ISSUE TITLE
Intellisense with Unity

### ISSUE THREAD

**Issue by james072898** [dotnet/vscode-csharp#4042]
I opened a new Unity Project, then came to VS to code and the instellisense is not working with the UnityEngine things, only with the basics C# statements. With other projects it works is about the luck, some works, some doesnt.

**Comment by jmarolf** [comment]
@james072898 can you get us an example project where this happens? An Omnisharp log would also help a lot. Thanks!

**Comment by RGFTheCoder** [comment]
If you make a new script, open unity to let it generate metadata, and make sure to "Open C# Project" by right clicking on the project viewer, instead of double clicking a script.

**Comment by RGFTheCoder** [comment]
And try using global mono

**Comment by JoeRobich** [comment]
Recommend using the Unity extension for VS Code.
