### ISSUE TITLE
Intellisense not working.

### ISSUE THREAD

**Issue by HaykShirinyan** [dotnet/vscode-csharp#4047]
Issue Type: <b>Bug</b>

It works at first. But after typing a few more lines, the intelisense stops working completely. 

OmniSharp log:

[2020-09-08 00:00:00.901] [renderer1] [error] Problem invoking 'GetCodeActions' on OmniSharp server: Error: Pending request cancelled: /v2/getcodeactions
[2020-09-08 00:00:05.897] [renderer1] [error] Problem invoking 'GetCodeActions' on OmniSharp server: Error: Pending request cancelled: /v2/getcodeactions

Extension version: 1.23.2
VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (8.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by meysamzare** [comment]
I have the same issue too.........

**Comment by jmarolf** [comment]
can you provide a project that this reproduces on ?

**Comment by julian-vp** [comment]
Same issue. Fresh install of VS Code, fresh install of Omnisharp.  Syntax Highlighting, IntelliSense, Go to Definition, Find All References NOT WORKING

**Comment by Molunerfinn** [comment]
me too

**Comment by matthewjdegarmo** [comment]
@HaykShirinyan, Exact same behavior. I get one tab complete and then it's useless.

**Comment by naster01** [comment]
### How to make it crash 
- dotnet tool install -g dotnet-script
- dotnet script init
- Add a nuget package like this :
```
#r "nuget: CliWrap, 3.2.3"
using CliWrap;
```
- Ctrl+Shift+P -> Restart OmniSharp
- It crashes after a certain time 
![image](https://user-images.githubusercontent.com/1693728/100164722-79451d00-2e86-11eb-867c-8446a3547934.png)

### Logs
```
OmniSharp server started.
    Path: c:\Users\nfs12\.vscode\extensions\ms-dotnettools.csharp-1.23.6\.omnisharp\1.37.3\OmniSharp.exe
    PID: 17236

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2019 16.8.30717.126 - "e:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
            2: StandAlone 16.8.0 - "c:\Users\nfs12\.vscode\extensions\ms-dotnettools.csharp-1.23.6\.omnisharp\1.37.3\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2019 16.8.30717.126 - "e:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\nfs12\OneDrive\Desktop\New folder'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Users\nfs12\OneDrive\Desktop\New folder'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\nfs12\OneDrive\Desktop\New folder'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Found 1 CSX files.
[info]: OmniSharp.Script.ScriptContextProvider
        Searching for compilation dependencies with the fallback framework of 'net5.0'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Added CSX project 'c:\Users\nfs12\OneDrive\Desktop\New folder\main.csx' to the workspace.
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
```
```
[2020-11-24 18:49:23.255] [exthost] [info] ExtensionService#_doActivateExtension ms-dotnettools.csharp {"startup":false,"extensionId":{"value":"ms-dotnettools.csharp","_lower":"ms-dotnettools.csharp"},"activationEvent":"onLanguage:csharp"}
[2020-11-24 18:49:23.255] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/nfs12/.vscode/extensions/ms-dotnettools.csharp-1.23.6/dist/extension
[2020-11-24 18:52:21.468] [exthost] [error] [ms-dotnettools.csharp] provider FAILED
[2020-11-24 18:52:21.468] [exthost] [error] Problem invoking 'GetCodeActions' on OmniSharp server: Error: Pending request cancelled: /v2/getcodeactions
```

**Comment by JoeRobich** [comment]
There have been lots of improvements since this issue was opened. Please open a new issue with logs if you are still running into this.
