### ISSUE TITLE
Clarification On Data Collection

### ISSUE THREAD

**Issue by john01dav** [dotnet/vscode-csharp#4069]
The [license](https://github.com/OmniSharp/omnisharp-vscode/blob/master/RuntimeLicenses/license.txt) for binary distributions has the following in it (emphasis mine):

> a. Data Collection. The software may collect information about you and your use of the software, 
and send that to Microsoft. Microsoft may use this information to provide services and improve 
our products and services.  **You may opt-out of many of these scenarios, but not all, as described 
in the product documentation.**  There are also some features in the software that may enable 
you and Microsoft to collect data from users of your applications. If you use these features, you 
must comply with applicable law, including providing appropriate notices to users of your 
applications together with a copy of Microsoft’s privacy statement. Our privacy statement is 
located at https://go.microsoft.com/fwlink/?LinkID=824704. You can learn more about data 
collection and use in the help documentation and our privacy statement. Your use of the software 
operates as your consent to these practices.
b. Processing of Personal Data. To the extent Microsoft is a processor or subprocessor of 
personal data in connection with the software, Microsoft makes the commitments in the 
European Union General Data Protection Regulation Terms of the Online Services Terms to all 
customers effective May 25, 2018, at http://go.microsoft.com/?linkid=9840733. 

Yet the documentation that I can see (e.g. README.md) does not document what, exactly, is collected and what can and can not be disabled. Such information is vital for me to make an informed decision about using or not using this software.

**Comment by jmarolf** [comment]
All the code that reports telemetry is [here](https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/observers/TelemetryObserver.ts)

We collect the following info:
https://github.com/OmniSharp/omnisharp-vscode/blob/71203748f5c042f4b126ffef0bb03ad68766811e/src/observers/TelemetryObserver.ts#L104-L114

- `SolutionId`, `ProjectId`, and `SessionId` are hashes that do not contain personal info but can be used to track if events in telemetry events came from the same instance. [here](https://github.com/OmniSharp/omnisharp-roslyn/blob/3ef61095eb12fe9859672e0f67d9900674f60ec5/src/OmniSharp.MSBuild/ProjectLoadListener.cs#L35) is where the hashing of these items is done.
- `References`, and `FileExtensions` are also hashed. These hashes can be reversed for known references (like `mscorlib.dll`) but _not_ for dlls that are unique to your project. This is generally used to analyze what the of projects people are using look like. I recently made a [change to caching behavior](https://github.com/dotnet/roslyn/pull/46060) in the C# compiler based on this info.
- `FileCounts` the number of files, also useful when determining what internal compiler caches should be.
- `OutputType`, `ProjectCapabilities`, and `TargetFrameworks` are all info on what sort of assembly is being generated. This is used to track what sorts of projects users are using (how many folks used web projects this months etc.)
- `NetSdkVersion` the version of the sdk you are using to build. It helps us track how quickly new .NET SDKs are being adopted.

**Comment by JoeRobich** [comment]
Closing due to lack of response.
