### ISSUE TITLE
VSCode not loading C# extension

### ISSUE THREAD

**Issue by OlegChep** [dotnet/vscode-csharp#4074]
## Steps to Reproduce ##
Open code via "code ." from local repo.
## Expected Behavior ##
C# extension to work.
## Actual Behavior ##
Extension is not loaded and following error is shown when extension is enabled: [2020-09-18 10:19:05.844] [renderer1] [error] An unknown error occurred. Please consult the log for more details.

If extension is disabled, there is no error.
## Logs ##
[2020-09-18 10:18:58.403] [main] [info] update#setState idle
[2020-09-18 10:19:28.417] [main] [info] update#setState checking for updates
[2020-09-18 10:19:28.634] [main] [info] update#setState idle

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>
Empty
### C# log ###
<details>Post the output from Output-->C# here</details>
Empty
## Environment information ##

**VSCode version**: 1.49.1
**C# Extension**: 1.23.2

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.402\

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  2.1.514 [C:\Program Files\dotnet\sdk]
  2.1.515 [C:\Program Files\dotnet\sdk]
  2.1.516 [C:\Program Files\dotnet\sdk]
  2.1.517 [C:\Program Files\dotnet\sdk]
  2.1.518 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.5.0|
|csharp|ms-dotnettools|1.23.2|
|favorites|kdcro101|2.4.5|
|json-script-tag|sissel|0.3.2|
|json-tools|eriklynd|1.0.2|
|json2csv|khaeransori|0.0.1|
|kuskus-kusto-language-server|rosshamish|1.0.1|
|kusto-syntax-highlighting|josin|1.0.1|
|markdown-all-in-one|yzhang|3.3.0|
|powershell|ms-vscode|2020.6.0|
|prettier-vscode|esbenp|5.6.0|
|prettify-json|mohsen1|0.0.3|
|qub-xml-vscode|qub|1.2.8|
|quicktype|quicktype|12.0.46|
|t4-support|zbecknell|0.5.0|
|team|ms-vsts|1.161.0|
|tt-processor|aisoftware|0.8.0|
|vs-code-xml-format|fabianlauer|0.1.5|
|vscode-fileutils|sleistner|3.0.1|
|vscode-icons|vscode-icons-team|11.0.0|
|vscode-markdownlint|DavidAnson|0.36.3|
|vscode-pull-request-github|GitHub|0.20.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.10|
|xml|DotJoshJohnson|2.5.1|
|xml-format|mikeburgh|1.0.2|;

</details>

**Comment by jmarolf** [comment]
There needs to be a csproj file or sln file in the folder or no me gusta. can you provide a repo?

**Comment by JoeRobich** [comment]
Closing due to lack of response.
