### ISSUE TITLE
Intellisense always Loading...

### ISSUE THREAD

**Issue by jkleinecke** [dotnet/vscode-csharp#4080]
Issue Type: <b>Bug</b>

Intellisense tries to work, but never moves past the Loading... text.  Omnisharp logs do not indicate any errors or on-going activitiy.

Extension version: 1.23.2
VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:21:17.533Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|32.00GB (3.60GB free)|
|Process Argv|. --crash-reporter-id 21773cd3-da3e-428c-8301-33f6e312bc2f|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by wendellestradairely** [comment]
I've been experiencing this for many months now. Intellisense is very slow compared to Visual Studio IDE.

**Comment by JoeRobich** [comment]
@jkleinecke Sorry you are seeing issues. Can you please share your OmniSharp log as well as the output from running `dotnet --info`?

**Comment by jkleinecke** [comment]
It's worth noting that it's working fine now.  I think it has to do with
opening up a folder that contains many solution files and switching between
the projects.  I've since run dotnet restore on all my projects and I'm no
longer experiencing the issue.

Starting OmniSharp server at 9/22/2020, 1:07:59 PM
    Target:
/Users/james/projects/slb-erc/core-service-layer/src/crew-service/CrewService.sln

OmniSharp server started.
    Path:
/Users/james/.vscode/extensions/ms-dotnettools.csharp-1.23.2/.omnisharp/1.37.1/run
    PID: 32511

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 10.15.6 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.8.0 -
"/Users/james/.vscode/extensions/ms-dotnettools.csharp-1.23.2/.omnisharp/1.37.1/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to
'/Users/james/.vscode/extensions/ms-dotnettools.csharp-1.23.2/.omnisharp/1.37.1/omnisharp/.msbuild/Current/Bin/MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.8.0 -
"/Users/james/.vscode/extensions/ms-dotnettools.csharp-1.23.2/.omnisharp/1.37.1/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            MSBuildToolsPath =
/Users/james/.vscode/extensions/ms-dotnettools.csharp-1.23.2/.omnisharp/1.37.1/omnisharp/.msbuild/Current/Bin
            CscToolPath =
/Users/james/.vscode/extensions/ms-dotnettools.csharp-1.23.2/.omnisharp/1.37.1/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath =
/Users/james/.vscode/extensions/ms-dotnettools.csharp-1.23.2/.omnisharp/1.37.1/omnisharp/.msbuild
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in
'/Users/james/projects/slb-erc/core-service-layer/src/crew-service'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in
'/Users/james/projects/slb-erc/core-service-layer/src/crew-service/CrewService.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for
'/Users/james/projects/slb-erc/core-service-layer/src/crew-service/CrewService/CrewService.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for
'/Users/james/projects/slb-erc/core-service-layer/src/crew-service/CrewServiceTest/CrewServiceTest.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in
'/Users/james/projects/slb-erc/core-service-layer/src/crew-service'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider:
OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider,
Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project:
/Users/james/projects/slb-erc/core-service-layer/src/crew-service/CrewService/CrewService.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider:
OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider,
Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider:
OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider:
OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider,
Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider:
OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider,
Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location
'/Users/james/projects/slb-erc/core-service-layer/src/crew-service' on host
31208.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file
'/Users/james/projects/slb-erc/core-service-layer/src/crew-service/CrewService/CrewService.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project
'/Users/james/projects/slb-erc/core-service-layer/src/crew-service/CrewService/CrewService.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project:
/Users/james/projects/slb-erc/core-service-layer/src/crew-service/CrewServiceTest/CrewServiceTest.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file
'/Users/james/projects/slb-erc/core-service-layer/src/crew-service/CrewServiceTest/CrewServiceTest.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project
'/Users/james/projects/slb-erc/core-service-layer/src/crew-service/CrewServiceTest/CrewServiceTest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: CrewService
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: CrewServiceTest

.NET Core SDK (reflecting any global.json):
 Version:   3.1.401
 Commit:    39d17847db

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.401/

Host (useful for support):
  Version: 3.1.7
  Commit:  fcfdef8d6b

.NET Core SDKs installed:
  2.2.107 [/usr/local/share/dotnet/sdk]
  2.2.402 [/usr/local/share/dotnet/sdk]
  3.0.100 [/usr/local/share/dotnet/sdk]
  3.1.103 [/usr/local/share/dotnet/sdk]
  3.1.302 [/usr/local/share/dotnet/sdk]
  3.1.401 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.5
[/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7
[/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.5
[/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7
[/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0
[/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3
[/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6
[/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7
[/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13
[/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.21
[/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5
[/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7
[/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0
[/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3
[/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6
[/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7
[/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by JoeRobich** [comment]
Closing as issue was resolved.
