### ISSUE TITLE
Enable auto fix for suggested quick actions

### ISSUE THREAD

**Issue by totkeks** [dotnet/vscode-csharp#4083]
## Issue Description ##
Simple quick actions with only a single fix are not applied automatically on save. For example, the rule for unnecessary usings - those are not automatically removed on save, even though everything else is formatted on save. Is this because one is code style and the other changes the actual code?

I noticed there are commands `Fix all occurences of a code issue within a document/project/solution`, but I'd rather apply them automatically.

## Steps to Reproduce ##
Have a simple program
```
using System;

namespace MyProgram
{
	class Program
	{
		static int Main(string[] args)
		{
			return 0;
		}
	}
}
```

## Expected Behavior ##
Unnecessary using `using System;` is removed on saving.

## Actual Behavior ##
Unnecessary using `using System;` is still there after saving.

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.49.2
**C# Extension**: 1.23.2

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.1.20452.10
 Commit:    473d1b592e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\

Host (useful for support):
  Version: 5.0.0-rc.1.20451.14
  Commit:  38017c3935

.NET SDKs installed:
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.1.20451.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.1.20452.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|Angular2|johnpapa|9.1.2|
|azure-account|ms-vscode|0.9.3|
|azure-pipelines|ms-azure-devops|1.174.2|
|azurecli|ms-vscode|0.5.0|
|better-toml|bungcip|0.3.2|
|bracket-pair-colorizer-2|CoenraadS|0.2.0|
|cpptools|ms-vscode|1.0.1|
|csharp|ms-dotnettools|1.23.2|
|debugger-for-chrome|msjsdiag|4.12.11|
|docomment|k--kato|0.1.18|
|EditorConfig|EditorConfig|0.15.1|
|git-graph|mhutchie|1.26.0|
|githistory|donjayamanne|0.6.10|
|gitignore|codezombiech|0.6.0|
|gitlens|eamodio|10.2.2|
|hexeditor|ms-vscode|1.3.0|
|ng-template|Angular|0.1001.0|
|postcss|csstools|1.0.9|
|powershell|ms-vscode|2020.6.0|
|prettier-vscode|esbenp|5.7.1|
|quicktype|quicktype|12.0.46|
|remote-containers|ms-vscode-remote|0.140.1|
|stylelint-plus|hex-ci|0.52.10|
|team|ms-vsts|1.161.0|
|vetur|octref|0.28.0|
|vscode-autohotkey|slevesque|0.2.2|
|vscode-eslint|dbaeumer|2.1.8|
|vscode-icons|vscode-icons-team|11.0.0|
|vscode-markdownlint|DavidAnson|0.36.3|
|vscode-npm-script|eg2|0.3.13|
|vscode-scss|mrmlnc|0.9.0|
|vscode-sort-json|richie5um2|1.18.0|
|vscode-stylelint|stylelint|0.85.0|
|vscode-svgviewer|cssho|2.0.0|
|vscode-typescript-tslint-plugin|ms-vscode|1.2.3|
|vscode-yaml|redhat|0.11.0|
|vscode-zipfs|arcanis|2.0.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.10|
|vsliveshare|ms-vsliveshare|1.0.2740|
|vsliveshare-audio|ms-vsliveshare|0.1.91|
|vsliveshare-pack|ms-vsliveshare|0.4.0|
|vsonline|ms-vsonline|1.0.2823|
|xml|DotJoshJohnson|2.5.1|;

</details>

**Comment by CEbbinghaus** [comment]
It also seems as though there aren't many handlers for common C# warnings so its only a handful or warnings that can be fixed automatically. As much as i would like to see this feature it would be worth a lot more if more warnings could be automatically fixed.

**Comment by JoeRobich** [comment]
@totkeks Does your configuration look something like this users? https://github.com/OmniSharp/omnisharp-vscode/issues/4401 

If not, what are your omnisharp and fixAll settings?

**Comment by JoeRobich** [comment]
Closing due to lack of response.
