### ISSUE TITLE
.NET Core not located

### ISSUE THREAD

**Issue by JustSomeTrash** [dotnet/vscode-csharp#4105]
![Screenshot 2020-10-11 161720](https://user-images.githubusercontent.com/68954075/95680942-6aa7ec80-0bdd-11eb-8d8b-944be4e26851.png)
![Screenshot 2020-10-11 161628](https://user-images.githubusercontent.com/68954075/95680952-74315480-0bdd-11eb-8c08-c53008ebabc9.png)

I have recently started to try and learn C# but when I use VS Code it keep giving me the "The .NET Core SDK cannot be located" error message, although I have downloaded it many times the same thing still happens and I even readded it to the path.

**Comment by gregg-miskelly** [comment]
I am not sure if this is your problem, but you don't want dotnet.exe on your Path, but rather the folder containing dotnet.exe.

**Comment by gregg-miskelly** [comment]
If that doesn't help, here is some more information on the problem: https://github.com/OmniSharp/omnisharp-vscode/wiki/Troubleshooting:-'The-.NET-Core-SDK-cannot-be-located.'-errors
