### ISSUE TITLE
Associate custom file extension to intellisense

### ISSUE THREAD

**Issue by Freddykong76** [dotnet/vscode-csharp#4149]
I'm working with a specific software that compile c# file only if they have the extension ".pcs" . Unfortunately, it is impossible to have Intellisense correctly working if it is not with a true .cs file.

Would it be possible to add a custom file extension to omnisharp configuration file or something like this ?

## Steps to reproduce
create a file with a custom extension, write some c# code in it.

## Expected  behavior
Intellisense working as if the file was a .cs

## Actual behavior
Only code color is working but no other intellisense features are working..

**Comment by JoeRobich** [comment]
Closing as this request is outside the scope of this extension. 

The C# extension requires a .csproj file that is buildable by msbuild. A design-time build is performed to determine what references and which files are contained in the project. If you could get a .csproj to report .pcs file, then this might work.
