### ISSUE TITLE
Syntax highlighting breaks after parenthesis in new line

### ISSUE THREAD

**Issue by webJose** [dotnet/vscode-csharp#4190]
## Issue Description ##
Syntax highlighting fails for methods after constructor if the parenthesis are moved to a new line.

## Steps to Reproduce ##
1. Write a constructor with at least one parameter.
2. Now format it so the opening parenthesis is in the next line.
3.  Now add a method after the constructor.

## Expected Behavior ##
The lines after the constructor should have correct syntax highlighting.
![image](https://user-images.githubusercontent.com/25540842/98434671-74ffbe00-2097-11eb-83a5-2c9291774410.png)

## Actual Behavior ##
All text is white.
![image](https://user-images.githubusercontent.com/25540842/98434662-5ef1fd80-2097-11eb-9a4e-cbc1f18a3d34.png)

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.50.1
**C# Extension**: 1.23.5

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.301\

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|atlascode|atlassian|2.8.3|
|cpptools|ms-vscode|1.1.0|
|csharp|ms-dotnettools|1.23.5|
|debugger-for-chrome|msjsdiag|4.12.11|
|docomment|k--kato|0.1.18|
|git-easy|bibhasdn|1.11.0|
|git-graph|mhutchie|1.27.0|
|gitlens|eamodio|10.2.3|
|hexeditor|ms-vscode|1.3.0|
|remote-wsl|ms-vscode-remote|0.50.1|
|vscode-drawio|hediet|1.0.3|
|vscode-eslint|dbaeumer|2.1.13|
|vscode-language-pack-es|MS-CEINTL|1.50.2|
|vscode-markdownlint|DavidAnson|0.37.2|
|vscode-yaml|redhat|0.12.0|;

</details>

**Comment by JoeRobich** [comment]
The C# extension now supports semantic highlighting as well as an improved textmate grammar.

**Comment by webJose** [comment]
Does this mean that the bug is no longer present?  Apologies, this was opened too long ago and I will need to search for the code that I had formatted this way.

**Comment by JoeRobich** [comment]
@webJose I have moved your issue to https://github.com/dotnet/csharp-tmLanguage/issues/326, which is the repository containing the C# textmate grammar. I can reproduce the highlight error when semantic highlighting is turned off. With semantic highlighting enabled I see
![Image](https://github.com/user-attachments/assets/07eba54b-56e5-4dd7-9652-8f2f53102749)

**Comment by webJose** [comment]
Hello, @JoeRobich .  Thanks for the response.  I see.  Thank you very much for testing this out.  I'll check out if I have it on or not.
