### ISSUE TITLE
Create commands for running/debugging tests

### ISSUE THREAD

**Issue by troydai** [dotnet/vscode-csharp#421]

**Comment by seesharper** [comment]
Any progress on this one ? :)

**Comment by troydai** [comment]
It is supported in c# extension. (I built it before I left the team a year ago.)

**Comment by seesharper** [comment]
and it is a great feature 👍 I was looking for a way to invoke the commands using keyboard shortcuts. 
If you assign a shortcut and put the cursor either in the test name it self or in the body, it will not pick up the method name.
```
Debugging method '[object Object]'...
```

**Comment by DustinCampbell** [comment]
Correct. Commands need to be added that query OmniSharp for the current method name before. This is on the backlog. Contributions are certainly welcome (especially if you'd like to see this sooner rather than later).

**Comment by xen22** [comment]
I also think this would be a great feature (i.e. having a shortcut to trigger the debugging of a test that has the cursor in it)..  :-)

**Comment by jordimontana82** [comment]
Is it possible to tell the C# extension to use a specific configuration rather than just Debug?

Debug tests like this dotnet test --configuration MyConfig

**Comment by mikadumont** [comment]
This should work in O#, C#, and Dev Kit.
