### ISSUE TITLE
.vscode\extensions\ms-dotnettools.csharp-1.23.6\.omnisharp\1.37.3\OmniSharp.exe' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by tharwatgamil** [dotnet/vscode-csharp#4227]
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:

**Comment by JoeRobich** [comment]
@Tharwat322 Perhaps this was an installation issue. Does the file exist at the specified path? If not, you could uninstall and reinstall the c# extension.

**Comment by alanondra** [comment]
Reinstalling doesn't work, even if you go into your user .vscode directory and delete the extension there. The executable never downloads/builds.

**Comment by JoeRobich** [comment]
A lot has changed with O# packaging and acquisition since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
