### ISSUE TITLE
Indenting multiple lines inside of an "if" block, and intenting pasted code. 

### ISSUE THREAD

**Issue by HubKing** [dotnet/vscode-csharp#4228]
## Environment data
`dotnet --info` output:
VS Code version: 1.51.1
C# Extension version: 1.23.6

## Steps to reproduce
1. Create a new if clause
2. Press enter two times to make two empty lines
3. Paste a line of code.

## Expected  behavior
Pasted line is indented.

## Actual behavior
Pasted line is not indented. If I do the same thing with Visual Studio, works as expected, but not VS Code. I am not sure if it is VS Code's problem or OmniSharp's problem. Below is the screen recording of the two applications' behaviours.

Visual Studio
![vs](https://user-images.githubusercontent.com/10900489/99910028-3b81b080-2d2f-11eb-95e3-8c2ec0d3a343.gif)

VS Code
![code](https://user-images.githubusercontent.com/10900489/99910031-3fadce00-2d2f-11eb-95e7-329a115f4c8a.gif)

**Comment by JoeRobich** [comment]
@HubKing VS Code has a `editor.formatOnPaste` setting. Do you see the expected result when that setting is enabled?

**Comment by HubKing** [comment]
> 
> 
> @HubKing VS Code has a `editor.formatOnPaste` setting. Do you see the expected result when that setting is enabled?

That setting worked on a C project, but not on a C# project. Anyway, I think the main cause of this is that when inserting multiple lines by pressing enter, automatic indentation works only for the first enter, and all subsequent lines have no indentation. Is this VS Code's problem?

![image](https://user-images.githubusercontent.com/10900489/100161480-dc6d9880-2ef4-11eb-8d8c-b89789102967.png)

**Comment by JoeRobich** [comment]
A lot has changed with O# formatting since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
