### ISSUE TITLE
"npm run compile" little change for compile

### ISSUE THREAD

**Issue by cdruine** [dotnet/vscode-csharp#4232]
ERROR: .../omnisharp-vscode/src/features/codeActionProvider.ts:103:66 - functions that return promises must be async

Little change is:

 src/features/codeActionProvider.ts | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/features/codeActionProvider.ts b/src/features/codeActionProvider.ts
index d519924..b69b856 100644
--- a/src/features/codeActionProvider.ts
+++ b/src/features/codeActionProvider.ts
@@ -100,7 +100,7 @@ export default class CodeActionProvider extends AbstractProvider implements vsco
 
     private async _runCodeAction(req: protocol.V2.RunCodeActionRequest, token: vscode.CancellationToken): Promise<boolean | string | {}> {
 
-        return serverUtils.runCodeAction(this._server, req).then(response => {
+        return serverUtils.runCodeAction(this._server, req).then(async (response) => {
             if (response) {
                 return buildEditForResponse(response.Changes, this._languageMiddlewareFeature, token);
             }

**Comment by sekhemrekhutawysobekhotep** [comment]
getting same error on Ubuntu 20.04 laptop

```

unni@nigardsbreen ~/src/github.com/OmniSharp/omnisharp-vscode $ npm run compile

> csharp@1.23.7 compile /home/unni/src/github.com/OmniSharp/omnisharp-vscode
> tsc -p ./ && gulp tslint

[08:32:29] Requiring external module ts-node/register
[08:32:32] Using gulpfile ~/src/github.com/OmniSharp/omnisharp-vscode/gulpfile.ts
[08:32:32] Starting 'tslint'...

ERROR: /home/unni/src/github.com/OmniSharp/omnisharp-vscode/src/features/codeActionProvider.ts:103:66 - functions that return promises must be async

[08:32:36] Finished 'tslint' after 3.48 s


   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │      New minor version of npm available! 6.13.4 → 6.14.9       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.14.9   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯

unni@nigardsbreen ~/src/github.com/OmniSharp/omnisharp-vscode $ 
unni@nigardsbreen ~/src/github.com/OmniSharp/omnisharp-vscode $ npm --version
6.13.4
unni@nigardsbreen ~/src/github.com/OmniSharp/omnisharp-vscode $ node --version
v12.16.1

```

**Comment by womsdn** [comment]
Same error on Ubuntu and on Windows:
ERROR: /home/wocli/Documents/OmniSharp/omnisharp-vscode/src/features/codeActionProvider.ts:103:66 - functions that return promises must be async

**Comment by JoeRobich** [comment]
Cannot reproduce with the code from the main branch.
