### ISSUE TITLE
Cannot format Example.cs

### ISSUE THREAD

**Issue by Tymski** [dotnet/vscode-csharp#4233]
## Issue Description ##
Can't format any csharp files
## Steps to Reproduce ##
Open a c# solution, run format document command.
## Expected Behavior ##
Code is formatted.
Or, if there is a problem it should tell why can't it format the .cs file.
## Actual Behavior ##
Very brief notification on the bottom bar shows up
![image](https://user-images.githubusercontent.com/8183632/100134284-4439ca00-2e88-11eb-85dd-f1cfacde5cb3.png)
## Logs ##
Where are the logs?
![image](https://user-images.githubusercontent.com/8183632/100134500-9a0e7200-2e88-11eb-9a09-5a20edf003b4.png)

### OmniSharp log ###
?

### C# log ###
?

## Environment information ##

**VSCode version**: 1.51.1
**C# Extension**: 1.23.6

<details><summary>Dotnet Information</summary>
Zestaw .NET SDK (odzwierciedlenie dowolnego pliku global.json):
 Version:   5.0.100
 Commit:    5044b93829

�rodowisko uruchomieniowe:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  3.1.404 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|batch-format|zhaofinger|0.3.3|
|beautify|HookyQR|1.5.0|
|better-comments|aaron-bond|2.1.0|
|code-settings-sync|Shan|3.4.3|
|csharp|ms-dotnettools|1.23.6|
|csharp-colors|logerfo|0.1.8|
|csv-to-table|phplasma|1.2.3|
|debugger-for-chrome|msjsdiag|4.12.11|
|docomment|k--kato|0.1.19|
|emojisense|bierner|0.8.0|
|eppz-code|eppz|1.2.52|
|gi|rubbersheep|0.2.11|
|ginfuru-vscode-jekyll-syntax|ginfuru|0.1.1|
|github-plus-theme|thenikso|1.2.1|
|gitlens|eamodio|11.0.5|
|html-css-class-completion|Zignd|1.19.0|
|imagemin|knighd|1.0.1|
|increment-selection|albymor|0.2.0|
|JavaScriptSnippets|xabikos|1.8.0|
|jsrefactor|cmstead|2.20.6|
|jupyter|ms-toolsai|2020.11.372831992|
|linux-themes|SolarLiner|1.0.1|
|lorem-ipsum|Tyriar|1.2.0|
|markdown-all-in-one|yzhang|3.4.0|
|markdown-emoji|bierner|0.0.9|
|markdown-formatter|mervin|0.8.9|
|markdown-preview-enhanced|shd101wyy|0.5.13|
|material-icon-theme|PKief|4.4.0|
|mssql|ms-mssql|1.9.0|
|pdf|tomoki1207|1.1.0|
|php-intellisense|felixfbecker|2.3.14|
|prettier-vscode|esbenp|5.8.0|
|prettier-vscode|SimonSiefke|2.0.7|
|prettier-vscode-with-tabs|passionkind|1.1.0|
|python|ms-python|2020.11.371526539|
|rainbow-csv|mechatroner|1.7.1|
|rech-editor-batch|rechinformatica|0.0.19|
|select-part-of-word|mlewand|1.0.1|
|shader|slevesque|1.1.4|
|shaderlabformatter|litefeel|0.4.0|
|shaderlabvscodefree|amlovey|1.2.2|
|shell-format|foxundermoon|7.0.1|
|sky-csv|Hanul|0.0.5|
|sublime-keybindings|ms-vscode|4.0.7|
|svg|jock|1.4.1|
|theme-actual-obsidian|zehfernando|2.1.0|
|theme-cobalt2|wesbos|2.1.6|
|theme-dracula|dracula-theme|2.22.3|
|tinypng|andi1984|0.3.4|
|tinypng|weijialiu|0.0.7|
|unity-code-snippets|kleber-swf|1.3.0|
|unity-debug|Unity|3.0.2|
|unity-tools|Tobiah|1.2.12|
|vscode-autohotkey|slevesque|0.2.2|
|vscode-autoprefixer|mrmlnc|3.0.1|
|vscode-babel-coloring|dzannotti|0.0.4|
|vscode-css-peek|pranaygp|4.0.2|
|vscode-custom-css|be5invis|4.0.1|
|vscode-edit-csv|janisdd|0.5.0|
|vscode-eslint|dbaeumer|2.1.13|
|vscode-gutter-preview|kisstkondoros|0.26.2|
|vscode-html-css|ecmel|0.2.3|
|vscode-imagemin|axetroy|0.5.1|
|vscode-intelephense-client|bmewburn|1.5.4|
|vscode-jekyll-snippets|ginfuru|0.9.3|
|vscode-language-babel|mgmcdermott|0.0.30|
|vscode-markdownlint|DavidAnson|0.37.2|
|vscode-multi-line-tricks|bigous|0.0.3|
|vscode-paste-image|mushan|1.0.4|
|vscode-phpfmt|kokororin|1.0.30|
|vscode-power-mode|hoovercj|2.2.0|
|vscode-react-native|msjsdiag|1.1.1|
|vscode-solution-explorer|fernandoescolar|0.3.11|
|vscode-svgviewer|cssho|2.0.0|
|vscode-unitymeta|PTD|0.0.7|
|vscode-yaml|redhat|0.13.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.10|
|xml|DotJoshJohnson|2.5.1|;

</details>

**Comment by JoeRobich** [comment]
The C# extension does not support loose C# files. For accurate language services C# files must be opened in the context of a project file.
