### ISSUE TITLE
c# not fade out the inactive region

### ISSUE THREAD

**Issue by AkitsukiShintai** [dotnet/vscode-csharp#4240]
not fade out an undefined region in c# files. Like:
![image](https://user-images.githubusercontent.com/26338862/100299920-d3052e80-2fcf-11eb-99cd-57218b26d1a5.png)
I don't define TRANSITION_BACK_CHUNK globally or locally

**Comment by JoeRobich** [comment]
The c# extension now supports semantic highlighting which correctly fades source.
