### ISSUE TITLE
Attribute formatting for fields on multiple lines

### ISSUE THREAD

**Issue by RedSray** [dotnet/vscode-csharp#4259]
## Issue Description ##
I have a problem with a specific formatting. I use CSharp attribute on certain fields and I want them to be on the same line. Everything is fine until my field declaration needs to be wrap on a second line. When this happen the formatter force the attribute above the field

## Steps to Reproduce ##
- Declare a field with an attribute
- Wrap the declaration on a second line 
- Trigger the formatter

## Expected Behavior ##
The formatter keep the attribute on the first line of the field declaration
![image](https://user-images.githubusercontent.com/3038116/101015987-76be8380-3568-11eb-8487-f97db7000553.png)

## Actual Behavior ##
The formatter put the attribute above the first line of the field declaration
![image](https://user-images.githubusercontent.com/3038116/101016033-8a69ea00-3568-11eb-886d-3160cfb1e816.png)

**Comment by JoeRobich** [comment]
O# uses the Roslyn Formatter which can be configured by an .editorconfig. See details at https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-style-rule-options

If there is a particular formatting configuration you are looking for but with no option, you can open a feature request at https://github.com/dotnet/roslyn/issues
