### ISSUE TITLE
Omnisharp folder not created when using VSCode on FreeBSD 

### ISSUE THREAD

**Issue by nkosi23** [dotnet/vscode-csharp#4266]
## Environment data
VS Code version: 1.46.1
C# Extension version: 1.23.6

## OmniSharp log

None exists

## Steps to reproduce

Install the extension and try to use it, whether by running commands such as Omnisharp Restart (& Cie), or even "Csharp report issue", or by writing C# code. 

## Expected  behavior

Commands can be executed, and intellisense is available when editing csharp code.

## Actual behavior

Trying to run any command created by the extension returns a "command not found error". For example, the command "Csharp: report an issue" returns the error "command 'csharp.reportissue' not found". Same with any OmniSharp command, they all return:  "command o.XXX not found" where XXX is the name of the command.

After investigating and looking into the logs submitted by people regarding unrelated issues (unfortunately no log whatsoever is created in my case), [for example here](https://github.com/OmniSharp/omnisharp-vscode/issues/4220), I noticed that people have a ".omnisharp" folder created in '/home/unix-user-name/.vscode/extensions/ms-dotnettools.csharp-1.23.6/" however this is not the case for me, this folder only contains:

-rw-r--r--      2648 Dec  4 21:53 .vsixmanifest
-rw-r--r--    112166 Dec  4 21:53 CHANGELOG.md
-rw-r--r--     1124 Dec  4 21:53 LICENSE.txt
-rw-r--r--    18010 Dec  4 21:53 README.md
drwxr-xr-x      4 Dec  4 21:53 RuntimeLicenses
-rw-r--r--    6704 Dec  4 21:53 ThirdPartyNotices.txt
-rw-r--r--    17777 Dec  4 21:53 debugger-launchjson.md
-rw-r--r--     7021 Dec  4 21:53 debugger.md
drwxr-xr-x       3 Dec  4 21:53 dist
drwxr-xr-x       3 Dec  4 21:53 images
-rw-r--r--  145086 Dec  4 21:53 package.json
-rw-r--r--     2438 Dec  4 21:53 packages-microsoft-prod.deb
drwxr-xr-x       3 Dec  4 21:53 scripts
drwxr-xr-x        3 Dec  4 21:53 snippets
drwxr-xr-x         3 Dec  4 21:53 src
drwxr-xr-x      4 Dec  4 21:53 themes

The extension displayed no error message during installation, in VSCode it appears as if has been installed successfully and is now enabled. I can enable and disable it in the UI, but I cannot use it because of the aforementioned issues. 

My guess is that the installer of the extension tried to download Omnisharp, but since it couldn't find a release for the FreeBSD operating system, it dropped the ball. While my understanding is that there is no official omnisharp build for FreeBSD, the installer of the extension should fail gracefully and not leave the extension in an unusable state. At the very least, the vscode commands of the extension should be installed properly, and we should be provided hooks allowing us to install and run the omnisharp server ourselves for platforms not being officially supported, and set a path in the settings of the extension.

Especially since I am actually able to run the omnisharp-server in a terminal without problem by downloading a linux64 build from github and running "mono OmniSharp.exe". Despite this, right now I am unable to use the extension because some files do not get installed as previously mentioned, and even if files these weren't missing, it doesn't look like there is a hook allowing us to provide our own path to the omnisharp-server. Since I am required to use FreeBSD to develop, I am now forced to revert to using emacs where OmniSharp works properly, but where I am unfortunately much less productive :(

**Comment by JoeRobich** [comment]
@nkosi23 Sorry you are running into installation issues. Can you share any logs from the ".NET" or "OmniSharp Log" dropdown in the Output pane?

**Comment by nkosi23** [comment]
@JoeRobich  Thank you for your assistance. There are no logs in the ".NET" and "Omnisharp Log" output consoles, both just after installing the extension and when trying to run a command (such as Omnisharp Select Project). Only the aforementioned "Command not found" disappearing popup appears when trying to run a command.

**Comment by nkosi23** [comment]
I am still unable to fix this issue, is there a way to build and install the extension manually so that I can try to tinker with the source code?

**Comment by nkosi23** [comment]
Well, I forgot that I literally am on the source code repo, never mind :smile: 
I will try to get my hands dirty on that one

**Comment by nkosi23** [comment]
I think the reason the installer fails silently is that [this function](https://github.com/OmniSharp/omnisharp-vscode/blob/a2c3a9d5024399ee65f77992dd81b63831d5cca6/src/packageManager/PackageFilterer.ts#L13) contains no logic to detect if the required runtimes dependencies are not available for the current platform:

```ts
export async function getNotInstalledPackagesForPlatform(packages: AbsolutePathPackage[], platformInfo: PlatformInformation): Promise<AbsolutePathPackage[]> {
    let platformPackages = filterPlatformPackages(packages, platformInfo);
    return filterAlreadyInstalledPackages(platformPackages);
}
```

```ts
export function filterPlatformPackages(packages: AbsolutePathPackage[], platformInfo: PlatformInformation) {
    if (packages) {
        return packages.filter(pkg => {
            if (pkg.architectures && pkg.architectures.indexOf(platformInfo.architecture) === -1) {
                return false;
            }


            if (pkg.platforms && pkg.platforms.indexOf(platformInfo.platform) === -1) {
                return false;
            }


            return true;
        });
    }
    else {
        throw new PackageError("Package manifest does not exist.");
    }
}
```

This will return true for a platform for which no binary is available for Omnisharp. What is strange however is that while main.ts has logic to check if the platform is supported, the exception [being thrown here](https://github.com/OmniSharp/omnisharp-vscode/blob/a2c3a9d5024399ee65f77992dd81b63831d5cca6/src/platform.ts#L180) does not appear in the console log despite these lines in main.ts:

```ts
    let platformInfo: PlatformInformation;
    try {
        platformInfo = await PlatformInformation.GetCurrent();
    }
    catch (error) {
        eventStream.post(new ActivationFailure());
    }
```
Now this will not solve the actual issue, but figuring this out could prevent similar silent failures for other platforms. As far as running OmniSharp itself on FreeBSD and other platforms for which there is no official binary published, I gather the line that would need to be modified is [this one](https://github.com/OmniSharp/omnisharp-vscode/blob/a2c3a9d5024399ee65f77992dd81b63831d5cca6/src/main.ts#L162):

```ts    
let langServicePromise = OmniSharp.activate(context, extension.packageJSON, platformInfo, networkSettingsProvider, eventStream, optionProvider, extension.extensionPath);
```

So that the language server is invoked by reading a configuration option instead of executing OmniSharp from the package folder (that can't exist in the case of an unsupported platform).

**Comment by nkosi23** [comment]
In terms of preparing a pull request, would it be acceptable to stop [throwing an exception in PlatformInformation](https://github.com/OmniSharp/omnisharp-vscode/blob/a2c3a9d5024399ee65f77992dd81b63831d5cca6/src/platform.ts#L158) but to instead throw [in the isSupportedPlatform function of main.ts](https://github.com/OmniSharp/omnisharp-vscode/blob/a2c3a9d5024399ee65f77992dd81b63831d5cca6/src/main.ts#L208), so that the decision of whether a platform is supported or not can be made depending on whether or not 1) either runtimeDependencies packages exists for the platforms, or configuration options have been set with the path of executable that can be called to run the language server. It looks like isSupportedPlatform would be a proper place to have this logic.

**Comment by nkosi23** [comment]
I have been able to have the extension work by adding "freebsd" to the switch statement of the platform support code, and adding a dummy entry to the runtimeDependencies array linking to the linux url, but I then get omnisharp to ignore the downloaded files by overriding the path to omnisharp in settings.json. I build the extension, and create a vsix file using the provided build script of the repository, and install the extension manually in vscode. This is in a nutshell the overall approach I have taken. The extension has been working like a charm for over a week or so for my basic needs (intellisense, no debugging). 

Considering how central this extension is to the csharp ecosystem, I think it would be a good idea to add out-of-the-box support for non-supported platforms by skipping the automatic download of dependencies for such platforms, and letting the user set the path to the executable in his settings.json file. But looking at the source code, I appreciate that this is a non-trivial change that may require a couple of hours of work to add the necessary abstractions and refactor bits of code.

**Comment by JoeRobich** [comment]
A lot has changed with O# packaging and acquisition since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
