### ISSUE TITLE
Extension host gets terminated

### ISSUE THREAD

**Issue by momvart** [dotnet/vscode-csharp#4270]
## Issue Description ##
A problem that is really annoying and is happening a lot after the last update is extension host termination. I've included some logs found in vscode developer tools console.
## Steps to Reproduce ##
Not obvious. File/Folder creation may be a reason but happens a lot randomly. 

## Logs ##
<details>c:\Users\UserName\.vscode\extensions\ms-dotnettools.csharp-1.23.6\dist\extension.js:16
var r=function(e,t){return(r=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(e,t){e.__proto__=t}||function(e,t){for(var n in t)t.hasOwnProperty(n)&&(e[n]=t[n])})(e,t)};function i(e,t){function n(){this.constructor=e}r(e,t),e.prototype=null===t?Object.create(t):(n.prototype=t.prototype,new n)}},function(e,t,n){"use strict";n.d(t,"a",(function(){return l}));var r=n(0),i=n(50),o=n(97),s=n(8),a=n(78),c=n(27),u=n(65),l=function(e){function t(n,r,i){var s=e.call(this)||this;switch(s.syncErrorValue=null,s.syncErrorThrown=!1,s.syncErrorThrowable=!1,s.isStopped=!1,arguments.length){case 0:s.destination=o.a;break;case 1:if(!n){s.destination=o.a;break}if("object"==typeof n){n instanceof t?(s.syncErrorThrowable=n.syncErrorThrowable,s.destination=n,n.add(s)):(s.syncErrorThrowable=!0,s.destination=new d(s,n));break}default:s.syncErrorThrowable=!0,s.destination=new d(s,n,r,i)}return s}return r.a(t,e),t.prototype[a.a]=functio

[TypeError: Cannot read property 'replace' of null
	at t.post [as _next] (c:\Users\UserName\.vscode\extensions\ms-dotnettools.csharp-1.23.6\dist\extension.js:36:383357)
	at t.__tryOrUnsub (c:\Users\UserName\.vscode\extensions\ms-dotnettools.csharp-1.23.6\dist\extension.js:16:3217)
	at t.next (c:\Users\UserName\.vscode\extensions\ms-dotnettools.csharp-1.23.6\dist\extension.js:16:2362)
	at t._next (c:\Users\UserName\.vscode\extensions\ms-dotnettools.csharp-1.23.6\dist\extension.js:16:1414)
	at t.next (c:\Users\UserName\.vscode\extensions\ms-dotnettools.csharp-1.23.6\dist\extension.js:16:1085)
	at t.next (c:\Users\UserName\.vscode\extensions\ms-dotnettools.csharp-1.23.6\dist\extension.js:16:26271)
	at t.EventStream.post (c:\Users\UserName\.vscode\extensions\ms-dotnettools.csharp-1.23.6\dist\extension.js:36:66622)
	at EventEmitter.<anonymous> (c:\Users\UserName\.vscode\extensions\ms-dotnettools.csharp-1.23.6\dist\extension.js:16:536385)
	at EventEmitter.emit (events.js:228:7)
	at e._fireEvent (c:\Users\UserName\.vscode\extensions\ms-dotnettools.csharp-1.23.6\dist\extension.js:16:535299)
	at e._handleEventPacket (c:\Users\UserName\.vscode\extensions\ms-dotnettools.csharp-1.23.6\dist\extension.js:16:542766)
	at e._onLineReceived (c:\Users\UserName\.vscode\extensions\ms-dotnettools.csharp-1.23.6\dist\extension.js:16:542088)
	at Interface.emit (events.js:223:5)
	at Interface._onLine (readline.js:315:10)
	at Interface._normalWrite (readline.js:460:12)
	at Socket.ondata (readline.js:172:10)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)] {
  vslsStack: [
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}
  ]
}
</details>

### OmniSharp log ###
Nothing

### C# log ###
Nothing

## Environment information ##

**VSCode version**: 1.51.1
**C# Extension**: 1.23.6

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  2.2.300 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.5.0|
|code-spell-checker|streetsidesoftware|1.10.0|
|cpptools|ms-vscode|1.0.1|
|csharp|ms-dotnettools|1.23.6|
|dart-code|Dart-Code|3.14.1|
|escape-quotes|milovidov|1.10.0|
|flutter|Dart-Code|3.14.1|
|flutter-intl|localizely|1.10.1|
|git-graph|mhutchie|1.27.0|
|github-plus-theme|thenikso|1.2.1|
|hexeditor|ms-vscode|1.3.0|
|html-preview-vscode|george-alisson|0.2.5|
|jupyter|ms-toolsai|2020.11.372831992|
|latex-workshop|James-Yu|8.7.2|
|material-icon-theme|PKief|4.4.0|
|msbuild-project-tools|tintoy|0.3.10|
|mssql|ms-mssql|1.9.0|
|netcore-snippets|doggy8088|3.14.0|
|night-owl|sdras|1.1.3|
|powershell|ms-vscode|2020.6.0|
|prettier-vscode|esbenp|3.20.0|
|python|ms-python|2020.11.371526539|
|reg|ionutvmi|1.0.1|
|remote-containers|ms-vscode-remote|0.140.1|
|remote-ssh|ms-vscode-remote|0.55.0|
|remote-ssh-edit|ms-vscode-remote|0.55.0|
|remote-wsl|ms-vscode-remote|0.44.5|
|roslynator|josefpihrt-vscode|3.0.1|
|svg|jock|1.1.1|
|swdc-vscode|softwaredotcom|2.3.19|
|theme-boxythemekit|trongthanh|0.4.1|
|vsc-community-material-theme|Equinusocio|1.4.2|
|vsc-material-theme|Equinusocio|33.0.0|
|vsc-material-theme-icons|equinusocio|1.2.0|
|vscode-autohide|sirmspencer|1.0.7|
|vscode-docker|ms-azuretools|1.8.1|
|vscode-eslint|dbaeumer|2.1.8|
|vscode-html-css|ecmel|0.2.3|
|vscode-pylance|ms-python|2020.11.2|
|vscode-remote-extensionpack|ms-vscode-remote|0.20.0|
|vscode-sqlite|alexcvzz|0.10.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.10|
|vsliveshare|ms-vsliveshare|1.0.3206|
|winteriscoming|johnpapa|1.4.3|
|xml|DotJoshJohnson|2.5.0|;

</details>

**Comment by momt99** [comment]
I've attached the full log. I think it's a simple missing null check.

[-1615015678413.log](https://github.com/OmniSharp/omnisharp-vscode/files/6094958/-1615015678413.log)

**Comment by JoeRobich** [comment]
A lot has changed with O#  since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
