### ISSUE TITLE
Unclear which setting to change to disable the "The .NET Core SDK cannot be located." message

### ISSUE THREAD

**Issue by bjorn3** [dotnet/vscode-csharp#4272]
## Issue Description ##

The "Disable this message in user settings" button only brings me to the user settings without telling me anything about which setting to change,

## Steps to Reproduce ##

Ensure that "The .NET Core SDK cannot be located.". Click on the "Disable this message in user settings" button.

## Expected Behavior ##

The setting used to disable the message is shown.

## Actual Behavior ##

The setting used to disable the message is not shown, but instead the user settings tab is shown as a whole without even telling me which setting to toggle.

## Logs ##

Not relevant.

### OmniSharp log ###

Not relevant.

### C# log ###

Not relevant.

## Environment information ##

**VSCode version**: 1.51.1
**C# Extension**: 1.23.6

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
A valid dotnet installation could not be found.</details>
<details><summary>Visual Studio Code Extensions (not relevant)</summary>

</details>

**Comment by wotori** [comment]
+1
I have the same issue, tired from this allert
![image](https://user-images.githubusercontent.com/10486621/132552989-bea5025e-4aaf-41e7-907b-d5ff86f2ed3a.png)

**Comment by JoeRobich** [comment]
Sorry, the setting is `csharp.suppressDotnetInstallWarning`. You may have issues working with .NET SDK projects, if the SDK is unavailable.

**Comment by SpacewormSera** [comment]
To be 100% clear - in settings.json:   "csharp.suppressDotnetInstallWarning": true

**Comment by JoeRobich** [comment]
Closing as answered.
