### ISSUE TITLE
Omnisharp server is not running

### ISSUE THREAD

**Issue by Arjun0004** [dotnet/vscode-csharp#4294]
I'm new to programming and I don't know what I'm doing.. I was just following brackeys tutorial and had an issue with setting up my code not running on an external terminal. When I wanted to generate the launch.json and tasks.json file.. it's not generating it, and an error shows up on my screen showing 'Unable to generate assets to build and debug. OmniSharp server is not running.'

![image](https://user-images.githubusercontent.com/75514713/102014208-e9a2d800-3d7a-11eb-94da-9ecfdb0f888c.png)
this thing shows up...

I don't know how to prevent this and I don't know if this is even the format I am supposed to write my requrest/issue.. sorry if you can't understand the format of this, please help me with this :D

**Comment by Arjun0004** [comment]
Sorry if you can't understand my format of the file.. I know that this is not the format I was supposed to submit this in but my issue didn't fit in those categories... D:

**Comment by JoeRobich** [comment]
@Arjun0004 Sorry you are running into issues. Can you share the OmniSharp Log from the output pane of VS Code?

**Comment by JoeRobich** [comment]
Closing due to lack of response.
