### ISSUE TITLE
Please advise how to enable intellisense in VSCode with C# OmniSharp v1.23.7

### ISSUE THREAD

**Issue by dcs3spp** [dotnet/vscode-csharp#4311]
I have just installed C# OmniSharp v1.23.7 with VSCode and no intellisense at all. Have also restarted VSCode!

Please advise how to enable intellisense.....
Also Renaming a symbol (a method's implementation name)...does not work. It has no effect and remains the same name!

**VSCode details**
```bash
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z (4 wks ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

omnisharp.useGlobalMono=auto
```

**.Net Core version info**
```bash
.NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.402/

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  3.1.402 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

**Update**
The following day, after a restart intellisense was restored for a few days and then...lost again.....

What causes the intellisense to be switched off???

**Comment by JoeRobich** [comment]
A lot has changed with O# intellisense since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
