### ISSUE TITLE
Omnisharp Errors

### ISSUE THREAD

**Issue by Trimble-Brandon** [dotnet/vscode-csharp#4318]
## Issue Description ##
Multiple errors of:
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application.
        
And Multiple errors of:
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded
        
I have tried; updating Mono, adjusting setting 'Use Global Mono' to Always, reinstalling .NET Core, reinstalling .NET Framework, installing alt versions of the extension 1.23.7, 1.23.6, 1.23.5, 1.23.4, 1.23.3, 1.23.2, 1.23.1, 1.23.0, then back to 1.23.8, setting the mono installation path manually, setting Unity .NET to 4.x, and following this in its entirety:
https://code.visualstudio.com/docs/other/unity
### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>
Starting OmniSharp server at 12/26/2020, 3:28:25 AM
    Target: e:\code\_unitycourse\text_game\Text Adventure-Tales of the Skald\Text Adventure-Tales of the Skald.sln

OmniSharp server started.
    Path: c:\Users\brand\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.6-beta.7\OmniSharp.exe
    PID: 16668

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.8.0 - "c:\Users\brand\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.6-beta.7\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'c:\Users\brand\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.6-beta.7\.msbuild\Current\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.8.0 - "c:\Users\brand\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.6-beta.7\.msbuild\Current\Bin"
            CscToolExe = csc.exe
            CscToolPath = c:\Users\brand\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.6-beta.7\.msbuild\Current\Bin\Roslyn
            MSBuildExtensionsPath = c:\Users\brand\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.6-beta.7\.msbuild
            MSBuildToolsPath = c:\Users\brand\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.6-beta.7\.msbuild\Current\Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'e:\code\_unitycourse\text_game\Text Adventure-Tales of the Skald'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'e:\code\_unitycourse\text_game\Text Adventure-Tales of the Skald\Text Adventure-Tales of the Skald.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'e:\code\_unitycourse\text_game\Text Adventure-Tales of the Skald\Ink-Libraries.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'e:\code\_unitycourse\text_game\Text Adventure-Tales of the Skald\Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'e:\code\_unitycourse\text_game\Text Adventure-Tales of the Skald\Assembly-CSharp-firstpass.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'e:\code\_unitycourse\text_game\Text Adventure-Tales of the Skald\Assembly-CSharp-Editor-firstpass.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'e:\code\_unitycourse\text_game\Text Adventure-Tales of the Skald'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: e:\code\_unitycourse\text_game\Text Adventure-Tales of the Skald\Ink-Libraries.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'e:\code\_unitycourse\text_game\Text Adventure-Tales of the Skald' on host 4084.
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'e:\code\_unitycourse\text_game\Text Adventure-Tales of the Skald\Ink-Libraries.csproj'.
e:\code\_unitycourse\text_game\Text Adventure-Tales of the Skald\Ink-Libraries.csproj
c:\Users\brand\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.6-beta.7\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1180,5): Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: e:\code\_unitycourse\text_game\Text Adventure-Tales of the Skald\Assembly-CSharp.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'e:\code\_unitycourse\text_game\Text Adventure-Tales of the Skald\Assembly-CSharp.csproj'.
e:\code\_unitycourse\text_game\Text Adventure-Tales of the Skald\Assembly-CSharp.csproj
c:\Users\brand\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.6-beta.7\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1180,5): Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: e:\code\_unitycourse\text_game\Text Adventure-Tales of the Skald\Assembly-CSharp-firstpass.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'e:\code\_unitycourse\text_game\Text Adventure-Tales of the Skald\Assembly-CSharp-firstpass.csproj'.
e:\code\_unitycourse\text_game\Text Adventure-Tales of the Skald\Assembly-CSharp-firstpass.csproj
c:\Users\brand\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.6-beta.7\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1180,5): Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: e:\code\_unitycourse\text_game\Text Adventure-Tales of the Skald\Assembly-CSharp-Editor-firstpass.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'e:\code\_unitycourse\text_game\Text Adventure-Tales of the Skald\Assembly-CSharp-Editor-firstpass.csproj'.
e:\code\_unitycourse\text_game\Text Adventure-Tales of the Skald\Assembly-CSharp-Editor-firstpass.csproj
c:\Users\brand\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.6-beta.7\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1180,5): Error: The reference assemblies for .NETFramework,Version=v4.7.1 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: e:\code\_unitycourse\text_game\Text Adventure-Tales of the Skald\Ink-Libraries.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: e:\code\_unitycourse\text_game\Text Adventure-Tales of the Skald\Assembly-CSharp.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: e:\code\_unitycourse\text_game\Text Adventure-Tales of the Skald\Assembly-CSharp-firstpass.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: e:\code\_unitycourse\text_game\Text Adventure-Tales of the Skald\Assembly-CSharp-Editor-firstpass.csproj

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.52.1
**C# Extension**: 1.23.8

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.404
 Commit:    470f6754b3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.404\

Host (useful for support):
  Version: 3.1.10
  Commit:  1721e39439

.NET Core SDKs installed:
  3.1.102 [C:\Program Files\dotnet\sdk]
  3.1.404 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.2|
|cpptools|ms-vscode|1.1.3|
|csharp|ms-dotnettools|1.23.8|
|jupyter|ms-toolsai|2020.12.414227025|
|lua-debug|actboy168|1.30.1|
|material-theme|zhuangtongfa|3.9.12|
|nord-visual-studio-code|arcticicestudio|0.15.0|
|notepadplusplus-keybindings|ms-vscode|1.0.5|
|prettier-vscode|esbenp|5.8.0|
|python|ms-python|2020.12.424452561|
|unity-code-snippets|kleber-swf|1.3.0|
|unity-debug|Unity|3.0.2|
|unity-snippets|YclepticStudios|0.1.2|
|unity-tools|Tobiah|1.2.12|
|vscode-icons|vscode-icons-team|11.0.0|
|vscode-lua|trixnz|0.12.4|;

</details>

**Comment by filipw** [comment]
According to your log, OmniSharp is running on the built in Mono rather than global Mono, which probably means that global Mono is not available on the PATH for the OmniSharp process. Usually this happens when Mono was installed from an unofficial source e.g. brew.

1. Make sure to download global Mono - best using the official installer https://www.mono-project.com/download/stable/ instead of e.g. brew
2. set `"omnisharp.useGlobalMono":"always"`

**Comment by Trimble-Brandon** [comment]
> According to your log, OmniSharp is running on the built in Mono rather than global Mono, which probably means that global Mono is not available on the PATH for the OmniSharp process. Usually this happens when Mono was installed from an unofficial source e.g. brew.
> 
> 1. Make sure to download global Mono - best using the official installer https://www.mono-project.com/download/stable/ instead of e.g. brew
> 2. set `"omnisharp.useGlobalMono":"always"`

Thanks for the reply! However, I have already installed Mono from the official link and not from an unofficial source. I have already set the use global Mono setting to always previous to writing the original post on this forum.

**Comment by JoeRobich** [comment]
@Trimble-Brandon Sorry you are running into issues. Since you are using Windows it is recommended to install either Visual Studio or the Visual Studio Build Tools to get a more complete version of MSBuild. 

1. Go to https://visualstudio.microsoft.com/downloads/
2. In the search box under "All Downloads". Search for "Build Tools".
![image](https://user-images.githubusercontent.com/611219/103577978-a116a000-4e8a-11eb-8148-9f3e96cfcfb1.png)
3. When installing, click the "Individual Components" tab and select .NET Framework 4.7.1 Targeting pack
![image](https://user-images.githubusercontent.com/611219/103578126-de7b2d80-4e8a-11eb-980b-26ea6b56d765.png)

**Comment by Amogh-Mittal** [comment]
I have already answered it in another Issue #4347 
This was the solution to it.

looks like you are using unity engine, I am also a unity User and the solution is pretty simple. Omnisharp is asking you to download the .net Framework Developers pack so that You can develop apps in C#.
[Here is the link to download it.](https://www.microsoft.com/en-us/download/details.aspx?id=56119)

Hope this helps.😀

**Comment by s3intBeko** [comment]
I tried all but was not success then ubundu focial i upgrade mono by https://github.com/mono/mono/issues/19950 link and eveything working well now.

**Comment by Molpo456** [comment]
> According to your log, OmniSharp is running on the built in Mono rather than global Mono, which probably means that global Mono is not available on the PATH for the OmniSharp process. Usually this happens when Mono was installed from an unofficial source e.g. brew.
> 
>     1. Make sure to download global Mono - best using the official installer https://www.mono-project.com/download/stable/ instead of e.g. brew
> 
>     2. set `"omnisharp.useGlobalMono":"always"`

Where am I supposed to set "omnisharp.useGlobalMono":"always ?

**Comment by JoeRobich** [comment]
Closing as answered.
