### ISSUE TITLE
[Feature Request] Config file in 'project/.vscode/omnisharp.json'

### ISSUE THREAD

**Issue by lonix1** [dotnet/vscode-csharp#4328]
## Environment information ##
**VSCode version**: 1.52.1
**C# Extension**: 1.23.8

## Question / Feature Request
The convention in vscode is for all config files to go in `project/.vscode`, this keeps the solution neat and makes the config easily discoverable.

But the omnisharp config file (`omnisharp.json`) only works in the project root.

I asked in the omnisharp repo, and apparently [it's possible](https://github.com/OmniSharp/omnisharp-roslyn/issues/2059#issuecomment-753578581), but only if this extension supports it.

So is there a way to have `project/.vscode/omnisharp.json`? If not, please consider this feature request, thank you!

**Comment by LostTime76** [comment]
+1

I took a poke around the code base recently, and in my uneducated opinion, I can't see this being impossible to implement. It looks like the plugin is already looking for .sln and .csproj folders in an arbitrary directory hierarchy in the root directory after you open vscode. Therefore, I do not know why the plugin expects omnisharp.json to be in a hardcoded location in the root. Shouldn't there exist only one local omnisharp.json in the directory hierarchy? If that's the case, can we not just extend the same arbitrary sln / csproj discovery to the omnisharp.json discovery as well?

**Comment by lonix1** [comment]
Agreed. I'm not requesting to change the location as that would be a breaking change... I'm requesting to support another location (`project/.vscode/omnisharp.json`).

**Comment by JoeRobich** [comment]
This would be a request for O#. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
