### ISSUE TITLE
Control Space not working for me

### ISSUE THREAD

**Issue by AndiRudi** [dotnet/vscode-csharp#4336]
## Issue Description ##

In the [documentation](https://code.visualstudio.com/docs/languages/csharp#_intellisense) it is stated, that by pressing CONTROL SPACE the Intellisense Window opens (on mac). This does not work for me, instead the language of the keyboard changes.

## Steps to Reproduce ##

Open VS Code and press CONTROL + SPACE

## Expected Behavior ##

Intellisense options

## Actual Behavior ##

Language of Keyboard changes (because it is a global mac shortcut?)

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.52.1
**C# Extension**: 1.23.8

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.101/

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  3.1.404 [/usr/local/share/dotnet/sdk]
  5.0.100 [/usr/local/share/dotnet/sdk]
  5.0.101 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|add-reference|adrianwilczynski|1.0.2|
|auto-using|Fudge|0.7.15|
|cpptools|ms-vscode|1.1.3|
|csharp|ms-dotnettools|1.23.8|
|dotnet-test-explorer|formulahendry|0.7.4|
|gitlens|eamodio|11.1.3|
|html-preview-vscode|tht13|0.2.5|
|java|redhat|0.73.0|
|js-debug-nightly|ms-vscode|2021.1.417|
|markdown-pdf|yzane|1.4.4|
|material-icon-theme|PKief|4.4.0|
|msbuild-project-tools|tintoy|0.3.10|
|night-owl|sdras|2.0.0|
|nuget-reverse-package-search|jesschadwick|0.1.68|
|remote-containers|ms-vscode-remote|0.154.2|
|theme-bluloco-light|uloco|3.3.1|
|vscode-docker|ms-azuretools|1.9.0|
|vscode-drawio|hediet|1.2.0|
|vscode-java-debug|vscjava|0.30.0|
|vscode-java-dependency|vscjava|0.16.0|
|vscode-java-pack|vscjava|0.12.1|
|vscode-java-test|vscjava|0.27.0|
|vscode-kubernetes-tools|ms-kubernetes-tools|1.2.1|
|vscode-markdownlint|DavidAnson|0.38.0|
|vscode-maven|vscjava|0.27.0|
|vscode-nuget-gallery|patcx|0.0.24|
|vscode-nuget-package-manager-improved|maxbrister|2.1.0|
|vscode-solution-explorer|fernandoescolar|0.3.11|
|vscode-xml|redhat|0.14.0|
|vscode-yaml|redhat|0.13.0|;

</details>

**Comment by JoeRobich** [comment]
A lot has changed with O# project loading since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
