### ISSUE TITLE
Problem on VS Code start: "Attempted to update project that is not loaded"

### ISSUE THREAD

**Issue by FrederikWolter** [dotnet/vscode-csharp#4345]
## Issue Description ##
When starting Visual Studio Code with a C# project open, a notification appears saying  "Some projects have trouble loading. Please review the output for more details". Looking at the output I think there is a problem finding my installation of the .NET Framework.
But I have the **.NET Framework 4.8 DevPack** installed in 
`C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8`. 
I also tried copying the folder to `C:\Program Files\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8`.

## Expected Behavior ##
Just start VS Code and load project.

## Actual Behavior ##
Fails to load project.

### OmniSharp log ###
<details>Starting OmniSharp server at 14.1.2021, 17:00:00
    Target: c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\MossV4More.sln

OmniSharp server started.
    Path: c:\Users\wolterf2\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.5\OmniSharp.exe
    PID: 20356

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.8.0 - "c:\Users\wolterf2\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.5\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'c:\Users\wolterf2\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.5\.msbuild\Current\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.8.0 - "c:\Users\wolterf2\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.5\.msbuild\Current\Bin"
            CscToolExe = csc.exe
            CscToolPath = c:\Users\wolterf2\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.5\.msbuild\Current\Bin\Roslyn
            MSBuildExtensionsPath = c:\Users\wolterf2\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.5\.msbuild
            MSBuildToolsPath = c:\Users\wolterf2\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.5\.msbuild\Current\Bin
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\MossV4More.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\MossV4More.DataInput\MossV4More.DataInput.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\MossV4More.Start\MossV4More.Start.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\MossV4More.CustomControls\MossV4More.CustomControls.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\MossV4More.FastReportCreater\MossV4More.FastReportCreater.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\MossV4More.Model.Produktiv\MossV4More.Model.Produktiv.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\Moss4VMore.Model.Test\MossV4More.Model.Test.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\MossV4More.ExternalSources\MossV4More.ExternalSources.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\MossV4More.Versioning\MossV4More.Versioning.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\MossV4More.DataInput\MossV4More.DataInput.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More' on host 4452.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\MossV4More.DataInput\MossV4More.DataInput.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\MossV4More.DataInput\MossV4More.DataInput.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\MossV4More.Start\MossV4More.Start.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.8,Profile=Client were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\MossV4More.Start\MossV4More.Start.csproj'.
c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\MossV4More.Start\MossV4More.Start.csproj
c:\Users\wolterf2\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.5\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1180,5): Error: The reference assemblies for .NETFramework,Version=v4.8,Profile=Client were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\MossV4More.CustomControls\MossV4More.CustomControls.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\MossV4More.CustomControls\MossV4More.CustomControls.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\MossV4More.CustomControls\MossV4More.CustomControls.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\MossV4More.FastReportCreater\MossV4More.FastReportCreater.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.8,Profile=Client were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\MossV4More.FastReportCreater\MossV4More.FastReportCreater.csproj'.
c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\MossV4More.FastReportCreater\MossV4More.FastReportCreater.csproj
c:\Users\wolterf2\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.5\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1180,5): Error: The reference assemblies for .NETFramework,Version=v4.8,Profile=Client were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\MossV4More.Model.Produktiv\MossV4More.Model.Produktiv.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\MossV4More.Model.Produktiv\MossV4More.Model.Produktiv.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\MossV4More.Model.Produktiv\MossV4More.Model.Produktiv.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\Moss4VMore.Model.Test\MossV4More.Model.Test.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\Moss4VMore.Model.Test\MossV4More.Model.Test.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\Moss4VMore.Model.Test\MossV4More.Model.Test.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\MossV4More.ExternalSources\MossV4More.ExternalSources.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\MossV4More.ExternalSources\MossV4More.ExternalSources.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\MossV4More.ExternalSources\MossV4More.ExternalSources.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\MossV4More.Versioning\MossV4More.Versioning.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for .NETFramework,Version=v4.8,Profile=Client were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file 'c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\MossV4More.Versioning\MossV4More.Versioning.csproj'.
c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\MossV4More.Versioning\MossV4More.Versioning.csproj
c:\Users\wolterf2\.vscode\extensions\ms-dotnettools.csharp-1.23.8\.omnisharp\1.37.5\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1180,5): Error: The reference assemblies for .NETFramework,Version=v4.8,Profile=Client were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

[info]: OmniSharp.MSBuild.ProjectManager
        Update project: MossV4More.DataInput
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\MossV4More.Start\MossV4More.Start.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: MossV4More.CustomControls
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\MossV4More.FastReportCreater\MossV4More.FastReportCreater.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: MossV4More.Model.Produktiv
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: MossV4More.Model.Test
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: MossV4More.ExternalSources
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: c:\Users\wolterf2\Desktop\test\MOSS4More\MossV4More\MossV4More.Versioning\MossV4More.Versioning.csproj
</details>

### C# log ###
<details>nothing</details>

## Environment information ##

**VSCode version**: 1.52.1
**C# Extension**: 1.23.8

<details><summary>Dotnet Information</summary>
.NET SDK (gem�� "global.json"):
 Version:   5.0.101
 Commit:    d05174dc5a

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.23.8|
|plantuml|jebbs|2.14.1|;

</details>

**Comment by JoeRobich** [comment]
A lot has changed with O# project loading since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
