### ISSUE TITLE
Syntax highlighting on interfaces not working

### ISSUE THREAD

**Issue by azydevelopment** [dotnet/vscode-csharp#4352]
Issue Type: <b>Bug</b>

Create a new C# console program and add this code:

```csharp
using System;

namespace test
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }

        public int TempProp { get; set; }
        public int TempMethod();
    }

    interface ITestInterface
    {
        public int TempProp { get; set; }
        public abstract int TempMethod();
    }
}
```

![image](https://user-images.githubusercontent.com/29720335/104903749-4888dd80-5935-11eb-8deb-20067403ebdd.png)

Extension version: 1.23.8
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

**Comment by azydevelopment** [comment]
Another weird example. The keyword 'struct' is half highlighted.

![image](https://user-images.githubusercontent.com/29720335/104907201-8e47a500-5939-11eb-9ee5-a4a3e37d1083.png)

**Comment by filipw** [comment]
This is supported with semantic highlighting. 
To enable it set:

`csharp.semanticHighlighting.enabled` and `editor.semanticHighlighting.enabled` to `true`.

**Comment by JoeRobich** [comment]
The C# extension now supports semantic highlighting as well as it ships with a much improved textmate grammar.
