### ISSUE TITLE
OmniSharp stop several times a day

### ISSUE THREAD

**Issue by reginaldonoronha** [dotnet/vscode-csharp#4359]
It has occurred several times in the day that my omnisharp stops and I have to restart the extension.

VSCODE 
1.52.1
x64

OmniSharp 
v1.23.8

macOS 11.1 (20C69)

**Comment by momt99** [comment]
Is it like #4270?

**Comment by JoeRobich** [comment]
A lot has changed with O# since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
