### ISSUE TITLE
Omnisharp does not install - The system cannot find the path specified

### ISSUE THREAD

**Issue by davide-rota** [dotnet/vscode-csharp#4364]
Issue Type: <b>Bug</b>

On Surface Pro X (ARM64)
Install dotnet core SDK 5.0.102
Clean Install VSCode 

> Version: 1.52.1 (user setup)
> Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
> Date: 2020-12-16T15:57:21.921Z
> Electron: 9.3.5
> Chrome: 83.0.4103.122
> Node.js: 12.14.1
> V8: 8.3.110.13-electron.0
> OS: Windows_NT arm64 10.0.19042

Install C# Extension1.23.8
-> Omnisharp is not installed, .omnisharp folder does not exist

![image](https://user-images.githubusercontent.com/11763/106025400-0005b880-60c9-11eb-8227-1b18a85af9b7.png)

Install Old C# Extension 1.21.15
-> Omnisharp is installed in an older version, has problems with dotnet SDK

Extension version: 1.23.8
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T15:57:21.921Z)
OS version: Windows_NT arm64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Microsoft SQ1 @ 3.0 GHz (8 x 1670)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.54GB (1.08GB free)|
|Process Argv|--crash-reporter-id e30b7397-1d88-436c-ae4e-932bddf1f567|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2prompt:30224612
vstry244:30250195
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773:30248341
vstes627:30244334
pythonvspyt600cf:30247032

```

</details>

**Comment by JoeRobich** [comment]
A lot has changed with O# project loading since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
