### ISSUE TITLE
new project command

### ISSUE THREAD

**Issue by KaungZawHtet** [dotnet/vscode-csharp#4368]
I wish c# has new project commands like flutter : 

<img width="592" alt="Screen Shot 2021-01-30 at 15 52 44" src="https://user-images.githubusercontent.com/15225530/106352672-5bc38200-6313-11eb-8bf8-c3a4ac3afbab.png">

**Comment by JoeRobich** [comment]
There are no plans to support commands to generate projects from templates in the C# extension. For C# the recommendation is to use the dotnet CLI from the terminal. The C# DevKit does include the ability to create projects from templates.
