### ISSUE TITLE
[Feature Request] Exclude namespaces in intellisense popups

### ISSUE THREAD

**Issue by lonix1** [dotnet/vscode-csharp#4372]
If I'm editing a c# file, and I hover over a class/method/whatever then I get an intellisense ("suggestion") popup with the xml doc comments.

For example, `EndpointRoutingApplicationBuilderExtensions.UseEndpoints()`:
> The Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware defines a point in the middleware pipeline where routing decisions are made, and an Microsoft.AspNetCore.Http.Endpoint is associated with the Microsoft.AspNetCore.Http.HttpContext. The Microsoft.AspNetCore.Routing.EndpointMiddleware defines a point in the middleware pipeline where the current Microsoft.AspNetCore.Http.Endpoint is executed. Middleware between the Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware and Microsoft.AspNetCore.Routing.EndpointMiddleware may observe or change the Microsoft.AspNetCore.Http.Endpoint associated with the Microsoft.AspNetCore.Http.HttpContext.

It's very hard to read and understand all that noise, and in a little popup.

This is easier:
> The EndpointRoutingMiddleware defines a point in the middleware pipeline where routing decisions are made, and an Endpoint is associated with the HttpContext. The EndpointMiddleware defines a point in the middleware pipeline where the current Endpoint is executed. Middleware between the EndpointRoutingMiddleware and EndpointMiddleware may observe or change the Endpoint associated with the HttpContext.

Please add a setting where the full namespaces are ignored when showing intellisense?

---

I originally posted that on the [vscode repo](https://github.com/microsoft/vscode/issues/115534), but apparently that's the wrong place.

The response was:
> Hovers are just textual and we have no structured understanding of what's in it

However can it be done in this extension?

**Comment by JoeRobich** [comment]
A lot has changed with O# quick info since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
