### ISSUE TITLE
Intellisense, go to definition doesn't work

### ISSUE THREAD

**Issue by nidhi1612** [dotnet/vscode-csharp#4374]
## Environment data
`dotnet --info` output:
NET Core SDK (reflecting any global.json):
 Version:   3.1.201     
 Commit:    b1768b4ae7  

Runtime Environment:    
 OS Name:     Windows   
 OS Version:  10.0.19042
 OS Platform: Windows   
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

VS Code version: 1.52.1 (user setup)
C# Extension version: 1.23.8

## Steps to reproduce
I am working on Nopcommerce 4.3 version in VS code. The Intellisense was working fine till last week, And its not working anymore. on ctrl+space I get loading message but nothing happens.
Also go to definition is not working. This was inconsistent since the beginning. 
Below are the screenshots for the same.
I have removed all the extensions and reinstalled them.
Reinstalled vscode as well.
But still facing the issue.
![Untitled](https://user-images.githubusercontent.com/25578717/106561286-674ebd00-654e-11eb-92f9-0c7701981984.png)
![Untitled1](https://user-images.githubusercontent.com/25578717/106561288-687fea00-654e-11eb-80da-3d7e3f2707d9.png)

I am kind of stuck here. Please help me find whatever I have missed.

**Comment by saidsoualhi** [comment]
Did you resolved the issue?

**Comment by JoeRobich** [comment]
A lot has changed with O# project loading since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
