### ISSUE TITLE
[Bug] Parsing failure when tasks.json contains comments

### ISSUE THREAD

**Issue by lonix1** [dotnet/vscode-csharp#4377]
## Environment data
latest of everything
linux
sdk: 5.0.102
vscode: 1.52.1
c# extension: 1.23.8

## Problem
When opening a project, I get a popup error:
> Failed to parse tasks.json file

## Sample
This is `.vscode/tasks.json` which is a `jsonc` file:
````jsonc
// this comment is allowed
{
  // this comment is allowed
  "version": "2.0.0",
  "tasks": [
    {
      // this comment is allowed
      "label": "run",
      "type": "process",
      "command": "dotnet",             // this comment is allowed
      "args": [
        "run",
        "--project",
        "${workspaceFolder}/src/Foo/Foo.csproj",
        //"--launch-profile", "Production",           // <<<<<<<<<< THIS IS THE PROBLEM
      ],
    },
  ],
  // this comment is allowed
}

````

The comment inside the `args` array is the problem. When removed, there is no error.

**Comment by lonix1** [comment]
Working as of current version.

**Comment by lonix1** [comment]
Nope it's still a problem. The underlying parse doesn't like `jsonc`.

**Comment by JoeRobich** [comment]
@lonix1 Sorry we didn't respond to this issue earlier. I believe it is VS Code sending your this error popup. I think you will want to report this issue at https://github.com/microsoft/vscode/issues

**Comment by lonix1** [comment]
Thanks I've [done that](https://github.com/microsoft/vscode/issues/148679).

**Comment by lonix1** [comment]
Apparently they don't think it's a vscode issue.

One more thing, the error shows this:
> Failed to parse tasks.json file
Source: C# (Extension)                          <----------

Any thoughts?

**Comment by spencer741** [comment]
+1 I am still seeing this issue on latest omnisharp.

Proof that it is the omnisharp extension: If you restart the omnisharp server, the error message pops up again.

**Comment by jasonmalinowski** [comment]
@lonix1 Fine in this case, since it does look to be the same issue.
