### ISSUE TITLE
A variable's type isn't highlighted if its name is on a different line.

### ISSUE THREAD

**Issue by catonif** [dotnet/vscode-csharp#4387]
A variable's type isn't highlighted if its name is on a different line.
**Screenshot**:
![omnisharp-type-highlighting](https://user-images.githubusercontent.com/64315564/107157000-e7778700-6981-11eb-8461-5f6e812e84c2.png)

## Environment data
VS Code version: 1.53.0
C# Extension version: 10.143.912

## Steps to reproduce
Define a variable with it's name on a different line as its type.

## Expected  behavior
The type should be highlighted.

## Actual behavior
The type isn't highlighted.

**Comment by JoeRobich** [comment]
The C# extension now ships with semantic highlighting as well as an updated textmate grammar.
