### ISSUE TITLE
Track project updates for csproj files with globbing patterns

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/vscode-csharp#439]
When globbing patterns are used in a csproj file, the project can change when a file is added or removed that matches the pattern, but the project file itself won't be updated. This situation needs to be detected.

**Comment by jsheely** [comment]
- VSCode Version: 1.14.2
- OS Version: Windows 10 Pro 64-bit

Steps to Reproduce:
1. Open VSCode
2. Use Terminal to dotnet new webapi
3. dotnet add package serilog.sinks.elasticsearch
4. Yes to restore packages
5. Try to configure ```new LoggerConfiguration().writeTo.Elasticsearch``` (Elasticsearch is not available)
6. Close VSCode & Reopen
7. Elasticsearch will now be available to intellisense

Attached is a video of the process.
https://dl.dropboxusercontent.com/u/10620012/2017-07-23_18-42-06.mp4

Is there a way to force refresh of intellisense as a band-aid?

**Comment by DustinCampbell** [comment]
Could you file a new issue for this rather than replying to a work item on our future backlog? What you described should already be working and isn't related to this backlog item. Thanks!

**Comment by JoeRobich** [comment]
Implemented in https://github.com/OmniSharp/omnisharp-roslyn/pull/1841
