### ISSUE TITLE
project.json

### ISSUE THREAD

**Issue by ravihugo** [dotnet/vscode-csharp#4391]
I have an unrelated project that doesn't use C# but has project.json (it's actually a mongo collection of canned test data). The extension reports it as an error. Not sure what to do but it's definitely caused by this plugin when installed. It may be helpful to add additional heuristics before assuming this file is related to c#. No biggie otherwise just reporting what I'm seeing.

**Comment by filipw** [comment]
project.json support was removed long time ago, which version of the extension are you using?

**Comment by ravihugo** [comment]
Looks like v1.23.9

**Comment by filipw** [comment]
can you show what are you are seeing?

**Comment by JoeRobich** [comment]
The extension no longer activates on project.json files.
