### ISSUE TITLE
Action "Generate method" adds using System

### ISSUE THREAD

**Issue by ssoher** [dotnet/vscode-csharp#4393]
Let's say I have the following code while there is no method `OnEvent` is present.
`Class.Event += OnEvent`
Upon invoking the action "Generate method Class.OnEvent" I'm given

```csharp
using System;
.
.
.
private void OnEvent() {
    throw new NotImplementedException();
}
```
What I expect is
```csharp
private void OnEvent() {
    throw new System.NotImplementedException();
}
```

This action should not add `using System`

**Comment by JoeRobich** [comment]
This would be a feature request for Roslyn. If this is still a problems, please open a new issue at https://github.com/dotnet/roslyn/issues
