### ISSUE TITLE
Weird behaviour all the time...

### ISSUE THREAD

**Issue by AndiRudi** [dotnet/vscode-csharp#4404]
## Issue Description ##

Since a couple of weeks/month I have quite some issues working with vscode on our .net core / .net projects. We have multiple smaller microservices and one larger monolith. It actually does not make much difference which project I open, Omnisharp behaves weird and usually I need to work blindly. Here are some of my findings:

- The first one is, that it takes a minute or so to load intellisense. e.g. after pressing the dot (like in System.) when usually the popup should come in a second or so
- When I switch to another class and change something the change is often not recognized in other files. I need to restart Omnisharp but then it also takes minutes until it scanned all files
- When I add something it usually is not known to intellisense for quite a while or until Omnisharp is restarted
- Sometimes weird things happen see screenshot where I just changed some code and the code is correct and the errors reported are not correct and also it looks like the memory slipped :)
<img width="1123" alt="Screenshot 2021-02-18 at 16 31 39" src="https://user-images.githubusercontent.com/6254862/108381018-b449b900-7207-11eb-8cc1-04347430c467.png">

I want to add that I have those issues on different machines (iMac and MacBookPro). Also colleagues report similar issues. I'm happy to assist finding the issues (if not already known)

## Steps to Reproduce ##

I do not have explicit steps. It just happens all over the place while coding

## Expected Behavior ##

Intellisense to be stable and fast

## Actual Behavior ##

Intellisense not stable and slow

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.53.2
**C# Extension**: 1.23.9

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.103
 Commit:    72dec52dbd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.103/

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  3.1.404 [/usr/local/share/dotnet/sdk]
  3.1.405 [/usr/local/share/dotnet/sdk]
  3.1.406 [/usr/local/share/dotnet/sdk]
  5.0.100 [/usr/local/share/dotnet/sdk]
  5.0.101 [/usr/local/share/dotnet/sdk]
  5.0.102 [/usr/local/share/dotnet/sdk]
  5.0.103 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|add-reference|adrianwilczynski|1.0.2|
|auto-using|Fudge|0.7.15|
|cpptools|ms-vscode|1.2.1|
|csharp|ms-dotnettools|1.23.9|
|dotnet-test-explorer|formulahendry|0.7.5|
|gitlens|eamodio|11.2.1|
|HTMLHint|mkaufman|0.10.0|
|java|redhat|0.75.0|
|jupyter|ms-toolsai|2021.2.576440691|
|lit-html|bierner|1.11.1|
|material-icon-theme|PKief|4.5.0|
|msbuild-project-tools|tintoy|0.3.14|
|night-owl|sdras|2.0.0|
|nuget-reverse-package-search|jesschadwick|0.1.68|
|theme-bluloco-light|uloco|3.3.4|
|tizentv|tizensdk|1.2.2|
|vscode-docker|ms-azuretools|1.10.0|
|vscode-drawio|hediet|1.3.0|
|vscode-java-pack|vscjava|0.12.1|
|vscode-java-test|vscjava|0.28.0|
|vscode-markdownlint|DavidAnson|0.39.0|
|vscode-nuget-gallery|patcx|0.0.24|
|vscode-nuget-package-manager-improved|maxbrister|2.1.0|
|vscode-xml|redhat|0.15.0|
|vscode-yaml|redhat|0.15.0|;

</details>

**Comment by rupe120** [comment]
I just opened a project that was mostly working yesterday, minus one possibly related issue. Today I open it to find all sorts of misidentified issues
![image](https://user-images.githubusercontent.com/860348/110661225-579c4700-8192-11eb-8b4b-4612ecb1a594.png)

This is on a VM that I just created yesterday.

**Comment by DiegoGFritz** [comment]
I have the same issue. This occurs many, many times while I'm coding
VSCode version: 1.54.2
C# extension: 1.23.9
OS version: Windows 10 20H2

![imagen](https://user-images.githubusercontent.com/26330822/111172168-5b5e0e00-8584-11eb-87fb-adb5d3136a09.png)

**Comment by SirIntruder** [comment]
I've seen this recently on a Unity project/windows, and I have a hunch it was related to pulling git changes on a file that was not currently active.

**Comment by JoeRobich** [comment]
There have been lots of improvements since this issue was opened. Please open a new issue with logs if you are still running into this.
