### ISSUE TITLE
There is an error "OmniSharp.MSBuild.ProjectLoader Could not read state file "obj/Debug/net6.0/BlazorClient.Shared.csprojAssemblyReference.cache"." on the Output when open project with VSCode. 

### ISSUE THREAD

**Issue by EmilyFeng97** [dotnet/vscode-csharp#4416]
**Azure DevOps work item:**
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1285991

**Testcases Affected**
[[6.0] VerifyAngularwithNoAuth](https://github.com/aspnet/Tooling-ManualTests/blob/rel/16.6/E2EWalkthroughs/VSforLinux/AspNetCore3x/3x_VerifyAngularwithNoauth.md)
[[6.0] VerifyReactwithNoAuth](https://github.com/aspnet/Tooling-ManualTests/blob/rel/16.6/E2EWalkthroughs/VSforLinux/AspNetCore3x/3x_VerifyReactwithNoauth.md)
[[6.0] VerifyReactRedux](https://github.com/aspnet/Tooling-ManualTests/blob/rel/16.6/E2EWalkthroughs/VSforLinux/AspNetCore3x/3x_VerifyReactReduxTemplate.md)
[[6.0] VerifyBlazorClient](https://github.com/aspnet/Tooling-ManualTests/blob/rel/16.8stg/E2EWalkthroughs/VSforLinux/AspNetCore3x/3x_VerifyBlazorClient.md)

**Platform**
- [x] Windows
- [x] macOS
- [x] Linux

**Repro Steps**
1. Open up a normal Terminal Emulator
2. Create a BlazorClient project and name it "BlazorClient":
`dotnet new blazorwasm -ho -o BlazorClient`
3.  Navigate to the folder you created Angular and open VS Code using Terminal Emulator
 ```
 cd ~
 cd ./BlazorClient/Server/
 code .
 ```
**Actual Result**

Image
![image](https://user-images.githubusercontent.com/66412474/109488465-9100f280-7ac0-11eb-8554-52f2467bb757.png)
![image](https://user-images.githubusercontent.com/66412474/109488491-98280080-7ac0-11eb-9355-06a391f4aa01.png)

**Error Log**

[warn]: OmniSharp.MSBuild.ProjectLoader
        Could not read state file "obj/Debug/net6.0/BlazorClient.Shared.csprojAssemblyReference.cache". The input stream is not a valid binary format. The starting contents (in bytes) are: 4D-42-52-53-43-01-01-99-00-00-00-01-69-2F-68-6F-6D ...
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/aapt/BlazorClient/Shared/BlazorClient.Shared.csproj'.
/home/aapt/BlazorClient/Shared/BlazorClient.Shared.csproj
/home/aapt/.vscode/extensions/ms-dotnettools.csharp-1.23.10/.omnisharp/1.37.6/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(2123,5): Error: Could not read state file "obj/Debug/net6.0/BlazorClient.Shared.csprojAssemblyReference.cache". The input stream is not a valid binary format. The starting contents (in bytes) are: 4D-42-52-53-43-01-01-99-00-00-00-01-69-2F-68-6F-6D ...

[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/aapt/BlazorClient/Shared/BlazorClient.Shared.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: BlazorClient.Server
Can't find custom attr constructor image: /home/aapt/BlazorClient/Client/bin/Debug/net6.0/BlazorClient.Client.dll mtoken: 0x0a000001 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.

**Comment by EmilyFeng97** [comment]
Sometimes I also encounter the following error:
![image](https://user-images.githubusercontent.com/66412474/109612731-21940d00-7b6b-11eb-8620-0bceaa46f534.png)
**Error Log**
[warn]: OmniSharp.MSBuild.ProjectLoader
        Could not read state file "obj/Debug/net6.0/BlazoADDb2cstand.csprojAssemblyReference.cache". Binary stream '109' does not contain a valid BinaryHeader. Possible causes are invalid stream or object version change between serialization and deserialization.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/aapt/BlazoADDb2cstand/BlazoADDb2cstand.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/aapt/BlazoADDb2cstand/BlazoADDb2cstand.csproj'.
/home/aapt/BlazoADDb2cstand/BlazoADDb2cstand.csproj
/home/aapt/.vscode/extensions/ms-dotnettools.csharp-1.23.10/.omnisharp/1.37.6/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(2123,5): Error: Could not read state file "obj/Debug/net6.0/BlazoADDb2cstand.csprojAssemblyReference.cache". Binary stream '109' does not contain a valid BinaryHeader. Possible causes are invalid stream or object version change between serialization and deserialization.

**Comment by mwaqasaziz** [comment]
Mine error is also related

VSCODE version 1.54.3
DOTNET SDK - 6.0.100-preview.2.21155.3

Successfully loaded project file '/PData.A/VsCodeProjects/HisBizBackendSolution/HisBiz.Shared/SharedLibrary/SharedLibrary.csproj'.
/PData.A/VsCodeProjects/HisBizBackendSolution/HisBiz.Shared/SharedLibrary/SharedLibrary.csproj
/home/waqas/.vscode/extensions/ms-dotnettools.csharp-**1.23.9**/.omnisharp/**1.37.6**/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(2123,5): Error: Could not read state file "obj/Debug/net6.0/SharedLibrary.csprojAssemblyReference.cache". The input stream is not a valid binary format. The starting contents (in bytes) are: 4D-42-52-53-43-01-01-99-00-00-00-01-69-2F-75-73-72 ...

I only encountered this error when i installed dotnet 6.0.100-preview.2.21155.3 it was working fine with dotnet 6.0 preview 1

**Comment by Yuyue960724** [comment]
This issue not repro on MAC with latest .NET 6.0 Preview 3 build.

**Comment by semsuddin** [comment]
> This issue not repro on MAC/Linux with latest .NET 6.0 Preview 3 build.

Where did you get the Preview 3 version? I am facing the same issue with .NET 6 Preview 2.

**Comment by Yuyue960724** [comment]
> Preview 2.
.NET 6.0 Preview 3 is an internal version, Maybe you don’t have permission to get it.

**Comment by JoeRobich** [comment]
A lot has changed with O# project loading since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
