### ISSUE TITLE
memory rise to >6G  when open dotnet runtime

### ISSUE THREAD

**Issue by athinboy** [dotnet/vscode-csharp#4430]
https://github.com/dotnet/runtime

![image](https://user-images.githubusercontent.com/10301079/110296245-13dbfd00-802d-11eb-87da-af82c0e0d253.png)

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.54.1
**C# Extension**: 1.23.9

<details><summary>Dotnet Information</summary>
.NET SDK (��ӳ�κ� global.json):
 Version:   5.0.103
 Commit:    72dec52dbd

����ʱ����:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.103\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.813 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.1.200 [C:\Program Files\dotnet\sdk]
  3.1.406 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|aessoft-class-autocomplete|AESSoft|0.1.0|
|binary-preview|asurance|0.0.2|
|code-gnu-global|austin|0.2.2|
|code-runner|formulahendry|0.11.2|
|code-settings-sync|Shan|3.4.3|
|cpptools|ms-vscode|1.2.2|
|csharp|ms-dotnettools|1.23.9|
|csharpextensions|jchannon|1.3.1|
|docomment|k--kato|0.1.20|
|dotnet|leo-labs|1.3.0|
|dotnet-core-essentials|KishoreIthadi|0.0.8|
|dotnet-test-explorer|formulahendry|0.7.5|
|dotnetexplorer|mfery|1.0.0|
|es6-string-html|Tobermory|2.2.0|
|fabric8-analytics|redhat|0.3.2|
|git-extension-pack|donjayamanne|0.1.3|
|git-graph|mhutchie|1.29.0|
|githistory|donjayamanne|0.6.14|
|gitignore|codezombiech|0.6.0|
|gitlens|eamodio|11.3.0|
|html-snippets|abusaidm|0.2.1|
|html5-boilerplate|sidthesloth|1.1.1|
|ilspy-vscode|icsharpcode|0.9.0|
|java|redhat|0.76.0|
|jshint|dbaeumer|0.11.0|
|lit-html|bierner|1.11.1|
|markdown-all-in-one|yzhang|3.4.0|
|markdown-preview-enhanced|shd101wyy|0.5.16|
|msbuild-project-tools|tintoy|0.3.15|
|open-html-in-browser|peakchen90|2.1.3|
|project-manager|alefragnani|12.0.1|
|quicktype|quicktype|12.0.46|
|resxpress|PrateekMahendrakar|4.2.0|
|rtf|alefragnani|2.2.0|
|sonarlint-vscode|SonarSource|1.20.1|
|todo-tree|Gruntfuggly|0.0.201|
|vetur|octref|0.33.1|
|vsc-export|aslamanver|1.2.0|
|vscode-commons|redhat|0.0.4|
|vscode-csharp-snippets|jorgeserrano|1.1.0|
|vscode-dotnet-adapter|derivitec-ltd|1.4.3|
|vscode-drawio|hediet|1.3.0|
|vscode-eslint|dbaeumer|2.1.14|
|vscode-java-debug|vscjava|0.31.0|
|vscode-java-dependency|vscjava|0.18.1|
|vscode-java-pack|vscjava|0.13.0|
|vscode-java-test|vscjava|0.28.1|
|vscode-markdownlint|DavidAnson|0.39.0|
|vscode-maven|vscjava|0.27.1|
|vscode-npm-script|eg2|0.3.16|
|vscode-nuget-package-manager|jmrog|1.1.6|
|vscode-nxunit-test-adapter|wghats|0.1.3|
|vscode-open-in-github|ziyasal|1.3.6|
|vscode-sftp|suntobright|1.1.1|
|vscode-test-explorer|hbenl|2.19.5|
|vscode-typescript-tslint-plugin|ms-vscode|1.3.3|
|vscode-vstest-framework|gfrancischini|0.0.3|
|vscode-xml|redhat|0.15.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.11|
|vue-helper|shenjiaolong|2.4.7|
|vue-snippets|hollowtree|1.0.4|
|xml|DotJoshJohnson|2.5.1|
|yuml|JaimeOlivares|3.5.1|;

</details>

**Comment by JoeRobich** [comment]
A lot has changed with O# since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
