### ISSUE TITLE
C# format not working

### ISSUE THREAD

**Issue by pmahend1** [dotnet/vscode-csharp#4436]
### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.54.1
**C# Extension**: 1.23.9

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.201/

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  3.1.405 [/usr/local/share/dotnet/sdk]
  3.1.406 [/usr/local/share/dotnet/sdk]
  3.1.407 [/usr/local/share/dotnet/sdk]
  5.0.102 [/usr/local/share/dotnet/sdk]
  5.0.103 [/usr/local/share/dotnet/sdk]
  5.0.201 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.2|
|compareit|in4margaret|0.0.2|
|cpptools|ms-vscode|1.2.2|
|csharp|ms-dotnettools|1.23.9|
|docs-markdown|docsmsft|0.2.85|
|gitlens|eamodio|11.3.0|
|html-preview-vscode|tht13|0.2.5|
|html-snippets|abusaidm|0.2.1|
|powershell|ms-vscode|2021.2.2|
|prettier-vscode|esbenp|5.9.2|
|prettyxml|PrateekMahendrakar|0.7.1|
|resxpress|PrateekMahendrakar|4.2.0|
|svg|jock|1.4.5|
|vs-keybindings|ms-vscode|0.2.0|
|vscode-eslint|dbaeumer|2.1.17|
|vscode-firefox-debug|firefox-devtools|2.9.2|
|vscode-github|KnisterPeter|0.30.4|
|vscode-html-css|ecmel|1.10.2|
|vscode-pull-request-github|GitHub|0.24.0|;

</details>

## Environment data
`dotnet --info` output:
VS Code version:1.54.1
C# Extension version:
1.23.9
## OmniSharp log

[info]: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionService
        Could not find document for file /Users/abc/Desktop/dffd.cs
[info]: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionService
        Could not find document for file /Users/abc/Desktop/dffd.cs
[info]: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionService
        Could not find document for file /Users/abc/Desktop/dffd.cs
[info]: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionService
        Could not find document for file /Users/abc/Desktop/dffd.cs

## Steps to reproduce
- add C# code without saving, or with save but no project association.
- check the language at the bottom
- Try to format

## Expected  behavior
Should format C# file

## Actual behavior

Doesnt format the document

**Comment by brnhensley** [comment]
I'm having the same issue with formatting, my OmniSharp server keeps timing out.

### OmniSharp log ###
<details>Starting OmniSharp server at 3/15/2021, 2:17:42 PM
    Target: c:\Users\Brian\Desktop\Code\testing\fidgetech-to-do-list

OmniSharp server started.
    Path: c:\Users\Brian\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.omnisharp\1.37.6\OmniSharp.exe
    PID: 21588

[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).

</details>

**Comment by JoeRobich** [comment]
The C# extension does not support language services on loose C# files opened outside the context of a project file.
