### ISSUE TITLE
Format Document not working

### ISSUE THREAD

**Issue by ferenczy** [dotnet/vscode-csharp#4453]
## Issue Description ##

The "_Format Document_" command does nothing on a C# code.

## Prerequisities ##

The C# extension (`ms-dotnettools.csharp`) is installed.

## Steps to Reproduce ##

1. Open VS Code
2. Open a new editor
3. Execute the "_Change Language Mode_" command and set it to C# (<kbd>Ctrl</kbd>+<kbd>K</kbd> <kbd>M</kbd> or from the Command palette)
4. Paste some badly formatted C# code, e.g. an unindented code:
    ```
    public class Test
    {
    public Test()
    {
    }
    }
    ```
5. Execute the "_Format Document_" command (<kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>F</kbd> or from the Command palette)

## Expected Behavior ##

The source code is formatted.

You can see the expected behavior if you repeat the Steps to Reproduce, but with some JSON code and with the document language set to JSON, for example.

Code to test: `{{"a": 1}}`
Result after the "_Format Document_" is executed:
```
{
    {
        "a": 1
    }
}
```

## Actual Behavior ##

A notification "_There is no formatter for 'csharp' files installed._" is shown. When the button "_Install Formatter_" is pressed, the Extensions panel with a prefilled filter `category:formatters csharp` is opened. The extensions `ms-dotnettools.csharp` is not listed there and it's already installed anyway.

### OmniSharp log ###

(Empty)

### C# log ###

(Empty)

## Environment information ##

**VSCode version**: 1.54.3
**C# Extension**: 1.23.9

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  2.1.811 [C:\Program Files\dotnet\sdk]
  3.1.401 [C:\Program Files\dotnet\sdk]
  3.1.404 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|13.0.4|
|bracket-pair-colorizer-2|CoenraadS|0.2.0|
|change-case|wmaurer|1.0.0|
|code-spell-checker|streetsidesoftware|1.10.2|
|code-spell-checker-czech|streetsidesoftware|0.1.6|
|code-stats-vscode|riussi|1.0.18|
|color-highlight|naumovs|2.3.0|
|csharp|ms-dotnettools|1.23.9|
|docs-view|bierner|0.0.9|
|EditorConfig|EditorConfig|0.16.4|
|git-graph|mhutchie|1.29.0|
|githistory|donjayamanne|0.6.16|
|gitlens|eamodio|11.3.0|
|indent-rainbow|oderwat|7.5.0|
|linesinfostatusbar|peterfh|0.0.3|
|markdown-links|tchayen|0.8.0|
|markdown-memo|svsool|0.3.4|
|markdown-table-prettify|darkriszty|3.2.0|
|material-icon-theme|PKief|4.6.0|
|overtype|DrMerfy|0.4.0|
|project-manager|alefragnani|12.0.1|
|rainbow-csv|mechatroner|1.8.1|
|trailing-spaces|shardulm94|0.3.1|
|vscode-icons|vscode-icons-team|11.2.0|
|vscode-sql-formatter|adpyke|1.4.4|
|xml|DotJoshJohnson|2.5.1|;

</details>

**Comment by nohwnd** [comment]
Have you saved the file? Because for new files they don't get into the workspace, and so omnisharp does not think about them. Can you also confirm that the extension is active, because it only activates for csproj and sln files, but not for .cs files.

**Comment by ferenczy** [comment]
@nohwnd No, I didn't save the file, that was my point, that other formatters work fine on unsaved files. Sometimes I just need to quickly format some piece of C# source code, but creating a file or even a project or a solution would be too complicated.

**Comment by JoeRobich** [comment]
The C# extension does not provide language services for loose C# files opened outside the context of a project.
