### ISSUE TITLE
Yesterday Intellisense worked, today it does not

### ISSUE THREAD

**Issue by ielcoro** [dotnet/vscode-csharp#4463]
## Issue Description ##
This issue happens on various projects that i work on, sometimes restarting Omnisharp works, sometimes restarting the container makes Omnisharp work again, some other times it remains until some day it starts working again. 

This is one of the multiple issues with Omnisharp getting stuck, without any indication, and everything stop from working, go to reference, intellisense, refactorings, that makes every time i try to work with Visual Studio Code and .NET abandon it, despite much love I have to the Code IDE.

## Steps to Reproduce ##

Don't have a clue, just work on some mid sized project with tests, 2 ASP.NET Core projects, 2 .NET Core class libraries, and it will work for some time until it doesn't work, and anything that is provided by Omnisharp does not work.

## Expected Behavior ##

Just have intellisense, symbols, rename classes working.

## Actual Behavior ##

Every operation that uses Omnisharp does not work, without any crashes, just stops working.

I hope engineers can extract information from the attached logs and info, Omnisharp needs some effort on stabilizing it, actually is such a wasted potential.

### OmniSharp log ###
<details>Starting OmniSharp server at 3/29/2021, 4:24:07 PM
    Target: /repos/codeName/My.Project.CodeName.sln

OmniSharp server started.
    Path: /root/.vscode-server/extensions/ms-dotnettools.csharp-1.23.9/.omnisharp/1.37.6/run
    PID: 11988

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on ubuntu 20.4 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.8.0 - "/root/.vscode-server/extensions/ms-dotnettools.csharp-1.23.9/.omnisharp/1.37.6/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/root/.vscode-server/extensions/ms-dotnettools.csharp-1.23.9/.omnisharp/1.37.6/omnisharp/.msbuild/Current/Bin/MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.8.0 - "/root/.vscode-server/extensions/ms-dotnettools.csharp-1.23.9/.omnisharp/1.37.6/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            MSBuildToolsPath = /root/.vscode-server/extensions/ms-dotnettools.csharp-1.23.9/.omnisharp/1.37.6/omnisharp/.msbuild/Current/Bin
            CscToolPath = /root/.vscode-server/extensions/ms-dotnettools.csharp-1.23.9/.omnisharp/1.37.6/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /root/.vscode-server/extensions/ms-dotnettools.csharp-1.23.9/.omnisharp/1.37.6/omnisharp/.msbuild
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/repos/codeName'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/repos/codeName/My.Project.CodeName.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/repos/codeName/src/Core/My.Project.CodeName.Core.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/repos/codeName/tests/BehaviorTests/My.Project.CodeName.BehaviorTests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/repos/codeName/src/Infrastructure/EntityFramework.SqlServer/My.Project.CodeName.EntityFramework.SqlServer.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/repos/codeName/tools/Migrations.SqlServer/My.Project.CodeName.Migrations.SqlServer.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/repos/codeName/src/FrameworkExtensions/My.Project.CodeName.FrameworkExtensions.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/repos/codeName/src/Api/My.Project.CodeName.Api.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/repos/codeName/src/Web/My.Project.CodeName.Web.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/repos/codeName/src/Infrastructure/Authentication.AzureAD/My.Project.CodeName.Authentication.AzureAD.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/repos/codeName/src/Infrastructure/MSGraphService/My.Project.CodeName.MSGraphService.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/repos/codeName/src/Infrastructure/LicensesProviderService/My.Project.CodeName.LicensesProviderService.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/repos/codeName/src/Infrastructure/Authorization/My.Project.CodeName.Authorization.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/repos/codeName/tools/Tenants.Migration/My.Project.CodeName.Tenants.Migration.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/repos/codeName/tools/Tenants.Search/My.Project.CodeName.Tenants.Search.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/repos/codeName/src/Infrastructure/TaskScheduler/My.Project.CodeName.TaskScheduler.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/repos/codeName/src/AzureFunctions/PutUsetSync/My.Project.CodeName.Function.PutUserSync.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/repos/codeName/src/AzureFunctions/GetUserSync/My.Project.CodeName.Function.GetUserSync.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/repos/codeName'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/repos/codeName' on host 187.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /repos/codeName/src/Core/My.Project.CodeName.Core.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/repos/codeName/src/Core/My.Project.CodeName.Core.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/repos/codeName/src/Core/My.Project.CodeName.Core.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /repos/codeName/tests/BehaviorTests/My.Project.CodeName.BehaviorTests.csproj
Can't find custom attr constructor image: /repos/codeName/src/Core/bin/Debug/netcoreapp3.1/My.Project.CodeName.Core.dll mtoken: 0x0a000006 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
Can't find custom attr constructor image: /repos/codeName/src/Infrastructure/EntityFramework.SqlServer/bin/Debug/netcoreapp3.1/My.Project.CodeName.EntityFramework.SqlServer.dll mtoken: 0x0a000006 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/repos/codeName/tests/BehaviorTests/My.Project.CodeName.BehaviorTests.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/repos/codeName/tests/BehaviorTests/My.Project.CodeName.BehaviorTests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /repos/codeName/src/Infrastructure/EntityFramework.SqlServer/My.Project.CodeName.EntityFramework.SqlServer.csproj
Can't find custom attr constructor image: /repos/codeName/src/Core/bin/Debug/netcoreapp3.1/My.Project.CodeName.Core.dll mtoken: 0x0a000006 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/repos/codeName/src/Infrastructure/EntityFramework.SqlServer/My.Project.CodeName.EntityFramework.SqlServer.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/repos/codeName/src/Infrastructure/EntityFramework.SqlServer/My.Project.CodeName.EntityFramework.SqlServer.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /repos/codeName/tools/Migrations.SqlServer/My.Project.CodeName.Migrations.SqlServer.csproj
Can't find custom attr constructor image: /repos/codeName/src/Core/bin/Debug/netcoreapp3.1/My.Project.CodeName.Core.dll mtoken: 0x0a000006 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
Can't find custom attr constructor image: /repos/codeName/src/Infrastructure/EntityFramework.SqlServer/bin/Debug/netcoreapp3.1/My.Project.CodeName.EntityFramework.SqlServer.dll mtoken: 0x0a000006 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/repos/codeName/tools/Migrations.SqlServer/My.Project.CodeName.Migrations.SqlServer.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/repos/codeName/tools/Migrations.SqlServer/My.Project.CodeName.Migrations.SqlServer.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /repos/codeName/src/FrameworkExtensions/My.Project.CodeName.FrameworkExtensions.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/repos/codeName/src/FrameworkExtensions/My.Project.CodeName.FrameworkExtensions.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/repos/codeName/src/FrameworkExtensions/My.Project.CodeName.FrameworkExtensions.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /repos/codeName/src/Api/My.Project.CodeName.Api.csproj
Can't find custom attr constructor image: /repos/codeName/src/Core/bin/Debug/netcoreapp3.1/My.Project.CodeName.Core.dll mtoken: 0x0a000006 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
Can't find custom attr constructor image: /repos/codeName/src/Infrastructure/EntityFramework.SqlServer/bin/Debug/netcoreapp3.1/My.Project.CodeName.EntityFramework.SqlServer.dll mtoken: 0x0a000006 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/repos/codeName/src/Api/My.Project.CodeName.Api.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/repos/codeName/src/Api/My.Project.CodeName.Api.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /repos/codeName/src/Web/My.Project.CodeName.Web.csproj
[warn]: OmniSharp.MSBuild.ProjectLoader
        The SDK resolver "Microsoft.DotNet.MSBuildSdkResolver" failed to run. Method not found: 'Microsoft.Build.Framework.SdkResult Microsoft.Build.Framework.SdkResultFactory.IndicateSuccess(System.String, System.String, System.Collections.Generic.IDictionary`2<System.String,System.String>, System.Collections.Generic.IDictionary`2<System.String,Microsoft.Build.Framework.SdkResultItem>, System.Collections.Generic.IEnumerable`1<System.String>)'.
[warn]: OmniSharp.MSBuild.ProjectLoader
        The SDK resolver "Microsoft.DotNet.MSBuildSdkResolver" failed to run. Method not found: 'Microsoft.Build.Framework.SdkResult Microsoft.Build.Framework.SdkResultFactory.IndicateSuccess(System.String, System.String, System.Collections.Generic.IDictionary`2<System.String,System.String>, System.Collections.Generic.IDictionary`2<System.String,Microsoft.Build.Framework.SdkResultItem>, System.Collections.Generic.IEnumerable`1<System.String>)'.
[warn]: OmniSharp.MSBuild.ProjectLoader
        The SDK resolver "Microsoft.DotNet.MSBuildSdkResolver" failed to run. Method not found: 'Microsoft.Build.Framework.SdkResult Microsoft.Build.Framework.SdkResultFactory.IndicateSuccess(System.String, System.String, System.Collections.Generic.IDictionary`2<System.String,System.String>, System.Collections.Generic.IDictionary`2<System.String,Microsoft.Build.Framework.SdkResultItem>, System.Collections.Generic.IEnumerable`1<System.String>)'.
[warn]: OmniSharp.MSBuild.ProjectLoader
        The SDK resolver "Microsoft.DotNet.MSBuildSdkResolver" failed to run. Method not found: 'Microsoft.Build.Framework.SdkResult Microsoft.Build.Framework.SdkResultFactory.IndicateSuccess(System.String, System.String, System.Collections.Generic.IDictionary`2<System.String,System.String>, System.Collections.Generic.IDictionary`2<System.String,Microsoft.Build.Framework.SdkResultItem>, System.Collections.Generic.IEnumerable`1<System.String>)'.
[warn]: OmniSharp.MSBuild.ProjectLoader
        The SDK resolver "Microsoft.DotNet.MSBuildSdkResolver" failed to run. Method not found: 'Microsoft.Build.Framework.SdkResult Microsoft.Build.Framework.SdkResultFactory.IndicateSuccess(System.String, System.String, System.Collections.Generic.IDictionary`2<System.String,System.String>, System.Collections.Generic.IDictionary`2<System.String,Microsoft.Build.Framework.SdkResultItem>, System.Collections.Generic.IEnumerable`1<System.String>)'.
[warn]: OmniSharp.MSBuild.ProjectLoader
        The SDK resolver "Microsoft.DotNet.MSBuildSdkResolver" failed to run. Method not found: 'Microsoft.Build.Framework.SdkResult Microsoft.Build.Framework.SdkResultFactory.IndicateSuccess(System.String, System.String, System.Collections.Generic.IDictionary`2<System.String,System.String>, System.Collections.Generic.IDictionary`2<System.String,Microsoft.Build.Framework.SdkResultItem>, System.Collections.Generic.IEnumerable`1<System.String>)'.</details>

### C# log ###
<details></details>

## Environment information ##

**VSCode version**: 1.54.3
**C# Extension**: 1.23.9

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.405
 Commit:    65f9d75b1c

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.405/

Host (useful for support):
  Version: 3.1.11
  Commit:  f5eceb8105

.NET Core SDKs installed:
  3.1.405 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.11 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.23.9|
|gitlens|eamodio|11.3.0|
|prettier-vscode|esbenp|6.3.1|
|vetur|octref|0.33.1|;

</details>

**Comment by JoeRobich** [comment]
Closing due to lack of response.
