### ISSUE TITLE
Could not find document

### ISSUE THREAD

**Issue by iCraft85** [dotnet/vscode-csharp#4488]
## Issue Description ##
I keep getting this error I am not sure why, and I am not sure what its supposed to be for, I assume to its help with auto completion
## Steps to Reproduce ##
I am not sure how would reproduce
## Expected Behavior ##
I don’t know what its for, but I think its for auto-completion 
## Actual Behavior ##
I don’t know what its supposed to do
### OmniSharp log ###
Starting OmniSharp server at 4/9/2021, 11:42:45 AM
    Target: /Users/user/Documents/UnityProjects/TerrainGeneration/Mesh + Terrain Generation.sln

OmniSharp server started.
    Path: /Users/user/.vscode/extensions/ms-dotnettools.csharp-1.23.9/.omnisharp/1.37.9-beta.2/run
    PID: 10886

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 11.2 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.9.0 - "/Users/user/.vscode/extensions/ms-dotnettools.csharp-1.23.9/.omnisharp/1.37.9-beta.2/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/Users/user/.vscode/extensions/ms-dotnettools.csharp-1.23.9/.omnisharp/1.37.9-beta.2/omnisharp/.msbuild/Current/Bin/MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.9.0 - "/Users/user/.vscode/extensions/ms-dotnettools.csharp-1.23.9/.omnisharp/1.37.9-beta.2/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            MSBuildToolsPath = /Users/user/.vscode/extensions/ms-dotnettools.csharp-1.23.9/.omnisharp/1.37.9-beta.2/omnisharp/.msbuild/Current/Bin
            CscToolPath = /Users/user/.vscode/extensions/ms-dotnettools.csharp-1.23.9/.omnisharp/1.37.9-beta.2/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /Users/user/.vscode/extensions/ms-dotnettools.csharp-1.23.9/.omnisharp/1.37.9-beta.2/omnisharp/.msbuild
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/user/Documents/UnityProjects/TerrainGeneration'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/Users/user/Documents/UnityProjects/TerrainGeneration/Mesh + Terrain Generation.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/user/Documents/UnityProjects/TerrainGeneration/UnityEngine.TestRunner.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/user/Documents/UnityProjects/TerrainGeneration/UnityEngine.UI.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/user/Documents/UnityProjects/TerrainGeneration/Unity.Timeline.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/user/Documents/UnityProjects/TerrainGeneration/Unity.TextMeshPro.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/user/Documents/UnityProjects/TerrainGeneration/Assembly-CSharp.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/user/Documents/UnityProjects/TerrainGeneration/Unity.Timeline.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/user/Documents/UnityProjects/TerrainGeneration/UnityEditor.TestRunner.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/user/Documents/UnityProjects/TerrainGeneration/UnityEditor.UI.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/user/Documents/UnityProjects/TerrainGeneration/Unity.VisualStudio.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/user/Documents/UnityProjects/TerrainGeneration/Unity.TextMeshPro.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/user/Documents/UnityProjects/TerrainGeneration/Unity.CollabProxy.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/user/Documents/UnityProjects/TerrainGeneration/Unity.VSCode.Editor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/user/Documents/UnityProjects/TerrainGeneration/Unity.Rider.Editor.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/user/Documents/UnityProjects/TerrainGeneration'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/user/Documents/UnityProjects/TerrainGeneration' on host 10831.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/user/Documents/UnityProjects/TerrainGeneration/UnityEngine.TestRunner.csproj
[info]: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionService
        Could not find document for file /Users/user/Documents/UnityProjects/TerrainGeneration/Assets/Scripts/MeshGenerator.cs
[fail]: OmniSharp.MSBuild.ProjectLoader
        This project targets .NET version that requires reference assemblies that do not ship with OmniSharp out of the box (e.g. .NET Framework). The most common solution is to make sure Mono is installed on your machine (https://mono-project.com/download/) and that OmniSharp is started with that Mono installation (e.g. "omnisharp.useGlobalMono":"always" in C# Extension for VS Code).
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/Users/user/Documents/UnityProjects/TerrainGeneration/UnityEngine.TestRunner.csproj'.
/Users/user/Documents/UnityProjects/TerrainGeneration/UnityEngine.TestRunner.csproj
/Users/user/.vscode/extensions/ms-dotnettools.csharp-1.23.9/.omnisharp/1.37.9-beta.2/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1216,5): Error: This project targets .NET version that requires reference assemblies that do not ship with OmniSharp out of the box (e.g. .NET Framework). The most common solution is to make sure Mono is installed on your machine (https://mono-project.com/download/) and that OmniSharp is started with that Mono installation (e.g. "omnisharp.useGlobalMono":"always" in C# Extension for VS Code).

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/user/Documents/UnityProjects/TerrainGeneration/UnityEngine.UI.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        This project targets .NET version that requires reference assemblies that do not ship with OmniSharp out of the box (e.g. .NET Framework). The most common solution is to make sure Mono is installed on your machine (https://mono-project.com/download/) and that OmniSharp is started with that Mono installation (e.g. "omnisharp.useGlobalMono":"always" in C# Extension for VS Code).
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/Users/user/Documents/UnityProjects/TerrainGeneration/UnityEngine.UI.csproj'.
/Users/user/Documents/UnityProjects/TerrainGeneration/UnityEngine.UI.csproj
/Users/user/.vscode/extensions/ms-dotnettools.csharp-1.23.9/.omnisharp/1.37.9-beta.2/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1216,5): Error: This project targets .NET version that requires reference assemblies that do not ship with OmniSharp out of the box (e.g. .NET Framework). The most common solution is to make sure Mono is installed on your machine (https://mono-project.com/download/) and that OmniSharp is started with that Mono installation (e.g. "omnisharp.useGlobalMono":"always" in C# Extension for VS Code).

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/user/Documents/UnityProjects/TerrainGeneration/Unity.Timeline.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        This project targets .NET version that requires reference assemblies that do not ship with OmniSharp out of the box (e.g. .NET Framework). The most common solution is to make sure Mono is installed on your machine (https://mono-project.com/download/) and that OmniSharp is started with that Mono installation (e.g. "omnisharp.useGlobalMono":"always" in C# Extension for VS Code).
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/Users/user/Documents/UnityProjects/TerrainGeneration/Unity.Timeline.csproj'.
/Users/user/Documents/UnityProjects/TerrainGeneration/Unity.Timeline.csproj
/Users/user/.vscode/extensions/ms-dotnettools.csharp-1.23.9/.omnisharp/1.37.9-beta.2/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1216,5): Error: This project targets .NET version that requires reference assemblies that do not ship with OmniSharp out of the box (e.g. .NET Framework). The most common solution is to make sure Mono is installed on your machine (https://mono-project.com/download/) and that OmniSharp is started with that Mono installation (e.g. "omnisharp.useGlobalMono":"always" in C# Extension for VS Code).

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/user/Documents/UnityProjects/TerrainGeneration/Unity.TextMeshPro.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        This project targets .NET version that requires reference assemblies that do not ship with OmniSharp out of the box (e.g. .NET Framework). The most common solution is to make sure Mono is installed on your machine (https://mono-project.com/download/) and that OmniSharp is started with that Mono installation (e.g. "omnisharp.useGlobalMono":"always" in C# Extension for VS Code).
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/Users/user/Documents/UnityProjects/TerrainGeneration/Unity.TextMeshPro.csproj'.
/Users/user/Documents/UnityProjects/TerrainGeneration/Unity.TextMeshPro.csproj
/Users/user/.vscode/extensions/ms-dotnettools.csharp-1.23.9/.omnisharp/1.37.9-beta.2/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1216,5): Error: This project targets .NET version that requires reference assemblies that do not ship with OmniSharp out of the box (e.g. .NET Framework). The most common solution is to make sure Mono is installed on your machine (https://mono-project.com/download/) and that OmniSharp is started with that Mono installation (e.g. "omnisharp.useGlobalMono":"always" in C# Extension for VS Code).

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/user/Documents/UnityProjects/TerrainGeneration/Assembly-CSharp.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        This project targets .NET version that requires reference assemblies that do not ship with OmniSharp out of the box (e.g. .NET Framework). The most common solution is to make sure Mono is installed on your machine (https://mono-project.com/download/) and that OmniSharp is started with that Mono installation (e.g. "omnisharp.useGlobalMono":"always" in C# Extension for VS Code).
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/Users/user/Documents/UnityProjects/TerrainGeneration/Assembly-CSharp.csproj'.
/Users/user/Documents/UnityProjects/TerrainGeneration/Assembly-CSharp.csproj
/Users/user/.vscode/extensions/ms-dotnettools.csharp-1.23.9/.omnisharp/1.37.9-beta.2/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1216,5): Error: This project targets .NET version that requires reference assemblies that do not ship with OmniSharp out of the box (e.g. .NET Framework). The most common solution is to make sure Mono is installed on your machine (https://mono-project.com/download/) and that OmniSharp is started with that Mono installation (e.g. "omnisharp.useGlobalMono":"always" in C# Extension for VS Code).

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/user/Documents/UnityProjects/TerrainGeneration/Unity.Timeline.Editor.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        This project targets .NET version that requires reference assemblies that do not ship with OmniSharp out of the box (e.g. .NET Framework). The most common solution is to make sure Mono is installed on your machine (https://mono-project.com/download/) and that OmniSharp is started with that Mono installation (e.g. "omnisharp.useGlobalMono":"always" in C# Extension for VS Code).
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/Users/user/Documents/UnityProjects/TerrainGeneration/Unity.Timeline.Editor.csproj'.
/Users/user/Documents/UnityProjects/TerrainGeneration/Unity.Timeline.Editor.csproj
/Users/user/.vscode/extensions/ms-dotnettools.csharp-1.23.9/.omnisharp/1.37.9-beta.2/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1216,5): Error: This project targets .NET version that requires reference assemblies that do not ship with OmniSharp out of the box (e.g. .NET Framework). The most common solution is to make sure Mono is installed on your machine (https://mono-project.com/download/) and that OmniSharp is started with that Mono installation (e.g. "omnisharp.useGlobalMono":"always" in C# Extension for VS Code).

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/user/Documents/UnityProjects/TerrainGeneration/UnityEditor.TestRunner.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        This project targets .NET version that requires reference assemblies that do not ship with OmniSharp out of the box (e.g. .NET Framework). The most common solution is to make sure Mono is installed on your machine (https://mono-project.com/download/) and that OmniSharp is started with that Mono installation (e.g. "omnisharp.useGlobalMono":"always" in C# Extension for VS Code).
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/Users/user/Documents/UnityProjects/TerrainGeneration/UnityEditor.TestRunner.csproj'.
/Users/user/Documents/UnityProjects/TerrainGeneration/UnityEditor.TestRunner.csproj
/Users/user/.vscode/extensions/ms-dotnettools.csharp-1.23.9/.omnisharp/1.37.9-beta.2/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1216,5): Error: This project targets .NET version that requires reference assemblies that do not ship with OmniSharp out of the box (e.g. .NET Framework). The most common solution is to make sure Mono is installed on your machine (https://mono-project.com/download/) and that OmniSharp is started with that Mono installation (e.g. "omnisharp.useGlobalMono":"always" in C# Extension for VS Code).

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/user/Documents/UnityProjects/TerrainGeneration/UnityEditor.UI.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        This project targets .NET version that requires reference assemblies that do not ship with OmniSharp out of the box (e.g. .NET Framework). The most common solution is to make sure Mono is installed on your machine (https://mono-project.com/download/) and that OmniSharp is started with that Mono installation (e.g. "omnisharp.useGlobalMono":"always" in C# Extension for VS Code).
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/Users/user/Documents/UnityProjects/TerrainGeneration/UnityEditor.UI.csproj'.
/Users/user/Documents/UnityProjects/TerrainGeneration/UnityEditor.UI.csproj
/Users/user/.vscode/extensions/ms-dotnettools.csharp-1.23.9/.omnisharp/1.37.9-beta.2/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1216,5): Error: This project targets .NET version that requires reference assemblies that do not ship with OmniSharp out of the box (e.g. .NET Framework). The most common solution is to make sure Mono is installed on your machine (https://mono-project.com/download/) and that OmniSharp is started with that Mono installation (e.g. "omnisharp.useGlobalMono":"always" in C# Extension for VS Code).

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/user/Documents/UnityProjects/TerrainGeneration/Unity.VisualStudio.Editor.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        This project targets .NET version that requires reference assemblies that do not ship with OmniSharp out of the box (e.g. .NET Framework). The most common solution is to make sure Mono is installed on your machine (https://mono-project.com/download/) and that OmniSharp is started with that Mono installation (e.g. "omnisharp.useGlobalMono":"always" in C# Extension for VS Code).
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/Users/user/Documents/UnityProjects/TerrainGeneration/Unity.VisualStudio.Editor.csproj'.
/Users/user/Documents/UnityProjects/TerrainGeneration/Unity.VisualStudio.Editor.csproj
/Users/user/.vscode/extensions/ms-dotnettools.csharp-1.23.9/.omnisharp/1.37.9-beta.2/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1216,5): Error: This project targets .NET version that requires reference assemblies that do not ship with OmniSharp out of the box (e.g. .NET Framework). The most common solution is to make sure Mono is installed on your machine (https://mono-project.com/download/) and that OmniSharp is started with that Mono installation (e.g. "omnisharp.useGlobalMono":"always" in C# Extension for VS Code).

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/user/Documents/UnityProjects/TerrainGeneration/Unity.TextMeshPro.Editor.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        This project targets .NET version that requires reference assemblies that do not ship with OmniSharp out of the box (e.g. .NET Framework). The most common solution is to make sure Mono is installed on your machine (https://mono-project.com/download/) and that OmniSharp is started with that Mono installation (e.g. "omnisharp.useGlobalMono":"always" in C# Extension for VS Code).
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/Users/user/Documents/UnityProjects/TerrainGeneration/Unity.TextMeshPro.Editor.csproj'.
/Users/user/Documents/UnityProjects/TerrainGeneration/Unity.TextMeshPro.Editor.csproj
/Users/user/.vscode/extensions/ms-dotnettools.csharp-1.23.9/.omnisharp/1.37.9-beta.2/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1216,5): Error: This project targets .NET version that requires reference assemblies that do not ship with OmniSharp out of the box (e.g. .NET Framework). The most common solution is to make sure Mono is installed on your machine (https://mono-project.com/download/) and that OmniSharp is started with that Mono installation (e.g. "omnisharp.useGlobalMono":"always" in C# Extension for VS Code).

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/user/Documents/UnityProjects/TerrainGeneration/Unity.CollabProxy.Editor.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        This project targets .NET version that requires reference assemblies that do not ship with OmniSharp out of the box (e.g. .NET Framework). The most common solution is to make sure Mono is installed on your machine (https://mono-project.com/download/) and that OmniSharp is started with that Mono installation (e.g. "omnisharp.useGlobalMono":"always" in C# Extension for VS Code).
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/Users/user/Documents/UnityProjects/TerrainGeneration/Unity.CollabProxy.Editor.csproj'.
/Users/user/Documents/UnityProjects/TerrainGeneration/Unity.CollabProxy.Editor.csproj
/Users/user/.vscode/extensions/ms-dotnettools.csharp-1.23.9/.omnisharp/1.37.9-beta.2/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1216,5): Error: This project targets .NET version that requires reference assemblies that do not ship with OmniSharp out of the box (e.g. .NET Framework). The most common solution is to make sure Mono is installed on your machine (https://mono-project.com/download/) and that OmniSharp is started with that Mono installation (e.g. "omnisharp.useGlobalMono":"always" in C# Extension for VS Code).

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/user/Documents/UnityProjects/TerrainGeneration/Unity.VSCode.Editor.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        This project targets .NET version that requires reference assemblies that do not ship with OmniSharp out of the box (e.g. .NET Framework). The most common solution is to make sure Mono is installed on your machine (https://mono-project.com/download/) and that OmniSharp is started with that Mono installation (e.g. "omnisharp.useGlobalMono":"always" in C# Extension for VS Code).
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/Users/user/Documents/UnityProjects/TerrainGeneration/Unity.VSCode.Editor.csproj'.
/Users/user/Documents/UnityProjects/TerrainGeneration/Unity.VSCode.Editor.csproj
/Users/user/.vscode/extensions/ms-dotnettools.csharp-1.23.9/.omnisharp/1.37.9-beta.2/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1216,5): Error: This project targets .NET version that requires reference assemblies that do not ship with OmniSharp out of the box (e.g. .NET Framework). The most common solution is to make sure Mono is installed on your machine (https://mono-project.com/download/) and that OmniSharp is started with that Mono installation (e.g. "omnisharp.useGlobalMono":"always" in C# Extension for VS Code).

[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/user/Documents/UnityProjects/TerrainGeneration/Unity.Rider.Editor.csproj
[fail]: OmniSharp.MSBuild.ProjectLoader
        This project targets .NET version that requires reference assemblies that do not ship with OmniSharp out of the box (e.g. .NET Framework). The most common solution is to make sure Mono is installed on your machine (https://mono-project.com/download/) and that OmniSharp is started with that Mono installation (e.g. "omnisharp.useGlobalMono":"always" in C# Extension for VS Code).
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/Users/user/Documents/UnityProjects/TerrainGeneration/Unity.Rider.Editor.csproj'.
/Users/user/Documents/UnityProjects/TerrainGeneration/Unity.Rider.Editor.csproj
/Users/user/.vscode/extensions/ms-dotnettools.csharp-1.23.9/.omnisharp/1.37.9-beta.2/omnisharp/.msbuild/Current/Bin/Microsoft.Common.CurrentVersion.targets(1216,5): Error: This project targets .NET version that requires reference assemblies that do not ship with OmniSharp out of the box (e.g. .NET Framework). The most common solution is to make sure Mono is installed on your machine (https://mono-project.com/download/) and that OmniSharp is started with that Mono installation (e.g. "omnisharp.useGlobalMono":"always" in C# Extension for VS Code).

[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /Users/user/Documents/UnityProjects/TerrainGeneration/UnityEngine.TestRunner.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /Users/user/Documents/UnityProjects/TerrainGeneration/UnityEngine.UI.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /Users/user/Documents/UnityProjects/TerrainGeneration/Unity.Timeline.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /Users/user/Documents/UnityProjects/TerrainGeneration/Unity.TextMeshPro.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /Users/user/Documents/UnityProjects/TerrainGeneration/Assembly-CSharp.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /Users/user/Documents/UnityProjects/TerrainGeneration/Unity.Timeline.Editor.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /Users/user/Documents/UnityProjects/TerrainGeneration/UnityEditor.TestRunner.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /Users/user/Documents/UnityProjects/TerrainGeneration/UnityEditor.UI.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /Users/user/Documents/UnityProjects/TerrainGeneration/Unity.VisualStudio.Editor.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /Users/user/Documents/UnityProjects/TerrainGeneration/Unity.TextMeshPro.Editor.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /Users/user/Documents/UnityProjects/TerrainGeneration/Unity.CollabProxy.Editor.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /Users/user/Documents/UnityProjects/TerrainGeneration/Unity.VSCode.Editor.csproj
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /Users/user/Documents/UnityProjects/TerrainGeneration/Unity.Rider.Editor.csproj
[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
        Solution initialized -> queue all documents for code analysis. Initial document count: 0.
[info]: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionService
        Could not find document for file /Users/user/Documents/UnityProjects/TerrainGeneration/Assets/Scripts/MeshGenerator.cs

### C# log ###
There isn't any logs for C#

## Environment information ##

**VSCode version**: 1.55.1
**C# Extension**: 1.23.9

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.202
 Commit:    db7cc87d51

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.202/

Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14

.NET SDKs installed:
  3.1.407 [/usr/local/share/dotnet/sdk]
  5.0.202 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|atlantic-night|mrpbennett|1.22.0|
|csharp|ms-dotnettools|1.23.9|
|datapack-language-server|SPGoding|3.3.0|
|eppz-code|eppz|1.2.52|
|feppz--theme|foxnne|0.6.0|
|kite|kiteco|0.142.0|
|language-mcfunction|arcensoth|0.17.0|
|material-icon-theme|PKief|4.6.0|
|one-monokai|azemoh|0.5.0|
|Sk-VSC|ayhamalali|2.6.3|
|teppz|ofrades|2.4.2|
|theme-monokai-pro-vscode|monokai|1.1.19|
|tokyo-night|enkia|0.7.9|
|unity-code-snippets|kleber-swf|1.3.0|
|unity-debug|Unity|3.0.2|
|unity-snippets|YclepticStudios|0.1.2|
|unity-tools|Tobiah|1.2.12|;

</details>

**Comment by nohwnd** [comment]
Is the document that is reported as missing a document that you have open in the vscode editor? 

As the log suggests you need to install mono and configure you vscode to use it because this is needed for Unity development on MacOS: 

> This project targets .NET version that requires reference assemblies that do not ship with OmniSharp out of the box (e.g. .NET Framework). The most common solution is to make sure Mono is installed on your machine (https://mono-project.com/download/) and that OmniSharp is started with that Mono installation (e.g. "omnisharp.useGlobalMono":"always" in C# Extension for VS Code).
