### ISSUE TITLE
cant install dependencies

### ISSUE THREAD

**Issue by KurbagaPrens** [dotnet/vscode-csharp#4494]
Installing C# dependencies...
Platform: win32, x86_64

Downloading package 'Razor Language Server (Windows / x64)' (60477 KB)................... Done!
Installing package 'Razor Language Server (Windows / x64)'

Failed at stage: installPackage
C# Extension was unable to download its dependencies. Please check your internet connection. If you use a proxy server, please visit https://aka.ms/VsCodeCsharpNetworking

------------------------------------------------------------------------------------------------------------------------------------
This is what is on the output. I couldn't install dependencies at first so I manually downloaded them and moved them to the folders. Did the same with razor but VS Code didn't approved the installation. It downloads again and fails.

**Comment by nohwnd** [comment]
Since you manually downloaded those packages, ensure that the razor packages are installed into .razor and that an empty `install.Lock` file is present in the folder. The capitalization of the name might be important.

**Comment by JoeRobich** [comment]
Closing as answered.
