### ISSUE TITLE
Color coding issue when using newline in argument type list

### ISSUE THREAD

**Issue by gsscoder** [dotnet/vscode-csharp#4495]
More easy to see a shot:
![image](https://user-images.githubusercontent.com/1194228/114304067-854a1800-9ad1-11eb-83a1-6a458c74f508.png)

Have a nice day,
Giacomo S. S.

**Comment by nohwnd** [comment]
Do you have "Csharp › Semantic Highlighting: Enabled" setting enabled: 

![image](https://user-images.githubusercontent.com/5735905/114892679-48ea2500-9e0d-11eb-8310-48aaf5e510ab.png)

Can you please check that, and post the code as text as well so I can try it locally? 

Can you also list other extensions that you have installed? Maybe there is a conflict. You can do bisecting on the extensions: 

![image](https://user-images.githubusercontent.com/5735905/114893244-d0379880-9e0d-11eb-9b0c-ed5c3c89699b.png)

You can also report the issue using the built in command that provides more info and link back to this one, or just copy the information from there. Thanks. 

![image](https://user-images.githubusercontent.com/5735905/114893396-f1988480-9e0d-11eb-9a45-60cc4876ffd2.png)

**Comment by gsscoder** [comment]
@nohwnd, I've learned new thing with your reply. Thanks for that.

**Semantic Highlighting** was disabled and enabling it didn't fixed the issue.

I'm not familiar with **Extension Bisect**. It is activated to generated a log? Where I can find it?

Bye

**Comment by JoeRobich** [comment]
Closing as answered.
