### ISSUE TITLE
Intellisence not working inside of devcontainer

### ISSUE THREAD

**Issue by JasimAtiyeh** [dotnet/vscode-csharp#4496]
- VSCode Version: 1.55.0
- OS: macOS Catalina 10.15.6
- C# Extension: 1.23.11
- Dotnet core 3.1

I am running a dev container with the above setup. All of my cs files will show no syntax highlighting or intellisence at all. However, if I downgrade my version of the C# extension to 1.23.8, syntax highlighting and intellisence will work just fine. Anything past that version seems to not be working within a devcontainer. Outside of a devcontainer, I have no issues.

**Comment by JoeRobich** [comment]
@JasimAtiyeh Can you please share the OmniSharp log from the VS Code Output pane? It will likely have information we can use to narrow down the cause of your issue.

**Comment by JoeRobich** [comment]
Closing due to lack of response.
