### ISSUE TITLE
Multiple Restore dependencies notifications

### ISSUE THREAD

**Issue by ferenczy** [dotnet/vscode-csharp#4511]
## Issue Description ##

When I open a .NET solution that doesn't have restored dependencies yet, the C# extension sometimes generates multiple identical notifications with the text "_There are unresolved dependencies. Please execute the restore command to continue._" and the _Restore_ button, see below:

![Multiple restore dependencies notifications](https://user-images.githubusercontent.com/1712992/115603650-b5b76080-a2e0-11eb-99ec-df6b3182ec52.png)

I'm guessing that it happens when there're multiple projects and each notification references one of those projects, but there's no way how to recognize that and how to identify what notification references what project.

It would be great if the notification contains some identifier (a project name) to help with that.

## Steps to Reproduce ##

1. Open a .NET solution containing multiple projects with dependencies you don't have already downloaded (restored)
2. The C# extension generates multiple identical notifications

## Expected Behavior ##

There's some identifier to recognize what project notification references.

## Actual Behavior ##

The notification contains just generic text.

## Environment information ##

**VSCode version**: 1.55.1
**C# Extension**: 1.23.11

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.201\

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  2.1.811 [C:\Program Files\dotnet\sdk]
  3.1.404 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|13.0.4|
|bracket-pair-colorizer-2|CoenraadS|0.2.0|
|change-case|wmaurer|1.0.0|
|code-spell-checker|streetsidesoftware|1.10.2|
|code-spell-checker-czech|streetsidesoftware|0.1.6|
|code-stats-vscode|riussi|1.0.18|
|color-highlight|naumovs|2.3.0|
|csharp|ms-dotnettools|1.23.11|
|docs-view|bierner|0.0.9|
|EditorConfig|EditorConfig|0.16.4|
|git-graph|mhutchie|1.30.0|
|githistory|donjayamanne|0.6.16|
|gitlens|eamodio|11.4.1|
|indent-rainbow|oderwat|7.5.0|
|linesinfostatusbar|peterfh|0.0.3|
|markdown-links|tchayen|0.8.0|
|markdown-memo|svsool|0.3.4|
|markdown-table-prettify|darkriszty|3.4.0|
|markdown-toc|AlanWalk|1.5.6|
|material-icon-theme|PKief|4.6.0|
|overtype|DrMerfy|0.4.0|
|project-manager|alefragnani|12.1.0|
|rainbow-csv|mechatroner|1.8.1|
|trailing-spaces|shardulm94|0.3.1|
|vscode-icons|vscode-icons-team|11.4.0|
|vscode-nuget-package-manager-improved|maxbrister|2.1.0|
|vscode-sql-formatter|adpyke|1.4.4|
|xml|DotJoshJohnson|2.5.1|;

</details>

**Comment by ferenczy** [comment]
@JoeRobich I see, so what generates multiple notifications, please? Is it really one notification for each project?

**Comment by JoeRobich** [comment]
VS Code now deduplicates notifications with identical text.
