### ISSUE TITLE
Record types syntax highlighting

### ISSUE THREAD

**Issue by wendellestradairely** [dotnet/vscode-csharp#4512]
Feature request: Need a syntax highlighting for record types.

![image](https://user-images.githubusercontent.com/50942719/115812663-4cd90100-a424-11eb-91e8-f54a46af5e40.png)

**Comment by JoeRobich** [comment]
@wendellestradairely This is an issue with the C# textmate grammar. You can set `csharp.semanticHighlighting.enabled` to `true` to get a better highlighting experience.

**Comment by JoeRobich** [comment]
Closing as answered.
