### ISSUE TITLE
Cannot start extension - Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by CardExchangeSolutions** [dotnet/vscode-csharp#4513]
As soon as I install the extension on Mac I get this error in the output window:

Installing C# dependencies...
Platform: darwin, x86_64

Downloading package 'OmniSharp for OSX' 	Retrying from 'https://roslynomnisharp.blob.core.windows.net/releases/1.37.8/omnisharp-osx-1.37.8.zip' Failed at stage: downloadPackage
Error: self signed certificate in certificate chain

Can someone suggest how to resolve this error?

**Comment by JoeRobich** [comment]
A lot has changed with O# acquisition since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
