### ISSUE TITLE
[Feature Request] Remove unnecessary usings on format C# file

### ISSUE THREAD

**Issue by osotorrio** [dotnet/vscode-csharp#4519]
The same way today we can organise usings on format in a C# file with the following settings:

```
  "editor.formatOnSave": true,
  "omnisharp.organizeImportsOnFormat": true
```

It would be nice to have another option to remove the unused usings.

```
  "editor.formatOnSave": true,
  "omnisharp.organizeImportsOnFormat": true,
  "omnisharp.removeUnnecessaryImportsOnFormat": true (only a subjection)
```

I am aware that this feature has been implemented already via Ctrl+Shift+P -> OmniSharp: Fix all ocurrences of a code issue within solution (or project)-> CS8019: Unnecessary using directive.

But it would be helpful if the unnecessary imports are removed anytime you format the file so you don't need to remember to do it manually.

**Comment by JoeRobich** [comment]
`organizeImportsOnFormat` should already remove unnecessary imports.  If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
