### ISSUE TITLE
OmniSharp Intellisense in Razor Mac ARM

### ISSUE THREAD

**Issue by tiagoalberto** [dotnet/vscode-csharp#4521]
Issue Type: <b>Bug</b>

I've the lattest vs code and C# extension. .NET Core works fine on mac os BigSur running apple silicon, but there is no intellisense in Razor Views. 

Extension version: 1.23.11
VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:39:47.234Z)
OS version: Darwin arm64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (1.96GB free)|
|Process Argv|. --crash-reporter-id 22c681d6-b1c5-4139-a1c4-ff5c22a68bba|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602cf:30291500
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsnew554cf:30291488
pythontb:30283811
pythonvspyt551cf:30291415
vspre833:30267464
pythonptprofiler:30281270
vscnewfilehidden:30288034
vshan820:30276952
vscoreces:30290705
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30294352

```

</details>

**Comment by JoeRobich** [comment]
A lot has changed with O# ARM support since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
