### ISSUE TITLE
Editing support not working with Unity much of the time

### ISSUE THREAD

**Issue by andymads** [dotnet/vscode-csharp#4524]
## Issue Description ##

"Great C# editing support, including Syntax Highlighting, IntelliSense, Go to Definition, Find All References, etc" just doesn't work much of the time with Unity 2019.4 without going through cycles of regenerating project files, closing the project, and closing Visual Studio Code. Eventually I'll see "Loading" when I hover over some code so I know it's finally working, but next time I open that project it's a toss-up between it still working or having to go through the cycles again to get it working.

I have omnisharp.useGlobalMono set to "always" as specified in the Known Issues section.
I have the latest version of Visual Studio Code Editor package in my Unity projects.

I have attached a project demonstrating this behaviour.

[NewUnityProject.zip](https://github.com/OmniSharp/omnisharp-vscode/files/6393385/NewUnityProject.zip)

## Expected Behavior ##

When I do Open C# Project in Unity I expect the editing support to work every time. I was previously using a much older 1.32 version (possibly 1.32.2) before factory resetting my Mac and I had no problems then. 

## Actual Behavior ##

Most of the time the editing support does not work.

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.55.2
**C# Extension**: 1.23.11

<details><summary>Mono Information</summary>
        OmniSharp using global mono :6.12.0</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.202
 Commit:    db7cc87d51

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.202/

Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14

.NET SDKs installed:
  3.1.408 [/usr/local/share/dotnet/sdk]
  5.0.202 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.14 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.23.11|
|unity-debug|Unity|3.0.2|;

</details>

**Comment by JoeRobich** [comment]
@andymads Can you please share your OmniSharp Log from the Output pane? It will include details we need to help troubleshoot your issue.

**Comment by andymads** [comment]
> @andymads Can you please share your OmniSharp Log from the Output pane? It will include details we need to help troubleshoot your issue.

So it's telling me why it's not working? But if this is the reason then how does it work some of the time?

Starting OmniSharp server at 4/28/2021, 6:05:14 PM
    Target: /Users/andymaddison/Desktop/NewUnityProject/NewUnityProject.sln

[ERROR] Error: Unable to find Mono. Ensure that Mono's '/bin' folder is added to your environment's PATH variable.

**Comment by JoeRobich** [comment]
> But if this is the reason then how does it work some of the time?

@andymads On MacOS the environment variables inherited by VS Code depends on how it was launched. From a command line the VS Code instance will inherit your shell's environment variables. From the Dock or Unity this is not necessarily the case. It all depends on how Mono was installed. We recommend you use the installer from https://www.mono-project.com/download/stable/ instead of other means such as Homebrew.

**Comment by andymads** [comment]
> > But if this is the reason then how does it work some of the time?
> 
> @andymads On MacOS the environment variables inherited by VS Code depends on how it was launched. From a command line the VS Code instance will inherit your shell's environment variables. From the Dock or Unity this is not necessarily the case. It all depends on how Mono was installed. We recommend you use the installer from https://www.mono-project.com/download/stable/ instead of other means such as Homebrew.

I did install from that link. I followed the instructions at https://code.visualstudio.com/docs/other/unity.

In my path I have this

/Library/Frameworks/Mono.framework/Versions/Current/Commands

But there is no /bin folder for Mono.

Do I need to add 

/Library/Frameworks/Mono.framework/Versions/6.12.0/bin

to my path?

**Comment by JoeRobich** [comment]
> I went back to the mono download page and installed again, but it's still 6.12.0 which is the latest. Why is it suggesting I update?> 

@andymads You have NET 5 installed which requires MSBuild 16.8 or higher. The current Mono stable release only includes version 16.6. This won't be a problem when working with Unity projects because they target NET 4.7.1.

The Mono Preview build includes an MSBuild 16.9 and there will be much rejoicing when it becomes the stable release.

**Comment by JoeRobich** [comment]
@andymads The only reason I can see for you to occasionally get a missing Mono error, is that VS Code is being launched in a way that does not inherit your Shell's environment variables. There is a setting `omnisharp.monoPath` which you can set in VS Code to `/Library/Frameworks/Mono.framework/Versions/Current`. This should make it consistently locate Mono.

**Comment by andymads** [comment]
> /Library/Frameworks/Mono.framework/Versions/Current

@JoeRobich thank you.

**Comment by zcr1** [comment]
This regularly happens to me on osx (monthly?) and typically rebooting fixes it. No clue why.

**Comment by JoeRobich** [comment]
It is recommended to use the Unity extension for VS Code.
