### ISSUE TITLE
Show uninmplemented interface methods in Intellisense completion (after "public" and maybe "override" too)

### ISSUE THREAD

**Issue by geekley** [dotnet/vscode-csharp#4531]
## Environment data
`dotnet --info` output: not installed
VS Code version: 1.55.2; Linux x64 5.4.0-72-generic snap
C# Extension version: 1.23.11

## Steps to reproduce
```cs
class Foo : FooBase, ISomeInterface
{
  // ...
  public // after SPACE here, on IntelliSense completion (or CTRL+SPACE)
  // ...
  public override // maybe also here
  // ...
}
```

## Expected  behavior
Completion will list only `override` methods from base classes, but you can make a huge improvement if you also list all necessary interface methods that haven't been implemented yet. Even though they don't use the keyword, it's conceptually a very similar intent from the programmers' perspective.
You'd just have to make completion automatically delete the `override` keyword in this case, and then add the method signature.

If deleting it is impossible, you could at least have completion for interface methods suggested after `public` (space).
Suggestions for *required* interface methods should appear first priority, before everything else (since in this case, the file is in an error state, and you surely want to fix that right away).

## Actual behavior
Currently interface methods are not suggested at all in completion, neither after `public` or `public override`.

Yeah, I *could* use the "Implement interface" light-bulb fix, but I don't like it, because I don't even get to choose where I want the methods in the code, and that's important. Completion solves this.

---
Also, in both light-bulb and completion, I'm getting tabs even though my files are set to spaces; please fix this too (I do have `csharp.format.enable: false`, by the way).

**Comment by MasoudAbdaal** [comment]
I have same issue, while defining interface and do not have intellisense for it's implementations!

**Comment by JoeRobich** [comment]
This functionality is provided by Roslyn. If you are still having problems, you can open a new issue at https://github.com/dotnet/roslyn/issues
