### ISSUE TITLE
Error occurred in loading omnisharp from omnisharp.path

### ISSUE THREAD

**Issue by asim2000** [dotnet/vscode-csharp#4537]
Could not start the server due to Error: Request error: getaddrinfo ENOTFOUND roslynomnisharp.blob.core.windows.net

**Comment by JoeRobich** [comment]
@asim2000 Can you describe your scenario in more detail? Are you working offline or behind a firewall? 

These instructions can be followed to build a copy of the extension that can be fully installed offline - https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-the-C%23-extension-to-a-computer-without-internet-connectivity

**Comment by JoeRobich** [comment]
Closing due to lack of response.
