### ISSUE TITLE
[Feature Request] Implement highlighting for pointer syntax

### ISSUE THREAD

**Issue by Powerlated** [dotnet/vscode-csharp#4555]
Currently, syntax highlighting is not properly applied to pointer types.
![image](https://user-images.githubusercontent.com/7016749/118572943-88c76380-b74f-11eb-91ee-486af19d767a.png)

VSCode version: 1.56.0
C# Extension: 1.23.11

**Comment by 333fred** [comment]
It does not look like you have semantic highlighting turned on. Try enabling it and see if that fixes it for you.

**Comment by JoeRobich** [comment]
Closing due to lack of response
