### ISSUE TITLE
Command '.NET: Generate Assets for Build and Debug' resulted in an error.

### ISSUE THREAD

**Issue by WhatTheRob** [dotnet/vscode-csharp#4558]
## Environment data
`dotnet --info` output: 5.0.201 & 5.0.203
VS Code version: 1.56.2
C# Extension version: 1.23.11

## OmniSharp log
No log

## Steps to reproduce
type 'dotnet new console' in terminal
open command pallette
type '.NET: Generate Assets for Build and Debug'
press enter
## Expected  behavior
create .vscode folder with 'launch.json' and 'task.json' inside

## Actual behavior
I get the error "Command '.NET Generate Assets for Build and Debug' resulted in an error (command 'dotnet.generateAssets' not found)"

**Comment by Yng-Ducky09** [comment]
I noticed all of the commands that I do have the same problem.

**Comment by JoeRobich** [comment]
@Yng-Ducky09 I can reproduce similar errors when I open an empty folder in VS Code and follow your steps.

If you close VS Code and reopen the folder do the asset files generate properly?

The "command 'dotnet.generateAssets' not found" message makes me think it might be an installation issue. If the asset files won't generate after freshly openeing the folder, you may want to uninstall the C# extension and reinstall it.

**Comment by Yng-Ducky09** [comment]
When I close VScode and open it back up it does not work and the c# extension won't let me unistall it. When I try to I get another error: "Cannot unistall 'C#' extension. 'Ionide-fsharp' extension depends on this."

**Comment by JoeRobich** [comment]
> I fixed the unistalling problem but when I tried to generate the assets again, it failed.

Did it fail with the same error ("command 'dotnet.generateAssets' not found") or different error?

**Comment by Yng-Ducky09** [comment]
same error

**Comment by Yng-Ducky09** [comment]
Hello?

**Comment by JoeRobich** [comment]
This sounds like a O# issue where it is not watching the root folder for new project files to get created. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
