### ISSUE TITLE
Received response for /v2/getcodeactions but could not find request. Using namespace autocomplete not working.

### ISSUE THREAD

**Issue by py930828** [dotnet/vscode-csharp#4560]
## Issue Description ##
using namespace autocomplete not working, vscode intellisense shows No quick fixes available.
It seems like a server error as the log shows could not find request.
![image](https://user-images.githubusercontent.com/25916453/118878825-001b0580-b8be-11eb-803d-6276b5635c10.png)

## Steps to Reproduce ##
Doesn't work on two of my machine, never worked
## Expected Behavior ##
shows namespace autocomplete option.
## Actual Behavior ##
intellisense shows No quick fixes available
### OmniSharp log ###
<details>Starting OmniSharp server at 2021/5/19下午4:03:03
    Target: c:\Users\cl930\Desktop\LeetCode

OmniSharp server started.
    Path: c:\Users\cl930\.vscode\extensions\ms-dotnettools.csharp-1.23.11\.omnisharp\1.37.8\OmniSharp.exe
    PID: 4948

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.9.0 - "c:\Users\cl930\.vscode\extensions\ms-dotnettools.csharp-1.23.11\.omnisharp\1.37.8\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'c:\Users\cl930\.vscode\extensions\ms-dotnettools.csharp-1.23.11\.omnisharp\1.37.8\.msbuild\Current\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.9.0 - "c:\Users\cl930\.vscode\extensions\ms-dotnettools.csharp-1.23.11\.omnisharp\1.37.8\.msbuild\Current\Bin"
            CscToolExe = csc.exe
            CscToolPath = c:\Users\cl930\.vscode\extensions\ms-dotnettools.csharp-1.23.11\.omnisharp\1.37.8\.msbuild\Current\Bin\Roslyn
            MSBuildExtensionsPath = c:\Users\cl930\.vscode\extensions\ms-dotnettools.csharp-1.23.11\.omnisharp\1.37.8\.msbuild
            MSBuildToolsPath = c:\Users\cl930\.vscode\extensions\ms-dotnettools.csharp-1.23.11\.omnisharp\1.37.8\.msbuild\Current\Bin
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\cl930\Desktop\LeetCode'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Users\cl930\Desktop\LeetCode'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\cl930\Desktop\LeetCode\LeetCode.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\cl930\Desktop\LeetCode'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\cl930\Desktop\LeetCode' on host 2872.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\cl930\Desktop\LeetCode\LeetCode.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\cl930\Desktop\LeetCode\LeetCode.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\cl930\Desktop\LeetCode\LeetCode.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: LeetCode
Received response for /v2/getcodeactions but could not find request.
Received response for /quickinfo but could not find request.
[warn]: OmniSharp.Roslyn.CSharp.Services.Navigation.FindUsagesService
        No symbol found. File: c:\Users\cl930\Desktop\Leetcode\637.average-of-levels-in-binary-tree.cs, Line: 22, Column: 12.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
[warn]: OmniSharp.Roslyn.CSharp.Services.Navigation.FindUsagesService
        No symbol found. File: c:\Users\cl930\Desktop\Leetcode\637.average-of-levels-in-binary-tree.cs, Line: 23, Column: 23.
[warn]: OmniSharp.Roslyn.CSharp.Services.Navigation.FindUsagesService
        No symbol found. File: c:\Users\cl930\Desktop\Leetcode\637.average-of-levels-in-binary-tree.cs, Line: 23, Column: 37.
[warn]: OmniSharp.Roslyn.CSharp.Services.Navigation.FindUsagesService
        No symbol found. File: c:\Users\cl930\Desktop\Leetcode\637.average-of-levels-in-binary-tree.cs, Line: 22, Column: 37.
</details>

### C# log ###
<details>No C# log</details>

## Environment information ##

**VSCode version**: 1.56.2
**C# Extension**: 1.23.11

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.409
 Commit:    217439b5ae

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.409\

Host (useful for support):
  Version: 3.1.15
  Commit:  dc339bd0fb

.NET Core SDKs installed:
  3.1.409 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.23.11|
|vscode-leetcode|LeetCode|0.17.0|;

</details>

**Comment by zysim** [comment]
Consider reading this: https://github.com/OmniSharp/omnisharp-vscode/issues/5029#issuecomment-1023766141. It fixed the problem on my machine.

**Comment by JoeRobich** [comment]
A lot has changed with O# code analysis since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
