### ISSUE TITLE
[ERROR] Error: spawn cmd EACCES

### ISSUE THREAD

**Issue by taooceros** [dotnet/vscode-csharp#4564]
## Issue Description ##
Unable to start omnisharp in vscode

## Expected Behavior ##

Omnisharp starts normally and present intellisence

## Actual Behavior ##

Omnisharp is unable to start

### OmniSharp log ###

Starting OmniSharp server at 2021/5/23下午8:21:56
    Target: d:\Document\Dotnet\Flow.Launcher\Flow.Launcher.sln

[ERROR] Error: spawn cmd EACCES

### C# log ###

The log is empty

## Environment information ##

**VSCode version**: 1.57.0-insider
**C# Extension**: 1.23.11

<details><summary>Dotnet Information</summary>
A valid dotnet installation could not be found.

I don't know why it is unable to detect the dotnet installation. Here is the sdks installed.
![image](https://user-images.githubusercontent.com/45326534/119260480-8f4d5380-bc05-11eb-8540-70a5765b2d83.png)
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|1.5.0|
|bracket-pair-colorizer-2|CoenraadS|0.2.0|
|cloudmusic|YXL|8.3.3|
|code-runner|formulahendry|0.11.4|
|csharp|ms-dotnettools|1.23.11|
|debugger-for-edge|msjsdiag|1.0.15|
|docthis|oouo-diogo-perdigao|0.8.2|
|errorlens|usernamehw|3.2.6|
|gitlens|eamodio|11.4.1|
|gradle-language|naco-siren|0.2.3|
|html-snippets|abusaidm|0.2.1|
|java|redhat|0.79.2|
|java-decompiler|dgileadi|0.0.2|
|jeng-theme-light|jeng|1.0.5|
|jshint|dbaeumer|0.11.0|
|jupyter|ms-toolsai|2021.6.863311888|
|LiveServer|ritwickdey|5.6.1|
|octave|leafvmaple|0.1.1|
|octave|toasty-technologies|0.0.3|
|octave-hacking|apjanke|0.2.12|
|open-in-browser|techer|2.0.0|
|pdf|tomoki1207|1.1.0|
|powershell-preview|ms-vscode|2021.5.0|
|project-manager|alefragnani|12.1.0|
|python|ms-python|2021.5.842923320|
|r|Ikuyadeu|1.6.6|
|r-lsp|REditorSupport|0.1.14|
|remote-wsl|ms-vscode-remote|0.56.2|
|se-csproj-extensions|selcukermaya|0.0.7|
|tabnine-vscode|TabNine|3.4.4|
|vsc-community-material-theme|Equinusocio|1.4.2|
|vsc-material-theme|Equinusocio|33.1.2|
|vsc-material-theme-icons|equinusocio|1.2.2|
|vsc-octave-debugger|paulosilva|0.4.15|
|vsc-python-indent|KevinRose|1.14.2|
|vscode-commons|redhat|0.0.6|
|vscode-edge-devtools|ms-edgedevtools|1.1.9|
|vscode-eslint|dbaeumer|2.1.20|
|vscode-gradle|richardwillis|3.6.1|
|vscode-gradle-extension-pack|richardwillis|0.0.2|
|vscode-java-debug|vscjava|0.33.1|
|vscode-java-dependency|vscjava|0.18.3|
|vscode-java-pack|vscjava|0.15.0|
|vscode-java-test|vscjava|0.29.0|
|vscode-javascript-booster|sburg|14.0.1|
|vscode-maven|vscjava|0.30.1|
|vscode-pull-request-github|GitHub|0.26.0|
|vscode-pylance|ms-python|2021.5.3|
|vscode-sftp|suntobright|1.1.1|
|vscode-todo-highlight|wayou|1.0.4|
|vscode-wakatime|WakaTime|10.0.1|
|vscode-yaml|redhat|0.19.2|
|vscodeintellicode|VisualStudioExptTeam|1.2.14|
|vsliveshare|ms-vsliveshare|1.0.4272|
|vsliveshare-audio|ms-vsliveshare|0.1.91|
|vsliveshare-pack|ms-vsliveshare|0.4.0|
|winteriscoming|johnpapa|1.4.4|
|xml|DotJoshJohnson|2.5.1|;

</details>

**Comment by taooceros** [comment]
I don't know why it is unable to detect the dotnet installation. Here is the sdks installed.
![image](https://user-images.githubusercontent.com/45326534/119260480-8f4d5380-bc05-11eb-8540-70a5765b2d83.png)

**Comment by taooceros** [comment]
I don't know why it is unable to detect the dotnet installation. Here is the sdks installed.
![image](https://user-images.githubusercontent.com/45326534/119260480-8f4d5380-bc05-11eb-8540-70a5765b2d83.png)

**Comment by JoeRobich** [comment]
A lot has changed with O# launching since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
