### ISSUE TITLE
"value" should be highlighted as a keyword

### ISSUE THREAD

**Issue by JokeUrSelf** [dotnet/vscode-csharp#4565]
Issue Type: <b>Feature Request</b>

"value" is not highlighted as a keyword, when setting property

Extension version: 1.23.11
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.17763

**Comment by JoeRobich** [comment]
@JokeUrSelf Thanks for reporting this issue. It is likely an issue with the C# textmate grammar located at https://github.com/dotnet/csharp-tmLanguage. As a work around, you can set `csharp.semanticHighlighting.enabled` to `true` to enable semantic highlighting.

**Comment by JoeRobich** [comment]
Closing as answered.
