### ISSUE TITLE
Unable to target project directory when subfolders contain .sln files

### ISSUE THREAD

**Issue by HJfod** [dotnet/vscode-csharp#4567]
## Issue Description ##
I have a project, which at runtime uses CMake and MSBuild to build some executables. As a result though, my `bin/Debug/net5.0/win10-x64` folder has subfolders in it with .sln files. My root project directory does not contain a .sln file, only a .csproj file. When Omnisharp starts, it targets an .sln file within the bin/ directory, which is not what I want as I'd prefer to have intellisense for my actual project. I can't use `Omnisharp: Select Project` as it only lists .sln files, and not directories.

## Steps to Reproduce ##
1. Create an empty directory with .cs files and a .csproj file
2. Add a .sln file in a subfolder
3. Restart Omnisharp

## Expected Behavior ##
Omnisharp would either automatically target the root project folder or let you pick the root project folder as a target

## Actual Behavior ##
Omnisharp targets a .sln file from a subfolder, and there's no option in Select Project to select the root folder

### OmniSharp log ###
<details>
Starting OmniSharp server at 24/05/2021, 08:55:16
    Target: k:\gdmake\bin\Debug\net5.0\win10-x64\submodules\Cocos2d\cocos2dx\platform\third_party\winrt\freetype\proj.winrt\freetype_2013.sln

OmniSharp server started.
    Path: c:\Users\HJfod\.vscode\extensions\ms-dotnettools.csharp-1.23.11\.omnisharp\1.37.8\OmniSharp.exe
    PID: 8236

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2019 16.9.31313.79 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
            2: StandAlone 16.9.0 - "c:\Users\HJfod\.vscode\extensions\ms-dotnettools.csharp-1.23.11\.omnisharp\1.37.8\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2019 16.9.31313.79 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'k:\gdmake\bin\Debug\net5.0\win10-x64\submodules\Cocos2d\cocos2dx\platform\third_party\winrt\freetype\proj.winrt'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'k:\gdmake\bin\Debug\net5.0\win10-x64\submodules\Cocos2d\cocos2dx\platform\third_party\winrt\freetype\proj.winrt\freetype_2013.sln'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'k:\gdmake\bin\Debug\net5.0\win10-x64\submodules\Cocos2d\cocos2dx\platform\third_party\winrt\freetype\proj.winrt'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'k:\gdmake\bin\Debug\net5.0\win10-x64\submodules\Cocos2d\cocos2dx\platform\third_party\winrt\freetype\proj.winrt' on host 17892.
[ERROR] Error: command 'omnisharp.runCodeAction' already exists
</details>

### C# log ###
<details>(The log is completely empty)</details>

## Environment information ##

**VSCode version**: 1.56.2
**C# Extension**: 1.23.11

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.203
 Commit:    383637d63f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.203\

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

.NET SDKs installed:
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.203 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|cmake|twxs|0.0.17|
|cmake-format|cheshirekow|0.6.11|
|code-gnu-global|austin|0.2.2|
|cpptools|ms-vscode|1.4.0-insiders2|
|csharp|ms-dotnettools|1.23.11|
|dart-code|Dart-Code|3.22.0|
|discord-vscode|icrawl|5.6.3|
|jupyter|ms-toolsai|2021.6.832593372|
|material-icon-theme|PKief|4.6.0|
|material-product-icons|PKief|1.0.4|
|powershell|ms-vscode|2021.2.2|
|propertylist|zhouronghui|0.0.2|
|python|ms-python|2021.5.842923320|
|QML|bbenoist|1.0.0|
|qtvsctools|tonka3000|0.8.3|
|reg|ionutvmi|1.0.3|
|rust|rust-lang|0.7.8|
|shader|slevesque|1.1.5|
|spwn-language-support|Spu7Nix|0.0.3|
|vsc-community-material-theme|Equinusocio|1.4.2|
|vsc-material-theme|Equinusocio|33.2.0|
|vsc-material-theme-icons|equinusocio|1.2.2|
|vscode-editor-macros|jpsnee|0.0.3|
|vscode-glsllint|CADENAS|1.4.0|
|vscode-pylance|ms-python|2021.5.3|
|vscode-qt-for-python|seanwu|1.1.1|
|xml|DotJoshJohnson|2.5.1|;

</details>

**Comment by JoeRobich** [comment]
Both solution files and folder containing project files should be in the "Select project" dropdown.
