### ISSUE TITLE
Can't generate Linux-x64 ver offline extension package

### ISSUE THREAD

**Issue by nanlingyi** [dotnet/vscode-csharp#4569]
## Environment data
VS Code version:1.56.2
C# Extension version:1.23.11

I tried to build a 1.23.11 offline package, only the win-x64 and darwin-x64 packages did it, but the linux-x64 package coming with an error.
here are my logs(only the linux-x64 part):

> Downloading package 'OmniSharp for Linux (x64)' (35596 KB).................... Done!
> Validating download...
> Integrity Check succeeded.
> Installing package 'OmniSharp for Linux (x64)'
> 
> Downloading package '.NET Core Debugger (linux / x64)' (59244 KB).................... Done!
> Validating download...
> Integrity Check succeeded.
> Installing package '.NET Core Debugger (linux / x64)'
> 
> Downloading package 'Razor Language Server (Linux / x64)' (59765 KB).................... Done!
> Installing package 'Razor Language Server (Linux / x64)'
> 
> starting node /home/nanlingyi/Documents/vsix/omnisharp-vscode/node_modules/vsce/out/vsce package -o /home/nanlingyi/Documents/vsix/omnisharp-vscode/csharp.1.23.11-linux-x86_64.vsix
> Executing prepublish script 'npm run vscode:prepublish'...
> 
> > csharp@1.23.11 vscode:prepublish /home/nanlingyi/Documents/vsix/omnisharp-vscode
> > tsc -p ./ && webpack --mode production
> 
> asset extension.js 1.16 MiB [compared for emit] [minimized] (name: main) 2 related assets
> orphan modules 608 KiB [orphan] 156 modules
> runtime modules 670 bytes 3 modules
> modules by path ./node_modules/ 2.42 MiB
>   cacheable modules 2.42 MiB 375 modules
>   modules by path ./node_modules/diagnostic-channel-publishers/dist/src/ sync ^.*//lib// 320 bytes
>     ./node_modules/diagnostic-channel-publishers/dist/src/ sync ^.*\/lib\/Connection$ 160 bytes [built] [code generated]                                                                                                    
>     ./node_modules/diagnostic-channel-publishers/dist/src/ sync ^.*\/lib\/Pool$ 160 bytes [built] [code generated]                                                                                                          
>   ./node_modules/vscode-nls/lib/ sync 160 bytes [built] [code generated]
> modules by path ./src/ 568 KiB 105 modules
> 25 modules
> 
> WARNING in ./node_modules/applicationinsights/out/AutoCollection/NativePerformance.js 49:44-89
> Module not found: Error: Can't resolve 'applicationinsights-native-metrics' in '/home/nanlingyi/Documents/vsix/omnisharp-vscode/node_modules/applicationinsights/out/AutoCollection'
>  @ ./node_modules/applicationinsights/out/applicationinsights.js 12:26-71
>  @ ./node_modules/vscode-extension-telemetry/lib/telemetryReporter.js 11:18-48
>  @ ./src/main.ts 36:37-74
> 
> WARNING in ./node_modules/diagnostic-channel-publishers/dist/src/azure-coretracing.pub.js 24:26-71
> Module not found: Error: Can't resolve '@opentelemetry/tracing' in '/home/nanlingyi/Documents/vsix/omnisharp-vscode/node_modules/diagnostic-channel-publishers/dist/src'
>  @ ./node_modules/diagnostic-channel-publishers/dist/src/index.js 5:15-49
>  @ ./node_modules/applicationinsights/out/AutoCollection/diagnostic-channel/initialization.js 9:21-61
>  @ ./node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js 4:18-64
>  @ ./node_modules/applicationinsights/out/applicationinsights.js 3:32-85
>  @ ./node_modules/vscode-extension-telemetry/lib/telemetryReporter.js 11:18-48
>  @ ./src/main.ts 36:37-74
> 
> WARNING in ./node_modules/vscode-nls/lib/main.js 60:49-88
> Critical dependency: the request of a dependency is an expression
>  @ ./src/features/json/projectJSONContribution.ts 17:12-33
>  @ ./src/features/json/jsonContributions.ts 9:34-70
>  @ ./src/main.ts 37:28-72
> 
> WARNING in ./node_modules/vscode-nls/lib/main.js 215:19-66
> Critical dependency: the request of a dependency is an expression
>  @ ./src/features/json/projectJSONContribution.ts 17:12-33
>  @ ./src/features/json/jsonContributions.ts 9:34-70
>  @ ./src/main.ts 37:28-72
> 
> WARNING in ./node_modules/vscode-nls/lib/main.js 228:23-52
> Critical dependency: the request of a dependency is an expression
>  @ ./src/features/json/projectJSONContribution.ts 17:12-33
>  @ ./src/features/json/jsonContributions.ts 9:34-70
>  @ ./src/main.ts 37:28-72
> 
> WARNING in ./node_modules/vscode-nls/lib/main.js 229:19-72
> Critical dependency: the request of a dependency is an expression
>  @ ./src/features/json/projectJSONContribution.ts 17:12-33
>  @ ./src/features/json/jsonContributions.ts 9:34-70
>  @ ./src/main.ts 37:28-72
> 
> WARNING in ./node_modules/vscode-nls/lib/main.js 338:23-41
> Critical dependency: the request of a dependency is an expression
>  @ ./src/features/json/projectJSONContribution.ts 17:12-33
>  @ ./src/features/json/jsonContributions.ts 9:34-70
>  @ ./src/main.ts 37:28-72
> 
> WARNING in ./node_modules/vscode-nls/lib/main.js 416:23-53
> Critical dependency: the request of a dependency is an expression
>  @ ./src/features/json/projectJSONContribution.ts 17:12-33
>  @ ./src/features/json/jsonContributions.ts 9:34-70
>  @ ./src/main.ts 37:28-72
> 
> 8 warnings have detailed information that is not shown.
> Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.
> 
> webpack 5.34.0 compiled with 8 warnings in 40750 ms
>  ERROR  The following files have the same case insensitive path, which isn't supported by the VSIX format:
>   - extension/.omnisharp/1.37.8/omnisharp/.msbuild/Current/Bin/Workflow.targets
>   - extension/.omnisharp/1.37.8/omnisharp/.msbuild/Current/Bin/Workflow.Targets
>   - extension/.omnisharp/1.37.8/omnisharp/.msbuild/Current/Bin/Workflow.VisualBasic.targets
>   - extension/.omnisharp/1.37.8/omnisharp/.msbuild/Current/Bin/Workflow.VisualBasic.Targets
>

**Comment by JoeRobich** [comment]
A lot has changed with C# extension packaging since this issue was opened. If you are still having problems, please open a new issue.
