### ISSUE TITLE
CS0281 false positive - present in OmniSharp, absent when compiling

### ISSUE THREAD

**Issue by rdewaele** [dotnet/vscode-csharp#4578]
## Issue Description ##

Using signed assemblies, single solution, multiple projects. When exposing the internals from \<project\> to \<project\>-test, OmniSharp reports CS0281 where these internals are used:

> Friend access was granted by '<project>, Version=0.3.3.0, Culture=neutral, PublicKeyToken=null', but the public key of the output assembly ('') does not match that specified by the InternalsVisibleTo attribute in the granting assembly. [\<project\>-tests]

## Steps to Reproduce ##

Expose internals from one project to another, using signed assemblies.

## Expected Behavior ##

No errors reported.

## Actual Behavior ##

Even though the compiler compiles the code entirely warning (and error) free, with all analysis enabled, OmniSharp reports CS0281.

```
  <PropertyGroup>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
  </PropertyGroup>
```

## Logs ##

N/A

### OmniSharp log ###

Starting OmniSharp server at 5/27/2021, 11:36:00 PM
    Target: /home/\<user\>/Projects/\<client\>/\<repository\>/src/\<solution\>.sln

OmniSharp server started.
    Path: /home/\<user\>/.vscode/extensions/ms-dotnettools.csharp-1.23.12/.omnisharp/1.37.10/run
    PID: 1444553

Received response for /quickinfo but could not find request.

### C# log ###

Installing C# dependencies...
Platform: linux, x86_64, name=arch, version=unknown

Downloading package 'OmniSharp for Linux (x64)' (35903 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package 'OmniSharp for Linux (x64)'

Downloading package '.NET Core Debugger (linux / x64)' (59244 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package '.NET Core Debugger (linux / x64)'

Downloading package 'Razor Language Server (Linux / x64)' (60640 KB).................... Done!
Installing package 'Razor Language Server (Linux / x64)'

Finished

## Environment information ##

**VSCode version**: 1.56.2
**C# Extension**: 1.23.12

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.203
 Commit:    b5f47e6c6a

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.203/

Host (useful for support):
  Version: 5.0.6
  Commit:  a8f1277117

.NET SDKs installed:
  5.0.203 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.NETCore.App 5.0.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.23.12|
|dotnet-test-explorer|formulahendry|0.7.5|
|remote-containers|ms-vscode-remote|0.177.2|
|vim|vscodevim|1.20.3|
|vscode-docker|ms-azuretools|1.13.0|
|vscode-nuget-package-manager|jmrog|1.1.6|
|vscode-solution-explorer|fernandoescolar|0.4.3|;

</details>

**Comment by JoeRobich** [comment]
A lot has changed with O# project loading since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
