### ISSUE TITLE
Transient failure in `dotnet restore` causes errors in C# code-behind to incorrectly propagate to Q# code

### ISSUE THREAD

**Issue by cgranade** [dotnet/vscode-csharp#4579]
## Issue Description ##

When working in languages that code generate to C# such as Q#, errors in the generated C# can propagate forward through to the user-facing source code due to `#line` macros. In particular, if the design-time build used by OmniSharp fails to restore NuGet packages for a Q# `*.csproj` file, that can result in missing assembly errors in code-behind that appear as though they were Q# errors:

![image](https://user-images.githubusercontent.com/31516/120054450-e0ce5780-bfe4-11eb-80bf-5663b0f5cfe3.png)

![image](https://user-images.githubusercontent.com/31516/120054448-dad87680-bfe4-11eb-8bdf-e0786de067d1.png)

In this example, re-running `dotnet restore` manually on the affected project temporarily resolved the issue.

## Steps to Reproduce ##

The problem above occurs stochastically, such that a reliable reproduction of the error is not yet known.

## Expected Behavior ##

A failure to restore NuGet packages would not cause errors to appear in Q# code.

## Actual Behavior ##

See screenshots above.

### OmniSharp log ###

<details>
Starting OmniSharp server at 5/28/2021, 4:34:48 PM
    Target: c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry.sln

OmniSharp server started.
    Path: c:\Users\cgran\.vscode\extensions\ms-dotnettools.csharp-1.23.12\.omnisharp\1.37.10\OmniSharp.exe
    PID: 44976

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Enterprise 2019 16.9.31025.194 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin"
            2: StandAlone 16.11.0 - "c:\Users\cgran\.vscode\extensions\ms-dotnettools.csharp-1.23.12\.omnisharp\1.37.10\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Enterprise 2019 16.9.31025.194 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\cgran\source\repos\microsoft\quantumlibraries'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\src\Runtime\Runtime.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\src\DataModel\DataModel.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\tests\SystemTests\SystemTests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\tests\ChemistryTests\QSharpTests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Standard\src\Standard.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\tests\SamplesTests\SamplesTests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\src\Metapackage\Metapackage.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\src\Tools\Tools.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\cgran\source\repos\microsoft\quantumlibraries'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\cgran\source\repos\microsoft\quantumlibraries' on host 39616.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\src\Runtime\Runtime.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\src\Runtime\Runtime.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\src\Runtime\Runtime.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\src\DataModel\DataModel.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\src\DataModel\DataModel.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\src\DataModel\DataModel.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\tests\SystemTests\SystemTests.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\tests\SystemTests\SystemTests.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\tests\SystemTests\SystemTests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\tests\ChemistryTests\QSharpTests.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\tests\ChemistryTests\QSharpTests.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\tests\ChemistryTests\QSharpTests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\cgran\source\repos\microsoft\quantumlibraries\Standard\src\Standard.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Standard\src\Standard.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Standard\src\Standard.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\tests\SamplesTests\SamplesTests.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\tests\SamplesTests\SamplesTests.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\tests\SamplesTests\SamplesTests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\src\Metapackage\Metapackage.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\src\Metapackage\Metapackage.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\src\Metapackage\Metapackage.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\src\Tools\Tools.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\src\Tools\Tools.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\src\Tools\Tools.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Runtime
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: DataModel
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: SystemTests
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: QSharpTests
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Standard
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: SamplesTests
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Metapackage
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Tools
Received response for /quickinfo but could not find request.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\src\Tools\Tools.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\src\Metapackage\Metapackage.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\src\Runtime\Runtime.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\src\Tools\Tools.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Standard\src\Standard.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\src\Metapackage\Metapackage.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\src\DataModel\DataModel.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\tests\SamplesTests\SamplesTests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\src\DataModel\DataModel.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\tests\ChemistryTests\QSharpTests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\tests\SystemTests\SystemTests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\tests\SamplesTests\SamplesTests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Standard\src\Standard.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\tests\ChemistryTests\QSharpTests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\src\Runtime\Runtime.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\tests\SystemTests\SystemTests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\src\Tools\Tools.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\src\Tools\Tools.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\src\Metapackage\Metapackage.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\src\Metapackage\Metapackage.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\src\Runtime\Runtime.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\src\Runtime\Runtime.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\cgran\source\repos\microsoft\quantumlibraries\Standard\src\Standard.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Standard\src\Standard.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\src\DataModel\DataModel.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\src\DataModel\DataModel.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\tests\SamplesTests\SamplesTests.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\tests\SamplesTests\SamplesTests.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\tests\ChemistryTests\QSharpTests.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\tests\ChemistryTests\QSharpTests.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\tests\SystemTests\SystemTests.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\cgran\source\repos\microsoft\quantumlibraries\Chemistry\tests\SystemTests\SystemTests.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Tools
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Metapackage
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Runtime
[info]: OmniSharp.OmniSharpWorkspace
        Adding analyzer reference: C:\Users\cgran\.nuget\packages\microsoft.codeanalysis.analyzers\3.0.0\analyzers\dotnet\cs\Microsoft.CodeAnalysis.Analyzers.dll
[info]: OmniSharp.OmniSharpWorkspace
        Adding analyzer reference: C:\Users\cgran\.nuget\packages\microsoft.codeanalysis.analyzers\3.0.0\analyzers\dotnet\cs\Microsoft.CodeAnalysis.CSharp.Analyzers.dll
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Standard
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: DataModel
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: SamplesTests
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: QSharpTests
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: SystemTests
Received response for /v2/codestructure but could not find request.
Received response for /findusages but could not find request.
Received response for /findusages but could not find request.
Received response for /findusages but could not find request.
</details>

### C# log ###

(Log was blank.)

## Environment information ##

**VSCode version**: 1.56.2
**C# Extension**: 1.23.12

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.1.21103.13
 Commit:    b8a03527b2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.1.21103.13\

Host (useful for support):
  Version: 6.0.0-preview.1.21102.12
  Commit:  9b2776d481

.NET SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.200 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.1.21103.13 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.1.21103.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.1.21102.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.1.21103.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|asciidoctor-vscode|asciidoctor|2.8.9|
|asciidoctor-vscode|joaompinto|2.8.0|
|azure-account|ms-vscode|0.9.8|
|better-toml|bungcip|0.3.2|
|cmake|twxs|0.0.17|
|cmake-tools|ms-vscode|1.7.3|
|code-spell-checker|streetsidesoftware|1.10.2|
|codespaces|GitHub|0.10.4|
|codetour|vsls-contrib|0.0.53|
|cpptools|ms-vscode|1.4.0|
|csharp|ms-dotnettools|1.23.12|
|docs-article-templates|docsmsft|0.2.11|
|docs-authoring-pack|docsmsft|0.1.13|
|docs-build|docsmsft|0.3.4|
|docs-images|docsmsft|0.0.9|
|docs-linting|docsmsft|0.0.7|
|docs-markdown|docsmsft|0.2.93|
|docs-metadata|docsmsft|1.0.6|
|docs-preview|docsmsft|0.3.57|
|docs-scaffolding|docsmsft|0.0.7|
|docs-view|bierner|0.0.9|
|docs-yaml|docsmsft|0.2.6|
|EditorConfig|EditorConfig|0.16.4|
|gitignore|codezombiech|0.7.0|
|gitlens|eamodio|11.4.1|
|Ionide-fsharp|Ionide|5.5.5|
|jupyter|ms-toolsai|2021.6.832593372|
|latex-workshop|James-Yu|8.18.0|
|LinkCheckMD|blackmist|0.3.1|
|llvm|RReverser|0.1.1|
|mono-debug|ms-vscode|0.16.2|
|powershell|ms-vscode|2021.2.2|
|python|ms-python|2021.5.842923320|
|quantum-devkit-vscode|quantum|0.17.2105143879|
|remote-containers|ms-vscode-remote|0.177.2|
|remote-ssh|ms-vscode-remote|0.65.4|
|remote-ssh-edit|ms-vscode-remote|0.65.6|
|remote-wsl|ms-vscode-remote|0.56.3|
|rust-analyzer|matklad|0.3.598|
|todo-tree|Gruntfuggly|0.0.213|
|vscode-azurefunctions|ms-azuretools|1.4.0|
|vscode-azureresourcegroups|ms-azuretools|0.4.0|
|vscode-commons|redhat|0.0.6|
|vscode-docker|ms-azuretools|1.13.0|
|vscode-github-issue-notebooks|ms-vscode|0.0.96|
|vscode-markdownlint|DavidAnson|0.41.0|
|vscode-pull-request-github|GitHub|0.26.0|
|vscode-pylance|ms-python|2021.5.4|
|vscode-remote-extensionpack|ms-vscode-remote|0.21.0|
|vscode-streamdeck|nicollasr|4.1.5|
|vscode-xml|redhat|0.16.1|
|vscode-yaml|redhat|0.19.2|
|vsliveshare|ms-vsliveshare|1.0.4272|;

</details>

**Comment by JoeRobich** [comment]
A lot has changed with O# code analysis since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
