### ISSUE TITLE
C# extension not detecting 

### ISSUE THREAD

**Issue by Shiftythedev** [dotnet/vscode-csharp#4584]
Issue Type: <b>Bug</b>

The c# extension is not getting recognised. I have tried reinstalling.

Extension version: 1.23.12
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.80GB (1.88GB free)|
|Process Argv|--crash-reporter-id 6649777c-de81-455a-bcfc-f53a41972a38|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
bridgeflight:30302069
vscod805cf:30301675

```

</details>

**Comment by R-Code-Studios** [comment]
Excuse me are u getting this error cause I am getting this error

[Running] scriptcs "f:\RayyanPrograms\c++\test.cs"
'scriptcs' is not recognized as an internal or external command,
operable program or batch file.

[Done] exited with code=1 in 0.116 seconds

i even opened an issue here https://github.com/OmniSharp/omnisharp-vscode/issues/4585

**Comment by Shiftythedev** [comment]
> Excuse me are u getting this error cause I am getting this error
> 
> [Running] scriptcs "f:\RayyanPrograms\c++\test.cs"
> 'scriptcs' is not recognized as an internal or external command,
> operable program or batch file.
> 
> [Done] exited with code=1 in 0.116 seconds
> 
> i even opened an issue here https://github.com/OmniSharp/omnisharp-vscode/issues/4585

Nope. Its runs alright until I add a specific command like time.deltatime

I moved to visual studio 2019 
I would suggest you the same:)

**Comment by lucvtzel** [comment]
I got the same message. The issue was not from the *omnisharp-vscode* extension but from the *vscode-runner* extension which uses the *scriptcs* executable to run *C#* code. I solved the issue by installing *[scriptcs](http://scriptcs.net/)* 
via *chocolatey* from an administration console (under Windows as the operating system):  

cinst scriptcs
