### ISSUE TITLE
Huge memory use

### ISSUE THREAD

**Issue by Sanan07** [dotnet/vscode-csharp#4592]
VsCode Version: 1.57.0-insider (user setup)
Omnisharp version : v1.23.12

When I open C# project in VS Code, memory usage of Omnisharp in increasing to very high level
![OmniSharp](https://user-images.githubusercontent.com/8465726/120555555-87f32a80-c3fb-11eb-934d-34a3a3bc5598.PNG)

How can I fix this? Should I disable something?

**Comment by nohwnd** [comment]
@Sanan07 is it a big project? When you open the same project in VS is the memory usage much lower?

**Comment by Sanan07** [comment]
Project is VS itself. In VS it uses around 1.5 GB, but in OmniSharp it increasing around 3GB memory use.

**Comment by lixaotec** [comment]
+1

**Comment by JoeRobich** [comment]
A lot has changed with O# since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
