### ISSUE TITLE
Tooltips next to the suggestion list not shown anymore

### ISSUE THREAD

**Issue by sschultze** [dotnet/vscode-csharp#4606]
## Issue Description ##

OmniSharp doesn't show tooltips (i.e. property or method information) anymore next to the suggestion list.

## Steps to Reproduce ##

* Create a new project (`dotnet new console`)
* Open VSCode on macOS x64 (`code .`)
* Create a new line after `Console.WriteLine("Hello World!");`
* Type: `Console.`
* Go through the suggestion list (with arrow keys)

## Expected Behavior ##

A documentation tooltip should be shown for the focused suggestion, e.g. Console.Beep. I'm like 90% sure that it did before Visual Studio Code auto-updated itself to the latest version.

## Actual Behavior ##

No documentation tooltip is shown.

### OmniSharp log ###
<details>Starting OmniSharp server at 6/11/2021, 5:28:21 PM
    Target: /Users/stefan/nobackup/omnitest

OmniSharp server started.
    Path: /Users/stefan/.vscode/extensions/ms-dotnettools.csharp-1.23.12/.omnisharp/1.37.10/run
    PID: 30980

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 11.4 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.11.0 - "/Users/stefan/.vscode/extensions/ms-dotnettools.csharp-1.23.12/.omnisharp/1.37.10/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/Users/stefan/.vscode/extensions/ms-dotnettools.csharp-1.23.12/.omnisharp/1.37.10/omnisharp/.msbuild/Current/Bin/MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.11.0 - "/Users/stefan/.vscode/extensions/ms-dotnettools.csharp-1.23.12/.omnisharp/1.37.10/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            MSBuildToolsPath = /Users/stefan/.vscode/extensions/ms-dotnettools.csharp-1.23.12/.omnisharp/1.37.10/omnisharp/.msbuild/Current/Bin
            CscToolPath = /Users/stefan/.vscode/extensions/ms-dotnettools.csharp-1.23.12/.omnisharp/1.37.10/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /Users/stefan/.vscode/extensions/ms-dotnettools.csharp-1.23.12/.omnisharp/1.37.10/omnisharp/.msbuild
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/stefan/nobackup/omnitest'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/Users/stefan/nobackup/omnitest'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/stefan/nobackup/omnitest/omnitest.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/stefan/nobackup/omnitest'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/stefan/nobackup/omnitest' on host 30948.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/stefan/nobackup/omnitest/omnitest.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/stefan/nobackup/omnitest/omnitest.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/stefan/nobackup/omnitest/omnitest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: omnitest
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/stefan/nobackup/omnitest/omnitest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/stefan/nobackup/omnitest/omnitest.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/stefan/nobackup/omnitest/omnitest.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/stefan/nobackup/omnitest/omnitest.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: omnitest
Received response for /v2/getcodeactions but could not find request.
Received response for /completion/resolve but could not find request.
Received response for /v2/getcodeactions but could not find request.
</details>

## Environment information ##

**VSCode version**: 1.57.0
**C# Extension**: 1.23.12

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.202
 Commit:    db7cc87d51

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.202/

Host (useful for support):
  Version: 6.0.0-preview.4.21253.7
  Commit:  bfd6048a60

.NET SDKs installed:
  5.0.202 [/usr/local/share/dotnet/sdk]
  6.0.100-preview.4.21255.9 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.4.21253.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.4.21253.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.23.12|
|debugger-for-chrome|msjsdiag|4.12.12|
|EditorConfig|EditorConfig|0.16.4|
|hexeditor|ms-vscode|1.7.0|
|ilspy-vscode|icsharpcode|0.10.0|
|markdown-toc|AlanWalk|1.5.6|
|prettier-vscode|esbenp|6.4.0|
|remote-containers|ms-vscode-remote|0.183.0|
|remote-ssh|ms-vscode-remote|0.65.6|
|remote-ssh-edit|ms-vscode-remote|0.65.6|
|remote-wsl|ms-vscode-remote|0.56.4|
|rest-client|humao|0.24.5|
|rewrap|stkb|1.14.0|
|snapshot-tools|asvetliakov|0.4.0|
|toggle|rebornix|0.0.2|
|vscode-docker|ms-azuretools|1.13.0|
|vscode-eslint|dbaeumer|2.1.22|
|vscode-remote-extensionpack|ms-vscode-remote|0.21.0|
|vscode-typescript-tslint-plugin|ms-vscode|1.3.3|;

</details>

**Comment by JoeRobich** [comment]
If the details tooltip has been dismissed you can reopen it by clicking on the "Read more" arrow in the completion list.
![Image](https://github.com/user-attachments/assets/1747a710-745f-472b-ad00-c2cc7ac3dbf1)

**Comment by sschultze** [comment]
There is no arrow or "Read More" tooltip.

I think I reinstalled macOS and VSCode multiple times in the meantime (since 2021), I have the latest versions of everything installed, and I still see no documentation tooltip.

**Comment by JoeRobich** [comment]
I had to hover over the selected item with my mouse to get it to show. You can also get it to show by pressing `ctrl+space` when the completion list is up.

**Comment by sschultze** [comment]
I don't get the tooltip when I hover over the selected item with my mouse. I also don't get it by pressing `ctrl+space`(or any other modifier key together with space).

I do however get the tooltip if I hover over a symbol in the code, so the required information is definitely there.

**Comment by JoeRobich** [comment]
@sschultze Are you using O# still or have you moved to Roslyn LSP? 
![Image](https://github.com/user-attachments/assets/28b6ea24-692d-4c8f-b720-6b8f53b56c7d)

If you are still using O#, could you share the OmniSharp log from the Output pane? Otherwise, can you share the C# log from the Output pane?

**Comment by sschultze** [comment]
@JoeRobich I had this option turned off. For testing, I just turned it on and restarted VSCode, the tooltip still doesn't appear. Have turned the option off again.

This is the C# output (redacted directory and file names a bit - xxx):

```
2024-11-14 22:45:04.510 [info] Using dotnet configured on PATH
2024-11-14 22:45:04.511 [info] Dotnet path: /usr/local/share/dotnet/dotnet
2024-11-14 22:45:04.511 [info] Activating C# standalone...
2024-11-14 22:45:04.885 [info] [stdout] {"pipeName":"/var/folders/cr/q_1nv1dx77g_d89rn0wnvqz00000gn/T/514a5a2a.sock"}

2024-11-14 22:45:04.889 [info] received named pipe information from server
2024-11-14 22:45:04.889 [info] client has connected to server
2024-11-14 22:45:04.929 [info] [Info  - 10:45:04 PM] [Program] Language server initialized
2024-11-14 22:45:05.107 [info] [Info  - 10:45:05 PM] [LanguageServerProjectSystem] Loading /Users/xxx/xxx/xxx/xxx.sln...
2024-11-14 22:45:06.270 [info] [Info  - 10:45:06 PM] [LanguageServerProjectSystem] Successfully completed load of /Users/xxx/xxx/xxx/xxx.csproj
2024-11-14 22:45:06.270 [info] [Info  - 10:45:06 PM] [LanguageServerProjectSystem] Successfully completed load of /Users/xxx/xxx/xxx/xxx.csproj
2024-11-14 22:45:06.270 [info] [Info  - 10:45:06 PM] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:00.8950618
```

**Comment by JoeRobich** [comment]
Seeing as how the projects loaded successfully and you are able to see quick info when hovering over these methods, I am at a loss for what is happening on your end. Screenshots or a screen capture may help us figure out what is going on.

This is the best documentation I could find on how you should be able to show the quick info for suggestion items. https://code.visualstudio.com/docs/editor/intellisense#_key-bindings:~:text=you%20can%20see%20quick%20info%20for%20each%20method%20by%20either%20pressing%20%E2%8C%83Space%20or%20clicking%20the%20info%20icon.

> As provided by the language service, you can see quick info for each method by either pressing ⌃Space or clicking the info icon. The accompanying documentation for the method will now expand to the side. The expanded documentation will stay so and will update as you navigate the list. You can close this by pressing ⌃Space again or by clicking on the close icon.
> ![](https://code.visualstudio.com/assets/docs/editor/intellisense/intellisense_docs.gif)
