### ISSUE TITLE
obj folders showing errors

### ISSUE THREAD

**Issue by iamsaavya** [dotnet/vscode-csharp#4609]
<img src="https://user-images.githubusercontent.com/73835838/121782350-b1177600-cbc6-11eb-8c8f-53d9c4fbbf2d.png"/>

Yea, these debug folders would not let me live, C# extension automatically adds these debug folders and then this messes up my entire project. How to fix this?

**Comment by JoeRobich** [comment]
A lot has changed with O# code analysis since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
