### ISSUE TITLE
Suggestion :: add <summary xml:lang="xx"> culture support

### ISSUE THREAD

**Issue by a-gorozhankin** [dotnet/vscode-csharp#4630]
It isn't an issue, but a suggestion for multilanguage use.
Can you add omnisharp.Culture option in vscode extension with format "en-En" or "ru-RU" and add a capability to parse it into your omnisharp-server?

something like
``` cs
///<summary>
/// This is Description
///<summary/>
///<summary xml:lang="ru-RU">
/// Это - описание
///<summary/>
public class Test {}
```
If you will leave null in omnisharp.Culture hover will show "This is Description". Otherwise, if you'll set omnisharp.Culture = "ru-RU" hover will show "Это - описание"

And you will make it for other tags, such as param and other - it would be awesome!

**Comment by JoeRobich** [comment]
DocComments are part of the C# language. You could work up a proposal and share it on csharplang for consideration. See https://github.com/dotnet/csharplang?tab=readme-ov-file#proposals
