### ISSUE TITLE
OmniSharp keeps downloading and doesn't highligh errors 

### ISSUE THREAD

**Issue by Eltoney** [dotnet/vscode-csharp#4636]
## Environment data
`dotnet --info` output:
NET SDK (reflecting any global.json):
 Version:   5.0.301
 Commit:    ef17233f86

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /snap/dotnet-sdk/129/sdk/5.0.301/

Host (useful for support):
  Version: 5.0.7
  Commit:  556582d964

.NET SDKs installed:
  5.0.301 [/snap/dotnet-sdk/129/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.7 [/snap/dotnet-sdk/129/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.7 [/snap/dotnet-sdk/129/shared/Microsoft.NETCore.App]

VS Code version:
1.57.1
507ce72a4466fbb27b715c3722558bb15afa9f48
x64

C# Extension version:
latest
## Steps to reproduce
just reopening the program

## Expected  behavior
show errors in the cs file

## Actual behavior
whenever i reopen the program , the extension keeps downloading , and when i press on it for info it says command not found
also when i write any code with errors (like not typing semicolon) the program doesn't highlight the error or show it in the problems section

**Comment by JoeRobich** [comment]
A lot has changed with how the C# extension packages and acquires dependencies since this issue was opened. If you are still having problems, please open a new issue.
