### ISSUE TITLE
Problems do not update properly

### ISSUE THREAD

**Issue by Mailaender** [dotnet/vscode-csharp#4656]
Issue Type: <b>Bug</b> (regression maybe)

Since recent updates highlights of compile problems are sluggish and show old states. It will only silence when the line is updated. After checking out changes it in git this can escalate to the whole file showing weird errors that do not match the contents on the line.

![image](https://user-images.githubusercontent.com/756669/125648593-9f81b7dd-5233-4dac-a746-91d00e6ab342.png)
(none of the right underline is showing a real error)

Extension version: 1.23.13
VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:53:55.113Z)
OS version: Linux x64 5.3.18-59.10-default
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 3999)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|10, 10, 10|
|Memory (System)|15.59GB (2.58GB free)|
|Process Argv|--unity-launch /home/matthias/Entwicklung/OpenRA --crash-reporter-id 91f4602e-d448-4de4-b490-5d94a93272b3|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma5|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805cf:30301675
pythonvspyt200cf:30331938
vscextlang:30333561
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by JoeRobich** [comment]
A lot has changed with O# code analysis since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
