### ISSUE TITLE
No documentation on testRunSettings

### ISSUE THREAD

**Issue by jrmeland** [dotnet/vscode-csharp#4662]
## Issue Description ##
I am trying to configure the runtime context when clicking on "Run Test" code lense. Really I am just trying to make sure an ENV variable is set. I couldn't find any definitive documentation on it so I went digging through the code. I found [this line](https://github.com/OmniSharp/omnisharp-vscode/blob/5e48576134ef9b16226dcd9db400088f99e8a7de/src/features/dotnetTest.ts#L175) which pulls `testRunSettings` configuration but I can't find any record of how it is used. A search on GitHub only shows a [couple](https://github.com/search?l=JSON&q=testRunSettings&type=Code) of hits. The values e.g. `./insideDocker.runSettings` & `Pqsql.runsettings` look like they could be files but I don't see them in those repos.

Is `testRunSettings` something we can use? Is there some stupid simple way to know how "Run Test" works that I am missing? Any info is appreciated!

## Steps to Reproduce ##
Google search for `testRunSettings` and nada.

## Expected Behavior ##
Some explanation on how to configure the context `Run Test` is executed in exists.

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.57.1
**C# Extension**: 1.23.13

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.102/

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  3.1.405 [/usr/share/dotnet/sdk]
  5.0.102 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.11 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|change-case|wmaurer|1.0.0|
|code-spell-checker|streetsidesoftware|1.10.2|
|csharp|ms-dotnettools|1.23.13|
|csharp2ts|rafaelsalguero|0.0.26|
|csharpextensions|jchannon|1.3.1|
|docomment|k--kato|0.1.20|
|fix-json|oliversturm|0.1.2|
|gitlab-workflow|GitLab|3.26.0|
|gitlens|eamodio|11.6.0|
|html-slim-scss-css-class-completion|gencer|1.7.8|
|jupyter|ms-toolsai|2021.6.999662501|
|markdown-mermaid|bierner|1.10.0|
|ng-template|Angular|12.1.2|
|nodejs-extension-pack|waderyan|0.1.9|
|npm-intellisense|christian-kohler|1.3.1|
|path-intellisense|christian-kohler|2.3.0|
|pdf|tomoki1207|1.1.0|
|prettier-vscode|esbenp|8.0.1|
|python|ms-python|2021.6.944021595|
|search-editor-apply-changes|jakearl|0.1.1|
|search-node-modules|jasonnutter|1.3.0|
|shell-launcher|Tyriar|0.4.1|
|typescript-hero|rbbit|3.0.0|
|vscode-docker|ms-azuretools|1.14.0|
|vscode-eslint|dbaeumer|2.1.23|
|vscode-extension-auto-import|NuclleaR|1.4.3|
|vscode-markdownlint|DavidAnson|0.42.1|
|vscode-mermaid-preview|vstirbu|1.6.2|
|vscode-npm-script|eg2|0.3.22|
|vscode-nuget-package-manager|jmrog|1.1.6|
|vscode-pylance|ms-python|2021.7.4|
|vscode-typescript-tslint-plugin|ms-vscode|1.3.3|;

</details>

**Comment by devklick** [comment]
@jrmeland I think this should help you out: [Configure unit tests by using a .runsettings file](https://learn.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2022#example-runsettings-file). It's written for Visual Studio, but it uses `.runsettings` file which I expect this extension handles the file in the same way. 

There's a [section](https://learn.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2022#specify-environment-variables-in-the-runsettings-file) that covers setting environment variables:

```xml
<?xml version="1.0" encoding="utf-8"?>
<!-- File name extension must be .runsettings -->
<RunSettings>
  <RunConfiguration>
    <EnvironmentVariables>
      <!-- List of environment variables we want to set-->
      <DOTNET_ROOT>C:\ProgramFiles\dotnet</DOTNET_ROOT>
      <SDK_PATH>C:\Codebase\Sdk</SDK_PATH>
    </EnvironmentVariables>
  </RunConfiguration>
</RunSettings>
```

Even if this gives you the information you need, I think it would still be useful for the readme in this repo to point to some docs around how to configure, even if it's just linking to this same page.

**Comment by JoeRobich** [comment]
closing as answered.
