### ISSUE TITLE
Terrible situation In vs code, c# format does not work

### ISSUE THREAD

**Issue by seal2461** [dotnet/vscode-csharp#4665]
it's my OmniSharp Log
I don't understand why c# format does not work

Starting OmniSharp server at 2021/7/17 下午6:15:54
    Target: c:\Unity\New Unity Project

OmniSharp server started.
    Path: c:\Users\USER\.vscode\extensions\ms-dotnettools.csharp-1.23.13\.omnisharp\1.37.12\OmniSharp.exe
    PID: 9448

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 17.0.0 - "c:\Users\USER\.vscode\extensions\ms-dotnettools.csharp-1.23.13\.omnisharp\1.37.12\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to 'c:\Users\USER\.vscode\extensions\ms-dotnettools.csharp-1.23.13\.omnisharp\1.37.12\.msbuild\Current\Bin\MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 17.0.0 - "c:\Users\USER\.vscode\extensions\ms-dotnettools.csharp-1.23.13\.omnisharp\1.37.12\.msbuild\Current\Bin"
            CscToolExe = csc.exe
            CscToolPath = c:\Users\USER\.vscode\extensions\ms-dotnettools.csharp-1.23.13\.omnisharp\1.37.12\.msbuild\Current\Bin\Roslyn
            MSBuildExtensionsPath = c:\Users\USER\.vscode\extensions\ms-dotnettools.csharp-1.23.13\.omnisharp\1.37.12\.msbuild
            MSBuildToolsPath = c:\Users\USER\.vscode\extensions\ms-dotnettools.csharp-1.23.13\.omnisharp\1.37.12\.msbuild\Current\Bin
[fail]: OmniSharp.Services.AssemblyLoader
        Failed to load assembly: Microsoft.CodeAnalysis.CSharp.Features, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
System.BadImageFormatException: 無法載入檔案或組件 'Microsoft.CodeAnalysis.CSharp.Features, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 或其相依性的其中之一。 檔案或目錄損毀而且無法讀取。 (發生例外狀況於 HRESULT: 0x80070570)
檔案名稱: 'Microsoft.CodeAnalysis.CSharp.Features, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   於 System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   於 System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   於 System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   於 OmniSharp.Services.AssemblyLoader.Load(AssemblyName name) 於 D:\a\1\s\src\OmniSharp.Host\Services\AssemblyLoader.cs: 行 27

警告: 組件繫結記錄切換為 OFF。
若要記錄組件繫結失敗，請將登錄值 [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) 設為 1。
注意: 與組件繫結失敗記錄相關的效能會有部分負面影響。
若要關閉此功能，請移除登錄值 [HKLM\Software\Microsoft\Fusion!EnableLog]。

System.NullReferenceException: 並未將物件參考設定為物件的執行個體。
   於 OmniSharp.HostServicesAggregator..ctor(IEnumerable`1 hostServicesProviders, ILoggerFactory loggerFactory) 於 D:\a\1\s\src\OmniSharp.Roslyn\HostServicesAggregator.cs: 行 50
   於 lambda_method(Closure , LifetimeContext , CompositionOperation )
   於 lambda_method(Closure , LifetimeContext , CompositionOperation )
   於 System.Composition.TypedParts.ActivationFeatures.DisposalFeature.<>c__DisplayClass0_0.<RewriteActivator>b__0(LifetimeContext c, CompositionOperation o)
   於 System.Composition.Hosting.Core.LifetimeContext.GetOrCreate(Int32 sharingId, CompositionOperation operation, CompositeActivator creator)
   於 System.Composition.Hosting.Core.CompositionOperation.Run(LifetimeContext outermostLifetimeContext, CompositeActivator compositionRootActivator)
   於 System.Composition.Hosting.Core.LifetimeContext.TryGetExport(CompositionContract contract, Object& export)
   於 System.Composition.CompositionContext.GetExport(CompositionContract contract)
   於 System.Composition.CompositionContext.GetExport[TExport](String contractName)
   於 OmniSharp.Stdio.Host.Initialize() 於 D:\a\1\s\src\OmniSharp.Stdio\Host.cs: 行 58
   於 OmniSharp.Stdio.Host..ctor(TextReader input, ISharedTextWriter writer, IOmniSharpEnvironment environment, IServiceProvider serviceProvider, CompositionHostBuilder compositionHostBuilder, ILoggerFactory loggerFactory, CancellationTokenSource cancellationTokenSource) 於 D:\a\1\s\src\OmniSharp.Stdio\Host.cs: 行 52
   於 OmniSharp.Stdio.Driver.Program.<>c__DisplayClass0_1.<Main>b__1() 於 D:\a\1\s\src\OmniSharp.Stdio.Driver\Program.cs: 行 56
   於 OmniSharp.HostHelpers.Start(Func`1 action) 於 D:\a\1\s\src\OmniSharp.Host\HostHelpers.cs: 行 29
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).

**Comment by xwiggen** [comment]
did you try Ctrl-Shift-P OmniSharp: Restart Omnisharp ?

**Comment by JoeRobich** [comment]
It is recommended to use the Unity extension for VS Code.
