### ISSUE TITLE
name suggestions for public properties incomplete

### ISSUE THREAD

**Issue by burtonrodman** [dotnet/vscode-csharp#4682]
## Issue Description ##
i could be wrong, but I could swear this worked in previous versions.  typing a public property declaration no long suggests the pascal cased name.

## Steps to Reproduce ##
in a class, start typing a property declaration like ```public Article ar```
the suggestions do NOT include `Article` as a property name suggestion.

## Expected Behavior ##
suggestions include the typical PascalCase name suggestion that is standard for public properties.
 
## Actual Behavior ##
![image](https://user-images.githubusercontent.com/7658657/127085093-dfb95c59-0c50-4daf-8661-c7e5d555504e.png)

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.58.2
**C# Extension**: 1.23.13

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.5.21302.13
 Commit:    d6380bcae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.5.21302.13\

Host (useful for support):
  Version: 6.0.0-preview.5.21301.5
  Commit:  ec3e0b276b

.NET SDKs installed:
  3.1.411 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]
  5.0.200-preview.20601.7 [C:\Program Files\dotnet\sdk]
  5.0.400-preview.21277.10 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.5.21302.13 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.5.21301.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.5.21301.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.5.21301.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|auto-rename-tag|formulahendry|0.1.7|
|azure-account|ms-vscode|0.9.8|
|blazorwasm-companion|ms-dotnettools|1.1.0|
|code-spell-checker|streetsidesoftware|1.10.2|
|csharp|ms-dotnettools|1.23.13|
|debugger-for-chrome|msjsdiag|4.12.12|
|debugger-for-edge|msjsdiag|1.0.15|
|dotnet-test-explorer|formulahendry|0.7.6|
|EditorConfig|EditorConfig|0.16.4|
|gitlens|eamodio|11.6.0|
|libman|adrianwilczynski|1.0.1|
|powershell|ms-vscode|2021.6.2|
|prettier-vscode|esbenp|8.1.0|
|react-native-react-redux|EQuimper|2.0.6|
|react-native-snippet|jundat95|0.5.6|
|remote-containers|ms-vscode-remote|0.187.1|
|remote-ssh|ms-vscode-remote|0.65.7|
|remote-ssh-edit|ms-vscode-remote|0.65.7|
|remote-wsl|ms-vscode-remote|0.58.2|
|vetur|octref|0.34.1|
|vscode-azureresourcegroups|ms-azuretools|0.4.0|
|vscode-azurestorage|ms-azuretools|0.12.1|
|vscode-docker|ms-azuretools|1.15.0|
|vscode-dotnet-runtime|ms-dotnettools|1.2.0|
|vscode-edge-devtools|ms-edgedevtools|1.2.0|
|vscode-eslint|dbaeumer|2.1.23|
|vscode-icons|vscode-icons-team|11.5.0|
|vscode-jest|Orta|4.0.3|
|vscode-nuget-gallery|patcx|0.0.24|
|vscode-nuget-package-manager|jmrog|1.1.6|
|vscode-react-native|msjsdiag|1.5.2|
|vscode-sqlite|alexcvzz|0.13.0|
|vsliveshare|ms-vsliveshare|1.0.4583|;

</details>

**Comment by JoeRobich** [comment]
Could not reproduce with the current release. Name suggestions should follow the configured naming rules from your .editorconfig.

**Comment by burtonrodman** [comment]
also can no longer reproduce.  thanks!
