### ISSUE TITLE
VS Code using resouces when Visual Studio is building

### ISSUE THREAD

**Issue by Sti2nd** [dotnet/vscode-csharp#4683]
## Issue Description ##

I have both Visual Studio and VS Code open on the same project as I like VS Code best but Microsoft still wants VS Code C# functionality to be "Lightweight development tools for .NET Core"... forcing me to use VS for some functionality. This has been working fine up until recently. Recently I noticed building in Visual Studio took way longer. I found that VS Code that I had open in the background used most of the resources and that it was spawning more than 500 .NET Host processes. My computer froze, so in the image below there are only 253 processes from VS Code.

## Steps to Reproduce ##

I can't reproduce it, it just happened after a while of using both VS Code and Visual Studio.

## Expected Behavior ##

Able to have VS Code open while using Visual Studio without VS Code using much resources.

## Actual Behavior ##

VS Code spawns many many processes.
![image](https://user-images.githubusercontent.com/6373430/127162753-b10dce18-4753-4f9f-9a83-91dfac101e98.png)

## Logs ##

Unfortunately I closed VS Code before I found out about the "report an issue" command, so I don't have any logs.

## Environment information ##

**VSCode version**: 1.58.2
**C# Extension**: 1.23.13

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.302
 Commit:    c005824e35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.302\

Host (useful for support):
  Version: 5.0.8
  Commit:  35964c9215

.NET SDKs installed:
  5.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|aadb2c|AzureADB2CTools|1.3.0|
|autoimport|steoates|1.5.4|
|azure-account|ms-vscode|0.9.8|
|azurite|Azurite|3.14.0|
|Bookmarks|alefragnani|13.1.0|
|codesnap|adpyke|1.3.4|
|color-highlight|naumovs|2.4.0|
|csharp|ms-dotnettools|1.23.13|
|debugger-for-chrome|msjsdiag|4.12.12|
|docomment|k--kato|0.1.20|
|EditorConfig|EditorConfig|0.16.4|
|es6-css-minify|olback|3.3.2|
|forward-slasher|forward-slasher|0.1.0|
|github-vscode-theme|GitHub|4.1.1|
|jupyter|ms-toolsai|2021.8.1054968649|
|markdown-all-in-one|yzhang|3.4.0|
|mssql|ms-mssql|1.10.1|
|path-intellisense|christian-kohler|2.4.0|
|powershell|ms-vscode|2021.6.2|
|prettier-vscode|esbenp|8.1.0|
|python|ms-python|2021.7.1060902895|
|remote-containers|ms-vscode-remote|0.187.1|
|remote-ssh|ms-vscode-remote|0.65.7|
|remote-ssh-edit|ms-vscode-remote|0.65.7|
|remote-wsl|ms-vscode-remote|0.58.2|
|split-lines|brainfit|1.0.2|
|stackoverflow-search|Alexey-Strakh|1.2.0|
|tempotimetracking|tempo|1.0.0|
|test-adapter-converter|ms-vscode|0.0.13|
|todo-tree|Gruntfuggly|0.0.213|
|vscode-azurefunctions|ms-azuretools|1.4.1|
|vscode-azureresourcegroups|ms-azuretools|0.4.0|
|vscode-azurestorage|ms-azuretools|0.12.1|
|vscode-commons|redhat|0.0.6|
|vscode-css-modules|clinyong|0.2.3|
|vscode-css-peek|pranaygp|4.2.0|
|vscode-docker|ms-azuretools|1.15.0|
|vscode-dotnet-adapter|derivitec-ltd|1.4.3|
|vscode-edit-csv|janisdd|0.6.0|
|vscode-eslint|dbaeumer|2.1.23|
|vscode-markdownlint|DavidAnson|0.42.1|
|vscode-pylance|ms-python|2021.7.5|
|vscode-scss|mrmlnc|0.10.0|
|vscode-statusbar-json-path|richie5um2|1.4.5|
|vscode-svgviewer|cssho|2.0.0|
|vscode-test-explorer|hbenl|2.20.4|
|vscode-typescript-tslint-plugin|ms-vscode|1.3.3|
|vsliveshare|ms-vsliveshare|1.0.4583|;

</details>

**Comment by Sti2nd** [comment]
Definitiely something funky going on with Omnisharp. It used 1 minute and 8 seconds (and 100% CPU utilisation) to build two projects that Visual Studio use 10 seconds on. It's almost as if Omnisharp rebuilds the same project several times instead of just once.

**Comment by JoeRobich** [comment]
A lot has changed with O# since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
