### ISSUE TITLE
Wont prompt me to add missing json files when creating the most basic mvc project on desktop, but works on mac.

### ISSUE THREAD

**Issue by dinguus** [dotnet/vscode-csharp#4697]
## Issue Description ##
Trying to create the most basic MVC project using "dotnet new mvc -o MvcMovie
code -r MvcMovie" from Microsoft. Once i open the project, i never get asked to add the missing files. And when i try to launch it, it just gives me an empty launch.json file. I've tried for 7 hours to fix this. I did the exact same steps on my mac and i got the prompt to add the missing files, and then it worked. But on my windows i get nothing. 

## Steps to Reproduce ##
1. Create new MVC project: 
dotnet new mvc -o MvcMovie
code -r MvcMovie
2. Open it
3. Get no prompt for adding missing files
4. Files look like this 

## Expected Behavior ##
Expected behavior is for the files to like like this:
![image](https://user-images.githubusercontent.com/31272490/128535521-8219c7c5-d0ab-407f-bb92-bbc8479ef60a.png)

## Actual Behavior ##
![image](https://user-images.githubusercontent.com/31272490/128535345-3f8cc2f3-b2f8-4005-ae09-01f6fb209f6c.png)

### OmniSharp log ###
<details>Post the output from Output-->Starting OmniSharp server at 6.8.2021, 17:15:39
    Target: c:\Users\Micha\Desktop\MovieMVC\MvcMovie

OmniSharp server started.
    Path: c:\Users\Micha\.vscode\extensions\ms-dotnettools.csharp-1.23.14\.omnisharp\1.37.14\OmniSharp.exe
    PID: 199192

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
System.IO.FileNotFoundException: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Build.dll
   ved System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   ved OmniSharp.MSBuild.Discovery.MSBuildInstanceProvider.GetMSBuildVersion(String microsoftBuildPath) i D:\a\1\s\src\OmniSharp.Host\MSBuild\Discovery\MSBuildInstanceProvider.cs:linje 104
   ved OmniSharp.MSBuild.Discovery.Providers.MicrosoftBuildLocatorInstanceProvider.<>c.<GetInstances>b__1_0(VisualStudioInstance instance) i D:\a\1\s\src\OmniSharp.Host\MSBuild\Discovery\Providers\MicrosoftBuildLocatorInstanceProvider.cs:linje 30
   ved System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   ved System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   ved System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   ved System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   ved OmniSharp.MSBuild.Discovery.MSBuildLocator.GetInstances() i D:\a\1\s\src\OmniSharp.Host\MSBuild\Discovery\MSBuildLocator.cs:linje 115
   ved OmniSharp.MSBuild.Discovery.Extensions.GetBestInstance(IMSBuildLocator msbuildLocator, Version minimumMSBuildVersion, ILogger logger, Boolean& invalidVSFound, Boolean& vsWithoutSdkResolver) i D:\a\1\s\src\OmniSharp.Host\MSBuild\Discovery\Extensions.cs:linje 109
   ved OmniSharp.MSBuild.Discovery.Extensions.RegisterDefaultInstance(IMSBuildLocator msbuildLocator, ILogger logger, DotNetInfo dotNetInfo) i D:\a\1\s\src\OmniSharp.Host\MSBuild\Discovery\Extensions.cs:linje 17
   ved OmniSharp.CompositionHostBuilder.Build(String workingDirectory) i D:\a\1\s\src\OmniSharp.Host\CompositionHostBuilder.cs:linje 71
   ved OmniSharp.Stdio.Host..ctor(TextReader input, ISharedTextWriter writer, IOmniSharpEnvironment environment, IServiceProvider serviceProvider, CompositionHostBuilder compositionHostBuilder, ILoggerFactory loggerFactory, CancellationTokenSource cancellationTokenSource) i D:\a\1\s\src\OmniSharp.Stdio\Host.cs:linje 49
   ved OmniSharp.Stdio.Driver.Program.<>c__DisplayClass0_1.<Main>b__1() i D:\a\1\s\src\OmniSharp.Stdio.Driver\Program.cs:linje 74
   ved McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass146_0.<OnExecute>b__0(CancellationToken _)
   ved McMaster.Extensions.CommandLineUtils.CommandLineApplication.<ExecuteAsync>d__157.MoveNext()
--- Slutt på stakksporing fra forrige plassering der unntak ble iverksatt ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   ved OmniSharp.HostHelpers.Start(Func`1 action) i D:\a\1\s\src\OmniSharp.Host\HostHelpers.cs:linje 29
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
 </details>

### C# log ###
<details>Post the output from Output-->No errors here</details>

## Environment information ##

**VSCode version**: 1.59.0
**C# Extension**: 1.23.14

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.302
 Commit:    c005824e35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.302\

Host (useful for support):
  Version: 5.0.8
  Commit:  35964c9215

.NET SDKs installed:
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.23.14|;

</details>

**Comment by JoeRobich** [comment]
A lot has changed with O# project loading since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
