### ISSUE TITLE
OmniSharp not Autofilling for Unity Scripts

### ISSUE THREAD

**Issue by CoffeeDoge** [dotnet/vscode-csharp#4707]
## Issue Description ##
Intellisense isn't working. Visual Studio Code gives an error saying OmniSharp server is not running
### OmniSharp log ###
<details></details>

### C# log ###
<details></details>

## Environment information ##

**VSCode version**: 1.59.0
**C# Extension**: 1.23.14

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.400
 Commit:    d61950f9bf

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.400\

Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53

.NET SDKs installed:
  5.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.23.14|;

</details>

**Comment by 333fred** [comment]
It doesn't look like you posted any logs. Please make sure to collect them and include them in the bug, otherwise we can't offer any help.

**Comment by JoeRobich** [comment]
Closing due to lack of response. It is now recommended to use the Unity extension for VS Code.
