### ISSUE TITLE
Omnisharp crashes frequently

### ISSUE THREAD

**Issue by sameeragrawal** [dotnet/vscode-csharp#4721]
## Steps to Reproduce ##

Just keep working on the .NET core project.

## Expected Behavior ##

Omnisharp runs in background and provides intellisense, code completion etc.

## Actual Behavior ##

Omnisharp crashes after some time

### OmniSharp log ###
<details>
[warn]: OmniSharp.Roslyn.CSharp.Services.Navigation.FindUsagesService
        No symbol found. File: /Users/sameera/....cs, Line: 16, Column: 21.
mono_refcount_increment: cannot increment a ref with value 0

=================================================================
Native Crash Reporting
=================================================================
Got a abrt while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

=================================================================
Native stacktrace:
=================================================================
0x104990db9 - /Users/sameera/.vscode/extensions/ms-dotnettools.csharp-1.23.14/.omnisharp/1.37.14/bin/mono : mono_dump_native_crash_info
0x104928bfe - /Users/sameera/.vscode/extensions/ms-dotnettools.csharp-1.23.14/.omnisharp/1.37.14/bin/mono : mono_handle_native_crash
0x104990382 - /Users/sameera/.vscode/extensions/ms-dotnettools.csharp-1.23.14/.omnisharp/1.37.14/bin/mono : sigabrt_signal_handler
0x7fff20473d7d - /usr/lib/system/libsystem_platform.dylib : _sigtramp
0x12badbc5b - Unknown
0x7fff20383406 - /usr/lib/system/libsystem_c.dylib : abort
0x104b7cf37 - /Users/sameera/.vscode/extensions/ms-dotnettools.csharp-1.23.14/.omnisharp/1.37.14/bin/mono : monoeg_assert_abort
0x104b5ddbf - /Users/sameera/.vscode/extensions/ms-dotnettools.csharp-1.23.14/.omnisharp/1.37.14/bin/mono : mono_log_write_logfile
0x104b7d3ce - /Users/sameera/.vscode/extensions/ms-dotnettools.csharp-1.23.14/.omnisharp/1.37.14/bin/mono : monoeg_g_logv_nofree
0x104b7d482 - /Users/sameera/.vscode/extensions/ms-dotnettools.csharp-1.23.14/.omnisharp/1.37.14/bin/mono : monoeg_g_log
0x104a56db7 - /Users/sameera/.vscode/extensions/ms-dotnettools.csharp-1.23.14/.omnisharp/1.37.14/bin/mono : do_mono_image_open
0x104a55867 - /Users/sameera/.vscode/extensions/ms-dotnettools.csharp-1.23.14/.omnisharp/1.37.14/bin/mono : mono_image_open_a_lot_parameterized
0x104a3b371 - /Users/sameera/.vscode/extensions/ms-dotnettools.csharp-1.23.14/.omnisharp/1.37.14/bin/mono : ves_icall_System_Reflection_Assembly_InternalGetAssemblyName
0x104a47909 - /Users/sameera/.vscode/extensions/ms-dotnettools.csharp-1.23.14/.omnisharp/1.37.14/bin/mono : ves_icall_System_Reflection_Assembly_InternalGetAssemblyName_raw
0x119be62ce - Unknown
0x12b916c13 - Unknown
0x118558e3b - Unknown
0x12b915333 - Unknown
0x12b74909a - Unknown
0x12b748ddf - Unknown
0x12b63c0ad - Unknown
0x12b63b0fc - Unknown
0x12b637b3b - Unknown
0x12b5e91db - Unknown
0x12b5e7b13 - Unknown
0x12a199683 - Unknown
0x1171bb372 - Unknown
0x113e828fb - Unknown
0x1171bab6e - Unknown
0x11404369b - Unknown
0x114043003 - Unknown
0x1171bb372 - Unknown
0x113e828fb - Unknown
0x1171bab6e - Unknown
0x11404369b - Unknown
0x114043003 - Unknown
0x1171bb372 - Unknown
0x113e828fb - Unknown
0x1171bab6e - Unknown
0x11404369b - Unknown
0x114043003 - Unknown
0x12b7dba1b - Unknown
0x120cd768b - Unknown
0x1171bb372 - Unknown
0x113e828fb - Unknown
0x1171bab6e - Unknown
0x11404369b - Unknown
0x114043003 - Unknown
0x1171bb372 - Unknown
0x113e828fb - Unknown
0x1171bab6e - Unknown
0x11404369b - Unknown
0x114043003 - Unknown
0x113db714b - Unknown
0x104885ed2 - /Users/sameera/.vscode/extensions/ms-dotnettools.csharp-1.23.14/.omnisharp/1.37.14/bin/mono : mono_jit_runtime_invoke
0x104a96962 - /Users/sameera/.vscode/extensions/ms-dotnettools.csharp-1.23.14/.omnisharp/1.37.14/bin/mono : mono_runtime_try_invoke
0x104ac2848 - /Users/sameera/.vscode/extensions/ms-dotnettools.csharp-1.23.14/.omnisharp/1.37.14/bin/mono : worker_callback
0x1049f77e8 - /Users/sameera/.vscode/extensions/ms-dotnettools.csharp-1.23.14/.omnisharp/1.37.14/bin/mono : worker_thread
0x104abfd7d - /Users/sameera/.vscode/extensions/ms-dotnettools.csharp-1.23.14/.omnisharp/1.37.14/bin/mono : start_wrapper
0x7fff2042e8fc - /usr/lib/system/libsystem_pthread.dylib : _pthread_start
0x7fff2042a443 - /usr/lib/system/libsystem_pthread.dylib : thread_start

=================================================================
Telemetry Dumper:
=================================================================
Pkilling 0x13270802432x from 0x13152673792x
Pkilling 0x13228613632x from 0x13152673792x
Pkilling 0x13186424832x from 0x13152673792x
Pkilling 0x13144236032x from 0x13152673792x
Pkilling 0x13277130752x from 0x13152673792x
Pkilling 0x13234941952x from 0x13152673792x
Pkilling 0x13192753152x from 0x13152673792x
Pkilling 0x13150564352x from 0x13152673792x
Pkilling 0x13113589760x from 0x13152673792x
Pkilling 0x13283459072x from 0x13152673792x
Pkilling 0x13241270272x from 0x13152673792x
Pkilling 0x13199081472x from 0x13152673792x
Pkilling 0x13156892672x from 0x13152673792x
Pkilling 0x13289787392x from 0x13152673792x
Pkilling 0x13247598592x from 0x13152673792x
Pkilling 0x13205409792x from 0x13152673792x
Pkilling 0x13163220992x from 0x13152673792x
Pkilling 0x13121032192x from 0x13152673792x
Pkilling 0x13296115712x from 0x13152673792x
Pkilling 0x13253926912x from 0x13152673792x
Pkilling 0x13211738112x from 0x13152673792x
Pkilling 0x13169549312x from 0x13152673792x
Pkilling 0x13127360512x from 0x13152673792x
Pkilling 0x13114421248x from 0x13152673792x
Pkilling 0x13302444032x from 0x13152673792x
Pkilling 0x13260255232x from 0x13152673792x
Pkilling 0x13218066432x from 0x13152673792x
Pkilling 0x13175877632x from 0x13152673792x
Pkilling 0x13133688832x from 0x13152673792x
Pkilling 0x13266583552x from 0x13152673792x
Pkilling 0x13224394752x from 0x13152673792x
Pkilling 0x13182205952x from 0x13152673792x
Pkilling 0x13140017152x from 0x13152673792x
Pkilling 0x13272911872x from 0x13152673792x
Pkilling 0x13230723072x from 0x13152673792x
Pkilling 0x13188534272x from 0x13152673792x
Pkilling 0x13146345472x from 0x13152673792x
Pkilling 0x13279240192x from 0x13152673792x
Pkilling 0x13237051392x from 0x13152673792x
Pkilling 0x13194862592x from 0x13152673792x
Pkilling 0x13285568512x from 0x13152673792x
Pkilling 0x13243379712x from 0x13152673792x
Pkilling 0x13201190912x from 0x13152673792x
Pkilling 0x13159002112x from 0x13152673792x
Pkilling 0x13116813312x from 0x13152673792x
Pkilling 0x13291896832x from 0x13152673792x
Pkilling 0x13249708032x from 0x13152673792x
Pkilling 0x13207519232x from 0x13152673792x
Pkilling 0x13165330432x from 0x13152673792x
Could not exec mono-hang-watchdog, expected on path '/Users/sameera/.vscode/extensions/ms-dotnettools.csharp-1.23.14/.omnisharp/1.37.14/etc/../bin/mono-hang-watchdog' (errno 2)
Pkilling 0x13123141632x from 0x13152673792x
Pkilling 0x8672648704x from 0x13152673792x
Pkilling 0x13298225152x from 0x13152673792x
Pkilling 0x13256036352x from 0x13152673792x
Pkilling 0x13213847552x from 0x13152673792x
Pkilling 0x13171658752x from 0x13152673792x
Pkilling 0x13129469952x from 0x13152673792x
Pkilling 0x13304553472x from 0x13152673792x
Pkilling 0x13262364672x from 0x13152673792x
Pkilling 0x13220175872x from 0x13152673792x
Pkilling 0x13177987072x from 0x13152673792x
Pkilling 0x13135798272x from 0x13152673792x
Pkilling 0x13268692992x from 0x13152673792x
Pkilling 0x13226504192x from 0x13152673792x
Pkilling 0x13184315392x from 0x13152673792x
Pkilling 0x13142126592x from 0x13152673792x
Pkilling 0x13275021312x from 0x13152673792x
Pkilling 0x13232832512x from 0x13152673792x
Pkilling 0x13190643712x from 0x13152673792x
Pkilling 0x13148454912x from 0x13152673792x
Pkilling 0x13281349632x from 0x13152673792x
Pkilling 0x13239160832x from 0x13152673792x
Pkilling 0x13196972032x from 0x13152673792x
Pkilling 0x13154783232x from 0x13152673792x
Pkilling 0x13287677952x from 0x13152673792x
Pkilling 0x13245489152x from 0x13152673792x
Pkilling 0x13203300352x from 0x13152673792x
Pkilling 0x13161111552x from 0x13152673792x
Pkilling 0x13118922752x from 0x13152673792x
Pkilling 0x13294006272x from 0x13152673792x
Pkilling 0x13251817472x from 0x13152673792x
Pkilling 0x13209628672x from 0x13152673792x
Pkilling 0x13167439872x from 0x13152673792x
Pkilling 0x13125251072x from 0x13152673792x
Pkilling 0x13300334592x from 0x13152673792x
Pkilling 0x13258145792x from 0x13152673792x
Pkilling 0x13215956992x from 0x13152673792x
Pkilling 0x13173768192x from 0x13152673792x
Pkilling 0x13131579392x from 0x13152673792x
Pkilling 0x13306662912x from 0x13152673792x
Pkilling 0x13264474112x from 0x13152673792x
Pkilling 0x13222285312x from 0x13152673792x
Pkilling 0x13180096512x from 0x13152673792x
Pkilling 0x13137907712x from 0x13152673792x
Entering thread summarizer pause from 0x13152673792x
Finished thread summarizer pause from 0x13152673792x.
Failed to create breadcrumb file (null)/crash_hash_0x44e974cadf

Waiting for dumping threads to resume

=================================================================
	External Debugger Dump:
=================================================================
</details>

### C# log ###
<details>No output in C# log</details>

## Environment information ##

**VSCode version**: 1.59.1
**C# Extension**: 1.23.14

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.7.21379.14
 Commit:    22d70b47bc

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.5
 OS Platform: Darwin
 RID:         osx.11.0-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100-preview.7.21379.14/

Host (useful for support):
  Version: 6.0.0-preview.7.21377.19
  Commit:  91ba01788d

.NET SDKs installed:
  6.0.100-preview.7.21379.14 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-preview.6.21355.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.9.8|
|cmake|twxs|0.0.17|
|cmake-tools|ms-vscode|1.7.3|
|csharp|ms-dotnettools|1.23.14|
|docomment|k--kato|0.1.20|
|gitlens|eamodio|11.6.0|
|jupyter|ms-toolsai|2021.8.1236758218|
|python|ms-python|2021.8.1159798656|
|remote-containers|ms-vscode-remote|0.191.1|
|terraform|hashicorp|2.14.0|
|vscode-azureappservice|ms-azuretools|0.23.0|
|vscode-azureresourcegroups|ms-azuretools|0.4.0|
|vscode-azurestaticwebapps|ms-azuretools|0.7.1|
|vscode-docker|ms-azuretools|1.16.0|
|vscode-markdownlint|DavidAnson|0.43.2|
|vscode-pylance|ms-python|2021.8.2|
|vscode-sqlite|alexcvzz|0.13.0|;

</details>

**Comment by sameeragrawal** [comment]
I moved to Omnisharp v1.23.12 and things seem to be stable here

**Comment by nohwnd** [comment]
That's a proper crash. Is this happening just on any project? Or a specific project?

**Comment by nohwnd** [comment]
Related #3694

**Comment by sameeragrawal** [comment]
@nohwnd Currently I am only working on one project in my setup. I'll check with some other projects as well.

**Comment by burtonrodman** [comment]
i can consistently reproduce this by switching between branches that target .Net Core 3.1 vs .Net 6.0.  There are other scenarios, but this is a sure way to crash OmniSharp.  A Reload Window gets it running again, but _super_ annoying.

**Comment by filipw** [comment]
This has been resolved with the .NET 6 build of OmniSharp. See the instructions here on how to enable it https://github.com/OmniSharp/omnisharp-vscode/releases
