### ISSUE TITLE
Syntax coloring broken when missing bracket in comment

### ISSUE THREAD

**Issue by hachiang-msft** [dotnet/vscode-csharp#4728]
Issue Type: <b>Bug</b>

```
/// <summary>
/// Provide methods to access cloud queue.
/// </summary
public class QueueAccessor : IQueueAccessor, IDisposable
{
...
```

The third line of comment miss a '>', syntax coloring will treat following lines as comment.
It works correctly in VS 2019
![image](https://user-images.githubusercontent.com/75514909/131299370-db0c4f2b-57b9-48e2-b0b2-4e0debdc62b2.png)

Extension version: 1.23.14
VS Code version: Code - Insiders 1.60.0-insider (8dbad73de575e47e127c8b1a4324f2b61257fbdc, 2021-08-27T21:25:29.781Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (4.00GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/hachiang/source/repos/API-Face --crash-reporter-id 955000a5-15e6-4433-924f-13473dd0d244|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vshan820:30294714
vscod805:30301674
bridge0708:30335490
dockerwalkthru:30344881
bridge0723:30353136

```

</details>

**Comment by nohwnd** [comment]
This is broken in https://github.com/dotnet/csharp-tmLanguage/, you can turn on `csharp.semanticHighlighting.enabled` option to get another way of highlighting this, it is `false` by default. This will look weird when you diff files, but should work for this case.

**Comment by JoeRobich** [comment]
Closing as answered.
