### ISSUE TITLE
SIGABRT Crash

### ISSUE THREAD

**Issue by OoLunar** [dotnet/vscode-csharp#4767]
## Issue Description ##
Was writing XUnit tests when the crash unexpectedly occurred. I was in the action of Ctrl+D, selecting duplicates of the highlighted text.

## Steps to Reproduce ##
Unsure. Unable to reproduce myself, so I'll just send the actions that I happened to be doing at this time.
- Open up an XUnity project
- Write a class with around 24 tests
- Ctrl+D a line with 31 characters
- Expect a crash?

## Expected Behavior ##
No crash.
## Actual Behavior ##
Crash, extension errored and is no longer functional. Text is still highlighted with errors and warnings despite the code being updated to fix these errors and warnings.
### OmniSharp log ###
<details>
Starting OmniSharp server at 9/14/2021, 1:33:17 PM
    Target: /home/lunar/Code/ForSaken Borders/Backend/ForSakenBorders.Backend.Tests

OmniSharp server started.
    Path: /home/lunar/.vscode/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/run
    PID: 15790

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on void 0.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 17.0.0 - "/home/lunar/.vscode/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/home/lunar/.vscode/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/omnisharp/.msbuild/Current/Bin/MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 17.0.0 - "/home/lunar/.vscode/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            MSBuildToolsPath = /home/lunar/.vscode/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/omnisharp/.msbuild/Current/Bin
            CscToolPath = /home/lunar/.vscode/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /home/lunar/.vscode/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/omnisharp/.msbuild
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/lunar/Code/ForSaken Borders/Backend/ForSakenBorders.Backend.Tests'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/home/lunar/Code/ForSaken Borders/Backend/ForSakenBorders.Backend.Tests'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/lunar/Code/ForSaken Borders/Backend/ForSakenBorders.Backend.Tests/ForSakenBorders.Backend.Tests.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/lunar/Code/ForSaken Borders/Backend/ForSakenBorders.Backend.Tests'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/lunar/Code/ForSaken Borders/Backend/ForSakenBorders.Backend.Tests' on host 433.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/lunar/Code/ForSaken Borders/Backend/ForSakenBorders.Backend.Tests/ForSakenBorders.Backend.Tests.csproj
Can't find custom attr constructor image: /home/lunar/Code/ForSaken Borders/Backend/ForSakenBorders.Backend/bin/Debug/net6.0/ForSakenBorders.Backend.dll mtoken: 0x0a000001 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/lunar/Code/ForSaken Borders/Backend/ForSakenBorders.Backend.Tests/ForSakenBorders.Backend.Tests.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/lunar/Code/ForSaken Borders/Backend/ForSakenBorders.Backend.Tests/ForSakenBorders.Backend.Tests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: ForSakenBorders.Backend.Tests
[info]: OmniSharp.MSBuild.ProjectManager
        Found referenced project outside root directory: /home/lunar/Code/ForSaken Borders/Backend/ForSakenBorders.Backend/ForSakenBorders.Backend.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/lunar/Code/ForSaken Borders/Backend/ForSakenBorders.Backend/ForSakenBorders.Backend.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/lunar/Code/ForSaken Borders/Backend/ForSakenBorders.Backend/ForSakenBorders.Backend.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/lunar/Code/ForSaken Borders/Backend/ForSakenBorders.Backend/ForSakenBorders.Backend.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/lunar/Code/ForSaken Borders/Backend/ForSakenBorders.Backend/ForSakenBorders.Backend.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: ForSakenBorders.Backend
[info]: OmniSharp.OmniSharpWorkspace
        Adding analyzer reference: /usr/src/dotnet-6.0.0-preview-7/sdk/6.0.100-preview.7.21379.14/Sdks/Microsoft.NET.Sdk.Web/analyzers/cs/Microsoft.AspNetCore.Analyzers.dll
[info]: OmniSharp.OmniSharpWorkspace
        Adding analyzer reference: /usr/src/dotnet-6.0.0-preview-7/sdk/6.0.100-preview.7.21379.14/Sdks/Microsoft.NET.Sdk.Web/analyzers/cs/Microsoft.AspNetCore.Mvc.Analyzers.dll
[info]: OmniSharp.OmniSharpWorkspace
        Adding analyzer reference: /usr/src/dotnet-6.0.0-preview-7/sdk/6.0.100-preview.7.21379.14/Sdks/Microsoft.NET.Sdk.Web/analyzers/cs/Microsoft.AspNetCore.Components.Analyzers.dll
[info]: OmniSharp.OmniSharpWorkspace
        Adding analyzer reference: /usr/src/dotnet-6.0.0-preview-7/sdk/6.0.100-preview.7.21379.14/Sdks/Microsoft.NET.Sdk/analyzers/Microsoft.CodeAnalysis.CSharp.NetAnalyzers.dll
[info]: OmniSharp.OmniSharpWorkspace
        Adding analyzer reference: /usr/src/dotnet-6.0.0-preview-7/sdk/6.0.100-preview.7.21379.14/Sdks/Microsoft.NET.Sdk/analyzers/Microsoft.CodeAnalysis.NetAnalyzers.dll
[info]: OmniSharp.OmniSharpWorkspace
        Adding analyzer reference: /home/lunar/.nuget/packages/microsoft.entityframeworkcore.analyzers/5.0.9/analyzers/dotnet/cs/Microsoft.EntityFrameworkCore.Analyzers.dll
[info]: OmniSharp.OmniSharpWorkspace
        Adding analyzer reference: /home/lunar/.nuget/packages/xunit.analyzers/0.10.0/analyzers/dotnet/cs/xunit.analyzers.dll
[info]: OmniSharp.OmniSharpWorkspace
        Adding analyzer reference: /usr/src/dotnet-6.0.0-preview-7/packs/Microsoft.NETCore.App.Ref/6.0.0-preview.7.21377.19/analyzers/dotnet/cs/System.Text.Json.SourceGeneration.dll
[info]: OmniSharp.OmniSharpWorkspace
        Adding analyzer reference: /usr/src/dotnet-6.0.0-preview-7/packs/Microsoft.AspNetCore.App.Ref/6.0.0-preview.7.21378.6/analyzers/dotnet/cs/Microsoft.Extensions.Logging.Generators.dll
[info]: OmniSharp.OmniSharpWorkspace
        Adding analyzer reference: /usr/src/dotnet-6.0.0-preview-7/sdk/6.0.100-preview.7.21379.14/Sdks/Microsoft.NET.Sdk.Razor/source-generators/Microsoft.AspNetCore.Mvc.Razor.Extensions.dll
[info]: OmniSharp.OmniSharpWorkspace
        Adding analyzer reference: /usr/src/dotnet-6.0.0-preview-7/sdk/6.0.100-preview.7.21379.14/Sdks/Microsoft.NET.Sdk.Razor/source-generators/Microsoft.AspNetCore.Razor.Language.dll
[info]: OmniSharp.OmniSharpWorkspace
        Adding analyzer reference: /usr/src/dotnet-6.0.0-preview-7/sdk/6.0.100-preview.7.21379.14/Sdks/Microsoft.NET.Sdk.Razor/source-generators/Microsoft.CodeAnalysis.Razor.dll
[info]: OmniSharp.OmniSharpWorkspace
        Adding analyzer reference: /usr/src/dotnet-6.0.0-preview-7/sdk/6.0.100-preview.7.21379.14/Sdks/Microsoft.NET.Sdk.Razor/source-generators/Microsoft.NET.Sdk.Razor.SourceGenerators.dll
[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
        Solution initialized -> queue all documents for code analysis. Initial document count: 31.
Received response for /v2/gotodefinition but could not find request.
[warn]: OmniSharp.Roslyn.CSharp.Services.Navigation.FindUsagesService
        No symbol found. File: /home/lunar/Code/ForSaken Borders/Backend/ForSakenBorders.Backend.Tests/src/UsersControllerTest.cs, Line: 175, Column: 34.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/blockstructure but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /completion but could not find request.
Received response for /v2/blockstructure but could not find request.
Received response for /signatureHelp but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /completion but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/blockstructure but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/blockstructure but could not find request.
Received response for /signatureHelp but could not find request.
Received response for /signatureHelp but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
mono_refcount_increment: cannot increment a ref with value 0

=================================================================
Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

=================================================================
Native stacktrace:
=================================================================
0x4b8a69 - /home/lunar/.vscode/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/bin/mono :
0x4b8dd9 - /home/lunar/.vscode/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/bin/mono :
0x4626d5 - /home/lunar/.vscode/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/bin/mono :
0x4b800f - /home/lunar/.vscode/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/bin/mono :
0x7f87492f9900 - /usr/lib/libpthread.so.0 :
0x7f8748d92f81 - /usr/lib/libc.so.6 : gsignal
0x7f8748d7c536 - /usr/lib/libc.so.6 : abort
0x718ed4 - /home/lunar/.vscode/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/bin/mono :
0x6fc0f1 - /home/lunar/.vscode/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/bin/mono :
0x718dbb - /home/lunar/.vscode/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/bin/mono :
0x7192a3 - /home/lunar/.vscode/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/bin/mono : monoeg_g_logv
0x71935f - /home/lunar/.vscode/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/bin/mono : monoeg_g_log
0x423de1 - /home/lunar/.vscode/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/bin/mono :
0x5ee010 - /home/lunar/.vscode/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/bin/mono :
0x5f06e3 - /home/lunar/.vscode/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/bin/mono :
0x5f0f14 - /home/lunar/.vscode/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/bin/mono :
0x5d047a - /home/lunar/.vscode/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/bin/mono :
0x5dcf4b - /home/lunar/.vscode/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/bin/mono :
0x41dd33bc - Unknown

=================================================================
Telemetry Dumper:
=================================================================
Pkilling 0x140218423096896x from 0x140215866340928x
Pkilling 0x140218979661376x from 0x140215866340928x
Pkilling 0x140216621033024x from 0x140215866340928x
Pkilling 0x140216593819200x from 0x140215866340928x
Pkilling 0x140215864239680x from 0x140215866340928x
Pkilling 0x140218425198144x from 0x140215866340928x
Pkilling 0x140219019251648x from 0x140215866340928x
Pkilling 0x140216650094144x from 0x140215866340928x
Pkilling 0x140216623134272x from 0x140215866340928x
Pkilling 0x140217098913344x from 0x140215866340928x
Pkilling 0x140217857222208x from 0x140215866340928x
Pkilling 0x140217805145664x from 0x140215866340928x
Pkilling 0x140216595920448x from 0x140215866340928x
Pkilling 0x140218966885952x from 0x140215866340928x
Pkilling 0x140218427299392x from 0x140215866340928x
Pkilling 0x140216613598784x from 0x140215866340928x
Pkilling 0x140216652195392x from 0x140215866340928x
Pkilling 0x140217101014592x from 0x140215866340928x
Pkilling 0x140217807246912x from 0x140215866340928x
Pkilling 0x140217108391488x from 0x140215866340928x
Pkilling 0x140218952836672x from 0x140215866340928x
Pkilling 0x140216654296640x from 0x140215866340928x
Pkilling 0x140217103115840x from 0x140215866340928x
Could not exec mono-hang-watchdog, expected on path '/home/lunar/.vscode/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/etc/../bin/mono-hang-watchdog' (errno 2)
Pkilling 0x140217809348160x from 0x140215866340928x
Pkilling 0x140215858492992x from 0x140215866340928x
Pkilling 0x140218960533056x from 0x140215866340928x
Pkilling 0x140217110492736x from 0x140215866340928x
Pkilling 0x140218954937920x from 0x140215866340928x
Pkilling 0x140215854298688x from 0x140215866340928x
Pkilling 0x140217862317632x from 0x140215866340928x
Pkilling 0x140217811449408x from 0x140215866340928x
Pkilling 0x140217105217088x from 0x140215866340928x
Pkilling 0x140215909873216x from 0x140215866340928x
Pkilling 0x140218430645824x from 0x140215866340928x
Pkilling 0x140217864418880x from 0x140215866340928x
Pkilling 0x140218405119552x from 0x140215866340928x
Pkilling 0x140218964768320x from 0x140215866340928x
Pkilling 0x140217799882304x from 0x140215866340928x
Pkilling 0x140217850787392x from 0x140215866340928x
Pkilling 0x140218958415424x from 0x140215866340928x
Pkilling 0x140217834796608x from 0x140215866340928x
Pkilling 0x140218420803136x from 0x140215866340928x
Pkilling 0x140218408564288x from 0x140215866340928x
Pkilling 0x140218405385792x from 0x140215866340928x
Pkilling 0x140216618931776x from 0x140215866340928x
Pkilling 0x140218962650688x from 0x140215866340928x
Pkilling 0x140215649826368x from 0x140215866340928x
Entering thread summarizer pause from 0x140215866340928x
Finished thread summarizer pause from 0x140215866340928x.
Failed to create breadcrumb file (null)/crash_hash_0x38586d4324

Waiting for dumping threads to resume

=================================================================
	External Debugger Dump:
=================================================================
mono_gdb_render_native_backtraces not supported on this platform, unable to find gdb or lldb
</details>

### C# log ###
N/A

## Environment information ##

**VSCode version**: 1.60.0
**C# Extension**: 1.23.15

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.7.21379.14
 Commit:    22d70b47bc

Runtime Environment:
 OS Name:     void
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/src/dotnet-6.0.0-preview-7/sdk/6.0.100-preview.7.21379.14/

Host (useful for support):
  Version: 6.0.0-preview.7.21377.19
  Commit:  91ba01788d

.NET SDKs installed:
  6.0.100-preview.7.21379.14 [/usr/src/dotnet-6.0.0-preview-7/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [/usr/src/dotnet-6.0.0-preview-7/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [/usr/src/dotnet-6.0.0-preview-7/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|ariake-dark|wart|0.2.2|
|bracket-pair-colorizer|CoenraadS|1.0.61|
|color-highlight|naumovs|2.5.0|
|copilot|GitHub|1.4.2655|
|csharp|ms-dotnettools|1.23.15|
|discord-vscode|icrawl|5.7.0|
|docomment|k--kato|0.1.20|
|EditorConfig|EditorConfig|0.16.4|
|fabric8-analytics|redhat|0.3.3|
|gradle-language|naco-siren|0.2.3|
|java|redhat|0.81.0|
|kotlin|fwcd|0.2.23|
|material-icon-theme|PKief|4.10.0|
|vscode-color|anseki|0.4.5|
|vscode-commons|redhat|0.0.6|
|vscode-gradle|richardwillis|3.6.1|
|vscode-java-debug|vscjava|0.35.0|
|vscode-java-dependency|vscjava|0.18.7|
|vscode-java-pack|vscjava|0.18.4|
|vscode-java-test|vscjava|0.31.3|
|vscode-lombok|GabrielBB|1.0.1|
|vscode-maven|vscjava|0.33.0|
|vscode-pull-request-github|GitHub|0.30.0|
|vscode-sort-json|richie5um2|1.20.0|
|vscode-todo-highlight|jgclark|2.0.4|
|vscode-yaml|redhat|0.22.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.14|
|xml-format|mikeburgh|1.1.2|;

</details>

**Comment by OoLunar** [comment]
Restarting the extension does seem to solve the problem, even if it isn't a permanent solution. This issue has only happened once

**Comment by OoLunar** [comment]
Manually exiting and reopening the editor seems to actually solve the problem

**Comment by OoLunar** [comment]
Turns out I missed two files:
[mono_crash.38586d234c.0.json.txt](https://github.com/OmniSharp/omnisharp-vscode/files/7165375/mono_crash.38586d234c.0.json.txt)
[mono_crash.mem.15794.1.blob.txt](https://github.com/OmniSharp/omnisharp-vscode/files/7165379/mono_crash.mem.15794.1.blob.txt)

**Comment by JoeRobich** [comment]
A lot has changed with O# and mono since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
