### ISSUE TITLE
OmniSharp server is not running.

### ISSUE THREAD

**Issue by rrgarrido** [dotnet/vscode-csharp#4769]
When running a command to debug the code, the message "Unable to generate assets to build and debug. OmniSharp server is not running." comes out.

I tried deleting VS Code and downloading again with the extension C# and it did not work.

Also I cannot see the Omnisharp logs. 

The versions I have are:

VSCode: 1.60
C# extension: v1.23.15
Windows: 10.0.19042

**Comment by JoeRobich** [comment]
I think we may have an issue where sometimes the select project dropdown is not being shown. Try pressing ctrl+shift+p and type `Select Project` to invoke the project selector dropdown. 

![image](https://user-images.githubusercontent.com/611219/133476825-d6bcbda2-6da2-41de-9ef7-173338f0f78d.png)

Choose your solution or project and let me know if that resolves the issue.

**Comment by rrgarrido** [comment]
I did it and now the message is a different one: "Unable to generate assets to build and debug. TypeError: Cannot read property 'tasks' of undefined"

**Comment by rrgarrido** [comment]
Any suggestion?

**Comment by JoeRobich** [comment]
A lot has changed with O# project loading since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
