### ISSUE TITLE
TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by Shadowblitz16** [dotnet/vscode-csharp#4786]
## Issue Description ##
Unable to generate assets to build and debug. TypeError: Cannot read property '0' of null

## Steps to Reproduce ##
It just started happening after messing with bin and obj outputs.
Try building this in vs code https://github.com/Shadowblitz16/Pure. 
(not guaranteed to reproduce bug. ) 

- Delete .vscode folder and all obj and bin folders.
- Open `Pure/PureEditor/Program.cs`
- `ctrl+shift+p` ->`OmniSharp: Select Project` -> `Pure.sln`
- Wait for fire icon to be white on status bar.
- `ctrl+shift+p` -> `.NET: Generate Assets for Build and Debug `
- Error.

## Expected Behavior ##
Generates build and debug assets.

## Actual Behavior ##
Pops up with error and debugging isn't available.

## Logs ##
None.

### OmniSharp log ###
Starting OmniSharp server at 9/23/2021, 4:01:01 PM
    Target: /home/shadowblitz16/Documents/dev/cs/Pure/Pure.sln

OmniSharp server started.
    Path: /home/shadowblitz16/.vscode/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/run
    PID: 41997

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on ubuntu 20.4 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 17.0.0 - "/home/shadowblitz16/.vscode/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/home/shadowblitz16/.vscode/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/omnisharp/.msbuild/Current/Bin/MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 17.0.0 - "/home/shadowblitz16/.vscode/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            MSBuildToolsPath = /home/shadowblitz16/.vscode/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/omnisharp/.msbuild/Current/Bin
            CscToolPath = /home/shadowblitz16/.vscode/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /home/shadowblitz16/.vscode/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.15/omnisharp/.msbuild
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/home/shadowblitz16/Documents/dev/cs/Pure'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Skip loading projects listed in solution file or under target directory because MsBuild:LoadProjectsOnDemand is true.
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/shadowblitz16/Documents/dev/cs/Pure'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/home/shadowblitz16/Documents/dev/cs/Pure' on host 41366.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/shadowblitz16/Documents/dev/cs/Pure/PureEditor/PureEditor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/shadowblitz16/Documents/dev/cs/Pure/PureEditor/PureEditor.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/shadowblitz16/Documents/dev/cs/Pure/PureEditor/PureEditor.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/shadowblitz16/Documents/dev/cs/Pure/PureEditor/PureEditor.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PureEditor
[info]: OmniSharp.MSBuild.ProjectManager
        Found referenced project outside root directory: /home/shadowblitz16/Documents/dev/cs/Pure/PureEngine/PureEngine.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/home/shadowblitz16/Documents/dev/cs/Pure/PureEngine/PureEngine.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/home/shadowblitz16/Documents/dev/cs/Pure/PureEngine/PureEngine.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/shadowblitz16/Documents/dev/cs/Pure/PureEngine/PureEngine.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/home/shadowblitz16/Documents/dev/cs/Pure/PureEngine/PureEngine.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: PureEngine
[info]: OmniSharp.OmniSharpWorkspace
        Adding analyzer reference: /usr/share/dotnet/sdk/5.0.400/Sdks/Microsoft.NET.Sdk/analyzers/Microsoft.CodeAnalysis.CSharp.NetAnalyzers.dll
[info]: OmniSharp.OmniSharpWorkspace
        Adding analyzer reference: /usr/share/dotnet/sdk/5.0.400/Sdks/Microsoft.NET.Sdk/analyzers/Microsoft.CodeAnalysis.NetAnalyzers.dll
[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
   
### C# log ###
None.

## Environment information ##

**VSCode version**: 1.60.1
**C# Extension**: 1.23.15

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.400
 Commit:    d61950f9bf

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.400/

Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53

.NET SDKs installed:
  5.0.400 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.9 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|asm-code-lens|maziac|1.8.1|
|bash-ide-vscode|mads-hartmann|1.11.0|
|breeze|kde|0.0.4|
|cpptools|ms-vscode|1.6.0|
|csharp|ms-dotnettools|1.23.15|
|gitlens|eamodio|11.6.0|
|teamhub|TeamHub|14.0.4|
|vscode-nuget-gallery|patcx|0.0.24|;

</details>

**Comment by sys58260** [comment]
Ran on same error. After many tries, I found in my case that it seems related to an omnisharp (v1.25 vscode 1.62) setting about msbuild.

"omnisharp.enableMsBuildLoadProjectsOnDemand"

if present and its set on true, simply remove/comment or set on false on manual settings editor
Hope it helps
Regards

**Comment by best-mmg** [comment]
> 



> Ran on same error. After many tries, I found in my case that it seems related to an omnisharp (v1.25 vscode 1.62) setting about msbuild.
> 
> "omnisharp.enableMsBuildLoadProjectsOnDemand"
> 
> if present and its set on true, simply remove/comment or set on false on manual settings editor Hope it helps Regards

Thank you. It`s realy help me.
