### ISSUE TITLE
Syntax Highlighting not working properly.

### ISSUE THREAD

**Issue by blixto** [dotnet/vscode-csharp#4793]
The following piece of code don't get the proper syntax highlights:

        static int CalculateBalancingLotSize
        (
            decimal currAvgPrice, 
            int currStockQty, 
            decimal currStockPrice, 
            decimal intendedAvgPrice
        )
        {
            var lotSize = currStockQty * ((currAvgPrice - intendedAvgPrice) /
                                      (intendedAvgPrice - currStockPrice));
            return (int)(lotSize);
        }

I understand that the way the formal parameters of the above method are laid-out is in a non-orthodox way, but it is valid syntax. After the first parameter, the type names are not highlighted, and, inside the method body, the 'var' and 'return' keywords are not highlighted also.
![screenshot](https://user-images.githubusercontent.com/6854554/135782831-2b4b8000-1a8a-4b4d-91e8-08635061677c.png)

**Comment by blixto** [comment]
C# Extension Version: 1.23.15
VS Code Version: 1.60.2

**Comment by JoeRobich** [comment]
@blixto Thanks for reporting. This is likely an issue with the C# TextMate grammar which lives in the https://github.com/dotnet/csharp-tmLanguage repo. As a work around you can set `editor.semanticHighlighting.enabled` and `csharp.semanticHighlighting.enabled` to `true` to enabled our experimental semantic highlighting.

**Comment by blixto** [comment]
Yep, this solved the problem for me. I am not closing the issue myself because I don't want to interfere in how you guys at this project reason about what solves an issue, but, for the record, the workaround you pointed out brought the correct highlights back. Thanks for that! \o
![2021-10-07](https://user-images.githubusercontent.com/6854554/136316492-088fc45e-3b51-4f5b-8ced-4c35305e6a8d.png)

**Comment by JoeRobich** [comment]
Closing as the C# extension now ships with semantic highlighting and an improve textmate grammar.
