### ISSUE TITLE
[Feature Request] Log time taken to load/analyze projects

### ISSUE THREAD

**Issue by lonix1** [dotnet/vscode-csharp#4802]
**PROBLEM**
I have many projects, and so when starting vscode, it takes a long time (sometimes 10 minutes or more) for omnisharp to analyze everything. Even on a fast machine, with lots of RAM. It takes too long for me to "become productive".

I'm sure there are non-essential projects ("common", "utils", various test projects) that I can hide from analysis to speed up startup, but I'm unsure where the bottlenecks are.

**FEATURE REQUEST**
It would be nice if omnisharp, once done analyzing a project, would report the time taken. Perhaps in the omnisharp log/channel (unsure of the proper name - the log in the "output" window at the bottom). Better yet, once done analyzing all projects for the first time (upon vscode start), to log a table that shows loading times for all projects.

On big codebases and monorepos this would be **very** valuable.

**Comment by lonix1** [comment]
Unsure how to define it size-wise, but it's about a dozen projects or so. Individually they're nothing special, but together they put the analyser through its paces.

**Comment by JoeRobich** [comment]
A lot has changed with O# project loading since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
