### ISSUE TITLE
false errors

### ISSUE THREAD

**Issue by ilikefrogs101** [dotnet/vscode-csharp#4810]
I am using unity and it gives me errors for things that are not supposed to be error

**Comment by JoeRobich** [comment]
@ilikefrogs101 Please provide the complete OmniSharp log from the Output pane.

**Comment by CoolCoder353** [comment]
Same issue for me. Tried reinstalling but no luck.

**Comment by ilikefrogs101** [comment]
> Same issue for me. Tried reinstalling but no luck.

![image](https://user-images.githubusercontent.com/87593516/147864352-798dc39e-8eaa-4c6f-a57a-51828e29456e.png)
set the text editor you are using in the script editor part of that image

**Comment by ilikefrogs101** [comment]
@CoolCoder353

**Comment by JoeRobich** [comment]
It is now recommended to use the Unity extension for VS Code.
