### ISSUE TITLE
Took a long time reload in VS Code Insiders

### ISSUE THREAD

**Issue by VivekAgoge** [dotnet/vscode-csharp#4888]
- Issue Type: `Bug`
- Extension Name: `csharp`
- Extension Version: `1.23.16`
- OS Version: `Windows_NT x64 10.0.22499`
- VS Code version: `1.63.0-insider`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by VivekAgoge** [comment]
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 386,
		"activateCallTime": 19,
		"activateResolvedTime": 344,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-dotnettools.csharp",
				"_lower": "ms-dotnettools.csharp"
			},
			"activationEvent": "onLanguage:csharp"
		}
	},
	"runtimeErrors": [],
	"runningLocation": 1
}
```

**Comment by JoeRobich** [comment]
@VivekAgoge Could you describe you situation in more detail? When loading or reloading the extension must load your solution and projects into memory which can take some time and it is generally linear based on the size of your solution.

**Comment by JoeRobich** [comment]
Closing due to lack of response.
