### ISSUE TITLE
Contribute to language status bar

### ISSUE THREAD

**Issue by isidorn** [dotnet/vscode-csharp#4898]
Hi VS Code PM here 👋 

Currently the C# extension contributes individual items to the status bar. On my macOS I see the `flame` item in the status bar and I also see the project name (picture attached). There are probably more?
I suggest to use the [language status bar](https://code.visualstudio.com/updates/v1_61#_new-javascript-and-typescript-language-status-item), Typescript is already using this (picture attached).

This way all the C# status bar items will come under a common item making the whole status bar experience cleaner for our users.

The status bar items which are actually progress our current advise is to use the `withProgress`-API. With that you announce a long running thing to VS Code. Our current thinking is to add a new progress location which is the extension’s language status. With that we can render something on the composite item as well as on the item itself. This is being discussed [here](https://github.com/microsoft/vscode/issues/129037#issuecomment-957360329), please chime in.

Let me know what you think. Thanks

fyi @gregg-miskelly @jrieken

![Screenshot 2021-11-16 at 17 21 39](https://user-images.githubusercontent.com/1926584/142024254-07c52073-c570-4ac2-a36d-c28bff0f5aaf.png)

![Screenshot 2021-11-16 at 11 36 10](https://user-images.githubusercontent.com/1926584/141969857-f91e6642-7d1f-43d6-9d1b-a756ebf2c629.png)

**Comment by JoeRobich** [comment]
The C# extension now uses the Language Status Bar when running with the Roslyn LSP.
