### ISSUE TITLE
Debugger: Support Edit and Continue/Hot Reload

### ISSUE THREAD

**Issue by AmberZhang2016** [dotnet/vscode-csharp#490]
## Environment data

`dotnet --info` output:
VS Code version:1.2.1
C# Extension version:1.1.7
## Steps to reproduce
1. We add following code to update the value of one variable when break mode:
    a++; 
2.  then save the updated file;
3.  F10
## Expected  behavior

the new line will be executed and the value will be increased
## Actual behavior

the new line is skipped and the value is not changed

**Comment by gregg-miskelly** [comment]
@AmberZhang2016 Edit and Continue is a large and very connected feature which we don't have any immediate plans to bring to VS Code. I will leave this open, and people feel free to '+1' this. But, just to be clear, it is at least going to be a while before we get to this.

**Comment by 7654098** [comment]
@gregg-miskelly, +1

Any news?

**Comment by node-gs** [comment]
Very interested in something like this. Working from macOS with dotnet can be tough, this would really aid in the development process

**Comment by ikourfaln** [comment]
+1

**Comment by murr4y** [comment]
+1

Recently discovered dotnet watch with .net core. Having the same functionality with the addition of debugging would be great!

**Comment by frystpingvin** [comment]
+1

**Comment by dynameis** [comment]
+1

**Comment by thorgod** [comment]
+1

**Comment by coumarc9** [comment]
+1

**Comment by eluchsinger** [comment]
+1

**Comment by vanmxpx** [comment]
+1

**Comment by G43beli** [comment]
+1

**Comment by blendsdk** [comment]
+1

**Comment by mohamad-xtouch** [comment]
+1

**Comment by glazjoon** [comment]
+1

**Comment by Guybrush21** [comment]
+1

**Comment by sgentile** [comment]
"But, just to be clear, it is at least going to be a while before we get to this."

2 years later... any luck   :)

+2

**Comment by gregg-miskelly** [comment]
:) Not yet. But thanks for voting. The more votes the easier it will be to get funding for the project.

**Comment by amararias** [comment]
+1

**Comment by bitbonk** [comment]
We have rather complex applications that control actual machines and it is extremely time consuming (think hours!) to restart them and bring the software and the machines back into the desired state before we can try the effects that changes have to the overall system.

Of course we have unit test and integration test and all that but often it is just needed to test/try/fix things with/on the actual production hardware.

With the classic .NET Framework this is not really an option because customers might not allow the installation of a debugger on the production PC that controls the machine.

With both the .NET Core debugger and VS Code being copy-deployable this would actually become an option and it would be *extremely* cool to have this ability. It would be an absolute killer feature for us.

**Comment by gregg-miskelly** [comment]
@bitbonk just as an FYI, you actually have been able to XCopy Visual Studio's remote debugger for a very long time now, in case that helps you.

**Comment by bitbonk** [comment]
@gregg-miskelly Yes I am aware of that, but last time I checked edit & continue was not possible. I'd love to be proven wrong though.

**Comment by bitbonk** [comment]
@gregg-miskelly  I just checked again, and you are right. Edit&Continue on classic .NET (4.7.2) does indeed work with remote debugging even if the remote debugger is launched from a remote file share. But (and that's a big but for us unfortunately) you have to *launch* the application with the debugger, attaching it later does allow Edit&Continue.

**Comment by gregg-miskelly** [comment]
Technically the requirement is that the code must be Just-In-Time compiled with EnC enabled. The normal way to have that happen is to launch under a debugger. But if you don't mind giving up a bit of perf, you can run your app with the environment variable `COMPLUS_ForceEnc=1` set, and then you can attach later and EnC.

**Comment by bitbonk** [comment]
Wow that‘s interesting info. I wasn’t aware of the environment variable. It seems to have some [limitations](
https://blogs.msdn.microsoft.com/devops/2015/04/29/net-enc-support-for-lambdas-and-other-improvements-in-visual-studio-2015/) though, most notably

> If you make an edit after attaching you cannot detach the debugger; the debugger will terminate the process when you stop debugging

**Comment by gregg-miskelly** [comment]
To be clear - that is due to the way EnC works, not because of anything to do with the environment variable.

**Comment by clintnetwork** [comment]
It's an important feature

**Comment by ehouarn-perret** [comment]
`exp(Important Feature!)!`

**Comment by dgumberidze** [comment]
1

**Comment by clintnetwork** [comment]
Yes dotnet watch run need to be integrate to omnisharp

**Comment by Alirezanet** [comment]
every debug process takes about 5 min in large applications without edit and continue so this is important feature ! i'll give this issue a BIG +1 ...

**Comment by peresbruno** [comment]
+1

**Comment by ikourfaln** [comment]
+1

**Comment by rodcoura** [comment]
+1

**Comment by Jay1305** [comment]
+1

**Comment by cloder** [comment]
+1

**Comment by clintnetwork** [comment]
+249+2-1

**Comment by olfek** [comment]
I found the solution to this with sheer luck

 1. Stop all running `dotnet` processes
 2. Open `.vscode/launch.json`
 3. Change the line `"preLaunchTask": "build",` to `"preLaunchTask": "watch",`
 4. Start debug mode again (F5 or in the menu: Debug -> Start Debugging)

My answer on [SO](https://stackoverflow.com/a/58107160)

**Comment by nkev** [comment]
+1

**Comment by MESalar** [comment]
+1 Thanks

**Comment by dlkulp** [comment]
+1

**Comment by clintnetwork** [comment]
+2147483647

**Comment by clintnetwork** [comment]
+0xfffffff

**Comment by tedbergeron** [comment]
+1

**Comment by nkamenar** [comment]
+1

**Comment by EmadKaizen** [comment]
+1

**Comment by clintnetwork** [comment]
```
                                      
                                      
                            1111111   
                           1::::::1   
                          1:::::::1   
       +++++++            111:::::1   
       +:::::+               1::::1   
       +:::::+               1::::1   
 +++++++:::::+++++++         1::::1   
 +:::::::::::::::::+         1::::l   
 +:::::::::::::::::+         1::::l   
 +++++++:::::+++++++         1::::l   
       +:::::+               1::::l   
       +:::::+               1::::l   
       +++++++            111::::::111
                          1::::::::::1
                          1::::::::::1
                          111111111111
```

**Comment by wjsgzcn** [comment]
I found that "spring-boot-devtool" can make spring boot apps live reload in vs code. 
so, I hope the dotnet sdk would support this feature instead of vs code debugger.

**Comment by Nekuskus** [comment]
+1 bois

**Comment by PauloDanielCarneiro** [comment]
Any news about this?

**Comment by XmlmXmlmX** [comment]
+100!

**Comment by TechtonicSoftware** [comment]
+1

**Comment by aintitfun** [comment]
+1

**Comment by cloder** [comment]
+1

**Comment by husseinraoouf** [comment]
i think this issue (dotnet/runtime#12409) should be fixed first

**Comment by maxiostro** [comment]
+1

**Comment by bjswart** [comment]
+1

**Comment by PauloDanielCarneiro** [comment]
Any news about it?

**Comment by PauloDanielCarneiro** [comment]
The omnishare-vscode comunicates with a omnisharp-roslyn or with the omnisharp-server?

**Comment by filipw** [comment]
omnisharp-roslyn.
omnisharp-server is legacy.

however it also has nothing to do with debugger, debugger is a separate component

**Comment by eduardonoronha** [comment]
+1

**Comment by mpriem** [comment]
+1

**Comment by artem-hryb** [comment]
+1

**Comment by Alirezaja1384** [comment]
+1

**Comment by daniel18acevedo** [comment]
+1

**Comment by RaymondTracer** [comment]
+1

**Comment by Grimessa** [comment]
+1

**Comment by tgtjam** [comment]
```
                            1111111   
                           1::::::1   
                          1:::::::1   
       +++++++            111:::::1   
       +:::::+               1::::1   
       +:::::+               1::::1   
 +++++++:::::+++++++         1::::1   
 +:::::::::::::::::+         1::::l   
 +:::::::::::::::::+         1::::l   
 +++++++:::::+++++++         1::::l   
       +:::::+               1::::l   
       +:::::+               1::::l   
       +++++++            111::::::111
                          1::::::::::1
                          1::::::::::1
                          111111111111
```

**Comment by luizfernando1996** [comment]
+1

**Comment by jrkd** [comment]
Hey for those who don't want to wait, I've got a functioning workaround at least for the **asp.net core debugger**, with the use of a couple of extensions;
- [Trigger task on save - gruntfuggly.triggertaskonsave](https://github.com/Gruntfuggly/triggertaskonsave)
- [Debug Launcher - fabiospampinato.vscode-debug-launcher](https://github.com/fabiospampinato/vscode-debug-launcher)

My solution involves having `dotnet watch` running as usual, and using _Trigger task on save_ extension to attach back to the debugger (Since dotnet watch kicks off any existing attached debugging when changes happen). 
Running debug configurations isn't actually a task you can refer to, so that's where the _Debug Launcher_ extension comes in, letting you start a launch config from shell. 

Only real issue is that the _Trigger task on save_ extension fires immediately after save, so I added a 1 second delay to give dotnet watch time to properly restart. 

With the extensions installed, you'd need the following settings.  

**NB: Make sure to already be running dotnet watch separately beforehand.** 

`settings.json`
```
{
    "triggerTaskOnSave.tasks": {
        "restart-debugger": [
            "**/*.cs", // <-- change these to whatever other paths/files you need 
            "**/.cshtml"
        ],
    }
}
```

`tasks.json`
```
{
    "tasks": [
        //.. other tasks 
        {
            "label": "restart-debugger",
            "type": "shell",
            "dependsOn": [
                "wait-for-watch"
            ],
            // 'start' is a windows specific command, change this to 'open' on OSX, not sure what it is in linux.
            // this command is what allows us to initiate a .vscode/launch.json config via shell, using the debug launcher extension.
            "command": "start 'vscode://fabiospampinato.vscode-debug-launcher/auto?args=${workspaceFolder}/'"
        },
        {
            "label": "wait-for-watch",
            "type": "shell",
            "command": "Start-Sleep -s 1" //<-- this is a windows powershell command, change this if your on OSX/unix
        }
    ]
}
```

**NB for launch.json**, I had to remove any other configurations, since it doesnt look like theres a way to say this is the default config to run, so you'd otherwise have to choose between them every restart. 
`launch.json`
```
{
    "configurations": [
        {
            "name": "attach",
            "type": "coreclr",
            "request": "attach",
            "processName": "[YOUR PROJECT EXE NAME].exe" //<-- you can find this out by removing it and vs code will offer a list of processes you can search. 
        }
    ]
}
```

This will only work on windows, but just change the shell commands to whatever is available on your OS and it should be cross-platform.

**Comment by dgrigory** [comment]
+1

**Comment by ziaulhasanhamim** [comment]
+1

**Comment by alisol911** [comment]
+1

**Comment by alisol911** [comment]
+1

**Comment by murugaratham** [comment]
where's my user voice? +1

**Comment by PhilParisot** [comment]
+1
Java extensions have this

**Comment by WalissonPires** [comment]
+1

**Comment by andrewms2013** [comment]
+1

**Comment by heartacker** [comment]
Debugger: please support Edit and Continue feature

**Comment by NatanAmorim** [comment]
This feature would be awesome

**Comment by ziaulhasanhamim** [comment]
Any news on this? Is it even possible?

**Comment by heartacker** [comment]
What's stopping this? figure it out

**Comment by gyantal** [comment]
Waiting for this.

**Comment by LanceTrahan** [comment]
+1 and more from the FUUUUUUUTURE!!!

**Comment by darkguy2008** [comment]
So we've been waiting for this to happen since 2016. Is it too optimistic to wait for this to happen in 2026? Asking for a friend.

No seriously, this is one of the most important features that IMO VS has that VSCode doesn't, and heck, it's save me **so much time** when developing because restarting apps sometimes takes way too long. This is the only feature I miss from VS.

**Comment by PhilParisot** [comment]
With the removal of `dotnet watch` I don't think this will happen anytime soon. Google the saga if you like, it made quite some noise.

**Comment by darkguy2008** [comment]
> With the removal of hot reload in `dotnet watch` I don't think this will happen anytime soon. Google the saga if you like, it made quite some noise.

Huh, I recall there was some noise regarding that, but if I'm not mistaken they backed off from that decision and made it to stay. Was this changed recently then? I may have missed the news :(

In that case, is there any place where we can add some pressure on that?

**Comment by PhilParisot** [comment]
Never-mind, you might be right, I think they put it back in.

**Comment by ROMYIM** [comment]
+1

**Comment by TondaKrist** [comment]
+1

**Comment by tobobw** [comment]
+1

**Comment by RivenSkaye** [comment]
+1 for this.
We're 7 years on since the issue was opened, would love to know what the status is on this and if there's anything contributors could do

**Comment by JasonLeeForOnly** [comment]
Greetings
Really need this fature.I noticed this issues was open for over seven years,Need to know was is still prosess on?
BTW,Add local nuget resorce is also needed.

**Comment by tobobw** [comment]
+1

**Comment by gregg-miskelly** [comment]
This feature is now available in C# Dev Kit. See the [documentation](https://code.visualstudio.com/docs/csharp/debugging#_hot-reload) for more information.

**Comment by Igorgro** [comment]
@gregg-miskelly it's really disappointing that this feature was not implemented as a part of this open-source extension 😕
