### ISSUE TITLE
Omnisharp as a stanndalone application

### ISSUE THREAD

**Issue by Jaftali** [dotnet/vscode-csharp#4920]
Is there any way to use Omnisharp as a standalone application without requiring network connectivity during installation. We are a school and would like to use omnisharp in conjunction with Visual Studio Code. Unfortunately, we can't get around the firewall.

**Comment by gregg-miskelly** [comment]
Do you mean for the initial download of dependencies? If so: the next version we release will no longer down do that. You can install a beta release: https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases

**Comment by Jaftali** [comment]
thanks a lot!
