### ISSUE TITLE
Extension no longer works....

### ISSUE THREAD

**Issue by alexanderluiscampino** [dotnet/vscode-csharp#4941]
```
Extension 'ms-dotnettools.csharp' CANNOT use API proposal: quickPickSeparators. Its package.json#enabledApiProposals-property declares: [] but NOT quickPickSeparators. The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-dotnettools.csharp
```
![image](https://user-images.githubusercontent.com/32500355/145496122-7e8f9bad-c082-4b37-b448-e3965958508d.png)

was working couple days ago before the vscode update

**Comment by PsychoNineSix** [comment]
I was told in a previous issue that this is fixed in a prerelease:

https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.23.18-beta2

**Comment by alexanderluiscampino** [comment]
@PsychoNineSix Thank you. Possibly a stupid question, but how to enable the pre-release on vscode?

**Comment by raitonoberu** [comment]
I had the same problem. Follow the instructions here: https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases and then add `"omnisharp.path": "latest"` to your `settings.json` file.

**Comment by JoeRobich** [comment]
Closing as answered.
