### ISSUE TITLE
Failed to run test because "System.ArgumentNullException

### ISSUE THREAD

**Issue by joy1990** [dotnet/vscode-csharp#4960]
Failed to run test because "System.ArgumentNullException: 值不能为 null。\r\n参数名: workingDirectory\r\n 在 OmniSharp.DotNetTest.TestManager..ctor(Project project, String workingDirectory, IDotNetCliService dotNetCli, SemanticVersion dotNetCliVersion, IEventEmitter eventEmitter, ILogger logger) 位置 D:\\a\\1\\s\\src\\OmniSharp.DotNetTest\\TestManager.cs:行号 46\r\n 在 OmniSharp.DotNetTest.TestManager.Create(Project project, IDotNetCliService dotNetCli, IEventEmitter eventEmitter, ILoggerFactory loggerFactory) 位置 D:\\a\\1\\s\\src\\OmniSharp.DotNetTest\\TestManager.cs:行号 71\r\n 在 OmniSharp.DotNetTest.Services.RunTestsInContextService.<Handle>d__1.MoveNext() 位置 D:\\a\\1\\s\\src\\OmniSharp.DotNetTest\\Services\\RunTestsInContextService.cs:行号 29\r\n--- 引发异常的上一位置中堆栈跟踪的末尾 ---\r\n 在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n 在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n 在 OmniSharp.Endpoint.EndpointHandler`2.<GetFirs...

**Comment by JoeRobich** [comment]
A lot has changed with O# since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
