### ISSUE TITLE
The extension shows "Failed to spawn 'dotnet --info'" although I could run the command on the Command Prompt

### ISSUE THREAD

**Issue by Poteto143** [dotnet/vscode-csharp#4969]
This is my first issue on Github, so there would be a something strange, sorry.
## Environment data
**`dotnet --info` output**:
```
.NET SDK (global.json を反映):
 Version:   6.0.101
 Commit:    ef49f6213a

ランタイム環境:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   S:\***

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  6.0.101 [S:\***\VSCode\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [S:\***]
  Microsoft.NETCore.App 6.0.1 [S:\***]
  Microsoft.WindowsDesktop.App 6.0.1 [S:\***]
```

**VSCode version**: 1.63.1(Portable)
**C# Extension**: 1.23.17

## OmniSharp log
Nothing is shown

I installed the C# Extension and .NET SDK to use the code completion for Unity.
However the extension shows "Failed to spawn 'dotnet --info'" on the output log, although I could run `dotnet --info` on the command prompt.
.NET SDK is not on the PATH, instead I put this line on the `settings.json`.
```
"terminal.integrated.env.windows":{
        "PATH": "S:\\***\\dotnet"
    }
```

If you have the solution, please let me know.

**Comment by gregg-miskelly** [comment]
This error means that in the C# extension process, dotnet.exe is not on the path. You can find some instructions to hopefully troubleshoot this here: https://github.com/OmniSharp/omnisharp-vscode/wiki/Troubleshooting:-'The-.NET-Core-SDK-cannot-be-located.'-errors

**Comment by JoeRobich** [comment]
A lot has changed with O# sdk resolution since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
