### ISSUE TITLE
Unable to select project: "Cannot use API proposal: quickPickSeparators."

### ISSUE THREAD

**Issue by nathan130200** [dotnet/vscode-csharp#4970]
```cs
[2021-12-23 08:26:10.592] [exthost] [error] Error: Extension 'ms-dotnettools.csharp' CANNOT use API proposal: quickPickSeparators.
Its package.json#enabledApiProposals-property declares: [] but NOT quickPickSeparators.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-dotnettools.csharp
    at E (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:80833)
    at Object.showQuickPick (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:30178)
    at /home/vera/.vscode/extensions/ms-dotnettools.csharp-1.23.17/dist/extension.js:2:592598
    at Generator.next (<anonymous>:null:null)
    at /home/vera/.vscode/extensions/ms-dotnettools.csharp-1.23.17/dist/extension.js:2:592089
    at new Promise (<anonymous>:null:null)
    at r (/home/vera/.vscode/extensions/ms-dotnettools.csharp-1.23.17/dist/extension.js:2:591834)
    at b (/home/vera/.vscode/extensions/ms-dotnettools.csharp-1.23.17/dist/extension.js:2:592548)
    at /home/vera/.vscode/extensions/ms-dotnettools.csharp-1.23.17/dist/extension.js:2:594111
    at Generator.next (<anonymous>:null:null)
    at /home/vera/.vscode/extensions/ms-dotnettools.csharp-1.23.17/dist/extension.js:2:592089
    at new Promise (<anonymous>:null:null)
    at r (/home/vera/.vscode/extensions/ms-dotnettools.csharp-1.23.17/dist/extension.js:2:591834)
    at /home/vera/.vscode/extensions/ms-dotnettools.csharp-1.23.17/dist/extension.js:2:593977
    at runMicrotasks (<anonymous>:null:null)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at r._executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:31072)
 o.pickProjectAndStart {"value":"ms-dotnettools.csharp","_lower":"ms-dotnettools.csharp"}
```

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.63.0
**C# Extension**: 1.23.17

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
SDK do .NET (refletindo qualquer global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Ambiente de runtime:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.101/

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  6.0.101 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|aspnetcorerazor-html-css-class-completion|kevin-chatham|1.0.3|
|better-cpp-syntax|jeff-hykin|1.15.10|
|bisqwit-terminal-theme|yegiyan|1.0.0|
|cmake|twxs|0.0.17|
|cmake-tools|ms-vscode|1.9.2|
|cpp-helper|amiralizadeh9480|0.3.0|
|CppSnippets|hars|0.0.15|
|cpptools|ms-vscode|1.7.1|
|cpptools-extension-pack|ms-vscode|1.1.0|
|cpptools-themes|ms-vscode|1.0.0|
|csharp|ms-dotnettools|1.23.17|
|csharpextensions|jchannon|1.3.1|
|dark-plus-syntax|dunstontc|0.0.170|
|doxdocgen|cschlosser|1.3.2|
|EditorConfig|EditorConfig|0.16.4|
|go|golang|0.30.0|
|hexeditor|ms-vscode|1.8.2|
|html-css-class-completion|Zignd|1.20.0|
|html-preview-vscode|tht13|0.2.5|
|html-snippets|abusaidm|0.2.1|
|java|redhat|1.2.0|
|live-server|ms-vscode|0.2.11|
|LiveServer|ritwickdey|5.6.1|
|markdown-preview-github-styles|bierner|0.2.0|
|msbuild-project-tools|tintoy|0.4.3|
|powershell|ms-vscode|2021.12.0|
|remote-containers|ms-vscode-remote|0.209.6|
|remote-ssh|ms-vscode-remote|0.70.0|
|remote-ssh-edit|ms-vscode-remote|0.70.0|
|remote-wsl|ms-vscode-remote|0.63.13|
|vs-keybindings|ms-vscode|0.2.1|
|vscode-antlr4|mike-lischke|2.2.4|
|vscode-base64|adamhartford|0.1.0|
|vscode-commons|redhat|0.0.6|
|vscode-css-formatter|aeschli|1.0.2|
|vscode-decompiler|tintinweb|0.0.8|
|vscode-gradle|vscjava|3.9.0|
|vscode-html-css|ecmel|1.10.2|
|vscode-implicit-indent|jemc|1.1.1|
|vscode-java-debug|vscjava|0.37.0|
|vscode-java-dependency|vscjava|0.18.9|
|vscode-java-pack|vscjava|0.20.0|
|vscode-java-test|vscjava|0.33.1|
|vscode-maven|vscjava|0.34.2|
|vscode-nuget-gallery|patcx|0.0.24|
|vscode-solution-explorer|fernandoescolar|0.4.4|
|vscode-typescript-next|ms-vscode|4.6.20211222|
|vscode-wakatime|WakaTime|17.1.0|
|vscode-xml|redhat|0.18.2|
|vscodeintellicode|VisualStudioExptTeam|1.2.15|
|xml|DotJoshJohnson|2.5.1|
|xml-format|mikeburgh|1.1.2|;

</details>

**Comment by dimitritholen** [comment]
I'm experiencing the same issue.

**Comment by Kwonunn** [comment]
I'm experiencing the same issue.
I tried installing a different version but for some (possibly related?) reason when selecting "Install another version" the popup isn't able to load the other versions. I am able to install different versions of other extensions, only C# won't work.

**Comment by nathan130200** [comment]
Same, i tried reinstall extension, reinstall dotnet same happen.

**Comment by dimitritholen** [comment]
@Kwonunn @nathan130200 you have to download the Beta version as a VSIX file and then inside VS Code install the extension via the "install from file" option.

**Comment by xiaomi7732** [comment]
Same issue. @dimitritholen Where can I get the beta vsix? Thanks.

**Comment by gregg-miskelly** [comment]
https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases

**Comment by nathan130200** [comment]
From beta release:
![image](https://user-images.githubusercontent.com/14365254/147925213-157d1e1e-7086-4f76-8218-557a790df8b4.png)

Still same error

**Comment by nathan130200** [comment]
Another problem, everytime i save the file, omnisharp extension force cursor to move to end of file.

**Comment by majew7** [comment]
For me the bug also appears fixed on my Mac with C# extension beta version 1.24.0, which I manually installed into VS Code with this  [Guide: Installing Beta Releases](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases).

Version 1.24.0 doesn't appear available in the VS Code Extension Marketplace yet (https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp)

**Comment by majew7** [comment]
Seems related: https://github.com/OmniSharp/omnisharp-vscode/issues/4907

**Comment by JoeRobich** [comment]
There have been lots of improvements since this issue was opened. Please open a new issue with logs if you are still running into this.
