### ISSUE TITLE
Intellisense not suggesting tokens in the same assembly, but different namespace while not having the using statement yet

### ISSUE THREAD

**Issue by rhyek** [dotnet/vscode-csharp#4979]
## Environment data
`dotnet --info` output:
```
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.1
 OS Platform: Darwin
 RID:         osx.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.101/

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  3.1.415 [/usr/local/share/dotnet/sdk]
  3.1.416 [/usr/local/share/dotnet/sdk]
  6.0.100 [/usr/local/share/dotnet/sdk]
  6.0.101 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.21 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.21 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
VS Code version: 1.63.2
C# Extension version: ?

## OmniSharp log
```
Received response for /v2/blockstructure but could not find request.
Received response for /v2/blockstructure but could not find request.
Received response for /v2/getcodeactions but could not find request.
```

## Steps to reproduce
Have an exception class `AuthenticationException` in namespace `Api.Exceptions`.
Have a controller `SomeController` in namespace `Api.Controllers`.
In `SomeController` start typing (but do not finish) `AuthenticationException` without having a `using Api.Exceptions` at the top of the file.
VSCode will not suggest to autocomplete and automatically add the using statement.
Finish typing `AuthenticationException`.
VSCode will show a code action (lightbulb at start of line) to add the `using Api.Exceptions` statement for you.

## Expected  behavior
VSCode should suggest autocompleting `AuthenticationException` after typing a few letters and on pressing tab to accept the autocomplete, it should automatically add the using statement.

## Actual behavior
Only suggests via code actions to add the using statement after typing the complete name of the class. For comparison, Jetbrains Rider suggests the correct autocomplete after only typing the first two letters ("Au").

If I already have the `using Api.Extensions` statement in the file, the autocomplete works correctly after typing a few letters.

**Comment by JoeRobich** [comment]
Closing as C# extension now supports unimported type completion.
