### ISSUE TITLE
omisharp is frequently crashing with in 5 mins

### ISSUE THREAD

**Issue by hassanrazakhalid** [dotnet/vscode-csharp#4982]
MacBook: M1 pro 2021
OS: Momterey 12.1
VscodeL  1.63.2

Steps:
1. Click on Debug Test
2. omnisharp crashes always

Starting OmniSharp server at 12/31/2021, 1:15:26 PM
    Target: /Volumes/Data/hardstone-projects/qms-api/qms.sln

OmniSharp server started.
    Path: /Users/hassan/.vscode/extensions/ms-dotnettools.csharp-1.23.17/.omnisharp/1.37.17/run
    PID: 3250

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 12.1 (x64)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 17.0.0 - "/Users/hassan/.vscode/extensions/ms-dotnettools.csharp-1.23.17/.omnisharp/1.37.17/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/Users/hassan/.vscode/extensions/ms-dotnettools.csharp-1.23.17/.omnisharp/1.37.17/omnisharp/.msbuild/Current/Bin/MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 17.0.0 - "/Users/hassan/.vscode/extensions/ms-dotnettools.csharp-1.23.17/.omnisharp/1.37.17/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            MSBuildToolsPath = /Users/hassan/.vscode/extensions/ms-dotnettools.csharp-1.23.17/.omnisharp/1.37.17/omnisharp/.msbuild/Current/Bin
            CscToolPath = /Users/hassan/.vscode/extensions/ms-dotnettools.csharp-1.23.17/.omnisharp/1.37.17/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /Users/hassan/.vscode/extensions/ms-dotnettools.csharp-1.23.17/.omnisharp/1.37.17/omnisharp/.msbuild
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Volumes/Data/hardstone-projects/qms-api'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/Volumes/Data/hardstone-projects/qms-api/qms.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Volumes/Data/hardstone-projects/qms-api/src/Domain/Domain.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Volumes/Data/hardstone-projects/qms-api/src/Application/Application.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Volumes/Data/hardstone-projects/qms-api/src/Infrastructure/Infrastructure.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Volumes/Data/hardstone-projects/qms-api/src/Presistence/Presistence.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Volumes/Data/hardstone-projects/qms-api/src/Api/Api.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Volumes/Data/hardstone-projects/qms-api/tests/Application.UnitTests/Application.UnitTests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Volumes/Data/hardstone-projects/qms-api/tests/Domain.UnitTests/Domain.UnitTests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Volumes/Data/hardstone-projects/qms-api/tests/Application.IntegrationTests/Application.IntegrationTests.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Volumes/Data/hardstone-projects/qms-api'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Volumes/Data/hardstone-projects/qms-api' on host 3210.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Volumes/Data/hardstone-projects/qms-api/src/Domain/Domain.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Volumes/Data/hardstone-projects/qms-api/src/Domain/Domain.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Volumes/Data/hardstone-projects/qms-api/src/Domain/Domain.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Volumes/Data/hardstone-projects/qms-api/src/Application/Application.csproj
Can't find custom attr constructor image: /Volumes/Data/hardstone-projects/qms-api/src/Domain/bin/Debug/net5.0/qms.Domain.dll mtoken: 0x0a000001 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Volumes/Data/hardstone-projects/qms-api/src/Application/Application.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Volumes/Data/hardstone-projects/qms-api/src/Application/Application.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Volumes/Data/hardstone-projects/qms-api/src/Infrastructure/Infrastructure.csproj
Can't find custom attr constructor image: /Volumes/Data/hardstone-projects/qms-api/src/Application/bin/Debug/net5.0/qms.Application.dll mtoken: 0x0a000001 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
Can't find custom attr constructor image: /Volumes/Data/hardstone-projects/qms-api/src/Domain/bin/Debug/net5.0/qms.Domain.dll mtoken: 0x0a000001 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Volumes/Data/hardstone-projects/qms-api/src/Infrastructure/Infrastructure.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Volumes/Data/hardstone-projects/qms-api/src/Infrastructure/Infrastructure.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Volumes/Data/hardstone-projects/qms-api/src/Presistence/Presistence.csproj
Can't find custom attr constructor image: /Volumes/Data/hardstone-projects/qms-api/src/Application/bin/Debug/net5.0/qms.Application.dll mtoken: 0x0a000001 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
Can't find custom attr constructor image: /Volumes/Data/hardstone-projects/qms-api/src/Domain/bin/Debug/net5.0/qms.Domain.dll mtoken: 0x0a000001 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Volumes/Data/hardstone-projects/qms-api/src/Presistence/Presistence.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Volumes/Data/hardstone-projects/qms-api/src/Presistence/Presistence.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Volumes/Data/hardstone-projects/qms-api/src/Api/Api.csproj
Can't find custom attr constructor image: /Volumes/Data/hardstone-projects/qms-api/src/Application/bin/Debug/net5.0/qms.Application.dll mtoken: 0x0a000001 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
Can't find custom attr constructor image: /Volumes/Data/hardstone-projects/qms-api/src/Infrastructure/bin/Debug/net5.0/qms.Infrastructure.dll mtoken: 0x0a000001 due to: Cannot resolve dependency to assembly because it has not been 
Envirnoment:
MacBook: Apple M1 Pro
OS = Monterey 

preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
Can't find custom attr constructor image: /Volumes/Data/hardstone-projects/qms-api/src/Presistence/bin/Debug/net5.0/Presistence.dll mtoken: 0x0a000001 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
Can't find custom attr constructor image: /Volumes/Data/hardstone-projects/qms-api/src/Domain/bin/Debug/net5.0/qms.Domain.dll mtoken: 0x0a000001 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Volumes/Data/hardstone-projects/qms-api/src/Api/Api.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Volumes/Data/hardstone-projects/qms-api/src/Api/Api.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Volumes/Data/hardstone-projects/qms-api/tests/Application.UnitTests/Application.UnitTests.csproj
Can't find custom attr constructor image: /Volumes/Data/hardstone-projects/qms-api/src/Application/bin/Debug/net5.0/qms.Application.dll mtoken: 0x0a000001 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
Can't find custom attr constructor image: /Volumes/Data/hardstone-projects/qms-api/src/Domain/bin/Debug/net5.0/qms.Domain.dll mtoken: 0x0a000001 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Volumes/Data/hardstone-projects/qms-api/tests/Application.UnitTests/Application.UnitTests.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Volumes/Data/hardstone-projects/qms-api/tests/Application.UnitTests/Application.UnitTests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Volumes/Data/hardstone-projects/qms-api/tests/Domain.UnitTests/Domain.UnitTests.csproj
Can't find custom attr constructor image: /Volumes/Data/hardstone-projects/qms-api/src/Domain/bin/Debug/net5.0/qms.Domain.dll mtoken: 0x0a000001 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Volumes/Data/hardstone-projects/qms-api/tests/Domain.UnitTests/Domain.UnitTests.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Volumes/Data/hardstone-projects/qms-api/tests/Domain.UnitTests/Domain.UnitTests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Volumes/Data/hardstone-projects/qms-api/tests/Application.IntegrationTests/Application.IntegrationTests.csproj
Can't find custom attr constructor image: /Volumes/Data/hardstone-projects/qms-api/src/Api/bin/Debug/net5.0/Api.dll mtoken: 0x0a000001 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
Can't find custom attr constructor image: /Volumes/Data/hardstone-projects/qms-api/src/Presistence/bin/Debug/net5.0/Presistence.dll mtoken: 0x0a000001 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
Can't find custom attr constructor image: /Volumes/Data/hardstone-projects/qms-api/src/Application/bin/Debug/net5.0/qms.Application.dll mtoken: 0x0a000001 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
Can't find custom attr constructor image: /Volumes/Data/hardstone-projects/qms-api/src/Domain/bin/Debug/net5.0/qms.Domain.dll mtoken: 0x0a000001 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
Can't find custom attr constructor image: /Volumes/Data/hardstone-projects/qms-api/src/Infrastructure/bin/Debug/net5.0/qms.Infrastructure.dll mtoken: 0x0a000001 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Volumes/Data/hardstone-projects/qms-api/tests/Application.IntegrationTests/Application.IntegrationTests.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Volumes/Data/hardstone-projects/qms-api/tests/Application.IntegrationTests/Application.IntegrationTests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Domain
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Application
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Infrastructure
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Presistence
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Api
Can't find custom attr constructor image: /Volumes/Data/hardstone-projects/qms-api/src/Application/bin/Debug/net5.0/qms.Application.dll mtoken: 0x0a000001 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
Can't find custom attr constructor image: /Volumes/Data/hardstone-projects/qms-api/src/Infrastructure/bin/Debug/net5.0/qms.Infrastructure.dll mtoken: 0x0a000001 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
Can't find custom attr constructor image: /Volumes/Data/hardstone-projects/qms-api/src/Presistence/bin/Debug/net5.0/Presistence.dll mtoken: 0x0a000001 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
Can't find custom attr constructor image: /Volumes/Data/hardstone-projects/qms-api/src/Domain/bin/Debug/net5.0/qms.Domain.dll mtoken: 0x0a000001 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Application.UnitTests
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Domain.UnitTests
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Application.IntegrationTests
Received response for /quickinfo but could not find request.
Received response for /quickinfo but could not find request.
Received response for /completion/resolve but could not find request.
Received response for /completion/resolve but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
[info]: OmniSharp.DotNetTest.VSTestManager
        read: {"MessageType":"TestSession.Connected","Payload":null}
[info]: OmniSharp.DotNetTest.VSTestManager
        read: {"MessageType":"ProtocolVersion","Payload":1}
[info]: OmniSharp.DotNetTest.DebugSessionManager
        Debug session started.
Received response for /findusages but could not find request.
/Users/hassan/.vscode/extensions/ms-dotnettools.csharp-1.23.17/.omnisharp/1.37.17/run: line 28:  3255 Killed: 9               "${mono_cmd}" "${omnisharp_cmd}" "$@"

**Comment by Lobosque** [comment]
@hassanrazakhalid try the 1.24 version with the new .net build. It solved all the constant crashing for me

**Comment by filipw** [comment]
yes the crashes come from the Mono runtime, which is no longer there in the .NET 6 builds of course.

**Comment by JoeRobich** [comment]
A lot has changed with O# and mono since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
