### ISSUE TITLE
[fail]: OmniSharp.MSBuild.ProjectLoader The SDK 'Microsoft.NET.Sdk' specified could not be found.

### ISSUE THREAD

**Issue by hanushi** [dotnet/vscode-csharp#4984]
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:

**Comment by JoeRobich** [comment]
A lot has changed with O# sdk resolution since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
