### ISSUE TITLE
OmniSharp server load timed out

### ISSUE THREAD

**Issue by YuryCH3** [dotnet/vscode-csharp#4987]
## Steps to Reproduce ##
Start VS Code for C# project of any size, or use a command to restart OmniSharp 
## Expected Behavior ##
Expecting OmniSharp  to load
## Actual Behavior ##
It doesn't and nothing about language analysis works.
## What I Tried ##
- Changing omnisharp.projectLoadTimeout to half an hour
- Different versions of VS code 
- Different versions of  `C# for Visual Studio Code` extension 
- Removing user data, reinstalling VS code entirely. 
- Using custom installation `Path: C://omnisharp-win-x86//OmniSharp.exe`
### OmniSharp log ###
<details>Starting OmniSharp server at 02.01.2022, 09:08:13
    Target: c:\Users\TheUser\Documents\C-Sharp-Projects\MyProject

OmniSharp server started.
    Path: c:\Users\TheUser\.vscode\extensions\ms-dotnettools.csharp-1.23.17\.omnisharp\1.37.17\OmniSharp.exe
    PID: 3804

[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
</details>

## Environment information ##

**VSCode version**: 1.63.2
**C# Extension**: 1.23.17

<details><summary>Dotnet Information</summary>
Пакет SDK для .NET (отражающий любой global.json):
 Version:   5.0.404
 Commit:    72c68b830a

Среда выполнения:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.404\

Host (useful for support):
  Version: 5.0.13
  Commit:  b3afe99225

.NET SDKs installed:
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.404 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|13.2.2|
|code-spell-checker|streetsidesoftware|2.0.14|
|cpptools|ms-vscode|1.7.1|
|csharp|ms-dotnettools|1.23.17|
|git-graph|mhutchie|1.30.0|
|jupyter|ms-toolsai|2021.11.1001550889|
|path-intellisense|christian-kohler|2.6.0|
|python|ms-python|2021.12.1559732655|
|theme-monokai-pro-vscode|monokai|1.1.19|
|vscode-pylance|ms-python|2021.12.2|
|vscode-todo-highlight|wayou|1.0.5|
|xml|DotJoshJohnson|2.5.1|;

</details>

**Comment by davidvmckay** [comment]
Possibly same thing as #4959

**Comment by JoeRobich** [comment]
A lot has changed with O# project loading since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
