### ISSUE TITLE
VSCode and OmniSharp

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/vscode-csharp#4994]
---
**Issue moved from dotnet/core#7003**
- Please respond to @renatormendes.

---

_From @renatormendes on Saturday, December 4, 2021 10:11:41 PM_

Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install#
Operating System: linux

Problem: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /home/renatormendes/Documentos/code/MyApp/MyApp.csproj

I made the change in omnisharp.path and also to always update it and I still have the same problem here with .NET 6.0. I use the Solus 4.3 system and my PATH is set in /home/user/.dotnet, where user is my username.

**Comment by JoeRobich** [comment]
A lot has changed with O# project loading since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
