### ISSUE TITLE
Intellisense is not showing any constructor signature suggestion when using "base()" or "this()"

### ISSUE THREAD

**Issue by benayamanuel** [dotnet/vscode-csharp#4998]
## Issue Description ##
Intellisense is not showing any constructor signature suggestion when using "base()" or "this()"

## Steps to Reproduce ##
- Create a random class
- Create one constructor with few parameters
- Create another constructor and try to call another constructor (this()) that has a parameter / or a subclass (base())

## Expected  behavior
VSCode should show a list of available constructor like when we instantiate an object.

![Fix](https://user-images.githubusercontent.com/69380299/148639031-5ba0cebb-6bf0-4211-a32e-ac56fdd9feef.png)

## Actual behavior
VSCode not showing any current available constructor as a suggestion.

![Bug](https://user-images.githubusercontent.com/69380299/148638914-d8450e20-c96b-4e4a-bf87-da491c5e5a1e.png)

### OmniSharp log ###
<details>Starting OmniSharp server at 1/8/2022, 4:00:10 PM
    Target: e:\BenayaManuel\Books Project\Console

OmniSharp server started.
    Path: c:\Users\BenayaManuel\.vscode\extensions\ms-dotnettools.csharp-1.23.17\.omnisharp\1.37.17\OmniSharp.exe
    PID: 23760

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 4 MSBuild instance(s)
            1: Visual Studio Community 2019 16.8.31005.135 16.8.3 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
            2: Visual Studio Community 2017 15.9.28307.858 15.9.21 - "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
            3: Visual Studio Community 2022 17.0.31912.275 17.0.0 - "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin"
            4: StandAlone 17.0.0 - "c:\Users\BenayaManuel\.vscode\extensions\ms-dotnettools.csharp-1.23.17\.omnisharp\1.37.17\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2022 17.0.31912.275 17.0.0 - "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'e:\BenayaManuel\Books Project\Console'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'e:\BenayaManuel\Books Project\Console'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'e:\BenayaManuel\Books Project\Console\Console.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'e:\BenayaManuel\Books Project\Console'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'e:\BenayaManuel\Books Project\Console' on host 3000.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: e:\BenayaManuel\Books Project\Console\Console.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'e:\BenayaManuel\Books Project\Console\Console.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'e:\BenayaManuel\Books Project\Console\Console.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Console
Received response for /completion but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /v2/getcodeactions but could not find request.
Received response for /completion/resolve but could not find request.</details>

### C# log ###
<details></details>

## Environment information ##

**VSCode version**: 1.63.2
**C# Extension**: 1.23.17

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  2.1.509 [C:\Program Files\dotnet\sdk]
  3.1.404 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|atom-material-theme|tobiasalthoff|1.10.8|
|ayu|teabyii|1.0.5|
|better-go-syntax|jeff-hykin|1.1.0|
|color-highlight|naumovs|2.5.0|
|cpptools|ms-vscode|1.7.1|
|csharp|ms-dotnettools|1.23.17|
|dotenv|mikestead|1.0.1|
|github-vscode-theme|GitHub|5.1.0|
|go-nightly|golang|2022.1.521|
|gruvbox|jdinhlife|1.5.1|
|hexeditor|ms-vscode|1.8.2|
|horizon-theme-vscode|jolaleye|2.0.2|
|infinite-theme|benayamanuel|0.0.1|
|javascript-ejs-support|DigitalBrainstem|1.3.1|
|jupyter-renderers|ms-toolsai|1.0.4|
|LiveServer|ritwickdey|5.6.1|
|material-icon-theme|PKief|4.11.0|
|material-theme|zhuangtongfa|3.13.10|
|monogame-pipeline-vscode|abcdef|0.0.3|
|nord-visual-studio-code|arcticicestudio|0.19.0|
|ocean-dark-extended|kleber-swf|1.5.0|
|one-monokai|azemoh|0.5.0|
|prettier-vscode|esbenp|9.1.0|
|python|ms-python|2021.12.1559732655|
|remote-wsl|ms-vscode-remote|0.63.13|
|scss-bem-support|joloyonaha|0.0.6|
|theme-dracula|dracula-theme|2.24.1|
|theme-oceanicnext|naumovs|0.0.4|
|vsc-community-material-theme|Equinusocio|1.4.2|
|vsc-material-theme|Equinusocio|33.1.2|
|vsc-material-theme-icons|equinusocio|1.2.2|
|vscode-css-variables|vunguyentuan|2.3.5|
|vscode-eslint|dbaeumer|2.2.2|
|vscode-gutter-preview|kisstkondoros|0.29.0|
|vscode-icons|vscode-icons-team|11.8.0|
|vscode-pugbeautify|mrmlnc|1.0.2|
|vscode-pylance|ms-python|2022.1.0|
|vscode-react-native|msjsdiag|1.8.1|
|vscode-scss|mrmlnc|0.10.0|
|vscode-styled-components|jpoissonnier|1.7.0|
|vscode-theme-onedark|akamud|2.2.3|
|vscode-todo-highlight|wayou|1.0.5|
|vscode-typescript-next|ms-vscode|4.6.20220107|;

</details>

**Comment by JoeRobich** [comment]
This appears to be an O# bug. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
