### ISSUE TITLE
Inferred files from VS Code propagate through intellisense.

### ISSUE THREAD

**Issue by johnrom** [dotnet/vscode-csharp#4999]
## Issue Description ##

Hi all, happy new year. I was hitting a strange issue today and it had a very funny resolution. Basically, I forgot to add `.cs` to one of my files after renaming. What appears to have happened was that the extensionless file was being inferred as a csharp file by VS Code's intellisense, and its namespace and other metadata were loaded into intellisense. When I opened other files which referenced that file (which was technically not a csharp file), they appeared to work correctly and performing actions like "Go to Definition" went to the extensionless file.

However, there were errors on Build because the project was unable to find a csharp file that had the code that intellisense was picking up. After taking a break and eating lunch, I came back and easily noticed the missing extension, but VS code made it a little harder to detect by auto-inferring the C#-ness of the extensionless file and making it appear normal.

This is a bit of Quality of Life more than a bug, but it might be nice to avoid combining inferred code into the intellisense of real code. Or at least display a warning like "This appears to be a csharp file but will not work in the project due to lack of a `.cs` extension."

## Steps to Reproduce ##

- Create a project
- Remove CSharp extension from a file.
- Go to another file referencing code in that file. There will be no errors / missing references.
- Receive an error on build, missing references.

## Expected Behavior ##

Print errors that references are missing, or warn that the file cannot be referenced by a project when it has an incorrect extension.

## Actual Behavior ##

Intellisense does not warn or error, but build produces an error.

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.63.2
**C# Extension**: 1.23.17

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.101\

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.103 [C:\Program Files\dotnet\sdk]
  3.1.416 [C:\Program Files\dotnet\sdk]
  5.0.404 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.23.17|
|dotnet-test-explorer|formulahendry|0.7.7|
|mdx|silvenon|0.1.0|
|php-debug|felixfbecker|1.22.0|
|phpcs|ikappas|1.0.5|
|powershell|ms-vscode|2021.12.0|
|prettier-vscode|esbenp|9.1.0|
|vscode-intelephense-client|bmewburn|1.8.0|
|vscode-mdx-preview|xyc|0.3.3|;

</details>

**Comment by JoeRobich** [comment]
A lot has changed with O# code analysis since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues

**Comment by johnrom** [comment]
Thanks, I don't see this issue anymore.
