### ISSUE TITLE
SpaceAfterComma not working

### ISSUE THREAD

**Issue by Alemvik** [dotnet/vscode-csharp#5013]
{
	"FormattingOptions": {
		"1doc": "https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.Shared/Options/FormattingOptions.cs",

		"enableEditorConfigSupport": true,

		"newLine": "\n",
		"UseTabs": true,

		"NewLinesForBracesInLambdaExpressionBody": false,
		"NewLinesForBracesInAnonymousMethods": false,
		"NewLinesForBracesInAnonymousTypes": false,
		"NewLinesForBracesInControlBlocks": false,
		"NewLinesForBracesInTypes": false,
		"NewLinesForBracesInMethods": true,
		"NewLinesForBracesInProperties": false,
		"NewLinesForBracesInObjectCollectionArrayInitializers": false,
		"NewLinesForBracesInAccessors": false,

		"NewLineForElse": false,
		"NewLineForCatch": false,
		"NewLineForFinally": false,
		"NewLineForMembersInObjectInit": false,
		"NewLineForMembersInAnonymousTypes": false,
		"NewLineForClausesInQuery": false,

		"IndentBlock": true,
		"SpaceAfterComma": true,
		"SpaceBeforeComma": false,
		"1TabSize": 2,
		"1IndentationSize": 2,
		"IndentBraces": false,
		"WrappingKeepStatementsOnSingleLine": true
	}
}

**Comment by JoeRobich** [comment]
@Alemvik Can you share a sample of code that you expect to be formatted with the additional space?  Also, I see that you have .editorconfig support enabled. Are you using and .editorconfig with you project and does it have SpaceAfterComma configured?

**Comment by Alemvik** [comment]
Thanks, here are the 4 files (and I have no .editorconfig, I tried with this option to enabled, but no luck):


PS: I'm on macbook air M1 with latest OS.

Alain Trépanier 514-707-6713 | Software Designer & Developer

**Comment by JoeRobich** [comment]
A lot has changed with O# since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
