### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by firaskudsy** [dotnet/vscode-csharp#5018]
- Issue Type: `Bug`
- Extension Name: `csharp`
- Extension Version: `1.24.0`
- OS Version: `Darwin x64 19.6.0`
- VS Code version: `1.63.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by shingle-bells** [comment]
Mind telling us what the issue is?

**Comment by firaskudsy** [comment]
VS Code opens .cs files as plain text even after installing the "C# for Visual Studio Code (powered by OmniSharp)." extension. and on the extension run time status am getting:

Unknown language in `contributes.csharp.language`. Provided value: csharp

and .Net version on my machine 5.0.404, tried with .NET 6 but same issue

**Comment by dreammixgames** [comment]
Hey. I'm not sure if this will help, but I was having trouble with the C# extension as well. This fixed it.

Go here:
![image](https://user-images.githubusercontent.com/22350412/150698865-7adb712c-67f3-45dc-80ef-87ead4fa9e6b.png)

Set this to "" instead of whatever it is set to, and save.
![image](https://user-images.githubusercontent.com/22350412/150698869-582e2a93-8d09-4e61-aa53-84a73cb6f2c4.png)

Then restart VS Code

**Comment by firaskudsy** [comment]
i don't see any od the above settings in the json file, the extension installed but nothing in the setting !!

**Comment by JoeRobich** [comment]
@firaskudsy Can you please share the "OmniSharp Log" from the Output pane?

**Comment by firaskudsy** [comment]
so yes am working inside.NET Web API project with .csproj , i don't have .sln file !!

the OmniSharp output 
----------------------

Starting OmniSharp server at 2022-01-26, 8:24:10 a.m.
    Target: /Users/user1/Desktop/code/net-api/yahoo-finance

OmniSharp server started.
    Path: /Users/user1/.vscode/extensions/ms-dotnettools.csharp-1.24.0/.omnisharp/1.38.0/run
    PID: 4668

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 10.15.7 (x64)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 17.0.0 - "/Users/user1/.vscode/extensions/ms-dotnettools.csharp-1.24.0/.omnisharp/1.38.0/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/Users/user1/.vscode/extensions/ms-dotnettools.csharp-1.24.0/.omnisharp/1.38.0/omnisharp/.msbuild/Current/Bin/MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 17.0.0 - "/Users/user1/.vscode/extensions/ms-dotnettools.csharp-1.24.0/.omnisharp/1.38.0/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            MSBuildToolsPath = /Users/user1/.vscode/extensions/ms-dotnettools.csharp-1.24.0/.omnisharp/1.38.0/omnisharp/.msbuild/Current/Bin
            CscToolPath = /Users/user1/.vscode/extensions/ms-dotnettools.csharp-1.24.0/.omnisharp/1.38.0/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /Users/user1/.vscode/extensions/ms-dotnettools.csharp-1.24.0/.omnisharp/1.38.0/omnisharp/.msbuild
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/user1/Desktop/code/net-api/yahoo-finance'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Did not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/Users/user1/Desktop/code/net-api/yahoo-finance'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/user1/Desktop/code/net-api/yahoo-finance/yahoo-finance.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/user1/Desktop/code/net-api/yahoo-finance'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Did not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/user1/Desktop/code/net-api/yahoo-finance' on host 4545.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/user1/Desktop/code/net-api/yahoo-finance/yahoo-finance.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/user1/Desktop/code/net-api/yahoo-finance/yahoo-finance.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/user1/Desktop/code/net-api/yahoo-finance/yahoo-finance.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: yahoo-finance

**Comment by JoeRobich** [comment]
A lot has changed with O# project loading since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
