### ISSUE TITLE
C# Version 1.24.0 not installing in VSCode Version 1.63.2

### ISSUE THREAD

**Issue by banda64** [dotnet/vscode-csharp#5026]
## Environment data
`dotnet --info` output:
VS Code version: 1.63.2
C# Extension version: 1.24.0

## Steps to reproduce
Install C# extension in vscode with version 1.63.2 (latest).

## Expected  behavior
It should be compatible with latest version and install

## Actual behavior
Can't install 'ms-dotnettools.csharp' extension because it is not compatible with the current version of Visual Studio Code (version 1.63.2).

**Comment by JoeRobich** [comment]
Closing due to lack of response.
