### ISSUE TITLE
Rename file refactoring doesn't work in macOS

### ISSUE THREAD

**Issue by ImmuneGit** [dotnet/vscode-csharp#5031]
## Issue Description ##
It's not possible to rename file to a new name of a class

## Steps to Reproduce ##
1. Create class with the same file name
2. Rename class name
3. Open refactoring offer -> "Rename file to" and get the error

<img width="295" alt="Screen Shot 2022-01-30 at 12 40 34" src="https://user-images.githubusercontent.com/25203571/151701835-007acc27-12de-4db7-b01b-347031753701.png">
<img width="455" alt="Screen Shot 2022-01-30 at 12 40 57" src="https://user-images.githubusercontent.com/25203571/151701841-dc768f6c-655f-4580-b3dd-75e2e1a0eda1.png">

## Expected Behavior ##
It have to rename file name

## Actual Behavior ##
Shows an error (a screenshot below)

### OmniSharp log ###
<details>
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.RunCodeActionService
        Applying code action: Rename file to Test.cs
Received response for /v2/getcodeactions but could not find request.
</details>

### C# log ###
<details>
Installing C# dependencies...
Platform: darwin, x86_64

Finished
</details>

## Environment information ##

**VSCode version**: 1.63.2
**C# Extension**: 1.24.0

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.101/
 Electron: 13.5.2
 Chromium: 91.0.4472.164
 Node.js: 14.16.0
 V8: 9.1.269.39-electron.0

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  2.2.207 [/usr/local/share/dotnet/sdk]
  3.1.416 [/usr/local/share/dotnet/sdk]
  5.0.404 [/usr/local/share/dotnet/sdk]
  6.0.101 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.24.0|;

</details>

**Comment by filipw** [comment]
Are you consistently running into this, or just sometimes?
The reproduction steps are very common usage pattern, and they should definitely work (at least I am unable to reproduce this).

Is this a Unity project or .NET Core project? Because Unity uses old style .NET projects where each file needs to be manually tracked in the csproj file, these features would in general not work well unless you manually added the newly created project to the project file.

**Comment by ImmuneGit** [comment]
I run into this all the time. I don't remember this working at all. I've disabled all others extensions and it seems none of them affected this.

**Comment by Strandinator** [comment]
I don't think this is macOS specific.
I get a simmilar error on windows 10.

A new editor tab opens and nothing else happens:

![image](https://github.com/OmniSharp/omnisharp-vscode/assets/45405887/54bc8d8a-4da1-4c1d-9ac5-c49421f5e9f6)

**Comment by JoeRobich** [comment]
A lot has changed with O# code fixes since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
