### ISSUE TITLE
Omnisharp does not detect changes immediately.

### ISSUE THREAD

**Issue by sourvinos** [dotnet/vscode-csharp#5045]
The "Department" child-class is changed into "Departments", yet no error is detected in the "Employees" parent-class

![Omnisharp](https://user-images.githubusercontent.com/16444494/153013398-b6fde948-0744-4115-86ab-8cc71dc03f04.jpg)

**Comment by JoeRobich** [comment]
A lot has changed with O# code analysis since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
