### ISSUE TITLE
nuget package references / state not tracked

### ISSUE THREAD

**Issue by OneCyrus** [dotnet/vscode-csharp#5065]
omnisharp fails to load when opening a project where the nuget packages are not restored yet (dotnet restore).

`Some projects have trouble loading. Please review the output for more details.`

the output leads to missing restored packages:
```
[fail]: OmniSharp.MSBuild.ProjectLoader
        Package MessagePackAnalyzer, version 2.1.152 was not found. It might have been deleted since NuGet restore. Otherwise, NuGet restore might have only partially completed, which might have been due to maximum path length restrictions.
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/home/source/Tests.csproj'.
/home/source/Tests.csproj
/usr/share/dotnet/sdk/6.0.200/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): Error: Package MessagePackAnalyzer, version 2.1.152 was not found. It might have been deleted since NuGet restore. Otherwise, NuGet restore might have only partially completed, which might have been due to maximum path length restrictions.
```

when running dotnet restore omnisharp doesn't detect this and is still in a broken state. I need to restart omnisharp to get the project loaded.

my expectation would be the following:
- omnisharp should detect when something with the nuget package restore state changes. recover from a broken state automatically
- the full Visual Studio auto restores when opening a project/solution. this would be pretty cool to have in omnisharp as well.

**Comment by mauroservienti** [comment]
I'm having the same issue. A sort of workaround is to manually run a `dotnet restore` from the VS Code terminal and then from the command palette to restart OmniSharp (`OmaniSharp:Restart OmniSharp`). It's a sort of workaround, because then I'm getting plenty of the following in the logs:

> [info]: OmniSharp.MSBuild.ProjectManager
>        Update project: Whatever.BlaBla
> Can't find custom attr constructor image: /path/to/some/assembly/...dll mtoken: 0x0a000001 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.

**Comment by rkeithhill-keysight** [comment]
The same thing was happening to me after updating to the latest extension release (11/20/2022) and .NET 7.0 . Thousands of problems - red everywhere in the editors. The suggestion to manually `dotnet restore` and restart omnisharp worked for me.  Annoying though.

**Comment by JoeRobich** [comment]
A lot has changed with O# project loading since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
