### ISSUE TITLE
null recommendation should be prioritized over nuint

### ISSUE THREAD

**Issue by kjackson1998** [dotnet/vscode-csharp#5084]
## Issue Description ##

nu suggestion defaults to nuint instead of null. This seems to have been fixed here giving it lower priority:

https://github.com/dotnet/roslyn/pull/44451

I cannot tell if that has made it into this extension or not yet, but it isn't working if it has. If it hasn't, when will it be brought over?

## Steps to Reproduce ##

in C# code enter a statement like:

string foo = nu

## Expected Behavior ##

null should be prioritized above nuint even though that would be alphabetically out of order.

## Actual Behavior ##

autocomplete list pops up, nuint at the top and highlighted.

## Environment information ##

**VSCode version**: 1.64.2
**C# Extension**: 1.24.0

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.101\

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  3.1.416 [C:\Program Files\dotnet\sdk]
  5.0.211 [C:\Program Files\dotnet\sdk]
  5.0.404 [C:\Program Files\dotnet\sdk]
  5.0.405 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.10.0|
|csharp|ms-dotnettools|1.24.0|
|hexeditor|ms-vscode|1.9.5|
|nsis|idleberg|3.48.0|
|remote-wsl|ms-vscode-remote|0.64.2|
|unity-debug|Unity|3.0.2|
|vscode-azureresourcegroups|ms-azuretools|0.4.0|
|vscode-azurestorage|ms-azuretools|0.13.0|
|vscode-eslint|dbaeumer|2.2.2|
|vscode-nuget-gallery|patcx|0.0.24|
|vscode-xml|redhat|0.19.1|;

</details>

**Comment by kjackson1998** [comment]
It looks to me while Roslyn produces a MatchPriority for CompletionItems, OmniSharp-roslyn doesn't pass it on to OmniSharp-vscode. And vscode wouldn't be able to use it if OmniSharp-vscode had it as it only does sortText ordering? But that's just my naive looking at the pieces not understanding the codebase at all.

**Comment by kjackson1998** [comment]
Added vscode feature request: https://github.com/microsoft/vscode/issues/144149

**Comment by kjackson1998** [comment]
Added OmniSharp-roslyn feature request: https://github.com/OmniSharp/omnisharp-roslyn/issues/2350

**Comment by kjackson1998** [comment]
Tag @CyrusNajmabadi in case the original roslyn author for nuint/null priority cares about this here.

**Comment by CyrusNajmabadi** [comment]
Sounds reasonable to me for omnisharp to support this :)

**Comment by ultimaweapon** [comment]
This one really annoying me too. Most of the times I ended up with `nuint` instead of `null`.

**Comment by leidegre** [comment]
Why does `nuint` even exist? If you need a platform specific integer type there's System.IntPtr and System.UIntPtr this alias -- given the fact that it always shows up before `null` -- is ultra annoying!

**Comment by ostrongent** [comment]
I've worked around it by adding this code snippet in File > Preferences > Configure user snippets, in the c# snippets add following:
```
	"null instead of nuint": {
		"prefix": "nu",
		"body": [
			"null"
		],
		"description": "fix nuint being selected when typing nu <tab> instead of much more popular null"
	}
```

**Comment by JoeRobich** [comment]
Closing as this should be fixed in O#. See https://github.com/OmniSharp/omnisharp-roslyn/issues/2350
