### ISSUE TITLE
Switching away and back to a tab causes folding to be lost and reanalysed

### ISSUE THREAD

**Issue by lonix1** [dotnet/vscode-csharp#5095]
## Environment data
latest of everything
`dotnet --info` output: 6.0.200
VS Code version: 1.65.0
C# Extension version: 1.24.1
linux ubuntu

## OmniSharp log
n/a

## Steps to reproduce
- Open a cs file, wait for folding to appear
- Switch to different tab
- Switch to original tab

## Expected  behavior
Folding info to still exist in the original document. To be able to use the folding triangles (in the gutter).

## Actual behavior
The document's folding info is gone. Any blocks that were folded remain folded, but the folding marks in the gutter are gone. It take some time for the document to be reanalysed - sometimes a loooong time - and only then it becomes usable again.

In older versions it used to be that when a document was fully loaded, switching to a different tab and then switching back, did not cause anything to be lost. The document was only loaded once.

**Comment by JoeRobich** [comment]
Cannot reproduce with current release.
