### ISSUE TITLE
Debugging or Running a Test net6 crashes

### ISSUE THREAD

**Issue by hassanrazakhalid** [dotnet/vscode-csharp#5108]
## Issue Description ##
If the click on debug or run test. I get DirectoryNotFoundExeption. Please see the logs. Note if i run "dotnet test" in terminal i don't get this exception. Something is wrong with omnisharp or vscode i am not sure. One more point "authorization_app.Domain.dll" is available on path "home/hassan/projects/hardstone/authorization-app/src/Domain/bin/Debug/net6.0/authorization_app.Domain.dll". Why when i debug or run a test, it look in ref folder, but it should be looking in folder before "ref". This might help to debug this issue. 
## Steps to Reproduce ##
1. Create a new api project in net6.
2. Create a test project
3. Click on Debug Test it will throw exception.
## Expected Behavior ##
Clicking on Debug or Run Test should allow me to Debug or Run a test.
## Actual Behavior ##
Clicking on Debug or Run test is crashing.
### OmniSharp log ###
<details>
----- Debugging test method authorization_app.Application.IntegrationTests.ApplicationUsers.CreateUserTests.CreateUser -----

Microsoft (R) Build Engine version 17.1.0+ae57d105c for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

/usr/share/dotnet/sdk/6.0.200/Microsoft.Common.CurrentVersion.targets(4650,5): error MSB3883: Unexpected exception:  [/home/hassan/projects/hardstone/authorization-app/src/Domain/Domain.csproj]
/usr/share/dotnet/sdk/6.0.200/Microsoft.Common.CurrentVersion.targets(4650,5): error : DirectoryNotFoundException: Could not find a part of the path '/home/hassan/projects/hardstone/authorization-app/src/Domain/bin/Debug/net6.0/ref/authorization_app.Domain.dll'. [/home/hassan/projects/hardstone/authorization-app/src/Domain/Domain.csproj]
/usr/share/dotnet/sdk/6.0.200/Microsoft.Common.CurrentVersion.targets(4650,5): error :    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter) [/home/hassan/projects/hardstone/authorization-app/src/Domain/Domain.csproj]
/usr/share/dotnet/sdk/6.0.200/Microsoft.Common.CurrentVersion.targets(4650,5): error :    at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter) [/home/hassan/projects/hardstone/authorization-app/src/Domain/Domain.csproj]
/usr/share/dotnet/sdk/6.0.200/Microsoft.Common.CurrentVersion.targets(4650,5): error :    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode) [/home/hassan/projects/hardstone/authorization-app/src/Domain/Domain.csproj]
/usr/share/dotnet/sdk/6.0.200/Microsoft.Common.CurrentVersion.targets(4650,5): error :    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) [/home/hassan/projects/hardstone/authorization-app/src/Domain/Domain.csproj]
/usr/share/dotnet/sdk/6.0.200/Microsoft.Common.CurrentVersion.targets(4650,5): error :    at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite) [/home/hassan/projects/hardstone/authorization-app/src/Domain/Domain.csproj]
/usr/share/dotnet/sdk/6.0.200/Microsoft.Common.CurrentVersion.targets(4650,5): error :    at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite) [/home/hassan/projects/hardstone/authorization-app/src/Domain/Domain.csproj]
/usr/share/dotnet/sdk/6.0.200/Microsoft.Common.CurrentVersion.targets(4650,5): error :    at Microsoft.CodeAnalysis.BuildTasks.CopyRefAssembly.Copy() [/home/hassan/projects/hardstone/authorization-app/src/Domain/Domain.csproj]
/usr/share/dotnet/sdk/6.0.200/Microsoft.Common.CurrentVersion.targets(4650,5): error :  [/home/hassan/projects/hardstone/authorization-app/src/Domain/Domain.csproj]

Build FAILED.

/usr/share/dotnet/sdk/6.0.200/Microsoft.Common.CurrentVersion.targets(4650,5): error MSB3883: Unexpected exception:  [/home/hassan/projects/hardstone/authorization-app/src/Domain/Domain.csproj]
/usr/share/dotnet/sdk/6.0.200/Microsoft.Common.CurrentVersion.targets(4650,5): error : **DirectoryNotFoundException: Could not find a part of the path '/home/hassan/projects/hardstone/authorization-app/src/Domain/bin/Debug/net6.0/ref/authorization_app.Domain.dll'**. [/home/hassan/projects/hardstone/authorization-app/src/Domain/Domain.csproj]
/usr/share/dotnet/sdk/6.0.200/Microsoft.Common.CurrentVersion.targets(4650,5): error :    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter) [/home/hassan/projects/hardstone/authorization-app/src/Domain/Domain.csproj]
/usr/share/dotnet/sdk/6.0.200/Microsoft.Common.CurrentVersion.targets(4650,5): error :    at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter) [/home/hassan/projects/hardstone/authorization-app/src/Domain/Domain.csproj]
/usr/share/dotnet/sdk/6.0.200/Microsoft.Common.CurrentVersion.targets(4650,5): error :    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode) [/home/hassan/projects/hardstone/authorization-app/src/Domain/Domain.csproj]
/usr/share/dotnet/sdk/6.0.200/Microsoft.Common.CurrentVersion.targets(4650,5): error :    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) [/home/hassan/projects/hardstone/authorization-app/src/Domain/Domain.csproj]
/usr/share/dotnet/sdk/6.0.200/Microsoft.Common.CurrentVersion.targets(4650,5): error :    at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite) [/home/hassan/projects/hardstone/authorization-app/src/Domain/Domain.csproj]
/usr/share/dotnet/sdk/6.0.200/Microsoft.Common.CurrentVersion.targets(4650,5): error :    at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite) [/home/hassan/projects/hardstone/authorization-app/src/Domain/Domain.csproj]
/usr/share/dotnet/sdk/6.0.200/Microsoft.Common.CurrentVersion.targets(4650,5): error :    at Microsoft.CodeAnalysis.BuildTasks.CopyRefAssembly.Copy() [/home/hassan/projects/hardstone/authorization-app/src/Domain/Domain.csproj]
/usr/share/dotnet/sdk/6.0.200/Microsoft.Common.CurrentVersion.targets(4650,5): error :  [/home/hassan/projects/hardstone/authorization-app/src/Domain/Domain.csproj]
    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:00.40

</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.65.1
**C# Extension**: 1.24.1

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.200
 Commit:    4c30de7899

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.200/

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  5.0.405 [/usr/share/dotnet/sdk]
  6.0.200 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.14 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.14 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|atlascode|atlassian|2.10.9|
|csharp|ms-dotnettools|1.24.1|
|docomment|k--kato|0.1.30|
|namespace|adrianwilczynski|1.1.2|
|remote-containers|ms-vscode-remote|0.224.2|
|vscode-docker|ms-azuretools|1.20.0|
|vscode-icons|vscode-icons-team|11.10.0|
|vscode-yaml|redhat|1.5.1|;

</details>

**Comment by bewoodall** [comment]
Likely you are hitting this issue: https://github.com/microsoft/vscode-azurefunctions/issues/3051

To be consistent with the intent of the new behavior regarding reference assemblies I recommend limiting the application of the work-around to the debug configuration.

```csproj
    <PropertyGroup Condition="'$(Configuration)'=='DEBUG'">
      <ProduceReferenceAssemblyInOutDir>true</ProduceReferenceAssemblyInOutDir>
    </PropertyGroup>
```

**Comment by hassanrazakhalid** [comment]
Thank you it works. i also found another way for this to work in vscode go to settings of Omnisharp and look for flag "Use Modern Net" and if i check this then it works fine. I am not sure which way is better but both works fine.

**Comment by cateyes99** [comment]
> i also found another way for this to work in vscode go to settings of Omnisharp and look for flag "Use Modern Net" and if i check this then it works fine. I am not sure which way is better but both works fine.

@hassanrazakhalid, thank you.
This works well for my .NET 6 unit tests. Need to reload the project to let it download the OmniSharp for Windows package though after changing this setting.
> Installing C# dependencies...
Platform: win32, x86_64
>
> Downloading package 'OmniSharp for Windows (.NET 6 / x64)' (39624 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package 'OmniSharp for Windows (.NET 6 / x64)'
>
> Finished

**Comment by JoeRobich** [comment]
Closing as answered.
