### ISSUE TITLE
Suggestions not showing in C# IntelliSense

### ISSUE THREAD

**Issue by anna-rosew** [dotnet/vscode-csharp#5133]
Issue Type: <b>Bug</b>

Hi, the suggestions for C# IntelliSense aren't showing in my editor. I only see The only suggestions that do show are words I already typed earlier in the class. I have included a screenshot of a new script I'm working on demonstrating the issue.

![Screenshot 2022-03-30 131833](https://user-images.githubusercontent.com/72981644/160832975-410fcb88-10a2-4579-8d66-599810c515e0.jpg)

I have attempted:

- Restarting VSC.
- Uninstalling and reinstalling most recent version of C# IntelliSense and restarting VSC.
- Uninstalling most recent version of C# IntelliSense and installing an older version and restarting VSC.

None of these solutions worked and I still can't see suggestions when I type. 
If I could get some help that'd be great as I'm a beginner with C# and could really do with this extension working to optimise my work flow.

Thanks,
Anna

Extension version: 1.24.1
VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 3200G with Radeon Vega Graphics     (4 x 3593)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.94GB (1.15GB free)|
|Process Argv|C:\\Users\\anna-\\Desktop\\Create with Code\\Prototype 3\\Prototype 3\\Assets\\Scripts\\PlayerController.cs --crash-reporter-id 23f5ef5e-92a5-4c8d-bd40-6d62b1ed1f13|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30457759
vscscmwlcmt:30438805
vscgsvidc:30447482
pynewfile477:30450038

```

</details>

**Comment by filipw** [comment]
Please post the log output from the "OmniSharp" panel.

**Comment by filipw** [comment]
According to this OmniSharp does not even start because it does not see any csproj/sln files. Those have to be explicitly generated with Unity. Then, a folder containing those files must be opened in VS Code - not individual C# files.

**Comment by verbess** [comment]
"Right click the `Project` panel and Choose `Open C# Project`."

This command will automatically generate the .csproj files for you and open your file with vscode (you need to set vscode as your external script editor) as a project.

**Comment by mig82** [comment]
It took me a while to figure out what this meant. So here's a screenshot for others to find it. 
![image](https://user-images.githubusercontent.com/10434613/163717760-8875f123-2714-4d06-8b98-16705cadc36b.png)
