### ISSUE TITLE
Omnisharp color hightligts not working properly

### ISSUE THREAD

**Issue by Legenden84** [dotnet/vscode-csharp#5162]
![image](https://user-images.githubusercontent.com/97565175/162827758-d6fd44ad-6c19-402c-bd60-e30be982f33b.png)

Hello.

I seem to have problem with my color highligts as seen above. If i disable the C# extension in VS code. The highlighting is fixed, but I also need to extention do be enabled. 

Any fixes that will correct this issue?

**Comment by JoeRobich** [comment]
@Legenden84 Can you share the OmniSharp Log from the VS Code Output pane? Also, what theme do you have configured?

**Comment by Legenden84** [comment]
@JoeRobich  thank you for he fast reply.
I did manage to isolate the problem. The problem was with the "C#" extention that i had installed. Recently was updated. So i downgraded it again for the time being.

**Comment by JoeRobich** [comment]
Closing as answered.
