### ISSUE TITLE
[Feature Request] Cache analyzed code

### ISSUE THREAD

**Issue by ghost** [dotnet/vscode-csharp#5169]
Sometimes you may have projects with various .NET language scripts, for example, in Unity you may get and link all C# Project files one of each other, making the analyze time of the full solution to be extremely slow and performance demandant, which slows down the whole computer.

I think it might be a good idea to add a functionality to cache the analyzed code of a solution, so instead of analyzing the whole document from scratch, it will use that data, unless the hash of it gets changed, which would signify it was modified and it needs to be reanalyzed

**Comment by JoeRobich** [comment]
@usrDottik You may want to try setting "omnisharp.analyzeOpenDocumentsOnly" to "true" in your settings. This will limit analysis only to the open documents instead of the entire solution.

**Comment by usrDottik** [comment]
> @usrDottik You may want to try setting "omnisharp.analyzeOpenDocumentsOnly" to "true" in your settings. This will limit analysis only to the open documents instead of the entire solution.

Thanks for that, made it so much better, though, I still think that my suggestion is a good suggestion

**Comment by ablakey** [comment]
I've set  `omnisharp.analyzeOpenDocumentsOnly` to `true` and yet it still seems to analyze cache files in different directories (even directories I'm trying to ignore entirely, which it seems like omnisharp can't be told not to do?) 

<img width="956" alt="Screen Shot 2022-12-19 at 6 10 05 PM" src="https://user-images.githubusercontent.com/9021944/208545741-70dd2695-6b2b-44aa-ba18-748efd76e7aa.png">

**Comment by Cdddo** [comment]
> @usrDottik You may want to try setting "omnisharp.analyzeOpenDocumentsOnly" to "true" in your settings. This will limit analysis only to the open documents instead of the entire solution.

That's not really a solution because when working on a project in Unity, you *want* to have an analysis of the whole thing.

**Comment by JoeRobich** [comment]
A lot has changed with O# code analysis since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues. Also, It is recommended to use the Unity extension for VS Code.
