### ISSUE TITLE
File in ancestor Directory.Build.props not recognised

### ISSUE THREAD

**Issue by lonix1** [dotnet/vscode-csharp#5173]
## Environment data
dotnet: 6.0.202
VS Code version: 1.66.2
C# Extension version: 1.24.4

## OmniSharp log
none

## Intro
I want to have a common "global usings" file that applies to all projects in my workspace.

## Steps to reproduce
Consider this structure:
- src
  - Project1
    - Project1.csproj
  - Project2
    - Project1.csproj
- tests
  - Project1.Tests
    - Project1.Tests.csproj
  - Project2.Tests
    - Project2.Tests.csproj
- Directory.Build.props
- Globals.cs

Globals.cs:
````cs
global using Foo.Bar;
global using Foo.Baz;
global using Qux.Blah;
````
Directory.Build.props:
````xml
<!-- other stuff... -->
<ItemGroup>
  <Compile Include="Globals.cs" />
</ItemGroup>
<!-- other stuff... -->
````

## Expected  behavior
In either of the projects, I expect that the `Globals.cs` file would be recogised, but it is not.

## Actual behavior
If the inclusion is made in `Project1.csproj` or `Project2.csproj`, then it works.

Note: everything else in `Directory.Build.props` works in those projects.

Is this problem with the extension, omnisharp / roslyn or msbuild?

**Comment by JoeRobich** [comment]
OmniSharp uses MSBuild to run a design-time build where we can get an accurate listing of code files in the project/solution.

I wonder if the issue would be resolved by using the following:
```xml
<ItemGroup>
  <Compile Include="$(MSBuildThisFileDirectory)\Globals.cs" />
</ItemGroup>
```

**Comment by lonix1** [comment]
Hi @JoeRobich thanks - I tested your way in a console console project, and it works!

But in vscode, it doesn't. My .cs files have red squiggly marks with `The type or namespace name "Foo" could not be found (are you missing a using directive of an assembly reference?)`.

Where do you think the problem is? I didn't know which repo to put this in.

**Comment by JoeRobich** [comment]
A lot has changed with O# since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
