### ISSUE TITLE
Could not execute because the specified command or file was not found

### ISSUE THREAD

**Issue by mystiquewolf** [dotnet/vscode-csharp#5195]
## Steps to Reproduce ##
1. Enable `Use  Modern Net` setting.
## Expected Behavior ##
No issues
## Actual Behavior ##
There's an error in the path that the extension tries to load, see the OmniSharp log for the path
`You intended to execute a .NET program, but dotnet-/home/lyubotest/.vscode/extensions/ms-dotnettools.csharp-1.24.4-linux-x64/.omnisharp/1.38.2-net6.0/OmniSharp.dll does not exist.`
### OmniSharp log ###
<details>

```Starting OmniSharp server at 28/04/2022, 20:19:57
    Target: /home/lyubotest/Documents/Projects/pacman-new-deps-notifier

OmniSharp server started with .NET 6.0.102
.
    Path: /home/lyubotest/.vscode/extensions/ms-dotnettools.csharp-1.24.4-linux-x64/.omnisharp/1.38.2-net6.0/OmniSharp.dll
    PID: 155383

Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-/home/lyubotest/.vscode/extensions/ms-dotnettools.csharp-1.24.4-linux-x64/.omnisharp/1.38.2-net6.0/OmniSharp.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
```

</details>

### C# log ###
<details>Nothing here, log is empty</details>

## Environment information ##

**VSCode version**: 1.66.2
**C# Extension**: 1.24.4

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.102
 Commit:    49861cb924

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.102/

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  6.0.102 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.NETCore.App 6.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|bash-debug|rogalmic|0.3.9|
|better-comments|aaron-bond|3.0.0|
|Bookmarks|alefragnani|13.2.4|
|cloudcode|googlecloudtools|1.18.0|
|code-spell-checker|streetsidesoftware|2.1.11|
|cool-language-support|Linhan|0.1.1|
|copilot|GitHub|1.14.5744|
|cpptools|ms-vscode|1.9.8|
|csharp|ms-dotnettools|1.24.4|
|es6-css-minify|olback|3.3.3|
|gc-excelviewer|GrapeCity|4.2.54|
|git-graph|mhutchie|1.30.0|
|gitignore|codezombiech|0.7.0|
|gitlens|eamodio|12.0.6|
|icon-fonts|idleberg|2.5.3|
|idl|mythmon|0.3.1|
|indenticator|SirTori|0.7.0|
|live-server|ms-vscode|0.2.12|
|output-colorizer|IBM|0.1.2|
|partial-diff|ryu1kn|1.4.3|
|path-intellisense|christian-kohler|2.8.0|
|prettier-vscode|esbenp|9.5.0|
|python|ms-python|2022.4.1|
|remote-containers|ms-vscode-remote|0.231.6|
|remote-ssh|ms-vscode-remote|0.78.0|
|remote-ssh-edit|ms-vscode-remote|0.80.0|
|remote-wsl|ms-vscode-remote|0.66.2|
|shell-format|foxundermoon|7.2.2|
|sort-lines|Tyriar|1.9.1|
|teamhub|TeamHub|15.0.6|
|vscode-colorize|kamikillerto|0.11.1|
|vscode-diff-viewer|caponetto|1.2.0|
|vscode-docker|ms-azuretools|1.22.0|
|vscode-eslint|dbaeumer|2.2.2|
|vscode-gutter-preview|kisstkondoros|0.30.0|
|vscode-html-css|ecmel|1.11.0|
|vscode-icons|vscode-icons-team|11.11.0|
|vscode-javascript-booster|sburg|14.0.1|
|vscode-jumpy|krnik|1.0.2|
|vscode-pets|tonybaloney|1.10.0|
|vscode-pylance|ms-python|2022.4.3|
|vscode-remote-extensionpack|ms-vscode-remote|0.21.0|
|vscode-sort-json|richie5um2|1.20.0|
|vscode-versionlens|pflannery|1.0.9|
|vscode-xml|redhat|0.20.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.20|;

</details>

**Comment by mystiquewolf** [comment]
Thanks, this worked!

**Comment by JoeRobich** [comment]
Closing as resolved.
