### ISSUE TITLE
msbuild config file  intellisense

### ISSUE THREAD

**Issue by 2239559319** [dotnet/vscode-csharp#5203]
## Is your feature request related to a problem? Please describe.

Is it possible to support intellisense for msbuild config files like vs?

## Describe the solution you would like
When I edit a `csproj` file I can get intellisense like vs.

## Applicable Scenarios
msbuild file like `csproj` and custom configuration file.

## Describe alternatives you've considered
Is there any other plugin to support it?

**Comment by JoeRobich** [comment]
This is outside the scope of the C# extension. There are other extensions in the marketplace such as https://marketplace.visualstudio.com/items?itemName=tintoy.msbuild-project-tools which provide services like this.
