### ISSUE TITLE
On Mac Intel, with SDK:3.1.420 x64 and latest C# extension:1.25.0 installed, debugging 3.1 project doesn't work in VSCode.

### ISSUE THREAD

**Issue by v-xiaofchen** [dotnet/vscode-csharp#5237]
Environment:
VSCode: 1.67.2
C# extension:1.25.0

Repro steps:
1. Create a new project via CLI
2. Open the project in VSCode

Expected behavior:
VSCode pops up message "Required asserts to build and debug are missing from ‘11’. Add them?"
![image](https://user-images.githubusercontent.com/99376012/170640291-dc1f355c-14e6-4bff-a11c-e0418dd9f586.png)

Actual behavior:
Message "Required asserts to build and debug are missing from ‘11’. Add them?" did not pop up and debug didn't work.
![image](https://user-images.githubusercontent.com/99376012/170640234-27fcdc73-475e-40e0-bfa5-b72e862c6eb4.png)
![image](https://user-images.githubusercontent.com/99376012/170640170-abc862fb-551c-4f05-a4b6-604bca3a6985.png)

dotnet --info:
.NET Core SDK (reflecting any global.json):
Version: 3.1.420
Commit: c4a02e4c2d

Runtime Environment:
OS Name: Mac OS X
OS Version: 10.15
OS Platform: Darwin
RID: osx.10.15-x64
Base Path: /usr/local/share/dotnet/sdk/3.1.420/

Host (useful for support):
Version: 3.1.26
Commit: dae24f14e7

.NET Core SDKs installed:
3.1.420 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
Microsoft.AspNetCore.App 3.1.26 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.26 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
https://aka.ms/dotnet-download

**Comment by v-xiaofchen** [comment]
This issue is not repro on SDK:3.1.419/3.1.420 + C# extension:1.24.4 in VSCode.

**Comment by JoeRobich** [comment]
@v-xiaofchen The C# extension now requires a .NET 6 SDK be installed when working with .NET Core/.NET SDK projects. See the announcement at https://github.com/OmniSharp/omnisharp-vscode/issues/5120

**Comment by ghzhouxin** [comment]
> @v-xiaofchen The C# extension now requires a .NET 6 SDK be installed when working with .NET Core/.NET SDK projects. See the announcement at #5120

How can I set .NET core sdk version to 3.1.4xx for .NET core 3 project?
When I set it in vscode settings like this:
<img width="768" alt="image" src="https://user-images.githubusercontent.com/44893547/171082761-d8ff2eb8-888a-43c1-a13c-b180bddff27a.png">
Omnisharp show log:
        The Sdk version specified in the OmniSharp settings was not a valid semantic version. Configured version is ''3.4.419''. Please update your settings and restart OmniSharp.

**Comment by JoeRobich** [comment]
@ghzhouxin O# requires .NET 6 SDK installed. The .NET 6 SDK can still build apps that are targeting netcoreapp3.1. For running apps built against netcoreapp3.1 you would only need a .NET Core 3.1 runtime to be installed.

**Comment by ghzhouxin** [comment]
> @ghzhouxin O# requires .NET 6 SDK installed. The .NET 6 SDK can still build apps that are targeting netcoreapp3.1. For running apps built against netcoreapp3.1 you would only need a .NET Core 3.1 runtime to be installed.

Thanks for your help.
