### ISSUE TITLE
Code formatting misbehaving

### ISSUE THREAD

**Issue by bestknighter** [dotnet/vscode-csharp#5246]
## Issue Description ##
I'm triggering a Code Format but the behaviour sometimes is not as expected. I've been trying to debug this for a while now with no success. I'd love some help on this.

I have a Unity Project setup and I'm trying to setup an `.editorconfig` to enforce some rules. When I delete the `.sln` and all `*.csproj`, and then restart the O#, the `.editorconfig` is properly read, but some settings are being ignored. I could pinpoint some of those but I couldn't figure out why they aren't being enforced. How can I fix that? Or at least figure out why they are not being applied.

But it gets worse. I ask Unity to generate the bare minimum files, which gives me three files: `silentdepths.sln`, `Assembly-CSharp-Editor.csproj` and `Assembly-CSharp-Editor.csproj`. If I restart O#, now `.editorconfig` is almost completely ignored. The only settings that survive are the diagnostic severity tweaks.

Any light on this would immensely help.

I also quadruple checked both my global `settings.json` for VSCode and the project's `omnisharp.json` to make sure they were properly set up, restarting VSCode everytime I closed them, even if no changes were made.

## Steps to Reproduce ##
1. Create a new Unity Project
2. Setup VSCode as a dev environment with Roslyn Analyzers following Unity's and VSCode's documentation
3. Create an `.editorconfig` and set some formatting rules
4. Create a simple script for testing the formatting rules
5. [Re]Start Omnisharp
6. Try formating the file

## Expected Behavior ##
The code now is formatted following the settings found in `.editorconfig`

## Actual Behavior ##
The code is formatted following other settings (that I have no clue were they are coming from).

## Environment information ##

**VSCode version**: 1.67.2
**C# Extension**: 1.25.0

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.419
 Commit:    92a4e4b3fa

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.419\

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  7.1.2 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.526 [C:\Program Files\dotnet\sdk]
  8.1.419 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|addDocComments|stevencl|0.0.8|
|better-comments|aaron-bond|3.0.0|
|better-cpp-syntax|jeff-hykin|1.15.14|
|cmake|twxs|0.0.17|
|cmake-tools|ms-vscode|1.10.5|
|code-gnu-global|austin|0.2.2|
|codestream|CodeStream|12.18.0|
|cpptools|ms-vscode|1.9.8|
|cpptools-extension-pack|ms-vscode|1.2.0|
|cpptools-themes|ms-vscode|1.0.0|
|csharp|ms-dotnettools|1.25.0|
|docomment|k--kato|0.1.31|
|doxdocgen|cschlosser|1.4.0|
|git-graph|mhutchie|1.30.0|
|gitlens|eamodio|12.0.7|
|jupyter|ms-toolsai|2022.4.1021342353|
|jupyter-keymap|ms-toolsai|1.0.0|
|jupyter-renderers|ms-toolsai|1.0.8|
|markdown-preview-github-styles|bierner|1.0.1|
|partial-diff|ryu1kn|1.4.3|
|python|ms-python|2022.6.2|
|remote-containers|ms-vscode-remote|0.234.0|
|remote-ssh|ms-vscode-remote|0.80.0|
|remote-ssh-edit|ms-vscode-remote|0.80.0|
|remote-wsl|ms-vscode-remote|0.66.3|
|unity-code-snippets|kleber-swf|1.3.0|
|unity-debug|Unity|3.0.2|
|unity-tools|Tobiah|1.2.12|
|vscode-clang|mitaki28|0.2.4|
|vscode-eslint|dbaeumer|2.2.2|
|vscode-hexdump|slevesque|1.8.1|
|vscode-markdownlint|DavidAnson|0.47.0|
|vscode-pull-request-github|GitHub|0.42.0|
|vscode-pylance|ms-python|2022.5.3|
|vscode-react-native|msjsdiag|1.9.2|
|vscode-typescript-next|ms-vscode|4.8.20220530|
|vsliveshare|ms-vsliveshare|1.0.5597|
|vsliveshare-audio|ms-vsliveshare|0.1.91|
|vsliveshare-pack|ms-vsliveshare|0.4.0|
|xml|DotJoshJohnson|2.5.1|;

</details>

## Logs and other relevant files
[files.zip](https://github.com/OmniSharp/omnisharp-vscode/files/8810365/files.zip)

**Comment by JoeRobich** [comment]
It is recommended to use the Unity extensions for VS Code.
