### ISSUE TITLE
IntelliSense has stopped working. Quick fix is not working , it is popping "No code actions available"

### ISSUE THREAD

**Issue by szymi-dev** [dotnet/vscode-csharp#5253]
So I set up VSCode on Windows10 for .NET 5.0 development but the Quick Fix to automatically import namespaces won't work at all. It was working fine until the update of IDE. I can't no longer see the yellow bulb when I hover mouse over the class namespace. Moreover when I click "Ctrl + ." it says "No code actions available". Now I'm struggling with importing libraries manually...[enter image description here](https://i.stack.imgur.com/DDWyr.png) Any help or tips?

## Environment information ##

**VSCode version**: 1.67.2
**C# Extension**: 1.25.0

<details><summary>Dotnet Information</summary>
Zestaw .NET SDK (odzwierciedlenie dowolnego pliku global.json):
 Version:   5.0.203
 Commit:    383637d63f

�rodowisko uruchomieniowe:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.203\

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  3.1.416 [C:\Program Files\dotnet\sdk]
  5.0.203 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|Angular2|johnpapa|13.0.0|
|bracket-pair-colorizer-2|CoenraadS|0.2.4|
|csharp|ms-dotnettools|1.25.0|
|csharpextensions|kreativ-software|1.7.0|
|material-icon-theme|PKief|4.17.0|
|ng-template|Angular|14.0.0|
|vscode-nuget-gallery|patcx|0.0.24|
|vscode-sqlite|alexcvzz|0.14.0|;

</details>
ur clipboard

**Comment by JoeRobich** [comment]
The C# extension now requires an installed .NET 6 SDK. The .NET 6 SDK can build projects that target `net5.0`. Be aware that the .NET 5 SDK is no longer being serviced (see https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core).

**Comment by JoeRobich** [comment]
Closing as answered
