### ISSUE TITLE
VS code debugging issue for azure powershell function - Omnisharp Json Rpc exception

### ISSUE THREAD

**Issue by lavibhatnagar** [dotnet/vscode-csharp#5279]
## Environment data
VS Code version: 1.68.0
C# Extension version: 1.25.0
Azure Core tools: v4
powershell version: 7

## OmniSharp error
![image](https://user-images.githubusercontent.com/5319479/174024720-528938b6-b2e6-4439-b310-31cff565f144.png)

## Steps to reproduce

1. Create azure powershell function 
2. Put a breakpoint anywhere and hit F5
3. See error

## Expected  behavior
Should be able to debug the function

## Actual behavior
Exception of type Omnisharp.Extensions.JsonRpc.RpcErrorException was thrown

**Comment by HariKrishnaRajoli-MT** [comment]
We have tried the scenarios like 
- Uninstalling and Re-installing the C# version in VS Code Extensions
- changing the C# version in VS Code Extensions
- Restarting the VS Code

But getting the same exception for us too. Please give us a fix to this issue!

**Comment by gregg-miskelly** [comment]
I am guessing the issue is that the C# extension is getting activated, but OmniSharp is unhappy that it can't find any C# code or projects in the workspace. But an OmniSharp log would probably be helpful if anyone from the OmniSharp team has the cycles to look at this...

**Comment by lavibhatnagar** [comment]
@HariKrishnaRajoli-MT @gregg-miskelly please follow this thread
https://github.com/Azure/azure-functions-core-tools/issues/3076

**Comment by lavibhatnagar** [comment]
@gregg-miskelly this issue has been logged as bug by azure function.

https://github.com/microsoft/vscode-azurefunctions/issues/3223

**Comment by alexweininger** [comment]
@gregg-miskelly a few users have reported this issue and provided some information in https://github.com/microsoft/vscode-azurefunctions/issues/3223. We haven't had much luck in our investigation and would appreciate any help you could provide! 😄

**Comment by erwinkramer** [comment]
@tanieee28 this works for me, modifying the tasks and launch json's.

**Comment by potatoqualitee** [comment]
sweet, that worked for me, thank you @tanieee28 !

**Comment by dadlMilestone** [comment]
I wish that the solution put forth by @tanieee28 worked for me, but unfortunately it did not. I seem to have to troubleshoot this issue with debugging every couple of weeks. Usually changing or adjusting something helps, but I have shot an entire day today just trying to run my code :( .

VSCODE: 1.81.1
C# ext: 2.0.376
PS ext: 2023.6.0
Az Func ext: 1.12.4
Az Func Core Tools: 4.0.5198
PowerShell: 7.3.6

Same error, although I only get it upon stopping the Azure Functions Core Tools. Very frustrating, and also this issue has been around a very long time.

**Comment by JoeRobich** [comment]
This seems like an issue with the PowerShell extension. The PowerShell LSP is written with OmniSharp's LSP framework.
