### ISSUE TITLE
Formatting of base in constructor

### ISSUE THREAD

**Issue by HypeillingerChillinger** [dotnet/vscode-csharp#5282]
## Describe the solution you would like
```C#
public class WhereFuncPathTests : UnitTestBase
{
    public WhereFuncPathTests(DatabaseFixture fixture)
: base(fixture)        
{ }
}
```

Should be converted/formatted (CTRL+SHIFT+I) to:

```C#
public class WhereFuncPathTests : UnitTestBase
{
    public WhereFuncPathTests(DatabaseFixture fixture)
        : base(fixture)        
    { }
}
```

**Comment by JoeRobich** [comment]
A lot has changed with O# formatting since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
