### ISSUE TITLE
Flathub Specific Workaround In Documentation

### ISSUE THREAD

**Issue by thomas992** [dotnet/vscode-csharp#5294]
https://github.com/OmniSharp/omnisharp-vscode/wiki/Troubleshooting:-'The-.NET-Core-SDK-cannot-be-located.'-errors

Clear Linux uses Flathub. In Visual Studio Code go to terminal and type $PATH or which dotnet
```
which: no dotnet in (/app/bin:/app/bin:/app/bin:/usr/bin:/home/tommhnsn/.var/app/com.visualstudio.code/data/node_modules/bin)
```
most of those paths are not going to work, the one that does is this imaginary one that does not exist the node_modules one, create the node_modules folder and the bin folder inside of it.
now open your real terminal and type something like this
```
sudo ln -s /home/tommhnsn/.dotnet/dotnet /home/tommhnsn/.var/app/com.visualstudio.code/data/node_modules/bin/dotnet
```

I would hope an update would add a Flathub specific documentation before reading anything this heavy

```
If which dotnet produces a PATH, then the .NET SDK was able to successfully modify the PATH, but VS Code isn't picking it up. VS Code attempts to scrape the environment by launching the default shell under the covers. But this process can be fragile.
```

**Comment by thomas992** [comment]
the current documentation makes no reference to how the path environment variable works in a sandbox environment. I originally titled this issue as Clear Linux specific but this would apply to anyone running Kinoite, Forever OS or just happen to be using the Flathub version. Clear Linux runs better than Debian or Red Hat derived Linux in my opinion.

**Comment by thomas992** [comment]
sudo ln -s /usr/bin/npm /home/tommhnsn/.var/app/com.visualstudio.code/data/node_modules/bin/npm
sudo ln -s /usr/bin/node /home/tommhnsn/.var/app/com.visualstudio.code/data/node_modules/bin/node
 are also needed for node & npm on flathub might as well make a note of it in docs

**Comment by JoeRobich** [comment]
A lot has changed with O# sdk resolution since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
