### ISSUE TITLE
Not able to use Intellisense for dotnet core application

### ISSUE THREAD

**Issue by HimanshuNankani** [dotnet/vscode-csharp#5295]
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:

**Comment by froggej** [comment]
@HimanshuNankani  if your project is .net core or .net 5.0 or above, you need to install the .net 6.0 sdk for OmniSharp to work properly in v1.25 of the C# extension.

**Comment by JoeRobich** [comment]
Closing as answered.
