### ISSUE TITLE
Cannot bring Warning into English.

### ISSUE THREAD

**Issue by sdjfidn** [dotnet/vscode-csharp#5303]
## Environment data
`dotnet --info` output:.NET SDK (global.json を反映):
 Version:   6.0.301
 Commit:    43f9b18481

ランタイム環境:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.301\

Host (useful for support):
  Version: 6.0.6
  Commit:  7cca709db2

.NET SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.526 [C:\Program Files\dotnet\sdk]
  3.1.420 [C:\Program Files\dotnet\sdk]
  5.0.409 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]
  6.0.106 [C:\Program Files\dotnet\sdk]
  6.0.301 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
VS Code version:1.69.0
C# Extension version:v1.25.0

## Steps to reproduce

1.Install Japanese Extension
2.Install C# Extension
3.Follow https://stackoverflow.com/questions/68260004/how-to-change-language-in-warnings-in-vscode
(I did not find Windows-10 & Window 7 %APPDATA%ThomasCode and "C:\Users\me\AppData\Roaming.cache" in https://github.com/microsoft/vscode/issues/3)
4.Writing the wrong syntax
5..See warnings

## Expected  behavior
The warning is displayed in English.
## Actual behavior
Warnings are displayed in Japanese.
## Additional context
From https://github.com/microsoft/vscode/issues/154426

**Comment by JoeRobich** [comment]
This could be an issue with O# not respecting your locale setting. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
