### ISSUE TITLE
Intellisense not working using Unity on Linux - Could not locate MSBuild instance to register with OmniSharp.

### ISSUE THREAD

**Issue by theInfiTualEr** [dotnet/vscode-csharp#5304]
## Expected Behavior ##
Intellisense working. 

## Actual Behavior ##
Intellisense not working.

### OmniSharp log ###
<details>
Starting OmniSharp server at 7/9/2022, 9:06:34 AM
    Target: /path/to/project/unity-project/unity-project.sln

OmniSharp server started.
    Path: ~/.vscode/extensions/ms-dotnettools.csharp-1.24.4-linux-x64/.omnisharp/1.39.1-beta.11/run
    PID: 15042

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on fedora 36.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 0 MSBuild instance(s)
Could not locate MSBuild instance to register with OmniSharp.
</details>

### C# log ###
<details>
Getting latest OmniSharp version information
Downloading package 'Latest OmniSharp Version Information' (1 KB).................... Done!
</details>

## Environment information ##

**VSCode version**: 1.68.1
**C# Extension**: 1.24.4

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.106
 Commit:    e83a22f558

Runtime Environment:
 OS Name:     fedora
 OS Version:  36
 OS Platform: Linux
 RID:         fedora.36-x64
 Base Path:   /usr/lib64/dotnet/sdk/6.0.106/

Host (useful for support):
  Version: 6.0.6
  Commit:  7cca709db2

.NET SDKs installed:
  6.0.106 [/usr/lib64/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.6 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.6 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>

**EDIT:**

Problem also persists on **C# Extension: 1.25.0**, I just downgraded to check if it works.

**Comment by JoeRobich** [comment]
It is now recommended to use the Unity extension for VS Code.
