### ISSUE TITLE
Add (configurable) intellisense for prerelease packages

### ISSUE THREAD

**Issue by ivan-prodanov** [dotnet/vscode-csharp#531]
## Environment data

`dotnet --info` output: 1.0.0-preview2-003121
VS Code version: 1.2.1
C# Extension version: 1.2.1
## Steps to reproduce

Open package.json, start typing "IdentityServer4"
## Expected  behavior

IntelliSense shows "IdentityServer4" package.
## Actual behavior

IntelliSense shows all "IdentityServer3*" packages.
## Comment

How do we enable intellisense for prerelease packages?

**Comment by JoeRobich** [comment]
Closing this as we do not support project.json.
