### ISSUE TITLE
Doesn't detect changes for projects inside a symlink

### ISSUE THREAD

**Issue by lonix1** [dotnet/vscode-csharp#5312]
## Environment data
VS Code version: 1.69.1
C# Extension version: 1.25.0
dotnet: 6.0.302
os: linux

## OmniSharp log
None

## Steps to reproduce
My workspace contains multiple projects. It also contains a symlink, and inside that there are more projects.

If I make changes to projects inside the symlink, omnisharp won't detect them. So I close and reopen vscode to force it to reanalyse those projects. *Very very frustrating.*

(The symlink is there because in a large monorepo with many people and subsystems, that is a convenient way to work.)

## Expected  behavior
Omnisharp obviously can work with symlinks, because when vscode loads it detects all the projects in the symlink and analyses them normally.

So if they are changed, I'd expect omnisharp to detect the changes.

## Actual behavior
Omnisharp doesn't detect changes. I must restart to force it to reanalyse the symlinked projects.

## Additional context
None

**Comment by JoeRobich** [comment]
A lot has changed with VS Code file watching since this issue was opened. If you are still having problems, please open a new issue
