### ISSUE TITLE
unkonw error from omisharp with xaml

### ISSUE THREAD

**Issue by heartacker** [dotnet/vscode-csharp#5323]
## Environment data
名称: C#
ID: ms-dotnettools.csharp
说明: C# for Visual Studio Code (powered by OmniSharp).
版本: 1.25.0
发布者: Microsoft
VS Marketplace 链接: https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp
## Steps to reproduce

1. open vscode with wpf project
2. open wpf project with vs 2022
3. build and launch project in vs 2022
4. See error in vscode
5. cannot clear the errors anymore 

## Actual behavior
![xamleror](https://user-images.githubusercontent.com/1876302/181695398-54477290-c58f-4f3c-b3a5-f0c58ca79d7f.gif)

**Comment by heartacker** [comment]
anyupdate

**Comment by JoeRobich** [comment]
A lot has changed with the C# extension since this issue was opened. If you are still having problems, please open a new issue.
