### ISSUE TITLE
Different colors for namespaces, interfaces, classes, etc.?

### ISSUE THREAD

**Issue by aradalvand** [dotnet/vscode-csharp#5325]
Currently, almost all C# types (and also namespaces), including interfaces, enums, structs, and classes, appear in the same color in VS Code + OmniSharp. By default this is a light greenish kind of color:

![image](https://user-images.githubusercontent.com/26527405/181923664-5fbc7d73-3eb0-4f2a-9943-952cf5c3919f.png)

Whereas in Visual Studio, for example, the colors are different for each of these entities which enables you to better distinguish them visually:

![image](https://user-images.githubusercontent.com/26527405/181923751-cff7d21c-434b-4e68-91a7-61566e2cee8e.png)

I've been using C# with VS Code for a long time now, and I'm still not sure why this hasn't been implemented? Is it somehow not possible? I would say at the very least namespaces should have a different color (preferably white, to be consistent with Visual Studio) than the rest of these because namespaces are an entirely different construct. They're not even a type.

I also have semantic highlighting enabled in VS Code, if that matters.

Thanks.

**Comment by victormikael** [comment]
Hi, @aradalvand.

The C# extension provides the Visual Studio 2019 theme that solves this problem, I've been using it and it has greatly improved my experience.

Just set in: 

> Manage Icon > Color Theme > Visual Studio 2019 Dark

Or go to settings.json and add or edit this line:

> "workbench.colorTheme": "Visual Studio 2019 Dark"

**Comment by aradalvand** [comment]
Hi @victormikael. Thank you, that works, I didn't know that!
But it's weird that I have to change the theme in order to get this syntax highlighting, isn't it? What if I want to use a custom theme with this same syntax highlighting?
Wouldn't it be better if this syntax highlighting was the default for C#?!

**Comment by aradalvand** [comment]
Is this repo not actively maintained anymore?! I would like a response from the maintainers if possible, regarding why this isn't the default?!

**Comment by kemsky** [comment]
@aradalvand, see #5276

**Comment by McNerdius** [comment]
@aradalvand - you mentioned enabling semantic highlighting.  As you may know two things are required for this to work: A language extension to provide semantic information, and a theme capable of mapping the provided semantic information to colors.  I guess what you're getting at boils down to is, the C# extension would theoretically / automatically override VS Code's theme with one of its own upon install.  Seems like a bad idea IMO, but i do agree that the discoverability of these bundled themes could be much improved (as well as "omnisharp.enableEditorConfigSupport": true, "omnisharp.enableImportCompletion": true, "omnisharp.enableRoslynAnalyzers": true but i digress).  The alternative being that the VS Code team (and other theme makers) keep their themes up-to-date with C# and countless other languages' semantics, so that when/if a language extension is installed, it "just works".

**Comment by elianiva** [comment]
Just dropping by to say to whoever reading this thread, you can just [override the token colours manually](https://github.com/elianiva/dotfiles/blob/master/vscode/.config/Code/User/settings.json#L167-L176). I did it this way instead of changing the whole theme because the theme that comes with the C# extension doesn't really look good on any other language compared to the one that comes with vscode by default.

**Comment by JoeRobich** [comment]
Closing as answered.

**Comment by JobaDiniz** [comment]
> Just dropping by to say to whoever reading this thread, you can just [override the token colours manually](https://github.com/elianiva/dotfiles/blob/master/vscode/.config/Code/User/settings.json#L167-L176). I did it this way instead of changing the whole theme because the theme that comes with the C# extension doesn't really look good on any other language compared to the one that comes with vscode by default.

this link does not work anymore.

do you have the settings that you manually added?

**Comment by JoeRobich** [comment]
>this link does not work anymore. 

Here is a permalink to the token color customizations - https://github.com/elianiva/dotfiles/blob/d898fa92fca4407ccff5fed60c776be7e055705b/vscode/.config/Code/User/settings.json#L167-L176

**Comment by JobaDiniz** [comment]
Thanks, based on yours I converted more things:

```json
"editor.semanticTokenColorCustomizations": {
        "[Default Dark Modern]": {
            "rules": {
                "enum": "#b8d7a3",
                "interface": "#b8d7a3",
                "struct": "#86C691",
                "type": "#86C691",
                "namespace": "#dcdcdc",
                "operator": "#b4b4b4",
                "xmlDocCommentAttributeName": "#c8c8c8",
                "field.static": "#dcdcdc",
                "typeParameter": "#b0d79a",
                "property": "#dcdcdc",
                "constant.static": "#dcdcdc",
                "preprocessorText": "#dcdcdc",
                "macro": "#9b9b9b",
                "comment": "#45a64a"
            }
        }
    }
```

The only thing I could not change are the _punctuations_, like parenteses and curly braces. In `vscode` they change colors (yellow, pink, etc), but `Visual Studio` they are consistently the same (and I like that):

`visual studio`

![Image](https://github.com/user-attachments/assets/a1dac1f6-d0a6-4f4f-a8d4-5537456f2d83)

`vscode`

![Image](https://github.com/user-attachments/assets/b324341f-f079-481c-9bf7-e005e6ac5dcf)

**Comment by elianiva** [comment]
> Thanks, based on yours I converted more things:
> 
> "editor.semanticTokenColorCustomizations": {
>         "[Default Dark Modern]": {
>             "rules": {
>                 "enum": "#b8d7a3",
>                 "interface": "#b8d7a3",
>                 "struct": "#86C691",
>                 "type": "#86C691",
>                 "namespace": "#dcdcdc",
>                 "operator": "#b4b4b4",
>                 "xmlDocCommentAttributeName": "#c8c8c8",
>                 "field.static": "#dcdcdc",
>                 "typeParameter": "#b0d79a",
>                 "property": "#dcdcdc",
>                 "constant.static": "#dcdcdc",
>                 "preprocessorText": "#dcdcdc",
>                 "macro": "#9b9b9b",
>                 "comment": "#45a64a"
>             }
>         }
>     }
> 
> The only thing I could not change are the _punctuations_, like parenteses and curly braces. In `vscode` they change colors (yellow, pink, etc), but `Visual Studio` they are consistently the same (and I like that):
> 
> `visual studio`
> 
> ![Image](https://github.com/user-attachments/assets/a1dac1f6-d0a6-4f4f-a8d4-5537456f2d83)
> 
> `vscode`
> 
> ![Image](https://github.com/user-attachments/assets/b324341f-f079-481c-9bf7-e005e6ac5dcf)

you can turn it off in the settings, it's called rainbow parentheses or something like that
