### ISSUE TITLE
Server timeout in github codespaces.

### ISSUE THREAD

**Issue by spy653** [dotnet/vscode-csharp#5330]
## Environment data
`dotnet --info` output:
```
.NET SDK (reflecting any global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /opt/dotnet/6.0.201/sdk/6.0.201/

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  3.1.417 [/home/codespace/.dotnet/sdk]
  6.0.201 [/home/codespace/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.23 [/home/codespace/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.417 [/home/codespace/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [/home/codespace/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.201 [/home/codespace/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.23 [/home/codespace/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.417 [/home/codespace/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [/home/codespace/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.201 [/home/codespace/.dotnet/shared/Microsoft.NETCore.App]
```
VS Code version: 1.69.2
C# Extension version: 1.25.0

## OmniSharp log
```
Starting OmniSharp server at 8/4/2022, 3:08:58 PM
    Target: /workspaces/Zelda-Core

OmniSharp server started with .NET 6.0.201
.
    Path: /home/codespace/.vscode-remote/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/.omnisharp/1.39.0-net6.0/OmniSharp.dll
    PID: 8013

[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).

```

## Steps to reproduce
1. Open Command Pallet,
2. ">omniSharp: Restart OmniSharp"
3. Observe timeout

## Expected  behavior
Intellisense to populate with appropriate subclasses and method arguments.

## Actual behavior
Auto complete list only populates with snippets and words common in the document.

## Additional context
Problem arose suddenly yesterday.
I am running in a standard github codespace, and have attempted many tests disabling all other extensions.
I have set the timeout period up to 20 minutes, no help.

I have also rebuilt my container and reinstalled visualstudio code.
I am unsure of how I can dig deeper into this issue.

**Comment by spy653** [comment]
Additional:
I have observed the same problem on my PC and laptop.

**Comment by validide** [comment]
Same issue for me on both Windows and Linux (reported on #5302).

**Comment by RDavis3000** [comment]
anyone looking at this? Any solution? Or do I just go back to Visual Studio?

**Comment by RDavis3000** [comment]
I had the same issue; seems the problem is that OmniSharp is trying to execute \OmniSharp.dll
If you go to settings Omnisharp:path and put the full path to OmniSharp.exe it works.
In your example @spy653  it would be :
** /home/codespace/.vscode-remote/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/.omnisharp/1.39.0-net6.0/OmniSharp.exe**
So far its working for me (on Windows), no idea how its going to handle an update

**Comment by spy653** [comment]
> anyone looking at this? Any solution? Or do I just go back to Visual Studio?

I went and bought rider, I do miss my money but I'd rather have reliable tools.

**Comment by spy653** [comment]
> I had the same issue; seems the problem is that OmniSharp is trying to execute \OmniSharp.dll
> If you go to settings Omnisharp:path and put the full path to OmniSharp.exe it works.
> In your example @spy653  it would be :
> ** /home/codespace/.vscode-remote/extensions/ms-dotnettools.csharp-1.25.0-linux-x64/.omnisharp/1.39.0-net6.0/OmniSharp.exe**
> So far its working for me (on Windows), no idea how its going to handle an update

Hopefully someone finds this helpful!

**Comment by pnocera** [comment]
Unchecking Omnisharp:Wait For Debugger setting made it work for me.

**Comment by validide** [comment]
> Unchecking Omnisharp:Wait For Debugger setting made it work for me.

I can confirm this works but I do not know if it's intended behavior or not. At the moment it feels like a workaround.

**Comment by JoeRobich** [comment]
A lot has changed with O# project loading since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
