### ISSUE TITLE
Build not working on MacOS Monterey on version 1.25.0

### ISSUE THREAD

**Issue by danilie7** [dotnet/vscode-csharp#5346]
## Steps to Reproduce ##

1. Open Project in VS Code
2. Build project (CMD+SHIFT+B)

## Expected Behavior ##
Project should build
## Actual Behavior ##
The following output appears in terminal:
Executing task: dotnet build /Users/idan/Documents/GitHub/Reactivities/API/API.csproj /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary 

execvp(3) failed.: Permission denied

 *  The terminal process "dotnet 'build', '/Users/idan/Documents/GitHub/Reactivities/API/API.csproj', '/property:GenerateFullPaths=true', '/consoleloggerparameters:NoSummary'" failed to launch (exit code: 1). 
 *  Terminal will be reused by tasks, press any key to close it. 

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.70.1
**C# Extension**: 1.25.0

<details><summary>Mono Information</summary>
        There is a problem with running OmniSharp on mono: Error: Unable to find Mono. Ensure that Mono's '/bin' folder is added to your environment's PATH variable.</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.5
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.400/

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: arm64
  Commit:       55fb7ef977

.NET SDKs installed:
  6.0.400 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|black|Jaakko|0.12.0|
|copilot|GitHub|1.41.6508|
|copilot-theme|benjaminbenais|1.0.0|
|csharp|ms-dotnettools|1.25.0|
|csharpextensions|kreativ-software|1.7.1|
|darkpp-italic|idbartosz|0.2.0|
|es7-react-js-snippets|dsznajder|4.4.3|
|freecodecamp-dark-vscode-theme|freeCodeCamp|1.0.0|
|gitlens|eamodio|12.1.2|
|material-icon-theme|PKief|4.19.0|
|path-intellisense|christian-kohler|2.8.1|
|simple-react-snippets|burkeholland|1.2.6|
|spellright|ban|3.0.82|
|vsc-community-material-theme|Equinusocio|1.4.4|
|vscode-autohotkey-plus-plus|mark-wiemer|2.8.4|
|vscode-nuget-gallery|patcx|0.0.24|
|vscode-peacock|johnpapa|4.1.0|
|vscode-sqlite|alexcvzz|0.14.1|;

</details>

**Comment by JoeRobich** [comment]
A lot has changed with since this issue was opened. If you are still having problems, please open a new issue.
