### ISSUE TITLE
No "null check" code actions are available for method's arguments of nullable ref type

### ISSUE THREAD

**Issue by tvardero** [dotnet/vscode-csharp#5351]
## Issue Description ##
Code refactor is provided for non-nullable reference types in method arguments, containing suggestions to add null checks:
![image](https://user-images.githubusercontent.com/45442278/185784107-cc4f38ff-6919-41a1-baf2-d90c55fe0edf.png)

They are not provided for nullable reference types:
![image](https://user-images.githubusercontent.com/45442278/185784090-b975bfff-06a2-4f66-8361-d4d6ba05b462.png)

## Environment information ##

**VSCode version**: 1.70.2
**C# Extension**: 1.25.0

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.303
 Commit:    7494fee64a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.303\

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  3.1.422 [C:\Program Files\dotnet\sdk]
  6.0.108 [C:\Program Files\dotnet\sdk]
  6.0.300 [C:\Program Files\dotnet\sdk]
  6.0.303 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.25.0|
|gitlens|eamodio|12.1.2|
|user-secrets|adrianwilczynski|2.0.1|
|vsc-material-theme|Equinusocio|33.5.0|
|vsc-material-theme-icons|equinusocio|2.3.1|
|vscode-eslint|dbaeumer|2.2.6|
|vscode-nuget-gallery|patcx|0.0.24|
|vscode-pull-request-github|GitHub|0.48.1|
|vscode-solution-explorer|fernandoescolar|0.5.0|;

</details>

**Comment by JoeRobich** [comment]
This is by design in Roslyn. See https://github.com/dotnet/roslyn/blob/e75664fa1ebe4b064ea84814a006b2d6e7fe2e11/src/Features/Core/Portable/InitializeParameter/AbstractAddParameterCheckCodeRefactoringProvider.cs#L249

If you want to request a change in this behavior, please open an issue at https://github.com/dotnet/roslyn/issues
