### ISSUE TITLE
Formatter - remove extra newlines on save

### ISSUE THREAD

**Issue by devonpmack** [dotnet/vscode-csharp#5360]
## Is your feature request related to a problem? Please describe.

In prettier for other languages, it will auto remove extra newlines. This saves developers time and keeps style consistent.

### Example 1: (space between brackets)
```diff
public class ConnectToServer : MonoBehaviour {
  public override void Hello() {
    SceneManager.LoadScene("Lobby");
  }
+
+
}
```

This code on save should become
```diff
public class ConnectToServer : MonoBehaviour {
  public override void Hello() {
    SceneManager.LoadScene("Lobby");
  }
}
```

### Example 2: (more than one newline in code)

```diff
public class ConnectToServer : MonoBehaviour {
  public override void Hello() {
    SceneManager.LoadScene("Lobby");

+
    Hello();
  }
}
```

This code on save should become
```diff
public class ConnectToServer : MonoBehaviour {
  public override void Hello() {
    SceneManager.LoadScene("Lobby");

    Hello();
  }
}
```

## Applicable Scenarios

On format

## Describe alternatives you've considered

A different vscode extension to do it after save?

**Comment by JoeRobich** [comment]
This is a request for the Roslyn formatter. An issue can be opened at https://github.com/dotnet/roslyn/issues
