### ISSUE TITLE
C# Extension Output "Failed to spawn 'dotnet --info'" - False Positive?

### ISSUE THREAD

**Issue by vindicatorr** [dotnet/vscode-csharp#5363]
## Issue Description ##
Commit 92d998f9eb046f733ba87af3873615caa2c3527a
I built vscode-oss yesterday after fetching/pulling master --depth 1, and I seem to recall the omnisharp master I built months ago that was still used with the latest vscode-oss worked fine with no issues.

Today I built omnisharp-vscode after fetching/pulling master --depth 1, and when I installed the .vsix and ran vscode, I got the `The .NET Core SDK cannot be located...` notification and saw the error in the title.

But I'm questioning whether it's a false-positive because everything seems to be working.
I get intellisense, and it compiles and runs, so I'm not sure what to take away from this.

Full-disclosure, I DO make a bunch of edits just so I can build the latest. In other words, if there's errors in a build, I work through them. Or I may not want to have the build keep redownloading stuff when I do a rebuild, so I make edits pointing to the downloads and let the build continue with those.
eg: ./src/packageManager/downloadAndInstallPackages.ts
```
      //comment out:
       import { PackageError } from './PackageError';
       import { NestedError } from "../NestedError";
       import { DownloadFile } from './FileDownloader';
       import { InstallZip } from './ZipInstaller';
       import { touchInstallFile, InstallFileType, deleteInstallFile, installFileExists } from "../common";
       import { InstallationFailure, IntegrityCheckFailure } from "../omnisharp/loggingEvents";
       import { mkdirpSync } from "fs-extra";
       import { PackageInstallStart } from "../omnisharp/loggingEvents";
       In "downloadAndInstallPackages", just comment everything and return true
```
Or pointing "package.json" to use "netcoredbg" that I just built. The same sort of changes I did several months ago when I did my same steps (had to make adjustments this time because of new changes that affected my changes), and I didn't have this "failed to spawn" issue with that build.

In the logs below, you can see the contradiction with `Located 2 MSBuild instance(s)` finding stuff, but later `A valid dotnet installation could not be found.`.

## Steps to Reproduce ##
Build omnisharp-vscode and install the .vsix, then run vscode for a C# program.

## Expected Behavior ##
C# runs `dotnet --info` because the program DOES exist in the PATH.

## Actual Behavior ##
C# output contains `Failed to spawn 'dotnet --info`

### OmniSharp log ###
<details>Starting OmniSharp server at 9/2/2022, 10:46:45 PM
    Target: <pathToProject>

OmniSharp server started with .NET 7.0.100-preview.4.22252.9
 (/opt/dotnet/dotnet).
    Path: /home/userName/.vscode-oss/extensions/ms-dotnettools.csharp-1.25.1/.omnisharp/1.39.1-net6.0/OmniSharp.dll
    PID: 2220701

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Unknown 0.0 (Unknown)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: .NET Core SDK 7.0.100 17.3.0 - "/opt/dotnet/sdk/7.0.100-preview.4.22252.9/"
            2: .NET Core SDK 6.0.200 17.1.0 - "/opt/dotnet/sdk/6.0.200/"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: .NET Core SDK 7.0.100 17.3.0 - "/opt/dotnet/sdk/7.0.100-preview.4.22252.9/"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '<pathToProject>'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '<pathToProject>/<project.csproj>'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '<pathToProject>'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Did not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '<pathToProject>' on host 2220586.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: <pathToProject>/<project.csproj>
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '<pathToProject>/<project.csproj>'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '<pathToProject>/<project.csproj>'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: <project>
</details>

### C# log ###
<details>Installing C# dependencies...
Platform: linux, x86_64, name=arch, version=unknown

Finished

Failed to spawn 'dotnet --info'</details>

## Environment information ##

**VSCode version**: 1.72.0
**C# Extension**: 1.25.1

<details><summary>Mono Information</summary>
        There is a problem with running OmniSharp on mono: Error: Unable to find Mono. Ensure that Mono's '/bin' folder is added to your environment's PATH variable.</details>
<details><summary>Dotnet Information</summary>
A valid dotnet installation could not be found.</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.8.9|
|cloudcode|googlecloudtools|1.21.0-insiders.1|
|csharp|ms-dotnettools|1.25.1|
|vscode-docker|ms-azuretools|1.22.0|;

</details>

EDIT0:
I'll also include the output for Extension Host when enabling omnisharp:
```
[2022-09-03 00:44:42.400] [exthost] [info] ExtensionService#_doActivateExtension ms-dotnettools.csharp, startup: false, activationEvent: 'onLanguage:csharp'
[2022-09-03 00:44:49.513] [exthost] [warning] DiagnosticCollection with name 'csharp' does already exist.
[2022-09-03 00:44:49.560] [exthost] [error] [ms-dotnettools.csharp] provider FAILED
[2022-09-03 00:44:49.561] [exthost] [error] Problem invoking 'GetCodeActions' on OmniSharp server: Error: Request /v2/getcodeactions cancelled, id: undefined
```

**Comment by JoeRobich** [comment]
A lot has changed with the extension since this issue was opened. If you are still having problems, please open a new issue
