### ISSUE TITLE
C# Extension does not work in alpine container

### ISSUE THREAD

**Issue by Torkolis** [dotnet/vscode-csharp#5368]
Hi I am currently trying to get C# Extension with intellisense to get working in a container with this image: mcr.microsoft.com/dotnet/sdk:6.0-alpine

I can't even do the `CSharp: Report an issue` because it shows me this error: 
![image](https://user-images.githubusercontent.com/98939160/189081425-a7f9e2c2-9609-44a9-98ae-fa19f7835bd7.png)
So I will try to fill out myself

## Environment data
`dotnet --info` output:
<details>.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Runtime Environment:
 OS Name:     alpine
 OS Version:  3.16
 OS Platform: Linux
 RID:         alpine.3.16-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.400/

global.json file:
  /home/dotnet/dotnet/FirstProject/global.json

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  6.0.400 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info</details>
VS Code version: 1.71.0
C# Extension version: 1.25.0

## C# log
[ERROR]: C# Extension failed to get platform information.

**Comment by Zeddicus414** [comment]
This seems similar to what I've experienced.
https://github.com/OmniSharp/omnisharp-vscode/issues/5348

**Comment by JoeRobich** [comment]
The C# extension now supports Alpine.
