### ISSUE TITLE
Support launching .NET MAUI projects on Windows and Mac

### ISSUE THREAD

**Issue by romanfurinda** [dotnet/vscode-csharp#5393]
I want to meake MAUI project by VS CODE from template net6 or net7. When start by dotnet CLI application working, but from omnisharp still endding in debbug console  : The program '[34012] ContextMenuSample.dll' has exited with code -1073741189 (0xc000027b).

Loaded 'C:\Users\furindar\Documents\OneDrive\OFZ\Codovanie\mauitest\maui-samples\7.0\Fundamentals\ContextMenu\ContextMenuSample\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\System.Private.CoreLib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Users\furindar\Documents\OneDrive\OFZ\Codovanie\mauitest\maui-samples\7.0\Fundamentals\ContextMenu\ContextMenuSample\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\ContextMenuSample.dll'. Symbols loaded.
Loaded 'C:\Users\furindar\Documents\OneDrive\OFZ\Codovanie\mauitest\maui-samples\7.0\Fundamentals\ContextMenu\ContextMenuSample\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\System.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Users\furindar\Documents\OneDrive\OFZ\Codovanie\mauitest\maui-samples\7.0\Fundamentals\ContextMenu\ContextMenuSample\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\WinRT.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Users\furindar\Documents\OneDrive\OFZ\Codovanie\mauitest\maui-samples\7.0\Fundamentals\ContextMenu\ContextMenuSample\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\System.Runtime.InteropServices.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Users\furindar\Documents\OneDrive\OFZ\Codovanie\mauitest\maui-samples\7.0\Fundamentals\ContextMenu\ContextMenuSample\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\System.Collections.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Users\furindar\Documents\OneDrive\OFZ\Codovanie\mauitest\maui-samples\7.0\Fundamentals\ContextMenu\ContextMenuSample\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\System.Collections.Concurrent.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Users\furindar\Documents\OneDrive\OFZ\Codovanie\mauitest\maui-samples\7.0\Fundamentals\ContextMenu\ContextMenuSample\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\System.Threading.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Users\furindar\Documents\OneDrive\OFZ\Codovanie\mauitest\maui-samples\7.0\Fundamentals\ContextMenu\ContextMenuSample\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\Microsoft.WinUI.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Users\furindar\Documents\OneDrive\OFZ\Codovanie\mauitest\maui-samples\7.0\Fundamentals\ContextMenu\ContextMenuSample\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\System.Runtime.CompilerServices.Unsafe.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Users\furindar\Documents\OneDrive\OFZ\Codovanie\mauitest\maui-samples\7.0\Fundamentals\ContextMenu\ContextMenuSample\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\System.Private.Uri.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Users\furindar\Documents\OneDrive\OFZ\Codovanie\mauitest\maui-samples\7.0\Fundamentals\ContextMenu\ContextMenuSample\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\System.ObjectModel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Users\furindar\Documents\OneDrive\OFZ\Codovanie\mauitest\maui-samples\7.0\Fundamentals\ContextMenu\ContextMenuSample\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\System.ComponentModel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Users\furindar\Documents\OneDrive\OFZ\Codovanie\mauitest\maui-samples\7.0\Fundamentals\ContextMenu\ContextMenuSample\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\System.Numerics.Vectors.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Users\furindar\Documents\OneDrive\OFZ\Codovanie\mauitest\maui-samples\7.0\Fundamentals\ContextMenu\ContextMenuSample\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\System.Security.Cryptography.Algorithms.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Users\furindar\Documents\OneDrive\OFZ\Codovanie\mauitest\maui-samples\7.0\Fundamentals\ContextMenu\ContextMenuSample\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\System.Security.Cryptography.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Users\furindar\Documents\OneDrive\OFZ\Codovanie\mauitest\maui-samples\7.0\Fundamentals\ContextMenu\ContextMenuSample\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\System.Security.Cryptography.Csp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Users\furindar\Documents\OneDrive\OFZ\Codovanie\mauitest\maui-samples\7.0\Fundamentals\ContextMenu\ContextMenuSample\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\System.Security.Cryptography.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Users\furindar\Documents\OneDrive\OFZ\Codovanie\mauitest\maui-samples\7.0\Fundamentals\ContextMenu\ContextMenuSample\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\System.Linq.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The program '[34012] ContextMenuSample.dll' has exited with code -1073741189 (0xc000027b).

**Comment by gregg-miskelly** [comment]
That is `STATUS_STOWED_EXCEPTION` which means that something in your process is catching an exception and aborting the process. I think the issue is that the C# extension doesn't understand how to launch a MAUI application, which would be significant work to make work. But let me double check this.

**Comment by romanfurinda** [comment]
I AM the begginer with C#, i do not like visual studio 2019-2022. I like VS CODE. 
I installed net 6 last version, I try net 7 last version. I write command : dotnet new maui....was ok. 
![image](https://user-images.githubusercontent.com/72338337/194723118-3f3b5160-176a-496d-a11a-536cbee91fa1.png)
Application working. 
I want to debbuging  with with extentions c:\Users\work\.vscode\extensions\ms-dotnettools.csharp-1.25.0-win32-x64\.
It working wit standard form application.
There is application from standard template without bin and obj directories.
[testMAUIpodpis.zip](https://github.com/OmniSharp/omnisharp-vscode/files/9740091/testMAUIpodpis.zip)
How I have to fixed ?

**Comment by romanfurinda** [comment]
> That is `STATUS_STOWED_EXCEPTION` which means that something in your process is catching an exception and aborting the process. I think the issue is that the C# extension doesn't understand how to launch a MAUI application, which would be significant work to make work. But let me double check this.

I AM the begginer with C#, i do not like visual studio 2019-2022. I like VS CODE.
I installed net 6 last version, I try net 7 last version. I write command : dotnet new maui....was ok.
image
Application working.
I want to debbuging with with extentions c:\Users\work.vscode\extensions\ms-dotnettools.csharp-1.25.0-win32-x64.
It working wit standard form application.
There is application from standard template without bin and obj directories.
[testMAUIpodpis.zip](https://github.com/OmniSharp/omnisharp-vscode/files/9740091/testMAUIpodpis.zip)
How I have to fixed ?

**Comment by gregg-miskelly** [comment]
.NET Maui applications run as packaged applications on Windows, which means that debuggers need to do a lot of work to support launching them. I am turning this issue into a feature request to support them. I would highly recommend using for Visual Studio for MAUI applications. The one way you could use Visual Studio code would be to configure a task to run them, and then attach the debugger to the running process.

**Comment by jmgalzate** [comment]
Hi there! I know the Feature Request is still pending. I just added myself to the watchers' list (considering Visual Studio for MAC will be disabled. 

This is the profile I have configured in my launch.json file. The debugger recognizes the profile, but the application is not launched after deployment. I tried to add the properties "program" or "app" but no one of them are part of the maui type. 

```
        {
            "name": ".NET MAUI",
            "type": "maui",
            "request": "launch",
            "preLaunchTask": "maui: Build",
            "targetFramework": "net7.0-maccatalyst",
            "project": "${workspaceFolder}/myapp/myapp.csproj",
            "configuration": "Debug"
        },
```

Hugs!

**Comment by gregg-miskelly** [comment]
Hi @jmgalzate, I am not that familiar with the `maui` debugger, but issues are being tracked in the [vscode-dotnettools](https://github.com/microsoft/vscode-dotnettools/issues) repo, so I would suggest opening an issue there (assuming you don't see something already).

**Comment by gregg-miskelly** [comment]
Now that the `maui` debugger exists, I don't think this issue should continue to exist: MAUI support will come from the MAUI extension rather than the C# extension itself.
