### ISSUE TITLE
Linter is outdated

### ISSUE THREAD

**Issue by ayalamac** [dotnet/vscode-csharp#5399]
Hello, this code throws a warning:

```
namespace BuberDinner.Contracts.Authentication;
public record AuthenticationResponse(
    Guid Id,
    string FirstName,
    string LastName,
    string Email,
    string Token
);
```
Warning is "Move 'AuthenticationResponse' into a named namespace.

**Comment by JoeRobich** [comment]
@ayalamac Can you provide the OmniSharp Log from the VS Code Output pane? Which version of the SDK are you using?
