### ISSUE TITLE
`launchUrl` from launchSettings.json should be used

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/vscode-csharp#5416]
Follow the instructions at the [Microsoft Web API tutorial-Create a web project](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-6.0&tabs=visual-studio-code#create-a-web-project-1)

```
dotnet new webapi -o TodoApi
cd TodoApi
code -r ../TodoApi
```

^F5 and it launches a browser to `http:localhost::<port>` not ` "launchUrl": "swagger",` from  `launchSettings.json`

That's not a good experience for our customers.

VS output has: 
```
Using launch settings from 'C:\tmp\TodoApi\Properties\launchSettings.json' [Profile 'http']...
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5072
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
```

cc @TAGC

See [this SO that reports the same problem](https://stackoverflow.com/questions/55996668/launchsettings-json-launchurl-doesnt-work-api-values)

Dup of  closed #2935

**Comment by gregg-miskelly** [comment]
@Rick-Anderson Currently VS Code doesn't use `launchUrl` from launchSettings.json. Doing so is a fairly significant effort.

In the mean time, the way to make this work is to change launch.json. Add `uriFormat` to `serverReadyAction`:

```json
            "serverReadyAction": {
                "action": "openExternally",
                "pattern": "\\bNow listening on:\\s+(https?://\\S+)",
                "uriFormat": "%s/swagger"
            },
```

**Comment by Rick-Anderson** [comment]
@gregg-miskelly  but we have dozens of tutorials based on `dotnet new` and it's a significant effort for the 50K + VSC customers every month who try our tutorials to make this change. It's a security best practice which I think would warrant the significant effort.

**Comment by gregg-miskelly** [comment]
This issue is now fixed when using the `dotnet` debugger type, which is what one will get by default when using C# Dev Kit in a solution without a launch.json. So I am resolving this as fixed.
