### ISSUE TITLE
Choose the command that is triggered when `ctrl-click` is pressed in the code editor

### ISSUE THREAD

**Issue by nZeus** [dotnet/vscode-csharp#5428]
## Is your feature request related to a problem? Please describe.
When I use VS Code with a .NET/C# project, and when I want to navigate in the source code, I want to be able to easily navigate to a method **implementation**. For this it seems natural to press `CTRL+Click`, but it triggers the `Go to Definition` command.

Right now there is no way how to go to the implementation with the mouse...

This seems to be a strange decision to use `Go to Definition` as the default action on `Ctrl+click`. In the majority of the scenarios, developers want to navigate to the implementation of a type/method.

I think it would be so nice to have an option in the settings to select the default behavior.

## Describe the solution you would like
In the settings of OmniSharp:
* Add a dropdown "Ctrl+click command" with the following options
  * goToDefinitions (default?)
  * goToImplementations

**Comment by nZeus** [comment]
no one? 😢

**Comment by JoeRobich** [comment]
This would be a request for Microsoft/vscode as the Ctrl+click behavior is owned by the Editor itself.
