### ISSUE TITLE
Intelli sense with Source Code Generators in Omnisharp

### ISSUE THREAD

**Issue by abdollahkahne** [dotnet/vscode-csharp#5455]
### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.73.1
**C# Extension**: 1.25.1

<details><summary>Mono Information</summary>
        There is a problem with running OmniSharp on mono: Error: Unable to find Mono. Ensure that Mono's '/bin' folder is added to your environment's PATH variable.</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.403
 Commit:    2bc18bf292

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.403/

global.json file:
  Not found

Host:
  Version:      6.0.11
  Architecture: x64
  Commit:       943474ca16

.NET SDKs installed:
  6.0.403 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.11 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|asp-net-core-switcher|adrianwilczynski|2.0.2|
|auto-using|Fudge|0.7.15|
|csharp|ms-dotnettools|1.25.1|
|csharpextensions|kreativ-software|1.7.3|
|data-workspace-vscode|ms-mssql|0.3.0|
|docomment|k--kato|0.1.31|
|msbuild-project-tools|tintoy|0.4.9|
|mssql|ms-mssql|1.16.0|
|sharppad|jmazouri|1.1.0|
|sql-bindings-vscode|ms-mssql|0.3.0|
|sql-database-projects-vscode|ms-mssql|0.19.0|;

</details>
I am using Source Generation in VSCode and It appears that after each change in source code in Generator which require intellisense (for example adding a method or changing a method signature), it needs to select the project/solution from list of project in omnisharp again in order to it reflect the changes in Intelli sens. If my issue is not clear enough, Let me know to attach a sample. 
Thanks

**Comment by abdollahkahne** [comment]
As another behaviour which observed in this situation, after changing the source code in generator, if we do not change the main code (client which uses Source Generator), these changes do not reflect in generated dll built and returned from dotnet run command. Although this behaviour may be considered normal/useful in case of built time but needs attention.

**Comment by JoeRobich** [comment]
A lot has changed with O# source generators since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
