### ISSUE TITLE
Reporting errant code with red squiggly that is not errant

### ISSUE THREAD

**Issue by ghost** [dotnet/vscode-csharp#5458]
Please paste the output from your clipboard
![OmnisharpBug](https://user-images.githubusercontent.com/43715016/201531187-6ab76f5f-805f-4142-95d7-78dbc8317f51.jpg)
Getting red squiggly line under code that is not errant.  See uploaded screenshot.

**Comment by JoeRobich** [comment]
Closed due to lack of activity.
