### ISSUE TITLE
Can's install C# Extension from a downaloaded file offline

### ISSUE THREAD

**Issue by Nefcanto** [dotnet/vscode-csharp#5470]
I do not have C# extension installed, thus I can't use `CSharp: Report an issue` command. I have to write this issue manually.

## Environment data
`dotnet --info` output:

.NET SDK (reflecting any global.json):
 Version:   6.0.401
 Commit:    0906eae6f8

Runtime Environment:
 OS Name:     debian
 OS Version:  11
 OS Platform: Linux
 RID:         debian.11-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.401/

global.json file:
  Not found

Host:
  Version:      6.0.9
  Architecture: x64
  Commit:       163a63591c

.NET SDKs installed:
  6.0.401 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.9 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

---

VS Code version: 1.73.1
C# Extension version: latest version, currently 1.25.2

## OmniSharp log
No log

## Steps to reproduce

1- Download C# extension from [Marketplace](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp) for **Linux x64**. [Current download link](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-dotnettools/vsextensions/csharp/1.25.2/vspackage?targetPlatform=linux-x64)
2- Open VS Code
3- Go to the extensions panel
4- From **View and More Actions** menu, choose **Install from VSIX...**
5- You should see this error: `Corrupt ZIP: end of central directory record signature not found`

## Expected  behavior
We should be able to download the offline `vsix` file, and download it on a VS Code that is not connected to the internet.

## Actual behavior
We get zip error. We can't install C# extension from a downloaded `vsix` file.

**Comment by Wamiq319** [comment]
i am also facing same issues

**Comment by JoeRobich** [comment]
A lot has changed with how the C# extension is packaged since this issue was opened. If you are still having problems, please open a new issue.

**Comment by Nefcanto** [comment]
@JoeRobich, really? Did you answer after 2 years? Awesome.
