### ISSUE TITLE
C# code formatting option to insert space after "IF" statemnt

### ISSUE THREAD

**Issue by alex-jitbit** [dotnet/vscode-csharp#5482]
I would like the code formatter to insert space after `if` just like the "big" Visual Studio does: `if (a == b)`

I created an `~/.omnisharp/onmisharp.json` file and added this:

```json
{
	"FormattingOptions": {
		"SpaceAfterControlFlowStatementKeyword": true
	}
}
```

However this does not work. Either `if` is not considered a control-flow statement (bug?) or there's some other option I need to set?

UPDATE: seems like the problem is with the braceless if-blocks only

```csharp
if(condition)
    DoTuff();
```

Fix this bug please.

**Comment by Thaina** [comment]
Is it because vscode csharp now don't use omnisharp anymore?

I try to find is there any option to add config to current formatter. But of there are none I think maybe we should just readopt `omnisharp.json`

**Comment by Thaina** [comment]
Also some suggest using `.editorconfig` file

https://github.com/dotnet/vscode-csharp/issues/6215

**Comment by alex-jitbit** [comment]
Actually, it looks like enabling `"editor.formatOnType": true` has helped.

**Comment by JoeRobich** [comment]
@alex-jitbit Happy you are seeing your formatting choices being respected. Going to close this issue out.

I recommend whether you are using O# or Roslyn LSP to configure your code style with an .editorconfig (see https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-style-rule-options). They both use the same formatter underneath and it respects your .editorconfig options. Also, the VS Code settings "editor.formatOnType", "editor.formatOnSave", and "editor.formatOnPaste" options are all useful to keep your code formatted.
