### ISSUE TITLE
c# project load failed in Unity 2022.2 (because of Unity.SourceGenerators.dll)

### ISSUE THREAD

**Issue by coeyes** [dotnet/vscode-csharp#5494]
## Environment data
`dotnet --info` output:
```
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  3.1.404 [C:\Program Files\dotnet\sdk]
  5.0.401 [C:\Program Files\dotnet\sdk]
  6.0.403 [C:\Program Files\dotnet\sdk]
  7.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  arm64 [C:\Program Files\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\arm64\InstallLocation]
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found
```

VS Code version: 1.73.1
C# Extension version: v1.25.1

## OmniSharp log
```
...
[fail]: OmniSharp.MSBuild.ProjectManager
        Failure while loading the analyzer reference 'Unity.SourceGenerators': Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
...
```

## Steps to reproduce

1. open c# project in Unity 2022.2

```
void Start()
{
    abc = 20;
}
```

2. quick fix (code action) under 'abc'  (shortcut key: ctrl+.)

## Expected  behavior

- should be load project well with no error.
- all quick fix (code action) should be working.

## Actual behavior

- code completion is worked well.
- but some quick fix (code action) is not working. ( ex> generate field or property, import using)

## Description

`Unity.SourceGenerators.dll` compiled with netstandard 2.1
but `<TargetFramework>` of Unity project file (.csproj) is 4.7.1
(because omnisharp with unity must be use with option: "omnisharp.useModernNet": false )

I tried to remove these lines of Assembly-Csharp.csproj
```
..
<ItemGroup>
    <Analyzer Include="E:\UnityEditors\2022.2.0f1\Editor\Data\Tools\Unity.SourceGenerators\Unity.SourceGenerators.dll" />
    <Analyzer Include="E:\UnityEditors\2022.2.0f1\Editor\Data\Tools\Unity.SourceGenerators\Unity.Properties.SourceGenerator.dll" />
  </ItemGroup>
..
```
and restart omnisharp, then errors disappers and quick fix works well.
but Unity always regenerate those lines.
I think omnisharp should provide option to bypass `<Analyzer>` items, or fix this problem.

thanks.

**Comment by winstxnhdw** [comment]
Having this issue as well. It seems to break Omnisharp completely. Code formatting stops working.

**Comment by KerkDovan** [comment]
Found fix in [this Unity forum post](https://forum.unity.com/threads/vs-22-throws-cs8032-after-updating-to-tech-stream-2022-2-0f1.1372701/#post-8715939).

Put the file with this code into `Assets/Editor` folder of the Unity project:
```C#
using System.Linq;
using System.Xml.Linq;
using UnityEditor;

public class CodeActionsRestorer : AssetPostprocessor
{
    private static string OnGeneratedCSProject(string path, string content)
    {
        var document = XDocument.Parse(content);
        document.Root.Descendants()
            .Where(x => x.Name.LocalName == "Analyzer")
            .Where(x => x.Attribute("Include").Value.Contains("Unity.SourceGenerators"))
            .Remove();
        return document.Declaration + System.Environment.NewLine + document.Root;
    }
}
```

**Comment by ozanyasindogan** [comment]
> Found fix in [this Unity forum post](https://forum.unity.com/threads/vs-22-throws-cs8032-after-updating-to-tech-stream-2022-2-0f1.1372701/#post-8715939).
> 
> Put the file with this code into `Assets/Editor` folder of the Unity project:
> 
> ```cs
> using System.Linq;
> using System.Xml.Linq;
> using UnityEditor;
> 
> public class CodeActionsRestorer : AssetPostprocessor
> {
>     private static string OnGeneratedCSProject(string path, string content)
>     {
>         var document = XDocument.Parse(content);
>         document.Root.Descendants()
>             .Where(x => x.Name.LocalName == "Analyzer")
>             .Where(x => x.Attribute("Include").Value.Contains("Unity.SourceGenerators"))
>             .Remove();
>         return document.Declaration + System.Environment.NewLine + document.Root;
>     }
> }
> ```

You basically removed the code generator here :)

**Comment by JoeRobich** [comment]
A lot has changed with O# source generator support since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues. It is recommended to use the Unity extension for VS Code.
