### ISSUE TITLE
Error occurred in loading omnisharp from omnisharp.path Could not start the server due to Error: Invalid OmniSharp version - "omnisharp.path": "latest"

### ISSUE THREAD

**Issue by Nidhiksha** [dotnet/vscode-csharp#5500]
I have tried doing in every way....i mentioned "omnisharp.path": "latest" in Omnisharp path and restarted by VS Code ,it didn't work,i also changed my C# Version one step older and tried to restart it didn't work.

kindly help me in figuring out this error
![OmniSharp Error](https://user-images.githubusercontent.com/116510902/208878077-87f36c58-4eed-4382-83d2-8ebffdf181a7.png)

**Comment by Belaid8** [comment]
same

**Comment by JoeRobich** [comment]
When editing VS Code settings using the GUI you only need to enter `latest` as the path. When editing your settings.json in the text editor you would enter `"omnisharp.path": "latest"`.
