### ISSUE TITLE
A bug of displaying the errors 

### ISSUE THREAD

**Issue by Dangerise** [dotnet/vscode-csharp#5508]
If I use some extensions like error lens or error gutter to display the errors of my code ,although i fixed the bugs ,and the code could be compiled correctly,the errors still showed.

I believe the problem was not from the extensions above ,because both of them show the error.

![image](https://user-images.githubusercontent.com/88434542/209831386-471a2742-62e0-45a2-a58e-19244e298c4e.png)

**Comment by JoeRobich** [comment]
A lot has changed with O# since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
