### ISSUE TITLE
Each build reruns analyzers

### ISSUE THREAD

**Issue by Tantol** [dotnet/vscode-csharp#5511]
Seems like omnisharp (roslyn) runs analyze on newly created files (bin/ obj/) after build.

Is this normal or I'm missing something?

Each build reruns analyze for ~1k files (for my project) and I can imagine it can be worse for bigger ones.

**Comment by JoeRobich** [comment]
A lot has changed with O# code analysis since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
