### ISSUE TITLE
My vs code cant find the .NET Core SDK but I can run the dotnet command in the vscode terminal

### ISSUE THREAD

**Issue by 09FALLDAMAGE** [dotnet/vscode-csharp#5512]
does anyone know how to fix this, its taken the better part of a day. I have tried uninstalling and reinstalling everything. I am running windows 10 and funny compatible versions with the VS code C# extension
![Screenshot 2022-12-30 212516](https://user-images.githubusercontent.com/101277689/210122454-5e7975f3-98db-49fd-8a09-97e6c4e80b59.png)

**Comment by CC-Dennis** [comment]
Same problem here on Linux

**Comment by Ghostbird** [comment]
If this is still an issue, you might want to look at the Omnisharp log and if necessary increase the logging level:

![image](https://user-images.githubusercontent.com/1202149/213109918-da795c66-5a72-4bef-a559-97f6ed115350.png)

**Comment by JoeRobich** [comment]
A lot has changed with O# sdk resolution since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
