### ISSUE TITLE
Add "declaration" semantic token modifiers

### ISSUE THREAD

**Issue by dmrowiec-pl** [dotnet/vscode-csharp#5514]
Current semantic highlighting does not distinguish between declaration and normal usage of various entities.

For example, it is not possible to assign different colors for method declaration and its usage. The same applies for class and other entities - class declaration and usage does not have any different modifiers (they do not have any modifiers at all).

When creating themes that would fit well with most programming languages and utilize semantic highlighting, I have to say that cases mentioned above are supported by almost all major programming languages.

Since it is possible to use "go to definition" feature, I assume that the language server must have knowledge where the declaration is and where it is not (simple usage of method/class/namespace etc instead). Therefore, it seems like the required improvement should not be complicated.

**Comment by JoeRobich** [comment]
This request should go to Roslyn which does the semantic tagging. If you are still running into problems, you can open an issue at https://github.com/dotnet/roslyn/issues
