### ISSUE TITLE
Formatter ignoring 'NewLinesForX' in omnisharp.json

### ISSUE THREAD

**Issue by simonsanchezart** [dotnet/vscode-csharp#5517]
## Issue Description ##
Same as this issue ([#313](https://github.com/OmniSharp/omnisharp-vscode/issues/313)), I don't want a new line for braces, if/else statements, etc...

I've set up the omnisharp.json formatting configuration in .omnisharp on my User folder, it is being recognized, however it's still adding a new line.

(IndentationSize set to 10 to check it's properly reading the config)
https://user-images.githubusercontent.com/63672631/210675376-100047f4-5d78-4a3c-bd3d-3897f5f91cba.mp4

I've restarted Omnisharp.

## Environment information ##

**VSCode version**: 1.74.2
**C# Extension**: 1.25.2

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.201\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  3.1.424 [C:\Program Files\dotnet\sdk]
  5.0.415 [C:\Program Files\dotnet\sdk]
  6.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|auto-rename-tag|formulahendry|0.1.10|
|autodocstring|njpwerner|0.6.1|
|better-cpp-syntax|jeff-hykin|1.17.2|
|blender-development|JacquesLucke|0.0.17|
|cmake|twxs|0.0.17|
|cmake-tools|ms-vscode|1.12.27|
|code-runner|formulahendry|0.11.8|
|code-spell-checker|streetsidesoftware|2.12.0|
|color-highlight|naumovs|2.5.0|
|cpptools|ms-vscode|1.13.9|
|cpptools-extension-pack|ms-vscode|1.3.0|
|cpptools-themes|ms-vscode|2.0.0|
|csharp|ms-dotnettools|1.25.2|
|doxdocgen|cschlosser|1.4.0|
|es7-react-js-snippets|dsznajder|4.4.3|
|genesis-code|Zerasul|1.4.1|
|google-search|kameshkotwani|0.0.1|
|gruvbox|jdinhlife|1.8.0|
|gruvbox-material|sainnhe|6.5.2|
|hexeditor|ms-vscode|1.9.9|
|intellicode-api-usage-examples|VisualStudioExptTeam|0.2.6|
|isort|ms-python|2022.8.0|
|jupyter|ms-toolsai|2022.11.1003412109|
|jupyter-keymap|ms-toolsai|1.0.0|
|jupyter-renderers|ms-toolsai|1.0.12|
|live-sass|glenn2223|5.5.1|
|LiveServer|ritwickdey|5.7.9|
|material-palenight-theme|whizkydee|2.0.2|
|mdx|silvenon|0.1.1|
|path-intellisense|christian-kohler|2.8.4|
|pico8-ls|PollywogGames|0.4.10|
|pico8-vscode|johob|0.0.1|
|prettier-vscode|esbenp|9.10.3|
|python|ms-python|2022.20.1|
|python-environment-manager|donjayamanne|1.0.4|
|python-extension-pack|donjayamanne|1.7.0|
|restructuredtext|lextudio|189.3.0|
|simple-rst|trond-snekvik|1.5.2|
|theme-material-theme|jprestidge|1.0.1|
|todo-tree|Gruntfuggly|0.0.220|
|trailing-spaces|shardulm94|0.4.1|
|vim|vscodevim|1.24.3|
|vsc-python-indent|KevinRose|1.18.0|
|vscode-auto-scroll|pejmannikram|1.1.0|
|vscode-css-peek|pranaygp|4.2.0|
|vscode-django|batisteo|1.10.0|
|vscode-drawio|hediet|1.6.4|
|vscode-jupyter-cell-tags|ms-toolsai|0.1.6|
|vscode-jupyter-slideshow|ms-toolsai|0.1.5|
|vscode-mdx-preview|xyc|0.3.3|
|vscode-pull-request-github|GitHub|0.56.0|
|vscode-pylance|ms-python|2023.1.10|
|vscodeintellicode|VisualStudioExptTeam|1.2.29|
|wrapSelection|konstantin|0.10.0|;

</details>

**Comment by JoeRobich** [comment]
It is recommended to use .editorconfig for setting your formatting options. It is understood by the Roslyn compiler and many text editors.
