### ISSUE TITLE
omnisharp does not format unsaved buffer

### ISSUE THREAD

**Issue by githubuser6000** [dotnet/vscode-csharp#5527]
Omnisharp is not able to format unsaved documents

**Comment by JoeRobich** [comment]
This is by design. The C# extension does not provide language services for C# files outside the scope of a project file.

**Comment by githubuser6000** [comment]
So I cannot format a file without creating a whole new project? How disappointing. 

Oh well, not like I can use this extension outside vscode anyway. It was a good decision on my part to move away from microsoft ecosystem completely.
