### ISSUE TITLE
Debug test from VS code does not work

### ISSUE THREAD

**Issue by sirdawidd** [dotnet/vscode-csharp#5533]
## Environment data

.NET SDK (reflecting any global.json):
 Version:   6.0.403     
 Commit:    2bc18bf292  

Runtime Environment:    
 OS Name:     Windows   
 OS Version:  10.0.19042
 OS Platform: Windows   
 RID:         win10-x64
 Base Path:   C:\Programs\dotnet-sdk-6.0.403-win-x64\sdk\6.0.403\

global.json file:
  Not found

Host:
  Version:      6.0.11
  Architecture: x64
  Commit:       943474ca16

.NET SDKs installed:
  6.0.403 [C:\Programs\dotnet-sdk-6.0.403-win-x64\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.11 [C:\Programs\dotnet-sdk-6.0.403-win-x64\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Programs\dotnet-sdk-6.0.403-win-x64\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Programs\dotnet-sdk-6.0.403-win-x64\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
VS Code version:
C# Extension version:

## OmniSharp log

OmniSharp server started with .NET 6.0.403
.
    Path: c:\Users\xxx\.vscode\extensions\ms-dotnettools.csharp-1.25.2-win32-x64\.omnisharp\1.39.2-net6.0\OmniSharp.dll
    PID: 24196

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 10.0.19042.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to C:\Programs\dotnet-sdk-6.0.403-win-x64\dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: .NET Core SDK 6.0.403 17.3.2 - "C:\Programs\dotnet-sdk-6.0.403-win-x64\sdk\6.0.403\"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: .NET Core SDK 6.0.403 17.3.2 - "C:\Programs\dotnet-sdk-6.0.403-win-x64\sdk\6.0.403\"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\api'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Did not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Skip loading projects listed in solution file or under target directory because MsBuild:LoadProjectsOnDemand is true.
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\api'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Did not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\api' on host 32912.

When I try to debug test I see

        Update project: DistributionApi.Tests
[info]: OmniSharp.DotNetTest.VSTestManager
        read: {"MessageType":"TestSession.Connected","Payload":null}
[info]: OmniSharp.DotNetTest.VSTestManager
        read: {"MessageType":"ProtocolVersion","Payload":1}
[info]: OmniSharp.DotNetTest.DebugSessionManager
        Debug session started.
[info]: OmniSharp.DotNetTest.DebugSessionManager
        Debug session ended.

## Steps to reproduce

1. Try to click on popup of selected test option: Debug Test
2. You will see

Failed to read environment variable [DOTNET_ROOT], HRESULT: 0x80070002
A fatal error occurred. The required library hostfxr.dll could not be found.
If this is a self-contained application, that library should exist in [c:\Users\Api.Tests\bin\Debug\net6.0\].
If this is a framework-dependent application, install the runtime in the global location [C:\Program Files\dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation].

The .NET Core runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win10-x64
The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
The program '[34396] testhost.exe' has exited with code -2147450749 (0x80008083).

Option Run Test, works fine , I get test results, also debugging is working, if I run it manually:
Create test process and attach debugger.
Also o .net 5 I didn't faced similar issue.

## Expected  behavior
Click Debug Test option in Vs Code should run debugger without error.

## Actual behavior
Failed to read environment variable [DOTNET_ROOT], HRESULT: 0x80070002
A fatal error occurred. The required library hostfxr.dll could not be found.
If this is a self-contained application, that library should exist in [c:\Users\Tests\bin\Debug\net6.0\].
If this is a framework-dependent application, install the runtime in the global location [C:\Program Files\dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation].

The .NET Core runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win10-x64
The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
The program '[34396] testhost.exe' has exited with code -2147450749 (0x80008083).

**Comment by sirdawidd** [comment]
After some investigation, it work when I removed from user variables DOTNET_ROOT.
However the path was correctly setup, and even error mentioned that I need to define base directory....
Now I only have issues that some plugins in VS code does not work, as they cant find installation of .net  ....

**Comment by moly** [comment]
I'm seeing the same problem for both "Run Test" and "Debug Test". I have dotnet 7.0.400 extracted to c:\users\x\AppData\Local\dotnet. DOTNET_ROOT is set and added to PATH. Running `dotnet test` in the vscode terminal works fine.

**Comment by moly** [comment]
After playing with this a bit I think I've found a workaround. Setting the environment variable `VSTEST_WINAPPHOST_DOTNET_ROOT` to my dotnet location fixes it for me.

**Comment by JoeRobich** [comment]
A lot has changed with O#  since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
