### ISSUE TITLE
VS Code: Using quick actions on 8.0 projects does not show usage directionality.

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/vscode-csharp#5545]
**Describe the bug:**
Using quick actions on 8.0 projects does not show usage directionality.

**Version used:**
VS2022 17.5 Preview 3
VS Code: 1.74.2
C# Extension version:1.25.2
SDK: 8.0.100-alpha.1.23056.11

 **Platform**

- [x] Windows
- [x] Linux
- [x] Mac

**To reproduce:**

1.Open a normal Terminal Emulator, create MVC project and open it using VS code
```
mkdir MVC3x
cd MVC3x
dotnet new mvc -f net8.0
code .
```
2.Go to [https://github.com/OmniSharp/omnisharp-vscode/releases](https://github.com/OmniSharp/omnisharp-vscode/releases) > Download the csharp-1.25.2-win32-x64.vsix.
3.In VS Code and go to the Extensions Tab, select "Install from VSIX" > install the file you downloaded.
4.In VS Code, using CTRL + ~ to open up TERMINAL window, type the following code.
```
'namespace MVC3x // Or Razor3x
{
    public class CustomTagHelper
    {
    }
}' | Out-File CustomTagHelper.cs
```
5.In CustomTagHelper.cs, type ": TagHelper" following the class. And then use Quick Actions (ctrl +.) "No code actions available" is displayed after that.

**Actual behavior:**
![image](https://user-images.githubusercontent.com/71361488/211261406-cdddec80-160a-4a41-9dbb-b05ba5598efd.png)
**Expected behavior:**
![image](https://user-images.githubusercontent.com/71361488/211261492-884bd20d-66e1-4474-94c5-842cc3040a83.png)
**Additional context:**
Note: 
1. This issue also repro on C# extension 1.25.1.
2. This issue only repro on 8.0 project, the 6.0 project works fine.

**Comment by JoeRobich** [comment]
A lot has changed with O# code analysis since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
