### ISSUE TITLE
OmniSharp can't access CMD on Windows

### ISSUE THREAD

**Issue by StevePlaysMinecraft** [dotnet/vscode-csharp#5549]
I'm opening a unity cs script and IntelliSense doesn't work. This is the OmniSharp log

```
Starting OmniSharp server at 1/22/2023, 12:22:51 PM
    Target: c:\Users\user\Unity Projects\Kinda Better Minecraft\Kinda Better Minecraft.sln

OmniSharp server started.
    Path: c:\Users\user\.vscode\extensions\ms-dotnettools.csharp-1.25.2-win32-x64\.omnisharp\1.39.2\OmniSharp.exe
    PID: 13552

[STDERR] 'cmd' is not recognized as an internal or external command,
operable program or batch file.

[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
```
how can I fix this?

**Comment by JoshMatthew** [comment]
Anything yet?

**Comment by JoshMatthew** [comment]
> I'm opening a unity cs script and IntelliSense doesn't work. This is the OmniSharp log
> 
> ```
> Starting OmniSharp server at 1/22/2023, 12:22:51 PM
>     Target: c:\Users\user\Unity Projects\Kinda Better Minecraft\Kinda Better Minecraft.sln
> 
> OmniSharp server started.
>     Path: c:\Users\user\.vscode\extensions\ms-dotnettools.csharp-1.25.2-win32-x64\.omnisharp\1.39.2\OmniSharp.exe
>     PID: 13552
> 
> [STDERR] 'cmd' is not recognized as an internal or external command,
> operable program or batch file.
> 
> [ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
> ```
> 
> how can I fix this?

Hello, I found a quick solution for this. I just have to enable Omnisharp: Use Modern Net option from vscode settings and restart the editor. Atleast this works for me.

**Comment by JoeRobich** [comment]
A lot has changed with O# since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
