### ISSUE TITLE
OmniSharp server load timed out

### ISSUE THREAD

**Issue by johnib** [dotnet/vscode-csharp#5551]
## Issue Description ##
OmniSharp vscode extension is failing to start (due to timeouts).
It doesn't matter how high I configure the timeout, as suggested by the below logs, it still won't start.
Even on the simple `webapp` template, it timeouts starting -- so it's not related to my project's size.

## Steps to Reproduce ##

```
brew install dotnet
```

## Expected Behavior ##
OmniSharp to start

## Actual Behavior ##
OmniSharp is timing out when starting (no matter what the timeout is, no matter what project size, even the default `webapp` template won't load)

### OmniSharp log ###
<details>

```
Starting OmniSharp server at 1/23/2023, 9:39:19 PM
    Target: /Users/user/repos/Playground/Playground.sln

OmniSharp server started.
    Path: /Users/user/.vscode/extensions/ms-dotnettools.csharp-1.24.1-darwin-arm64/.omnisharp/1.38.1/run
    PID: 2000

[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).

```
</details>

### C# log ###
none

## Environment information ##

**VSCode version**: 1.74.3
**C# Extension**: 1.24.1 (**I happens on the latest version as well 1.25.x**)

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.1
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /opt/homebrew/Cellar/dotnet/7.0.100/libexec/sdk/7.0.100/

Host:
  Version:      7.0.0
  Architecture: arm64
  Commit:       d099f075e4

.NET SDKs installed:
  7.0.100 [/opt/homebrew/Cellar/dotnet/7.0.100/libexec/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0 [/opt/homebrew/Cellar/dotnet/7.0.100/libexec/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0 [/opt/homebrew/Cellar/dotnet/7.0.100/libexec/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/opt/homebrew/Cellar/dotnet/7.0.100/libexec]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.11.3|
|azure-event-hub-explorer|Summer|0.1.1|
|azurerm-vscode-tools|msazurermtools|0.15.8|
|color-highlight|naumovs|2.5.0|
|csharp|ms-dotnettools|1.24.1|
|githistory|donjayamanne|0.6.19|
|gitignore|codezombiech|0.9.0|
|guid|kosunix|0.0.1|
|json-escaper|joshuapoehls|1.1.2|
|json-scape-unscape|yuvraj|1.3.0|
|json-tools|eriklynd|1.0.2|
|powershell|ms-vscode|2023.1.0|
|remote-containers|ms-vscode-remote|0.266.1|
|svg-preview|SimonSiefke|2.8.3|
|timestamp-converter|Stalinbalraj|0.0.1|
|unixtime-converter|espresso3389|0.0.2|
|vscode-base64|adamhartford|0.1.0|
|vscode-docker|ms-azuretools|1.23.3|
|vscode-dotnet-runtime|ms-dotnettools|1.6.0|
|vscode-icons|vscode-icons-team|12.2.0|
|vscode-kubernetes-tools|ms-kubernetes-tools|1.3.11|
|vscode-markdownlint|DavidAnson|0.49.0|
|vscode-solution-explorer|fernandoescolar|0.7.5|
|vscode-sort-json|richie5um2|1.20.0|
|vscode-styled-components|styled-components|1.7.5|
|vscode-yaml|redhat|1.11.0|
|xml|DotJoshJohnson|2.5.1|;

</details>

**Comment by barruka** [comment]
After opening vscode, updated c# extension to v1.25.4

OmniSharp Log:
```
Error occurred in loading omnisharp from omnisharp.path
Could not start the server due to Error: Request error: connect ETIMEDOUT 52.239.160.170:443
```

`omnisharp.path = latest`

**Comment by JoeRobich** [comment]
A lot has changed with O# project loading since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
