### ISSUE TITLE
Performance Issues Blocking File Saves

### ISSUE THREAD

**Issue by boydbuchanan** [dotnet/vscode-csharp#5556]
Type: <b>Bug</b>

In a unity project with a decent sized framework. Nothing specific to cause issue. Running Unity and VSCode together and switching. VSCode has issueing saving files as they are busy or locked. Unknown (FileSystemError): Error: EBUSY: resource busy or locked

Extension version: 1.25.4
VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600X Six-Core Processor            (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.93GB (19.28GB free)|
|Process Argv|--folder-uri file:///c%3A/Projects/Spright --crash-reporter-id f99a4a0c-aca4-4669-875f-9e6e1c3e8983|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
282f8724:30602487
89544117:30613380
2i9eh265:30646982
vscsb:30628654

```

</details>

**Comment by boydbuchanan** [comment]
Downgraded to 1.25.2 and the issue resolved. CPU usage normalized, Intellisense is responsive and no issues saving files.

**Comment by JoeRobich** [comment]
A lot has changed with O# since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues. It is recommended to use the Unity extension for VS Code
