### ISSUE TITLE
If Roslyn analyzer is enabled, analyzer appears to lag behind and freeze during typing

### ISSUE THREAD

**Issue by myocytebd** [dotnet/vscode-csharp#5557]
## Issue Description ##
During typing, transient Problems appears due to incomplete input. e.g. "missing ;" may appear because semicolon is not yet typed.  
With Roslyn analyzer disabled, these transient Problems quickly disappears.  
However when Roslyn analyzer enabled, these should-be transient Problems may persist. e.g. "missing ;" keeps showing despite the line of code is completed.  

By "lag behind", I meant that the should-be transient Problems keep showing, but Problems can update on further typing or cut/paste.  
By "freeze", I meant that the should-be transient Problems keep showing, and Problems no longer updates on further typing or cut/paste.  

There is no Output message appears during typing.

## Steps to Reproduce ##
0. Enable Roslyn analyzer.  
1. Open any project, and analyzer works as expected.  
2. Start to type code.  
* Problems refreshes in much high latency compared to Roslyn analyzer disabled.  
* There is chance for analyzer to "lag behind" during typing or paste. It quickly lags behind in a few lines in my usage.  
* When analyzer "lags behind", it will not catch up on its own. If I type again or cut & paste, it might update, but unlikely to fully catch up.  
* Sometimes (or eventually), it looks like the analyzer is fully stuck and no longer update on change.  
4. Reopen vscode, and analyzer is back to normal.  

## Expected Behavior ##
* Analyzer always catch up if code is not being updated.  
* During typing, basic Problems updates as fast as Roslyn analyzer disabled.  

## Actual Behavior ##
Analyzer appears to "lag behind" or freeze.  

### OmniSharp log ###
(No Output message appears during typing)

### C# log ###
(All kinds of transient Problems as if the code line is not yet completed)

## Environment information ##

**VSCode version**: 1.74.1
**C# Extension**: 1.25.4

<details><summary>Mono Information</summary>
        OmniSharp using mono: 6.12.0</details>
<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.100-rc.2.22477.23
 Commit:    0a5360315a

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /home/xxx/.dotnet/sdk/7.0.100-rc.2.22477.23/

Host:
  Version:      7.0.0-rc.2.22472.3
  Architecture: x64
  Commit:       550605cc93

.NET SDKs installed:
  6.0.402 [/home/xxx/.dotnet/sdk]
  7.0.100-rc.2.22477.23 [/home/xxx/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.10 [/home/xxx/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-rc.2.22476.2 [/home/xxx/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [/home/xxx/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.30 [/home/xxx/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [/home/xxx/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-rc.2.22472.3 [/home/xxx/.dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/home/xxx/.dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|cmake|twxs|0.0.17|
|cmake-tools|ms-vscode|1.13.41|
|cpptools|ms-vscode|1.13.9|
|cpptools-extension-pack|ms-vscode|1.3.0|
|cpptools-themes|ms-vscode|2.0.0|
|csharp|ms-dotnettools|1.25.4|
|intellicode-api-usage-examples|VisualStudioExptTeam|0.2.6|
|isort|ms-python|2022.8.0|
|java|redhat|1.14.0|
|jupyter|ms-toolsai|2022.11.1003412109|
|jupyter-keymap|ms-toolsai|1.0.0|
|jupyter-renderers|ms-toolsai|1.0.14|
|nugetpackagemanagergui|aliasadidev|2.0.6|
|powershell|ms-vscode|2023.1.0|
|python|ms-python|2022.20.2|
|ruby|rebornix|0.28.1|
|vscode-back-forward-button|grimmer|0.1.6|
|vscode-fileutils|sleistner|3.8.0|
|vscode-java-debug|vscjava|0.47.0|
|vscode-java-dependency|vscjava|0.21.1|
|vscode-java-pack|vscjava|0.25.7|
|vscode-java-test|vscjava|0.37.1|
|vscode-jupyter-cell-tags|ms-toolsai|0.1.6|
|vscode-jupyter-slideshow|ms-toolsai|0.1.5|
|vscode-maven|vscjava|0.40.4|
|vscode-pylance|ms-python|2023.1.30|
|vscode-ruby|wingrunr21|0.28.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.30|;

</details>

**Comment by JoeRobich** [comment]
A lot has changed with O# code analysis since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
