### ISSUE TITLE
Intellisense with Unity 2021.3.5f1 not working :(

### ISSUE THREAD

**Issue by xFirefalconx** [dotnet/vscode-csharp#5558]
*Copied from my other VSC bug report you can find here: https://github.com/microsoft/vscode/issues/172368#issue-1556357856

For more specific information scroll further, I filled in both.

Type: <b>Bug</b>

I don't know, why. Theoretically it should be working. 

1. I create a new C# file in Unity and type "ejkhifkjefhgjksehfksjegfsjkefhsjkefse ejkfhkjefhsekjfgjik ekfhjgeshkjfghsehk" (without the "s) in the Update function.
2. It doesn't underline it and goes like "This is totally fine". No errors found, does my terminal/problems thing say. When I have C# selected. I have the extensions I would need, I even added NuGetAnalyzers but even they didn't change a thing. 

Potential clue: I observed this happening when I first opened a .TOML file from Minecraft configs, but I don't know if this is the cause or just something that I noticed. Also, these colors are not the usual C# Unity Intellisense? The recommendation for words is working, but no error detection??? (See screenshots at the bottom)

I tried everything I could find to fix it, but it didn't do anything (including restarting it about 20 times, not exaggerated). I am desperate for help at this point. Please help me.

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|23.95GB (5.98GB free)|
|Process Argv|--crash-reporter-id 899bea0c-1702-4991-8a83-01ce0249fe7c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
unity-debug|dei|3.0.11
unity-code-snippets|kle|1.3.0
git-graph|mhu|1.30.0
csharp|ms-|1.25.4
hlsltools|Tim|1.1.303
unity-tools|Tob|1.2.12

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
3biah626:30602489
89544117:30613380

```

</details>

Images: 
![grafik](https://user-images.githubusercontent.com/106652912/214531866-9a4a17d1-9117-44f7-b1e0-4a9cdfcf22c8.png)
![grafik](https://user-images.githubusercontent.com/106652912/214532159-85a812d0-c7c3-4165-9f72-ae5806867b5e.png)
![grafik](https://user-images.githubusercontent.com/106652912/214532249-6971a2ef-5e85-4ce6-b140-78aaf246fab9.png)
![grafik](https://user-images.githubusercontent.com/106652912/214532683-0a6be02c-103a-42e2-8f57-b25fc1c1a5c6.png)

**Prefilled from the specific Csharp bug report function I found by pressing F1**

## Issue Description ##
OmniSharp is not working properly, Intellisense broken, syntax highlighting not fit for C# Unity environment

## Steps to Reproduce ##
Create a new C# file within Unity, open it up and type... just anything in the Update function. 
For example: "wekufghhkegfhekjf ekjfhef"
If it doesn't underline anything and the colors of the highlighting are not as expected (see screenshots above), you have my issue.

## Expected Behavior ##
Intellisense working with Unity integration

## Actual Behavior ##
It tells me there are no issues at all. 

### OmniSharp log ###
<details>Starting OmniSharp server at 25.1.2023, 09:35:02
    Target: f:\3D_Projekte\Repo\Burning Tears\Burning Tears Online\Burning Tears Online.sln

OmniSharp server started.
    Path: c:\Users\Joana\.vscode\extensions\ms-dotnettools.csharp-1.25.4-win32-x64\.omnisharp\1.39.4\OmniSharp.exe
    PID: 40996

[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
</details>

### C# log ###
<details>Installing C# dependencies...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 4.7.2 / x64)' (29097 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package 'OmniSharp for Windows (.NET 4.7.2 / x64)'

Finished

</details>

## Environment information ##

**VSCode version**: 1.74.3
**C# Extension**: 1.25.4

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.101
 Commit:    bb24aafa11

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.101\

Host:
  Version:      7.0.1
  Architecture: x64
  Commit:       97203d38ba

.NET SDKs installed:
  7.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.25.4|
|git-graph|mhutchie|1.30.0|
|hlsltools|TimGJones|1.1.303|
|unity-code-snippets|kleber-swf|1.3.0|
|unity-debug|deitry|3.0.11|
|unity-tools|Tobiah|1.2.12|;

</details>

**Comment by dibarbet** [comment]
It looks like it timed out loading the project.  Could be for many reasons, but could you try increasing the default timeout of 60 seconds?  The setting is `omnisharp.projectLoadTimeout` with values specified in seconds

**Comment by xFirefalconx** [comment]
Thank you, I tried this now but after 360s it still gets timeout. Should I set it for an hour and see if it still does? 🙈 

![grafik](https://user-images.githubusercontent.com/106652912/217175776-8fc0d997-d0dc-442d-ad1a-fad1d2f019aa.png)

**Comment by xFirefalconx** [comment]
![grafik](https://user-images.githubusercontent.com/106652912/217200200-5411c640-1918-4b3f-a427-e0f2530568ec.png)
I don't think it will... ever connect? 

Additional info: HLSL error detection is working now, but C# is stubborn.

**Comment by abedaster** [comment]
This is also happening in my environment.
It appears that the hinting information set by the project (.sln) file created in Unity is being overwritten from the C# extension.

**Comment by xFirefalconx** [comment]
> This is also happening in my environment. It appears that the hinting information set by the project (.sln) file created in Unity is being overwritten from the C# extension.


Additional info: Please check if you have debug mode enabled within the settings in VSCode for OmniSharp. 
DISABLE them. 
I forgot to add this, but a few months after I posted my logs, I realized I had a local debug mode on that would block the omnisharp server to connect because it would wait for input to debug the omnisharp plugin itself. I didn't know back then but I hope to save you from a headache in case you did the same. 
If that isn't the case, do as I did, post logs and check every other possible step that could have made it go wrong. Uninstalling the editor for some reason does NOT reset/disable the debug mode (which is a bit... not straightforward?), so be careful, it might be true for other settings, too. I don't know how it's called like right now, but I posted something regarding this, feel free to take a look in case it leads to the solution. https://github.com/dotnet/vscode-csharp/issues/5631 
I wish you all the best in your pursuit to fix the problem.

**Comment by abedaster** [comment]
Thank you for your response.
In my case, it was happening because I did not have the .NET SDK installed.
I am embarrassed to say that I was able to repair the problem by installing it.
Your suggestion to look at the logs helped. Thanks!

I have not made any changes to the item in the OmniSharp settings to debug mode, so if I see it in the future I will treat it with caution.
