### ISSUE TITLE
Unwanted automatic code formatting in 1.25.4

### ISSUE THREAD

**Issue by lonix1** [dotnet/vscode-csharp#5560]
## Environment data
Latest of everything
`dotnet --info` output: 1.25.4
VS Code version: 1.74.3
C# Extension version: 6.0.405

## Steps to reproduce
- Open vscode
- Open cs or razor file
- Press `;` or `)` or `,` or any of the formatting keys
- The document is automatically formatted

## Expected  behavior
Before upgrading to 1.25.4 it did not automatically format. I don't want that behaviour as it never formats the way I want, and ruins my git diffs.

## Actual behavior
Automatically formats. No idea how to revert to previous behaviour.

**Comment by Ertan222** [comment]
I don't want another space too, there is no setting to prevent formatting.

**Comment by JoeRobich** [comment]
Is it possible that `editor.formatOnType` got enabled locally? If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
