### ISSUE TITLE
[BUG] Can't install or update C# extension

### ISSUE THREAD

**Issue by ErtanTaner** [dotnet/vscode-csharp#5562]
## Issue Description ##
When ı try to install or update C# from vscode extension tab or cli, installation progress is freezeing ang nothing happens after that. Idk is about vscode or extension but report an issue lead me here. If ı need to open issue in a different repository, please give me the correct information.

## Steps to Reproduce ##
I tried to update my C# extension to 1.25.4, new version but couldn't. I removed and tried to install again but same, couldn't. I tried to install previous version but same, nothing happened. 
Only VSIX version installation worked for me and can use C# with that.

### Vscode Extensions Step
Vscode => Extensions => Search for 'C#' => Press install / Press Update button.

### CLI Step
Terminal => type "code --install-extension ms-dotnettools.csharp"

## Expected Behavior ##
Should install or update C# extension.
## Actual Behavior ##
It's not update or install C#. Only VSIX worked.
## Logs ##
TRACE [File Watcher (node.js)] Request to start watching: /home/ertan/.config/Code/User (excludes: <none>, includes: <all>),/home/ertan/.config/Code/User/settings.json (excludes: <none>, includes: <all>)
 INFO CLI main {
  _: [],
  diff: false,
  merge: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  'install-extension': [ 'ms-dotnettools.csharp' ],
  'pre-release': false,
  version: false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'no-cached-data': false,
  'prof-v8-extensions': false,
  'disable-extensions': false,
  'disable-gpu': false,
  'ms-enable-electron-run-as-node': false,
  telemetry: false,
  debugRenderer: false,
  'enable-smoke-test-driver': false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'skip-welcome': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-keytar': false,
  'disable-workspace-trust': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'force-user-env': false,
  'force-disable-user-env': false,
  'open-devtools': false,
  '__enable-file-policy': false,
  'enable-coi': false,
  'no-proxy-server': false,
  'no-sandbox': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false,
  'disable-dev-shm-usage': false,
  'profile-temp': false,
  logsPath: '/home/ertan/.config/Code/logs/20230128T063115'
}
Installing extensions...
TRACE Started scanning user extensions r {
  scheme: 'file',
  authority: '',
  path: '/home/ertan/.vscode/extensions/extensions.json',
  query: '',
  fragment: '',
  _formatted: null,
  _fsPath: null
}
TRACE [File Watcher (node.js)] Request to start watching: /home/ertan/.vscode/extensions (excludes: <none>, includes: <all>),/home/ertan/.vscode/extensions/extensions.json (excludes: <none>, includes: <all>)
TRACE [File Watcher (node.js)] Started watching: '/home/ertan/.config/Code/User'
TRACE [File Watcher (node.js)] Started watching: '/home/ertan/.config/Code/User/settings.json'
DEBUG ComputeTargetPlatform: linux-x64
TRACE Started scanning user extensions r {
  scheme: 'file',
  authority: '',
  path: '/home/ertan/.vscode/extensions',
  query: '',
  fragment: '',
  _formatted: 'file:///home/ertan/.vscode/extensions',
  _fsPath: '/home/ertan/.vscode/extensions'
}
TRACE [File Watcher (node.js)] Started watching: '/home/ertan/.vscode/extensions'
TRACE [File Watcher (node.js)] Started watching: '/home/ertan/.vscode/extensions/extensions.json'
TRACE Scanned user extensions: 39
DEBUG ComputeTargetPlatform: linux-x64
TRACE Scanned user extensions: 39
TRACE RequestService#request (node) - begin https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery
TRACE resolveShellEnv(): skipped (VSCODE_CLI is set)
TRACE RequestService#request (node) - success https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery
TRACE RequestService#request (node) - begin https://ms-dotnettools.gallerycdn.vsassets.io/extensions/ms-dotnettools/csharp/1.25.4/1674587554430/Microsoft.VisualStudio.Code.Manifest?targetPlatform=linux-x64
TRACE resolveShellEnv(): skipped (VSCODE_CLI is set)
TRACE RequestService#request (node) - success https://ms-dotnettools.gallerycdn.vsassets.io/extensions/ms-dotnettools/csharp/1.25.4/1674587554430/Microsoft.VisualStudio.Code.Manifest?targetPlatform=linux-x64
Installing extension 'ms-dotnettools.csharp'...
TRACE ExtensionManagementService.refreshReportedCache
TRACE RequestService#request (node) - begin https://az764295.vo.msecnd.net/extensions/marketplace.json
TRACE resolveShellEnv(): skipped (VSCODE_CLI is set)
TRACE RequestService#request (node) - success https://az764295.vo.msecnd.net/extensions/marketplace.json
TRACE ExtensionManagementService.refreshControlCache {
  malicious: [
    { id: 'visualstuiocode.emmet' },
    { id: 'joaomoreno.banana' },
    { id: 'JacobeanResearchandDevelopmentLLC.vscode-scxml-preview' },
    { id: 'joaquin6.package-watch' },
    { id: 'KazuoCode.gthubsum' },
    { id: 'MaxGotovkin.tslens' },
    { id: 'stephen-riley.regexworkbench' },
    { id: 'guozebin.api-generator-plugin' },
    { id: 'code-tester.code-tester' }
  ],
  deprecated: {
    'github.vscode-pull-request-github-insiders': { disallowInstall: true, extension: [Object] },
    'julialang.language-julia-insider': { disallowInstall: true, extension: [Object] },
    'ms-vscode-remote.remote-ssh-nightly': { disallowInstall: true, extension: [Object] },
    'ms-vscode-remote.remote-ssh-edit-nightly': { disallowInstall: true, extension: [Object] },
    'msjsdiag.debugger-for-chrome': { disallowInstall: true, extension: [Object] },
    'adashen.vscode-tomcat': { disallowInstall: true, extension: [Object] },
    'summersun.vscode-jetty': { disallowInstall: true, extension: [Object] },
    'abusaidm.html-snippets': {},
    'ms-vscode.vscode-typescript-tslint-plugin': {},
    'eg2.tslint': {},
    'zenclabs.reactpreview': { disallowInstall: true, extension: [Object] },
    'auchenberg.vscode-browser-preview': { disallowInstall: false, extension: [Object] },
    'donjayamanne.jupyter': { disallowInstall: true, extension: [Object] },
    'awwsky.csharpfixformatfixed': { disallowInstall: true, extension: [Object] },
    'cadenas.vscode-glsllint': { disallowInstall: true, extension: [Object] },
    'tiibun.vscode-docker-ws': { disallowInstall: true, extension: [Object] },
    'ballerina.ballerina': { disallowInstall: true, extension: [Object] },
    'correctnesslab.dafny-vscode': { disallowInstall: true, extension: [Object] },
    'elixir-lsp.elixir-ls': { disallowInstall: true, extension: [Object] },
    'smeagolem.ayu-one-dark-pro': { disallowInstall: true, extension: [Object] },
    'jpogran.puppet-vscode': { disallowInstall: true, extension: [Object] },
    'ibm.xmllanguagesupport': { disallowInstall: true, extension: [Object] },
    'ms-vscode.latex': { disallowInstall: true, extension: [Object] },
    'axetroy.vscode-deno': { disallowInstall: true, extension: [Object] },
    'justjavac.vscode-deno': { disallowInstall: true, extension: [Object] },
    'doublefint.vscode-cos': { disallowInstall: true, extension: [Object] },
    'rust-lang.rust': { disallowInstall: true, extension: [Object] },
    'freebroccolo.reasonml': { disallowInstall: true, extension: [Object] },
    'knisterpeter.vscode-github': { disallowInstall: true, extension: [Object] },
    'antfu.vue-i18n-ally': { disallowInstall: true, extension: [Object] },
    'antfu.i18n-ally': { disallowInstall: true, extension: [Object] },
    'haaleo.vscode-stylint': { disallowInstall: true, extension: [Object] },
    'snooz82.rf-intellisense': { disallowInstall: true },
    'keith.robotframework': { disallowInstall: true },
    'slevesque.vscode-hexdump': { disallowInstall: true, extension: [Object] },
    'togusa09.tmlanguage': { disallowInstall: true, extension: [Object] },
    'slevesque.perforce': { disallowInstall: true, extension: [Object] },
    'raagh.angular-karma-test-explorer': { disallowInstall: true, extension: [Object] },
    'ritwickdey.live-sass': { disallowInstall: true, extension: [Object] },
    'redhat.vscode-didact': { disallowInstall: false, extension: [Object] },
    'camel-tooling.atlasmap-viewer': { disallowInstall: false, extension: [Object] },
    'imperez.smarty': { disallowInstall: true, extension: [Object] },
    'badochov.ocaml-formatter': { disallowInstall: true, extension: [Object] },
    'damirka.move-ide': { disallowInstall: true, extension: [Object] },
    'sanderledegen.angular-follow-selector': { disallowInstall: true, extension: [Object] },
    'yorkxin.coffeescript-support': { disallowInstall: true, extension: [Object] },
    'shopify.rubocop-lsp': { disallowInstall: true, extension: [Object] },
    'tomiturtiainen.rf-intellisense': { disallowInstall: false },
    'chenxsan.vscode-standardjs': { disallowInstall: true, extension: [Object] },
    'idleberg.innosetup': { disallowInstall: true, extension: [Object] },
    'pluyckx.iar-vsc': { disallowInstall: true, extension: [Object] },
    'stateful.edge': { disallowInstall: true, extension: [Object] },
    'slevesque.vscode-autohotkey': { disallowInstall: true, extension: [Object] },
    'embertooling.vscode-ember': { disallowInstall: true, extension: [Object] },
    'embertooling.prettier-for-handlebars-vscode': { disallowInstall: true, extension: [Object] },
    'liuji-jim.vue': { disallowInstall: true, extension: [Object] },
    'spences10.vscode-vba-icons': { disallowInstall: false, extension: [Object] },
    'spences10.vba': { disallowInstall: true, extension: [Object] },
    'eyhn.vscode-vibrancy': { disallowInstall: true, extension: [Object] },
    'redvanworkshop.explorer-exclude-vscode-extension': { disallowInstall: true, extension: [Object] },
    'activecove.osmosis': { disallowInstall: true, extension: [Object] },
    'trass3r.cxx-compiler-explorer': { disallowInstall: true, extension: [Object] },
    'jcbuisson.vue': { disallowInstall: true, extension: [Object] },
    'silvenon.mdx': { disallowInstall: true, extension: [Object] },
    'liximomo.sftp': { disallowInstall: true, extension: [Object] },
    'coenraads.bracket-pair-colorizer-2': { settings: [Array] },
    'coenraads.bracket-pair-colorizer': { settings: [Array] },
    '2gua.rainbow-brackets': { settings: [Array] },
    'tyriar.terminal-tabs': { settings: [Array] },
    'austin.code-gnu-global': { disallowInstall: true, extension: [Object] },
    'mkaufman.htmlhint': { disallowInstall: false, extension: [Object] },
    'aleohq.aleo-instructions-syntax': { disallowInstall: true, extension: [Object] },
    'aleohq.leo-language-features-extension': { disallowInstall: true, extension: [Object] },
    'tomaciazek.ansible': { disallowInstall: true, extension: [Object] },
    'nextfaze.comment-wrap': { disallowInstall: true, extension: [Object] },
    'magneet.talkgrammar': { disallowInstall: true, extension: [Object] },
    'philhindle.errorlens': { disallowInstall: true, extension: [Object] },
    'alexeaton.openscad-format': { disallowInstall: true, extension: [Object] },
    'efbenson.scad': { disallowInstall: true, extension: [Object] },
    'meowcolm024.has-go': { disallowInstall: true, extension: [Object] },
    'haneefdm.memview': { disallowInstall: true, extension: [Object] },
    'avli.clojure': { disallowInstall: true, extension: [Object] },
    'buhlerplctools.gcpro-macro-language': { disallowInstall: true, extension: [Object] },
    'prql.prql': { disallowInstall: true, extension: [Object] },
    'jodyh.circleci-vscode': { disallowInstall: true, extension: [Object] },
    'tonsky.clojure-warrior': { disallowInstall: true, extension: [Object] },
    'tao-cumplido.hex-viewer': { disallowInstall: true, extension: [Object] },
    'modyqyw.vscode-uni-app-schemas': { disallowInstall: true, extension: [Object] },
    'modyqyw.vscode-uni-app-snippets': { disallowInstall: true, extension: [Object] },
    'modyqyw.vscode-uni-cloud-snippets': { disallowInstall: true, extension: [Object] },
    'modyqyw.vscode-uni-helper': { disallowInstall: true, extension: [Object] },
    'modyqyw.vscode-uni-ui-snippets': { disallowInstall: true, extension: [Object] },
    'kellielutze.language-epsilon': { disallowInstall: true, extension: [Object] },
    'lvjiaxuan.eslint-disable': { disallowInstall: true, extension: [Object] },
    'sa2taka.js-go-to-test': { disallowInstall: true, extension: [Object] },
    'huacnlee.auto-correct': { disallowInstall: true, extension: [Object] },
    'nobuhito.printcode': { disallowInstall: false, extension: [Object] },
    'webososesdk.webosose': { disallowInstall: true, extension: [Object] },
    'wwm.better-align': { disallowInstall: true, extension: [Object] },
    'sandipchitale.vscode-kubernetes-commander': { disallowInstall: true, extension: [Object] },
    'shan.code-settings-sync': {
      disallowInstall: true,
      additionalInfo: 'Please use the built-in [Settings Sync](https://aka.ms/vscode-settings-sync-help) functionality instead.'
    },
    'dbaeumer.jshint': { disallowInstall: true, extension: [Object] },
    'lindraupe.aw-watcher-vscode': { disallowInstall: true, extension: [Object] },
    'ms-kubernetes-tools.porter-vscode': { disallowInstall: true, extension: [Object] },
    'simonsiefke.prettier-vscode': { disallowInstall: true, extension: [Object] },
    'redwoodjs.redwood': {},
    'msoffice.microsoft-office-add-in-debugger': {},
    'microsoft.merge-conflict-detection': {},
    'formulahendry.terminal': {},
    'tyriar.shell-launcher': {},
    'logerfo.cd-repo': {},
    'bitlang.bitlangcoboldepreciated': {},
    'redhat.vscode-datavirt': {},
    'redhat.datavirt-extension-pack': {},
    'redhat.vscode-wsdl2rest': {},
    'nikitakunevich.snippet-creator': {},
    'ms-vscode.node-debug2': {},
    'ms-vscode.node-debug': {},
    'entomy.ada': {},
    'glen-84.sass-lint': {},
    'hackwaly.ocaml': {},
    'jchannon.csharpextensions': {},
    'unity.unity-debug': {},
    'hookyqr.beautify': {},
    'tht13.python': {},
    'lonefy.vscode-js-css-html-formatter': {},
    'tht13.html-preview-vscode': {},
    'ikappas.phpcs': {},
    'qinjia.view-in-browser': {},
    'hdg.live-html-previewer': {},
    'dongli.python-preview': {},
    'sophisticode.php-formatter': {},
    'peakchen90.vue-beautify': {},
    'utsavm9.c-cpp-flag-debugging': {},
    'uvbrain.angular2': {},
    'coderfee.open-html-in-browser': {},
    'remimarsal.prettier-now': {},
    'himanoa.python-autopep8': {},
    'tht13.gerrit-vscode': {},
    'felipecrs.vscode-gerrit': {},
    'heptio.jsonnet': {},
    'eg2.vscode-npm-script': {},
    'ethan-reesor.vscode-go-test-adapter': {},
    'aaronpowell.vscode-profile-switcher': {},
    'nachocab.highlight-dodgy-characters': {},
    'pthorsson.vscode-jsp': {},
    'ctf0.htmlhint': {},
    'cellery.cellery-vscode-extension': {},
    'vsciot-vscode.vscode-iot-device-cube': {},
    'ms-azuretools.vscode-azureeventgrid': {},
    'vsciot-vscode.azure-iot-tools': {},
    'ms-vsliveshare.vsliveshare-audio': {}
  }
}
 INFO Getting Manifest... ms-dotnettools.csharp
TRACE RequestService#request (node) - begin https://ms-dotnettools.gallerycdn.vsassets.io/extensions/ms-dotnettools/csharp/1.25.4/1674587554430/Microsoft.VisualStudio.Code.Manifest?targetPlatform=linux-x64
TRACE resolveShellEnv(): skipped (VSCODE_CLI is set)
TRACE RequestService#request (node) - success https://ms-dotnettools.gallerycdn.vsassets.io/extensions/ms-dotnettools/csharp/1.25.4/1674587554430/Microsoft.VisualStudio.Code.Manifest?targetPlatform=linux-x64
 INFO Installing extension: ms-dotnettools.csharp
TRACE Started scanning system extensions
TRACE Started scanning user extensions r {
  scheme: 'file',
  authority: '',
  path: '/home/ertan/.vscode/extensions/extensions.json',
  query: '',
  fragment: '',
  _formatted: 'file:///home/ertan/.vscode/extensions/extensions.json',
  _fsPath: '/home/ertan/.vscode/extensions/extensions.json'
}
TRACE Scanned system extensions: 88
TRACE Scanned user extensions: 39
TRACE Started scanning system extensions
TRACE Started scanning user extensions r {
  scheme: 'file',
  authority: '',
  path: '/home/ertan/.vscode/extensions/extensions.json',
  query: '',
  fragment: '',
  _formatted: 'file:///home/ertan/.vscode/extensions/extensions.json',
  _fsPath: '/home/ertan/.vscode/extensions/extensions.json'
}
TRACE Scanned system extensions: 88
TRACE Scanned user extensions: 39
TRACE Started scanning system extensions
TRACE Started scanning user extensions r {
  scheme: 'file',
  authority: '',
  path: '/home/ertan/.vscode/extensions',
  query: '',
  fragment: '',
  _formatted: 'file:///home/ertan/.vscode/extensions',
  _fsPath: '/home/ertan/.vscode/extensions'
}
TRACE Scanned system extensions: 88
TRACE Scanned user extensions: 39
TRACE Started extracting the extension from /home/ertan/.config/Code/CachedExtensionVSIXs/ms-dotnettools.csharp-1.25.4-linux-x64 to /home/ertan/.vscode/extensions/.cbe06145-5aa2-4664-9ef7-1ab89aa6ed05
TRACE [File Watcher (node.js)] [raw] ["rename"] .cbe06145-5aa2-4664-9ef7-1ab89aa6ed05
TRACE [File Watcher (node.js)] [ADDED] /home/ertan/.vscode/extensions/.cbe06145-5aa2-4664-9ef7-1ab89aa6ed05
TRACE [File Watcher (node.js)] >> normalized [ADDED] /home/ertan/.vscode/extensions/.cbe06145-5aa2-4664-9ef7-1ab89aa6ed05

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.74.3
**C# Extension**: 1.25.4

<details><summary>Mono Information</summary>
        There is a problem with running OmniSharp on mono: Error: Unable to find Mono. Ensure that Mono's '/bin' folder is added to your environment's PATH variable.</details>
<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.102/

Host:
  Version:      7.0.2
  Architecture: x64
  Commit:       d037e070eb

.NET SDKs installed:
  6.0.405 [/usr/share/dotnet/sdk]
  7.0.102 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.13 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.13 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|bracket-pair-color-dlw|BracketPairColorDLW|0.0.6|
|cmake|twxs|0.0.17|
|cmake-tools|ms-vscode|1.13.43|
|cpptools|ms-vscode|1.13.9|
|cpptools-extension-pack|ms-vscode|1.3.0|
|cpptools-themes|ms-vscode|2.0.0|
|csharp|ms-dotnettools|1.25.4|
|csharpextensions|kreativ-software|1.7.3|
|github-markdown-preview|bierner|0.3.0|
|github-vscode-theme|GitHub|6.3.3|
|gitlens|eamodio|13.2.0|
|gitpod-desktop|gitpod|0.0.71|
|intellicode-api-usage-examples|VisualStudioExptTeam|0.2.7|
|JavaScriptSnippets|xabikos|1.8.0|
|jquerysnippets|donjayamanne|0.0.1|
|LiveServer|ritwickdey|5.7.9|
|markdown-checkbox|bierner|0.4.0|
|markdown-emoji|bierner|0.3.0|
|markdown-footnotes|bierner|0.1.1|
|markdown-mermaid|bierner|1.17.4|
|markdown-preview-enhanced|shd101wyy|0.6.7|
|markdown-preview-github-styles|bierner|1.0.1|
|markdown-yaml-preamble|bierner|0.1.0|
|npm-intellisense|christian-kohler|1.4.4|
|prettier-vscode|esbenp|9.10.4|
|remote-explorer|ms-vscode|0.0.3|
|remote-ssh|ms-vscode-remote|0.94.0|
|remote-ssh-edit|ms-vscode-remote|0.84.0|
|rest-client|humao|0.25.1|
|theme-dracula|dracula-theme|2.24.2|
|vscode-csharp-snippets|jorgeserrano|1.1.0|
|vscode-eslint|dbaeumer|2.2.6|
|vscode-gutter-preview|kisstkondoros|0.30.0|
|vscode-icons|vscode-icons-team|12.2.0|
|vscode-language-babel|mgmcdermott|0.0.36|
|vscode-mdx|unifiedjs|1.2.1|
|vscode-mdx-preview|xyc|0.3.3|
|vscode-yaml|redhat|1.11.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.30|;

</details>

**Comment by PieterjanDeClippel** [comment]
Having the same, but it appears that you just have to wait a really, really long time (like 5 minutes). VS Code will get there eventually

**Comment by Ertan222** [comment]
@PieterjanDeClippel I waited for a looong time. It's not about that.

**Comment by JoeRobich** [comment]
A lot has changed with O# packaging and acquisition of dependencies since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
