### ISSUE TITLE
Unable to step into Console.WriteLine in .NET 6 macos-arm64

### ISSUE THREAD

**Issue by v-xiaofchen** [dotnet/vscode-csharp#5563]
## Environment data
`dotnet --info` output:
.NET SDK (reflecting any global.json):
 Version:   6.0.114
 Commit:    346c0065dd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.6
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.114/

global.json file:
  Not found

Host:
  Version:      6.0.14
  Architecture: arm64
  Commit:       2a90daa2cc

.NET SDKs installed:
  6.0.114 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.14 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

VS Code version: 1.74.3
C# Extension version: 1.25.4

## Steps to reproduce
1.	Create a new ASP.NET Razor project by doing
 
mkdir razor
cd razor
dotnet new razor
 
2.	Install VS code (if you have not already) https://code.visualstudio.com/Download 
3.	Launch VSCode and install the C# extension. 
4.	Install the 1.15 or later C# (by OmniSharp) Extention (View -> Extensions, then type OmniSharp, and click on ‘Install’) 
5.	Use File -> Open Folder to open the razor folder you have created in step 1
6.	It may ask at the bottom right to install assets to build and debug, say yes.  
7.	After it has done this it will have created a .vscode directory in the ‘razor’ directory and a ‘launch.json’ file in that directory.   Open the ‘.vscode’ directory, and double click on the ‘launch.json to edit it. 
8.	Add the following lines after the “name” line of the “Configurations” object.   (This allows debugging through the framework.  
 
"justMyCode": false,
"symbolOptions": {
      "searchMicrosoftSymbolServer": true
},
"suppressJITOptimizations": true,
 
 
9.	Double click on the ‘Startup.cs’ file in the ‘Explorer’ pane to bring up that source code. 
10.	 Add the following line to the Startup.cs file at the beginning of the ‘Configure’ method (at the bottom of the file).  
Console.WriteLine("x " + 3);
 
11.	Place a breakpoint on that line (F9). 
12.	Run the application until it hit that breakpoint (F5).   It will load symbols from the Microsoft symbol server, and may take a few seconds to hit the breakpoint.   You should see 20-30 lines of ‘Loaded XXX Symbols loaded’.  Lines as it does this).  
13.	Step into the concatination method (F11).   This tests CoreCLR symbols   AT THIS POINT IT SHOULD SHOW YOU THE SOURCE CODE FOR Concat().  If it does not that is a FAILURE.  Please report it.  
14.	Step out of Concat (Shift F11).   Then step into Console.WriteLine (F11). 

## Expected  behavior
This tests CoreFX symbols AT THIS POINT IT SHOULD SHOW YOU THE SOURCE CODE FOR Console.WriteLine().

## Actual behavior
Razor exit with code 0(0x0).
![image](https://user-images.githubusercontent.com/99376012/215316574-87647c38-e715-4d00-a258-f7f28527e99a.png)

Note: It can work fine on mac x64.

**Comment by v-xiaofchen** [comment]
This issue does not repro on SDK 7.0.103.

**Comment by v-xiaofchen** [comment]
Still repro on SDK 6.0.115.

**Comment by v-xiaofchen** [comment]
Still repro on SDK 6.0.418 on mac ARM64, keep tracking.
![6 0IL](https://github.com/dotnet/vscode-csharp/assets/99376012/51f1d67f-a7b2-48a7-b769-7f4775930afa)

**Comment by gregg-miskelly** [comment]
Can you try adding the following to your launch.json?

```json
"env": {
        "COMPlus_ReadyToRun": "0"
    }
```

**Comment by v-xiaofchen** [comment]
@gregg-miskelly It works fine after adding them to my launch.json. Thanks for your help.

> Can you try adding the following to your launch.json?
> 
> ```json
> "env": {
>         "COMPlus_ReadyToRun": "0"
>     }
> ```
