### ISSUE TITLE
Go to type definition does not work

### ISSUE THREAD

**Issue by strowk** [dotnet/vscode-csharp#5564]
## Issue Description ##

Clicking with cntrl on some of symbols (names) does not produce any effect. I also get warn message in OmniSharp Log output saying "No symbol found".

## Steps to Reproduce ##

In c# code click with cntrl on any name - it should open file. Nothing would happen and warning would be logged. Then if that file opened manually (by searching it using cntrl+P , then after returning back to original file - the same operation works as expected.

## Expected Behavior ##

Code navigation should work without opening files previously (otherwise it does not really make much sense).

## Actual Behavior ##

Have to preopen the file to be able to navigate to it later. If try to navigate to class in previously unopened file, it would only produce warn message.

### OmniSharp log ###
[warn]: OmniSharp.Roslyn.CSharp.Services.Navigation.FindUsagesService
        No symbol found. File: /home/.../MyClass.cs, Line: 58, Column: 75.

### C# log ###
there is nothing in this log

## Environment information ##

**VSCode version**: 1.74.2
**C# Extension**: 1.25.4

<details><summary>Mono Information</summary>
        OmniSharp using mono: 6.12.0</details>
<details><summary>Dotnet Information</summary>
Found dotnet version 3.1.422. Minimum required version is 6.0.100.

Note: I cannot use any versions newer than 3, this is our project requirement. I have disabled modern flag in configuration though, so I expect mono to work.
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.11.3|
|azure-iot-edge|vsciot-vscode|1.25.11|
|azure-iot-toolkit|vsciot-vscode|2.17.1|
|azure-iot-tools|vsciot-vscode|0.3.0|
|cloudformation-yaml-snippets|dannysteenman|3.93.0|
|csharp|ms-dotnettools|1.25.4|
|git-compose|git-compose|0.5.3|
|gitlens|eamodio|13.2.0|
|gnuplot|fizzybreezy|0.1.3|
|gnuplot|mammothb|1.0.5|
|multi-command|ryuta46|1.6.0|
|prettier-vscode|esbenp|9.10.4|
|remote-containers|ms-vscode-remote|0.266.1|
|remote-explorer|ms-vscode|0.0.3|
|remote-ssh|ms-vscode-remote|0.94.0|
|remote-ssh-edit|ms-vscode-remote|0.84.0|
|remote-wsl|ms-vscode-remote|0.72.0|
|rust-analyzer|rust-lang|0.3.1386|
|search-json-path|guilhermeavanci|0.0.5|
|sqltools|mtxr|0.27.1|
|sqltools-driver-mssql|mtxr|0.4.1|
|sqltools-driver-mysql|mtxr|0.5.1|
|terraform|hashicorp|2.25.2|
|vscode-azurefunctions|ms-azuretools|1.9.0|
|vscode-azureresourcegroups|ms-azuretools|0.5.6|
|vscode-drawio|hediet|1.6.6|
|vscode-eslint|dbaeumer|2.2.6|
|vscode-iot-device-cube|vsciot-vscode|0.3.0|
|vscode-iot-workbench|vsciot-vscode|0.16.0|
|vscode-remote-extensionpack|ms-vscode-remote|0.23.0|
|vsliveshare|ms-vsliveshare|1.0.5823|;

</details>

**Comment by JoeRobich** [comment]
A lot has changed with O# since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
