### ISSUE TITLE
Get CA1825 warning in place of constructor with params string[]

### ISSUE THREAD

**Issue by AlexandrValerevich** [dotnet/vscode-csharp#5572]
Hi, I get warning CA1825 with message `Avoid unnecessary zero-length array allocations.  Use Array.Empty<string>() instead.` in code:
```charp
    [Consumes(MediaTypeNames.Application.Json)]
    [Produces(MediaTypeNames.Application.Json)]
```
It occurred after update Vs code from version *1.7.1* to *1.7.5*.

**Comment by ed555009** [comment]
same here

**Comment by filipw** [comment]
This is a problem in dotnet analyzers - see https://github.com/dotnet/roslyn-analyzers/pull/6114
It was already fixed there and will be inherited by OmniSharp.
