### ISSUE TITLE
Method declaration new line open parenthesis color coding failure

### ISSUE THREAD

**Issue by ccalhoun1999** [dotnet/vscode-csharp#5576]
## Issue Description ##
Method definition with opening parenthesis on following line causes intellisense to stop working properly.
Example:
```
private void ExampleMethod
(
   int param1,
   int param2
{
   // code from here will not be color coded
}
```
## Steps to Reproduce ##
Paste the above code into a CSharp file. Code following the opening parenthesis will for the most part not be color coded properly.

## Expected Behavior ##
Color coding should be consistent throughout the entire file.

## Actual Behavior ##
Color coding after the opening parenthesis is not consistently color coded.

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.74.3
**C# Extension**: 1.25.4

<details><summary>Mono Information</summary>
        OmniSharp using mono: 6.12.0</details>
<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.6
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.100/

Host:
  Version:      7.0.0
  Architecture: arm64
  Commit:       d099f075e4

.NET SDKs installed:
  7.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.25.4|
|gitlens|eamodio|13.2.0|
|one-monokai|azemoh|0.5.0|
|shader|slevesque|1.1.5|
|unity-debug|Unity|3.0.2|
|vscode-edit-csv|janisdd|0.7.2|;

</details>

**Comment by JoeRobich** [comment]
The C# extension ships with semantic highlighting support as well as an improved textmate grammar.
