### ISSUE TITLE
VS Code: After installing the "C#" extension, "No extensions found" is displayed in INSTALLED.

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/vscode-csharp#5577]
## Environment data
VS Code version: [1.75.0](https://code.visualstudio.com/Download)
C# Extension version: [1.25.4](https://github.com/OmniSharp/omnisharp-vscode/releases)
VS 2022: 17.4.4

 **Platform**

- [x] Windows
- [x] Linux
- [x] Mac

## Steps to reproduce

1. Open VS Code
2. Go to [https://github.com/OmniSharp/omnisharp-vscode/releases](https://github.com/OmniSharp/omnisharp-vscode/releases) > Download the csharp-1.25.4-win32-x64.vsix.
3. In VS Code and go to the Extensions Tab, select "Install from VSIX" > install the file you downloaded.
4. After installing finished, there is one extension "C#" shows up.

**Actual behavior:**
After the installation is complete, No extensions found is displayed in INSTALLED.
![image](https://user-images.githubusercontent.com/71361488/217137183-fd5780ba-5eb0-4f7f-b8d8-f49c13b7b49e.png)

**Expected behavior:**
After the installation is complete, there will show extension "C#" in INSTALLED.
![image](https://user-images.githubusercontent.com/71361488/217137384-03da8cdc-4e75-4cf1-bb76-1c132c8d4b5e.png)

**Additional context:**
Note: 
1. After the installation is complete, click Refresh and the extension "C#" will be displayed in INSTALLED.
2. This issue does not repro on VS Code 1.74.3.

**Comment by v-wenkecheng** [comment]
This repro is also reproduced in SDK 7.0.300-preview.23159.18

**Comment by JoeRobich** [comment]
Unable to reproduce with current release.
