### ISSUE TITLE
Inlay Hint for non-nullable var shows as nullable

### ISSUE THREAD

**Issue by JustinGrote** [dotnet/vscode-csharp#5581]
Type: <b>Bug</b>

```csharp
using Ping ping = new();
var pingTask = ping.SendPingAsync(Hostname, Timeout * 1000);
```
![image](https://user-images.githubusercontent.com/15258962/218859799-897c0b0d-cacb-440a-a5f7-3f4495deaca9.png)

![image](https://user-images.githubusercontent.com/15258962/218859890-1d1006cf-eebe-44b4-91c4-691ac7b83a0b.png)

This should be `Task<PingReply>` without the `?`

----
Extension version: 1.25.4
VS Code version: Code - Insiders 1.76.0-insider (af4a70d991053dcbf64d9a86c76a02dced81d9c4, 2023-02-14T05:22:59.020Z)
OS version: Windows_NT x64 10.0.22623
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.69GB (3.61GB free)|
|Process Argv|--crash-reporter-id 452cacee-4d7b-4088-b47c-d8efa68952a0 --crash-reporter-id 452cacee-4d7b-4088-b47c-d8efa68952a0|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
6233i204:30659907
pythonb192:30661256

```

</details>

**Comment by JoeRobich** [comment]
This is by design. To the C# compiler the type of `pingTask` is nullable. It just happens to be `not null` after assignment.

**Comment by JustinGrote** [comment]
@JoeRobich thanks for taking a look! Why would the inlay hint and the popup be different then? Shouldn't the popup also show ?

**Comment by JoeRobich** [comment]
The quick info is showing you the definition of the method which has a return type that is not nullable. It is part of the [feature spec](https://github.com/dotnet/roslyn/blob/3bc2a12596187a792e467f07801c5a16c078e2d0/docs/features/nullable-reference-types.md?plain=1#L168) that `var` will be the nullable version of the inferred type.
