### ISSUE TITLE
During IntelliSense autocomplete, the tab doesn't work as expected

### ISSUE THREAD

**Issue by Kotsuha** [dotnet/vscode-csharp#5582]
## Issue Description ##

During IntelliSense autocomplete, the tab doesn't work as expected.

![image](https://user-images.githubusercontent.com/10438710/218893870-29b27479-601f-4500-a46f-36814e3c4217.png)

This issue starts from VSCode-win32-x64-1.75.0
It was fine in VSCode-win32-x64-1.74.3

## Environment information ##

**VSCode version**: 1.75.1
**C# Extension**: 1.25.4

<details><summary>Dotnet Information</summary>
Found dotnet version 5.0.412. Minimum required version is 6.0.100.</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.25.4|;

</details>

**Comment by heartacker** [comment]
yes

**Comment by Kotsuha** [comment]
I just found another extension ([vscode-input-sequence](https://marketplace.visualstudio.com/items?itemName=tomoki1207.vscode-input-sequence)) that becomes "not functioning normally" in VSCode `1.75.0`, and it works fine in `1.74.3`. It's also an issue related to key press. Maybe something fundamentally changed in VSCode after `1.75.0`. Maybe I should open an issue in the [vscode](https://github.com/microsoft/vscode) repository instead.

**Comment by JoeRobich** [comment]
Cannot reproduce with the latest release.
