### ISSUE TITLE
There is no code actions available when use quick action on the "HttpProtocols" for 8.0 gRPC project

### ISSUE THREAD

**Issue by dibarbet** [dotnet/vscode-csharp#5583]
INSTALL STEPS

1. Clean machine: MacOS: Big Sur 
2. Install 8.0 SDK from: https://aka.ms/dotnet/8.0.1xx/daily/dotnet-sdk-osx-x64.pkg
3. Feed: https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json

REPRO STEPS
Create a gRPC service via Terminal Emulator and open it with VS Code
mkdir GrpcGreeter  
cd GrpcGreeter
dotnet new grpc 
code .
        2. Install the required C# Extension [[v1.25.3](https://github.com/OmniSharp/omnisharp-vscode/releases)]
        3. Open Program.cs and add the following code in this file.
builder.Services.AddGrpc();
builder.WebHost.ConfigureKestrel(options =>
{
  // Setup a HTTP/2 endpoint without TLS.
  options.ListenLocalhost(5000, o => o.Protocols = HttpProtocols.Http2);
});
var app = builder.Build();
        4. On the 'HttpProtocols', use quick action to add "using Microsoft.AspNetCore.Server.Kestrel.Core;".

ACTUAL
![image](https://user-images.githubusercontent.com/5749229/219172305-d5d3666a-7ab5-46e2-9272-1eed8c9d9b76.png)

Expected
![image](https://user-images.githubusercontent.com/5749229/219172340-c65ba2b3-1329-468b-9c8d-fffbf044eb8d.png)

**Comment by wellintonperazzoli** [comment]
Having the same issue here.

**Comment by JoeRobich** [comment]
A lot has changed with O# code analysis since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
