### ISSUE TITLE
O# server does not start with vs-code in a virtual workspace

### ISSUE THREAD

**Issue by birdracoon** [dotnet/vscode-csharp#5585]
I have a problem starting the O# server with Visual Studio Code in a [virtual workspace](https://code.visualstudio.com/api/extension-guides/virtual-workspaces).

- The files are to be edited remotely, for which I have implemented my own [FileSystemProvider](https://code.visualstudio.com/api/extension-guides/virtual-documents#file-system-api). 
- For Editing, I generate a folder that also contains the .csproj file and when I copy the generated folder into my local file system, starting and editing via O# works perfectly.
- I have also tried to start the O# server via the command palette. However, it does not start and I do not get any log messages.
 
Is there anything else to consider with O# and virtual workspaces or any known limitations?
Could it possibly be because I need the /.vscode/ folder as I don't generate it or are there restrictions on running O# in the extensions debugger?

**Comment by JoeRobich** [comment]
The O# project system relies on MSBuild to perform a design time build and it is unaware of any virtual file system.
