### ISSUE TITLE
Omnisharp simply stops working

### ISSUE THREAD

**Issue by generateui** [dotnet/vscode-csharp#5593]
## Issue Description ##
After I restart vscode or Omnisharp, it is analyzing the files and folders in the target workspace directory. However, after sometime it ends with a message and then stops. "Stops" in the sense of intellisense for C# does not work, autosuggest does not work and any language feature does not work. the last message of the log is
```
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: SerilogExtensions.Tests
```

The interesting part is that a similar repo just works. I have recloned the offending repo in another folder with same results. It suddenyl stopped working, I have not recorded the trigger of the problem. I think it must have been so in the timeframe of ~3 weeks ago until ~1 week ago when it broke.

It broke before update to MacOS Ventura, and the upgrade did not affect the current broken behavior.
It broken before the update of vscode, and the upgrade did not affect the current broken behavior.
## Expected Behavior ##
Language services to work

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.75.1
**C# Extension**: 1.25.4

<details><summary>Mono Information</summary>
        There is a problem with running OmniSharp on mono: Error: Unable to find Mono. Ensure that Mono's '/bin' folder is added to your environment's PATH variable.</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.401
 Commit:    0906eae6f8

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.2
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.401/

global.json file:
  Not found

Host:
  Version:      6.0.9
  Architecture: x64
  Commit:       163a63591c

.NET SDKs installed:
  6.0.401 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.30 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.25.4|
|githistory|donjayamanne|0.6.19|
|gitlens|eamodio|13.2.0|
|svg-preview|SimonSiefke|2.8.3|
|vscode-configurable-windowtitle|undefined_publisher|0.0.1|
|vscode-diff|fabiospampinato|1.4.2|
|vscode-diff-viewer|caponetto|1.4.0|
|vscode-drawio|hediet|1.6.6|
|vscode-position|jtr|1.1.2|;

</details>

**Comment by generateui** [comment]
I have narrowed down the problem. In  my `.csproj` file, I have:
```xml
	<Import Project="Styling/styling.targets" />
```
of which the contents of `styling.targets` is
```xml
<Project>
  <Target Name="StylingNpmRestore"
          AfterTargets="CollectPackageReferences"
          Inputs="package-lock.json"
          Outputs="$(BaseIntermediateOutputPath)/StylingNpmRestore">
    <Message Text="Restore styling packages" Importance="high" />
    <Exec Command="npm ci"
          WorkingDirectory="$(MSBuildThisFileDirectory)" />
    <MakeDir Directories="$(BaseIntermediateOutputPath)" />
    <Touch Files="$(BaseIntermediateOutputPath)/StylingNpmRestore"
           AlwaysCreate="true" />
  </Target>

  <ItemGroup>
    <Scss Include="$(MSBuildThisFileDirectory)*.scss" />
    <Scss Include="$(MSBuildProjectDirectory)/specific.scss" Condition="Exists('$(MSBuildProjectDirectory)/specific.scss')" />
  </ItemGroup>

  <Target Name="scss2css" AfterTargets="Build"
          Inputs="@(Scss)"
          Outputs="$(MSBuildProjectDirectory)/wwwroot/css/main.css">
    <MakeDir Directories="$(MSBuildProjectDirectory)/wwwroot/css/" />
    <Message Text="@(Scss) Outputting to: &quot;$(MSBuildProjectDirectory)/wwwroot/css/main.css&quot;" Importance="high" />
    <Exec Command="node &quot;$(MSBuildThisFileDirectory)compile-sass.js&quot; -o &quot;$(MSBuildProjectDirectory)/wwwroot/css/main.css&quot; &quot;$(MSBuildThisFileDirectory)base.scss&quot;"
          WorkingDirectory="$(MSBuildThisFileDirectory)"/>
  </Target>
</Project>
```

When I comment the reference to the `styling.targets` file and relowd Omnisharp, all goes as expected. I believe
```xml
  <Target Name="StylingNpmRestore"
```
may be the issue.

**Comment by JoeRobich** [comment]
A lot has changed with O# project loading since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
