### ISSUE TITLE
Error - Unable to generate assets to build and debug

### ISSUE THREAD

**Issue by gbrac** [dotnet/vscode-csharp#5597]
I have tried to run through the HelloWorld sample from Microsoft for C# on VS Code. On both Windows and a Mac, I get the error: Unable to generate assets to build and debug. OmniSharp server is not running. I have the C# extension, .NET Core 7 SDK installed, etc.

**Comment by JoeRobich** [comment]
A lot has changed with O# since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
