### ISSUE TITLE
System.Linq.Expression not Recognized / Suggested by Omnisharp

### ISSUE THREAD

**Issue by davidhmays** [dotnet/vscode-csharp#5605]
Please paste the output from your clipboard## Issue Description ##
## Steps to Reproduce ##
In a .cs file, try adding "using _System.Linq._Expression_" and notice that expression is not suggested, and if manually input it is highlighted. 

Also nothing is suggested when trying to use "Expression" such as in this example:
Task<IReadOnlyCollection<T>> GetAllAsync(Expression<Func<T, bool>> filter);

Finally, trying to use 'dotnet add package "System.Linq.Expression" does not fail, but still does not get Expressions recognized.

(Project is .NET 7)
## Expected Behavior ##
Omnisharp should be recognizing System.Linq.Expression and suggesting it when entering "." after "System.Linq".

## Actual Behavior ##
System.Linq.Expression not Recognized / Suggested by Omnisharp

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.75.1
**C# Extension**: 1.25.4

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.102\

Host:
  Version:      7.0.2
  Architecture: x64
  Commit:       d037e070eb

.NET SDKs installed:
  5.0.401 [C:\Program Files\dotnet\sdk]
  6.0.200 [C:\Program Files\dotnet\sdk]
  7.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  arm64 [C:\Program Files\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\arm64\InstallLocation]
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|blazorwasm-companion|ms-dotnettools|1.1.4|
|calva|betterthantomorrow|2.0.335|
|csharp|ms-dotnettools|1.25.4|
|dark-mint-vscode-theme|hugolcouto|4.4.0|
|dart-code|Dart-Code|3.60.1|
|es6-string-css|bashmish|0.1.0|
|flutter|Dart-Code|3.60.0|
|galax-theme|daniel-lvovsky|0.0.1|
|git-graph|mhutchie|1.30.0|
|gruvbox-material|sainnhe|6.5.2|
|intellicode-api-usage-examples|VisualStudioExptTeam|0.2.7|
|Ionide-fsharp|Ionide|7.5.1|
|LiveServer|ritwickdey|5.7.9|
|material-theme|zhuangtongfa|3.15.6|
|midnight-synth|ekelley|2.1.1|
|mongodb-vscode|mongodb|0.10.0|
|monokai-charcoal-high-contrast|74th|3.4.0|
|night-owl|sdras|2.0.1|
|radical-vscode|dhedgecock|3.3.1|
|rainbow-brackets|2gua|0.0.6|
|razor-switcher|LennartKleymann|1.0.0|
|synthwave-vscode|RobbOwen|0.1.15|
|theme-bluloco-dark|uloco|3.7.4|
|theme-monokai-hc|DataByne|1.1.1|
|tokyo-night|enkia|0.9.7|
|visual-nuget|fullstackspider|0.2.1|
|vscode-dotnet-runtime|ms-dotnettools|1.6.0|
|vscode-icons|vscode-icons-team|12.2.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.30|
|z-theme|Zortea|0.0.2|
|zeonica|andrewvallette|1.4.0|;

</details>

**Comment by JoeRobich** [comment]
A lot has changed with O# since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
