### ISSUE TITLE
Not reporting IDE0161 defined in editorconfig

### ISSUE THREAD

**Issue by Indeedornot** [dotnet/vscode-csharp#5606]
## Issue Description ##
Omnisharp does not report IDE0161

## Steps to Reproduce ##
1. Run `dotnet new console -n reprod`
2. Set file content to
```cs
namespace MyApp {
    public class Program {
        public static void Main(string[] args) {
            Console.WriteLine("Hello World!");
        }
    }
}
```
3. Add .editorconfig with following rules included
```editorconfig
root = true

[*.cs]
csharp_style_namespace_declarations = file_scoped:error
dotnet_diagnostic.IDE0161.severity = error
```

## Expected Behavior ##
Report of IDE0161 and possible ability to refactor it to file-scoped namespace (vs2022 screenshot)
![image](https://user-images.githubusercontent.com/49447848/222754811-1dacc5d5-7b4e-47d3-85a8-d255d856bbb7.png)

## Actual Behavior ##
Nothing happens
![image](https://user-images.githubusercontent.com/49447848/222754962-f8fcad3a-0e31-4735-805c-a413ce541fe7.png)

### OmniSharp log ###
<details>Starting OmniSharp server at 3/3/2023, 4:08:09 PM
    Target: c:\Users\Indeed\Desktop\IDE0161

OmniSharp server started with .NET 7.0.201
.
    Path: c:\Users\Indeed\.vscode\extensions\ms-dotnettools.csharp-1.25.4-win32-x64\.omnisharp\1.39.4-net6.0\OmniSharp.dll
    PID: 2884

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 10.0.22621.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: .NET Core SDK 7.0.201 17.5.0 - "C:\Program Files\dotnet\sdk\7.0.201\"
            2: .NET Core SDK 6.0.114 17.0.1 - "C:\Program Files\dotnet\sdk\6.0.114\"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: .NET Core SDK 7.0.201 17.5.0 - "C:\Program Files\dotnet\sdk\7.0.201\"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\Indeed\Desktop\IDE0161'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Did not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Users\Indeed\Desktop\IDE0161'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Users\Indeed\Desktop\IDE0161\IDE0161.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\Indeed\Desktop\IDE0161'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Did not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\Indeed\Desktop\IDE0161' on host 16760.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Users\Indeed\Desktop\IDE0161\IDE0161.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Users\Indeed\Desktop\IDE0161\IDE0161.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Users\Indeed\Desktop\IDE0161\IDE0161.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: IDE0161</details>

### C# log ###
Empty

## Environment information ##

**VSCode version**: 1.76.0
**C# Extension**: 1.25.4

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.201
 Commit:    68f2d7e7a3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.201\

Host:
  Version:      7.0.3
  Architecture: x64
  Commit:       0a2bda10e8

.NET SDKs installed:
  6.0.114 [C:\Program Files\dotnet\sdk]
  7.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|2077-theme|Endormi|1.5.3|
|add-reference|adrianwilczynski|1.0.2|
|aspnetcorerazor-html-css-class-completion|kevin-chatham|1.0.3|
|atom-material-theme|tobiasalthoff|1.10.9|
|auto-rename-tag|formulahendry|0.1.10|
|ayu|teabyii|1.0.5|
|batch-rename-extension|JannisX11|0.0.6|
|better-comments|aaron-bond|3.0.2|
|blazor-snippet-pack|adrianwilczynski|2.6.1|
|Bookmarks|alefragnani|13.3.1|
|calc|raidou|2.3.1|
|code-autocomplete|svipas|1.2.1|
|copilot|GitHub|1.77.9225|
|cornflakes-linter|kevinglasson|0.5.1|
|csharp|ms-dotnettools|1.25.4|
|Csharp-ASPNETCore|rahulsahay|1.11.0|
|csharpextensions|kreativ-software|1.7.3|
|deepdark-material|Nimda|3.3.0|
|docomment|k--kato|0.1.32|
|EditorConfig|EditorConfig|0.16.4|
|electron|kuscamara|0.2.6|
|errorlens|usernamehw|3.7.0|
|explicit-folding|zokugun|0.23.1|
|gdscript|jjkim|0.0.2|
|git-commit-message-editor|phoihos|0.6.3|
|git-graph|mhutchie|1.30.0|
|github-markdown-preview|bierner|0.3.0|
|github-plus-theme|thenikso|1.4.3|
|github-vscode-theme|GitHub|6.3.3|
|godot-hover-docs|RedMser|0.0.1|
|godot-tools|geequlim|1.3.1|
|gruvbox|jdinhlife|1.8.0|
|html-css-class-completion|Zignd|1.20.0|
|html5-boilerplate|sidthesloth|1.1.1|
|indent-rainbow|oderwat|8.3.1|
|inifmt|lkrms|0.1.5|
|intellicode-api-usage-examples|VisualStudioExptTeam|0.2.7|
|java|redhat|1.15.0|
|jupyter-keymap|ms-toolsai|1.1.0|
|markdown-checkbox|bierner|0.4.0|
|markdown-emoji|bierner|0.3.0|
|markdown-footnotes|bierner|0.1.1|
|markdown-mermaid|bierner|1.17.4|
|markdown-preview-github-styles|bierner|1.0.1|
|markdown-yaml-preamble|bierner|0.1.0|
|material-icon-theme|PKief|4.24.0|
|npm|idered|1.3.0|
|nugetpackagemanagergui|aliasadidev|2.0.6|
|one-monokai|azemoh|0.5.0|
|prettier-vscode|esbenp|9.10.4|
|prettyxml|PrateekMahendrakar|3.0.1|
|prisma|Prisma|4.11.0|
|quick-terminal|Fooxly|1.0.7|
|quokka-vscode|WallabyJs|1.0.527|
|remote-repositories|ms-vscode|0.30.0|
|remotehub|GitHub|0.52.0|
|Safurai|Safurai|0.0.5|
|sln-support|logerfo|0.0.1|
|sonarlint-vscode|SonarSource|3.15.1|
|svelte-vscode|svelte|107.1.2|
|svg-preview|SimonSiefke|2.8.3|
|terminal-command-keys|petekinnecom|0.3.0|
|test-adapter-converter|ms-vscode|0.1.6|
|theme|tal7aouy|2.5.0|
|theme-bear|dahong|2.1.0|
|theme-bluloco-dark|uloco|3.7.4|
|theme-bluloco-light|uloco|3.7.3|
|theme-dracula-at-night|bceskavich|2.7.1|
|Theme-FlatlandMonokai|gerane|0.0.6|
|theme-material-theme|jprestidge|1.0.1|
|Theme-MaterialKit|ms-vscode|0.1.4|
|theme-monokai-pro-vscode|monokai|1.2.0|
|theme-oceanicnext|naumovs|0.0.4|
|theme-omni|rocketseat|1.0.12|
|theme-onedark|azemoh|0.6.0|
|theme-panda|tinkertrain|1.3.0|
|ts-error-translator|mattpocock|0.8.0|
|tsimporter|pmneo|2.0.1|
|turbo-console-log|ChakrounAnas|2.7.1|
|user-secrets|adrianwilczynski|2.0.1|
|vsc-community-material-theme|Equinusocio|1.4.4|
|vsc-material-theme|Equinusocio|33.6.0|
|vsc-python-indent|KevinRose|1.18.0|
|vscode-chatgpt|gencay|3.9.0|
|vscode-commit-reminder|Kurozero|0.3.0|
|vscode-docker|ms-azuretools|1.24.0|
|vscode-dotnet-runtime|ms-dotnettools|1.6.0|
|vscode-eslint|dbaeumer|2.4.0|
|vscode-github-actions|cschleiden|0.24.4|
|vscode-html-css|ecmel|1.13.1|
|vscode-html-format|mohd-akram|0.0.5|
|vscode-icon-theme|jtlowe|1.6.6|
|vscode-icons|vscode-icons-team|12.2.0|
|vscode-import-cost|wix|3.3.0|
|vscode-intelli-refactor|ypresto|0.1.2|
|vscode-javascript-booster|sburg|14.0.1|
|vscode-jest|Orta|5.2.3|
|vscode-jupyter-cell-tags|ms-toolsai|0.1.6|
|vscode-jupyter-slideshow|ms-toolsai|0.1.5|
|vscode-markdownlint|DavidAnson|0.49.0|
|vscode-monokai-night|fabiospampinato|1.6.2|
|vscode-paste-image|mushan|1.0.4|
|vscode-peacock|johnpapa|4.2.2|
|vscode-solution-explorer|fernandoescolar|0.8.1|
|vscode-svelte-snippets|fivethree|0.5.0|
|vscode-tailwindcss|bradlc|0.9.7|
|vscode-test-explorer|hbenl|2.21.1|
|vscode-theme-darcula|rokoroku|1.2.3|
|vscode-todo-plus|fabiospampinato|4.19.1|
|vscode-typescript-exportallmodules|eliostruyf|2.6.0|
|vscode-typescript-next|ms-vscode|5.1.20230302|
|vscode-versionlens|pflannery|1.5.0|
|vscode-wakatime|WakaTime|24.0.7|
|vscodeintellicode|VisualStudioExptTeam|1.2.30|
|vscord|LeonardSSH|5.0.20|
|zoombar-vscode|wraith13|1.4.4|;

</details>

**Comment by JoeRobich** [comment]
A lot has changed with O# code analysis since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
