### ISSUE TITLE
Support XDG directory specification

### ISSUE THREAD

**Issue by tiritto** [dotnet/vscode-csharp#5607]
Omnisharp is automatically creating a new directory under `$HOME/.omnisharp`, instead of using `$XDG_DATA_HOME/.omnisharp` directory under Linux. In order to adhere to [XDG Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) `$XDG_DATA_HOME` path should take priority over `$HOME` whenever its declared.

**Comment by kands-code** [comment]
> Omnisharp is automatically creating a new directory under `$HOME/.omnisharp`, instead of using `$XDG_DATA_HOME/.omnisharp` directory under Linux.

I think `${XDG_DATA_HOME:-$HOME/.local/share}/omnisharp` is a much better choice.

**Comment by JoeRobich** [comment]
This sounds like an issue with O#. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
