### ISSUE TITLE
Omnisharp server starts but not loaded 

### ISSUE THREAD

**Issue by faizu2k01** [dotnet/vscode-csharp#5610]
I started visual studio code to create a .NET project with 
Setup --
.NET 7 (Latest)
C# extension (Latest)
Visual studio Code (Latest)

Then I created WebApi application using "dotnet new webapi -n nameing" command and it worked fine.
When I try to generate required assets folder by using the command ".NET>Generate required assets"
It throws and error which said "Unable to generate the assets because the omnisharp server is not running.".

I search for it and used multiple methods like--
1-running the "Omnisharp>Restart" command
2-re-install everything includes C#,.NET even VS code
3-Extend the omnisharp server load time till 1000
4-Created a solution of dotnet and set the target omnisharp server path for it

But nothing worked for me and still I'm facing the same issue "The Omnisharp server not running."
Even if it is visual in the Task manager.

I'm attaching some images of the same scenario which I'm facing 
If somebody require some more detail about this issue pls raise a comment .

![Image 1](https://user-images.githubusercontent.com/91092261/223707474-a1b1f3d7-1a05-4eaa-9776-9f1b483d1136.png)

![Image 2](https://user-images.githubusercontent.com/91092261/223707440-9a47610b-0745-445a-965c-23dc0ecca68d.png)
![image 3](https://user-images.githubusercontent.com/91092261/223707462-31a8d95a-1db7-430d-b1b0-72cc503bdc24.png)
![image 4](https://user-images.githubusercontent.com/91092261/223707470-1d23b5aa-444a-4bb3-bdfa-cdfa154aa990.png)

**Comment by JoeRobich** [comment]
A lot has changed with O# project loading since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
