### ISSUE TITLE
Prompt

### ISSUE THREAD

**Issue by KabanovDima** [dotnet/vscode-csharp#5613]
Type: <b>Feature Request</b>

I installed VSC and the C# extension, I did not change the settings. I don't get prompts when writing code. I don’t know what to do, I can’t find the answer in Google. Please help me to solve the problem.

Extension version: 1.25.4
VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

**Comment by JoeRobich** [comment]
@KabanovDima Can you please open your project folder and share the OmniSharp Log from the Output pane?

**Comment by JoeRobich** [comment]
Closing due to lack of response.
