### ISSUE TITLE
Error on removing unused 'using' directives

### ISSUE THREAD

**Issue by mkorsukov** [dotnet/vscode-csharp#5615]
## Environment data
`dotnet --info` output:
```
.NET SDK (reflecting any global.json):
 Version:   6.0.406
 Commit:    2988897946

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.406/

global.json file:
  Not found

Host:
  Version:      6.0.14
  Architecture: x64
  Commit:       2a90daa2cc

.NET SDKs installed:
  3.1.426 [/usr/share/dotnet/sdk]
  6.0.406 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.14 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.14 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

```
VS Code version:
```
Version: 1.76.0
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:25:16.105Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 5.15.0-67-generic
Sandboxed: No
```
C# Extension version:
```
v1.25.4
```

## Steps to reproduce

- Open C# file with unused 'using' directive.
- Open F1 menu > 'OmniSharp: Fix all occurences in solution' > 'CS8019: Unnecessary using directive'.
- See error alert:
![image](https://user-images.githubusercontent.com/21244808/224183010-ed5767e9-25b5-424e-b704-ba19e881daa4.png)

## Expected  behavior
- All unused 'usings' are removed.

## Actual behavior
- An error appears.

**Comment by JoeRobich** [comment]
@mkorsukov There is a timeout for long running fix all actions. It may be better to use dotnet-format for this purpose instead.

**Comment by mkorsukov** [comment]
Thank you, @JoeRobich for response. I didn't know about `dotnet-format` yet, and I will try it!
