### ISSUE TITLE
Unable to Install C# Extension

### ISSUE THREAD

**Issue by PrathameshAnilMore** [dotnet/vscode-csharp#5627]
Type: <b>Bug</b>

 Path: /Users/prathameshmore/.vscode/extensions/ms-dotnettools.csharp-1.25.4-darwin-arm64/.omnisharp/1.39.6-beta.4-net6.0/OmniSharp.dll
    PID: 3800

[STDERR] Unhandled exception. 
[STDERR] System.BadImageFormatException: An attempt was made to load a program with an incorrect format.
 (0x8007000B)

Getting above error 
I am unable to find the "OmniSharp.dll" file on above location 

Extension version: 1.25.4
VS Code version: Code 1.74.3 (Universal) (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T17:07:18.579Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 197f45ca-0655-44e6-9ffe-62d56c2fa0bc|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
pythonb192:30669360
funwalk2cf:30682975
pythonms35cf:30686773

```

</details>

**Comment by hugoantunes** [comment]
```
Starting OmniSharp server at 23/03/2023, 13:33:50
    Target: .../unity/delivery_car/delivery_car.sln

OmniSharp server started with .NET 7.0.202
.
    Path: .../.vscode/extensions/ms-dotnettools.csharp-1.25.4-darwin-x64/.omnisharp/1.39.4-net6.0/OmniSharp.dll
    PID: 14534

[STDERR] Unhandled exception. System.BadImageFormatException: An attempt was made to load a program with an incorrect format.
 (0x8007000B)

[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
```

I got the same error

**Comment by Jgfrausing** [comment]
I have the same issue on windows 11

**Comment by JoeRobich** [comment]
@PrathameshAnilMore I see you have the Universal build of VS Code installed. For me, those builds are run under Rosetta as x64. Could you [try installing](https://code.visualstudio.com/Download) the Apple Silicon build of VS Code instead? You will also need to be sure you have the Apple Silicon build of the dotnet SDK installed.

@hugoantunes Are you also running on Apple Silicon?

@Jgfrausing Most likely the path to the 32-bit dotnet SDK is on your path before the 64-bit. Are you running on an ARM device or Intel?

**Comment by JoeRobich** [comment]
Closing due to lack of response.
