### ISSUE TITLE
Roslyn analyzer CompilationEndAction action is never called in VS Code

### ISSUE THREAD

**Issue by allisterb** [dotnet/vscode-csharp#5634]
I wrote an analyzer that uses a compilation end action. While it works fine in Visual Studio, the end action never seems to get called in Visual Studio Code even with solution-wide analysis enabled.

```
public override void Initialize(AnalysisContext context)
{
    ...
    context.RegisterCompilationStartAction(ctx =>
    {
        ...
       // MyAction never gets called 
       ctx.RegisterCompilationEndAction(cctx => MyAction(cctx.Compilation));
```

I used the following components in VS 2019 to build the analyzer:

* Microsoft.CodeAnalysis.CSharp 3.11 (NuGet)
* Latest MSBuild for VS 2019.

Edit: I initially had filed an issue in the Roslyn repo: dotnet/roslyn#67294 since this also appears to happen with JetBrains Rider but they believe this is an IDE-specific issue since all they do is provide the APIs and it's up to the particular IDE or environment to implement calling the relevant actions. 
## Environment data
**VSCode version**: 1.76.2
**C# Extension**: 1.25.4

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.416 [C:\Program Files\dotnet\sdk]
  5.0.414 [C:\Program Files\dotnet\sdk]
  7.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|better-cpp-syntax|jeff-hykin|1.17.2|
|cpptools-themes|ms-vscode|2.0.0|
|csharp|ms-dotnettools|1.25.4|
|dotnet-interactive-vscode|ms-dotnettools|1.0.4165020|
|go|golang|0.38.0|
|Ionide-fsharp|Ionide|7.5.1|
|isort|ms-python|2022.8.0|
|jupyter|ms-toolsai|2023.2.1200692131|
|jupyter-keymap|ms-toolsai|1.1.0|
|jupyter-renderers|ms-toolsai|1.0.15|
|python|ms-python|2023.4.1|
|remote-explorer|ms-vscode|0.2.0|
|remote-ssh|ms-vscode-remote|0.98.0|
|remote-ssh-edit|ms-vscode-remote|0.84.0|
|remote-wsl|ms-vscode-remote|0.76.1|
|solidity|JuanBlanco|0.0.149|
|truffle-vscode|trufflesuite-csi|2.7.1|
|vsc-gsql-extension|DavidBakerEffendi|0.0.2|
|vscode-jupyter-cell-tags|ms-toolsai|0.1.6|
|vscode-jupyter-slideshow|ms-toolsai|0.1.5|
|vscode-pylance|ms-python|2023.3.20|;

</details>

## OmniSharp log
I have console logging enabled in my analyzer. The `|INFO|ROSLYN|` and `|DEBUG|ROSLYN|` entries are from my analyzer. The analyzer logs `Compilation start` in `RegisterCompilationStartAction` and it should log `Compilation end.` when the action registered in `RegisterCompilationEndAction` executes but this never happens.
```
Starting OmniSharp server at 3/15/2023, 10:50:59 PM
    Target: c:\Projects\Stratis.DevEx\tests\testprojects\Stratis.DevEx.TestProjects.sln

OmniSharp server started with .NET 7.0.100
.
    Path: c:\Users\Allister\.vscode\extensions\ms-dotnettools.csharp-1.25.4-win32-x64\.omnisharp\1.39.4-net6.0\OmniSharp.dll
    PID: 25888

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 10.0.19044.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: .NET Core SDK 7.0.100 17.4.0 - "C:\Program Files\dotnet\sdk\7.0.100\"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: .NET Core SDK 7.0.100 17.4.0 - "C:\Program Files\dotnet\sdk\7.0.100\"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Projects\Stratis.DevEx\tests\testprojects'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Did not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in 'c:\Projects\Stratis.DevEx\tests\testprojects\Stratis.DevEx.TestProjects.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for 'c:\Projects\Stratis.DevEx\tests\testprojects\Stratis.CodeAnalysis.Cs.GuiTestProject1\Stratis.CodeAnalysis.Cs.GuiTestProject1.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Projects\Stratis.DevEx\tests\testprojects'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Did not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Projects\Stratis.DevEx\tests\testprojects' on host 22564.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: c:\Projects\Stratis.DevEx\tests\testprojects\Stratis.CodeAnalysis.Cs.GuiTestProject1\Stratis.CodeAnalysis.Cs.GuiTestProject1.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file 'c:\Projects\Stratis.DevEx\tests\testprojects\Stratis.CodeAnalysis.Cs.GuiTestProject1\Stratis.CodeAnalysis.Cs.GuiTestProject1.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project 'c:\Projects\Stratis.DevEx\tests\testprojects\Stratis.CodeAnalysis.Cs.GuiTestProject1\Stratis.CodeAnalysis.Cs.GuiTestProject1.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Stratis.CodeAnalysis.Cs.GuiTestProject1
[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
        Solution initialized -> queue all documents for code analysis. Initial document count: 3.
[INFO] Initialize called on thread id 14.
2023-03-15 22:51:10.5154|INFO|ROSLYN|Stratis.CodeAnalysis.Cs initialized from entry assembly OmniSharp, Version=1.39.0.0, Culture=neutral, PublicKeyToken=7e5bf7b3b470b509 with log file C:\Users\Allister\AppData\Roaming\StratisDev\Stratis.CodeAnalysis.Cs.4205.log...
2023-03-15 22:51:10.5464|INFO|ROSLYN|Loading existing global configuration file...
2023-03-15 22:51:10.5635|INFO|ROSLYN|Debug mode enabled.
2023-03-15 22:51:10.5635|INFO|ROSLYN|Loaded 1 section(s) with 2 value(s) from global configuration at C:\Users\Allister\AppData\Roaming\StratisDev\Stratis.CodeAnalysis.Cs.cfg.
2023-03-15 22:51:10.5635|INFO|ROSLYN|5 existing log file(s) found.
2023-03-15 22:51:10.5635|INFO|ROSLYN|Initialize called on thread id 8.
2023-03-15 22:51:10.5635|INFO|ROSLYN|Runtime already initialized.
2023-03-15 22:51:10.5635|INFO|ROSLYN|Initialize called on thread id 6.
2023-03-15 22:51:10.5635|INFO|ROSLYN|Runtime already initialized.
2023-03-15 22:51:10.5835|DEBUG|ROSLYN|Compilation start...
2023-03-15 22:51:10.5835|DEBUG|ROSLYN|Compilation start...
2023-03-15 22:51:10.5835|DEBUG|ROSLYN|Compilation start...
2023-03-15 22:51:10.5835|INFO|ROSLYN|Loading analyzer configuration from c:\Projects\Stratis.DevEx\tests\testprojects\Stratis.CodeAnalysis.Cs.GuiTestProject1\stratisdev.cfg...
2023-03-15 22:51:10.5835|INFO|ROSLYN|Loading analyzer configuration from c:\Projects\Stratis.DevEx\tests\testprojects\Stratis.CodeAnalysis.Cs.GuiTestProject1\stratisdev.cfg...
2023-03-15 22:51:10.5835|INFO|ROSLYN|Loading analyzer configuration from c:\Projects\Stratis.DevEx\tests\testprojects\Stratis.CodeAnalysis.Cs.GuiTestProject1\stratisdev.cfg...
2023-03-15 22:51:10.5835|INFO|ROSLYN|GUI enabled for compilation, registering action to send compilation message...
2023-03-15 22:51:10.5835|INFO|ROSLYN|GUI enabled for compilation, registering action to send compilation message...
2023-03-15 22:51:10.5835|INFO|ROSLYN|GUI enabled for compilation, registering action to send compilation message...
2023-03-15 22:51:10.8526|DEBUG|ROSLYN|Using namespace Stratis.SmartContracts at c:\Projects\Stratis.DevEx\tests\testprojects\Stratis.CodeAnalysis.Cs.GuiTestProject1\Test.cs: (0,6)-(0,28).
2023-03-15 22:51:10.9158|DEBUG|ROSLYN|Class Test with attributes  declared at c:\Projects\Stratis.DevEx\tests\testprojects\Stratis.CodeAnalysis.Cs.GuiTestProject1\Test.cs: (4,4)-(15,5).
2023-03-15 22:51:10.9158|DEBUG|ROSLYN|Class Test declared at c:\Projects\Stratis.DevEx\tests\testprojects\Stratis.CodeAnalysis.Cs.GuiTestProject1\Test.cs: (4,4)-(15,5).
2023-03-15 22:51:10.9358|DEBUG|ROSLYN|Constructor for type Test declared at c:\Projects\Stratis.DevEx\tests\testprojects\Stratis.CodeAnalysis.Cs.GuiTestProject1\Test.cs: (7,8)-(14,9).
2023-03-15 22:51:10.9973|DEBUG|ROSLYN|Variable b of type byte[] declared at c:\Projects\Stratis.DevEx\tests\testprojects\Stratis.CodeAnalysis.Cs.GuiTestProject1\Test.cs: (11,19)-(11,26). Base type: System.Array. Enum type: False. User struct: False. Primitive type: False., Array type: True. Element type: byte.
2023-03-15 22:51:11.0003|DEBUG|ROSLYN|Method invocation Stratis.SmartContracts.SmartContract.SmartContract(Stratis.SmartContracts.ISmartContractState) at c:\Projects\Stratis.DevEx\tests\testprojects\Stratis.CodeAnalysis.Cs.GuiTestProject1\Test.cs: (8,12)-(8,25)
```

## Steps to reproduce

* Ensure the "Analyze Open Documents Only" OmniSharp setting is off.
* Open a .NET project with a omnisharp.json that enables Roslyn analyzers and uses a Roslyn analyzer that registers a compilation end action. 
* Ensure compilation end action for analyzer runs under Visual Studio.

## Expected  behavior
Compilation end action should run in VS Code OmniSharp.

## Actual behavior
Compilation end action never runs in VS Code OmniSharp.

**Comment by mavasani** [comment]
@dibarbet I confirmed that this still repros with the latest C# extension even after enabling full solution analysis. There seem to be few issues here:

1. The below code skips computing workspace diagnostics for open documents: https://github.com/dotnet/roslyn/blob/f5b6c715a742c56b7cc672e47385508fb4df98cc/src/Features/LanguageServer/Protocol/Handler/Diagnostics/WorkspacePullDiagnosticHandler.cs#L122-L128
This means any non-local diagnostics, such as compilation end diagnostics, are never reported for open documents.

2.  The below code marks diagnostics from DocumentDiagnosticHandler as superseding the ones froom WorkspacePullDiagnosticHandler: https://github.com/dotnet/roslyn/blob/f5b6c715a742c56b7cc672e47385508fb4df98cc/src/Features/LanguageServer/Protocol/Handler/Diagnostics/DocumentPullDiagnosticHandler.cs#L43-L47

3. I tried to fix this with below changes locally:
   1. Do not skip open documents in `WorkspacePullDiagnosticsHandler` in `ShouldSkipDocument` method pointed in 1. above
   2. Remove the `Supersedes` property setting in `DocumentPullDiagnosticHandler`
   3. Additionally, also mark the diagnostics from `WorkspacePullDiagnosticHandler` with `Supersedes` property set to `DocumentDiagnosticIdentifier`
Now the compilation end diagnostics do get computed and reported for open documents by WorkspacePullDiagnosticsHandler, but they still do not seem to be reported in VSCode (both in Problems window, and squiggles in the editor). So, something else is filtering them out - I am presuming this is some caching at Editor layer that is causing this. @dibarbet I am not familiar with the LSP contracts here and Editor assumptions/caching logic to diagnose this further. Does the information provided above strike something to you about the possible causes for this?

**Comment by dibarbet** [comment]
@mavasani I think there are two problems here
1.  Workspace pull diagnostics generally is not supposed to report diagnostics for open documents.  You could be hitting one of the conditions listed here causing the document diagnostics to always win - https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_diagnostic
2.  Even if you get the workspace diagnostics to successfully report for open documents, remember that a diagnostic report for a single URI is all or nothing - not additive.  So the workspace diagnostics would replace the entire document diagnostics.

I think the only way that this is going to work is for the document pull diagnostics to report these diagnostics.  However I understand that could be slow...

**Comment by mavasani** [comment]
> I think the only way that this is going to work is for the document pull diagnostics to report these diagnostics. However I understand that could be slow...

Yes, we definitely do not want to go that route, that can make the squiggles and problems window refresh for active document to become extremely slow. I see couple of options here:

1. Call it out as a known limitation that compilation end diagnostics will not show up during background analysis, even with FSA enabled. User is expected to run an explicit build command to see these diagnostics in the problems window, and once fixed would need to rerun the build to see them cleared. They will be truly build-only diagnostics in every sense.
2. Create a new diagnostic source for reporting non-local live diagnostics. We are already going to need 2 sources - build-only and live for #5728. This will be a third source for non-local live diagnostics, and I presume it would be okay for refresh of this source to be slow, as the live source for open documents will still be refreshing majority of diagnostics pretty fast.

I am fine with either stance here.

**Comment by dibarbet** [comment]
@mavasani 
> Create a new diagnostic source for reporting non-local live diagnostics.

I actually really like this idea - and it should actually be possible to do it entirely server side in LSP.  We'd want to confirm with the vscode team, but I *think* that the identifier here - https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#diagnosticOptions is the diagnostic source.  I'm pretty sure with dynamic registration we can register two sources from the server (through https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#client_registerCapability). 

Then when the client calls back into us, it will tell us which source is being used https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#documentDiagnosticParams

So we'd have a regular one and then compilation end for document.  We could consider improving it even more to have a compiler source, analyzer source, and compilation end source.

**Comment by mavasani** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/69541
