### ISSUE TITLE
Omnisharp fails to find components on macOS Ventura (especially when there are multiple VSCode instances)

### ISSUE THREAD

**Issue by AcrylicShrimp** [dotnet/vscode-csharp#5637]
## Issue Description ##

Omnisharp fails to find components on macOS Ventura. It asks me to install mono, or open settings. My project is using Unity, so I don't have any choice but to set `useModernNet` to `false`. The weird thing is that it not happens after installing mono and dotnet. But, if I restart VSCode, it happens. I looked the below logs, and I'm 200% sure that `mono`, `dotnet`, and `msbuild` is properly installed, and it works definitely.

```
which mono

/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono
```

```
mono --version

Mono JIT compiler version 6.12.0.182 (2020-02/6051b710727 Tue Jun 14 15:01:21 EDT 2022)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           
        SIGSEGV:       altstack
        Notification:  kqueue
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        Interpreter:   yes
        LLVM:          yes(610)
        Suspend:       hybrid
        GC:            sgen (concurrent by default)
```

```
which dotnet

/opt/homebrew/bin/dotnet
```

```
dotnet --version

7.0.202
```

```
which msbuild

/Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild
```

```
echo $PATH

/opt/homebrew/opt/postgresql@15/bin /Library/Frameworks/Mono.framework/Versions/Current/Commands /Applications/Araxis Merge.app/Contents/Utilities /Applications/Araxis Merge.app/Contents /Users/ashrimp/Library/Android/sdk/emulator /Users/ashrimp/go/bin /Users/ashrimp/.spoof-dpi/bin /opt/homebrew/opt/openjdk/bin /Users/ashrimp/.cargo/bin /opt/homebrew/bin /usr/local/bin /System/Cryptexes/App/usr/bin /usr/bin /bin /usr/sbin /sbin /Library/Apple/usr/bin /usr/local/share/dotnet ~/.dotnet/tools
```

I have no idea why it is not working.

## Steps to Reproduce ##

1. Install VSCode
1. Install C# extension
1. Turn off `useModernNet`.
1. Open any C# project; this will make VSCode to reload.
1. Omnisharp will be started automatically. Therefore, Omnisharp would ask you to install components.
1. Install newest dotnet and mono components.
1. Restart VSCode, and open any C# project.
1. Now it seems to work; but it isn't. Uninstall C# extension from VSCode.
1. Install C# extension again, and open any C# project.
1. At this moment, Omnisharp would fail to find components, and ask you to install components, even if we already installed them.

## Expected Behavior ##

Whatever we do, Omnisharp must find components properly, if installed.

## Actual Behavior ##

It fails to find components at random moment(maybe after re-installed C# extension). After that, it never finds again.

### OmniSharp log ###
<details>OmniSharp failed to start because of missing requirements.</details>

### C# log ###
<details>EMPTY</details>

## Environment information ##

**VSCode version**: 1.76.2
**C# Extension**: 1.25.4

<details><summary>Mono Information</summary>
        There is a problem with running OmniSharp on mono: Error: Unable to find Mono. Ensure that Mono's '/bin' folder is added to your environment's PATH variable.</details>
<details><summary>Dotnet Information</summary>
Command failed: dotnet --version
/bin/sh: dotnet: command not found
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|cmake-tools|ms-vscode|1.13.45|
|copilot|GitHub|1.78.9758|
|csharp|ms-dotnettools|1.25.4|
|EditorConfig|EditorConfig|0.16.4|
|gitlens|eamodio|13.4.0|
|gruvbox|jdinhlife|1.8.0|
|isort|ms-python|2022.8.0|
|npm-intellisense|christian-kohler|1.4.4|
|path-intellisense|christian-kohler|2.8.4|
|prettier-vscode|esbenp|9.10.4|
|python|ms-python|2023.4.1|
|rainglow|daylerees|1.5.2|
|rust-analyzer|rust-lang|0.3.1443|
|svelte-vscode|svelte|107.2.5|
|tauri-vscode|tauri-apps|0.2.6|
|vera|TTOOWA|0.8.0|
|vs-sequential-number|neptunedesign|1.1.0|
|vscode-eslint|dbaeumer|2.4.0|
|vscode-github-actions|me-dutour-mathieu|3.0.1|
|vscode-icons|vscode-icons-team|12.2.0|
|vscode-lldb|vadimcn|1.9.0|
|vscode-pylance|ms-python|2023.3.20|
|vscode-todo-highlight|jgclark|2.0.4|
|vscode-yaml|redhat|1.12.2|
|vscode-zig|ziglang|0.3.1|
|wgsl|PolyMeilex|0.1.14|;

</details>

**Comment by Werasilz** [comment]
same problem on macOS Ventura

**Comment by AcrylicShrimp** [comment]
Ok, I found a way to bypass this error. Open JSON settings in VSCode, fill below.

> **NOTE**: Exact path may differ, find them yourself. e.g. `which dotnet`

```json
"omnisharp.dotnetPath": "/usr/local/share/dotnet",
  "omnisharp.monoPath": "/Library/Frameworks/Mono.framework/Versions/Current/bin",
  "omnisharp.sdkPath": "/usr/local/share/dotnet/sdk/7.0.202",
```

After done, quite VSCode completely (It is required for some reason when I tested), and restart VSCode. And, it will work again.

**Comment by Werasilz** [comment]
it's working, thank you!

**Comment by AcrylicShrimp** [comment]
Wow, I'm surprised that this problem arose again for me. What should I do next...?

**Comment by AcrylicShrimp** [comment]
Umm, it's very weird. The problem has gone right after restarting VSCode completely.

**Comment by AcrylicShrimp** [comment]
Ah, I think I found the exact cause of this issue. This problem happens when I opended a **second** instance of VSCode. Doesn't this extension support multi-instance of VSCode?

**Comment by bardackx** [comment]
having the same problem on version 1.25.4, downgrading to 1.25.0 fixed the issue

**Comment by thomasbergersen** [comment]
Fixed in vscode  v1.77.1

**Comment by AcrylicShrimp** [comment]
> Fixed in vscode v1.77.1

No, I think it's not fixed in `v1.77.1`, it still occurs.

**Comment by thomasbergersen** [comment]
<img width="879" alt="image" src="https://user-images.githubusercontent.com/3325006/231243631-401d4fe9-c2fa-4173-9586-45b1ea673d51.png">
This is my setup. For me, version 1.77.1 on macOS 13.3.1 has already fixed this issue.

**Comment by JoeRobich** [comment]
A lot has changed with O# and mono since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues.
