### ISSUE TITLE
The plugin did not ignore '*/' in quotation marks

### ISSUE THREAD

**Issue by hidiyou** [dotnet/vscode-csharp#5647]
## Environment data
`dotnet --info` output:

```
.NET SDK (反映任何 global.json):
 Version:   6.0.113
 Commit:    4a23b50f97

运行时环境:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/lib/dotnet/sdk/6.0.113/

global.json file:
  Not found

Host:
  Version:      6.0.13
  Architecture: x64
  Commit:       1af80ba017

.NET SDKs installed:
  6.0.113 [/usr/lib/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.13 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.13 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

```

VS Code version:

```
版本: 1.77.0
提交: 7f329fe6c66b0f86ae1574c2911b681ad5a45d63
日期: 2023-03-29T10:05:35.165Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 5.19.0-38-generic
沙盒化: Yes
```

C# Extension version:

```
名称: C#
ID: ms-dotnettools.csharp
说明: C# for Visual Studio Code (powered by OmniSharp).
版本: 1.25.4
发布者: Microsoft
VS Marketplace 链接: https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp
```

## Steps to reproduce

1. Create a new console project with `dotnet new console`

2. Input following code

   ```C#
   class a
   {
       public static void Main()
       {
           /*
           Console.WriteLine("*/");
           */
       }
   }
   ```

3. See error

## Expected  behavior
In

```C#
/*
        Console.WriteLine("*/");
*/
```

The `/*` in the first line should be paired with the `*/`in the third line

## Actual behavior

It is paired with the `*/` in the second line quotation mark

You can clearly see this error in the following image:

![image](https://user-images.githubusercontent.com/98258846/230066791-ff7b8613-aa73-4100-85d3-b3cc6fcaed48.png)

## Additional context
When I use `dotnet run` to compile this code, its behavior is normal.

```bash
 $ dotnet run
*/
```
![image](https://user-images.githubusercontent.com/98258846/230066955-7211c796-d212-48ac-b547-3c9dcfe2dcc8.png)

**Comment by JoeRobich** [comment]
The C# extension ships with semantic highlighting support which correctly highlights this code.
