### ISSUE TITLE
Please implement refactor rename record parameters in .NET 7 in both ways!

### ISSUE THREAD

**Issue by maxron84** [dotnet/vscode-csharp#5650]
Type: <b>Bug</b>

Visual Studio Code with C# Extension using .NET 7 C# 11

When trying to refactor rename (standard keybind F2) a parameter for a record, it only works from outside at the consuming variables, not the definition directly (the record's defined parameter name).
You have to do it manually from there. This has high potential to cause massive frustrations to many users working with C# especially when maintaining complex solutions! Please fix that! Thank you!

Extension version: 1.25.4
VS Code version: Code 1.77.1 (b7886d7461186a5eac768481578c1d7ca80e2d21, 2023-04-04T23:21:11.906Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

**Comment by JoeRobich** [comment]
This issue will be resolved when https://github.com/dotnet/roslyn/issues/44560 is fixed.

**Comment by JoeRobich** [comment]
Closing as resolved.
