### ISSUE TITLE
no formatea y fastidia

### ISSUE THREAD

**Issue by wjvelasquez** [dotnet/vscode-csharp#5658]
en el poco uso que le doy a Code. la extencion de c# me tiene super molesto.
A cada rato me da algun mensaje del tipo: "Request textDocument/formatting failed."

solucionen que es una verdadera molestia

**Comment by JoeRobich** [comment]
A lot has changed with O# since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
