### ISSUE TITLE
100% cpu usage when idle

### ISSUE THREAD

**Issue by pederlh** [dotnet/vscode-csharp#5676]
Type: <b>Bug</b>

After running any dotnet command (like building a project, running tests), the cpu usage of dotnet in Activity finder is still very high, draining the battery when not connected to AC power.

Extension version: 1.25.7
VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:15:29.774Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.33GB free)|
|Process Argv|--crash-reporter-id d751481c-ae1c-4e04-98c2-ceff9ae10dd9|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyonecf:30548226
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
0bg3d529:30706074
7ij38806:30736111
pythonfmttext:30731395
pythoncmvfstrcf:30731970
fixshowwlkth:30730052
pythongtdpathcf:30731979

```

</details>

**Comment by JoeRobich** [comment]
@pederlh Can you share a screenshot of the VS Code process explorer (Help > Open Process Explorer)? 

> After running any dotnet command (like building a project, running tests)

Are you running these from the terminal or as VS Code commands?

**Comment by pederlh** [comment]
Sorry for the late reply. It's been hard to pinpoint exactly when the issue arrises, but essentially it seems some processes are not killed correctly. I've attached some screenshots from both the Activity monitor and the VS Code process explorer below. 

![image](https://github.com/OmniSharp/omnisharp-vscode/assets/36080334/cac21f74-3760-4431-b1c5-4aa0b04289a3)

![image](https://github.com/OmniSharp/omnisharp-vscode/assets/36080334/61f384d8-0ac5-4fc7-87c8-01662ea88b88)

**Comment by vaind** [comment]
I'm having the same issue consistently, while working on https://github.com/getsentry/sentry-dotnet

**Comment by JoeRobich** [comment]
A lot has changed with O# since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
