### ISSUE TITLE
Unable to run C#, Julia and Rust file

### ISSUE THREAD

**Issue by AGoh2019** [dotnet/vscode-csharp#5688]
Type: <b>Bug</b>

On startup, C# run and debug doesn't work
Run button on top right corner not showing
Ran w/o debugging: Variable ${workspaceRoot} can not be resolved. Please open folder. 
Can't start client Java Language Server

Similar issues encountered with Julia and rust-analyzer.  Except that "Can't start client Java Language Server" doesn't show.

Please fix the issue, I am tired of filing reports.  F# also installed on VS Code.

In addition, I have VS IDE installed with support for C++, C# and F#.

Extension version: 1.25.7
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.77GB (9.12GB free)|
|Process Argv|--crash-reporter-id d28106b3-cd04-490a-b194-f819821f7d80|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsccsb:30705552
pythonms35:30701012
pythonfmttext:30731395
pythoncmv:30739700
fixshowwlkth:30730052
showsbindicator:30730056
pythongtdpathcf:30739705

```

</details>

**Comment by JoeRobich** [comment]
@AGoh2019 Can you please open your project folder again in VS Code and share the OmniSharp Log from the output pane?

**Comment by AGoh2019** [comment]
Julia and Rust running.  Still can't figure out what's wrong with C# and F# in VS Code.  Can we build single file programs without creating a project for it?

**Comment by JoeRobich** [comment]
The C# extension supports C# script files (.csx) which can be run which can be run after installing the dotnet-script tool. See https://github.com/dotnet-script/dotnet-script for more information.

**Comment by JoeRobich** [comment]
Closing as answered.
