### ISSUE TITLE
Omnisharp error when install in vscode 32 bit

### ISSUE THREAD

**Issue by NCLnclNCL** [dotnet/vscode-csharp#5697]
I using window 64 bit, if i using vs32 bit it will install 32 bit omnisharp extention  but it cannot running with errors, if i using 64 bit omnisharp extention then it can work

**Comment by JoeRobich** [comment]
@NCLnclNCL As you said, the 32-bit VS Code will install the 32-bit version of OmniSharp. In this setup you will need to use a matching 32-bit dotnet SDK. If you have a mix of 64-bit and 32-bit dotnet SDKs installed, you can set 'omnisharp.sdkPath' to the 32-bit SDK you wish to use.

**Comment by JoeRobich** [comment]
Closing as answered.
