### ISSUE TITLE
[STDERR] Unhandled exception. System.BadImageFormatException: An attempt was made to load a program with an incorrect format.  (0x8007000B)

### ISSUE THREAD

**Issue by codewithfan** [dotnet/vscode-csharp#5700]
Currently experiencing an issue trying to run the debug program.
![Screenshot 2023-06-02 at 7 17 22 PM](https://github.com/OmniSharp/omnisharp-vscode/assets/85418632/ec093862-0ad3-41f9-959e-b045a0e7ff01)

But keep receiving this:
![Screenshot 2023-06-02 at 7 17 56 PM](https://github.com/OmniSharp/omnisharp-vscode/assets/85418632/2ea1eeb4-ecf3-45de-9ba0-5375f39df3fd)

I've updated my .NET, VS Code, and C# extension. 

## Environment data
.NET SDK:
 Version:   7.0.302
 Commit:    990cf98a27

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.3
 OS Platform: Darwin
 RID:         osx.13-x64
 Base Path:   /usr/local/share/dotnet/x64/sdk/7.0.302/

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  7.0.302 [/usr/local/share/dotnet/x64/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.5 [/usr/local/share/dotnet/x64/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/local/share/dotnet/x64/shared/Microsoft.NETCore.App]

Other architectures found:
  arm64 [/usr/local/share/dotnet]
    registered at [/etc/dotnet/install_location_arm64]

Environment variables:
  Not set

global.json file:
  Not found

## OmniSharp log

Starting OmniSharp server at 6/2/2023, 7:09:10 PM
    Target: /Users/fan/HelloDotNet

OmniSharp server started with .NET 7.0.302
.
    Path: /Users/fan/.vscode/extensions/ms-dotnettools.csharp-1.25.8-darwin-arm64/.omnisharp/1.39.6-net6.0/OmniSharp.dll
    PID: 49568

[STDERR] Unhandled exception. 
[STDERR] System.BadImageFormatException: An attempt was made to load a program with an incorrect format.
 (0x8007000B)

[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).

## Steps to reproduce

1. Go to 'Output'
2. See error

## Expected  behavior
OmniSharp loads properly.

## Actual behavior

[STDERR] Unhandled exception. 
[STDERR] System.BadImageFormatException: An attempt was made to load a program with an incorrect format.
 (0x8007000B)

## Additional context
N/A

**Comment by JoeRobich** [comment]
@codewithfan The issue is the arm64 build of the extension will not work with a x64 SDK. Try uninstalling and installing a arm64 build instead.
