### ISSUE TITLE
Coalesce Themes

### ISSUE THREAD

**Issue by 333fred** [dotnet/vscode-csharp#5710]
Right now there are a bunch of different themes, based on the VS colors, but with slight differences. In the current version, we have:

* Dark+
* Dark Modern
* Dark (Visual Studio)
* Visual Studio 2019 Dark

The last one has some semantic themeing info the previous 3 do not (such as coloring classes/structs/interfaces differently to each other). We should deduplicate these where can.

**Comment by aradalvand** [comment]
Why not just remove "Visual Studio 2019 Dark" and add proper semantic highlighting to the new "Dark Modern" theme?

The main thing the VS Code C# tooling has always lacked is proper syntax highlighting comparable to Visual Studio. This is now a good time to address this.

**Comment by just-ero** [comment]
Another coloring issue I'd like to point out is properties and fields versus locals. In the `Visual Studio 2019 Dark` theme, properties and fields are colored white, locals are light blue. In the other themes, all 3 are the same color.

**Comment by arkalyanms** [comment]
Closing as dup of https://github.com/dotnet/vscode-csharp/issues/5763

**Comment by just-ero** [comment]
#5763 came later and is much less complete in terms of information. How was this closed in favor of that?
