### ISSUE TITLE
New LSP does not respect VS Code language settings.

### ISSUE THREAD

**Issue by StringEpsilon** [dotnet/vscode-csharp#5716]
## Environment data
`dotnet --info` output:
```
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\
```

VS Code version: `1.78.2`
C# Extension version: `v2.0.206`

## OmniSharp log
Not applicable.

## Steps to reproduce

1. Set your operating system language to German (or any other non-english language)
2. Set your VS Code language to english.
3. Open any C# file.
4. Observe how refactoring options and lenses provided by the new LSP are using the system language instead of vs code language.

## Expected  behavior
The LSP / Extension should use the language configured in VS Code.

## Actual behavior
![grafik](https://github.com/dotnet/vscode-csharp/assets/5951778/7eb4f307-f3d6-46ec-9eaf-e0485f9d4d5b)

![grafik](https://github.com/dotnet/vscode-csharp/assets/5951778/a8e06752-50ff-43e4-82f2-9a2cddb47321)

**Comment by Igorgro** [comment]
It's interesting that the omnisharp had the same problem in some cases: #5217. Maybe it is caused by roslyn?

**Comment by JoannaFalkowska** [comment]
This is still a problem.

It seems to be alleviated after using [this specific workaround for Omnisharp](https://github.com/OmniSharp/omnisharp-roslyn/issues/2661), **but only partially**.

before:
![Image](https://github.com/user-attachments/assets/552be1ef-68b4-4c9e-9847-4a9a69e62c0e)
after:
![Image](https://github.com/user-attachments/assets/359503d6-1caf-4003-adac-7ba5b63864ac)
