### ISSUE TITLE
[O# Parity] Run and debug tests in context

### ISSUE THREAD

**Issue by dibarbet** [dotnet/vscode-csharp#5719]
O# supports a couple of commands to run and debug tests using vstest console.
1.  In the right click menu, run and debug tests in context
2.  In codelens on test methods - links to run and debug tests

We need to add support for these commands in the preview version of the C# extension for full parity.

**Comment by agocke** [comment]
This one seems high priority -- without this feature I don't think I can run tests at all without the dev kit.

**Comment by dibarbet** [comment]
> This one seems high priority -- without this feature I don't think I can run tests at all without the dev kit.

It should be one of the first features coming as soon as we finish getting the infrastructure setup in this new repo.  It's a GA blocker.

**Comment by dibarbet** [comment]
Remaining TODO items:
1.  Allow custom .runsettings file - https://learn.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2022
2.  Support `unitTestDebuggingOptions` - https://github.com/dotnet/vscode-csharp/blob/main/package.json#L922

**Comment by dibarbet** [comment]
`csharp.unitTestDebuggingOptions` support here - https://github.com/dotnet/vscode-csharp/pull/6110
