### ISSUE TITLE
[O# Parity] Project loading support for projects running on Mono

### ISSUE THREAD

**Issue by dibarbet** [dotnet/vscode-csharp#5721]
For the C# project loader, we need to run our design time builds out of proc using the project specific SDK.  This will avoid errors trying to load various project types in the .NET 7 runtime.

With out of proc design time builds, we should also be able to load mono / legacy csproj (similar to O#'s useModernDotnet flag).

Note that this is only planned to be supported in the C# extension project loader.

**Comment by jasonmalinowski** [comment]
Didn't quite mean to close this yet, but https://github.com/dotnet/roslyn/pull/69616 brings significant improvements here and adds legacy support for .NET Framework projects on Windows. Mac/Linux for stuff running atop Mono should come soon.

**Comment by jasonmalinowski** [comment]
With #70263 being merged in Roslyn, we should now have support for all the MSBuild-based projects that Omnisharp also supported. There's still some non-MSBuild project types to look at, but we should have the same compat across all platforms.
