### ISSUE TITLE
Theme / color coding does not render correctly using LSP / pre release version

### ISSUE THREAD

**Issue by fuzzlebuck** [dotnet/vscode-csharp#5731]
## Issue Description ##

After switching to the new pre release v2.0.206 the color formatting / theming does not appear correctly.

## Steps to Reproduce ##

Open up any example C# unit, switch to the pre release version of the extension and reload the ide.

Note that colors do not appear correctly, most of the color definition is missing, everything looks similar.

Switch between the preview version and the release version to see the tokens with different colors.

It's more subtle on the default themes like 'Dark modern' but much more obvious on other themes like the one I use 'Monokai Pro'

Seems that different tokens / elements are not being identified correctly, so everything looks the same color.

## Expected Behavior ##

Code should appear using the same colors in the current release version.

[How Monokai Pro should look](https://i.imgur.com/BOwf2D2.png)
[How Dark Modern should look](https://i.imgur.com/MzZBzId.png)

## Actual Behavior ##

Colors are not right.

[How Monokai Pro looks with the LSP / pre release extension](https://i.imgur.com/CRtFnQ8.png)
[How Dark Modern looks with the LSP / pre release extension](https://i.imgur.com/QYMFJfZ.png)

## Environment information ##

Have confirmed this on both 1.79.0-insider and 1.78.2

**VSCode version**: 1.79.0-insider
**C# Extension**: 1.25.9

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.105
 Commit:    e1bc5e001c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.105\

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.301 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  5.0.411 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  7.0.100 [C:\Program Files\dotnet\sdk]
  7.0.105 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  arm64 [C:\Program Files\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\arm64\InstallLocation]
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.11.5|
|azure-pipelines|ms-azure-devops|1.208.0|
|Bookmarks|alefragnani|13.3.1|
|clock|angelo-breuer|1.0.1|
|copilot-chat|GitHub|0.2.0|
|copilot-nightly|GitHub|1.88.144|
|csharp|ms-dotnettools|1.25.9|
|delphi-keybindings|alefragnani|9.7.1|
|docomment|k--kato|1.0.0|
|gitlens|eamodio|13.6.0|
|json2csv|khaeransori|0.0.1|
|live-server|ms-vscode|0.4.8|
|material-icon-theme|PKief|4.28.0|
|powershell|ms-vscode|2023.6.0|
|prettier-vscode|esbenp|9.13.0|
|rainbow-csv|mechatroner|3.7.0|
|remote-containers|ms-vscode-remote|0.294.0|
|remote-explorer|ms-vscode|0.4.0|
|remote-server|ms-vscode|1.2.0|
|remote-ssh|ms-vscode-remote|0.102.0|
|remote-ssh-edit|ms-vscode-remote|0.86.0|
|remote-wsl|ms-vscode-remote|0.79.4|
|sass-indented|syler|1.8.26|
|terraform|hashicorp|2.26.1|
|theme-monokai-pro-vscode|monokai|1.2.1|
|vscode-azureappservice|ms-azuretools|0.24.9|
|vscode-azureresourcegroups|ms-azuretools|0.7.5|
|vscode-azurestorage|ms-azuretools|0.15.2|
|vscode-coverage-gutters|ryanluker|2.11.0|
|vscode-docker|ms-azuretools|1.25.1|
|vscode-dotnet-runtime|ms-dotnettools|1.6.0|
|vscode-remote-extensionpack|ms-vscode-remote|0.24.0|
|vscode-versionlens|pflannery|1.5.0|;

</details>

**Comment by dibarbet** [comment]
A couple questions
1.  Does the 'Visual Studio 2019 Dark' theme look any better?
2.  On the `var d = DateTime.Parse(...)` in your screenshot, can you invoke the 'Inspect Editor Tokens and Scope` command and send a screenshot of the box that appears? e.g.
<img width="521" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/5749229/1fa096e0-764c-4e06-98c6-d82a994021b5">
3.  Any changes in the colors if you type in the editor?

**Comment by fuzzlebuck** [comment]
I realised that example project I was showing didn't have a .sln (my bad sorry), once I added the Solution the default theme tidied up a lot!

For the token values below I've used the Visual Studio 2019 Dark theme in both comparisons, and since a lot of the tokens are the same / similar colors it's hard to notice much difference, but on other themes it has quite an impact.

The one you asked for I think looks fine to me since adding the Solution:

[Parse existing](https://i.imgur.com/VDnwUBh.png)
[Parse LSP](https://i.imgur.com/2zdNKtN.png)

Using Monokai Pro, I picked out the main offenders:

[Existing](https://i.imgur.com/yOeND3w.png)
[LSP](https://i.imgur.com/f7sX3SQ.png)

Of which I can only spot two:

[Namespace existing](https://i.imgur.com/qW2EJW6.png)
[Namespace LSP](https://i.imgur.com/b6gbun6.png)

[Parameter existing](https://i.imgur.com/Td6IRMU.png)
[Parameter LSP](https://i.imgur.com/Jeud5T7.png)

You can see on this theme they don't look any different but for other themes they do.

Note I also work in Typescript a fair amount using the Monokai Pro theme and it renders renders correctly, parameters / variables are the correct color in TS as they are in the existing C# extension.

**Comment by fuzzlebuck** [comment]
The latest released versions 2.0.230 and 2.0.238 breaks the formatting which make it unusable for me, I'm stuck on 1.26.0 and unable to use the DevKit until this is resolved.

Themes work in everything else but the newest C#.

**Comment by JoeRobich** [comment]
@dibarbet I think we should remove any of the core LSP tokens types from our list of scopes. https://github.com/dotnet/vscode-csharp/blob/main/package.json#L4739-L4780

**Comment by fuzzlebuck** [comment]
Thanks @JoeRobich that's worked well, I've updated the PR.

**Comment by fuzzlebuck** [comment]
@dibarbet any chance we can get a pre-release build with the fix for this? or maybe there's a build planned soon?

**Comment by dibarbet** [comment]
@fuzzlebuck your PR should be in the latest non-prerelease build
https://github.com/dotnet/vscode-csharp/blob/main/CHANGELOG.md#latest
2.0.376

Let me know if you're seeing it properly

**Comment by fuzzlebuck** [comment]
@dibarbet Not sure how I missed that! 

I've been using an old version for awhile now and just updated, looks so much better and great to be on the new DevKit now :-) thank you. 

Closing.
