### ISSUE TITLE
[O# Parity] Nested code actions including FixAll support for code fixes and refactorings

### ISSUE THREAD

**Issue by mikadumont** [dotnet/vscode-csharp#5735]
C# Dev Kit v0.0.649-alpha
C# v2.0.59-beta.g7eb4b27ce6

VSCode doesn't seem to support FixAll functionality for code fixes and refactorings. I couldn't find a tracking issue for this feature, so filing this issue. Feel free to dupe if there exists one.

**Comment by dibarbet** [comment]
Completed in https://github.com/dotnet/vscode-csharp/pull/6572

**Comment by devantler** [comment]
This is still not working for me. Is there any prerequisites to make it work?

**Comment by dibarbet** [comment]
> This is still not working for me. Is there any prerequisites to make it work?

As long as you have a project loaded, fix all / suppress actions should show alongside applicable code actions in the lightbulb e.g.

![Image](https://github.com/user-attachments/assets/5b7ca323-40ff-414e-8ce0-3b2cfe5ed5b2)

If it isn't working for you, please file a new issue

**Comment by devantler** [comment]
It might be that it is not applicable code. I want to use it to fix all namespaces. Im tired of doing that semi-manually :-)

Will create a new issue, if it is something I have issues with everywhere. Not sure right now :-)
