### ISSUE TITLE
Renaming or deleting an opened C# source file in VSCode does not refresh the Problems window

### ISSUE THREAD

**Issue by mikadumont** [dotnet/vscode-csharp#5739]
Affected Branch:
Affected Build: C# Dev Kit version: v0.0.641-alpha
Affected Product Language:

Steps to reproduce:

See the VS and VSCode gifs below for the expected and actual experience.

Expected behavior (VS):

![image](https://github.com/dotnet/vscode-csharp/assets/46729679/0f739035-371a-4618-877c-4d00cbae7ea2)

Actual behavior (VSCode):

![image](https://github.com/dotnet/vscode-csharp/assets/46729679/542a4f40-cfad-4716-aa05-c1dd51a530a3)

**Comment by CyrusNajmabadi** [comment]
This doesn't repro for me.  After i rename (say "Program.cs" to "Program1.cs") i see:

![image](https://github.com/dotnet/vscode-csharp/assets/4564579/c334fb59-48a1-498a-b569-d7ff169463ad)

Can you supply a more detailed repro showing the issue?
