### ISSUE TITLE
LanguageServer hangs on ungraceful shutdown on Linux/Mac with Devkit installed

### ISSUE THREAD

**Issue by mikadumont** [dotnet/vscode-csharp#5743]
C# Extension installed: v2.0.100-beta.g98603998e1
Dev Kit installed: v0.0.783-alpha

It seems if our language server shuts down to textDocument/didChange throwing an exception, and you have Dev Kit installed, and it's on Linux, we hang during the shutdown process. We hit this await.

But then it doesn't complete from there.

The fact we hang during shutdown means that VS Code doesn't restart us, which isn't great.

**Comment by dibarbet** [comment]
Haven't had any real custom reported for this - closing.
