### ISSUE TITLE
Enable ESLint for vscode-csharp-next

### ISSUE THREAD

**Issue by mikadumont** [dotnet/vscode-csharp#5745]
ESLint would be great to have running in the c# extension repo as it prevents certain classes of bugs from being checked in.  Case in point, with the consistent-return rule, this bug: `All files are in the misc workspace` would never have even been checked in.

However, the repo currently has over 9000 errors from ESLint.  Fixing them all at once isn't do-able and bound to cause merge conflicts when we want to merge back into the public repo.  So we should tackle this after that happens.

**Comment by dibarbet** [comment]
this is essentially done.  there are potentially more rules to enable, but we'll take those 1 at a time
