### ISSUE TITLE
Omnisharp is not showing codelens in razor file

### ISSUE THREAD

**Issue by mikadumont** [dotnet/vscode-csharp#5749]
C# Extension Version: 190
![image](https://github.com/dotnet/vscode-csharp/assets/46729679/bcfbc04e-b772-4c75-b753-c82e9b5666d7)

**Comment by arkalyanms** [comment]
@dibarbet This seems true of the C# extension as well for me (without the omnisharp option enabled)

![image](https://github.com/dotnet/vscode-csharp/assets/60013978/bda457b4-0e2c-4e5b-b613-b31e7703acb5)

**Comment by dibarbet** [comment]
Ah - I'm guessing Razor needs to add an LSP delegation handler to call the new Roslyn codelens endpoint?
cc @davidwengier ?

**Comment by arkalyanms** [comment]
Ok looking back at the codelens being green in @phil-allen-msft's status report, it looks like it was covering the C# codelens. So this may just not have been tested before?

**Comment by davidwengier** [comment]
> new Roslyn codelens endpoint?

New?

Our code lens support is entirely in TypeScript, and we just call the VS Code command on the generated C# buffer: https://github.com/dotnet/vscode-csharp/blob/main/src/razor/src/CodeLens/RazorCodeLensProvider.ts#L67-L69 
We don't have codelens support in our LSP server at the moment at all.

> So this may just not have been tested before?

CodeLens on C# in Razor files definitely used to work. It's working in your screenshot even.

**Comment by arkalyanms** [comment]
Argh, it snuck in between me seeing it realtime and the Ctrl+Shift+S. Just a delay in the C# 2.0, but it does show!

With the omnisharp option enabled, I also see below when I close and reopen the razor file:
[Error - 4:48:39 PM] Request textDocument/foldingRange failed.
  Message: Error writing JSON RPC Message: ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
  Code: -32003 
[object Object]

**Comment by dibarbet** [comment]
Closing this as it appears to be working.
