### ISSUE TITLE
Automatic completion makes it harder to type doc comments

### ISSUE THREAD

**Issue by mikadumont** [dotnet/vscode-csharp#5751]
Affected Branch:
Affected Build: csharp-win32-x64-2.0.33-beta.g4da1a88a0f and csdevkit-win32-x64-0.0.571-alpha
Affected Product Language:

Steps to reproduce:

See the attached Repro.mp4 for a recording.
Open a solution in VS Code
Open a .cs file
Start typing a doc comment like `"/// <summary>..."`
Note that the completion list comes up when you type "<" and "summary" is one of the options.
Try to close the doc comment by typing `"/// </summary>"`
Note that the completion list comes up on "<" again, but does not include "/summary". Instead, "c" is selected and is automatically completed when typing the "/".

**Comment by arkalyanms** [comment]
Moving to Cyrus in Gen's absence.

**Comment by dibarbet** [comment]
No longer reproduces on the latest c# extension - completion after typing the `</` is dismissed.
