### ISSUE TITLE
Open Solution command does not appear after LS restart when switching out of the omnisharp option

### ISSUE THREAD

**Issue by mikadumont** [dotnet/vscode-csharp#5753]
C# Extension Version:
C# Dev Kit Extension Version:

Steps to reproduce:

1) Set omnisharp to true

2) Restart vscode

3) Open a solution and play around with it

4) set omnisharp to false

5) click restart on the toast to restart LS

6) open solution command does not show up post restart

**Comment by arkalyanms** [comment]
This does not repro for me anymore on v2.0.248
