### ISSUE TITLE
C# textmate grammar doesn't support top-level statements

### ISSUE THREAD

**Issue by mikadumont** [dotnet/vscode-csharp#5760]
[C# 9 Top-Level Statements Syntax Coloring Bugs · Issue #203 · dotnet/csharp-tmLanguage (github.com)](https://github.com/dotnet/csharp-tmLanguage/issues/203)

**Comment by JoeRobich** [comment]
Looks like VS Code pulled in the latest C# grammar [a couple weeks back](https://github.com/microsoft/vscode/pull/184151/files#diff-b74b355da4910ff95f4ec3a492a542e4636b20ec72c0edf80dc43c5720a5628b). Installed the latest insiders build and can verify the linked issue is resolved.

<img width="806" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/611219/56c9a123-aafa-4220-8c8c-c6d8ea8b68a4">

**Comment by arkalyanms** [comment]
@sharwell fyi who opened it originally.
