### ISSUE TITLE
Go to definition for non-source symbol shows MAS, not decompilation

### ISSUE THREAD

**Issue by mikadumont** [dotnet/vscode-csharp#5761]
C# Extension Version:
C# Dev Kit Extension Version:

Steps to reproduce:

1. Open OrchardCore, BackgroundTaskScheduler.cs
2. Navigate to definition on CrontabSchedule.Parse (line 41)

In VS this shows a decompilation:
![image](https://github.com/dotnet/vscode-csharp/assets/46729679/4ef917ef-18cb-47e4-b07e-d0081a8e3ccc)

In C# Dev Kit this shows MAS:
![image](https://github.com/dotnet/vscode-csharp/assets/46729679/4a3f4372-b7b4-4cbb-ae88-e9638a73b399)

**Comment by fh-yuxiao-zeng** [comment]
When can we get this fixed? The lack of decomplication is the biggest blocker for us to adopt the new C# extension. It makes it very inefficient to navigate into library code.

**Comment by DaveMcCrady** [comment]
@fh-yuxiao-zeng 
I agree.   As a workaround, to properly navigate to project references, I have to temporarily

1. Disable the "C# Dev Kit" plugin. Which disables dependant plugins (MAUI). (reload required)
2. Right-click "Go To Definition", navigate to the source file as expected, then complete the task.
3. When done, re-enable the "C# Dev Kit" plugin and the dependant plugins. (reload required)

This applies to all Project References

**Comment by Number-3434** [comment]
This would be very useful for me, as I'm using Unity, and I regularly need to figure out how something is implemented.

**Comment by franroa** [comment]
Hi, what is the state of this issue? I think it would improve the developer experience a lot

**Comment by mikadumont** [comment]
Decompilation and Source Link support is in the latest pre-release version 2.45.17.
