### ISSUE TITLE
C# Dev Kit extension page doesn't mention it installs ".NET Install Tool for Extension Authors"

### ISSUE THREAD

**Issue by eric-camplin** [dotnet/vscode-csharp#5762]
## Steps to reproduce

1. Open Visual Studio Code - (fresh install on Windows Sandbox)
2. Install C# Dev Kit Extension
3. View: extensions pane and C# Dev Kit extension details page

## Expected  behavior
C# Dev Kit extension details page indicates that ".NET Install Tool for Extension Authors" is installed with Dev Kit Extension

## Actual behavior
<img width="290" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/12022944/a71fe480-8433-4051-8dc1-6a5b6f44c8ee">

"C#" extension and "IntelliCode for C# Dev Kit" extensions are mentioned - but no mention of ".NET Install Tool for Extension Authors"

**Comment by arkalyanms** [comment]
This can likely move to https://github.com/microsoft/vscode-dotnettools/issues
