### ISSUE TITLE
Modify VSCode theme to follow the VS rules for classification

### ISSUE THREAD

**Issue by mikadumont** [dotnet/vscode-csharp#5763]
Do not assign a specific classification to an item unless it is known to be correct. For example, in the qualified name A.B.C we cannot assign a classification to A (could be type or namespace or member) or B (same) or C (same). 

Here's a section of C# code with all classification other than semantic tokens set to red:
![image](https://github.com/dotnet/vscode-csharp/assets/46729679/3b1adb37-7cad-4081-b83d-7198e7dacff3)

**Comment by arkalyanms** [comment]
Duping to https://github.com/dotnet/vscode-csharp/issues/5710
