### ISSUE TITLE
"No code actions available" after changing to line with visible diagnostic

### ISSUE THREAD

**Issue by mikadumont** [dotnet/vscode-csharp#5767]
Affected Branch:
Affected Build: csdevkit-win32-x64-0.0.527-alpha.vsix
Affected Product Language:

Steps to reproduce:

1. Open a C# document with fixable diagnostics
2. Wait for diagnostics to appear with glyphs showing where the diagnostic is
3. In rapid sequence, click the line containing a diagnostic and press Ctrl+.

Expected behavior:

Light bulb appears with code action to fix the diagnostic.

Actual behavior:

VS Code reports "No code actions available".

**Comment by dibarbet** [comment]
Cannot reproduce on current versions, closing.
