### ISSUE TITLE
C# Dev Kit: Format document sometimes adds two blank lines

### ISSUE THREAD

**Issue by mikadumont** [dotnet/vscode-csharp#5769]
In the following scenario, when the fix formatting will add a second empty line between line 7 and line 9, making the spacing 2 instead of 1.

![image](https://github.com/dotnet/vscode-csharp/assets/46729679/4639b3f3-3326-472d-80e0-5e428c9f56a9)

**Comment by Cosifne** [comment]
Close this as not repro now using the code above.
