### ISSUE TITLE
Fix Return Type does nothing on Mac

### ISSUE THREAD

**Issue by mikadumont** [dotnet/vscode-csharp#5771]
C# Extension Version: v2.0.196-beta.g8eb75efcd6
C# Dev Kit Extension Version: v0.1.65-gc73b002296

Steps to reproduce:

1. Write method with incorrect return type

```
   public static void AddNumber(int num1, int num2)
    {
        return num1 + num2;
    }
```
2. Quick Fix -> Fix Return Type
3. Nothing happens. No error reported in the console. See attached screen recording. 

I am only seeing this on Mac. No repro on Windows.

**Comment by beccamc** [comment]
This issue here is when the code fix menu overlaps with code lens. See the attached gif. 

![returnType](https://github.com/dotnet/vscode-csharp/assets/9122518/cea132f0-5bb9-418f-923e-3716b7cf18d4)

Closing in favor of VS code tracking [bug](https://github.com/microsoft/vscode/issues/169854).
