### ISSUE TITLE
Do not restart LS when Omnisharp option changes with CDK installed which is a no op anyway

### ISSUE THREAD

**Issue by mikadumont** [dotnet/vscode-csharp#5774]
Install C# 2.0 prerelease and CDK preview from the marketplace (yes, first bug filed with that as the repro steps 😊)

1) Open a console project
2) Go to the C# extension settings and switch to omnisharp options
3) Omnisharp option is ignored in LS with CDK installed. So no need to restart LS.

**Comment by dibarbet** [comment]
done in https://github.com/dotnet/vscode-csharp/pull/5895
