### ISSUE TITLE
[C# Dev Kit] `Go to definition` goes to decompilation instead of source

### ISSUE THREAD

**Issue by mareklinka** [dotnet/vscode-csharp#5776]
ms-dotnettools.csharp 2.0.206
ms-dotnettools.csdevkit: 0.1.83

I have a very simple solution consisting of a class library project and a test project for the library. When in the context of a unit test, hitting `F12` goes to decompilation instead of the corresponding source:

https://github.com/dotnet/vscode-csharp/assets/7479226/cfb6fc73-3ad5-4417-a2c1-68e8ae8b57ae

**Comment by igbenic** [comment]
Same, goes to obj/Debug/net7.0/ref/XYZ.dll instead of my code

**Comment by just-ero** [comment]
This can in fact be expanded to external libraries as well. Say the BCL or a NuGet, which both also go to decompiled code, even though the source is (most times) available.

**Comment by dibarbet** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/68472

Will be fixed in preview1.1 (releasing this week).
