### ISSUE TITLE
 CodeLens reference count incorrect

### ISSUE THREAD

**Issue by AndrewWoodi** [dotnet/vscode-csharp#5778]
## Environment data
`dotnet --info` output:

.NET SDK:
 Version:   7.0.302
 Commit:    990cf98a27

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.302\

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]
  6.0.102 [C:\Program Files\dotnet\sdk]
  6.0.116 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.400 [C:\Program Files\dotnet\sdk]
  7.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

VS Code version:

1.79.0

C# Extension version:

2.0.206 (Pre-Release)

## OmniSharp log

No OmniSharp log available. 

C# Log: 

Dotnet path: c:\Users\andre\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.5\dotnet.exe
Activating C# + C# Dev Kit + C# IntelliCode...
info: LanguageServerHost[0]
      Starting server...
[Info  - 4:29:46 PM] [LanguageServerProjectSystem]Loaded MSBuild at C:\Program Files\dotnet\sdk\7.0.302
[Info  - 4:29:46 PM] [LanguageServerProjectSystem]Loading c:\Users\andre\source\repos\algorithms\algorithms.sln...
[Info  - 4:29:49 PM] [LanguageServerProjectSystem]Successfully completed load of c:\Users\andre\source\repos\algorithms\test_console\test_console.csproj
[Info  - 4:29:49 PM] [LanguageServerProjectSystem]Successfully completed load of c:\Users\andre\source\repos\algorithms\strings\strings.csproj
[Info  - 4:29:49 PM] [LanguageServerProjectSystem]Completed (re)load of all projects in 00:00:02.696239

## Steps to reproduce

1. Ensure that CodeLens is enabled. 
2. Open a project with a class that has a method referred to by another project
3. View the reference count of a method that is referred to in another project.

## Expected  behavior

I expect the reference count to be correct. The reference count of public methods should include references in external projects.

See the screenshot below. This is example output when using the release version of the C# extension: 

![Screenshot 2023-06-10 162921](https://github.com/dotnet/vscode-csharp/assets/58918241/4b360a3e-9525-4889-8378-04946a4aad06)

## Actual behavior

The reference count of the count of public methods does not include references in external projects. 

See the screnshot below. This is with the pre-release version of the C# extension.

![Screenshot 2023-06-10 163010](https://github.com/dotnet/vscode-csharp/assets/58918241/9f714e5d-5a71-455c-9df7-538121d55690)

**Comment by dibarbet** [comment]
This appears to be fallout of the project system issue, same cause as https://github.com/dotnet/roslyn/issues/68472

Should be fixed in preview1.1 (coming out this week).

**Comment by arkalyanms** [comment]
@AndrewWoodi would you try upgrade to the v2.0.212 version of the C# extension to confirm if you issue is resolved?

**Comment by AndrewWoodi** [comment]
Yes, this is all working now. 

Thanks very much. The new version of the extension is going to be fantastic. Thanks for all your hard work.
