### ISSUE TITLE
Error when restarting Language Server

### ISSUE THREAD

**Issue by Igorgro** [dotnet/vscode-csharp#5779]
When running ".NET: Restart Language Server" vscode command, I get the following error:

![image](https://github.com/dotnet/vscode-csharp/assets/22894169/43f8093a-d0b8-4cf1-97f3-571293a35b58)

## Environment data
`dotnet --info` output:
```
.NET SDK:
 Version:   7.0.302
 Commit:    990cf98a27

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.302/

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  6.0.408 [/usr/share/dotnet/sdk]
  7.0.302 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.16 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.16 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found
``` 
VS Code version: 1.79.0
C# Extension version: v2.0.206

## Steps to reproduce

1. Install preview version of C# extension
2. Open any C#/.NET project and wait for language server to start
3. Open command palette and run ".NET: Restart Language Server" command
4. See error (screenshot)

## Expected  behavior
No error is shown

## Actual behavior
See attached screenshot

## Additional context
--

**Comment by dibarbet** [comment]
@allisonchou Razor bug, FYI
