### ISSUE TITLE
License on VS Code marketplace 

### ISSUE THREAD

**Issue by filipnavara** [dotnet/vscode-csharp#5783]
The description on VS Code marketplace has a license link pointing to https://devdiv.visualstudio.com/DevDiv/_git/vscode-csharp-next?path=/RuntimeLicenses/license.txt. That URL is not accessible without a login. In fact, it doesn't even let me login. The license should be accessible without an account.

**Comment by dibarbet** [comment]
Believe this should be resolved as soon as we ship a vsix out of this repo

**Comment by dibarbet** [comment]
Should be fixed as of todays release
<img width="448" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/5749229/87802ca9-4c82-43f6-ae8c-0e7cbb4e10b8">
