### ISSUE TITLE
Starting OmniSharp server

### ISSUE THREAD

**Issue by Khonglim** [dotnet/vscode-csharp#5795]
.
    Path: /Users/.vscode/extensions/ms-dotnettools.csharp-1.25.7-darwin-arm64/.omnisharp/1.39.6-net6.0/OmniSharp.dll
    PID: 83470

[STDERR] Unhandled exception. 
[STDERR] System.BadImageFormatException: An attempt was made to load a program with an incorrect format.
 (0x8007000B)

**Comment by JoeRobich** [comment]
The most likely cause of this is that you have the x64 build of the dotnet sdk installed. Try installing the arm64 (apple silicon) build.

**Comment by JoeRobich** [comment]
Closing as answered
