### ISSUE TITLE
Can not disable Reference Code Lens

### ISSUE THREAD

**Issue by kemsky** [dotnet/vscode-csharp#5809]
## Environment data
`dotnet --info` output:
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /home/xxx/.dotnet/sdk/7.0.100/

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  3.1.422 [/home/xxx/.dotnet/sdk]
  6.0.400 [/home/xxx/.dotnet/sdk]
  7.0.100 [/home/xxx/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.28 [/home/xxx/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [/home/xxx/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [/home/xxx/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.28 [/home/xxx/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [/home/xxx/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [/home/xxx/.dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/home/xxx/.dotnet]

global.json file:
  Not found

VS Code version: 1.79.0
C# Extension version: v2.0.212

## Steps to reproduce

C# extension has option to enable/disable reference code lens but it has no effect, lens always on:

![image](https://github.com/dotnet/vscode-csharp/assets/3826972/c1c9ef64-602c-4041-bb31-6df5e587d05a)

## Expected  behavior
Should enable or disable reference code lens

## Actual behavior
does nothing

## Additional context

Used to work in v1

**Comment by dibarbet** [comment]
This will be in next weeks release
