### ISSUE TITLE
repo link error

### ISSUE THREAD

**Issue by heartacker** [dotnet/vscode-csharp#5811]
![image](https://github.com/dotnet/vscode-csharp/assets/1876302/fe7428a2-e7c5-4870-a8c0-6030fea66d12)

**Comment by dibarbet** [comment]
Will be fixed as soon as we ship a release out of this repo (most likely next week).

**Comment by dibarbet** [comment]
Fixed in todays release
<img width="270" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/5749229/428eadf1-63ab-4c20-ba78-c10032669459">
