### ISSUE TITLE
[BUG] Issue with "Go to Implementations" feature opening decompiled file instead of source code

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/vscode-csharp#5816]
From vscode-dotnettools created by [nphamvn](https://github.com/nphamvn): microsoft/vscode-dotnettools#135  

### Describe the Issue

In my solution, I have two projects: a Web project (Web application) and a Domain project (Class library). The Web project references the Domain project. However, when I attempt to use the "Go to implementations" feature in the Web project to navigate to the implementation, it opens a temporary decompiled file instead of the source code in the Domain project.

**Comment by jasonmalinowski** [comment]
@nphamvn: we've shipped an update to the C# extension bringing it up to 2.0.212 which might already fix this -- I can't quite tell based on your description which version you had. Can you upgrade and try again?
