### ISSUE TITLE
Can't find system packages definition.

### ISSUE THREAD

**Issue by zhen8838** [dotnet/vscode-csharp#5818]
## Environment data
`dotnet --info` output: 
  .NET SDK:
 Version:   7.0.203
 Commit:    5b005c19f5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.2
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.203/

Host:
  Version:      7.0.5
  Architecture: arm64
  Commit:       8042d61b17
VS Code version:
  1.79.2
695af097c7bd098fbf017ce3ac85e09bbc5dda06
arm64
C# Extension version:  v2.0.212

## Actual behavior
when update c# to pre-release  v2.0.212, can't find any system packages definition:

https://github.com/dotnet/vscode-csharp/assets/26156999/ef05f4dd-ae71-47be-9b26-0ba973df8e4e

**Comment by arkalyanms** [comment]
No repro on a windows device, may be mac specific.

**Comment by jasonmalinowski** [comment]
@zhen8838 Did you also have the Dev Kit extension installed? Either way, did you have any errors in the C# output log?

**Comment by jasonmalinowski** [comment]
(it's also possible this is now fixed by the change @tmeschter made around ensuring design time builds actually run CoreCompile)

**Comment by zhen8838** [comment]
now I switch to the old version.

**Comment by jasonmalinowski** [comment]
> now I switch to the old version.

@zhen8838 Do you mean you switched to an older version to work around this, or it's working for you now on new versions?
