### ISSUE TITLE
About failing to highlight syntax correctly

### ISSUE THREAD

**Issue by Edemilorhea** [dotnet/vscode-csharp#5819]
Type: <b>Bug</b>

If I need to use this C# Dev kit, I must first upgrade the C# extension to the preview version.

But this creates several problems.

1.
My syntax highlighting is invalid. I am developing a Blazor Wasm Host project, but the project is developed from .Net 6.0, and the current version is .Net 7.0.
The most important thing is that I reopened a project. Syntax highlighting does not seem to be a big problem at present, but as long as I change the Extension to the release version, the problem will be solved.

2.
Related commands provided by the C# Dev kit cannot be used in Blazor, including .Net Restrt, which will cause errors in some commands

Extension version: 1.25.9
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700F (24 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.84GB (41.78GB free)|
|Process Argv|--crash-reporter-id ea7c6aa3-c78c-47b1-96da-a5973dfa85be|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
pythonfmttext:30731395
pythoncmv:30756943
fixhidewlkth:30730051
showindicator:30766890
pythongtdpath:30769146
i26e3531:30769768
dh2dc718:30763024

```

</details>

**Comment by lior0r** [comment]
I am also experiencing this issue, fresh install of vs code

**Comment by dibarbet** [comment]
This issue is quite stale and we've made a number of fixes in these areas - if you're still having issues on the latest version of the extension, please re-open and include the C# logs + general reproduction steps.
