### ISSUE TITLE
Have some problem when using <Project Sdk="Microsoft.NET.Sdk.Web"> in class library

### ISSUE THREAD

**Issue by abdollahkahne** [dotnet/vscode-csharp#5820]
## Issue Description ##
When I change the project sdk from Microsoft.Net.Sdk to Microsoft.Net.Sdk.Web in class library I have some problems. For eample you can not auto generate constructor from `private readonly` fields or I can not implement interfaces. I am sure there is other problem too but I am not sure which of them are specific to this sdk.
### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.79.2
**C# Extension**: 1.25.2

<details><summary>Mono Information</summary>
        There is a problem with running OmniSharp on mono: Error: Unable to find Mono. Ensure that Mono's '/bin' folder is added to your environment's PATH variable.</details>
<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.304
 Commit:    7e794e2806

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.304/

Host:
  Version:      7.0.7
  Architecture: x64
  Commit:       5b20af47d9

.NET SDKs installed:
  7.0.304 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|asp-net-core-switcher|adrianwilczynski|2.0.2|
|blazor-snippet-pack|adrianwilczynski|2.6.1|
|csharp|ms-dotnettools|1.25.2|
|csharpextensions|kreativ-software|1.7.3|
|docomment|k--kato|1.0.0|
|markdown-preview-enhanced|shd101wyy|0.6.8|
|prettier-vscode|esbenp|9.13.0|
|razor-switcher|LennartKleymann|1.0.0|
|rest-client|humao|0.25.1|
|sharppad|jmazouri|1.1.0|
|test-adapter-converter|ms-vscode|0.1.8|
|vscode-dotnet-runtime|ms-dotnettools|1.6.0|
|vscode-markdownlint|DavidAnson|0.51.0|
|vscode-resx-editor|DominicVonk|0.0.5|;

</details>

**Comment by JoeRobich** [comment]
A lot has changed with O# since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
