### ISSUE TITLE
Run/Debug Tests not showing for C# extension with prerelase version

### ISSUE THREAD

**Issue by timheuer** [dotnet/vscode-csharp#5823]
Migrated from https://github.com/microsoft/vscode-dotnettools/issues/161 (from @claytonweaver)

Type: <b>Bug</b>

Open any .net solution with no prerelease version of C# extension (without c# dev kit) and you don't get the option for run and debug.

Extension version: 2.0.212
VS Code version: Code 1.79.0 (b380da4ef1ee00e224a15c1d4d9793e27c2b6302, 2023-06-07T14:26:35.552Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (10.19GB free)|
|Process Argv|misc.code-workspace --crash-reporter-id f6a729dc-634b-4958-b661-e16e7f4bfa41|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
f6dab269:30613381
vscrp:30673768
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixhidewlkth:30730051
pythongtdpath:30769146
bgfeh915:30769767
dh2dc718:30763024

```

</details>

**Comment by Igorgro** [comment]
Duplicate of https://github.com/dotnet/vscode-csharp/issues/5719

**Comment by timheuer** [comment]
Thanks for the dupe tag @Igorgro closing as dupe of #5719
