### ISSUE TITLE
Typing a keyword followed by space at start of another word deletes the preceding word when suggestions are triggered

### ISSUE THREAD

**Issue by valters-tomsons** [dotnet/vscode-csharp#5826]
## Issue Description ##

When typing a keyword at the start of another word and then pressing the space bar, the preceding word gets deleted. This behavior seems to be triggered when the autocomplete suggestions pop up.

I've uninstalled all other extensions and reset the entire VScode configuration.

<details> 
  <summary>🎥 Video Recording Here! 🎥</summary>

   [Kooha-2023-06-19-02-45-00.webm](https://github.com/dotnet/vscode-csharp/assets/4209639/7f965768-7cbd-4de3-809e-84439cee6372)
</details>

## Steps to Reproduce ##

1. Open Visual Studio Code.
2. Enable the C# extension.
3. Create a new C# file or open an existing one.
4. Type a word, for example, exampleWord.
5. Place the cursor at the start of the word you just typed.
6. Begin typing a C# keyword such as bool.
7. Make sure the autocomplete suggestion popup appears.
8. Finish typing the word and press space bar

## Expected Behavior ##

The keyword should be inserted at the cursor location followed by a space, without affecting the preceding word. For example, typing `bool` at the start of `exampleWord` should result in `bool exampleWord`.

## Actual Behavior ##

The preceding word is deleted when the space bar is pressed after typing a keyword at the start of the word. Using the previous example, `exampleWord` is deleted and only `bool  ` remains.

### OmniSharp log ###

Nothing appears in OmniSharp log when the word is replaced.

### C# log ###
Nothing appears in C# output when the word is replaced.

## Environment information ##

**VSCode version**: 1.79.2
**C# Extension**: 1.25.9

<details><summary>Mono Information</summary>
        OmniSharp using mono: 6.12.0</details>
<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.105
 Commit:    e1bc5e001c

Runtime Environment:
 OS Name:     endeavouros
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.105/

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  6.0.118 [/usr/share/dotnet/sdk]
  7.0.105 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.18 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/share/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.25.9|
|vscode-neovim|asvetliakov|0.0.97|;

</details>

**Comment by bwiklund** [comment]
this also started recently for our team. i couldn't find any mention of this bug in the main vscode issues page, so i think this extension might be the source of it? my global "insert/replace" for suggestions is set to insert, so i don't think it's coming from that.

**Comment by dschmitt-org** [comment]
Same behavior for me, it's annoying...

**Comment by parksj10** [comment]
Yes, just tested myself, same thing. Note: tested with `Typescript` in my project and it seems to be specific to C# extension/language
