### ISSUE TITLE
the new omnisharp extension is too heavy, and i need to install c# devkit to get Intellisense

### ISSUE THREAD

**Issue by NCLnclNCL** [dotnet/vscode-csharp#5832]
when i open it up and don't use anything, vscode takes up 700mb ram, i only install omnisharp and code runner and extension boot time is quite long.so the c# extension that replaces the old omnisharp version only has a bridging effect?

**Comment by JoeRobich** [comment]
Are you using the Pre-release or Release version of the C# extension?

**Comment by NCLnclNCL** [comment]
> Are you using the Pre-release or Release version of the C# extension?

Yes bro, i use it

**Comment by dibarbet** [comment]
It should be possible to use the pre-release version of the C# extension standalone (without using C# devkit).  Could you share exactly what issues you were seeing when you tried that?

And if you could attach any logs (from the output window -> C#) from when things were not working, that would be extremely useful. 
Thanks!

**Comment by dibarbet** [comment]
This is not actionable without the requested information.  If you're still having issues on the latest version of the extension, please re-open and include the requested information.
