### ISSUE TITLE
[NETSDKE2E]With SDK 8.0.100-preview.6.23320.4 installed, warning NU1901: Package 'NuGet.Commands' 4.0.0 has a known low severity vulnerability, https://github.com/advisories/GHSA-3885-8gqc-3wpf occurred when Package Downgrades as Errors on Windows11 ARM64.

### ISSUE THREAD

**Issue by v-xiaofchen** [dotnet/vscode-csharp#5842]
## Environment data
`dotnet --info` output:
.NET SDK:
 Version:   8.0.100-preview.6.23320.4
 Commit:    a597bdf439

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-arm64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.6.23320.4\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-preview.6.23316.3
  Architecture: arm64
  Commit:       76da696f3f

.NET SDKs installed:
  8.0.100-preview.6.23320.4 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0-preview.6.23316.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0-preview.6.23316.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.6.23316.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

VS Code version: 1.79.2
C# Extension version: 1.25.9

## OmniSharp log
![image](https://github.com/dotnet/vscode-csharp/assets/99376012/fd277c41-7946-40a7-aa63-f22c1fc2c185)

## Steps to reproduce

1. Install SDK: 8.0.100-preview.6.23320.4 from https://github.com/dotnet/installer on windows11 ARM64 OS
2. Create a new .NET 8 console app and open it in VSCode
3. Add some Package Reference pairs that trigger a package downgrade warning.
E.g.  
![image](https://github.com/dotnet/vscode-csharp/assets/99376012/f6aebca2-cba5-4b98-8db0-d929e59b5e40)

## Expected  behavior
This should produce NU1605 Errors and no warning.

## Actual behavior
There is a warning NU1901: Package 'NuGet.Commands' 4.0.0 has a known low severity vulnerability, https://github.com/advisories/GHSA-3885-8gqc-3wpf produced.
![image](https://github.com/dotnet/vscode-csharp/assets/99376012/109ec54e-adac-452c-8754-aa4d328c98ab)

**Comment by v-xiaofchen** [comment]
This issue does not repro on Monterey(12.6.6) M1.

**Comment by dibarbet** [comment]
This doesn't seem like a bug - there is a security advisory for the version of Nuget.Commands that is being used.  Using one of the versions listed in https://github.com/advisories/GHSA-3885-8gqc-3wpf should resolve the problem (for example, 4.9.5 instead of 4.0.0).
