### ISSUE TITLE
Output window is opened automatically every time VS Code starts

### ISSUE THREAD

**Issue by jeffpapp** [dotnet/vscode-csharp#5844]
## Environment data

VS Code version:
C# Extension version: 2.0.212

## Steps to reproduce

1. Open VS Code for a folder with a C# solution or project
2. The output window automatically opens with a message `Starting command: "dotnet.exe" restore`

## Expected  behavior
I would expect the C# extension to just work in the background.  It's annoying that I have to close the output pane every single time VS Code opens with a C# project to tell me it's installing packages.  I don't really need to know this, at best it should be configurable.

## Actual behavior

Every time VS Code opens the output window pops up to tell me NuGet is restoring packages

**Comment by dibarbet** [comment]
The restore window is created by C# devkit - I created https://github.com/microsoft/vscode-dotnettools/issues/192 to track this issue on their end.

Closing this one in favor of the above issue.

**Comment by jeffpapp** [comment]
> The restore window is created by C# devkit - I created https://github.com/microsoft/vscode-dotnettools/issues/192 to track this issue on their end.
> 
> 
> 
> Closing this one in favor of the above issue.

Thanks!
