### ISSUE TITLE
C# extension v2.x introduces new file language association, which breaks several things

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/vscode-csharp#5860]
In C# extension version 1.x `.csproj` files were classified as `xml` files. I believe, this is default behaviour, and extension didn't change it. However, starting with versions 2.x `.csproj` files are now classified as `dotnetProject`, which breaks several things:
1. Default colorization for `xml` was good enough, but now it is completely gone:
**Before:**
![Code_F2rIS0OMjF](https://github.com/dotnet/vscode-csharp/assets/70431552/4f7321be-8584-4a08-89f2-a76001cc3ab7)
**After:**
![Code_XFvAkWeuVQ](https://github.com/dotnet/vscode-csharp/assets/70431552/66c18bd2-e0b4-4bb6-b730-81d5a85985f3)
2. This breaks existing extensions, that provide intellisense for MSBuild files, e.g. https://marketplace.visualstudio.com/items?itemName=tintoy.msbuild-project-tools relies on `msbuild` association.

So if it is possible, please revert to previous behaviour for better compatability. If such move is not possible/too complicated to do at least bring back xml syntax colorization

**Comment by 333fred** [comment]
@arkalyanms I think this needs to be addressed before GA.

**Comment by arkalyanms** [comment]
@WardenGnaw would you take a look? The association seems to come from https://github.com/dotnet/vscode-csharp/commit/173be18fd37ee88b53214a13b4b574507cc6ec34

**Comment by WardenGnaw** [comment]
Yep. This was added so we can support start debugging / start without debugging from the editor pane.

![image](https://github.com/dotnet/vscode-csharp/assets/3953714/9bfaae94-3b6e-42fd-ac6c-1e35f2122dbb)

There are two ways to fix this: 
1. Enable the coreclr debug engine to work on all [`xml` file types](https://github.com/microsoft/vscode/blob/57cf8c8ce3c7c30d06b40bb81fb5b4b0e98bebe6/extensions/xml/package.json#L15).
2. Port over the [xml grammer](https://github.com/microsoft/vscode/tree/main/extensions/xml) to the `dotnetProject` language.

**Comment by 333fred** [comment]
1 sounds like what we need to do. 2 would still leave xml-based extensions (such as tag completion and synchronization) broken.

**Comment by timheuer** [comment]
> 1. Enable the coreclr debug engine to work on all [`xml` file types](https://github.com/microsoft/vscode/blob/57cf8c8ce3c7c30d06b40bb81fb5b4b0e98bebe6/extensions/xml/package.json#L15).

Agree with @333fred here that 2 seems bad.  But associating a debugger with all xml types seems equally overkill.  What is lost here in somehow mapping to the file extension instead rather than some mime-type?  Can't we do an if (xml && .csproj) combo instead? (with obviously a better if check ;-))

**Comment by WardenGnaw** [comment]
> > 1. Enable the coreclr debug engine to work on all [`xml` file types](https://github.com/microsoft/vscode/blob/57cf8c8ce3c7c30d06b40bb81fb5b4b0e98bebe6/extensions/xml/package.json#L15).
> 
> Agree with @333fred here that 2 seems bad. But associating a debugger with all xml types seems equally overkill. What is lost here in somehow mapping to the file extension instead rather than some mime-type? Can't we do an if (xml && .csproj) combo instead? (with obviously a better if check ;-))

Yep. Reverting https://github.com/dotnet/vscode-csharp/commit/173be18fd37ee88b53214a13b4b574507cc6ec34 maybe the best solution for now and the workaround would be to select a `.cs` file to start debugging instead of your `.csproj` or `.sln`.

Debugging is heavily tied to a language instead of file type for now. I will work with the VS Code team to see if we can get that resolved but maybe require a newer vscode version past GA.

**Comment by gaelj** [comment]
This issue also breaks [version lens](https://marketplace.visualstudio.com/items?itemName=pflannery.vscode-versionlens), which is a deal-breaker to me
