### ISSUE TITLE
please tell us the changelog (insiders)

### ISSUE THREAD

**Issue by heartacker** [dotnet/vscode-csharp#5878]
The new version has no change log

**Comment by arkalyanms** [comment]
Its on our backlog, we plan to add it soon.

**Comment by dibarbet** [comment]
This should be fixed now - the changelog is on the marketplace 
https://marketplace.visualstudio.com/items/ms-dotnettools.csharp/changelog

And https://github.com/dotnet/vscode-csharp/blob/main/CHANGELOG.md
