### ISSUE TITLE
[BUG] Opening a solution with C# Dev Kit causes dotnet build to ignore .editorconfig analyzer settings

### ISSUE THREAD

**Issue by DavidZidar** [dotnet/vscode-csharp#5885]
### Describe the Issue

I have multiple projects that build cleanly with no warnings using `dotnet build` at the CLI.

But after having opened them using Visual Studio Code with the C# Dev Kit extension `dotnet build` shows warnings that are clearly disabled in the `.editorconfig` file. Even after exiting Visual Studio Code I have to kill all `dotnet.exe` processes to make `dotnet build` build properly again.

### Steps To Reproduce

1. Disable some analyzer warning in `.editorconfig`, for example `dotnet_diagnostic.CA1040.severity = none`
2. Open the solution using C# Dev Kit and watch it run restore
3. Build using `dotnet build` at the CLI

### Expected Behavior

Disabled warnings should not be displayed by `dotnet build`.

### Environment Information

- OS: Windows 11
- VS Code Version: 1.79.2
- Extension Versions: C# v2.0.248, C# Dev Kit v0.1.103

### Workaround

Set the environment variable `MSBUILDDISABLENODEREUSE=1`, this does makes builds slower but they'll be correct.

**Comment by DavidZidar** [comment]
I already reported this issue in microsoft/vscode-dotnettools#160 but since I feel that this is a pretty serious issue that seems to be ignored I am cross reporting here as well.

**Comment by arkalyanms** [comment]
This is still in scope for pre C# Dev Kit GA, but post C# GA.

**Comment by DavidZidar** [comment]
I've only been able to reproduce this issue with the C# Dev Kit extension running.

**Comment by reynoldsa** [comment]
Is work on this currently planned? Unfortunately this is a pretty big blocker for me to use dev kit, as my team have a nontrivial `editorconfig` + warnings as errors configured, so this causes builds to fail.

**Comment by arkalyanms** [comment]
Pulling into September opportunistically.

**Comment by DavidZidar** [comment]
I am no longer able to reproduce this issue, it seems to have been fixed somewhere at some point. @richardstanton wasn't able to reproduce the issue either as of last week and just closed my original issue so I guess I better close this one too. If anyone can confirm they still have this issue with the latest SDKs I can reopen.

**Comment by mdsitton** [comment]
> I am no longer able to reproduce this issue, it seems to have been fixed somewhere at some point. @richardstanton wasn't able to reproduce the issue either as of last week and just closed my original issue so I guess I better close this one too. If anyone can confirm they still have this issue with the latest SDKs I can reopen.

I had found that my issue ended up being an issue in my editorconfig so it could be a lack of error messages when this happens causing a lot of issues like this.

**Comment by thumpnail** [comment]
@definitelyokay got the same issue. Enableing omnisharp as a language server solves this issue but i would prefer to be able to use `c# dev kit` tbh. it seems like when not using omnisharpls it reverts back to some sort of internal formatting options even when a `.editorconfig` is present. I could be missing a json setting in vscode but i am finding none.
