### ISSUE TITLE
[NETSDKE2E] On Ubuntu20.04, ASP.Net symbols is missing with .NET SDK: 8.0.100-preview.6.23330.14 installed.

### ISSUE THREAD

**Issue by v-xiaofchen** [dotnet/vscode-csharp#5890]
## Environment data
OS: Ubuntu 20.04 X64
VS Code version:1.79.2
C# Extension version:1.26.0
.NET SDK: 8.0.100-preview.6.23330.14 from https://dev.azure.com/dnceng/internal/_build/results?buildId=2212903&view=artifacts&pathAsName=false&type=publishedArtifacts

## Steps to reproduce
1.Create a new ASP.NET Razor project by doing

mkdir razor
cd razor
dotnet new razor

2.Use File -> Open Folder to open the razor folder you have created in step 1

3.It may ask at the bottom right to install assets to build and debug, say yes.

4.After it has done this it will have created a .vscode directory in the ‘razor’ directory and a ‘launch.json’ file in that directory. Open the ‘.vscode’ directory, and double click on the ‘launch.json to edit it.

5.Add the following lines after the “name” line of the “Configurations” object. (This allows debugging through the framework.
"justMyCode": false,
"symbolOptions": {
"searchMicrosoftSymbolServer": true
},
"suppressJITOptimizations": true,

6.Double click on the ‘Startup.cs’ file in the ‘Explorer’ pane to bring up that source code.

7.Add the following line to the Startup.cs file at the beginning of the ‘Configure’ method (at the bottom of the file).
Console.WriteLine("x " + 3);

8.Place a breakpoint on that line (F9).

9.Run the application until it hit that breakpoint (F5). It will load symbols from the Microsoft symbol server, and may take a few seconds to hit the breakpoint. You should see 20-30 lines of ‘Loaded XXX Symbols loaded’. Lines as it does this).

10.Step into the concatination method (F11). This tests CoreCLR symbols AT THIS POINT IT SHOULD SHOW YOU THE SOURCE CODE FOR Concat(). If it does not that is a FAILURE. Please report it.

11.Step out of Concat (Shift F11). Then step into Console.WriteLine (F11).

12. Put breakpoint on this line -
	           if (!app.Environment.IsDevelopment())
F5 to continue debugging. The breakpoint you added above will get hit. Step into the ‘env.IsDevelopement() method (it should be the next line) by typing F11.   This tests ASP.Net symbols.   AT THIS POINT IT SHOULD SHOW YOU THE SOURCE CODE FOR HostingEnvironmentExtensions.IsDevelopment().  If it does not that is a FAILURE.  Please report it.  

## Expected  behavior
With step12, Step into the ‘env.IsDevelopement() method (it should be the next line) by typing F11. 
![preview5-1](https://github.com/dotnet/vscode-csharp/assets/99376012/303335bf-21a1-46eb-8810-f71aa5a429f8)

## Actual behavior
With step12, can not step into the ‘env.IsDevelopement() method (it should be the next line) by typing F11. 
![preview6-1](https://github.com/dotnet/vscode-csharp/assets/99376012/a4a39299-eb0c-48b2-8af3-f5b7dab9b97f)

##`dotnet --info`:
.NET SDK:
 Version:   8.0.100-preview.6.23330.14
 Commit:    ba97796b8f

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.100-preview.6.23330.14/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-preview.6.23329.7
  Architecture: x64
  Commit:       5340be2ccc

.NET SDKs installed:
  8.0.100-preview.6.23330.14 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0-preview.6.23329.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0-preview.6.23329.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

Note:
Not repro on .NET 8 preview5.

**Comment by v-xiaofchen** [comment]
Not repro on .NET 8 Preview 7 SDK: 8.0.100-preview.7.23356.13 (runtime-8.0.0-preview.7.23355.8), will keep tracking.
VS Code version:1.80.0
C# Extension version:1.26.0
![preview7](https://github.com/dotnet/vscode-csharp/assets/99376012/21caab9f-9c6a-41ec-836b-f72f672663c8)

**Comment by gregg-miskelly** [comment]
Closing the issue since this no longer repros.
