### ISSUE TITLE
Source generators not run for diagnostics

### ISSUE THREAD

**Issue by 333fred** [dotnet/vscode-csharp#5900]
Type: <b>Bug</b>

1. Clean your roslyn repo. I mean it, delete the `.artifacts` directory.
2. Open your roslyn repo, and navigate to a file with source generated types. As an example, `src/Compilers/CSharp/Test/Semantic/Semantics/FunctionPointerTests.cs`.

### Expected

No errors from missing source generated types.

### Actual

Errors about types being missing when those types are source generated.

Extension version: 2.0.246-gc81fc4a054
VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T13:39:48.236Z)
OS version: Linux x64 5.19.0-45-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz (20 x 4899)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 4, 5|
|Memory (System)|62.57GB (27.16GB free)|
|Process Argv|--no-sandbox . --crash-reporter-id 43eefd67-e97f-4f18-b0d4-472657c3e98a|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|regolith|
|XDG_CURRENT_DESKTOP|Regolith:GNOME-Flashback:GNOME|
|XDG_SESSION_DESKTOP|regolith|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes516:30244333
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30776702
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
vscrpc:30673769
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30766890
pythongtdpath:30769146
i26e3531:30780429
pythonnosm12tcf:30779713
pythonidxpt:30784022
pythonnocebcf:30776496
e537b577:30772215

```

</details>

**Comment by 333fred** [comment]
![image](https://github.com/dotnet/vscode-csharp/assets/2371880/3208c04a-0599-448e-b4f4-312419f99265)

**Comment by jasonmalinowski** [comment]
@333fred I'm slightly confused by your repro steps. Did you do another build after the artifacts directory? Because if not, I'd expect the error -- you no longer have a generator DLL on disk.

**Comment by 333fred** [comment]
> Did you do another build after the artifacts directory?

No, I did not.

**Comment by jasonmalinowski** [comment]
Then this is expected behavior. We don't have any mechanism today to compile the generator project in our process and then use that generator downstream -- we see a file reference and we expect the file to be there.

**Comment by sharwell** [comment]
📝 This feature request is tracked by https://github.com/dotnet/roslyn/issues/48083
