### ISSUE TITLE
Windows Parallels Desktop; M2 Silicon Mac Can not start OmniSharp

### ISSUE THREAD

**Issue by horvatic** [dotnet/vscode-csharp#5907]
## Environment data

global.json file:
  Not found

Host:
  Version:      6.0.18
  Architecture: x64
  Commit:       c76ac56549

.NET SDKs installed:
  6.0.410 [C:\Program Files\dotnet\x64\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.18 [C:\Program Files\dotnet\x64\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.18 [C:\Program Files\dotnet\x64\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.18 [C:\Program Files\dotnet\x64\shared\Microsoft.WindowsDesktop.App]

## OmniSharp log

Starting OmniSharp server at 7/10/2023, 11:53:32 AM
    Target: c:\LZ\sp.test\sp.test.sln

OmniSharp server started with .NET 6.0.410
.
    Path: c:\Users\horvatic\.vscode\extensions\ms-dotnettools.csharp-1.26.0-win32-arm64\.omnisharp\1.39.7-net6.0\OmniSharp.dll
    PID: 7092

[STDERR] Unhandled exception.
[STDERR]  
[STDERR] System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B)

[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).

## Steps to reproduce

1. Install VS code in Windows Parallels Desktop; M2 Silicon Mac 
2. Install C# Plugin
3. Plugin Crashes

## Expected  behavior
Plugin doesn't crash

## Actual behavior
Plugin Crashes

## Additional context
Running Windows 11 ARM within Parallels

**Comment by JoeRobich** [comment]
Hi @horvatic, You have the arm64 VS Code and C# extension builds but a x64 dotnet SDK. You will need to install the arm64 SDK for O# to start, since it loads resources out of the SDK.

**Comment by JoeRobich** [comment]
Closing as answered.
