### ISSUE TITLE
Where to get the new C# logo image?

### ISSUE THREAD

**Issue by julioct** [dotnet/vscode-csharp#5912]
A new C# logo appeared with the new C# Dev Kit, but I'm struggling to find the original high resolution png or svg image file. 

Is there a place I can get it from?

**Comment by Igorgro** [comment]
https://github.com/dotnet/vscode-csharp/blob/main/images/csharpIcon.png

**Comment by dibarbet** [comment]
@timheuer might you know if a larger version is available (and where)?

**Comment by timheuer** [comment]
They'll likely show up in more proper places but here's a 2048x for you...

![CS_2048](https://github.com/dotnet/vscode-csharp/assets/4821/9f5b83e7-cb9a-4f59-be6f-cb407c2247e9)

**Comment by julioct** [comment]
Thank you @timheuer!

**Comment by tauraigombera** [comment]
Awesome

**Comment by imadimadimadimad** [comment]
https://commons.wikimedia.org/wiki/File:C_Sharp_Logo_2023.svg

**Comment by pascalecu** [comment]
Hi, @timheuer, sorry to necropost. Do you happen to know if there exists a SVG (or at least a sufficiently high res image) for the F# and VB.NET logos? They are attested in the docs here: https://learn.microsoft.com/en-us/dotnet/, but I wasn't able to find any other source. The only SVG available points to the old logo over at https://docs.microsoft.com/en-us/media/logos/logo_vb.svg (same with {C,F}# if you replace vb with {c,f}sharp). These are 72x72, which are clearly not hi-res enough:

<img width="72" height="72" alt="Image" src="https://github.com/user-attachments/assets/cd502e24-8be6-469c-b70d-709f71def5c2" />

<img width="72" height="72" alt="Image" src="https://github.com/user-attachments/assets/975d5808-a0c6-4e6b-afcf-9ba65ad21d27" />

While not strictly relevant to this extension, I am hoping you might know who made the icons, and this is the only relevant issue where the new C# logo was ever discussed.

**Comment by timheuer** [comment]
Hi @pascalecu -- sure thing, I just submitted a PR to our brand repo with these, so they should be merged soon.
