### ISSUE TITLE
Completion of unimported types adds wrong import

### ISSUE THREAD

**Issue by dibarbet** [dotnet/vscode-csharp#5916]
Type: <b>Bug</b>

## Issue Description ##
Selecting an unimported type to complete chooses the wrong import to add when there are two imports for the same name.

## Steps to Reproduce ##
See gif attached

![completion_wrong_import_contract](https://github.com/dotnet/vscode-csharp/assets/5749229/3d1a5804-6592-46d8-bbb5-e1d3ffe3f45b)

1.  Open Roslyn.sln
2.  Open file that does not import the `Contract` symbol.
3.  Start typing `Contract` to trigger completion
4.  Select the `Contract` item from the `Roslyn.Utilities` namespace.
5.  Note how it adds an import for `System.Diagnostics.Contracts` instead.

## Expected Behavior ##
Selecting the completion item from `Roslyn.Utilities` imports adds a using for `Roslyn.Utilities`

## Actual Behavior ##
Selecting the completion item from `Roslyn.Utilities` imports adds a using for `System.Diagnostics.Contract`

## Logs ##

[output_logging_20230712T125641.zip](https://github.com/dotnet/vscode-csharp/files/12032505/output_logging_20230712T125641.zip)

## Environment information ##

**VSCode version**: 1.80.0
**C# Extension**: 2.0.249
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>

Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 7.0.9 [c:\Users\dabarbet\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.9\shared\Microsoft.NETCore.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|csdevkit|ms-dotnettools|0.2.100|ms-dotnettools.csdevkit-0.2.100-win32-x64|
|csharp|ms-dotnettools|2.0.249|ms-dotnettools.csharp-2.0.249-win32-x64|
|powershell|ms-vscode|2023.6.0|ms-vscode.powershell-2023.6.0|
|remote-wsl|ms-vscode-remote|0.80.2|ms-vscode-remote.remote-wsl-0.80.2|
|richcodenav|MS-RichCodeNav|0.1.231|ms-richcodenav.richcodenav-0.1.231|
|test-adapter-converter|ms-vscode|0.1.8|ms-vscode.test-adapter-converter-0.1.8|
|tsl-problem-matcher|amodio|0.6.2|amodio.tsl-problem-matcher-0.6.2|
|vscode-dotnet-runtime|ms-dotnettools|1.6.0|ms-dotnettools.vscode-dotnet-runtime-1.6.0|
|vscode-eslint|dbaeumer|2.4.2|dbaeumer.vscode-eslint-2.4.2|
|vscode-pull-request-github|GitHub|0.68.0|github.vscode-pull-request-github-0.68.0|
|vscodeintellicode-csharp|ms-dotnettools|0.1.26|ms-dotnettools.vscodeintellicode-csharp-0.1.26-win32-x64|;

</details>

Extension version: 2.0.249
VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T15:06:02.407Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 7950X 16-Core Processor             (24 x 4500)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|32.00GB (2.96GB free)|
|Process Argv|. --crash-reporter-id 04f71626-2539-4283-a32d-cf61d5b2c689|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30784847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
bgfeh915:30780428
pythonnosmt12:30779714
pythonidxpt:30784022
pythonnoceb:30776495
h7j2d465:30786200
dsvsc013cf:30784101

```

</details>

**Comment by OoLunar** [comment]
Able to reproduce on any project which has multiple types of the same name on different namespaces.

**Comment by ThaDaVos** [comment]
Oh the feature even works for you? For me it doesn't add anything - I have to use the Intellisense yellow lightbulb to get my imports 🤣🤣

(Sorry for commenting on something which is closed, just wanted to let it be known)

**Comment by OoLunar** [comment]
Yes, I've recently encountered this issue as well. I believe this is caused by something else though, and should probably be opened in a separate GitHub issue.
