### ISSUE TITLE
Move class to its own file refactoring creates file in wrong folder

### ISSUE THREAD

**Issue by AArnott** [dotnet/vscode-csharp#5918]
Type: <b>Bug</b>

I have a .cs file with 5 classes in a subfolder of my project. When using the 'Move to its own file' refactoring, the class is moved to a file in the project root directory instead of keeping it in the directory it was originally in.

I have C# Dev Kit installed and the solution loaded.

Extension version: 2.0.271-gdd5cb6a983
VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T15:06:02.407Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz (16 x 2793)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|63.95GB (37.56GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/andarno/source/repos/VisualStudio.Conversations --crash-reporter-id 9c78b15b-0d6e-432f-83a0-8d9f7be0e545|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30784848
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyonecf:30548226
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
hideindicator:30785051
pythongtdpath:30769146
i26e3531:30780429
pythonnosmt12:30779714
pythonidxpt:30784022
pythonnoceb:30776495
e537b577:30786199
dsvsc013cf:30784101

```

</details>

**Comment by mrdamian** [comment]
I have the same problem. It is reproducible on both Mac and Windows. For testing purposes I had only C# v2.0.357 installed

**Comment by Cosifne** [comment]
Fixed https://github.com/dotnet/roslyn/pull/68995
