### ISSUE TITLE
language server cannot start unless the project is a sln

### ISSUE THREAD

**Issue by imcainess** [dotnet/vscode-csharp#5923]
Type: <b>Bug</b>

> dotnet new console
> open in vscode
c# output
Dotnet path: c:\Users\foo\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.9\dotnet.exe
Activating C# standalone...
info: LanguageServerHost[0]
      Starting server...

Extension version: 2.0.249
VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:07.651Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2400G with Radeon Vega Graphics     (8 x 3593)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|13.92GB (6.36GB free)|
|Process Argv|-n --crash-reporter-id ecb23b5c-531e-4aff-8414-101be1092934|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30789497
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
hideindicator:30785051
pythongtdpath:30769146
i26e3531:30780429
pythonnosm12tcf:30779713
pythonidxpt:30784022
pythonnocebcf:30776496
e537b577:30786199
dsvsc013cf:30789518

```

</details>

**Comment by aeb-dev** [comment]
Having the same problem

**Comment by rng4302** [comment]
> Is there an ETA when this is getting fixed?
> 
> Edit: Fixed it by setting `dotnet.server.useOmnisharp` to true.

But where to set this thing?

**Comment by imcainess** [comment]
> 

what ETA means, temporary fix
1) add sln file and add your project to sln
2) use c# dev kit, which will auto add sln file in your root directory
3) switch back to stable release, which much slower than prerelease one

**Comment by rng4302** [comment]
> > 
> 
> what ETA means, temporary fix
> 
> 1. add sln file and add your project to sln
> 2. use c# dev kit, which will auto add sln file in your root directory
> 3. switch back to stable release, which much slower than prerelease one

This will be slow only once while opening vsc? Or it will be slow throughout?

**Comment by arkalyanms** [comment]
Retitling since its not prerelease anymore. This is coming soon. Using this as the primary to post updates on the release.

**Comment by stoyandimov** [comment]
> dotnet.server.useOmnisharp

you can open vscode settings and past the exact setting in the search. This will show a check to switch it on.
