### ISSUE TITLE
Deprecated. . .

### ISSUE THREAD

**Issue by zhouxinghong** [dotnet/vscode-csharp#5944]
Deprecated. . .

**Comment by arkalyanms** [comment]
@zhouxinghong would you update the dotnet.server.trace setting to Trace and attach the C# output window logs for us to investigate this further?

**Comment by zhouxinghong** [comment]
This problem has been submitted by many friends, but it has not been resolved. You can try to see the effect after installing all the tools according to the version information I submitted. terribly sorry! I don't want to waste time on `VSCode` `C#`. I still returned to the first IDE in the universe, namely `VisualStudio`
