### ISSUE TITLE
Can not format single `.cs` file

### ISSUE THREAD

**Issue by GF-Huang** [dotnet/vscode-csharp#5948]
## Issue Description ##
Can not format single `.cs` file

## Steps to Reproduce ##
1. Just create a single .cs file.
2. Press `shift` + `alt` + `f` for formatting.

It will show you no formatter installed for C#.

![image](https://github.com/dotnet/vscode-csharp/assets/4510984/10ee5976-ebe0-448f-a27a-da00021bd689)

## Expected Behavior ##
Format the code.

## Actual Behavior ##
It will show you no formatter installed for C#.

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.80.1
**C# Extension**: 1.26.0

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.306
 Commit:    f500069cb7

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.306\

Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  4.2.207 [C:\Program Files\dotnet\sdk]
  5.1.426 [C:\Program Files\dotnet\sdk]
  6.0.315 [C:\Program Files\dotnet\sdk]
  7.0.306 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|anaconda-extension-pack|ms-python|1.0.1|
|ascii-unicode-escape|yaruson|0.1.0|
|auto-close-tag|formulahendry|0.5.14|
|auto-using|Fudge|0.7.15|
|black-formatter|ms-python|2023.4.1|
|cpptools|ms-vscode|1.16.3|
|csharp|ms-dotnettools|1.26.0|
|dotnet-interactive-vscode|ms-dotnettools|1.0.4313020|
|dotnetscriptr|Wivuu|0.2.4|
|ecdc|mitchdenny|1.8.0|
|escaping-characters|drphrozen|1.0.0|
|go|golang|0.39.1|
|hexeditor|ms-vscode|1.9.11|
|html-css-class-completion|Zignd|1.20.0|
|ini-for-vscode|DavidWang|0.0.4|
|isort|ms-python|2023.10.1|
|JavaScriptSnippets|xabikos|1.8.0|
|js-eval-replace|hanneshdc|1.0.0|
|json-tools|eriklynd|1.0.2|
|jupyter|ms-toolsai|2023.6.1101941928|
|jupyter-keymap|ms-toolsai|1.1.2|
|jupyter-renderers|ms-toolsai|1.0.17|
|LogFileHighlighter|emilast|2.16.0|
|markdown-all-in-one|yzhang|3.5.1|
|markdown-preview-github-styles|bierner|2.0.2|
|pascal|alefragnani|9.6.0|
|path-intellisense|christian-kohler|2.8.4|
|powershell|ms-vscode|2023.6.0|
|prettify-json|mohsen1|0.0.3|
|python|ms-python|2023.12.0|
|quicktype|quicktype|12.0.46|
|rainbow-csv|mechatroner|3.7.0|
|reg|ionutvmi|1.1.0|
|remote-explorer|ms-vscode|0.4.1|
|remote-ssh|ms-vscode-remote|0.102.0|
|remote-ssh-edit|ms-vscode-remote|0.86.0|
|sarif-viewer|MS-SarifVSCode|3.3.9|
|sqlite-viewer|qwtel|0.2.5|
|systemd-unit-file|coolbear|1.0.6|
|transformer|dakara|1.12.1|
|vdf|GEEKiDoS|0.0.7|
|vs-code-xml-format|fabianlauer|0.1.5|
|vs-keybindings|ms-vscode|0.2.1|
|vscode-caddyfile-syntax|zamerick|1.0.4|
|vscode-commons|redhat|0.0.6|
|vscode-docker|ms-azuretools|1.26.0|
|vscode-exec-node|miramac|0.5.5|
|vscode-innosetup|chouzz|1.9.2|
|vscode-json-editor|nickdemayo|0.3.0|
|vscode-jupyter-cell-tags|ms-toolsai|0.1.8|
|vscode-jupyter-slideshow|ms-toolsai|0.1.5|
|vscode-language-pack-zh-hans|MS-CEINTL|1.80.2023071209|
|vscode-nuget-gallery|patcx|0.0.24|
|vscode-proto3|zxh404|0.5.5|
|vscode-pylance|ms-python|2023.7.30|
|vscode-standard-format|chenxsan|0.0.12|
|vscode-typescript-ast-explorer|krizzdewizz|1.0.0|
|vscode-witcherscript|nicollasricas|1.0.9|
|vscode-yaml|redhat|1.14.0|
|vue-snippets|hollowtree|1.0.4|
|xml|DotJoshJohnson|2.5.1|;

</details>

**Comment by JoeRobich** [comment]
The C# extension only provides language services for C# files within the context of a project.
