### ISSUE TITLE
Json Deserialize struct error when step over deserialize statement

### ISSUE THREAD

**Issue by 10ve** [dotnet/vscode-csharp#5952]
## Issue Description ##
Json Deserialize error when step over deserialize statement
## Steps to Reproduce ##
```csharp
using System.Text.Json;
var _options = new JsonSerializerOptions()
{
    WriteIndented = true,
    IncludeFields = true
};
var teststruct = new TestStruct()
{
    str1 = "hello",
    str2 = "world",
    num = 1,
    data = new SubTestStruct()
    {
        number = 2,
        str3 = "bug",
    }
};
var testStructStr = JsonSerializer.Serialize(teststruct, _options);
Console.WriteLine(testStructStr);
var deTestStructStr = JsonSerializer.Deserialize<TestStruct>(testStructStr, _options);
Console.WriteLine(deTestStructStr.num);

struct TestStruct
{
    public string? str1;
    public string? str2;
    public int num;
    public SubTestStruct data;

}
struct SubTestStruct
{
    public int number;
    public string str3;
}
```
1.  breakpoint at `var deTestStructStr = JsonSerializer.Deserialize<TestStruct>(testStructStr, _options);`
2. Step Over
3. 
<img width="335" alt="Screenshot 2023-07-24 at 2 25 33 PM" src="https://github.com/dotnet/vscode-csharp/assets/11514850/fded6c5e-d837-4b4a-be3c-dc31c02b96d1">

when no breakpoint
<img width="333" alt="Screenshot 2023-07-24 at 2 27 41 PM" src="https://github.com/dotnet/vscode-csharp/assets/11514850/c79d50cc-3f5b-4bcb-99f2-4a8b588908ea">

## Expected Behavior ##

Deserialize Consistent behavior

## Actual Behavior ##

Deserialize error

## Environment information ##

**VSCode version**: 1.80.1
**C# Extension**: 1.26.0

<details><summary>Mono Information</summary>
        OmniSharp using mono: 6.12.0</details>
<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.203
 Commit:    5b005c19f5

运行时环境:
 OS Name:     Mac OS X
 OS Version:  13.4
 OS Platform: Darwin
 RID:         osx.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.203/

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  7.0.203 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.26.0|
|theme-dracula|dracula-theme|2.24.3|
|vscode-language-pack-zh-hans|MS-CEINTL|1.80.2023071209|;

</details>

**Comment by 10ve** [comment]
> I am not able to reproduce this. Questions:
> 
> 1. I see that you don't have the latest version of the .NET 7 SDK installed. Can you try upgrading?
> 2. Assuming you can still reproduce this after upgrading, if you change `TestStruct` to a `class` can you still reproduce this?

1. still reproduce this

```
dotnet --version
7.0.306
```
<img width="481" alt="Screenshot 2023-07-25 at 9 52 29 AM" src="https://github.com/dotnet/vscode-csharp/assets/11514850/179dbeb3-52f0-41c6-a058-c5e360cbd71e">

2. Resolve errors only when the type is a structure

**Comment by gregg-miskelly** [comment]
Thanks, next question: can you try disabling AVX code generation in your app's process? Assuming you are configuring the debugger to launch using launch.json, you can do so with:

```json
            "env": {
                "DOTNET_EnableAVX": "0"
            }
```

**Comment by gregg-miskelly** [comment]
Thanks! In this case you are running into https://github.com/dotnet/runtime/issues/78991. Hopefully the .NET runtime will address it soon. In the meantime, I hope that work around will keep you unblocked.
