### ISSUE TITLE
Type names in hover are not colorized correctly

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/vscode-csharp#5966]
## Steps to Reproduce ##
```cs
using System.Collections.Generic;

List<int> ints;
```
Hover over `List`
Hover over `int`

## Expected Behavior ##
Hover over `List` contains `System.Collections.Generic.List<T>`, `List` colorized as type, `T` colorized as generic constraint
Hover over `int` contains `System.Int32`, `Int32` colorized as type

## Actual Behavior ##
Instead of `List` first part of namespace (`System` in this case) is colorized as type name:
![Code_sUfPUZaKoZ](https://github.com/dotnet/vscode-csharp/assets/70431552/0c361f8f-beff-4cc4-81a3-85fbc37a684c)

Same with `int` (I have VS2019 theme installed, so struct type colorization is different for me):
![Code_0ntLvoQEe9](https://github.com/dotnet/vscode-csharp/assets/70431552/de5dc1d9-d7f9-4f27-93ec-cad7c9be19ae)

### C# log ###
<details>Post the output from Output-->C# here</details>

### C# LSP Trace Logs ###
<details>Post the output from Output-->C# LSP Trace Logs here.  Requires `dotnet.server.trace` to be set to `Trace`</details>

## Environment information ##

**VSCode version**: 1.80.2
**C# Extension**: 2.0.312
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>

Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 7.0.9 [c:\Users\mapmy\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.9\shared\Microsoft.NETCore.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|csharp|ms-dotnettools|2.0.312|ms-dotnettools.csharp-2.0.312-win32-x64|
|EditorConfig|EditorConfig|0.16.4|editorconfig.editorconfig-0.16.4|
|LiveServer|ritwickdey|5.7.9|ritwickdey.liveserver-5.7.9|
|markdown-preview-enhanced|shd101wyy|0.6.8|shd101wyy.markdown-preview-enhanced-0.6.8|
|msbuild-project-tools|tintoy|0.4.9|tintoy.msbuild-project-tools-0.4.9|
|powershell|ms-vscode|2023.6.0|ms-vscode.powershell-2023.6.0|
|python|ms-python|2023.12.0|ms-python.python-2023.12.0|
|svg-preview|SimonSiefke|2.8.3|simonsiefke.svg-preview-2.8.3|
|vscode-dotnet-runtime|ms-dotnettools|1.6.0|ms-dotnettools.vscode-dotnet-runtime-1.6.0|
|vscode-icons|vscode-icons-team|12.4.0|vscode-icons-team.vscode-icons-12.4.0|
|vscode-language-pack-ru|MS-CEINTL|1.80.2023071209|ms-ceintl.vscode-language-pack-ru-1.80.2023071209|
|vscode-pull-request-github|GitHub|0.68.1|github.vscode-pull-request-github-0.68.1|
|vscode-pylance|ms-python|2023.7.40|ms-python.vscode-pylance-2023.7.40|;

</details>

**Comment by dibarbet** [comment]
Unfortunately we don't have much control over colorization in hover - we are only able to put in markdown code fences with no semantic information.

https://github.com/microsoft/vscode/issues/91279 tracks supporting better colorization in hover on the vscode side.  Until that is resolved we can't do much here, so closing this.

**Comment by dibarbet** [comment]
Related to https://github.com/dotnet/vscode-csharp/issues/6654
