### ISSUE TITLE
Omnisharp failing with .NET 8.0.100-preview-6

### ISSUE THREAD

**Issue by goncalo-oliveira** [dotnet/vscode-csharp#5967]
Omnisharp seems to be having issues with .NET 8, preview 6. It's not consistent, seems to be working fine for class library projects, but not for console projects.

## Steps to Reproduce ##

1. Create a .NET console app
2. Watch Omshisharp log

## Expected Behavior ##

No errors.

## Actual Behavior ##

Omnisharp fails.

### OmniSharp log ###

```
[fail]: OmniSharp.Stdio.Host
        ************  Response (65.1662ms) ************ 
{
  "Request_seq": 2178,
  "Command": "/v2/getcodeactions",
  "Running": true,
  "Success": false,
  "Message": "\"System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. [..],
  "Body": null,
  "Seq": 246,
  "Type": "response"
}
```

### C# log ###
<details>
Getting latest OmniSharp version information
Downloading package 'Latest OmniSharp Version Information' (1 KB).................... Done!
</details>

## Environment information ##

**VSCode version**: 1.80.1
**C# Extension**: 1.26.0

<details><summary>Mono Information</summary>
        There is a problem with running OmniSharp on mono: Error: Unable to find Mono. Ensure that Mono's '/bin' folder is added to your environment's PATH variable.</details>
<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   8.0.100-preview.6.23330.14
 Commit:    ba97796b8f

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.4
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.100-preview.6.23330.14/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-preview.6.23329.7
  Architecture: arm64
  Commit:       5340be2ccc

.NET SDKs installed:
  6.0.201 [/usr/local/share/dotnet/sdk]
  7.0.100 [/usr/local/share/dotnet/sdk]
  7.0.102 [/usr/local/share/dotnet/sdk]
  7.0.202 [/usr/local/share/dotnet/sdk]
  7.0.203 [/usr/local/share/dotnet/sdk]
  7.0.302 [/usr/local/share/dotnet/sdk]
  8.0.100-preview.6.23330.14 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.6.23329.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.6.23329.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]
    registered at [/etc/dotnet/install_location_x64]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azurite|Azurite|3.25.0|
|copilot|GitHub|1.99.289|
|csharp|ms-dotnettools|1.26.0|
|dart-code|Dart-Code|3.68.1|
|EditorConfig|EditorConfig|0.16.4|
|even-better-toml|tamasfe|0.19.2|
|flutter|Dart-Code|3.68.0|
|go|golang|0.39.1|
|hexeditor|ms-vscode|1.9.11|
|markdown-mermaid|bierner|1.19.0|
|mongodb-vscode|mongodb|1.1.0|
|rainbow-csv|mechatroner|3.7.0|
|volar|Vue|1.8.8|
|vscode-docker|ms-azuretools|1.26.0|
|vscode-github-actions|github|0.25.8|
|vscode-openapi|42Crunch|4.18.5|
|vscode-pbkit|pbkit|0.0.5|
|vscode-typescript-vue-plugin|Vue|1.8.8|
|vscode-yaml|redhat|1.14.0|
|vsliveshare|ms-vsliveshare|1.0.5877|;

</details>

**Comment by JoeRobich** [comment]
A lot has changed with O# code analysis since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues

**Comment by PedroContipelli** [comment]
**EDIT: THIS [FIX](https://github.com/dotnet/vscode-csharp/issues/6718#issuecomment-1846766013) WORKED FOR ME**
