### ISSUE TITLE
Add 'coreclr' to keywords or other searchable

### ISSUE THREAD

**Issue by timheuer** [dotnet/vscode-csharp#5973]
When someone has an environment that doesn't have the extension installed and they attempt to debug, a dialog will show:
![image](https://github.com/dotnet/vscode-csharp/assets/4821/c573589f-fd30-4f9d-a559-7a65ff03e1b0)

VSCode creates a link `install coreclr extension` which is just a link to a pre-configured search that is `category:"debuggers" coreclr` which will return nothing for C#.  

![image](https://github.com/dotnet/vscode-csharp/assets/4821/98cbbf8a-a8f4-4744-9e38-a359fb5c5c21)

If we added the keyword and/or ensured it was in something that was indexed this would provide a better experience in this situation.

**Comment by dibarbet** [comment]
@timheuer if you were thinking of adding 'coreclr' as a keyword here - https://github.com/dotnet/vscode-csharp/blob/main/package.json#L25 I don't believe we can.  We're already at the limit of 5

![image](https://github.com/dotnet/vscode-csharp/assets/5749229/f1e8efb7-253e-4fec-9430-d807faaa8c8d)

I don't know of other places where we can configure the search (but my knowledge here is limited).

**Comment by timheuer** [comment]
@dibarbet do we know the history of "multi-root ready" keyword? that doesn't seem terribly valuable and can replace? Ironically if you look at marketplace listing it has more than 5.

**Comment by dibarbet** [comment]
I don't know the history myself, but this is the PR that added it - https://github.com/dotnet/vscode-csharp/pull/1841

Maybe @DustinCampbell remembers?  

I think multi-root ready indicates that you can open multiple folders.  Both O# / Roslyn only open 1 sln at a time though (unless load projects on demand works for multi-workspace in O#?  Not sure).

**Comment by timheuer** [comment]
I wonder if that is a hard-coded UI search thing in VS Code.  The one for 'coreclr' is -- when a debugger fails, VSCode basically has a link to pre-search and it's not a great experience.  I'd favor using one of our slots for this.

**Comment by DustinCampbell** [comment]
Yes, multi-root workspaces allow multiple folders to be opened at once. We made O# work with multi-root workspaces back in the day, but the support was pretty minimal. Instead of removing that, I would imagine that we should try to understand why there's a limit of 5. That seems unnecessarily restrictive.

**Comment by timheuer** [comment]
We can do that @DustinCampbell but I'm also just trying to understand if that's even a valuable keyword.  'coreclr' explicitly shows up (think fwlink as the dialog pre-calculates a search) and is failing customers.  'multi-root' seems odd unless similar.

**Comment by timheuer** [comment]
Fyi I'm told that the validation of only 5 keywords does not check.  In fact I just did it myself: https://marketplace.visualstudio.com/items?itemName=TimHeuer.base-ext-sample

**Comment by dibarbet** [comment]
> Fyi I'm told that the validation of only 5 keywords does not check. In fact I just did it myself: https://marketplace.visualstudio.com/items?itemName=TimHeuer.base-ext-sample

Hmm, might as well try it then!

**Comment by DustinCampbell** [comment]
> We can do that @DustinCampbell but I'm also just trying to understand if that's even a valuable keyword. 'coreclr' explicitly shows up (think fwlink as the dialog pre-calculates a search) and is failing customers. 'multi-root' seems odd unless similar.

I have no idea if it's still valuable. It was requested that we add that keyword here: https://github.com/Microsoft/vscode/wiki/Adopting-Multi-Root-Workspace-APIs.
