### ISSUE TITLE
Codelens References are still showing even though I disabled the feature

### ISSUE THREAD

**Issue by MuhammadKotb** [dotnet/vscode-csharp#5996]
Codelens References are still showing even though I disabled the feature, restarted language server and restarted vscode

I switched to v1.26.0 and its working fine

**Comment by adamrybak** [comment]
I too am having this issue.
`csharp.referencesCodeLens.enabled` has no effect.

**Comment by dibarbet** [comment]
Thanks for the report - this is a duplicate of https://github.com/dotnet/vscode-csharp/issues/5809

Downgrading is absolutely valid, alternatively you can set the `dotnet.server.useOmnisharp` flag to true to get the O# experience back on the latest version of the extension
