### ISSUE TITLE
Roslyn Analyzer works even though I disabled It

### ISSUE THREAD

**Issue by MuhammadKotb** [dotnet/vscode-csharp#5998]
I don't like analyzing my code while Editing So I Disabled the Roslyn Analyzer through  ```Enable support for roslyn analyzers, code fixes and rulesets``` setting

But It still works even after restarting language server and restarting vscode

I switched to version v1.26.0 and Everything is working fine

**Comment by dibarbet** [comment]
This is a side effect of switching to the new roslyn based language server as a default in the latest version of the extension.  For now as workaround you can either downgrade or set the `dotnet.server.useOmnisharp` flag to get back the old behavior.

This is an option we should consider in the new roslyn based language server as well
cc @mavasani

**Comment by MuhammadKotb** [comment]
I upgraded to the latest version and set ```dotnet.server.useOmnisharp``` to ```true``` and restarted vscode but unfortunately the behavior did not change

**Comment by dibarbet** [comment]
Hmm that's definitely unexpected.  Mind sharing your C# / Omnisharp logs from the output window when you have the 'dotnet.server.useOmnisharp' setting checked?

**Comment by MuhammadKotb** [comment]
from c# output

**Comment by dibarbet** [comment]
Ah gotcha.  When the devkit extension is installed, the `dotnet.server.useOmnisharp` option is ignored - this is because devkit requires that the C# extension is launched with the new Roslyn LSP based server.  

In order to use the `dotnet.server.useOmnisharp` flag, C# devkit needs to be uninstalled or disabled.

**Comment by MuhammadKotb** [comment]
Is there any chance to fix it ?

**Comment by tommyvct** [comment]
I have the same behaviour, but from the C# output log it will stuck at `Starting server...` indefinitely.

**Comment by tommyvct** [comment]
I want to use the IntelliCode extension but it depends on the C# Dev Kit, which will enforce the use of Roslyn. But it's so broken that the language server can't even be started. 

I'm on openSUSE Tumbleweed with .NET 7.

**Comment by vladkor-alt** [comment]
> Hmm that's definitely unexpected. Mind sharing your C# / Omnisharp logs from the output window when you have the 'dotnet.server.useOmnisharp' setting checked?

Really? Unexpected? Considering latest few releases this kind of stuff becomes rather greatly expected. "Oh, look, they released a new version of C# extension! LET'S SEE WHAT DID THEY FUCK UP THIS TIME, SHALL WE?"
