### ISSUE TITLE
Cannot run tests

### ISSUE THREAD

**Issue by mauve** [dotnet/vscode-csharp#6007]
Type: <b>Bug</b>

## Issue Description ##
When running a test from Test Explorer, an error message `An error occurred attempting to run tests: Error: The given key '/home/mikael/repos/api/tests/Api.Backend.IntegrationTests/bin/Debug/net7.0/Api.Backend.IntegrationTests.dll' was not present in the dictionary.` is shown.

## Steps to Reproduce ##
1. open solution
2. build solution
3. tests are automatically discovered
4. press "run test" either in test explorer or in the overlay in the editor

## Expected Behavior ##
Test runs

## Actual Behavior ##
Error message is shown:

```
An error occurred attempting to run tests: Error: The given key '/home/mikael/repos/api/tests/Api.Backend.IntegrationTests/bin/Debug/net7.0/Api.Backend.IntegrationTests.dll' was not present in the dictionary.
```

### C# log ###
<details>Post the output from Output-->C# here</details>

### C# LSP Trace Logs ###
There are no interesting logs in the Trace output, however the Extension Host (Remote) has the following error:

```
2023-08-03 08:12:34.484 [error] Error: The given key '/home/mikael/repos/api/tests/Api.Backend.IntegrationTests/bin/Debug/net7.0/Api.Backend.IntegrationTests.dll' was not present in the dictionary.
	at /home/mikael/.vscode-server/extensions/ms-dotnettools.csdevkit-0.4.2-linux-x64/dist/extension.js:2:805420
	at re (/home/mikael/.vscode-server/extensions/ms-dotnettools.csdevkit-0.4.2-linux-x64/dist/extension.js:2:805714)
	at /home/mikael/.vscode-server/extensions/ms-dotnettools.csdevkit-0.4.2-linux-x64/dist/extension.js:2:800498
	at Immediate.<anonymous> (/home/mikael/.vscode-server/extensions/ms-dotnettools.csdevkit-0.4.2-linux-x64/dist/extension.js:2:800518)
	at processImmediate (node:internal/timers:466:21)
```

## Environment information ##

**VSCode version**: 1.80.2
**C# Extension**: 2.0.320
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>

Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 7.0.9 [/home/mikael/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.9/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/lib/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|azure-account|ms-vscode|0.11.5|ms-vscode.azure-account-0.11.5|
|azure-pipelines|ms-azure-devops|1.208.0|ms-azure-devops.azure-pipelines-1.208.0|
|csdevkit|ms-dotnettools|0.4.2|ms-dotnettools.csdevkit-0.4.2-linux-x64|
|csharp|ms-dotnettools|2.0.320|ms-dotnettools.csharp-2.0.320-linux-x64|
|dotnet-test-explorer|formulahendry|0.7.8|formulahendry.dotnet-test-explorer-0.7.8|
|EditorConfig|EditorConfig|0.16.4|editorconfig.editorconfig-0.16.4|
|html-preview-vscode|george-alisson|0.2.5|george-alisson.html-preview-vscode-0.2.5|
|prettier-vscode|esbenp|10.1.0|esbenp.prettier-vscode-10.1.0|
|rest-client|humao|0.25.1|humao.rest-client-0.25.1|
|terraform|hashicorp|2.27.1|hashicorp.terraform-2.27.1-linux-x64|
|vscode-azurefunctions|ms-azuretools|1.12.2|ms-azuretools.vscode-azurefunctions-1.12.2|
|vscode-azureresourcegroups|ms-azuretools|0.7.5|ms-azuretools.vscode-azureresourcegroups-0.7.5|
|vscode-dotnet-runtime|ms-dotnettools|1.6.0|ms-dotnettools.vscode-dotnet-runtime-1.6.0|
|vscode-gitweblinks|reduckted|2.9.2|reduckted.vscode-gitweblinks-2.9.2|
|vscodeintellicode-csharp|ms-dotnettools|0.1.26|ms-dotnettools.vscodeintellicode-csharp-0.1.26-linux-x64|;

</details>

Extension version: 2.0.320
VS Code version: Code 1.80.2 (2ccd690cbff1569e4a83d7c43d45101f817401dc, 2023-07-27T20:40:28.909Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (7.46GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/mikael/repos/api --remote=wsl+Ubuntu --crash-reporter-id efe51cbf-e401-4ba4-be5e-28983a805951|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|Memory (System)|15.54GB (11.15GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by dibarbet** [comment]
This looks like a bug on the devkit side, transferring over to https://github.com/microsoft/vscode-dotnettools/issues/316
