### ISSUE TITLE
New version tries to download .NET 7 (even though it's already installed) and fails

### ISSUE THREAD

**Issue by Santorayo3** [dotnet/vscode-csharp#6009]
After updating the extension to the newest version a download is immediatly started for .NET 7.
This download never finishes and the extension doesn't work anymore.

I have manually installed .NET 7, but that didn't help. Only way to use the extension seems to go back to an older version.

Not living in China, but in Germany. ;)

**Comment by timheuer** [comment]
Hi @Santorayo3 are you getting dialogs similar to #6004 ?

**Comment by timheuer** [comment]
Hi @Santorayo3 we've been checking with our edge delivery teams and we're just not seeing widespread indicators here. I know it's asking a lot but can you help provide us with more information so our network partners can troubleshoot some more?  I appreciate it.

Instructions:

1) Public IP (visit https://ipinfo.io/)
2) HAR file while the issue occurs
3) MTR (100 count) to "dotnetcli.azureedge.net" (excluding quotations) 
4) Visit/provide us the results from http://wpc.2dcc.edgecastcdn.net/002DCC/n2/
5) Visit/provide us the results from https://tools.vdms.com/
 
We've additionally included steps on how to obtain a HAR/MTR below should the end user require assistance to the ask above. This information would help our team greatly towards our efforts in investigating the report. 
 
Below are the steps for collecting HAR/MTR
*****
HAR file :
Here is a guide from Google support, explaining how to use the developer tools to capture the full log of the interaction.
https://support.google.com/admanager/answer/10358597?hl=en
 
MTR:
Download and install WinMTR: Visit the WinMTR website (https://sourceforge.net/projects/winmtr/) and download the latest version of WinMTR suitable for your operating system.
Launch WinMTR: After installation, open WinMTR from the location where it was installed.
Enter the target destination: In the "Host" field, enter the IP address or domain name of the destination you want to test. For example, you can enter a website URL or an IP address , the domain name portion of the URL of the site where you are seeing 504 errors.
Start the test: Click on the "Start" or "Start/Stop" button to begin the test. WinMTR will start sending packets to the destination and collect data about each network hop along the way.
Copy the data or send a screenshot of the MTR to help us diagnose what server may be returning that code.
*****

**Comment by dibarbet** [comment]
Closing - we've made a number of improvements to both the dotnet resolution and runtime download of dotnet since this was filed.  If you're still having issues on the latest version of the extension, please file a *new* issue.
