### ISSUE TITLE
csharp.referencesCodeLens.enabled DOESN'T WORK!!!! FIX IT ASAP!!!!!

### ISSUE THREAD

**Issue by vladkor-alt** [dotnet/vscode-csharp#6015]
subj!!!!! FIX IT!!!!!! NOW!!!!!!!!

**Comment by KnorpelSenf** [comment]
relax and install 1.x

**Comment by Kidsunbo** [comment]
Just downgrade to previous version will fix the issue. But anyway, I switch to Rider.

**Comment by dibarbet** [comment]
Duplicate of https://github.com/dotnet/vscode-csharp/issues/5809
