### ISSUE TITLE
works partially on Remote linux machine

### ISSUE THREAD

**Issue by yanivsag** [dotnet/vscode-csharp#6017]
## Issue Description ##
extension doesn't work on dotnet project on Remote linux machine

## Steps to Reproduce ##
with v2 extension - go to test project and try to run tests from the code (Run Test in Context)

## Expected Behavior ##
menu item appers on right click
## Actual Behavior ##
Item is missing 
### C# log ###
<details>Post the output from Output-->C# here</details>

### C# LSP Trace Logs ###
<details>Post the output from Output-->C# LSP Trace Logs here.  Requires `dotnet.server.trace` to be set to `Trace`</details>

## Environment information ##

**VSCode version**: 1.80.2
**C# Extension**: 2.0.320
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.306
 Commit:    f500069cb7

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /snap/dotnet-sdk/216/sdk/7.0.306/

Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  7.0.306 [/snap/dotnet-sdk/216/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.9 [/snap/dotnet-sdk/216/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.9 [/snap/dotnet-sdk/216/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|azure-account|ms-vscode|0.11.5|ms-vscode.azure-account-0.11.5|
|azurecli|ms-vscode|0.5.0|ms-vscode.azurecli-0.5.0|
|cadl-vscode|Microsoft|0.38.0|microsoft.cadl-vscode-0.38.0|
|copilot|GitHub|1.100.307|github.copilot-1.100.307|
|copilot-chat|GitHub|0.5.2023071302|github.copilot-chat-0.5.2023071302|
|csdevkit|ms-dotnettools|0.4.2|ms-dotnettools.csdevkit-0.4.2-linux-x64|
|csharp|ms-dotnettools|2.0.320|ms-dotnettools.csharp-2.0.320-linux-x64|
|dotnet-interactive-vscode|ms-dotnettools|1.0.4313020|ms-dotnettools.dotnet-interactive-vscode-1.0.4313020|
|git-graph|mhutchie|1.30.0|mhutchie.git-graph-1.30.0|
|githistory|donjayamanne|0.6.20|donjayamanne.githistory-0.6.20|
|go|golang|0.39.1|golang.go-0.39.1|
|isort|ms-python|2023.10.1|ms-python.isort-2023.10.1|
|jupyter|ms-toolsai|2023.6.1101941928|ms-toolsai.jupyter-2023.6.1101941928-linux-x64|
|jupyter-renderers|ms-toolsai|1.0.17|ms-toolsai.jupyter-renderers-1.0.17|
|mono-debug|ms-vscode|0.16.3|ms-vscode.mono-debug-0.16.3|
|open-in-azure-devops-v2|AnkitSharma|0.0.2|ankitsharma.open-in-azure-devops-v2-0.0.2|
|powershell|ms-vscode|2023.6.0|ms-vscode.powershell-2023.6.0|
|python|ms-python|2023.12.0|ms-python.python-2023.12.0|
|rust-analyzer|rust-lang|0.3.1607|rust-lang.rust-analyzer-0.3.1607-linux-x64|
|vscode-bicep|ms-azuretools|0.20.4|ms-azuretools.vscode-bicep-0.20.4|
|vscode-docker|ms-azuretools|1.26.0|ms-azuretools.vscode-docker-1.26.0|
|vscode-dotnet-runtime|ms-dotnettools|1.6.0|ms-dotnettools.vscode-dotnet-runtime-1.6.0|
|vscode-guid|heaths|1.7.0|heaths.vscode-guid-1.7.0|
|vscode-jupyter-cell-tags|ms-toolsai|0.1.8|ms-toolsai.vscode-jupyter-cell-tags-0.1.8|
|vscode-jupyter-slideshow|ms-toolsai|0.1.5|ms-toolsai.vscode-jupyter-slideshow-0.1.5|
|vscode-kubernetes-tools|ms-kubernetes-tools|1.3.13|ms-kubernetes-tools.vscode-kubernetes-tools-1.3.13|
|vscode-nuget-package-manager|jmrog|1.1.6|jmrog.vscode-nuget-package-manager-1.1.6|
|vscode-pylance|ms-python|2023.8.10|ms-python.vscode-pylance-2023.8.10|
|vscode-scp|aminkira|0.0.23|aminkira.vscode-scp-0.0.23|
|vscode-yaml|redhat|1.14.0|redhat.vscode-yaml-1.14.0|
|vscodeintellicode-csharp|ms-dotnettools|0.1.26|ms-dotnettools.vscodeintellicode-csharp-0.1.26-linux-x64|;

</details>

**Comment by GlacierFox** [comment]
Yeah same for me on a remote Linux container. I rolled back to the previous version and it seems to be fine.

**Comment by jblam** [comment]
Extension fails to activate at all for me. Says it refuses to start because of a dependency on .NET Installer for Extension Authors, which won't install because "it prefers not to run". C# extension refuses to start even if Use Omnisharp is enabled.

Version 1.x still works.

**Comment by dibarbet** [comment]
We've made a number of changes around extension initialization, dotnet resolution, and project loading since this issue was filed.  All of those could cause problems with similar symptoms to this issue.

If you're still encountering issues with the extension on remote development, please file a *new* issue with the C# output window logs collect when the `dotnet.server.trace` setting is set to `Trace`.

Thanks!
