### ISSUE TITLE
Problems Info dissapeared 

### ISSUE THREAD

**Issue by AleksandarDevic** [dotnet/vscode-csharp#6018]
## Environment data
.NET SDK:
 Version:   7.0.306
 Commit:    f500069cb7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.306\

Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  6.0.402 [C:\Program Files\dotnet\sdk]
  7.0.102 [C:\Program Files\dotnet\sdk]
  7.0.306 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]
VS Code version:
code --version
1.80.2
2ccd690cbff1569e4a83d7c43d45101f817401dc
x64
C# Extension version:
v2.0.320

## Steps to reproduce
Install the latest version of the C# extension.

## Expected  behavior
![Screenshot 2023-08-03 095513-VSCode-OldVersionOfExtension](https://github.com/dotnet/vscode-csharp/assets/43075620/7b90b967-ee41-465e-9c0d-b70416f05e8a)

## Actual behavior
![image](https://github.com/dotnet/vscode-csharp/assets/43075620/24c2e996-0928-4d51-8767-074755d93125)

## Additional context
Maybe a new major version of C# Extension which uses LSP raised this, but not sure.

Any workaround to fix this issue?

**Comment by AleksandarDevic** [comment]
For me resolved with (F1/CTRL+SHIFT+P) => .NET: Restart Language Server.

**Comment by AleksandarDevic** [comment]
Hi, @dibarbet thank you for the fast response :-) 

this is C# output(With Trace level): 

Dotnet path: c:\Users\aleksandar\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.9\dotnet.exe
Activating C# standalone...
Starting server at c:\Users\aleksandar\.vscode\extensions\ms-dotnettools.csharp-2.0.320-win32-x64\.roslyn\Microsoft.CodeAnalysis.LanguageServer.exe
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\aleksandar\.vscode\extensions\ms-dotnettools.csharp-2.0.320-win32-x64\.roslyn\Microsoft.CodeAnalysis.AnalyzerUtilities.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\aleksandar\.vscode\extensions\ms-dotnettools.csharp-2.0.320-win32-x64\.roslyn\Microsoft.CodeAnalysis.CSharp.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\aleksandar\.vscode\extensions\ms-dotnettools.csharp-2.0.320-win32-x64\.roslyn\Microsoft.CodeAnalysis.CSharp.Features.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\aleksandar\.vscode\extensions\ms-dotnettools.csharp-2.0.320-win32-x64\.roslyn\Microsoft.CodeAnalysis.CSharp.Workspaces.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\aleksandar\.vscode\extensions\ms-dotnettools.csharp-2.0.320-win32-x64\.roslyn\Microsoft.CodeAnalysis.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\aleksandar\.vscode\extensions\ms-dotnettools.csharp-2.0.320-win32-x64\.roslyn\Microsoft.CodeAnalysis.Elfie.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\aleksandar\.vscode\extensions\ms-dotnettools.csharp-2.0.320-win32-x64\.roslyn\Microsoft.CodeAnalysis.Features.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\aleksandar\.vscode\extensions\ms-dotnettools.csharp-2.0.320-win32-x64\.roslyn\Microsoft.CodeAnalysis.Razor.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\aleksandar\.vscode\extensions\ms-dotnettools.csharp-2.0.320-win32-x64\.roslyn\Microsoft.CodeAnalysis.Remote.Workspaces.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\aleksandar\.vscode\extensions\ms-dotnettools.csharp-2.0.320-win32-x64\.roslyn\Microsoft.CodeAnalysis.Scripting.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\aleksandar\.vscode\extensions\ms-dotnettools.csharp-2.0.320-win32-x64\.roslyn\Microsoft.CodeAnalysis.Workspaces.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\aleksandar\.vscode\extensions\ms-dotnettools.csharp-2.0.320-win32-x64\.roslyn\Microsoft.CodeAnalysis.Workspaces.MSBuild.dll added to workspace.
info: LanguageServerHost[0]
      Starting server...
[LanguageServerHost][07:37:16.986][Start]initialize
[LanguageServerHost][07:37:17.063][Start]Initialize
[LanguageServerHost][07:37:17.120][End]Initialize
[LanguageServerHost][07:37:17.180][End]initialize
[LanguageServerHost][07:37:17.187][Start]initialized
[LanguageServerHost][07:37:17.315][End]initialized
[LanguageServerHost][07:37:17.317][Start]textDocument/didOpen
[LanguageServerHost]didOpen for file:///c:/Users/aleksandar/git/private-repos/Skeleton-Project/Skeleton/src/Skeleton.Api/Middleware/ExceptionHandlingMiddleware.cs
[LanguageServerHost][07:37:17.330][End]textDocument/didOpen
[LanguageServerHost]Could not find 'file:///c:/Users/aleksandar/git/private-repos/Skeleton-Project/Skeleton/src/Skeleton.Api/Middleware/ExceptionHandlingMiddleware.cs'.  Searched Host
[LanguageServerHost][07:37:17.420][Start]textDocument/diagnostic
[LanguageServerHost]PublicDocumentPullDiagnosticsHandler(category: ) started getting diagnostics
[LanguageServerHost]previousResults.Length=0
[LanguageServerHost]Processing 1 documents
[LanguageServerHost][07:37:17.444][Start]workspace/diagnostic
[LanguageServerHost]c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Middleware\ExceptionHandlingMiddleware.cs found in workspace MiscellaneousFiles
[LanguageServerHost][07:37:17.447][Start]textDocument/documentSymbol
[LanguageServerHost]c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Middleware\ExceptionHandlingMiddleware.cs found in workspace MiscellaneousFiles
[LanguageServerHost]c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Middleware\ExceptionHandlingMiddleware.cs found in workspace MiscellaneousFiles
[LanguageServerHost]PublicWorkspacePullDiagnosticsHandler(category: ) started getting diagnostics
[LanguageServerHost]c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Middleware\ExceptionHandlingMiddleware.cs found in workspace MiscellaneousFiles
[LanguageServerHost][07:37:17.450][Start]textDocument/codeAction
[LanguageServerHost][07:37:17.451][Start]textDocument/inlayHint
[LanguageServerHost][07:37:17.451][Start]solution/open
[LanguageServerHost]previousResults.Length=0
[LanguageServerHost]Processing 0 documents
[LanguageServerHost]Closing workspace/diagnostics request
[LanguageServerHost]Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.Public.PublicWorkspacePullDiagnosticsHandler finished getting diagnostics
[LanguageServerHost][07:37:17.465][End]workspace/diagnostic
[LanguageServerHost][07:37:17.469][Start]textDocument/semanticTokens/range
[Info  - 9:37:17 PM] [LanguageServerProjectSystem]Loaded MSBuild at C:\Program Files\dotnet\sdk\7.0.306
[Info  - 9:37:17 PM] [LanguageServerProjectSystem]Loading c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\Skeleton.sln...
[LanguageServerHost][07:37:17.484][End]textDocument/inlayHint
[LanguageServerHost]Found 0 diagnostics for DocumentDiagnosticSource: c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Middleware\ExceptionHandlingMiddleware.cs in Miscellaneous Files
[LanguageServerHost]Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.Public.PublicDocumentPullDiagnosticsHandler finished getting diagnostics
[LanguageServerHost][07:37:17.602][End]textDocument/diagnostic
[LanguageServerHost]c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Middleware\ExceptionHandlingMiddleware.cs found in workspace MiscellaneousFiles
[LanguageServerHost][07:37:17.738][Start]textDocument/foldingRange
[LanguageServerHost][07:37:17.803][End]textDocument/foldingRange
[LanguageServerHost]c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Middleware\ExceptionHandlingMiddleware.cs found in workspace MiscellaneousFiles
[LanguageServerHost][07:37:17.810][Start]textDocument/codeLens
[LanguageServerHost][07:37:17.848][End]textDocument/codeLens
[LanguageServerHost][07:37:17.871][End]textDocument/codeAction
[LanguageServerHost]c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Middleware\ExceptionHandlingMiddleware.cs found in workspace MiscellaneousFiles
[LanguageServerHost][07:37:17.907][Start]textDocument/inlayHint
[LanguageServerHost][07:37:17.908][End]textDocument/inlayHint
[LanguageServerHost]c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Middleware\ExceptionHandlingMiddleware.cs found in workspace MiscellaneousFiles
[LanguageServerHost][07:37:18.012][Start]textDocument/semanticTokens/range
[LanguageServerHost][07:37:18.066][End]textDocument/documentSymbol
[LanguageServerHost]c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Middleware\ExceptionHandlingMiddleware.cs found in workspace MiscellaneousFiles
[LanguageServerHost][07:37:18.249][Start]codeLens/resolve
[LanguageServerHost]c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Middleware\ExceptionHandlingMiddleware.cs found in workspace MiscellaneousFiles
[LanguageServerHost][07:37:18.252][Start]codeLens/resolve
[LanguageServerHost][07:37:18.426][End]textDocument/semanticTokens/range
[LanguageServerHost][07:37:18.430][End]textDocument/semanticTokens/range
[LanguageServerHost][07:37:18.522][End]codeLens/resolve
[LanguageServerHost][07:37:18.535][End]codeLens/resolve
[Info  - 9:37:18 PM] [LanguageServerProjectSystem]Successfully completed load of c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Skeleton.Api.csproj
[Info  - 9:37:18 PM] [LanguageServerProjectSystem]Successfully completed load of c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Application\Skeleton.Application.csproj
[Info  - 9:37:18 PM] [LanguageServerProjectSystem]Successfully completed load of c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Domain\Skeleton.Domain.csproj
[Info  - 9:37:18 PM] [LanguageServerProjectSystem]Completed (re)load of all projects in 00:00:01.2108785
[LanguageServerHost][07:37:18.869][End]solution/open
[LanguageServerHost][07:37:18.873][Start]workspace/debugConfiguration
[LanguageServerHost][07:37:18.880][End]workspace/debugConfiguration
[LanguageServerHost]c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Middleware\ExceptionHandlingMiddleware.cs found in workspace Host
[LanguageServerHost][07:37:19.329][Start]textDocument/diagnostic
[LanguageServerHost]PublicDocumentPullDiagnosticsHandler(category: ) started getting diagnostics
[LanguageServerHost]previousResults.Length=1
[LanguageServerHost]Processing 1 documents
[LanguageServerHost][07:37:19.472][Start]workspace/diagnostic
[LanguageServerHost]PublicWorkspacePullDiagnosticsHandler(category: ) started getting diagnostics
[LanguageServerHost]previousResults.Length=0
[LanguageServerHost]Processing 0 documents
[LanguageServerHost]Closing workspace/diagnostics request
[LanguageServerHost]Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.Public.PublicWorkspacePullDiagnosticsHandler finished getting diagnostics
[LanguageServerHost][07:37:19.475][End]workspace/diagnostic
[LanguageServerHost]c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Middleware\ExceptionHandlingMiddleware.cs found in workspace Host
[LanguageServerHost][07:37:19.805][Start]textDocument/codeLens
[LanguageServerHost][07:37:19.806][End]textDocument/codeLens
[LanguageServerHost]c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Middleware\ExceptionHandlingMiddleware.cs found in workspace Host
[LanguageServerHost][07:37:20.200][Start]codeLens/resolve
[LanguageServerHost]c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Middleware\ExceptionHandlingMiddleware.cs found in workspace Host
[LanguageServerHost][07:37:20.200][Start]codeLens/resolve
[LanguageServerHost][07:37:20.245][End]codeLens/resolve
[LanguageServerHost][07:37:20.278][End]codeLens/resolve
[LanguageServerHost]Found 7 diagnostics for DocumentDiagnosticSource: c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Middleware\ExceptionHandlingMiddleware.cs in c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Skeleton.Api.csproj ($net7.0)
[LanguageServerHost]Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.Public.PublicDocumentPullDiagnosticsHandler finished getting diagnostics
[LanguageServerHost][07:37:20.790][End]textDocument/diagnostic
[LanguageServerHost]c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Middleware\ExceptionHandlingMiddleware.cs found in workspace Host
[LanguageServerHost][07:37:21.048][Start]textDocument/codeAction
[LanguageServerHost][07:37:21.074][End]textDocument/codeAction
[LanguageServerHost]c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Middleware\ExceptionHandlingMiddleware.cs found in workspace Host
[LanguageServerHost][07:37:21.336][Start]textDocument/diagnostic
[LanguageServerHost]PublicDocumentPullDiagnosticsHandler(category: ) started getting diagnostics
[LanguageServerHost]previousResults.Length=1
[LanguageServerHost]Processing 1 documents
[LanguageServerHost]Diagnostics were unchanged for DocumentDiagnosticSource: c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Middleware\ExceptionHandlingMiddleware.cs in c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Skeleton.Api.csproj ($net7.0)
[LanguageServerHost]Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.Public.PublicDocumentPullDiagnosticsHandler finished getting diagnostics
[LanguageServerHost][07:37:21.361][End]textDocument/diagnostic
[LanguageServerHost][07:37:21.492][Start]workspace/diagnostic
[LanguageServerHost]PublicWorkspacePullDiagnosticsHandler(category: ) started getting diagnostics
[LanguageServerHost]previousResults.Length=0
[LanguageServerHost]Processing 0 documents
[LanguageServerHost]c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Middleware\ExceptionHandlingMiddleware.cs found in workspace Host
[LanguageServerHost][07:37:25.828][Start]textDocument/diagnostic
[LanguageServerHost]PublicDocumentPullDiagnosticsHandler(category: ) started getting diagnostics
[LanguageServerHost]previousResults.Length=1
[LanguageServerHost]Processing 1 documents
[LanguageServerHost]Diagnostics were unchanged for DocumentDiagnosticSource: c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Middleware\ExceptionHandlingMiddleware.cs in c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Skeleton.Api.csproj ($net7.0)
[LanguageServerHost]Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.Public.PublicDocumentPullDiagnosticsHandler finished getting diagnostics
[LanguageServerHost][07:37:25.829][End]textDocument/diagnostic

But now everything seems working well.

**Comment by dibarbet** [comment]
> [Info - 9:37:18 PM] [LanguageServerProjectSystem]Completed (re)load of all projects in 00:00:01.2108785
>...
> But now everything seems working well.

From logs it does appear as though the project is loading as I would expect now.  It sounds things are working now so I'll close this issue.  However if you encounter issues again, absolutely feel free to re-open this.
