### ISSUE TITLE
Cannot read properties of null (reading 'command')

### ISSUE THREAD

**Issue by CoderJason123** [dotnet/vscode-csharp#6020]
Steps to Reproduce:
1. Create a blazor hosted web assembly app.
2. Try to run it.
3. 
This error message pops up when you try to run the app, the browser will no longer open. I've disabled all extensions, cleared any caches from vs code, reinstalled vs code, added all extensions back. I can successfully run console apps, but i can't start and debug a blazor wasm app.
If there's a way to find the source of this message, that might help. I've looked through every single log, in order to try to provide further information.  I can launch this as a console, but I want debug support and launch as blazorwasm.

Assistance appreciated.

Version: 1.81.0
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:38:28.722Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0

**Comment by CoderJason123** [comment]
Sure enough ... after many hours on this issue, thinking about the error message, I added  "browser": "chrome" to my launch.json and it works successfully.  I don't know if this has changed / updated, but none of my launches ever had this.  

I'm going to leave this here for anyone else running into this frustrating issue.  I'd still love to know how to get better information next time to hint at the issue or where to look.

**Comment by ahanusa** [comment]
> Sure enough ... after many hours on this issue, thinking about the error message, I added "browser": "chrome" to my launch.json and it works successfully. I don't know if this has changed / updated, but none of my launches ever had this.
> 
> I'm going to leave this here for anyone else running into this frustrating issue. I'd still love to know how to get better information next time to hint at the issue or where to look.

This was super annoying, I'm thankful you figured out this issue and shared with others as I wasted a weekend on this.
