### ISSUE TITLE
I cannot install C# extension

### ISSUE THREAD

**Issue by soroshsabz** [dotnet/vscode-csharp#6025]
ITNOA

## Issue Description ##

I could not install C# extension

## Steps to Reproduce ##
1. search C# extension in extensions
2. install extension (install successfully)
3. I close and reopen vscode
4. C# extension does not install (install icon display again)

## Expected Behavior ##
C# extension must be remain installed in each open and close vscode

## Actual Behavior ##
C# extension does not install correctly, after close and reopen vscode, C# extension is gone

## Logs ##

I do not know how to opened by run command.

[sharedprocess.zip](https://github.com/dotnet/vscode-csharp/files/12256009/sharedprocess.zip)

        
### C# log ###
<details>Dotnet path: c:\Users\sooro\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.9\dotnet.exe
Activating C# standalone...
info: LanguageServerHost[0]
      Starting server...
[Info  - 4:07:34 AM] [LanguageServerProjectSystem]Loaded MSBuild at C:\Program Files\dotnet\sdk\7.0.306
[Info  - 4:07:34 AM] [LanguageServerProjectSystem]Loading d:\Source\Repos\Resa\IpTables.Api\BSN.IpTables.Api.sln...
[Info  - 4:07:36 AM] [LanguageServerProjectSystem]Successfully completed load of d:\Source\Repos\Resa\IpTables.Api\Test\SystemTests\BSN.IpTables.Data.SystemTest\BSN.IpTables.Data.SystemTest.csproj
[Info  - 4:07:36 AM] [LanguageServerProjectSystem]Successfully completed load of d:\Source\Repos\Resa\IpTables.Api\Source\BSN.IpTables.Domain\BSN.IpTables.Domain.csproj
[Info  - 4:07:36 AM] [LanguageServerProjectSystem]Successfully completed load of d:\Source\Repos\Resa\IpTables.Api\Test\SystemTests\BSN.IpTables.Api.SystemTest\BSN.IpTables.Api.SystemTest.csproj
[Info  - 4:07:36 AM] [LanguageServerProjectSystem]Successfully completed load of d:\Source\Repos\Resa\IpTables.Api\Source\BSN.IpTables.Data\BSN.IpTables.Data.csproj
[Info  - 4:07:36 AM] [LanguageServerProjectSystem]Successfully completed load of d:\Source\Repos\Resa\IpTables.Api\Source\BSN.IpTables.Api\BSN.IpTables.Api.csproj
[Info  - 4:07:37 AM] [LanguageServerProjectSystem]Successfully completed load of d:\Source\Repos\Resa\IpTables.Api\Test\UnitTests\BSN.IpTables.Api.Tests\BSN.IpTables.Api.Tests.csproj
[Info  - 4:07:37 AM] [LanguageServerProjectSystem]Completed (re)load of all projects in 00:00:02.2906669
</details>

### C# LSP Trace Logs ###
<details>Extension vscode.bat does not contribute csharpExtensionLoadPaths
Extension vscode.clojure does not contribute csharpExtensionLoadPaths
Extension vscode.coffeescript does not contribute csharpExtensionLoadPaths
Extension vscode.configuration-editing does not contribute csharpExtensionLoadPaths
Extension vscode.cpp does not contribute csharpExtensionLoadPaths
Extension vscode.csharp does not contribute csharpExtensionLoadPaths
Extension vscode.css does not contribute csharpExtensionLoadPaths
Extension vscode.css-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.dart does not contribute csharpExtensionLoadPaths
Extension vscode.debug-auto-launch does not contribute csharpExtensionLoadPaths
Extension vscode.debug-server-ready does not contribute csharpExtensionLoadPaths
Extension vscode.diff does not contribute csharpExtensionLoadPaths
Extension vscode.docker does not contribute csharpExtensionLoadPaths
Extension vscode.emmet does not contribute csharpExtensionLoadPaths
Extension vscode.extension-editing does not contribute csharpExtensionLoadPaths
Extension vscode.fsharp does not contribute csharpExtensionLoadPaths
Extension vscode.git does not contribute csharpExtensionLoadPaths
Extension vscode.git-base does not contribute csharpExtensionLoadPaths
Extension vscode.github does not contribute csharpExtensionLoadPaths
Extension vscode.github-authentication does not contribute csharpExtensionLoadPaths
Extension vscode.go does not contribute csharpExtensionLoadPaths
Extension vscode.groovy does not contribute csharpExtensionLoadPaths
Extension vscode.grunt does not contribute csharpExtensionLoadPaths
Extension vscode.gulp does not contribute csharpExtensionLoadPaths
Extension vscode.handlebars does not contribute csharpExtensionLoadPaths
Extension vscode.hlsl does not contribute csharpExtensionLoadPaths
Extension vscode.html does not contribute csharpExtensionLoadPaths
Extension vscode.html-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.ini does not contribute csharpExtensionLoadPaths
Extension vscode.ipynb does not contribute csharpExtensionLoadPaths
Extension vscode.jake does not contribute csharpExtensionLoadPaths
Extension vscode.java does not contribute csharpExtensionLoadPaths
Extension vscode.javascript does not contribute csharpExtensionLoadPaths
Extension vscode.json does not contribute csharpExtensionLoadPaths
Extension vscode.json-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.julia does not contribute csharpExtensionLoadPaths
Extension vscode.latex does not contribute csharpExtensionLoadPaths
Extension vscode.less does not contribute csharpExtensionLoadPaths
Extension vscode.log does not contribute csharpExtensionLoadPaths
Extension vscode.lua does not contribute csharpExtensionLoadPaths
Extension vscode.make does not contribute csharpExtensionLoadPaths
Extension vscode.markdown does not contribute csharpExtensionLoadPaths
Extension vscode.markdown-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.markdown-math does not contribute csharpExtensionLoadPaths
Extension vscode.media-preview does not contribute csharpExtensionLoadPaths
Extension vscode.merge-conflict does not contribute csharpExtensionLoadPaths
Extension vscode.microsoft-authentication does not contribute csharpExtensionLoadPaths
Extension ms-vscode-remote.remote-wsl-recommender does not contribute csharpExtensionLoadPaths
Extension ms-vscode.js-debug does not contribute csharpExtensionLoadPaths
Extension ms-vscode.js-debug-companion does not contribute csharpExtensionLoadPaths
Extension ms-vscode.vscode-js-profile-table does not contribute csharpExtensionLoadPaths
Extension vscode.builtin-notebook-renderers does not contribute csharpExtensionLoadPaths
Extension vscode.npm does not contribute csharpExtensionLoadPaths
Extension vscode.objective-c does not contribute csharpExtensionLoadPaths
Extension vscode.perl does not contribute csharpExtensionLoadPaths
Extension vscode.php does not contribute csharpExtensionLoadPaths
Extension vscode.php-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.powershell does not contribute csharpExtensionLoadPaths
Extension vscode.pug does not contribute csharpExtensionLoadPaths
Extension vscode.python does not contribute csharpExtensionLoadPaths
Extension vscode.r does not contribute csharpExtensionLoadPaths
Extension vscode.razor does not contribute csharpExtensionLoadPaths
Extension vscode.references-view does not contribute csharpExtensionLoadPaths
Extension vscode.restructuredtext does not contribute csharpExtensionLoadPaths
Extension vscode.ruby does not contribute csharpExtensionLoadPaths
Extension vscode.rust does not contribute csharpExtensionLoadPaths
Extension vscode.scss does not contribute csharpExtensionLoadPaths
Extension vscode.search-result does not contribute csharpExtensionLoadPaths
Extension vscode.shaderlab does not contribute csharpExtensionLoadPaths
Extension vscode.shellscript does not contribute csharpExtensionLoadPaths
Extension vscode.simple-browser does not contribute csharpExtensionLoadPaths
Extension vscode.sql does not contribute csharpExtensionLoadPaths
Extension vscode.swift does not contribute csharpExtensionLoadPaths
Extension vscode.theme-abyss does not contribute csharpExtensionLoadPaths
Extension vscode.theme-defaults does not contribute csharpExtensionLoadPaths
Extension vscode.theme-kimbie-dark does not contribute csharpExtensionLoadPaths
Extension vscode.theme-monokai does not contribute csharpExtensionLoadPaths
Extension vscode.theme-monokai-dimmed does not contribute csharpExtensionLoadPaths
Extension vscode.theme-quietlight does not contribute csharpExtensionLoadPaths
Extension vscode.theme-red does not contribute csharpExtensionLoadPaths
Extension vscode.vscode-theme-seti does not contribute csharpExtensionLoadPaths
Extension vscode.theme-solarized-dark does not contribute csharpExtensionLoadPaths
Extension vscode.theme-solarized-light does not contribute csharpExtensionLoadPaths
Extension vscode.theme-tomorrow-night-blue does not contribute csharpExtensionLoadPaths
Extension vscode.typescript does not contribute csharpExtensionLoadPaths
Extension vscode.typescript-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.vb does not contribute csharpExtensionLoadPaths
Extension vscode.xml does not contribute csharpExtensionLoadPaths
Extension vscode.yaml does not contribute csharpExtensionLoadPaths
Extension 1dot75cm.RPMSpec does not contribute csharpExtensionLoadPaths
Extension Angular.ng-template does not contribute csharpExtensionLoadPaths
Extension bierner.markdown-mermaid does not contribute csharpExtensionLoadPaths
Extension christian-kohler.npm-intellisense does not contribute csharpExtensionLoadPaths
Extension christian-kohler.path-intellisense does not contribute csharpExtensionLoadPaths
Extension coolbear.systemd-unit-file does not contribute csharpExtensionLoadPaths
Extension cschlosser.doxdocgen does not contribute csharpExtensionLoadPaths
Extension DavidAnson.vscode-markdownlint does not contribute csharpExtensionLoadPaths
Extension dbaeumer.vscode-eslint does not contribute csharpExtensionLoadPaths
Extension DominicVonk.vscode-resx-editor does not contribute csharpExtensionLoadPaths
Extension esbenp.prettier-vscode does not contribute csharpExtensionLoadPaths
Extension fabiospampinato.vscode-install-vsix does not contribute csharpExtensionLoadPaths
Extension GitHub.codespaces does not contribute csharpExtensionLoadPaths
Extension GitHub.remotehub does not contribute csharpExtensionLoadPaths
Extension github.vscode-github-actions does not contribute csharpExtensionLoadPaths
Extension GitHub.vscode-pull-request-github does not contribute csharpExtensionLoadPaths
Extension golang.go does not contribute csharpExtensionLoadPaths
Extension GrapeCity.gc-excelviewer does not contribute csharpExtensionLoadPaths
Extension hbenl.vscode-mocha-test-adapter does not contribute csharpExtensionLoadPaths
Extension hbenl.vscode-test-explorer does not contribute csharpExtensionLoadPaths
Extension IBM.codewind-java-profiler does not contribute csharpExtensionLoadPaths
Extension jeff-hykin.better-cpp-syntax does not contribute csharpExtensionLoadPaths
Extension L13RARY.l13-diff does not contribute csharpExtensionLoadPaths
Extension miconda.kamailio-syntax does not contribute csharpExtensionLoadPaths
Extension mindaro-dev.file-downloader does not contribute csharpExtensionLoadPaths
Extension ms-azuretools.vscode-docker does not contribute csharpExtensionLoadPaths
Extension ms-dotnettools.csharp does not contribute csharpExtensionLoadPaths
Extension ms-dotnettools.dotnet-interactive-vscode does not contribute csharpExtensionLoadPaths
Extension ms-dotnettools.vscode-dotnet-runtime does not contribute csharpExtensionLoadPaths
Extension ms-mssql.data-workspace-vscode does not contribute csharpExtensionLoadPaths
Extension ms-mssql.mssql does not contribute csharpExtensionLoadPaths
Extension ms-mssql.sql-bindings-vscode does not contribute csharpExtensionLoadPaths
Extension ms-mssql.sql-database-projects-vscode does not contribute csharpExtensionLoadPaths
Extension ms-python.isort does not contribute csharpExtensionLoadPaths
Extension ms-python.python does not contribute csharpExtensionLoadPaths
Extension ms-python.vscode-pylance does not contribute csharpExtensionLoadPaths
Extension ms-toolsai.jupyter does not contribute csharpExtensionLoadPaths
Extension ms-toolsai.jupyter-keymap does not contribute csharpExtensionLoadPaths
Extension ms-toolsai.jupyter-renderers does not contribute csharpExtensionLoadPaths
Extension ms-toolsai.vscode-jupyter-cell-tags does not contribute csharpExtensionLoadPaths
Extension ms-toolsai.vscode-jupyter-slideshow does not contribute csharpExtensionLoadPaths
Extension ms-vscode-remote.remote-containers does not contribute csharpExtensionLoadPaths
Extension ms-vscode-remote.remote-ssh does not contribute csharpExtensionLoadPaths
Extension ms-vscode-remote.remote-ssh-edit does not contribute csharpExtensionLoadPaths
Extension ms-vscode-remote.remote-wsl does not contribute csharpExtensionLoadPaths
Extension ms-vscode.azure-repos does not contribute csharpExtensionLoadPaths
Extension ms-vscode.cmake-tools does not contribute csharpExtensionLoadPaths
Extension ms-vscode.cpptools does not contribute csharpExtensionLoadPaths
Extension ms-vscode.cpptools-extension-pack does not contribute csharpExtensionLoadPaths
Extension ms-vscode.cpptools-themes does not contribute csharpExtensionLoadPaths
Extension ms-vscode.powershell does not contribute csharpExtensionLoadPaths
Extension ms-vscode.remote-explorer does not contribute csharpExtensionLoadPaths
Extension ms-vscode.remote-repositories does not contribute csharpExtensionLoadPaths
Extension ms-vscode.test-adapter-converter does not contribute csharpExtensionLoadPaths
Extension ms-vsliveshare.vsliveshare does not contribute csharpExtensionLoadPaths
Extension ms-vsliveshare.vsliveshare-pack does not contribute csharpExtensionLoadPaths
Extension octref.vetur does not contribute csharpExtensionLoadPaths
Extension pedro-w.tmlanguage does not contribute csharpExtensionLoadPaths
Extension pspester.pester-test does not contribute csharpExtensionLoadPaths
Extension quantum.quantum-devkit-vscode does not contribute csharpExtensionLoadPaths
Extension rebornix.ruby does not contribute csharpExtensionLoadPaths
Extension redhat.ansible does not contribute csharpExtensionLoadPaths
Extension redhat.java does not contribute csharpExtensionLoadPaths
Extension redhat.vscode-commons does not contribute csharpExtensionLoadPaths
Extension redhat.vscode-extension-bpmn-editor does not contribute csharpExtensionLoadPaths
Extension redhat.vscode-yaml does not contribute csharpExtensionLoadPaths
Extension ritwickdey.LiveServer does not contribute csharpExtensionLoadPaths
Extension sumneko.lua does not contribute csharpExtensionLoadPaths
Extension timonwong.shellcheck does not contribute csharpExtensionLoadPaths
Extension twxs.cmake does not contribute csharpExtensionLoadPaths
Extension VisualStudioExptTeam.intellicode-api-usage-examples does not contribute csharpExtensionLoadPaths
Extension VisualStudioExptTeam.vscodeintellicode does not contribute csharpExtensionLoadPaths
Extension vscjava.vscode-gradle does not contribute csharpExtensionLoadPaths
Extension vscjava.vscode-java-debug does not contribute csharpExtensionLoadPaths
Extension vscjava.vscode-java-dependency does not contribute csharpExtensionLoadPaths
Extension vscjava.vscode-java-pack does not contribute csharpExtensionLoadPaths
Extension vscjava.vscode-java-test does not contribute csharpExtensionLoadPaths
Extension vscjava.vscode-maven does not contribute csharpExtensionLoadPaths
Extension vscjava.vscode-spring-initializr does not contribute csharpExtensionLoadPaths
Extension vscode-icons-team.vscode-icons does not contribute csharpExtensionLoadPaths
Extension vscodevim.vim does not contribute csharpExtensionLoadPaths
Extension Vue.volar does not contribute csharpExtensionLoadPaths
Extension wingrunr21.vscode-ruby does not contribute csharpExtensionLoadPaths
Extension zhouronghui.propertylist does not contribute csharpExtensionLoadPaths</details>

## Environment information ##

**VSCode version**: 1.81.0
**C# Extension**: 2.0.320

**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>

Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 7.0.9 [c:\Users\sooro\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.9\shared\Microsoft.NETCore.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|ansible|redhat|2.6.92|redhat.ansible-2.6.92|
|azure-repos|ms-vscode|0.36.0|ms-vscode.azure-repos-0.36.0|
|better-cpp-syntax|jeff-hykin|1.17.2|jeff-hykin.better-cpp-syntax-1.17.2|
|cmake|twxs|0.0.17|twxs.cmake-0.0.17|
|cmake-tools|ms-vscode|1.14.34|ms-vscode.cmake-tools-1.14.34|
|codespaces|GitHub|1.14.14|github.codespaces-1.14.14|
|codewind-java-profiler|IBM|0.9.0|ibm.codewind-java-profiler-0.9.0|
|cpptools|ms-vscode|1.16.3|ms-vscode.cpptools-1.16.3-win32-x64|
|cpptools-extension-pack|ms-vscode|1.3.0|ms-vscode.cpptools-extension-pack-1.3.0|
|cpptools-themes|ms-vscode|2.0.0|ms-vscode.cpptools-themes-2.0.0|
|csharp|ms-dotnettools|2.0.320|ms-dotnettools.csharp-2.0.320-win32-x64|
|data-workspace-vscode|ms-mssql|0.5.0|ms-mssql.data-workspace-vscode-0.5.0|
|dotnet-interactive-vscode|ms-dotnettools|1.0.4403010|ms-dotnettools.dotnet-interactive-vscode-1.0.4403010|
|doxdocgen|cschlosser|1.4.0|cschlosser.doxdocgen-1.4.0|
|file-downloader|mindaro-dev|1.0.12|mindaro-dev.file-downloader-1.0.12|
|gc-excelviewer|GrapeCity|4.2.57|grapecity.gc-excelviewer-4.2.57|
|go|golang|0.39.1|golang.go-0.39.1|
|intellicode-api-usage-examples|VisualStudioExptTeam|0.2.7|visualstudioexptteam.intellicode-api-usage-examples-0.2.7|
|isort|ms-python|2023.10.1|ms-python.isort-2023.10.1|
|java|redhat|1.21.0|redhat.java-1.21.0-win32-x64|
|jupyter|ms-toolsai|2023.7.1002162226|ms-toolsai.jupyter-2023.7.1002162226-win32-x64|
|jupyter-keymap|ms-toolsai|1.1.2|ms-toolsai.jupyter-keymap-1.1.2|
|jupyter-renderers|ms-toolsai|1.0.17|ms-toolsai.jupyter-renderers-1.0.17|
|kamailio-syntax|miconda|1.0.8|miconda.kamailio-syntax-1.0.8|
|l13-diff|L13RARY|1.3.2|l13rary.l13-diff-1.3.2|
|LiveServer|ritwickdey|5.7.9|ritwickdey.liveserver-5.7.9|
|lua|sumneko|3.6.26|sumneko.lua-3.6.26-win32-x64|
|markdown-mermaid|bierner|1.19.0|bierner.markdown-mermaid-1.19.0|
|mssql|ms-mssql|1.20.0|ms-mssql.mssql-1.20.0|
|ng-template|Angular|16.1.4|angular.ng-template-16.1.4|
|npm-intellisense|christian-kohler|1.4.4|christian-kohler.npm-intellisense-1.4.4|
|path-intellisense|christian-kohler|2.8.4|christian-kohler.path-intellisense-2.8.4|
|pester-test|pspester|2023.7.7|pspester.pester-test-2023.7.7|
|powershell|ms-vscode|2023.6.0|ms-vscode.powershell-2023.6.0|
|prettier-vscode|esbenp|10.1.0|esbenp.prettier-vscode-10.1.0|
|propertylist|zhouronghui|0.0.2|zhouronghui.propertylist-0.0.2|
|python|ms-python|2023.14.0|ms-python.python-2023.14.0|
|quantum-devkit-vscode|quantum|0.28.291394|quantum.quantum-devkit-vscode-0.28.291394|
|remote-containers|ms-vscode-remote|0.299.0|ms-vscode-remote.remote-containers-0.299.0|
|remote-explorer|ms-vscode|0.4.1|ms-vscode.remote-explorer-0.4.1|
|remote-repositories|ms-vscode|0.38.1|ms-vscode.remote-repositories-0.38.1|
|remote-ssh|ms-vscode-remote|0.102.0|ms-vscode-remote.remote-ssh-0.102.0|
|remote-ssh-edit|ms-vscode-remote|0.86.0|ms-vscode-remote.remote-ssh-edit-0.86.0|
|remote-wsl|ms-vscode-remote|0.80.2|ms-vscode-remote.remote-wsl-0.80.2|
|remotehub|GitHub|0.60.0|github.remotehub-0.60.0|
|RPMSpec|1dot75cm|0.1.0|1dot75cm.rpmspec-0.1.0|
|ruby|rebornix|0.28.1|rebornix.ruby-0.28.1|
|shellcheck|timonwong|0.33.0|timonwong.shellcheck-0.33.0-win32-x64|
|sql-bindings-vscode|ms-mssql|0.4.0|ms-mssql.sql-bindings-vscode-0.4.0|
|sql-database-projects-vscode|ms-mssql|1.2.0|ms-mssql.sql-database-projects-vscode-1.2.0|
|systemd-unit-file|coolbear|1.0.6|coolbear.systemd-unit-file-1.0.6|
|test-adapter-converter|ms-vscode|0.1.8|ms-vscode.test-adapter-converter-0.1.8|
|tmlanguage|pedro-w|0.13.0|pedro-w.tmlanguage-0.13.0|
|vetur|octref|0.37.3|octref.vetur-0.37.3|
|vim|vscodevim|1.25.2|vscodevim.vim-1.25.2|
|volar|Vue|1.8.8|vue.volar-1.8.8|
|vscode-commons|redhat|0.0.6|redhat.vscode-commons-0.0.6|
|vscode-docker|ms-azuretools|1.26.0|ms-azuretools.vscode-docker-1.26.0|
|vscode-dotnet-runtime|ms-dotnettools|1.6.0|ms-dotnettools.vscode-dotnet-runtime-1.6.0|
|vscode-eslint|dbaeumer|2.4.2|dbaeumer.vscode-eslint-2.4.2|
|vscode-extension-bpmn-editor|redhat|0.26.1|redhat.vscode-extension-bpmn-editor-0.26.1|
|vscode-github-actions|github|0.25.8|github.vscode-github-actions-0.25.8|
|vscode-gradle|vscjava|3.12.7|vscjava.vscode-gradle-3.12.7|
|vscode-icons|vscode-icons-team|12.4.0|vscode-icons-team.vscode-icons-12.4.0|
|vscode-install-vsix|fabiospampinato|1.4.0|fabiospampinato.vscode-install-vsix-1.4.0|
|vscode-java-debug|vscjava|0.53.0|vscjava.vscode-java-debug-0.53.0|
|vscode-java-dependency|vscjava|0.23.0|vscjava.vscode-java-dependency-0.23.0|
|vscode-java-pack|vscjava|0.25.13|vscjava.vscode-java-pack-0.25.13|
|vscode-java-test|vscjava|0.39.0|vscjava.vscode-java-test-0.39.0|
|vscode-jupyter-cell-tags|ms-toolsai|0.1.8|ms-toolsai.vscode-jupyter-cell-tags-0.1.8|
|vscode-jupyter-slideshow|ms-toolsai|0.1.5|ms-toolsai.vscode-jupyter-slideshow-0.1.5|
|vscode-markdownlint|DavidAnson|0.51.0|davidanson.vscode-markdownlint-0.51.0|
|vscode-maven|vscjava|0.42.0|vscjava.vscode-maven-0.42.0|
|vscode-mocha-test-adapter|hbenl|2.14.1|hbenl.vscode-mocha-test-adapter-2.14.1|
|vscode-pull-request-github|GitHub|0.70.0|github.vscode-pull-request-github-0.70.0|
|vscode-pylance|ms-python|2023.8.10|ms-python.vscode-pylance-2023.8.10|
|vscode-resx-editor|DominicVonk|0.0.5|dominicvonk.vscode-resx-editor-0.0.5|
|vscode-ruby|wingrunr21|0.28.0|wingrunr21.vscode-ruby-0.28.0|
|vscode-spring-initializr|vscjava|0.11.2|vscjava.vscode-spring-initializr-0.11.2|
|vscode-test-explorer|hbenl|2.21.1|hbenl.vscode-test-explorer-2.21.1|
|vscode-yaml|redhat|1.14.0|redhat.vscode-yaml-1.14.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.30|visualstudioexptteam.vscodeintellicode-1.2.30|
|vsliveshare|ms-vsliveshare|1.0.5877|ms-vsliveshare.vsliveshare-1.0.5877|
|vsliveshare-pack|ms-vsliveshare|0.4.0|ms-vsliveshare.vsliveshare-pack-0.4.0|;

</details>

**Comment by timheuer** [comment]
@soroshsabz the logs show that you have it installed...screenshot of what you are seeing?

**Comment by PiemP** [comment]
C# extension doesn't work well with LSP ...you have Omnisharp settings in your vscode settings? If yes try to enable it. see #6012

**Comment by soroshsabz** [comment]
@timheuer Exactly my problem is it.

![image](https://github.com/dotnet/vscode-csharp/assets/17947618/6e03feda-8e61-4c48-9c2b-b072e3f1ccd0)

As you can see in picutre, after install C# extension and reopen vscode, vscode says _Do you want install the recommended C# extension from Microsoft for C# language?_

This problem cause I cannot install C# Dev Kit

**Comment by soroshsabz** [comment]
@arkalyanms before reloading, vscode thinks C# extension is installed, but after reload vscode, vscode says C# extension does not installed

**Comment by dibarbet** [comment]
Closing as a stale issue.  This is also likely not an issue that can be solved on the extension side as we have almost no direct participation in how VSCode installs extensions.
