### ISSUE TITLE
How do I get my Omnisharp formatter working in C# Dev Kit?

### ISSUE THREAD

**Issue by CharlieHess** [dotnet/vscode-csharp#6026]
Type: <b>Bug</b>

## Issue Description ##
I've migrated to C# Dev Kit but I was using OmniSharp formatting settings to put brackets on the same line. Now that OmniSharp is history—what do I do?

### C# log ###
<details>Post the output from Output-->C# here</details>

### C# LSP Trace Logs ###
<details>Post the output from Output-->C# LSP Trace Logs here.  Requires `dotnet.server.trace` to be set to `Trace`</details>

## Environment information ##

**VSCode version**: 1.81.0
**C# Extension**: 2.0.320
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
A valid dotnet installation could not be found</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|clang-format|xaver|1.9.0|xaver.clang-format-1.9.0|
|copilot|GitHub|1.100.306|github.copilot-1.100.306|
|csdevkit|ms-dotnettools|0.3.21|ms-dotnettools.csdevkit-0.3.21-darwin-arm64|
|csharp|ms-dotnettools|2.0.320|ms-dotnettools.csharp-2.0.320-darwin-arm64|
|csharp-format-usings|gaoshan0621|0.0.4|gaoshan0621.csharp-format-usings-0.0.4|
|EditorConfig|EditorConfig|0.16.4|editorconfig.editorconfig-0.16.4|
|github-actions|formulahendry|0.0.1|formulahendry.github-actions-0.0.1|
|gitlens|eamodio|14.1.1|eamodio.gitlens-14.1.1|
|gltf-vscode|cesium|2.4.0|cesium.gltf-vscode-2.4.0|
|import-sorter|mike-co|3.3.1|mike-co.import-sorter-3.3.1|
|ink|bruno-dias|1.3.1|bruno-dias.ink-1.3.1|
|isort|ms-python|2023.10.1|ms-python.isort-2023.10.1|
|jupyter|ms-toolsai|2023.7.1002162226|ms-toolsai.jupyter-2023.7.1002162226-darwin-arm64|
|jupyter-keymap|ms-toolsai|1.1.2|ms-toolsai.jupyter-keymap-1.1.2|
|jupyter-renderers|ms-toolsai|1.0.17|ms-toolsai.jupyter-renderers-1.0.17|
|material-theme|zhuangtongfa|3.16.0|zhuangtongfa.material-theme-3.16.0|
|postcss|csstools|1.0.9|csstools.postcss-1.0.9|
|prettier-vscode|esbenp|10.1.0|esbenp.prettier-vscode-10.1.0|
|prisma|Prisma|5.1.0|prisma.prisma-5.1.0|
|python|ms-python|2023.12.0|ms-python.python-2023.12.0|
|require-sort|Perkovec|0.0.1|Perkovec.require-sort-0.0.1|
|shader|slevesque|1.1.5|slevesque.shader-1.1.5|
|shaderlabformatter|litefeel|0.4.3|litefeel.shaderlabformatter-0.4.3|
|shaderlabvscodefree|amlovey|1.3.3|amlovey.shaderlabvscodefree-1.3.3|
|unity-code-snippets|kleber-swf|2.1.0|kleber-swf.unity-code-snippets-2.1.0|
|vscode-commons|redhat|0.0.6|redhat.vscode-commons-0.0.6|
|vscode-css-formatter|aeschli|1.0.2|aeschli.vscode-css-formatter-1.0.2|
|vscode-docker|ms-azuretools|1.26.0|ms-azuretools.vscode-docker-1.26.0|
|vscode-dotnet-runtime|ms-dotnettools|1.6.0|ms-dotnettools.vscode-dotnet-runtime-1.6.0|
|vscode-eslint|dbaeumer|2.4.2|dbaeumer.vscode-eslint-2.4.2|
|vscode-glsl|GeForceLegend|0.2.10|geforcelegend.vscode-glsl-0.2.10|
|vscode-jupyter-cell-tags|ms-toolsai|0.1.8|ms-toolsai.vscode-jupyter-cell-tags-0.1.8|
|vscode-jupyter-slideshow|ms-toolsai|0.1.5|ms-toolsai.vscode-jupyter-slideshow-0.1.5|
|vscode-pylance|ms-python|2023.8.10|ms-python.vscode-pylance-2023.8.10|
|vscode-svgviewer|cssho|2.0.0|cssho.vscode-svgviewer-2.0.0|
|vscode-xml|redhat|0.26.1|redhat.vscode-xml-0.26.1-darwin-arm64|
|vscodeintellicode-csharp|ms-dotnettools|0.1.26|ms-dotnettools.vscodeintellicode-csharp-0.1.26-darwin-arm64|
|vstuc|visualstudiotoolsforunity|0.9.0|visualstudiotoolsforunity.vstuc-0.9.0|
|wallaby-vscode|WallabyJs|1.0.364|wallabyjs.wallaby-vscode-1.0.364|;

</details>

Extension version: 2.0.320
VS Code version: Code 1.81.0 (Universal) (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:40:02.782Z)
OS version: Darwin arm64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 5, 5|
|Memory (System)|32.00GB (0.21GB free)|
|Process Argv|--crash-reporter-id da296e29-1fc8-4490-861c-34888e4cdeaf|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
3biah626:30602489
89544117:30613380
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by dibarbet** [comment]
In devkit, you can configure this with an `.editorconfig` file in the root of your project.  

To configure the formatter to put open braces on the same line when you format for all classes/methods/etc, set this in your .editorconfig
```
csharp_new_line_before_open_brace = none
```
See https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/csharp-formatting-options#csharp_new_line_before_open_brace

If you want a diagnostic when the formatting is incorrect, you can add this line to the .editorconfig
```
dotnet_diagnostic.IDE0055.severity = error
```
See https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0055

Editorconfig docs - https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-style-rule-options

With these two rules in my test project it looks something like this:
![editorconfig_configuration](https://github.com/dotnet/vscode-csharp/assets/5749229/a59136be-2265-47dd-beff-aed43d8bc979)


Going to close this issue - but reopen it if you have any issues with it.

**Comment by CharlieHess** [comment]
Thank you @dibarbet !

**Comment by Vasdranna** [comment]
Is there a way to set it as global options or in the user settings of VS Code? Instead of making an `.editorconfig` file each time?

**Comment by JoeRobich** [comment]
If all your source is located under a single directory, you could put an .editorconfig in that root directory and it would apply as long as the nested directories did not contain an .editorconfig with `root = true`.

**Comment by Vasdranna** [comment]
> If all your source is located under a single directory, you could put an .editorconfig in that root directory and it would apply as long as the nested directories did not contain an .editorconfig with `root = true`.

Thank you for answering. Does this still need a project file to work, right? It won't work without a Dotnet project?

**Comment by JoeRobich** [comment]
> Does this still need a project file to work, right?

Yes, it would.

**Comment by mahmudzero** [comment]
> @dibarbet In devkit, you can configure this with an `.editorconfig` file in the root of your project.
> 
> To configure the formatter to put open braces on the same line when you format for all classes/methods/etc, set this in your .editorconfig
> 
> ```
> csharp_new_line_before_open_brace = none
> ```
> 
> See https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/csharp-formatting-options#csharp_new_line_before_open_brace
> 
> If you want a diagnostic when the formatting is incorrect, you can add this line to the .editorconfig
> 
> ```
> dotnet_diagnostic.IDE0055.severity = error
> ```
> 
> See https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0055
> 
> Editorconfig docs - https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-style-rule-options
> 
> With these two rules in my test project it looks something like this: ![editorconfig_configuration](https://github.com/dotnet/vscode-csharp/assets/5749229/a59136be-2265-47dd-beff-aed43d8bc979) [ ![editorconfig_configuration](https://github.com/dotnet/vscode-csharp/assets/5749229/a59136be-2265-47dd-beff-aed43d8bc979) ](https://private-user-images.githubusercontent.com/5749229/258279778-a59136be-2265-47dd-beff-aed43d8bc979.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzgzMzQxMzYsIm5iZiI6MTczODMzMzgzNiwicGF0aCI6Ii81NzQ5MjI5LzI1ODI3OTc3OC1hNTkxMzZiZS0yMjY1LTQ3ZGQtYmVmZi1hZWQ0M2Q4YmM5NzkuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMzFUMTQzMDM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmIzM2MxOWExNDdhNTgxYjAzOTg1M2RkZWUzZTQ5NzZlYWM0ZGZiZGUzMzJiNGY0MTcyZjI1YjY3MmUzMTdkZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.EzBfWoNn6UrLCUJojl789lL2COG2ZRXMsOZ37M0oImY) [ ](https://private-user-images.githubusercontent.com/5749229/258279778-a59136be-2265-47dd-beff-aed43d8bc979.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzgzMzQxMzYsIm5iZiI6MTczODMzMzgzNiwicGF0aCI6Ii81NzQ5MjI5LzI1ODI3OTc3OC1hNTkxMzZiZS0yMjY1LTQ3ZGQtYmVmZi1hZWQ0M2Q4YmM5NzkuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMzFUMTQzMDM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmIzM2MxOWExNDdhNTgxYjAzOTg1M2RkZWUzZTQ5NzZlYWM0ZGZiZGUzMzJiNGY0MTcyZjI1YjY3MmUzMTdkZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.EzBfWoNn6UrLCUJojl789lL2COG2ZRXMsOZ37M0oImY)
> 
> Going to close this issue - but reopen it if you have any issues with it.


As of 2024-01-31:

This doesn't seem to work with the latest version of the C# and C# Dev Kit extensions, there is a dialog box that says with the current version Omisharp will no longer be supported.

Is there anyway with the latest versions of these extensions to configure these settings?

**Comment by dibarbet** [comment]
@mahmudzero the latest versions of the C# extension and C# Dev Kit should work with `.editorconfig` automatically, as long as you have a project loaded with an `.editorconfig` file available in the file hierarchy.

I notice your `.editorconfig` is missing the configuration to enable formatting errors, meaning violations of `csharp_new_line_before_open_brace = none` will not show up as an error.  To ensure they show up as an error you need to also add
`dotnet_diagnostic.IDE0055.severity = error`

This seems to be working for me (I have a project loaded, with an .editorconfig file in the root of the project)

![Image](https://github.com/user-attachments/assets/5767b737-5aa3-45c9-895c-4e52f6b90842)

> # settings.json for vscode
>     "omnisharp.enableEditorConfigSupport": true,
>     "dotnet.server.useOmnisharp": true,

This configures the C# extension to use OmniSharp, which is not compatible with C# Dev Kit.  `dotnet.server.useOmnisharp` is ignored if C# Dev Kit is installed.  I would remove these settings if you're planning on using C# Dev Kit.  

If you're having an issue with this, could you file a new issue (please check that C# Dev Kit loaded the project correctly and the .editorconfig file is present in the solution explorer).

**Comment by mahmudzero** [comment]
> [@mahmudzero](https://github.com/mahmudzero) the latest versions of the C# extension and C# Dev Kit should work with `.editorconfig` automatically, as long as you have a project loaded with an `.editorconfig` file available in the file hierarchy.
> 
> I notice your `.editorconfig` is missing the configuration to enable formatting errors, meaning violations of `csharp_new_line_before_open_brace = none` will not show up as an error. To ensure they show up as an error you need to also add `dotnet_diagnostic.IDE0055.severity = error`
> 
> This seems to be working for me (I have a project loaded, with an .editorconfig file in the root of the project)
> 
> ![Image](https://github.com/user-attachments/assets/5767b737-5aa3-45c9-895c-4e52f6b90842)
> 
> > # settings.json for vscode
> > ```
> > "omnisharp.enableEditorConfigSupport": true,
> > "dotnet.server.useOmnisharp": true,
> > ```
> 
> This configures the C# extension to use OmniSharp, which is not compatible with C# Dev Kit. `dotnet.server.useOmnisharp` is ignored if C# Dev Kit is installed. I would remove these settings if you're planning on using C# Dev Kit.
> 
> If you're having an issue with this, could you file a new issue (please check that C# Dev Kit loaded the project correctly and the .editorconfig file is present in the solution explorer).

@dibarbet Hmm... I added `dotnet_diagnostic.IDE0055.severity = error` and nothing still - What version of dotnet does C# Devkit need? I'm running 9.0.X and I noticed I'm getting an error

> The current workspace is using a new version of .NET SDK '9.0.102', which is not supported by current .NET runtime used by the extension. Some functions may not work correctly. This may happen when global.json is changed, or new SDK installation after the workspace is opened. Reloading the workspace may fix the problem.
