### ISSUE TITLE
Intellisense not starting on Unity 2017 projects

### ISSUE THREAD

**Issue by rocket0634** [dotnet/vscode-csharp#6027]
Type: <b>Bug</b>

Hello, today I was working in a Unity project for a game that no longer has official support from its developers but gets newly created fan creations around a weekly to monthly basis and I was looking to create a new class library plugin for the project using VS Code, as I have been using it more over Visual Studio with it being lightweight. However when I attempted to add a reference to Unity's libraries to the project, I noticed that I wasn't getting any highlights in my usings, and looked at the C#/OmniSharp log to see what was going on.

I noticed that there was no OmniSharp log and that the C# log would stop after launching its server. After looking into it, it appears that a C# extension update was released that blanket disabled OmniSharp in favor of a new tool called the C# Dev Kit, which I haven't heard of before.

While that's good, I noticed some people reporting that the C# Dev Kit does not support Framework-based projects, and that the newly announced Unity Extension should be used instead. Of course, the first thing I noticed is that the Unity Extension requires Unity 2021, which is something we're unable to use, as we're limited to the build of Unity that the game uses.

I would like to request that the OmniSharp Server not be automatically disabled if the C# Dev Kit is not installed. There are several people I know who are using VS Code + .NET CLI to build projects on both Windows and Linux and this update is going to mysteriously disable their tools without any warning.

Extension version: 2.0.320
VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (1.24GB free)|
|Process Argv|--crash-reporter-id 89506afc-1d03-41fa-bb9d-1a15fb38e579|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30792226
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by amlinux** [comment]
What helped me to fix this issue: `"dotnet.server.useOmnisharp": true,` in .vscode/settings.json does the trick and reverts to OmniSharp.

**Comment by rocket0634** [comment]
> What helped me to fix this issue: `"dotnet.server.useOmnisharp": true,` in .vscode/settings.json does the trick and reverts to OmniSharp.

Thank you, I already know the solution to this. My main complaint is that this issue starts out of nowhere with no communication between the extension and the user. This means to all of the people I know who use VS Code for our projects would need to be told individually about what is causing the issue as opposed to being told by the program itself what the issue is. My temporary solution to this on the program's side is to not automatically set this value to false for people who already have the extension installed without the C# Dev Kit installed.

I see in hindsight however that there is another issue addressing legacy projects, so I'll wait to see what results from the current milestone addressing it.

**Comment by jasonmalinowski** [comment]
This should be addressed with https://github.com/dotnet/roslyn/pull/69616.

**Comment by jasonmalinowski** [comment]
@rocket0634 2.2.10 is now out which carries some support for legacy projects on Windows if you want to give that a shot. It's pre-release only at the moment, but you can easily switch back and forth. [Instructions are here.](https://github.com/dotnet/vscode-csharp/discussions/6320)
