### ISSUE TITLE
Disable .NET Runtime auto-downloading

### ISSUE THREAD

**Issue by forfcw** [dotnet/vscode-csharp#6029]
## Is your feature request related to a problem? Please describe.
Download latest .NET Runtime every time I open a C# workspace automatically!

## Describe the solution you would like
Please disable it or provide a way to disable it at least.

## Additional context
Downloading the .NET Runtime.
Downloading .NET version(s) 7.0.9 .................................................................................................................. Error!
Failed to download .NET 7.0.9:
.NET installation timed out.

 Error!
.NET Acquisition Failed: Installation failed: Error: .NET installation timed out.

**Comment by dibarbet** [comment]
It is possible to disable the autodownload if you point the .net acquisition extension at an existing .net7 install.

See https://github.com/dotnet/vscode-csharp/issues/6004#issuecomment-1664482389

**Comment by TheFibonacciEffect** [comment]
I have the same issue, however my vscode window freezes and does not react. Also I am not even writing c#, I am writing c++. I made a new file and before I could choose a name for the file in the popup dialogue, dotnet started to download and  the save file dialogue was closed.
![image](https://github.com/dotnet/vscode-csharp/assets/58665956/bc7c9eca-8800-4f48-a570-ac00b0341065)
