### ISSUE TITLE
no matching commands

### ISSUE THREAD

**Issue by TheGitHubed** [dotnet/vscode-csharp#6033]
Type: <b>Bug</b>

## Issue Description ##
when typing "omni" in command palette, i get the message "no matching commands" and all other omni csharp function is not working
### C# log ###
<details>Post the output from Output-->C# here</details>

### C# LSP Trace Logs ###
<details>Post the output from Output-->C# LSP Trace Logs here.  Requires `dotnet.server.trace` to be set to `Trace`</details>

## Environment information ##

**VSCode version**: 1.81.0
**C# Extension**: 2.0.320
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>

Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 7.0.9 [c:\Users\Administrator\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.9\shared\Microsoft.NETCore.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|cmake|twxs|0.0.17|twxs.cmake-0.0.17|
|cmake-tools|ms-vscode|1.14.34|ms-vscode.cmake-tools-1.14.34|
|code-runner|formulahendry|0.12.0|formulahendry.code-runner-0.12.0|
|cpptools|ms-vscode|1.16.3|ms-vscode.cpptools-1.16.3-win32-x64|
|cpptools-extension-pack|ms-vscode|1.3.0|ms-vscode.cpptools-extension-pack-1.3.0|
|cpptools-themes|ms-vscode|2.0.0|ms-vscode.cpptools-themes-2.0.0|
|csharp|ms-dotnettools|2.0.320|ms-dotnettools.csharp-2.0.320-win32-x64|
|dotnet-interactive-vscode|ms-dotnettools|1.0.4403010|ms-dotnettools.dotnet-interactive-vscode-1.0.4403010|
|hexeditor|ms-vscode|1.9.12|ms-vscode.hexeditor-1.9.12|
|intellicode-api-usage-examples|VisualStudioExptTeam|0.2.7|visualstudioexptteam.intellicode-api-usage-examples-0.2.7|
|java|redhat|1.21.0|redhat.java-1.21.0-win32-x64|
|jupyter|ms-toolsai|2023.7.1002162226|ms-toolsai.jupyter-2023.7.1002162226-win32-x64|
|jupyter-keymap|ms-toolsai|1.1.2|ms-toolsai.jupyter-keymap-1.1.2|
|jupyter-renderers|ms-toolsai|1.0.17|ms-toolsai.jupyter-renderers-1.0.17|
|msbuild-project-tools|tintoy|0.4.9|tintoy.msbuild-project-tools-0.4.9|
|python|ms-python|2023.14.0|ms-python.python-2023.14.0|
|rest-client|humao|0.25.1|humao.rest-client-0.25.1|
|vscode-dotnet-runtime|ms-dotnettools|1.6.0|ms-dotnettools.vscode-dotnet-runtime-1.6.0|
|vscode-drawio|hediet|1.6.6|hediet.vscode-drawio-1.6.6|
|vscode-java-debug|vscjava|0.53.0|vscjava.vscode-java-debug-0.53.0|
|vscode-java-dependency|vscjava|0.23.1|vscjava.vscode-java-dependency-0.23.1|
|vscode-java-pack|vscjava|0.25.13|vscjava.vscode-java-pack-0.25.13|
|vscode-java-test|vscjava|0.39.1|vscjava.vscode-java-test-0.39.1|
|vscode-jupyter-cell-tags|ms-toolsai|0.1.8|ms-toolsai.vscode-jupyter-cell-tags-0.1.8|
|vscode-jupyter-slideshow|ms-toolsai|0.1.5|ms-toolsai.vscode-jupyter-slideshow-0.1.5|
|vscode-maven|vscjava|0.42.0|vscjava.vscode-maven-0.42.0|
|vscode-pylance|ms-python|2023.8.10|ms-python.vscode-pylance-2023.8.10|
|vscodeintellicode|VisualStudioExptTeam|1.2.30|visualstudioexptteam.vscodeintellicode-1.2.30|;

</details>

Extension version: 2.0.320
VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
3biah626:30602489
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by dibarbet** [comment]
@TheGitHubed which commands are looking for?  In the latest version of the extension we switched to using the Roslyn LSP by default.  This means some of the old O# commands have been renamed or no longer apply.  

If you want to get back all the old O# behavior, set the `dotnet.server.useOmnisharp` flag and reload the window.

**Comment by dibarbet** [comment]
Closing, this issue is stale and not actionable.  If you're still having problems on the latest version of the extension, please open a *new* issue
