### ISSUE TITLE
Make project load failures more visible in the UI

### ISSUE THREAD

**Issue by dibarbet** [dotnet/vscode-csharp#6038]
There have been a number of issues reported where various features don't work (colorization, or completion, or go to def, etc).  Many of these are caused by the project not loading (either failing to load, or no sln being present, etc).

When the project fails to load, we should surface that better in VSCode - for example an error popup in the bottom right that will show the logs so that there is an indication that something went wrong.

For the no sln being present, we should just fix https://github.com/dotnet/vscode-csharp/issues/5722

cc @arkalyanms @jasonmalinowski

**Comment by arkalyanms** [comment]
Yes Jason had the same idea about the toast when we spoke about this yesterday. I tweaked the level to error for now.
