### ISSUE TITLE
Was 2.0 meant to be published stable?

### ISSUE THREAD

**Issue by JustinGrote** [dotnet/vscode-csharp#6040]
Seeing as there's not a corresponding GitHub release, is this an accident?
![image](https://github.com/dotnet/vscode-csharp/assets/15258962/5480c035-3173-4c90-b9d9-e6262dad1ccf)

**Comment by ashelleyPurdue** [comment]
I sure hope it was an accident.  If it wasn't, then that's just downright irresponsible.

**Comment by Kidsunbo** [comment]
Hope so, 2.0 makes all my workflow failed and force me install one more extension. Dislike this experience.

**Comment by Akronae** [comment]
Everything is broken now lmfao

**Comment by DanteMarshal** [comment]
I updated all my extensions today only to find out that everything is now broken with C#
I hope it was an accident, and not [this](https://github.com/dotnet/vscode-csharp/issues/6054#issuecomment-1667750413)
Installing the latest 1.* version from Github released VSIX fixed it

**Comment by JustinGrote** [comment]
@sharwell how about responding rather than removing the indicators to others there is clearly a major problem here.

**Comment by sharwell** [comment]
@JustinGrote I'll make sure it gets reviewed when the team gets in. The indicators weren't necessary and are used for a different purpose internally, so I removed them for clarity.

**Comment by mikadumont** [comment]
We had hoped to release a stable version of 2.0, but we're listening to feedback and trying to fill in some of the most requested features as quickly as we can. The new project system is still pretty new, so it might not have all the same features as the old O# system right away. But we're working hard to catch up and make sure everything's running smoothly. Sorry for any hiccups along the way!

**Comment by JustinGrote** [comment]
@mikadumont probably should have kept it in prereleases before releasing a stable version until those issues are addressed don't you think? That way you can gather feedback from early adopters without breaking everyone's workflows in such a jarring way that has caused so many issues to be created in this repo.

VSCode supports prereleases for extensions: https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prerelease-extensions

**Comment by sharwell** [comment]
Resolving as answered.

> probably should have kept it in prereleases before releasing a stable version until those issues are addressed

We do monitor feedback from preview releases and work to address them before marking a release as stable. Since the prerelease audience is naturally smaller than the release audience, sometimes issues slip through and get identified after the release occurs. We certainly prioritize these when they are identified based on impact and strive to resolve them as quickly as possible.

**Comment by JustinGrote** [comment]
@sharwell I very much appreciate your willingness to provide detailed explanations and engage with the community here, it goes a long way to restoring good will. I do also want to be clear that I do respect the hard work of the team engaged and I did mean "due respect" very specifically as not to be reductionist in your efforts.

I hope the team learns from this experience in driving future feature pushes, certainly hopefully not deploying on a Friday and then having all weekend before things can be addressed, exacerbating the issue :). I for one will do my part by testing future prereleases that hopefully are put to the community via the vscode prerelease feature and verify my standard use cases are stable and file issues if not.

I absolutely understand the engineering challenges involved here, but it doesn't change the net effect that the general perception on this extension has been sorely impacted by the littany of regressions in this release, and that doesn't help anyone, developer and user alike.
