### ISSUE TITLE
v2.0.328 doesn't pull partial class info from generated files

### ISSUE THREAD

**Issue by Rosentti** [dotnet/vscode-csharp#6053]
Type: <b>Bug</b>

## Issue Description ##
The new extension version doesn't pull data from obj/ folder and the .g.cs files within

## Steps to Reproduce ##
1. Create an avalonia project with CommunityToolkit.Mvvm
2. Create a viewmodel and a field named testField (not property)
3. Tag the field with [ObservableProperty]
4. Build the project
5. Try to use TestField in the constructor, and see as it complains it doesn't exist

## Expected Behavior ##
Extension should pull data from .g.cs files

## Actual Behavior ##
Extension no longer pulls data from .g.cs files, like it did with the non-prerelease version

### C# log ###
<details>Post the output from Output-->C# here</details>
(Doesn't fit, just full of spam):

```
[Info  - 11:49:10 PM] [LanguageServerProjectSystem]Completed (re)load of all projects in 00:00:00.1200976
[Info  - 11:49:10 PM] [LanguageServerProjectSystem]Successfully completed load of /home/onni/Documents/opensteamclient/opensteamclient/Common/Common.csproj
[Info  - 11:49:10 PM] [LanguageServerProjectSystem]Completed (re)load of all projects in 00:00:00.1147544
[Info  - 11:49:11 PM] [LanguageServerProjectSystem]Successfully completed load of /home/onni/Documents/opensteamclient/opensteamclient/Common/Common.csproj
[Info  - 11:49:11 PM] [LanguageServerProjectSystem]Completed (re)load of all projects in 00:00:00.1166971
[Info  - 11:49:11 PM] [LanguageServerProjectSystem]Successfully completed load of /home/onni/Documents/opensteamclient/opensteamclient/Common/Common.csproj
[Info  - 11:49:11 PM] [LanguageServerProjectSystem]Completed (re)load of all projects in 00:00:00.1346361
[Info  - 11:49:12 PM] [LanguageServerProjectSystem]Successfully completed load of /home/onni/Documents/opensteamclient/opensteamclient/Common/Common.csproj
[Info  - 11:49:12 PM] [LanguageServerProjectSystem]Completed (re)load of all projects in 00:00:00.1170578
[Info  - 11:49:12 PM] [LanguageServerProjectSystem]Successfully completed load of /home/onni/Documents/opensteamclient/opensteamclient/Common/Common.csproj
[Info  - 11:49:12 PM] [LanguageServerProjectSystem]Completed (re)load of all projects in 00:00:00.1238743
[Info  - 11:49:13 PM] [LanguageServerProjectSystem]Successfully completed load of /home/onni/Documents/opensteamclient/opensteamclient/Common/Common.csproj
[Info  - 11:49:13 PM] [LanguageServerProjectSystem]Completed (re)load of all projects in 00:00:00.1139928
[Info  - 11:49:13 PM] [LanguageServerProjectSystem]Successfully completed load of /home/onni/Documents/opensteamclient/opensteamclient/Common/Common.csproj
[Info  - 11:49:13 PM] [LanguageServerProjectSystem]Completed (re)load of all projects in 00:00:00.1296320
[Info  - 11:49:14 PM] [LanguageServerProjectSystem]Successfully completed load of /home/onni/Documents/opensteamclient/opensteamclient/Common/Common.csproj
[Info  - 11:49:14 PM] [LanguageServerProjectSystem]Completed (re)load of all projects in 00:00:00.1247758
[Info  - 11:49:14 PM] [LanguageServerProjectSystem]Successfully completed load of /home/onni/Documents/opensteamclient/opensteamclient/Common/Common.csproj
[Info  - 11:49:14 PM] [LanguageServerProjectSystem]Completed (re)load of all projects in 00:00:00.1136603
[Info  - 11:49:15 PM] [LanguageServerProjectSystem]Successfully completed load of /home/onni/Documents/opensteamclient/opensteamclient/Common/Common.csproj
[Info  - 11:49:15 PM] [LanguageServerProjectSystem]Completed (re)load of all projects in 00:00:00.1125492
[Info  - 11:49:16 PM] [LanguageServerProjectSystem]Successfully completed load of /home/onni/Documents/opensteamclient/opensteamclient/Common/Common.csproj
[Info  - 11:49:16 PM] [LanguageServerProjectSystem]Completed (re)load of all projects in 00:00:00.1139885
[Info  - 11:49:16 PM] [LanguageServerProjectSystem]Successfully completed load of /home/onni/Documents/opensteamclient/opensteamclient
```

## Environment information ##

**VSCode version**: 1.78.2
**C# Extension**: 2.0.328
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.107
 Commit:    bf72c06963

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.107/

Host:
  Version:      7.0.7
  Architecture: x64
  Commit:       5b20af47d9

.NET SDKs installed:
  6.0.119 [/usr/share/dotnet/sdk]
  7.0.107 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.NETCore.App 6.0.19 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/share/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|autoimport|steoates|1.5.4|steoates.autoimport-1.5.4|
|better-cpp-syntax|jeff-hykin|1.17.2|jeff-hykin.better-cpp-syntax-1.17.2|
|cmake|twxs|0.0.17|twxs.cmake-0.0.17|
|cmake-tools|ms-vscode|1.15.30|ms-vscode.cmake-tools-1.15.30|
|cpptools|ms-vscode|1.17.0|ms-vscode.cpptools-1.17.0-linux-x64|
|cpptools-extension-pack|ms-vscode|1.3.0|ms-vscode.cpptools-extension-pack-1.3.0|
|cpptools-themes|ms-vscode|2.0.0|ms-vscode.cpptools-themes-2.0.0|
|csharp|ms-dotnettools|2.0.328|ms-dotnettools.csharp-2.0.328-linux-x64|
|doxdocgen|cschlosser|1.4.0|cschlosser.doxdocgen-1.4.0|
|github-markdown-preview|bierner|0.3.0|bierner.github-markdown-preview-0.3.0|
|hexeditor|ms-vscode|1.9.12|ms-vscode.hexeditor-1.9.12|
|intellicode-api-usage-examples|VisualStudioExptTeam|0.2.7|visualstudioexptteam.intellicode-api-usage-examples-0.2.7|
|java|redhat|1.21.0|redhat.java-1.21.0-linux-x64|
|live-server|ms-vscode|0.4.8|ms-vscode.live-server-0.4.8|
|markdown-checkbox|bierner|0.4.0|bierner.markdown-checkbox-0.4.0|
|markdown-emoji|bierner|0.3.0|bierner.markdown-emoji-0.3.0|
|markdown-footnotes|bierner|0.1.1|bierner.markdown-footnotes-0.1.1|
|markdown-mermaid|bierner|1.19.0|bierner.markdown-mermaid-1.19.0|
|markdown-preview-github-styles|bierner|2.0.2|bierner.markdown-preview-github-styles-2.0.2|
|markdown-yaml-preamble|bierner|0.1.0|bierner.markdown-yaml-preamble-0.1.0|
|remote-containers|ms-vscode-remote|0.304.0|ms-vscode-remote.remote-containers-0.304.0|
|remote-explorer|ms-vscode|0.4.0|ms-vscode.remote-explorer-0.4.0|
|remote-ssh|ms-vscode-remote|0.102.0|ms-vscode-remote.remote-ssh-0.102.0|
|remote-ssh-edit|ms-vscode-remote|0.86.0|ms-vscode-remote.remote-ssh-edit-0.86.0|
|rust-analyzer|rust-lang|0.3.1607|rust-lang.rust-analyzer-0.3.1607-linux-x64|
|vscode-docker|ms-azuretools|1.26.0|ms-azuretools.vscode-docker-1.26.0|
|vscode-dotnet-runtime|ms-dotnettools|1.6.0|ms-dotnettools.vscode-dotnet-runtime-1.6.0|
|vscode-eslint|dbaeumer|2.4.2|dbaeumer.vscode-eslint-2.4.2|
|vscode-java-debug|vscjava|0.53.0|vscjava.vscode-java-debug-0.53.0|
|vscode-java-dependency|vscjava|0.23.1|vscjava.vscode-java-dependency-0.23.1|
|vscode-java-pack|vscjava|0.25.13|vscjava.vscode-java-pack-0.25.13|
|vscode-java-test|vscjava|0.39.1|vscjava.vscode-java-test-0.39.1|
|vscode-maven|vscjava|0.42.0|vscjava.vscode-maven-0.42.0|
|vscode-proto3|zxh404|0.5.5|zxh404.vscode-proto3-0.5.5|
|vscodeintellicode|VisualStudioExptTeam|1.2.30|visualstudioexptteam.vscodeintellicode-1.2.30|;

</details>

Extension version: 2.0.328
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:47:05.613Z)
OS version: Linux x64 6.3.9-zen1-1-zen
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7800X CPU @ 3.50GHz (12 x 3689)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|46.74GB (34.38GB free)|
|Process Argv|--unity-launch --crash-reporter-id 30978078-03a2-492c-acd6-8ba72e71e044|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasmawayland|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30792226
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by patnym** [comment]
Can verify!

Example, https://mapperly.riok.app/ generates visual errors.

```
[Mapper]
public static partial class Mapper
{
    public static partial Dto ToDto(Model model);
}
```

**Comment by kj372** [comment]
I have the same problem. Version is **2.0.376**.
I am using WPF and the files auto-generated by dotnet are not being read.

The x:Name defined in XAML is not recognized by the code-behind IntelliSense.

This is because *.g.cs under
```
/project name/obj/Debug/net*.*-windows
```
has not been read.

Thank you in advance.
