### ISSUE TITLE
Is there a way to get rid of .NET Install Tool for Extension Author?

### ISSUE THREAD

**Issue by Kidsunbo** [dotnet/vscode-csharp#6065]
After updating to 2.0. I have to install .NET Install Tool for Extension Author. I guess it's used to download a dotnet sdk. But I have had one installed with package manager. Why do I still need to download one? and Is there way to get rid of this extension? It can't be uninstalled because C# extension 2.0 depends on it.

**Comment by arkalyanms** [comment]
C# extension takes an external dependency on the .NET Install Tool instead of downloading it in house. The acquisition tool has features coming that optimizes the need for an SDK download. If there are particular feature requests to optimize the need for a download, we can certainly request it be added to the roadmap for that extension. 

@nagilson fyi

**Comment by nagilson** [comment]
https://github.com/dotnet/vscode-csharp/issues/6004#issuecomment-1669571454 explains how to use an existing dotnet install. Im not sure if vscode has the option for extensions to remove their extension dependencies.

**Comment by nagilson** [comment]
We are adding functionality to the extension to auto accept an existing SDK if one matches what is requested or needed to run. I share in your sentiment though I'm not aware of any functionality VS Code as a platform provides to have an optional dependency. I'd expect that's something we can investigate though!

**Comment by Kidsunbo** [comment]
> [#6004 (comment)](https://github.com/dotnet/vscode-csharp/issues/6004#issuecomment-1669571454) explains how to use an existing dotnet install. Im not sure if vscode has the option for extensions to remove their extension dependencies but if you use this setting the .NET extension will not really do anything.

Maybe downloading a new dotnet SDK should be kept only within its own extension. For users who already have one or who don't like to install automatically. A bundled extension only brings annoyance. If one wants that functionality, he can just install that extension, rather than ignore the existence of the extension if one doesn't want that.

**Comment by arkalyanms** [comment]
Closing via https://github.com/dotnet/vscode-csharp/pull/6074

**Comment by nagilson** [comment]
@dandev486  the install tool extension ( though it will actually be a different extension.) Thanks.

**Comment by NCLnclNCL** [comment]
I need unistall it

**Comment by darkstarx** [comment]
@arkalyanms Why this issue has been closed?
I don't use .net at all and I don't need it in vscode. How to remove this extension?

**Comment by nagilson** [comment]
If you use the C# extension then you do in fact need .NET to run. If you want to remove it, try removing it, and vs code will tell you which other extensions depend on it. Remove those as well.
