### ISSUE TITLE
Using the new language server, C# formatting rules in `.editorconfig` are ignored.

### ISSUE THREAD

**Issue by simonmattes** [dotnet/vscode-csharp#6067]
## Issue Description ##

Using the new language server, C# formatting rules in `.editorconfig` are ignored.

## Steps to Reproduce ##

1. Create a new blank `dotnet new console` application.
1. Create `.editorconfig` with:  
	```
	[*.cs]
	csharp_space_after_keywords_in_control_flow_statements = false
	csharp_indent_case_contents_when_block = false
	```
1. Add the following to `Program.cs`:  
	```csharp
	if(true)
	{
	}

	switch("Hello")
	{
		case "Hello":
		{
		}
		break;

		case "World":
			break;
	}
	```
1. Execute `Format Document`

## Expected Behavior ##

The formatter formats the code like this:

```csharp
if(true)
{
}

switch("Hello")
{
	case "Hello":
	{
	}
	break;

	case "World":
		break;
}
```

## Actual Behavior ##

The formatter formats the code like this:

```csharp
if (true)
{
}

switch ("Hello")
{
	case "Hello":
		{
		}
		break;

	case "World":
		break;
}
```

## Notes ##

Reverting to the Omnisharp language server (`"dotnet.server.useOmnisharp": true`) returns the expected behavior.

Minimal repro of the bug attached: [BugRepro.zip](https://github.com/dotnet/vscode-csharp/files/12288980/BugRepro.zip)

### C# log ###
<details>Post the output from Output-->C# here</details>

### C# LSP Trace Logs ###
<details>Post the output from Output-->C# LSP Trace Logs here.  Requires `dotnet.server.trace` to be set to `Trace`</details>

## Environment information ##

**VSCode version**: 1.81.0
**C# Extension**: 2.0.328
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>

Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 7.0.9 [c:\Users\simonmattes\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.9\shared\Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|code-spell-checker|streetsidesoftware|2.20.5|streetsidesoftware.code-spell-checker-2.20.5|
|code-spell-checker-german|streetsidesoftware|2.2.1|streetsidesoftware.code-spell-checker-german-2.2.1|
|csharp|ms-dotnettools|2.0.328|ms-dotnettools.csharp-2.0.328-win32-x64|
|docomment|k--kato|1.0.0|k--kato.docomment-1.0.0|
|github-vscode-theme|GitHub|6.3.4|github.github-vscode-theme-6.3.4|
|hexeditor|ms-vscode|1.9.12|ms-vscode.hexeditor-1.9.12|
|markdown-checkbox|bierner|0.4.0|bierner.markdown-checkbox-0.4.0|
|markdown-footnotes|bierner|0.1.1|bierner.markdown-footnotes-0.1.1|
|markdown-mermaid|bierner|1.19.0|bierner.markdown-mermaid-1.19.0|
|rainbow-csv|mechatroner|3.7.0|mechatroner.rainbow-csv-3.7.0|
|remote-explorer|ms-vscode|0.4.1|ms-vscode.remote-explorer-0.4.1|
|remote-ssh|ms-vscode-remote|0.102.0|ms-vscode-remote.remote-ssh-0.102.0|
|remote-ssh-edit|ms-vscode-remote|0.86.0|ms-vscode-remote.remote-ssh-edit-0.86.0|
|vscode-dotnet-runtime|ms-dotnettools|1.6.0|ms-dotnettools.vscode-dotnet-runtime-1.6.0|
|vscode-guid|heaths|1.7.0|heaths.vscode-guid-1.7.0|
|vscode-print|pdconsec|0.11.15|pdconsec.vscode-print-0.11.15|
|vscode-todo-highlight|wayou|1.0.5|wayou.vscode-todo-highlight-1.0.5|;

</details>

**Comment by dibarbet** [comment]
.editorconfig should be respected by the new language server - but the current marketplace version requires a solution file to be able to load (known bug that will be fixed in this weeks release, see https://github.com/dotnet/vscode-csharp/issues/5923).

If you add a solution file to the project, does it work?

**Comment by simonmattes** [comment]
Thanks for the fast response. Indeed, it looks like the language server is stuck in `Starting server...` without an .sln file in this build.

Adding an .sln file to the project restores proper formatting:

```
dotnet new sln --name BugRepro
dotnet sln add BugRepro.csproj
```

So it looks like it should be fixed with the update you are referring.

Thanks a lot!
