### ISSUE TITLE
F12 stopped working on linux

### ISSUE THREAD

**Issue by koyllis** [dotnet/vscode-csharp#6082]
After version 1.80 F12 just stopped working on ubuntu!

**Comment by dibarbet** [comment]
Can you share what kind of project you're trying to load and the output from the 'C#' output window?

**Comment by koyllis** [comment]
Its a library project.
The output says this -> otnet path: /home/koyllis/.config/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.10/dotnet
Activating C# standalone...
info: LanguageServerHost[0]
      Starting server...

But anyways all procjects behave the same.. For example if you press F12 on DateTime it says definition not found!
On windows its ok!

**Comment by stesto** [comment]
I'm on windows and I actually get the same error.
When I press F12 on anything I get an error message like:

The editor could not be opened due to an unexpected error: Unable to resolve resource
c:%5Users%5user%5Desktop%5MyProject%5SomeCodeFile.cs

**Comment by lyhongnhat** [comment]
Check whether your C# extension is pre-release version. If it's, switch back to the stable one. That helps resolve the problem in my case

**Comment by stesto** [comment]
> Check whether your C# extension is pre-release version. If it's, switch back to the stable one. That helps resolve the problem in my case

I already rolled back to a previous version, it solved it in my case too. Thanks,

**Comment by koyllis** [comment]
I noticed that when a  .sln file is present then everything works fine!
But if you open a .csproj it just stops working!

In other works if the folder does not contain  a .sln file then F12 Fails!

**Comment by cafenroy** [comment]
Had the same issue on Linux. 

I installed an older version of the C# Dev Kit (0.2.100) extension, it started to work.
Then I re-updated to the latest one (0.3.21), and it is still working.

**Comment by lars-nystrom-mio** [comment]
I also get the same "The editor could not be opened due to an unexpected error: Unable to resolve resource" on Windows. Rolled back `ms-dotnettools.csharp` to 2.0.328 and it works again.

**Comment by koyllis** [comment]
The only solution that works for now is to create a sln file and include the csproj ...

**Comment by dibarbet** [comment]
> I noticed that when a .sln file is present then everything works fine!
But if you open a .csproj it just stops working!

Yup this is a known issue that has been fixed (hopefully will be released later today).  See https://github.com/dotnet/vscode-csharp/issues/6013

> When I press F12 on anything I get an error message like:
The editor could not be opened due to an unexpected error: Unable to resolve resource
c:%5CUsers%5Cuser%5CDesktop%5CMyProject%5CSomeCodeFile.cs

This is also known, and should be fixed in the same release.  Fix was merged in https://github.com/dotnet/vscode-csharp/pull/6091

I'll close this issue since I think all the problems listed are known and should be resolved in the upcoming release.
