### ISSUE TITLE
Go To Definition broken on windows

### ISSUE THREAD

**Issue by omlnaut** [dotnet/vscode-csharp#6092]
Type: <b>Bug</b>

## Issue Description ##
When trying to go to the definition of any symbol (even those defined in my own solution), I get an error that the editor could not find the file. The path reported by the error is correct, but instead of backslashes it's showing %5.
I'm using the current nightly build of vscode. This started breaking today, yesterday I had no issues.

VsCode Insiders Version: 1.82.0-insider

**Comment by dibarbet** [comment]
Thanks for the report - this is known and fixed in this PR - https://github.com/dotnet/vscode-csharp/pull/6091.  Tentatively planning a release for tomorrow.
