### ISSUE TITLE
The type .. is defined in an assembly that is not referenced

### ISSUE THREAD

**Issue by nZeus** [dotnet/vscode-csharp#6096]
Type: <b>Bug</b>

## Issue Description ##
When I open a .NET project, I see a lot of places highlighted as errors. 
It complains that the `The type .. is defined in an assembly that is not referenced`, but the assembly _is_ referenced.

I can run and debug the app, but it's annoying to see eveything in red

## Steps to Reproduce ##
Open .NET project (on MacOS)

## Expected Behavior ##
VS Code should not complain on missing referencies

## Actual Behavior ##
<img width="1432" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/2727326/f73a25b4-4c83-4e97-8454-4a64d5dbc9fc">

### C# log ###
<details>
Dotnet path: /Users/iliatsvetkov/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.10/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
[Info  - 15:09:04] [Program]Language server initialized
</details>

### C# LSP Trace Logs ###
<details>
Extension vscode.bat does not contribute csharpExtensionLoadPaths
Extension vscode.clojure does not contribute csharpExtensionLoadPaths
Extension vscode.coffeescript does not contribute csharpExtensionLoadPaths
Extension vscode.configuration-editing does not contribute csharpExtensionLoadPaths
Extension vscode.cpp does not contribute csharpExtensionLoadPaths
Extension vscode.csharp does not contribute csharpExtensionLoadPaths
Extension vscode.css does not contribute csharpExtensionLoadPaths
Extension vscode.css-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.dart does not contribute csharpExtensionLoadPaths
Extension vscode.debug-auto-launch does not contribute csharpExtensionLoadPaths
Extension vscode.debug-server-ready does not contribute csharpExtensionLoadPaths
Extension vscode.diff does not contribute csharpExtensionLoadPaths
Extension vscode.docker does not contribute csharpExtensionLoadPaths
Extension vscode.emmet does not contribute csharpExtensionLoadPaths
Extension vscode.extension-editing does not contribute csharpExtensionLoadPaths
Extension vscode.fsharp does not contribute csharpExtensionLoadPaths
Extension vscode.git does not contribute csharpExtensionLoadPaths
Extension vscode.git-base does not contribute csharpExtensionLoadPaths
Extension vscode.github does not contribute csharpExtensionLoadPaths
Extension vscode.github-authentication does not contribute csharpExtensionLoadPaths
Extension vscode.go does not contribute csharpExtensionLoadPaths
Extension vscode.groovy does not contribute csharpExtensionLoadPaths
Extension vscode.grunt does not contribute csharpExtensionLoadPaths
Extension vscode.gulp does not contribute csharpExtensionLoadPaths
Extension vscode.handlebars does not contribute csharpExtensionLoadPaths
Extension vscode.hlsl does not contribute csharpExtensionLoadPaths
Extension vscode.html does not contribute csharpExtensionLoadPaths
Extension vscode.html-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.ini does not contribute csharpExtensionLoadPaths
Extension vscode.ipynb does not contribute csharpExtensionLoadPaths
Extension vscode.jake does not contribute csharpExtensionLoadPaths
Extension vscode.java does not contribute csharpExtensionLoadPaths
Extension vscode.javascript does not contribute csharpExtensionLoadPaths
Extension vscode.json does not contribute csharpExtensionLoadPaths
Extension vscode.json-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.julia does not contribute csharpExtensionLoadPaths
Extension vscode.latex does not contribute csharpExtensionLoadPaths
Extension vscode.less does not contribute csharpExtensionLoadPaths
Extension vscode.log does not contribute csharpExtensionLoadPaths
Extension vscode.lua does not contribute csharpExtensionLoadPaths
Extension vscode.make does not contribute csharpExtensionLoadPaths
Extension vscode.markdown does not contribute csharpExtensionLoadPaths
Extension vscode.markdown-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.markdown-math does not contribute csharpExtensionLoadPaths
Extension vscode.media-preview does not contribute csharpExtensionLoadPaths
Extension vscode.merge-conflict does not contribute csharpExtensionLoadPaths
Extension vscode.microsoft-authentication does not contribute csharpExtensionLoadPaths
Extension ms-vscode.js-debug does not contribute csharpExtensionLoadPaths
Extension ms-vscode.js-debug-companion does not contribute csharpExtensionLoadPaths
Extension ms-vscode.vscode-js-profile-table does not contribute csharpExtensionLoadPaths
Extension vscode.builtin-notebook-renderers does not contribute csharpExtensionLoadPaths
Extension vscode.npm does not contribute csharpExtensionLoadPaths
Extension vscode.objective-c does not contribute csharpExtensionLoadPaths
Extension vscode.perl does not contribute csharpExtensionLoadPaths
Extension vscode.php does not contribute csharpExtensionLoadPaths
Extension vscode.php-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.powershell does not contribute csharpExtensionLoadPaths
Extension vscode.pug does not contribute csharpExtensionLoadPaths
Extension vscode.python does not contribute csharpExtensionLoadPaths
Extension vscode.r does not contribute csharpExtensionLoadPaths
Extension vscode.razor does not contribute csharpExtensionLoadPaths
Extension vscode.references-view does not contribute csharpExtensionLoadPaths
Extension vscode.restructuredtext does not contribute csharpExtensionLoadPaths
Extension vscode.ruby does not contribute csharpExtensionLoadPaths
Extension vscode.rust does not contribute csharpExtensionLoadPaths
Extension vscode.scss does not contribute csharpExtensionLoadPaths
Extension vscode.search-result does not contribute csharpExtensionLoadPaths
Extension vscode.shaderlab does not contribute csharpExtensionLoadPaths
Extension vscode.shellscript does not contribute csharpExtensionLoadPaths
Extension vscode.simple-browser does not contribute csharpExtensionLoadPaths
Extension vscode.sql does not contribute csharpExtensionLoadPaths
Extension vscode.swift does not contribute csharpExtensionLoadPaths
Extension vscode.theme-abyss does not contribute csharpExtensionLoadPaths
Extension vscode.theme-defaults does not contribute csharpExtensionLoadPaths
Extension vscode.theme-kimbie-dark does not contribute csharpExtensionLoadPaths
Extension vscode.theme-monokai does not contribute csharpExtensionLoadPaths
Extension vscode.theme-monokai-dimmed does not contribute csharpExtensionLoadPaths
Extension vscode.theme-quietlight does not contribute csharpExtensionLoadPaths
Extension vscode.theme-red does not contribute csharpExtensionLoadPaths
Extension vscode.vscode-theme-seti does not contribute csharpExtensionLoadPaths
Extension vscode.theme-solarized-dark does not contribute csharpExtensionLoadPaths
Extension vscode.theme-solarized-light does not contribute csharpExtensionLoadPaths
Extension vscode.theme-tomorrow-night-blue does not contribute csharpExtensionLoadPaths
Extension vscode.typescript does not contribute csharpExtensionLoadPaths
Extension vscode.typescript-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.vb does not contribute csharpExtensionLoadPaths
Extension vscode.xml does not contribute csharpExtensionLoadPaths
Extension vscode.yaml does not contribute csharpExtensionLoadPaths
Extension 42Crunch.vscode-openapi does not contribute csharpExtensionLoadPaths
Extension alefragnani.Bookmarks does not contribute csharpExtensionLoadPaths
Extension amodio.toggle-excluded-files does not contribute csharpExtensionLoadPaths
Extension bierner.markdown-checkbox does not contribute csharpExtensionLoadPaths
Extension bpruitt-goddard.mermaid-markdown-syntax-highlighting does not contribute csharpExtensionLoadPaths
Extension DavidAnson.vscode-markdownlint does not contribute csharpExtensionLoadPaths
Extension dbaeumer.vscode-eslint does not contribute csharpExtensionLoadPaths
Extension donjayamanne.githistory does not contribute csharpExtensionLoadPaths
Extension DotJoshJohnson.xml does not contribute csharpExtensionLoadPaths
Extension DrMerfy.overtype does not contribute csharpExtensionLoadPaths
Extension eamodio.gitlens does not contribute csharpExtensionLoadPaths
Extension EditorConfig.EditorConfig does not contribute csharpExtensionLoadPaths
Extension fabiospampinato.vscode-todo-plus does not contribute csharpExtensionLoadPaths
Extension formulahendry.dotnet-test-explorer does not contribute csharpExtensionLoadPaths
Extension GitHub.github-vscode-theme does not contribute csharpExtensionLoadPaths
Extension github.vscode-github-actions does not contribute csharpExtensionLoadPaths
Extension GitHub.vscode-pull-request-github does not contribute csharpExtensionLoadPaths
Extension GrapeCity.gc-excelviewer does not contribute csharpExtensionLoadPaths
Extension Gruntfuggly.mermaid-export does not contribute csharpExtensionLoadPaths
Extension hashicorp.terraform does not contribute csharpExtensionLoadPaths
Extension hediet.vscode-drawio does not contribute csharpExtensionLoadPaths
Extension herrmannplatz.npm-dependency-links does not contribute csharpExtensionLoadPaths
Extension idleberg.emoji-code does not contribute csharpExtensionLoadPaths
Extension James-Yu.latex-workshop does not contribute csharpExtensionLoadPaths
Extension janisdd.vscode-edit-csv does not contribute csharpExtensionLoadPaths
Extension jock.svg does not contribute csharpExtensionLoadPaths
Extension jumpinjackie.vscode-map-preview does not contribute csharpExtensionLoadPaths
Extension kdcro101.favorites does not contribute csharpExtensionLoadPaths
Extension kumar-harsh.graphql-for-vscode does not contribute csharpExtensionLoadPaths
Extension lafe.contextualduplicate does not contribute csharpExtensionLoadPaths
Extension logerfo.csharp-colors does not contribute csharpExtensionLoadPaths
Extension mbinic.tgit-cmds does not contribute csharpExtensionLoadPaths
Extension me-dutour-mathieu.vscode-github-actions does not contribute csharpExtensionLoadPaths
Extension mechatroner.rainbow-csv does not contribute csharpExtensionLoadPaths
Extension mhutchie.git-graph does not contribute csharpExtensionLoadPaths
Extension mohsen1.prettify-json does not contribute csharpExtensionLoadPaths
Extension ms-azuretools.vscode-docker does not contribute csharpExtensionLoadPaths
Extension ms-dotnettools.blazorwasm-companion does not contribute csharpExtensionLoadPaths
Extension ms-dotnettools.csdevkit does not contribute csharpExtensionLoadPaths
Extension ms-dotnettools.csharp does not contribute csharpExtensionLoadPaths
Extension ms-dotnettools.dotnet-interactive-vscode does not contribute csharpExtensionLoadPaths
Extension ms-dotnettools.vscode-dotnet-runtime does not contribute csharpExtensionLoadPaths
Extension ms-dotnettools.vscodeintellicode-csharp does not contribute csharpExtensionLoadPaths
Extension ms-mssql.data-workspace-vscode does not contribute csharpExtensionLoadPaths
Extension ms-mssql.mssql does not contribute csharpExtensionLoadPaths
Extension ms-mssql.sql-bindings-vscode does not contribute csharpExtensionLoadPaths
Extension ms-python.isort does not contribute csharpExtensionLoadPaths
Extension ms-python.python does not contribute csharpExtensionLoadPaths
Extension ms-python.vscode-pylance does not contribute csharpExtensionLoadPaths
Extension ms-toolsai.jupyter does not contribute csharpExtensionLoadPaths
Extension ms-toolsai.jupyter-keymap does not contribute csharpExtensionLoadPaths
Extension ms-toolsai.jupyter-renderers does not contribute csharpExtensionLoadPaths
Extension ms-toolsai.vscode-jupyter-cell-tags does not contribute csharpExtensionLoadPaths
Extension ms-toolsai.vscode-jupyter-slideshow does not contribute csharpExtensionLoadPaths
Extension ms-vscode-remote.remote-containers does not contribute csharpExtensionLoadPaths
Extension ms-vscode-remote.remote-wsl does not contribute csharpExtensionLoadPaths
Extension ms-vscode.hexeditor does not contribute csharpExtensionLoadPaths
Extension ms-vscode.powershell does not contribute csharpExtensionLoadPaths
Extension ms-vsliveshare.vsliveshare does not contribute csharpExtensionLoadPaths
Extension mushan.vscode-paste-image does not contribute csharpExtensionLoadPaths
Extension myml.vscode-markdown-plantuml-preview does not contribute csharpExtensionLoadPaths
Extension nemesv.copy-file-name does not contribute csharpExtensionLoadPaths
Extension octref.vetur does not contribute csharpExtensionLoadPaths
Extension pflannery.vscode-versionlens does not contribute csharpExtensionLoadPaths
Extension RandomFractalsInc.geo-data-viewer does not contribute csharpExtensionLoadPaths
Extension redhat.vscode-yaml does not contribute csharpExtensionLoadPaths
Extension rogalmic.bash-debug does not contribute csharpExtensionLoadPaths
Extension sbrink.elm does not contribute csharpExtensionLoadPaths
Extension shd101wyy.markdown-preview-enhanced does not contribute csharpExtensionLoadPaths
Extension spmeesseman.vscode-taskexplorer does not contribute csharpExtensionLoadPaths
Extension tanhakabir.rest-book does not contribute csharpExtensionLoadPaths
Extension tomoki1207.pdf does not contribute csharpExtensionLoadPaths
Extension Tyriar.luna-paint does not contribute csharpExtensionLoadPaths
Extension vscode-icons-team.vscode-icons does not contribute csharpExtensionLoadPaths
Extension zaaack.markdown-editor does not contribute csharpExtensionLoadPaths
</details>

## Environment information ##

**VSCode version**: 1.81.0
**C# Extension**: 2.0.346
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
A valid dotnet installation could not be found</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|bash-debug|rogalmic|0.3.9|rogalmic.bash-debug-0.3.9|
|blazorwasm-companion|ms-dotnettools|1.1.4|ms-dotnettools.blazorwasm-companion-1.1.4|
|Bookmarks|alefragnani|13.4.1|alefragnani.bookmarks-13.4.1|
|contextualduplicate|lafe|0.2.0|lafe.contextualduplicate-0.2.0|
|copy-file-name|nemesv|1.2.0|nemesv.copy-file-name-1.2.0|
|csdevkit|ms-dotnettools|0.3.21|ms-dotnettools.csdevkit-0.3.21-darwin-arm64|
|csharp|ms-dotnettools|2.0.346|ms-dotnettools.csharp-2.0.346-darwin-arm64|
|csharp-colors|logerfo|0.2.1|logerfo.csharp-colors-0.2.1|
|data-workspace-vscode|ms-mssql|0.5.0|ms-mssql.data-workspace-vscode-0.5.0|
|dotnet-interactive-vscode|ms-dotnettools|1.0.4403010|ms-dotnettools.dotnet-interactive-vscode-1.0.4403010|
|dotnet-test-explorer|formulahendry|0.7.8|formulahendry.dotnet-test-explorer-0.7.8|
|EditorConfig|EditorConfig|0.16.4|editorconfig.editorconfig-0.16.4|
|elm|sbrink|0.26.0|sbrink.elm-0.26.0|
|emoji-code|idleberg|0.12.0|idleberg.emoji-code-0.12.0|
|favorites|kdcro101|2.4.5|kdcro101.favorites-2.4.5|
|gc-excelviewer|GrapeCity|4.2.57|grapecity.gc-excelviewer-4.2.57|
|geo-data-viewer|RandomFractalsInc|2.6.0|randomfractalsinc.geo-data-viewer-2.6.0|
|git-graph|mhutchie|1.30.0|mhutchie.git-graph-1.30.0|
|githistory|donjayamanne|0.6.20|donjayamanne.githistory-0.6.20|
|github-vscode-theme|GitHub|6.3.4|github.github-vscode-theme-6.3.4|
|gitlens|eamodio|14.2.0|eamodio.gitlens-14.2.0|
|graphql-for-vscode|kumar-harsh|1.15.3|kumar-harsh.graphql-for-vscode-1.15.3|
|hexeditor|ms-vscode|1.9.12|ms-vscode.hexeditor-1.9.12|
|isort|ms-python|2023.10.1|ms-python.isort-2023.10.1|
|jupyter|ms-toolsai|2023.7.1002162226|ms-toolsai.jupyter-2023.7.1002162226-darwin-arm64|
|jupyter-keymap|ms-toolsai|1.1.2|ms-toolsai.jupyter-keymap-1.1.2|
|jupyter-renderers|ms-toolsai|1.0.17|ms-toolsai.jupyter-renderers-1.0.17|
|latex-workshop|James-Yu|9.13.4|james-yu.latex-workshop-9.13.4|
|luna-paint|Tyriar|0.16.0|tyriar.luna-paint-0.16.0|
|markdown-checkbox|bierner|0.4.0|bierner.markdown-checkbox-0.4.0|
|markdown-editor|zaaack|0.1.10|zaaack.markdown-editor-0.1.10|
|markdown-preview-enhanced|shd101wyy|0.6.8|shd101wyy.markdown-preview-enhanced-0.6.8|
|mermaid-export|Gruntfuggly|0.0.8|gruntfuggly.mermaid-export-0.0.8|
|mermaid-markdown-syntax-highlighting|bpruitt-goddard|1.5.2|bpruitt-goddard.mermaid-markdown-syntax-highlighting-1.5.2|
|mssql|ms-mssql|1.20.1|ms-mssql.mssql-1.20.1|
|npm-dependency-links|herrmannplatz|1.2.0|herrmannplatz.npm-dependency-links-1.2.0|
|overtype|DrMerfy|0.5.0|drmerfy.overtype-0.5.0|
|pdf|tomoki1207|1.2.2|tomoki1207.pdf-1.2.2|
|powershell|ms-vscode|2023.6.0|ms-vscode.powershell-2023.6.0|
|prettify-json|mohsen1|0.0.3|mohsen1.prettify-json-0.0.3|
|python|ms-python|2023.14.0|ms-python.python-2023.14.0|
|rainbow-csv|mechatroner|3.7.0|mechatroner.rainbow-csv-3.7.0|
|remote-containers|ms-vscode-remote|0.304.0|ms-vscode-remote.remote-containers-0.304.0|
|remote-wsl|ms-vscode-remote|0.81.0|ms-vscode-remote.remote-wsl-0.81.0|
|rest-book|tanhakabir|6.2.1|tanhakabir.rest-book-6.2.1|
|sql-bindings-vscode|ms-mssql|0.4.0|ms-mssql.sql-bindings-vscode-0.4.0|
|svg|jock|1.5.3|jock.svg-1.5.3|
|terraform|hashicorp|2.27.1|hashicorp.terraform-2.27.1-darwin-arm64|
|tgit-cmds|mbinic|1.4.2|mbinic.tgit-cmds-1.4.2|
|toggle-excluded-files|amodio|2.0.0|amodio.toggle-excluded-files-2.0.0|
|vetur|octref|0.37.3|octref.vetur-0.37.3|
|vscode-docker|ms-azuretools|1.26.0|ms-azuretools.vscode-docker-1.26.0|
|vscode-dotnet-runtime|ms-dotnettools|1.6.0|ms-dotnettools.vscode-dotnet-runtime-1.6.0|
|vscode-drawio|hediet|1.6.6|hediet.vscode-drawio-1.6.6|
|vscode-edit-csv|janisdd|0.8.1|janisdd.vscode-edit-csv-0.8.1|
|vscode-eslint|dbaeumer|2.4.2|dbaeumer.vscode-eslint-2.4.2|
|vscode-github-actions|github|0.26.1|github.vscode-github-actions-0.26.1|
|vscode-github-actions|me-dutour-mathieu|3.0.1|me-dutour-mathieu.vscode-github-actions-3.0.1|
|vscode-icons|vscode-icons-team|12.5.0|vscode-icons-team.vscode-icons-12.5.0|
|vscode-jupyter-cell-tags|ms-toolsai|0.1.8|ms-toolsai.vscode-jupyter-cell-tags-0.1.8|
|vscode-jupyter-slideshow|ms-toolsai|0.1.5|ms-toolsai.vscode-jupyter-slideshow-0.1.5|
|vscode-map-preview|jumpinjackie|0.5.9|jumpinjackie.vscode-map-preview-0.5.9|
|vscode-markdown-plantuml-preview|myml|0.0.2|myml.vscode-markdown-plantuml-preview-0.0.2|
|vscode-markdownlint|DavidAnson|0.51.0|davidanson.vscode-markdownlint-0.51.0|
|vscode-openapi|42Crunch|4.18.6|42crunch.vscode-openapi-4.18.6|
|vscode-paste-image|mushan|1.0.4|mushan.vscode-paste-image-1.0.4|
|vscode-pull-request-github|GitHub|0.70.0|github.vscode-pull-request-github-0.70.0|
|vscode-pylance|ms-python|2023.8.20|ms-python.vscode-pylance-2023.8.20|
|vscode-taskexplorer|spmeesseman|2.13.2|spmeesseman.vscode-taskexplorer-2.13.2|
|vscode-todo-plus|fabiospampinato|4.19.1|fabiospampinato.vscode-todo-plus-4.19.1|
|vscode-versionlens|pflannery|1.5.0|pflannery.vscode-versionlens-1.5.0|
|vscode-yaml|redhat|1.14.0|redhat.vscode-yaml-1.14.0|
|vscodeintellicode-csharp|ms-dotnettools|0.1.26|ms-dotnettools.vscodeintellicode-csharp-0.1.26-darwin-arm64|
|vsliveshare|ms-vsliveshare|1.0.5877|ms-vsliveshare.vsliveshare-1.0.5877|
|xml|DotJoshJohnson|2.5.1|dotjoshjohnson.xml-2.5.1|;

</details>

Extension version: 2.0.346
VS Code version: Code 1.81.0 (Universal) (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:40:02.782Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|32.00GB (0.04GB free)|
|Process Argv|/Users/iliatsvetkov/Repos/build-support --crash-reporter-id c0898da9-5733-479d-b3df-367da3b0a819|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
2e4cg342:30602488
89544117:30613380
vscrp:30673768
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by dibarbet** [comment]
It looks like you're using C# devkit, correct?  Were there any errors output in nuget restore (in the 'NuGet' output window)?  Is there anything in the 'Projects' output window?

Additionally if you wouldn't mind sharing a screenshot of your solution explorer with all the dependencies nodes expanded?
It should look something like this (and include the referenced project / nuget package)
![image](https://github.com/dotnet/vscode-csharp/assets/5749229/64c7a768-e6a7-42d7-a351-9abf180a2f2e)

**Comment by nZeus** [comment]
You're right, I also have C# Devkit installed.

Nuget output is good:
```
Starting command: "dotnet" restore /Users/iliatsvetkov/Repos/build-support/BuildSupport.sln --interactive...
  Determining projects to restore...
  All projects are up-to-date for restore.
Completed command: "dotnet" restore /Users/iliatsvetkov/Repos/build-support/BuildSupport.sln --interactive (1788ms)
```

Projects output is ok, too
```
2023-08-10 23:42:58.510 [info] Project system initialization finished. 3 project(s) are loaded, and 0 failed to load.
```

Here is the screenshot as you asked:
<img width="364" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/2727326/dfccd8ea-9aff-4288-a038-c032eacf5455">

I noticed the warning icon on the `Nuget.Common` package... 🤔 
I did `Clean` + `Build` and the issue is gone now..
<img width="202" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/2727326/22a75556-54d5-4032-b3f6-8661f8fec880">
<img width="238" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/2727326/a3806193-26e4-4873-866c-b07760f6d83e">

Thank you for the hints! I guess my obj/bin were stale somehow.
I can enjoy my projects in VSCode again :)

**Comment by dibarbet** [comment]
Great to hear its working!  Yup a warning indicates there was some issue in finding the package which is why it would show up as missing in the editor.  Going to close this for now - please reopen if you have issues.
