### ISSUE TITLE
Plugin stopped working with upgrade to 2.0.x

### ISSUE THREAD

**Issue by jvcdk** [dotnet/vscode-csharp#6127]
Type: <b>Bug</b>

## Issue Description ##
After upgrading to v2.0.357 the plugin stopped (more or less) working for me. It will look up symbols within a single file, but any lookup to other files fail.

A thought is that it *may* be related to the fact that my solution is located in the root folder of the workspace, but in a subfolder. Also, there are two solutions in the subfolder (fyi). However, trying to create a solution file in the workspace root did not remedy the issue.

## Steps to Reproduce ##
For me: Open up any of my previous working workspaces. I don't know how to re-create the issue.

Creating a new workspace / project (with a .csproj file) remedies the issue.

Note: I am also using a Devcontainer setup.

## Expected Behavior ##
C# Intellisense to be working.

## Actual Behavior ##
C# Intellisense is not working in my existing workspaces.

## Logs ##
See attached file....
        
### C# log ###
See attached file....

### C# LSP Trace Logs ###
See attached file....

## Environment information ##

**VSCode version**: 1.81.1
**C# Extension**: 2.0.357
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>

Host:
  Version:      7.0.10
  Architecture: x64
  Commit:       a6dbb800a4

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 7.0.10 [/home/user/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.10/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|cmake|twxs|0.0.17|twxs.cmake-0.0.17|
|cmake-test-adapter|fredericbonnet|0.17.2|fredericbonnet.cmake-test-adapter-0.17.2|
|cmake-tools|ms-vscode|1.15.31|ms-vscode.cmake-tools-1.15.31|
|code-spell-checker|streetsidesoftware|2.20.5|streetsidesoftware.code-spell-checker-2.20.5|
|cpptools|ms-vscode|1.16.3|ms-vscode.cpptools-1.16.3-linux-x64|
|csharp|ms-dotnettools|2.0.357|ms-dotnettools.csharp-2.0.357-linux-x64|
|docomment|k--kato|1.0.0|k--kato.docomment-1.0.0|
|dotnet-test-explorer|formulahendry|0.7.8|formulahendry.dotnet-test-explorer-0.7.8|
|test-adapter-converter|ms-vscode|0.1.8|ms-vscode.test-adapter-converter-0.1.8|
|text-power-tools|qcz|1.41.0|qcz.text-power-tools-1.41.0|
|vscode-commandline-test-adapter|jvcdk-at-github|1.2.0|jvcdk-at-github.vscode-commandline-test-adapter-1.2.0|
|vscode-dotnet-runtime|ms-dotnettools|1.6.0|ms-dotnettools.vscode-dotnet-runtime-1.6.0|
|vscode-nuget-package-manager|jmrog|1.1.6|jmrog.vscode-nuget-package-manager-1.1.6|
|vscode-test-explorer|hbenl|2.21.1|hbenl.vscode-test-explorer-2.21.1|
|vscode-yaml|redhat|1.14.0|redhat.vscode-yaml-1.14.0|;

</details>

Extension version: 2.0.357
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:18:39.991Z)
OS version: Linux x64 5.19.0-50-generic
Modes:
Remote OS version: Linux x64 5.19.0-50-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 4089)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|31.13GB (3.37GB free)|
|Process Argv|--unity-launch --crash-reporter-id d178fecb-6804-4aa1-936c-790c081ceb24|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|Dev Container: LEAF Devcontainer|
|OS|Linux x64 5.19.0-50-generic|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 4096)|
|Memory (System)|31.13GB (3.37GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
3biah626:30602489
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
a2ce3375:30757347
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30812749

```

</details>

**Comment by jvcdk** [comment]
[C#.txt](https://github.com/dotnet/vscode-csharp/files/12335195/C.txt)
[C#_LSP_Trace_Logs.txt](https://github.com/dotnet/vscode-csharp/files/12335196/C._LSP_Trace_Logs.txt)

**Comment by jvcdk** [comment]
[exthost.zip](https://github.com/dotnet/vscode-csharp/files/12335240/exthost.zip)

**Comment by jasonmalinowski** [comment]
@jvcdk So if you have two solution files, we wouldn't have known which one to pick; I think Omnisharp might have picked one arbitrarily or had you use the picker. In any case, if you invoke the Command Palette (Ctrl+Shift+P on Windows -- I admit I don't know what it is on Linux) you should be able to find a "open solution" command which will let you pick the one you want. You can also set dotnet.defaultSolution as a workspace setting to specify the one you want by default.

**Comment by jasonmalinowski** [comment]
And I've written up https://github.com/dotnet/vscode-csharp/pull/6132 to be a bit friendlier in this case.

**Comment by jvcdk** [comment]
Then `open solution` worked perfectly :) I did look for it yesterday, I just did not find it. I was looking up "CSharp..." in the menu, and not ".Net". My bad.

Thank you for your quick reply :) And good idea with #6132 :)
