### ISSUE TITLE
no syntax highlights, can't browse to definition, no libs recognition.

### ISSUE THREAD

**Issue by alexandrenolla** [dotnet/vscode-csharp#6135]
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:

**Comment by jasonmalinowski** [comment]
@alexandrenolla I suspect you might have pushed the "create issue" button prematurely, but are you seeing any logs or error messages when the projects are trying to load? The best place to check would be any logs with "C#" in the title.

**Comment by adndyxu** [comment]
I meet he same problem when install c#v2.0.376, the output is 
"
Downloading the .NET Runtime.
Downloading .NET version(s) 7.0.10 ...........
"
And after throw Timeout Error
When I install c#v1.26.0, the problem is solved

**Comment by TheMarkie** [comment]
Installing C# Dev Kit bricked my entire C# language server today, all highlighting and intellisense stopped working, log is stuck at "Loading solution...", the only fix is to uninstall everything and reinstall only C# language support. I cannot believe that this can happen on a core project this important.

Does open source mean no quality control these days? And I don't mean code quality, I mean software engineer quality

**Comment by alexandrenolla** [comment]
@TheMarkie I did as suggested by @adndyxu and downgraded the extension to v1.26.0. It worked. I disabled auto-update as well...

**Comment by alexandrenolla** [comment]
@TheMarkie I followed the suggestion from @adndyxu and downgraded the extension to v1.26.0. It worked. I also disabled auto-updates...

**Comment by jasonmalinowski** [comment]
We've got a number of fixes that may address @adndyxu's issue, as well as some potential fixes for the original issue in the 2.2.* line that should be getting uploaded within the next day or so. I'm going to close the bug but for the folks who commented here, if you're still seeing issues do feel free to comment further -- although I'll need a _bit_ more to help with diagnosis!

**Comment by jasonmalinowski** [comment]
2.2.10 is now out if any of you want to give that a shot. It's pre-release only at the moment, but you can easily switch back and forth. [Instructions are here.](https://github.com/dotnet/vscode-csharp/discussions/6320)
