### ISSUE TITLE
Solution Explorer infinite loading (Ubuntu 22.04)

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/vscode-csharp#6149]
From vscode-dotnettools created by [BernardoDomeneghetti](https://github.com/BernardoDomeneghetti): microsoft/vscode-dotnettools#372  

Type: <b>Bug</b>

When i open a .NET solution in VS Code, the solution is detected and i can build, rebuild and clean it, but, the solution folders and files don't load.
It ocourred for me only in ubuntu. On windows it works fine

Extension version: 0.3.21
VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:36:11.334Z)
OS version: Linux x64 6.2.0-26-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3400G with Radeon Vega Graphics (8 x 3140)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.53GB (11.51GB free)|
|Process Argv|--unity-launch --crash-reporter-id f7b7b677-5827-4cea-b69a-56a29ac8710d|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by dibarbet** [comment]
@slowsigma or @BernardoDomeneghetti - would you be able to set the `dotnet.server.trace` setting to `Trace` and attach the C# logs here?  Might help see what is going on.

**Comment by slowsigma** [comment]
Sorry, I resolved my problem by removing all extensions, clearing out the extensions folder, putting back just the C# extension, and choosing the use omnisharp option.

**Comment by aliehsdev** [comment]
I also had windows go into endless loading, the whole VS Code slowed down, loaded the processor, the Output showed the download of the .NET Runtime update. The problem turned out to be your plugin, its latest versions. Disabling, deleting or rolling back to 1.26 solves the problem. I have Windows 8.1 if that helps. Also, this problem was repeated by other developers in our company.

**Comment by aliehsdev** [comment]
I have windows 8.1 and plugin version 2.0. I also had windows go into endless loading, the whole VS Code slowed down, loaded the processor, the Output showed the download of the .NET Runtime update. The problem turned out to be your plugin, its latest versions. Disabling, deleting or rolling back to 1.26 solves the problem. Also, this problem was repeated by other developers in our company.

**Comment by dibarbet** [comment]
Unfortunately this isn't resolvable without the requested logs.  If anyone hits this in the latest versions of the extension, please
1.  Set the vscode setting `dotnet.server.trace` to `Trace`
2.  File a new issue and attach the C# output window logs.

Thanks!
