### ISSUE TITLE
[BUG] Autocomplete always adds the first using

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/vscode-csharp#6153]
From vscode-dotnettools created by [RobertOstermann](https://github.com/RobertOstermann): microsoft/vscode-dotnettools#298  

### Describe the Issue

When using the autocomplete feature selecting an option adds a `using` statement to the top of the file. If there are multiple options with the same name, it is adding the `using` statement for the top option.

![image](https://github.com/microsoft/vscode-dotnettools/assets/46828475/82be5bbc-5b36-4ac2-af78-b1c5a2bfb57d)

![image](https://github.com/microsoft/vscode-dotnettools/assets/46828475/18e01e63-7087-4ff1-97ac-dc945eaa63b3)

### Steps To Reproduce

Attempt to autocomplete something with multiple options of the same name. In my example I attempted to add the `JsonIgnore` annotation and even though I selected the second option (Newtonsoft.Json) the `using System.Text.Json.Serialization` statement was added.

### Expected Behavior

The correct `using` statement should be added.

### Environment Information

- VSCode Version: 1.81.0-insider
- C# Dev Kit Version: v0.3.18
- Windows 10 using WSL

**Comment by RobertOstermann** [comment]
@genlu that solved the issue. Thanks!
