### ISSUE TITLE
VSCode installs x64 version not apple silicon of csharp extension

### ISSUE THREAD

**Issue by davidpene** [dotnet/vscode-csharp#6157]
## Environment data
`dotnet --info` output:
```
.NET SDK (reflecting any global.json):
 Version:   6.0.413
 Commit:    10710f7d8e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.3
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.413/

global.json file:
  Not found

Host:
  Version:      6.0.21
  Architecture: arm64
  Commit:       e40b3abf1b

.NET SDKs installed:
  6.0.408 [/usr/local/share/dotnet/sdk]
  6.0.413 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.21 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.21 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

```
VS Code version: 1.80.1
C# Extension version: 2.0.376

## Steps to reproduce

1. Go to extensions
2. Click on 'install c# dev kit'

## Expected  behavior
The apple silicon versions are installed

## Actual behavior
The x64 versions are install i.e ms-dotnettools.csharp-2.0.376-darwin-x64

**Comment by davidpene** [comment]
This results in the error in output

2023-08-17 16:12:29.165 [info] Unhandled exception. System.BadImageFormatException: Could not load file or assembly '/Users/user/.vscode/extensions/ms-dotnettools.csdevkit-0.4.5-darwin-x64/components/CPS/platforms/darwin-x64/node_modules/@microsoft/visualstudio-projectsystem-buildhost.darwin-x64/Microsoft.VisualStudio.ProjectSystem.Server.BuildHost.dll'. An attempt was made to load a program with an incorrect format.

File name: '/Users/user/.vscode/extensions/ms-dotnettools.csdevkit-0.4.5-darwin-x64/components/CPS/platforms/darwin-x64/node_modules/@microsoft/visualstudio-projectsystem-buildhost.darwin-x64/Microsoft.VisualStudio.ProjectSystem.Server.BuildHost.dll'

2023-08-17 16:12:29.165 [info] Try to use X64 based C# Dev Kit extension with ARM based SDK on an apple computer. This is not a supported scenario. Both C# Dev Kit and SDK should match the CPU architecture of the computer.

**Comment by davidpene** [comment]
<img width="424" alt="Screenshot 2023-08-17 at 4 13 47 PM" src="https://github.com/dotnet/vscode-csharp/assets/14010084/67b99489-5fb8-4584-bbb1-5a2bd52cb9fb">

**Comment by JoeRobich** [comment]
This typically happens when the Universal version of VS Code is installed and runs under Rosetta. You may want to try uninstalling and downloading the Apple Silicon version.
<img width="336" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/611219/8a5eb09f-b471-41b9-b22e-9a4a3f13f08e">

**Comment by davidpene** [comment]
Thanks for the quick response @JoeRobich.
I'll try that and let you know how it goes

**Comment by dibarbet** [comment]
Additionally, I've seen the marketplace randomly installing the x64 version even on an arm64 version of vscode.  One potential workaround is to uninstall the extension, then go into the extensions folder and actually delete all the ms-dotnettools.* versions for the wrong platform.

**Comment by davidpene** [comment]
I tried both and it looks like it worked, thanks!
I still can't seem to navigate using "go to definition" etc though, which I thought this would have fixed 🤷

**Comment by dibarbet** [comment]
Closing this issue as the original problem is fixed.  If you're still having issues with go to definition, please open a *new* issue (and include the c# logs and general repro steps).
