### ISSUE TITLE
Mac M2 Unity：No code highlighting and automatic prompts with C#v2.0.372

### ISSUE THREAD

**Issue by misuqian** [dotnet/vscode-csharp#6162]
## Environment data
.NET SDK:
 Version:   7.0.400
 Commit:    73bf45718d

运行时环境:
 OS Name:     Mac OS X
 OS Version:  13.4
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.400/

Host:
  Version:      7.0.10
  Architecture: arm64
  Commit:       a6dbb800a4

.NET SDKs installed:
  6.0.413 [/usr/local/share/dotnet/sdk]
  7.0.400 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.21 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.21 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]
    registered at [/etc/dotnet/install_location_x64]

Environment variables:
  Not set

global.json file:
  Not found

## VS Code version:
Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:40:25.698Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0

## C# Extension version:
v2.0。376

## Unity Extension version:
v0.9.0

**Comment by adndyxu** [comment]
rollback to c# 1.26.0

**Comment by dibarbet** [comment]
For unity projects using legacy csproj, see https://github.com/dotnet/vscode-csharp/blob/main/README.md#how-to-use-omnisharp to switch back to using O# until we resolve https://github.com/dotnet/vscode-csharp/issues/5721

If you're on Unity 2021 or higher though, we recommend upgrading your Unity project's 'Visual Studio Editor' package as described in https://devblogs.microsoft.com/visualstudio/announcing-the-unity-extension-for-visual-studio-code/#getting-started-with-the-unity-extension which should allow it to load in the current version of the extension.
