### ISSUE TITLE
Found dotnet version 7.0.10. Minimum required version is 7.0.100.

### ISSUE THREAD

**Issue by axiannv233** [dotnet/vscode-csharp#6167]
## Environment data
`dotnet --info` output:
.NET SDK:
 Version:   7.0.400
 Commit:    73bf45718d

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.400\

Host:
  Version:      7.0.10
  Architecture: x64
  Commit:       a6dbb800a4

.NET SDKs installed:
  6.0.202 [C:\Program Files\dotnet\sdk]
  7.0.306 [C:\Program Files\dotnet\sdk]
  7.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
VS Code version:1.81.1
C# Extension version: v2.0.376

## Steps to reproduce

Failed to find dotnet info from path, falling back to acquire runtime via ms-dotnettools.vscode-dotnet-runtime
Found dotnet version 7.0.10. Minimum required version is 7.0.100.
Dotnet path: c:\Users\biwy\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10\dotnet.exe
Activating C# + C# Dev Kit + C# IntelliCode...
[Info  - 11:02:16 AM] [Program]Language server initialized

**Comment by dibarbet** [comment]
Thanks for the report.  The issue here is that `dotnet --info` is outputting the runtime version instead of the SDK version in the host section
```
Host:
Version: 7.0.10
```

Since we're looking for the SDK version we fail to recognize it.  This can be fixed by us instead looking for exactly the runtimes or sdks (via `dotnet --list-sdks` or `dotnet --list-runtimes`).

Will fix this.

**Comment by dibarbet** [comment]
Fix - https://github.com/dotnet/vscode-csharp/pull/6175

**Comment by tclugao** [comment]
how to workaround this bug, I am in WSL2 20.02 and also meet this issue?
