### ISSUE TITLE
Newly added file is recognized as MiscellaneousFiles

### ISSUE THREAD

**Issue by Cosifne** [dotnet/vscode-csharp#6207]
Original comment: https://github.com/dotnet/vscode-csharp/issues/6023#issuecomment-1687626335
From the log it looks like part of the code is found in the project system, and the new file is not

**Comment by Cosifne** [comment]
@M0hammad124 
Could you share more info about your dev environment? Like the C# extension version? Are you also using C# DevKit?
If you are using DevKit, is it possible could you share the log under C# DevKit? 
Also, the original log you share is useful, but it looks like it's just a part of the full log. Could you post the full log?

**Comment by M0hammad124** [comment]
my os is Ubuntu 22.04
C# version 2.0.376
C# dev kit 0.4.5
vs code version is 1.81.1-1691620686

[C#.txt](https://github.com/dotnet/vscode-csharp/files/12415763/C.txt)
[Devkit.txt](https://github.com/dotnet/vscode-csharp/files/12415766/Devkit.txt)
[C# LPSTraceLog.txt](https://github.com/dotnet/vscode-csharp/files/12415769/C.LPSTraceLog.txt)

and thank you for following up on this issue

**Comment by Cosifne** [comment]
Tag @jasonmalinowski to help here.
I think we use a different project system when DevKit is enabled. So maybe we should ping someone from the DevKit?

**Comment by arkalyanms** [comment]
The miscellaneous file support here comes from CPS. We can move this to dotnettools.
