### ISSUE TITLE
Support debug x64 dotnet application on Apple silicon Mac

### ISSUE THREAD

**Issue by huanent** [dotnet/vscode-csharp#6210]
Some nuget package only provider x86 and x64 version, like [System.Data.SQLite.Core ](https://www.nuget.org/packages/System.Data.SQLite.Core)

Can we have a way to switch current dotnet executable to x64 like Visual Studio for Mac ?
 /usr/local/share/dotnet/dotnet --> /usr/local/share/dotnet/x64/dotnet

**Comment by huanent** [comment]
This works! This has been bothering me for a long time, thank you very much!

**Comment by coosfix** [comment]
Oh my God, I've been looking for this answer for a long time, thank you!

**Comment by ccidral** [comment]
> Looks like we are missing documentation for this scenario

I can't thank you enough @gregg-miskelly  I've been looking for this solution for 8 months.

**Comment by gregg-miskelly** [comment]
FYI I added a Wiki page for this: https://github.com/dotnet/vscode-csharp/wiki/Debugging-x64-processes-on-an-arm64-computer
