### ISSUE TITLE
Add a way to disable predictive suggestions

### ISSUE THREAD

**Issue by spajus** [dotnet/vscode-csharp#6220]
Type: <b>Feature Request</b>

I tried all possible settings but found no way to disable the IntelliCode predictions, which are almost always wrong and thus annoying.

Please add an easy way to disable them completely. 

Extension version: 2.0.413
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.19044
Modes:

**Comment by spajus** [comment]
Update: `Editor > Inline Suggest` seems to do the trick. Though I will keep the issue open because the name of that option does not have any hints about "predictions".

**Comment by arkalyanms** [comment]
@StringEpsilon's response covers it.
