### ISSUE TITLE
IntelliCode not working in latest version

### ISSUE THREAD

**Issue by dangpech** [dotnet/vscode-csharp#6237]
## Environment data
`dotnet --info` output:
NET SDK:
 Version:   7.0.400
 Commit:    73bf45718d

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /home/dangpech/dotnet/sdk/7.0.400/

Host:
  Version:      7.0.10
  Architecture: x64
  Commit:       a6dbb800a4

.NET SDKs installed:
  7.0.400 [/home/dangpech/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.10 [/home/dangpech/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.10 [/home/dangpech/dotnet/shared/Microsoft.NETCore.App]

VS Code version: 1.81.1
C# Extension version: 2.0.413

## OmniSharp log
Using dotnet configured on PATH
Dotnet path: /home/dangpech/dotnet/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
[Info  - 12:08:40 AM] [Program]Language server initialized

**Comment by dibarbet** [comment]
Transferring over to the intellicode/devkit side
https://github.com/microsoft/vscode-dotnettools/issues/459
