### ISSUE TITLE
Issue: C#  VSCode Extension Stuck in "Installing" State, IntelliCode and OmniSharp Not Working

### ISSUE THREAD

**Issue by ElieAzar-Algo** [dotnet/vscode-csharp#6251]
**Description:**
I am experiencing an issue with the C# extension in Visual Studio Code where it is stuck in the "Installing" state and does not complete the installation process. This issue prevents me from using the C# extension and its features in my development workflow.

**Steps to Reproduce:**

    -     Open Visual Studio Code.
    -     Go to the Extensions sidebar.
    -     Search for the "C#" extension.
    -     Click on the "Install" button for the C# extension.
    -     Observe that the extension remains in the "Installing" state indefinitely.

**Expected Behavior:**
The C# extension should install successfully and transition from the "Installing" state to the "Installed" state. I should be able to use the C# extension for my coding tasks.

**Actual Behavior:**
The C# extension gets stuck in the "Installing" state and does not complete the installation process. I have tried restarting Visual Studio Code and my computer, but the issue persists.

**Environment Information:**

      -     Visual Studio Code Version: Version: 1.81.1
                                                  Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
                                                  Date: 2023-08-09T22:18:39.991Z
                                                  Electron: 22.3.18
                                                  ElectronBuildId: 22689846
                                                  Node.js: 16.17.1
                                                  V8: 10.8.168.25-electron.0
                                                  OS: Linux x64 6.2.0-26-generic snap
      
      -       Operating System: Linux ea 6.2.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jul 13 16:27:29 UTC 2 
                                                 x86_64 x86_64 x86_64 GNU/Linux
            
      
      -       C# Extension Version: Latest

      
**Additional Information:**
I have attempted to restart Visual Studio Code and my computer, clear the extension cache, and reinstall Visual Studio Code itself. Despite these efforts, the C# extension remains stuck in the "Installing" state.

The issue initially arose due to the malfunctioning of IntelliCode and OmniSharp features, which led to the decision to roll back to a previous version of the extension. I am now unable to install the previous version and the extension is nonfunctional.

I appreciate any assistance in resolving this issue and getting the C# extension back to a functional state.

Thank you for your attention to this matter.

Sincerely,
Elias
ElieAzar-Algo

**Comment by dibarbet** [comment]
Apologies for the late reply here.  I'm not sure there is much we can do here from the extension side - we don't have insight into the installation.  A couple of suggestions you can try:
1.  Delete all folders starting with `ms-dotnettools.` in the extensions folder (when vscode is closed), and then re-installing.  You can find the extensions folder via this command:
![image](https://github.com/dotnet/vscode-csharp/assets/5749229/099929e2-6ded-4eaa-8369-c680cd3ca386)
2.  If 1) doesn't work delete the folders again but try installing the vsix manually.  You can download the vsix for your platform here - https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp (see screenshot below).
![image](https://github.com/dotnet/vscode-csharp/assets/5749229/ab05a499-967d-4d7b-b189-360eaa1eac81)
 You'd then install it in VSCode via the 'install from vsix' item in the extensions menu:
![image](https://github.com/dotnet/vscode-csharp/assets/5749229/748b09a6-ed02-4bce-a719-a7133a347b87)

If neither of those work, I'd try re-installing vscode entirely.  There's not much more advice I can give, you might have to reach out to the vscode team for this.
