### ISSUE TITLE
An error occurred with the overloaded function

### ISSUE THREAD

**Issue by xmwhune** [dotnet/vscode-csharp#6293]
## Environment data
`dotnet --info` output:
VS Code version:
C# Extension version:
When a subclass types a function that overrides the parent class, the function name is prompted, but the function is not generated after selection, it is blank, and the selection is not successful

**Comment by genlu** [comment]
Probably a duplicate of https://github.com/dotnet/vscode-csharp/issues/6246

**Comment by genlu** [comment]
Might be fixed by https://github.com/dotnet/vscode-csharp/pull/6315
If not, we'd have more info to investigated with additional logging from https://github.com/dotnet/vscode-csharp/pull/6325
