### ISSUE TITLE
Remove "windows only" on macOS and Linux

### ISSUE THREAD

**Issue by richlander** [dotnet/vscode-csharp#6312]
Can we remove the "windows only" line on macOS and Linux? It no-ops on macOS, so not super useful.

<img width="614" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/2608468/fe0a389f-fec8-4c52-a889-d472a7484c7f">

**Comment by gregg-miskelly** [comment]
The VS debugger team requested a feature from VS Code to allow us to hide these templates. I think we should wait for that feature before we modify this.

**Comment by gregg-miskelly** [comment]
Work item we are waiting on: https://github.com/microsoft/vscode/issues/184457
