### ISSUE TITLE
v2.1.2 cannot use 'F12'

### ISSUE THREAD

**Issue by b26168** [dotnet/vscode-csharp#6313]
## Environment data
`dotnet --info` output:
.NET SDK (reflecting any global.json):
 Version:   6.0.413
 Commit:    10710f7d8e

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.413/

global.json file:
  /home/posen/projects/tri-amr/global.json

Host:
  Version:      6.0.21
  Architecture: x64
  Commit:       e40b3abf1b

.NET SDKs installed:
  6.0.413 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.21 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.21 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
VS Code version:
Version: 1.82.0
Commit: 8b617bd08fd9e3fc94d14adb8d358b56e3f72314
Date: 2023-09-06T22:07:18.759Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.2.0-060200rc7-generic
C# Extension version:
v2.1.2
## Steps to reproduce

1. Right Click on code.
2. Go to Definition/References/.....
3. Always show no references.

## Expected  behavior
Go to Definition/References/.....

## Actual behavior
show no references.

## Additional context
Rollback to v2.0.436 is work.

**Comment by dibarbet** [comment]
@b26168 would you mind changing the `dotnet.server.trace` setting to `Trace` and reload vscode?  Then attach the C# output window logs here.

**Comment by b26168** [comment]
@dibarbet 
Sorry, How can I do this action?

**Comment by dibarbet** [comment]
> @dibarbet Sorry, How can I do this action?

1.  In vscode set this setting value to `Trace`:
<img width="449" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/5749229/68b4c971-f11f-4b6b-a8f7-f9ec3e92429e">

2.  Run this command from the command palette (cntrl+shift+p)
<img width="488" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/5749229/16b017ff-0040-4980-b327-bf25094b3164">

3.  Wait for a bit for things to settle, then open the output window and copy the contents of the C# output window and paste them here
<img width="644" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/5749229/faa9c19c-2354-463c-a350-0a214e3c5dd1">

**Comment by b26168** [comment]
Failed to find dotnet info from path, falling back to acquire runtime via ms-dotnettools.vscode-dotnet-runtime
No compatible .NET runtime found. Minimum required version is 7.0.
Dotnet path: /home/posen/.config/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.11/dotnet
Activating C# standalone...
Starting server at /home/posen/.vscode/extensions/ms-dotnettools.csharp-2.1.2-linux-x64/.roslyn/Microsoft.CodeAnalysis.LanguageServer.dll
Server arguments /home/posen/.vscode/extensions/ms-dotnettools.csharp-2.1.2-linux-x64/.roslyn/Microsoft.CodeAnalysis.LanguageServer.dll --logLevel Trace --telemetryLevel all --extensionLogDirectory /home/posen/.config/Code/logs/20230914T152136/window1/exthost/ms-dotnettools.csharp
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/posen/.vscode/extensions/ms-dotnettools.csharp-2.1.2-linux-x64/.roslyn/Microsoft.CodeAnalysis.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/posen/.vscode/extensions/ms-dotnettools.csharp-2.1.2-linux-x64/.roslyn/Microsoft.CodeAnalysis.Workspaces.MSBuild.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/posen/.vscode/extensions/ms-dotnettools.csharp-2.1.2-linux-x64/.roslyn/Microsoft.CodeAnalysis.CSharp.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/posen/.vscode/extensions/ms-dotnettools.csharp-2.1.2-linux-x64/.roslyn/Microsoft.CodeAnalysis.Workspaces.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/posen/.vscode/extensions/ms-dotnettools.csharp-2.1.2-linux-x64/.roslyn/Microsoft.CodeAnalysis.Elfie.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/posen/.vscode/extensions/ms-dotnettools.csharp-2.1.2-linux-x64/.roslyn/Microsoft.CodeAnalysis.Features.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/posen/.vscode/extensions/ms-dotnettools.csharp-2.1.2-linux-x64/.roslyn/Microsoft.CodeAnalysis.AnalyzerUtilities.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/posen/.vscode/extensions/ms-dotnettools.csharp-2.1.2-linux-x64/.roslyn/Microsoft.CodeAnalysis.Remote.Workspaces.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/posen/.vscode/extensions/ms-dotnettools.csharp-2.1.2-linux-x64/.roslyn/Microsoft.CodeAnalysis.Scripting.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/posen/.vscode/extensions/ms-dotnettools.csharp-2.1.2-linux-x64/.roslyn/Microsoft.CodeAnalysis.CSharp.Workspaces.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/posen/.vscode/extensions/ms-dotnettools.csharp-2.1.2-linux-x64/.roslyn/Microsoft.CodeAnalysis.CSharp.Features.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/posen/.vscode/extensions/ms-dotnettools.csharp-2.1.2-linux-x64/.roslyn/Microsoft.CodeAnalysis.Razor.dll added to workspace.
[Info  - 3:23:04 PM] [Program]Language server initialized
[LanguageServerHost][07:23:04.446][Start]initialize
[LanguageServerHost][07:23:04.452][Start]Initialize
[LanguageServerHost][07:23:04.489][End]Initialize
[LanguageServerHost][07:23:04.529][End]initialize
[LanguageServerHost][07:23:04.536][Start]initialized
[LanguageServerHost][07:23:04.596][End]initialized
[LanguageServerHost][07:23:04.597][Start]solution/open
No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet/download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
[LanguageServerHost][07:23:04.609][Start]workspace/diagnostic
[LanguageServerHost]PublicWorkspacePullDiagnosticsHandler(category: , source: ) started getting diagnostics
[LanguageServerHost]previousResults.Length=0
[LanguageServerHost]Processing 0 documents
[Error - 3:23:04 PM] [LanguageServerHost]System.InvalidOperationException: Failed to find all versions of .NET Core MSBuild. Call to hostfxr_resolve_sdk2. There may be more details in stderr.
   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetSdkFromGlobalSettings(String workingDirectory)
   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetDotNetBasePaths(String workingDirectory)+MoveNext()
   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetInstances(String workingDirectory)+MoveNext()
   at Microsoft.Build.Locator.MSBuildLocator.GetInstances(VisualStudioInstanceQueryOptions options)+MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.LanguageServerProjectSystem.TryEnsureMSBuildLoadedAsync(String workingDirectory) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs:line 159
   at Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.LanguageServerProjectSystem.OpenSolutionAsync(String solutionFilePath) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs:line 97
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 136
[LanguageServerHost][07:23:04.640][End]solution/open

**Comment by dibarbet** [comment]
Thanks for the logs, that confirms this is the same issue tracked by https://github.com/dotnet/vscode-csharp/issues/6335 - installing the .net 7 SDK alongside your existing install is a temporary workaround until we can resolve the issue.

Resolving as a duplicate.

**Comment by b26168** [comment]
Ok, I just rollback to v2.0.436 for workaround.
Thanks.
