### ISSUE TITLE
Committing `await` completion item has no effect

### ISSUE THREAD

**Issue by Vac-HongChen** [dotnet/vscode-csharp#6326]
Await does not support automatic tab input

For example, when I input aw and press tab, it doesn't have any effect, which is very annoying

**Comment by dibarbet** [comment]
@genlu most likely a dup of complex completion edit failures?  Couldn't find an exact issue to duplicate against.

**Comment by genlu** [comment]
I tried it locally, seems to be a dup of https://github.com/dotnet/vscode-csharp/issues/6246 therefore it should be fixed by https://github.com/dotnet/vscode-csharp/pull/6315
