### ISSUE TITLE
Unnecessary files getting shipped with extension package

### ISSUE THREAD

**Issue by ShreyasJejurkar** [dotnet/vscode-csharp#6330]
## Issue Description ##
When I was checking the extension folder on my machine, I could see some test files were getting shipped as part of the extension package. Please take a look at the below screenshot. 

As we can see below screenshot folders like `__mocks__`, `omnisharptest` are part of the test and also I can see this folder as part of this repo. Even more some files like `jest.config`, `baseJestConfig`, `.prettierignore` should not be there as they should be part of development dependencies and not deployment dependencies. 

![image](https://github.com/dotnet/vscode-csharp/assets/17148381/b8309026-2740-4e6a-95c7-4ab854bbcf89)

It looks like there is something wrong with the deployment steps, as its packing unnecessary files to user's machine, increasing the download size. 

## Environment information ##

**VSCode version**: 1.82.0
**C# Extension**: 2.1.2
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
Error running dotnet --info: Error: Command failed: C:\Program Files\dotnet\dotnet.exe --info
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|csdevkit|ms-dotnettools|0.4.10|ms-dotnettools.csdevkit-0.4.10-win32-x64|
|csharp|ms-dotnettools|2.1.2|ms-dotnettools.csharp-2.1.2-win32-x64|
|darker-dark|XavierNaves|1.0.0|xaviernaves.darker-dark-1.0.0|
|EditorConfig|EditorConfig|0.16.4|editorconfig.editorconfig-0.16.4|
|errorlens|usernamehw|3.13.0|usernamehw.errorlens-3.13.0|
|gitlens|eamodio|14.3.0|eamodio.gitlens-14.3.0|
|powershell|ms-vscode|2023.9.1|ms-vscode.powershell-2023.9.1|
|sonarlint-vscode|SonarSource|3.21.0|sonarsource.sonarlint-vscode-3.21.0-win32-x64|
|vim|vscodevim|1.26.0|vscodevim.vim-1.26.0|
|vscode-autohotkey2-lsp|thqby|2.1.5|thqby.vscode-autohotkey2-lsp-2.1.5|
|vscode-conventional-commits|vivaxy|1.25.0|vivaxy.vscode-conventional-commits-1.25.0|
|vscode-dotnet-runtime|ms-dotnettools|1.7.2|ms-dotnettools.vscode-dotnet-runtime-1.7.2|
|vscode-eslint|dbaeumer|2.4.2|dbaeumer.vscode-eslint-2.4.2|
|vscode-jest|Orta|5.2.3|orta.vscode-jest-5.2.3|
|vscodeintellicode-csharp|ms-dotnettools|0.1.26|ms-dotnettools.vscodeintellicode-csharp-0.1.26-win32-x64|;

</details>

**Comment by ShreyasJejurkar** [comment]
There is one more issue, looks like the command `CSharp: Report an issue` is not able to grab dotnet info if there are spaces in the path. Check the section of Dotnet Information in the above original message! 

![image](https://github.com/dotnet/vscode-csharp/assets/17148381/c1937ef2-3a41-45b2-9150-f8ddddf3808d)

**Comment by dibarbet** [comment]
Thanks - fix here - https://github.com/dotnet/vscode-csharp/pull/6332

For the dotnet info, I filed https://github.com/dotnet/vscode-csharp/issues/6333 since its a separate problem.
