### ISSUE TITLE
Run button does not start project

### ISSUE THREAD

**Issue by jtsom** [dotnet/vscode-csharp#6331]
Type: <b>Bug</b>

## Issue Description ##
Clicking the Run button
![image](https://github.com/microsoft/vscode-dotnettools/assets/13488/5d5666c5-138e-4436-85e7-2965b0426ca4)

Does not find the correct project to start the application. Seems to be missing a \.

```

MSBuild version 17.7.1+971bf70db for .NET
MSBUILD : error MSB1009: Project file does not exist.
Switch: d:sourcereposMyCompany.EMRApiMyCompany.EMRApi.WebMyCompany.EMRApi.csproj

 *  The terminal process "C:\Program Files\Git\bin\bash.exe '--login', '-i', '-c', 'dotnet build d:\source\repos\MyCompany.EMRApi\MyCompany.EMRApi.Web\MyCompany.EMRApi.csproj /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
```

Pressing F5 or clicking the Run button in the Debug pane works:

![image](https://github.com/microsoft/vscode-dotnettools/assets/13488/86c055db-0a6a-4e3a-b9da-e4f712bfb7ae)

## Steps to Reproduce ##
Open multi-project solution.
Click the Run button.

## Expected Behavior ##
Error, with project not starting.

## Actual Behavior ##
Project should start.

### C# log ###
<details>Post the output from Output-->C# here</details>

### C# LSP Trace Logs ###
<details>Post the output from Output-->C# LSP Trace Logs here.  Requires `dotnet.server.trace` to be set to `Trace`</details>

## Environment information ##

**VSCode version**: 1.83.0-insider
**C# Extension**: 2.1.2
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
Error running dotnet --info: Error: Command failed: C:\Program Files\dotnet\dotnet.exe --info
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|azure-account|ms-vscode|0.11.5|ms-vscode.azure-account-0.11.5|
|csdevkit|ms-dotnettools|0.5.24|ms-dotnettools.csdevkit-0.5.24-win32-x64|
|csharp|ms-dotnettools|2.1.2|ms-dotnettools.csharp-2.1.2-win32-x64|
|csharpextensions|kreativ-software|1.7.3|kreativ-software.csharpextensions-1.7.3|
|ecdc|mitchdenny|1.8.0|mitchdenny.ecdc-1.8.0|
|git-graph|mhutchie|1.30.0|mhutchie.git-graph-1.30.0|
|hexeditor|ms-vscode|1.9.12|ms-vscode.hexeditor-1.9.12|
|hl7tools|RobHolme|2.0.4|robholme.hl7tools-2.0.4|
|jwt-debugger|yokawasa|0.4.2|yokawasa.jwt-debugger-0.4.2|
|kanagawa|qufiwefefwoyn|1.5.1|qufiwefefwoyn.kanagawa-1.5.1|
|live-server|ms-vscode|0.4.9|ms-vscode.live-server-0.4.9|
|material-icon-theme|PKief|4.30.1|pkief.material-icon-theme-4.30.1|
|msbuild-project-tools|tintoy|0.4.9|tintoy.msbuild-project-tools-0.4.9|
|night-owl|sdras|2.0.1|sdras.night-owl-2.0.1|
|quicktype|quicktype|12.0.46|quicktype.quicktype-12.0.46|
|rainbow-csv|mechatroner|3.7.0|mechatroner.rainbow-csv-3.7.0|
|sync-scroll|dqisme|1.3.1|dqisme.sync-scroll-1.3.1|
|TabOut|albert|0.2.2|albert.tabout-0.2.2|
|vs-code-xml-format|fabianlauer|0.1.5|fabianlauer.vs-code-xml-format-0.1.5|
|vscode-azureappservice|ms-azuretools|0.25.0|ms-azuretools.vscode-azureappservice-0.25.0|
|vscode-azurefunctions|ms-azuretools|1.12.4|ms-azuretools.vscode-azurefunctions-1.12.4|
|vscode-azureresourcegroups|ms-azuretools|0.7.5|ms-azuretools.vscode-azureresourcegroups-0.7.5|
|vscode-azurestorage|ms-azuretools|0.15.3|ms-azuretools.vscode-azurestorage-0.15.3|
|vscode-base64|adamhartford|0.1.0|adamhartford.vscode-base64-0.1.0|
|vscode-cosmosdb|ms-azuretools|0.19.4|ms-azuretools.vscode-cosmosdb-0.19.4|
|vscode-dotnet-runtime|ms-dotnettools|1.7.2|ms-dotnettools.vscode-dotnet-runtime-1.7.2|
|vscode-thunder-client|rangav|2.12.0|rangav.vscode-thunder-client-2.12.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.30|visualstudioexptteam.vscodeintellicode-1.2.30|
|vscodeintellicode-csharp|ms-dotnettools|0.1.26|ms-dotnettools.vscodeintellicode-csharp-0.1.26-win32-x64|;

</details>

Extension version: 0.5.24
VS Code version: Code - Insiders 1.83.0-insider (3c133b63c6e17e2fe33f37db93a6d43e78a262c5, 2023-09-11T05:33:26.767Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (12.93GB free)|
|Process Argv|--crash-reporter-id 362817d9-b661-4b35-92b7-fe18e5872851|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
vscrp:30624060
a9j8j154:30646983
showlangstatbar:30737417
ecj1e332:30687743
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30808721
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206
pythonlinttype:30823781
pythonmpsinfo:30815194
dsvsc015:30821418
pythontestfixt:30826906
pythonfb280951:30830809

```

</details>

**Comment by jtsom** [comment]
UPDATE: This also happens with single project solutions. Does not have to have multiple projects.

**Comment by dibarbet** [comment]
Looks like you're using C# devkit, they own the run tasks when its installed.  Transferred to https://github.com/microsoft/vscode-dotnettools/issues/507
