### ISSUE TITLE
Analyzers shows `i` icon without any reason/problem

### ISSUE THREAD

**Issue by ShreyasJejurkar** [dotnet/vscode-csharp#6345]
## Issue Description ##
In the project dependencies section, under analyzers, all the analyzers have an `i` icon next to them without any reason. 
I thought they were not able to resolve the paths, but if I hover over them I can see from where those analyzers are getting imported. 

![image](https://github.com/dotnet/vscode-csharp/assets/17148381/fd2ed93d-a867-4a1e-8aad-888c0918ebe0)

## Steps to Reproduce ##
1. Create a console app with `dotnet new console`. 
2. Open that in VSCode. 
3. In Solution Explorer, expand the dependencies -> analyzers section. 

## Expected Behavior ##
We should not see any `i` there unless there is some issue loading that analyzer. Hovering over them should tell the reason for failure. 
## Actual Behavior ##
Although the analyzer is loaded correctly, it still shows `i`. 
## Environment information ##

**VSCode version**: 1.82.0
**C# Extension**: 2.1.2
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
Error running dotnet --info: Error: Command failed: C:\Program Files\dotnet\dotnet.exe --info
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|csdevkit|ms-dotnettools|0.4.10|ms-dotnettools.csdevkit-0.4.10-win32-x64|
|csharp|ms-dotnettools|2.1.2|ms-dotnettools.csharp-2.1.2-win32-x64|
|darker-dark|XavierNaves|1.0.0|xaviernaves.darker-dark-1.0.0|
|EditorConfig|EditorConfig|0.16.4|editorconfig.editorconfig-0.16.4|
|errorlens|usernamehw|3.13.0|usernamehw.errorlens-3.13.0|
|gitlens|eamodio|14.3.0|eamodio.gitlens-14.3.0|
|powershell|ms-vscode|2023.9.1|ms-vscode.powershell-2023.9.1|
|sonarlint-vscode|SonarSource|3.21.0|sonarsource.sonarlint-vscode-3.21.0-win32-x64|
|vim|vscodevim|1.26.0|vscodevim.vim-1.26.0|
|vscode-autohotkey2-lsp|thqby|2.1.5|thqby.vscode-autohotkey2-lsp-2.1.5|
|vscode-conventional-commits|vivaxy|1.25.0|vivaxy.vscode-conventional-commits-1.25.0|
|vscode-dotnet-runtime|ms-dotnettools|1.7.2|ms-dotnettools.vscode-dotnet-runtime-1.7.2|
|vscode-eslint|dbaeumer|2.4.2|dbaeumer.vscode-eslint-2.4.2|
|vscode-jest|Orta|5.2.3|orta.vscode-jest-5.2.3|
|vscodeintellicode-csharp|ms-dotnettools|0.1.26|ms-dotnettools.vscodeintellicode-csharp-0.1.26-win32-x64|;

</details>

**Comment by dibarbet** [comment]
Solution explorer is owned by devkit, closing this in favor of https://github.com/microsoft/vscode-dotnettools/issues/517
