### ISSUE TITLE
With v2.1.2 syntax highlighting and cmd-click for classes broke

### ISSUE THREAD

**Issue by michaelmarziani** [dotnet/vscode-csharp#6346]
Type: <b>Bug</b>

## Issue Description ##
In the new version as of this writing, v2.1.2, classes are (again) no longer highlighted as they were before, and you can no longer cmd-click on the class name to go to the definition. This same thing happened upon release of v2.0.320, subsequently fixed in v2.0.357. I reported this bug just over a month ago on Aug 3 (#6016).

Reverting to 2.0.436 restores the functionality.

## Steps to Reproduce ##
Install the new version.

## Expected Behavior ##
Classes are highlighted an cmd-clickable.

## Actual Behavior ##
Classes are not highlighted in green as before, and are not cmd-clickable.

## Logs ##
Zip of entire extensions log folder attached with `dotnet.server.trace` on.
        
### C# log ###
<details>
Failed to find dotnet info from path, falling back to acquire runtime via ms-dotnettools.vscode-dotnet-runtime
The architecture of the .NET runtime (undefined) does not match the architecture of the extension (arm64).
Dotnet path: /Users/mmarziani/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.10/dotnet
Activating C# standalone...
Starting server at /Users/mmarziani/.vscode/extensions/ms-dotnettools.csharp-2.1.2-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.LanguageServer.dll
Server arguments /Users/mmarziani/.vscode/extensions/ms-dotnettools.csharp-2.1.2-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.LanguageServer.dll --logLevel Trace --telemetryLevel off --extensionLogDirectory /Users/mmarziani/Library/Application Support/Code/logs/20230912T075113/window5/exthost/ms-dotnettools.csharp
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /Users/mmarziani/.vscode/extensions/ms-dotnettools.csharp-2.1.2-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.Remote.Workspaces.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /Users/mmarziani/.vscode/extensions/ms-dotnettools.csharp-2.1.2-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.CSharp.Workspaces.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /Users/mmarziani/.vscode/extensions/ms-dotnettools.csharp-2.1.2-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.CSharp.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /Users/mmarziani/.vscode/extensions/ms-dotnettools.csharp-2.1.2-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.Razor.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /Users/mmarziani/.vscode/extensions/ms-dotnettools.csharp-2.1.2-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.Scripting.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /Users/mmarziani/.vscode/extensions/ms-dotnettools.csharp-2.1.2-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.Workspaces.MSBuild.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /Users/mmarziani/.vscode/extensions/ms-dotnettools.csharp-2.1.2-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.Elfie.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /Users/mmarziani/.vscode/extensions/ms-dotnettools.csharp-2.1.2-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /Users/mmarziani/.vscode/extensions/ms-dotnettools.csharp-2.1.2-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.CSharp.Features.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /Users/mmarziani/.vscode/extensions/ms-dotnettools.csharp-2.1.2-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.Workspaces.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /Users/mmarziani/.vscode/extensions/ms-dotnettools.csharp-2.1.2-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.AnalyzerUtilities.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /Users/mmarziani/.vscode/extensions/ms-dotnettools.csharp-2.1.2-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.Features.dll added to workspace.
[Info  - 15:52:16] [Program]Language server initialized
[LanguageServerHost][01:52:16.144][Start]initialize
[LanguageServerHost][01:52:16.149][Start]Initialize
[LanguageServerHost][01:52:16.175][End]Initialize
[LanguageServerHost][01:52:16.194][End]initialize
[LanguageServerHost][01:52:16.196][Start]initialized
[LanguageServerHost][01:52:16.246][End]initialized
[LanguageServerHost][01:52:16.246][Start]textDocument/didOpen
[LanguageServerHost]didOpen for file:///Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs
[LanguageServerHost][01:52:16.250][End]textDocument/didOpen
[LanguageServerHost]Could not find 'file:///Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs'.  Searched Host
[LanguageServerHost][01:52:16.282][Start]textDocument/diagnostic
[LanguageServerHost]PublicDocumentPullDiagnosticsHandler(category: , source: ) started getting diagnostics
[LanguageServerHost]previousResults.Length=0
[LanguageServerHost]Processing 1 documents
[LanguageServerHost][01:52:16.292][Start]workspace/diagnostic
[LanguageServerHost]/Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs found in workspace MiscellaneousFiles
[LanguageServerHost]PublicWorkspacePullDiagnosticsHandler(category: , source: ) started getting diagnostics
[LanguageServerHost][01:52:16.294][Start]textDocument/codeAction
[LanguageServerHost]/Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs found in workspace MiscellaneousFiles
[LanguageServerHost][01:52:16.295][Start]textDocument/inlayHint
[LanguageServerHost][01:52:16.295][Start]project/open
[LanguageServerHost]previousResults.Length=0
[LanguageServerHost]Processing 0 documents
[LanguageServerHost]Closing workspace/diagnostics request
No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet/download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
[LanguageServerHost]Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.Public.PublicWorkspacePullDiagnosticsHandler finished getting diagnostics
[LanguageServerHost][01:52:16.303][End]workspace/diagnostic
[Error - 15:52:16] [LanguageServerHost]System.InvalidOperationException: Failed to find all versions of .NET Core MSBuild. Call to hostfxr_resolve_sdk2. There may be more details in stderr.
   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetSdkFromGlobalSettings(String workingDirectory)
   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetDotNetBasePaths(String workingDirectory)+MoveNext()
   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetInstances(String workingDirectory)+MoveNext()
   at Microsoft.Build.Locator.MSBuildLocator.GetInstances(VisualStudioInstanceQueryOptions options)+MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.LanguageServerProjectSystem.TryEnsureMSBuildLoadedAsync(String workingDirectory) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs:line 159
   at Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.LanguageServerProjectSystem.OpenProjectsAsync(ImmutableArray`1 projectFilePaths) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs:line 131
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 136
[LanguageServerHost][01:52:16.309][End]textDocument/inlayHint
[LanguageServerHost][01:52:16.310][End]project/open
[LanguageServerHost]Found 0 diagnostics for DocumentDiagnosticSource: /Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs in Miscellaneous Files
[LanguageServerHost]Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.Public.PublicDocumentPullDiagnosticsHandler finished getting diagnostics
[LanguageServerHost][01:52:16.352][End]textDocument/diagnostic
[LanguageServerHost]/Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs found in workspace MiscellaneousFiles
[LanguageServerHost][01:52:16.353][Start]textDocument/semanticTokens/range
[LanguageServerHost]/Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs found in workspace MiscellaneousFiles
[LanguageServerHost][01:52:16.502][Start]textDocument/foldingRange
[LanguageServerHost][01:52:16.525][End]textDocument/foldingRange
[LanguageServerHost][01:52:16.542][End]textDocument/codeAction
[LanguageServerHost]/Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs found in workspace MiscellaneousFiles
[LanguageServerHost][01:52:16.576][Start]textDocument/codeLens
[LanguageServerHost][01:52:16.585][End]textDocument/codeLens
[LanguageServerHost]/Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs found in workspace MiscellaneousFiles
[LanguageServerHost][01:52:16.629][Start]textDocument/inlayHint
[LanguageServerHost][01:52:16.629][End]textDocument/inlayHint
[LanguageServerHost][01:52:16.720][End]textDocument/semanticTokens/range
[LanguageServerHost]/Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs found in workspace MiscellaneousFiles
[LanguageServerHost][01:52:16.721][Start]textDocument/codeAction
[LanguageServerHost]/Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs found in workspace MiscellaneousFiles
[LanguageServerHost][01:52:16.723][Start]textDocument/documentSymbol
[LanguageServerHost][01:52:16.725][End]textDocument/codeAction
[LanguageServerHost]/Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs found in workspace MiscellaneousFiles
[LanguageServerHost][01:52:16.742][Start]textDocument/semanticTokens/range
[LanguageServerHost][01:52:16.747][End]textDocument/documentSymbol
[LanguageServerHost][01:52:16.762][End]textDocument/semanticTokens/range
[LanguageServerHost]/Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs found in workspace MiscellaneousFiles
[LanguageServerHost][01:52:16.913][Start]textDocument/hover
[LanguageServerHost][01:52:16.930][End]textDocument/hover
[LanguageServerHost]/Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs found in workspace MiscellaneousFiles
[LanguageServerHost][01:52:16.970][Start]codeLens/resolve
[LanguageServerHost][01:52:17.069][End]codeLens/resolve
[LanguageServerHost]/Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs found in workspace MiscellaneousFiles
[LanguageServerHost][01:52:18.310][Start]textDocument/diagnostic
[LanguageServerHost]PublicDocumentPullDiagnosticsHandler(category: , source: ) started getting diagnostics
[LanguageServerHost]previousResults.Length=1
[LanguageServerHost]Processing 1 documents
[LanguageServerHost]Diagnostics were unchanged for DocumentDiagnosticSource: /Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs in Miscellaneous Files
[LanguageServerHost]Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.Public.PublicDocumentPullDiagnosticsHandler finished getting diagnostics
[LanguageServerHost][01:52:18.317][Start]workspace/diagnostic
[LanguageServerHost]PublicWorkspacePullDiagnosticsHandler(category: , source: ) started getting diagnostics
[LanguageServerHost]previousResults.Length=0
[LanguageServerHost]Processing 0 documents
[LanguageServerHost][01:52:18.318][End]textDocument/diagnostic
[LanguageServerHost]/Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs found in workspace MiscellaneousFiles
[LanguageServerHost][01:52:18.690][Start]textDocument/codeLens
[LanguageServerHost][01:52:18.691][End]textDocument/codeLens
[LanguageServerHost]/Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs found in workspace MiscellaneousFiles
[LanguageServerHost][01:52:19.071][Start]codeLens/resolve
[LanguageServerHost][01:52:19.073][End]codeLens/resolve
[LanguageServerHost]/Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs found in workspace MiscellaneousFiles
[LanguageServerHost][01:52:58.488][Start]textDocument/codeLens
[LanguageServerHost][01:52:58.490][End]textDocument/codeLens
[LanguageServerHost]/Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs found in workspace MiscellaneousFiles
[LanguageServerHost][01:52:58.875][Start]codeLens/resolve
[LanguageServerHost][01:52:58.877][End]codeLens/resolve
Failed to find dotnet info from path, falling back to acquire runtime via ms-dotnettools.vscode-dotnet-runtime
The architecture of the .NET runtime (undefined) does not match the architecture of the extension (arm64).
[LanguageServerHost]/Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs found in workspace MiscellaneousFiles
[LanguageServerHost][01:53:03.936][Start]textDocument/codeLens
[LanguageServerHost][01:53:03.937][End]textDocument/codeLens
[LanguageServerHost]/Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs found in workspace MiscellaneousFiles
[LanguageServerHost][01:53:04.320][Start]codeLens/resolve
[LanguageServerHost][01:53:04.324][End]codeLens/resolve
[LanguageServerHost]/Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs found in workspace MiscellaneousFiles
[LanguageServerHost][01:53:13.413][Start]textDocument/codeLens
[LanguageServerHost][01:53:13.414][End]textDocument/codeLens
[LanguageServerHost]/Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs found in workspace MiscellaneousFiles
[LanguageServerHost][01:53:13.793][Start]codeLens/resolve
[LanguageServerHost][01:53:13.795][End]codeLens/resolve
[LanguageServerHost]/Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs found in workspace MiscellaneousFiles
[LanguageServerHost][01:53:16.619][Start]textDocument/diagnostic
[LanguageServerHost]PublicDocumentPullDiagnosticsHandler(category: , source: ) started getting diagnostics
[LanguageServerHost]previousResults.Length=1
[LanguageServerHost]Processing 1 documents
[LanguageServerHost]Diagnostics were unchanged for DocumentDiagnosticSource: /Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs in Miscellaneous Files
[LanguageServerHost]Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.Public.PublicDocumentPullDiagnosticsHandler finished getting diagnostics
[LanguageServerHost][01:53:16.619][End]textDocument/diagnostic
[LanguageServerHost]/Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs found in workspace MiscellaneousFiles
[LanguageServerHost][01:58:36.822][Start]textDocument/codeAction
[LanguageServerHost][01:58:36.830][End]textDocument/codeAction
[LanguageServerHost]/Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs found in workspace MiscellaneousFiles
[LanguageServerHost][01:58:36.877][Start]textDocument/inlayHint
[LanguageServerHost][01:58:36.877][End]textDocument/inlayHint
[LanguageServerHost]/Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs found in workspace MiscellaneousFiles
[LanguageServerHost][01:58:37.000][Start]textDocument/semanticTokens/range
[LanguageServerHost][01:58:37.016][End]textDocument/semanticTokens/range
[LanguageServerHost]/Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs found in workspace MiscellaneousFiles
[LanguageServerHost][01:58:37.059][Start]textDocument/codeAction
[LanguageServerHost][01:58:37.060][End]textDocument/codeAction
[LanguageServerHost]/Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs found in workspace MiscellaneousFiles
[LanguageServerHost][01:58:37.097][Start]textDocument/foldingRange
[LanguageServerHost][01:58:37.099][End]textDocument/foldingRange
[LanguageServerHost]/Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs found in workspace MiscellaneousFiles
[LanguageServerHost][01:58:37.192][Start]textDocument/codeLens
[LanguageServerHost][01:58:37.192][End]textDocument/codeLens
[LanguageServerHost]/Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs found in workspace MiscellaneousFiles
[LanguageServerHost][01:58:37.570][Start]codeLens/resolve
[LanguageServerHost][01:58:37.571][End]codeLens/resolve
[LanguageServerHost]/Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs found in workspace MiscellaneousFiles
[LanguageServerHost][01:58:40.208][Start]textDocument/inlayHint
[LanguageServerHost][01:58:40.208][End]textDocument/inlayHint
[LanguageServerHost]/Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs found in workspace MiscellaneousFiles
[LanguageServerHost][01:58:40.315][Start]textDocument/semanticTokens/range
[LanguageServerHost][01:58:40.326][End]textDocument/semanticTokens/range
[LanguageServerHost]/Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs found in workspace MiscellaneousFiles
[LanguageServerHost][01:58:40.408][Start]textDocument/diagnostic
[LanguageServerHost]PublicDocumentPullDiagnosticsHandler(category: , source: ) started getting diagnostics
[LanguageServerHost]previousResults.Length=1
[LanguageServerHost]Processing 1 documents
[LanguageServerHost]Diagnostics were unchanged for DocumentDiagnosticSource: /Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs in Miscellaneous Files
[LanguageServerHost]Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.Public.PublicDocumentPullDiagnosticsHandler finished getting diagnostics
[LanguageServerHost][01:58:40.408][End]textDocument/diagnostic
[LanguageServerHost]/Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs found in workspace MiscellaneousFiles
[LanguageServerHost][01:59:08.841][Start]textDocument/diagnostic
[LanguageServerHost]PublicDocumentPullDiagnosticsHandler(category: , source: ) started getting diagnostics
[LanguageServerHost]previousResults.Length=1
[LanguageServerHost]Processing 1 documents
[LanguageServerHost]Diagnostics were unchanged for DocumentDiagnosticSource: /Users/mmarziani/dev/code/slate/Okinawa/JwtIdentityAuthApi/Controllers/A204CloseAssetController.cs in Miscellaneous Files
[LanguageServerHost]Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.Public.PublicDocumentPullDiagnosticsHandler finished getting diagnostics
[LanguageServerHost][01:59:08.842][End]textDocument/diagnostic
</details>

### C# LSP Trace Logs ###
<details>
All extension logs are in attached .zip file.
</details>

## Environment information ##

**VSCode version**: 1.81.1
**C# Extension**: 2.1.2
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.5
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.202/

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

.NET SDKs installed:
  6.0.202 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|azure-account|ms-vscode|0.11.5|ms-vscode.azure-account-0.11.5|
|copilot|GitHub|1.110.389|github.copilot-1.110.389|
|copilot-chat|GitHub|0.6.0|github.copilot-chat-0.6.0|
|csharp|ms-dotnettools|2.1.2|ms-dotnettools.csharp-2.1.2-darwin-arm64|
|npm-intellisense|christian-kohler|1.4.4|christian-kohler.npm-intellisense-1.4.4|
|path-intellisense|christian-kohler|2.8.4|christian-kohler.path-intellisense-2.8.4|
|prettier-vscode|esbenp|10.1.0|esbenp.prettier-vscode-10.1.0|
|todo-tree|Gruntfuggly|0.0.226|gruntfuggly.todo-tree-0.0.226|
|vscode-azureappservice|ms-azuretools|0.25.0|ms-azuretools.vscode-azureappservice-0.25.0|
|vscode-azureresourcegroups|ms-azuretools|0.7.5|ms-azuretools.vscode-azureresourcegroups-0.7.5|
|vscode-dotnet-runtime|ms-dotnettools|1.7.2|ms-dotnettools.vscode-dotnet-runtime-1.7.2|
|vscode-eslint|dbaeumer|2.4.2|dbaeumer.vscode-eslint-2.4.2|;

</details>

Extension version: 2.1.2
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:40:25.698Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|16.00GB (0.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

[exthost.zip](https://github.com/dotnet/vscode-csharp/files/12587282/exthost.zip)

**Comment by dibarbet** [comment]
Thanks - we've tracked the issue down to an update to one of our dependencies.  As a temporary workaround until we fix the issue, installing the arm64 .NET 7 SDK (alongside the .net6 SDK) should fix the project loading

Closing as a duplicate https://github.com/dotnet/vscode-csharp/issues/6346

**Comment by michaelmarziani** [comment]
@dibarbet Thanks for the workaround, David. Unless you'd like me to try installing the arm64 .NET 7 SDK for confirmation of the workaround, I'm happy to just keep using the last working version of the extension until a fix is released.

**Comment by dibarbet** [comment]
> @dibarbet Thanks for the workaround, David. Unless you'd like me to try installing the arm64 .NET 7 SDK for confirmation of the workaround, I'm happy to just keep using the last working version of the extension until a fix is released.

No need, if you have something working stick with that!
