### ISSUE TITLE
Analyzers show "Roslyn" in the messaging, confusing new users

### ISSUE THREAD

**Issue by timheuer** [dotnet/vscode-csharp#6347]
From vscode-dotnettools created by [timheuer](https://github.com/timheuer): microsoft/vscode-dotnettools#511  

### Describe the Issue

When an analyzer shows in the editor surface it says "Roslyn" next to the message code:
![image](https://github.com/microsoft/vscode-dotnettools/assets/4821/d13ef2c5-9ce2-403b-876a-94c457ec1f79)

To new users for .NET this is confusing as this is not a term we put in front of any of our learning materials.  In contrast, Visual Studio does not surface this:
![image](https://github.com/microsoft/vscode-dotnettools/assets/4821/a9c113d4-fb54-4c1c-b62b-d7539a312938)

### Steps To Reproduce

Triggers something with an analyzer:
`int[] myNumbers = new[] {1,2,3];`

### Expected Behavior

Unfamiliar terms with no definition shouldn't be shown and suppressed.

Recommendation: if this is a 'user agent' type string we should consider a different name ("C#?" or just remove Roslyn from this view

**Comment by dibarbet** [comment]
Fix in https://github.com/dotnet/roslyn/pull/69939
