### ISSUE TITLE
[BUG] Documentation Xml Inline Code Contains Escape Characters

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/vscode-csharp#6352]
From vscode-dotnettools created by [Number-3434](https://github.com/Number-3434): microsoft/vscode-dotnettools#456  

Type: <b>Bug</b>

Code examples in documentation tags contain HTML.

E.g.
```
/// <summary>
/// <code>
/// 	var e = 0;
/// 	e += 1;
/// </code>
/// </summary>
public static void MyMethod () { }
```
...shows up as:
```
var&nbsp;e&nbsp;=&nbsp;0;
e&nbsp;\+=&nbsp;1; 
```
in the editor language hover.

Extension version: 0.3.21
VS Code version: Code 1.81.1 (Universal) (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:20:33.924Z)
OS version: Darwin x64 22.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|11, 12, 8|
|Memory (System)|16.00GB (0.49GB free)|
|Process Argv|--crash-reporter-id e4f569aa-2d6f-475d-805e-ac24d24373c8|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
962ge761:30823813
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572

```

</details>

**Comment by dibarbet** [comment]
This should no longer be an issue in the latest version of the extension
![image](https://github.com/dotnet/vscode-csharp/assets/5749229/c1c8f7ad-8d0c-4c3d-bf7b-dc040bda3a38)
