### ISSUE TITLE
MsBuild (dotnet build) is showing 571 warning, but Problems List only 116

### ISSUE THREAD

**Issue by josefsirucka** [dotnet/vscode-csharp#6355]
I have a solution with 5 projects.

## Environment data
Vs.code Version:
Version: 1.81.0 (user setup)
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:37:13.485Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

`dotnet --info` output:

.NET SDK:
 Version:   7.0.308
 Commit:    f6a2f50f2d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.308\

Host:
  Version:      7.0.11
  Architecture: x64
  Commit:       ecb34f85ec

.NET SDKs installed:
  7.0.305 [C:\Program Files\dotnet\sdk]
  7.0.308 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

VS Code version:
C# Extension version: v2.1.2

I Also use Roslynator v4.5.0

Firstly I have set the configuration to load diagnostics (both) to Load Entire Solution

## Expected  behavior
The problem lists will contain all messages as seen when dotnet build

## Actual behavior
I have wait a lot of time - and the problems are very slowly loading (but now it stopped in 139 problems...)
And even Roslynator Analyzers seems to be not loaded.

I have this Omnisharp.json - where there are analyzers from roslynator.

{
    "RoslynExtensionsOptions": {
        "EnableAnalyzersSupport": true,
        "LocationPaths": [
            "c:/Users/josef/.vscode/extensions/josefpihrt-vscode.roslynator-4.5.0/roslyn/common",
            "c:/Users/josef/.vscode/extensions/josefpihrt-vscode.roslynator-4.5.0/roslyn/analyzers",
            "c:/Users/josef/.vscode/extensions/josefpihrt-vscode.roslynator-4.5.0/roslyn/refactorings",
            "c:/Users/josef/.vscode/extensions/josefpihrt-vscode.roslynator-4.5.0/roslyn/fixes"
        ]
    },
    "FormattingOptions": {
        "newLine": "\n",
        "useTabs": false,
        "tabSize": 4,
        "indentationSize": 4,
        "NewLinesForBracesInLambdaExpressionBody": true,
        "NewLinesForBracesInAnonymousMethods": true,
        "NewLinesForBracesInAnonymousTypes": true,
        "NewLinesForBracesInControlBlocks": true,
        "NewLinesForBracesInTypes": true,
        "NewLinesForBracesInMethods": true,
        "NewLinesForBracesInProperties": true,
        "NewLinesForBracesInAccessors": true,
        "NewLineForElse": true,
        "NewLineForCatch": true,
        "NewLineForFinally": true,
        "NewLineForMembersInObjectInit": true,
        "NewLineForMembersInAnonymousTypes": true,
        "NewLineForClausesInQuery": true
    }
}

Before C# Version v2+ it was working properly in omnisharp.

I have tried to enable and disable omnisharp, but lot of problems still missing in the list...

**Comment by dibarbet** [comment]
A couple questions
1.  Are the missing errors in the problems list from closed files?
2.  What are the values of 
<img width="401" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/5749229/bd6eec92-3073-4e39-b2e0-0445076ec3ec">

If you wouldn't mind setting `dotnet.server.trace` to `Trace` and attaching both the C# logs and C# LSP trace logs here that would be useful as well

**Comment by dibarbet** [comment]
This is not actionable without the requested information.  If this still reproduces on the latest version of the extension, please re-open **with** the additional requested information.
