### ISSUE TITLE
problem with intellisense

### ISSUE THREAD

**Issue by Jayanth-YVS-31** [dotnet/vscode-csharp#6360]
Type: <b>Feature Request</b>

I am not getting any code suggestions while writing c# code on vs code for unity development.

Extension version: 2.1.2
VS Code version: Code 1.82.1 (6509174151d557a81c9d0b5f8a5a1e9274db5585, 2023-09-08T08:45:05.575Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by dibarbet** [comment]
There are some known issues loading (older) unity projects on the new version of the extension.  You have a couple options
1.  If you are on a new enough version of Unity, you can follow these steps to use the new Unity extension with C# devkit.  See https://devblogs.microsoft.com/visualstudio/announcing-the-unity-extension-for-visual-studio-code/#getting-started-with-the-unity-extension for how to update your unity project.
2. If you're not, then you can temporarily set the `dotnet.server.useOmnisharp` flag to switch back to the old server, which can load older Unity projects.

The issue tracking old style project support (the kind that used to be generated by Unity) in the new Roslyn LSP server is https://github.com/dotnet/vscode-csharp/issues/5721

Closing this issue - if you encounter problems with any of the above, feel free to re-open.
