### ISSUE TITLE
Convert to positional record fails

### ISSUE THREAD

**Issue by richlander** [dotnet/vscode-csharp#6366]
Code:

```csharp
public readonly struct EnvironmentInfo
```

Fixer suggestion:

<img width="559" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/2608468/dfc139f6-757b-4c6f-a67d-d66afba530b4">

Error:

<img width="483" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/2608468/41081f2c-f835-4aeb-880a-b5c5da2558d2">

**Comment by dibarbet** [comment]
I tried this out and wasn't able to reproduce myself - would you mind posting the C# output window logs here?  Ideally with the `dotnet.server.trace` setting set to `Trace`.

**Comment by dibarbet** [comment]
This is not actionable without the requested information.  If this still reproduces on the latest version of the extension, please re-open **with** the additional requested information.
