### ISSUE TITLE
[ERROR] Error: spawn vscode-csharp-omniSharp/extension/.omnisharp/1.37.8/run ENOENT

### ISSUE THREAD

**Issue by chidcrushev** [dotnet/vscode-csharp#6368]
Hi team,

The omnisharp server is choking and couldn't start. The architecture we have is linux-x86*64. This happens with the version 1.23.11. Does anyone know what's going on?

**Comment by JoeRobich** [comment]
A lot has changed with O# and mono since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
