### ISSUE TITLE
Website "Report Issue" links to wrong repo on "Build tools" page

### ISSUE THREAD

**Issue by xobs** [dotnet/vscode-csharp#6372]
Documentation contains a "Report issues" link that can be used to report incorrect or unclear information. However, some pages link to incorrect repositories resulting in unnecessary work as moderators close and move issues to their correct repositories. The "Report issues" (and "Request features") links should go to the correct repository.

## Steps to reproduce

1. Go to https://code.visualstudio.com/docs/csharp/build-tools to read up on the build tools
2. Notice an issue in the website
3. Click "Report issues"

## Expected  behavior

The "Report issues" link should go to a link where issues can be reported, which in this case is https://github.com/microsoft/vscode-dotnettools/issues/528

## Actual behavior

The "Report issues" link goes to this repository, which is incorrect.

## Additional context

An issue was opened at https://github.com/dotnet/vscode-csharp/issues/6363#issuecomment-1719972303 as instructed by the documentation, however this issue was moved to a different repository.

**Comment by dibarbet** [comment]
@xobs are you referring to the links in the side bar? e.g.
<img width="240" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/5749229/ed56c74e-287f-4e93-b57b-8003cb8e7e8c">

If so, for me those go to https://github.com/Microsoft/vscode/issues which I think is correct

**Comment by xobs** [comment]
That's what I'm referring to, yes. The issue I'm reporting is that when I followed the link and reported an issue, I was told that this wasn't the correct repository. I opened this issue because I followed that link to report a documentation problem (in that the experience didn't match the documentation), but was told that the documentation is managed by the extension and not the main repository.

It may be that it's expected that this repository does a lot of triaging, and that it is acceptable for people to be filing issues for languages here only to have issues forwarded to the extension. If that's the case, then please feel free to close this issue as WONTFIX.

**Comment by dibarbet** [comment]
Yeah I think things here are generally working as expected -
1.  We don't control the report issue links on the docs page - that always goes to the vscode repo (no matter which docs page you're on).
2.  Its totally fine and understandable that C# devkit issues get reported here, or C# issues on the c# devkit repo.  The line between them is blurry and we don't expect that issues always get filed in the correct place.  It's on us to move them to the correct location.
