### ISSUE TITLE
SYSLIB0049 warning -> 404

### ISSUE THREAD

**Issue by richlander** [dotnet/vscode-csharp#6378]
https://aka.ms/dotnet-warnings/SYSLIB0049

<img width="567" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/2608468/06eb1aa5-271e-4f64-b3ad-60b97c1baf13">

**Comment by dibarbet** [comment]
This is working in the latest release version - clicking the SYSLIB0049 link directs me to https://learn.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib0049
