### ISSUE TITLE
Run/Debug do not work with C# Devkit, despite it detecting my .NET SDK/Runtime (WSL2 Ubuntu)

### ISSUE THREAD

**Issue by GavinRay97** [dotnet/vscode-csharp#6379]
## Issue Description ##
When I try to run/debug a basic `dotnet new console` application, the following error is displayed in the `Debug Console` panel:
```ps1
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
You must install .NET to run this application.

App: /home/user/projects/dotnet-database/bin/Debug/net8.0/dotnet-database
Architecture: x64
App host version: 8.0.0-rc.1.23419.4
.NET location: Not found

Learn more:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=linux-x64&os=ubuntu.23.10&apphost_version=8.0.0-rc.1.23419.4
```

The output is:
```ps1
Executing task: dotnet build /home/user/projects/dotnet-database/dotnet-database.csproj /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary 

MSBuild version 17.8.0-preview-23418-03+0125fc9fb for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
/home/user/.dotnet/sdk/8.0.100-rc.1.23463.5/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(311,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/home/user/projects/dotnet-database/dotnet-database.csproj]
  dotnet-database -> /home/user/projects/dotnet-database/bin/Debug/net8.0/dotnet-database.dll
```

However, using `dotnet run` and `dotnet sdk list` works fine:
```
$ dotnet run
Hello, World!

$ dotnet --list-sdks
7.0.400 [/home/user/.dotnet/sdk]
8.0.100-preview.7.23376.3 [/home/user/.dotnet/sdk]
8.0.100-rc.1.23463.5 [/home/user/.dotnet/sdk]
```

### C# log ###
<details>
```
Dotnet path: /home/user/.dotnet/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
[Info  - 2:55:35 PM] [Program]Language server initialized
```
</details>

### C# LSP Trace Logs ###
<details>
</details>

## Environment information ##

**VSCode version**: 1.83.0-insider
**C# Extension**: 2.1.2
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   8.0.100-rc.1.23463.5
 Commit:    e7f4de8816

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  23.10
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /home/user/.dotnet/sdk/8.0.100-rc.1.23463.5/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-rc.1.23419.4
  Architecture: x64
  Commit:       92959931a3
  RID:          linux-x64

.NET SDKs installed:
  7.0.400 [/home/user/.dotnet/sdk]
  8.0.100-preview.7.23376.3 [/home/user/.dotnet/sdk]
  8.0.100-rc.1.23463.5 [/home/user/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.10 [/home/user/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.7.23375.9 [/home/user/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.1.23421.29 [/home/user/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.10 [/home/user/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.7.23375.6 [/home/user/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.1.23419.4 [/home/user/.dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|cmake|twxs|0.0.17|twxs.cmake-0.0.17|
|cmake-tools|ms-vscode|1.16.5|ms-vscode.cmake-tools-1.16.5|
|copilot|GitHub|1.111.414|github.copilot-1.111.414|
|copilot-chat|GitHub|0.8.2023091501|github.copilot-chat-0.8.2023091501|
|copilot-labs|GitHub|0.15.1019|github.copilot-labs-0.15.1019|
|cpptools|ms-vscode|1.17.5|ms-vscode.cpptools-1.17.5-linux-x64|
|csdevkit|ms-dotnettools|0.5.47|ms-dotnettools.csdevkit-0.5.47-linux-x64|
|csharp|ms-dotnettools|2.1.2|ms-dotnettools.csharp-2.1.2-linux-x64|
|git-graph|mhutchie|1.30.0|mhutchie.git-graph-1.30.0|
|intellicode-api-usage-examples|VisualStudioExptTeam|0.2.8|visualstudioexptteam.intellicode-api-usage-examples-0.2.8|
|java|redhat|1.23.2023091504|redhat.java-1.23.2023091504-linux-x64|
|kotlin|fwcd|0.2.31|fwcd.kotlin-0.2.31|
|markdown-all-in-one|yzhang|3.5.1|yzhang.markdown-all-in-one-3.5.1|
|prettier-vscode|esbenp|10.1.0|esbenp.prettier-vscode-10.1.0|
|quokka-vscode|WallabyJs|1.0.564|wallabyjs.quokka-vscode-1.0.564|
|test-adapter-converter|ms-vscode|0.1.8|ms-vscode.test-adapter-converter-0.1.8|
|vscode-clangd|llvm-vs-code-extensions|0.1.24|llvm-vs-code-extensions.vscode-clangd-0.1.24|
|vscode-docker|ms-azuretools|1.26.0|ms-azuretools.vscode-docker-1.26.0|
|vscode-dotnet-runtime|ms-dotnettools|1.7.3|ms-dotnettools.vscode-dotnet-runtime-1.7.3|
|vscode-gradle|vscjava|3.12.2023090704|vscjava.vscode-gradle-3.12.2023090704|
|vscode-java-debug|vscjava|0.54.2023082803|vscjava.vscode-java-debug-0.54.2023082803|
|vscode-java-dependency|vscjava|0.23.2023080400|vscjava.vscode-java-dependency-0.23.2023080400|
|vscode-java-pack|vscjava|0.25.2023091303|vscjava.vscode-java-pack-0.25.2023091303|
|vscode-java-test|vscjava|0.39.2023090502|vscjava.vscode-java-test-0.39.2023090502|
|vscode-maven|vscjava|0.42.2023080103|vscjava.vscode-maven-0.42.2023080103|
|vscode-mocha-test-adapter|hbenl|2.14.1|hbenl.vscode-mocha-test-adapter-2.14.1|
|vscode-test-explorer|hbenl|2.21.1|hbenl.vscode-test-explorer-2.21.1|
|vscodeintellicode|VisualStudioExptTeam|1.2.30|visualstudioexptteam.vscodeintellicode-1.2.30|
|vscodeintellicode-csharp|ms-dotnettools|0.1.26|ms-dotnettools.vscodeintellicode-csharp-0.1.26-linux-x64|;

</details>

**Comment by gregg-miskelly** [comment]
I believe your problem is: `App host version: 8.0.0-rc.1.23419.4`

But I am guessing it is looking for: `8.0.100-rc.1.23463.5`

**Comment by GavinRay97** [comment]
Ahh, good eye.

I'm generally unfamiliar with .NET development (the new Devkit prompted me to try the experience out), any ideas on what might be prompting this or ways to resolve?

Should I use the .NET download shell script and try to specifically fetch `8.0.100-rc.1.23463.5`, like:
```sh-session
$ ./dotnet-install.sh -v 8.0.100-rc.1.23463.5
```

**Comment by GavinRay97** [comment]
Update: Going to close this as after a VS Code auto-update it appears to be working now.

Sorry for the noise!
