### ISSUE TITLE
New types/files are not loaded until I restart vscode

### ISSUE THREAD

**Issue by verbess** [dotnet/vscode-csharp#6398]
## Environment data
`dotnet --info` output:

```
.NET SDK:
 Version:   7.0.401
 Commit:    eb26aacfec

运行时环境:
 OS Name:     Mac OS X
 OS Version:  13.5
 OS Platform: Darwin
 RID:         osx.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.401/

Host:
  Version:      7.0.11
  Architecture: x64
  Commit:       ecb34f85ec

.NET SDKs installed:
  7.0.401 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

VS Code version: 1.82.2
C# Extension version: v2.1.2

## Steps to reproduce
1. Create a new empty .NET project (console or classlib).
2. Add a file (e.g. Test.cs) with a new empty class to it (e.g. public class Test {}
3. Try to use code intellisense of the new type (class Test).

## Expected  behavior
Code intelligent suggestions should work, such as code fixes.

## Actual behavior
Code intelligent suggestions are not functioning properly; the new type (class Test) is not being loaded. Additionally, the command `.NET: Restart Language Server` does not work until I restart Visual Studio Code.

**Comment by dibarbet** [comment]
> Code intelligent suggestions are not functioning properly; the new type (class Test) is not being loaded. Additionally, the command .NET: Restart Language Server does not work until I restart Visual Studio Code.

THis is a known bug when using devkit - for now you can run reload window instead.

**Comment by verbess** [comment]
> THis is a known bug when using devkit - for now you can run reload window instead.

Thanks, that's really helpful.

**Comment by dibarbet** [comment]
This seems to be working for me in the latest version of the C# (and C# DevKit) extension - I'm able to see new files in the project.  I'm going to close this - if you're still having issues with the latest versions, please re-open and include the contents of the 'C#' output window with `dotnet.server.trace` set to `Trace` in VSCode settings.
