### ISSUE TITLE
Generating run and debug assets fails with recent version of the extension (v2.1.2)

### ISSUE THREAD

**Issue by vpetit-reimagine** [dotnet/vscode-csharp#6403]
## Environment data
`dotnet --info` output:
```
.NET SDK:
 Version:   8.0.100-rc.1.23455.8
 Commit:    e14caf947f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-rc.1.23455.8\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-rc.1.23419.4
  Architecture: x64
  Commit:       92959931a3
  RID:          win-x64

.NET SDKs installed:
  3.1.301 [C:\Program Files\dotnet\sdk]
  5.0.416 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]
  7.0.102 [C:\Program Files\dotnet\sdk]
  8.0.100-rc.1.23455.8 [C:\Program Files\dotnet\sdk]
```
VS Code version: 1.83.0-insider
C# Extension version: v2.1.2

## Steps to reproduce

1. Create a new Solution in an empty folder `dotnet new sln -n SolutionName`
2. Create a new Project with the following `dotnet new console -o ProjectName`
3. Add the Project to the Solution `dotnet sln add .\ProjectName\ProjectName.csproj`
4. Open a `.cs` file and click on the `Run and Debug` icon in left panel
5. Click on `Generate C# Assets for Build and Debug
6. See following error: `Could not locate .NET Core project in 'folder'. Assets were not generated.`

## Expected  behavior
The `.vscode/tasks.json` and `.vscode/launch.json` assets should be created to allow running and debugging the solution/projects.

## Actual behavior
The assets are not created and have to be done manually.

## Additional context
This seems to be a recent issue linked to the feature parity between Roslyn and OmniSharp as it was previously working fine.

**Comment by dibarbet** [comment]
@vpetit-reimagine are you using the `dotnet.server.useOmnisharp` flag - I did just fix a bug here which would be in the next release

**Comment by vpetit-reimagine** [comment]
> @vpetit-reimagine are you using the `dotnet.server.useOmnisharp` flag - I did just fix a bug here which would be in the next release

Yes, it is set to true

**Comment by dibarbet** [comment]
This should be fixed in the next release by https://github.com/dotnet/vscode-csharp/pull/6380
