### ISSUE TITLE
C

### ISSUE THREAD

**Issue by GuilhermeLCK** [dotnet/vscode-csharp#6412]
Type: <b>Bug</b>

### C# log ###
<details>Post the output from Output-->C# here</details>

### C# LSP Trace Logs ###
<details>Post the output from Output-->C# LSP Trace Logs here.  Requires `dotnet.server.trace` to be set to `Trace`</details>

## Environment information ##

**VSCode version**: 1.82.2
**C# Extension**: 2.1.2
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
Error running dotnet --info: Error: Command failed: C:\Program Files\dotnet\dotnet.exe --info
'C:\Program' n�o � reconhecido como um comando interno
ou externo, um programa oper�vel ou um arquivo em lotes.

'C:\Program' n�o � reconhecido como um comando interno
ou externo, um programa oper�vel ou um arquivo em lotes.
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|auto-close-tag|formulahendry|0.5.14|formulahendry.auto-close-tag-0.5.14|
|auto-complete-tag|formulahendry|0.1.0|formulahendry.auto-complete-tag-0.1.0|
|auto-rename-tag|formulahendry|0.1.10|formulahendry.auto-rename-tag-0.1.10|
|color-highlight|naumovs|2.5.0|naumovs.color-highlight-2.5.0|
|copilot|GitHub|1.114.426|github.copilot-1.114.426|
|csharp|ms-dotnettools|2.1.2|ms-dotnettools.csharp-2.1.2-win32-x64|
|in-your-face-incredible|TTOOWA|1.1.0|ttoowa.in-your-face-incredible-1.1.0|
|js-jsx-snippets|skyran|11.0.1|skyran.js-jsx-snippets-11.0.1|
|live-server|ms-vscode|0.4.9|ms-vscode.live-server-0.4.9|
|LiveServer|ritwickdey|5.7.9|ritwickdey.liveserver-5.7.9|
|material-icon-theme|PKief|4.30.1|pkief.material-icon-theme-4.30.1|
|namespace|adrianwilczynski|1.1.2|adrianwilczynski.namespace-1.1.2|
|prettier-vscode|esbenp|10.1.0|esbenp.prettier-vscode-10.1.0|
|vscode-css-formatter|aeschli|1.0.2|aeschli.vscode-css-formatter-1.0.2|
|vscode-dotnet-runtime|ms-dotnettools|1.7.3|ms-dotnettools.vscode-dotnet-runtime-1.7.3|;

</details>

Extension version: 2.1.2
VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690S CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|11.92GB (5.42GB free)|
|Process Argv|--crash-reporter-id 2cb76080-06ee-48da-88cf-88ae4fbb5ad3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingt:30839829
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015cf:30829746

```

</details>

**Comment by dibarbet** [comment]
Looks like this might be an accidentally filed issue?
