### ISSUE TITLE
Symbols requested through 'vscode.executeDocumentSymbolProvider' don't contain Namespace

### ISSUE THREAD

**Issue by CalvinAllen** [dotnet/vscode-csharp#6424]
In a VSCode extension that makes use of this C# extension, and its underlying LSP, we were previously able to request symbols for a document using the `vscode.executeDocumentSymbolProvider` built-in command.

With OmniSharp, we were able to do some basic filtering and matching using `SymbolKind.Module` -

```
allSymbols.find(_ => _.kind === SymbolKind.Module);
```

(Module, in this case, was actually Namespace)

It seems with the new LSP, that this is no longer working (nor are other kinds of Symbols, Namespace, Package, etc.)

Due to this, we are now having to re-read the file and parse the namespace using a regular expression.

## Environment data
`dotnet --info` output:
```
.NET SDK (reflecting any global.json):
 Version:   6.0.300
 Commit:    8473146e7d

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.5
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.300/

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  6.0.300 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```
Also on this machine -
```
.NET SDK:
 Version:   7.0.306
 Commit:    f500069cb7

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.5
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.306/

Host:
  Version:      7.0.9
  Architecture: arm64
  Commit:       8e9a17b221

.NET SDKs installed:
  7.0.302 [/usr/local/share/dotnet/sdk]
  7.0.304 [/usr/local/share/dotnet/sdk]
  7.0.306 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found
```

VS Code version: `1.82.2`
C# Extension version: `2.3.27`

## Expected  behavior
```
allSymbols.find(_ => _.kind === SymbolKind.Namespace);
```

Should return at least one symbol from in the file being requested

## Actual behavior
No results are found

**Comment by dibarbet** [comment]
We're most likely not going to modify what the document symbols request returns - as that affects how we render the outline in the UI.

However, we are planning on adding a public API for both the server and extension that will allow you to run custom code in the server to retrieve information your extension cares about.  See https://github.com/dotnet/roslyn/issues/68696.  In that future, it would be possible to write a small custom LSP message handler that returns whatever information you need and call it from your extension.

Going to close this to track as part of the public API request in https://github.com/dotnet/roslyn/issues/68696
