### ISSUE TITLE
Release notes for 2.4.4

### ISSUE THREAD

**Issue by lonix1** [dotnet/vscode-csharp#6455]
VSCode is offering me 2.4.4, but there are no release notes / changelog.

We can't upgrade without knowing what's in the new version. Does anyone know?

**Comment by dibarbet** [comment]
See https://github.com/dotnet/vscode-csharp/releases/tag/v2.4.4

This is a very small release to fix an interaction with the Devkit prerelease build.

The changelog in the extension marketplace should always be up to date - https://marketplace.visualstudio.com/items/ms-dotnettools.csharp/changelog
