### ISSUE TITLE
rg.exe loads CPU on 100%

### ISSUE THREAD

**Issue by irvnriir** [dotnet/vscode-csharp#6460]
## Steps to reproduce

possibly happens in relation to cycled Symbolic Links . or just with alot of content .

## Expected  behavior

recursing trough content in opened folders shouldn't ever be a default behavior .

## Additional context

setting `omnisharp.projectFilesExcludePattern` to `**` and changing:
```
csharp.debug.symbolOptions.moduleFilter.includeSymbolsNextToModules
csharp.debug.symbolOptions.moduleFilter.mode
```

didn't solve it .

**Comment by dibarbet** [comment]
The C# extension shouldn't be involved here, `rg.exe` looks like it is associated with VSCode's built in search.  For fixing issues related to vscode search, see https://github.com/microsoft/vscode/wiki/Search-Issues#slow-search-rg-running-for-a-long-time-or-consuming-lots-of-cpumemory 

It looks like you can configure it to not follow sym links or exclude files.

**Comment by irvnriir** [comment]
@dibarbet this happens only and instantly after i run vsc with this extension on, do you think i picked a repo of random extension ?

**Comment by irvnriir** [comment]
even if it would be reasoned to fix by disabling symlinks following, this would be done for this extension, not system wise, im sure if the rg has a config for it, its not per extension/call/thought .

**Comment by JoeRobich** [comment]
@irvnriir What are you doing when you see this behavior? Have you just opened a folder containing C# code and performed no other actions? Are you searching the C# code in the side bar? If it happens when only opening a folder, I wonder if the extension activation triggers might be causing the search.

Is there a repo that we could use to reproduce this behavior?

**Comment by irvnriir** [comment]
@JoeRobich the issue happens when one of:

1. .
    * dotnet.server.useOmnisharp on not off
    * omnisharp.autoStart on not off
    * omnisharp.useModernNet on or off
    * omnisharp.enableLspDriver on or off
2. dotnet.server.useOmnisharp off not on, or ms-dotnettools.csdevkit is installed

it doesn't seem to be related to cycled Reparse Points, just to amount of content in folders in workspace .

**Comment by irvnriir** [comment]
it happens when i have a folder with alot of .cs and a very large folder in the same workspace (including new workspaces and etc) . can be related to: amount of certain cross-linking Reparse Points, or combination of large amounts of certain files . (i tried alot to figure this out)

its hard to find the issue's condition, but easy to determine it's source: `recursing trough content in opened folders should never be a default behavior .` .

(one of opened files being .cs is required for Omnisharp to start and possibly come to the issue)

**Comment by JoeRobich** [comment]
@irvnriir Sorry, I still don't think I understand your scenario. 

> `recursing trough content in opened folders should never be a default behavior .`

The C# extension does not perform any searches with ripgrep nor does O# language server nor Roslyn LSP. The file search I mentioned before simply looks at the filesystem for files with certain extensions, which I realize now are unrelated.

If you are performing a search of your code and seeing this behavior, I would recommend filing an issue against VS Code using these steps https://github.com/microsoft/vscode/wiki/Search-Issues#filing-a-search-issue

**Comment by irvnriir** [comment]
apparently it does, there are prob many items in VSC API which: the extension use, and end up using rg.exe .

(freezes are due to that recorder gets no resources)
https://pixeldrain.com/u/QjSGxNwF

**Comment by irvnriir** [comment]
maybe one will open this issue which is clearly caused by this Extension and not resolved ?

**Comment by irvnriir** [comment]
`dotnet.preferVisualStudioCodeFileSystemWatcher` also doesn't affect this .
