### ISSUE TITLE
Two tooltips appear on top of each other during code completion

### ISSUE THREAD

**Issue by aradalvand** [dotnet/vscode-csharp#6501]
See the following video — when you type the opening parenthesis after the `.Add` method, previously you'd just see the method arguments in the code completion tooltip as expected, but now another useless/irrelevant window appears on top of that and covers it, so you have to press `Esc` to get rid of it. This happens constantly and is extremely annoying.

https://github.com/dotnet/vscode-csharp/assets/26527405/76784d79-8304-4f25-8cfa-c4a88012a9d2

## Environment data
VS Code version: 1.83.0 — e7e037083ff4455cf320e344325dacb480062c3c
C# Extension version: v2.5.30

**Comment by dibarbet** [comment]
Note - this is due to the location of the code and window size.  The signature help window is supposed to appear above the line, while the completion list appears below.  However if there is not enough space in the text editor window above, they will appear overlapped.

This behavior is defined by VSCode.  The most we could do on the extension side is have an option to disable completion in argument lists, which I'm not sure we want to do.

**Comment by aradalvand** [comment]
@dibarbet The argument list IS THE ONE THAT SHOULD BE SHOWN. Just don't show the other useless one that appears in these contexts. v1.x literally worked properly. Why can't you just do the same thing you used to?!

**Comment by aradalvand** [comment]
This is v1.26.0:

https://github.com/dotnet/vscode-csharp/assets/26527405/10af311a-ce83-4869-8f5c-cb08865a938d

**Comment by aradalvand** [comment]
This is what it looks like in v1.26.0:

https://github.com/dotnet/vscode-csharp/assets/26527405/b8bacd06-123e-434d-9575-1e7a351a746f

**Comment by DovydasNavickas** [comment]
This is still happening. No matter of the code location and where they're rendered, unless completion you need is for `AbandonedMutexException` or something else that is at the start of the alphabet, the completion is rarely what I want. I press Esc to get rid of it 100% of the time, which is annoying.
And after getting rid of the completion, typing a character gives completion again, which is when I want the completion to happen so only opening the parenthesis is where completion should not be shown.
The signature help window is what I expect to see and if there are overloads, I expect to be able to cycle through them with up/down arrows. This works only after Esc(aping) the completion window.

Are we he minority here with @aradalvand and think this behavior is counterproductive? 😄 If so, is there a setting for this that I didn't find?

**Comment by dibarbet** [comment]
Option `dotnet.completion.triggerCompletionInArgumentLists` to disable completion in argument lists added in https://github.com/dotnet/vscode-csharp/pull/7446.

This is not released yet, but should be part of next weeks prerelease update.  Will post here once it is available.

**Comment by dibarbet** [comment]
This is available in 2.45.17 prerelease.  Unchecking `dotnet.completion.triggerCompletionInArgumentLists` will prevent the completion list from showing up in argument list contexts (you will only see signature help).
