### ISSUE TITLE
Debug not working - "undefined" is not valid JSON 

### ISSUE THREAD

**Issue by ZhenyaPav** [dotnet/vscode-csharp#6504]
## Issue Description ##
When trying to run debugging, it fails with the warning ""undefined" is not valid JSON". Build tasks work fine.

## Steps to Reproduce ##
Open an empty C# project in VSCode - OSS, press F5
## Expected Behavior ##
Debug starts
## Actual Behavior ##
A warning pops up, debug does not start
### C# log ###
No logs are written in the output

## Environment information ##

**VSCode version**: 1.83.0
**C# Extension**: 2.0.436
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
ENOENT: no such file or directory, open '/home/zhenyapav/.config/Code - OSS/logs/20231008T030131/window1/exthost/ms-dotnettools.vscode-dotnet-runtime/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1696723303794.txt'</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|ansible|redhat|2.7.98|redhat.ansible-2.7.98-universal|
|csharp|muhammad-sammy|2.0.436|muhammad-sammy.csharp-2.0.436-universal|
|jinjahtml|samuelcolvin|0.20.0|samuelcolvin.jinjahtml-0.20.0-universal|
|python|ms-python|2023.18.0|ms-python.python-2023.18.0-universal|
|sweetdracula|PROxZIMA|1.0.9|proxzima.sweetdracula-1.0.9-universal|
|sweetdracula-monokai|lefd|1.1.9|lefd.sweetdracula-monokai-1.1.9-universal|
|vscode-docker|ms-azuretools|1.26.1|ms-azuretools.vscode-docker-1.26.1-universal|
|vscode-dotnet-runtime|ms-dotnettools|1.8.0|ms-dotnettools.vscode-dotnet-runtime-1.8.0-universal|
|vscode-yaml|redhat|1.14.0|redhat.vscode-yaml-1.14.0-universal|;

</details>

**Comment by ZhenyaPav** [comment]
Possibly relevant: when invoking command "Debug: Download .NET Core Debugger", I get an error
`command 'csharp.downloadDebugger' not found`

**Comment by nikola-godzilla** [comment]
Seems to be you're using different extension. There is "muhammad-sammy.csharp' in your list.
Is a fork. You may use old version 1.25.7, it works.
See https://github.com/muhammadsammy/free-omnisharp-vscode/issues/60
