### ISSUE TITLE
Better support for VSCode Icon folders in Solution Explorer

### ISSUE THREAD

**Issue by michaelstonis** [dotnet/vscode-csharp#6519]
## Is your feature request related to a problem? Please describe.
Not a problem at all, but a _very minor nice to have_. The Solution Explorer has good support for VSCode icons when displaying a file, but is inconsistent when displaying folders. VSCode icons appear to work on folders at the root of the solution, but they do not appear to work within a project.

## Describe the solution you would like
I am not familiar with how the solution explorer applies the icons to folders, but it looks like it has its own set of rules for projects (for example, C# projects have a C# icon on them). If we could look at the VSCode icons as a fallback that would be great.

## Applicable Scenarios
When opening a project with folder names that match VSCode icon configurations.

## Describe alternatives you've considered
Not sure that there is a clear alternative.

## Additional context
Below are screenshots showing differences between folders in the solution explorer and folder view.

Solution Explorer
<img width="210" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/120685/62e4b200-3cdc-48e6-952f-7390b1233883">

Folder View
<img width="195" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/120685/6d2666ff-d51d-49fd-85ba-7cde2c7f2309">

**Comment by jasonmalinowski** [comment]
Since this is a request for DevKit, I've migrated it to https://github.com/microsoft/vscode-dotnettools/issues/604.
