### ISSUE TITLE
NETSDK1206 Warning on clean build

### ISSUE THREAD

**Issue by jtsom** [dotnet/vscode-csharp#6546]
Type: <b>Bug</b>

## Issue Description ##
On a clean build, with the latest .NET 8 RC SDK 8.0.100-rc.2.23502.2,  of a simple application (`dotnet clean`, `dotnet build`) the following warning is given:

```
C:\Program Files\dotnet\sdk\8.0.100-rc.2.23502.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(284,5): warning NETSDK1206: Found version-specific or distribution-specific
 runtime identifier(s): alpine-arm, alpine-arm64, alpine-x64. Affected libraries: SQLitePCLRaw.lib.e_sqlite3. In .NET 8.0 and higher, assets for version-specific and distribution-sp 
ecific runtime identifiers will not be found by default. See https://aka.ms/dotnet/rid-usage for details. [D:\source\EF-API\EF-API\EF-API.csproj]
```

I do not include SQLite in my application, and I don't have any "distribution specific" settings set in the .csproj file.

Subsequent builds do not show this, only after a clean / build.

## Steps to Reproduce ##
Load new project, build.

## Expected Behavior ##
Do not show error

## Actual Behavior ##
Shows error

### C# log ###
<details>Using dotnet configured on PATH
Dotnet path: C:\Program Files\dotnet\dotnet.exe
Activating C# + C# Dev Kit + C# IntelliCode...
waiting for named pipe information from server...
[stdout] {"pipeName":"\\\\.\\pipe\\be7940d7-fe49-4cd4-8d6a-254a9971dd7c"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 9:31:04 AM] [Program] Language server initialized
Using dotnet configured on PATH
</details>

### C# LSP Trace Logs ###
<details>[Trace - 11:05:21 AM] Sending notification 'workspace/didChangeWatchedFiles'.
Params: {
    "changes": [
        {
            "uri": "file:///d:/source/EF-API/EF-API/obj/Debug/net8.0/EF-API.AssemblyInfo.cs",
            "type": 1
        },
        {
            "uri": "file:///d:/source/EF-API/EF-API/obj/Debug/net8.0/EF-API.GeneratedMSBuildEditorConfig.editorconfig",
            "type": 1
        },
        {
            "uri": "file:///d:/source/EF-API/EF-API/obj/Debug/net8.0/EF-API.MvcApplicationPartsAssemblyInfo.cs",
            "type": 1
        },
        {
            "uri": "file:///d:/source/EF-API/EF-API/obj/Debug/net8.0/EF-API.RazorAssemblyInfo.cs",
            "type": 1
        }
    ]
}

[Trace - 11:05:21 AM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "[LanguageServerHost] [03:05:21.300][Start]workspace/didChangeWatchedFiles"
}

[Trace - 11:05:21 AM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "[LanguageServerHost] [03:05:21.300][End]workspace/didChangeWatchedFiles"
}

</details>

## Environment information ##

**VSCode version**: 1.84.0-insider
**C# Extension**: 2.6.24
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   8.0.100-rc.2.23502.2
 Commit:    0abacfc2b6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-rc.2.23502.2\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-rc.2.23479.6
  Architecture: x64
  Commit:       0b25e38ad3

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.123 [C:\Program Files\dotnet\sdk]
  6.0.318 [C:\Program Files\dotnet\sdk]
  6.0.415 [C:\Program Files\dotnet\sdk]
  7.0.112 [C:\Program Files\dotnet\sdk]
  7.0.203 [C:\Program Files\dotnet\sdk]
  7.0.309 [C:\Program Files\dotnet\sdk]
  7.0.402 [C:\Program Files\dotnet\sdk]
  8.0.100-rc.2.23502.2 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.2.23480.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.2.23479.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-rc.2.23479.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|azure-account|ms-vscode|0.11.6|ms-vscode.azure-account-0.11.6|
|csdevkit|ms-dotnettools|0.6.3|ms-dotnettools.csdevkit-0.6.3-win32-x64|
|csharp|ms-dotnettools|2.6.24|ms-dotnettools.csharp-2.6.24-win32-x64|
|csharpextensions|kreativ-software|1.7.3|kreativ-software.csharpextensions-1.7.3|
|ecdc|mitchdenny|1.8.0|mitchdenny.ecdc-1.8.0|
|git-graph|mhutchie|1.30.0|mhutchie.git-graph-1.30.0|
|hexeditor|ms-vscode|1.9.12|ms-vscode.hexeditor-1.9.12|
|hl7tools|RobHolme|2.0.4|robholme.hl7tools-2.0.4|
|jwt-debugger|yokawasa|0.4.2|yokawasa.jwt-debugger-0.4.2|
|kanagawa|qufiwefefwoyn|1.5.1|qufiwefefwoyn.kanagawa-1.5.1|
|live-server|ms-vscode|0.4.11|ms-vscode.live-server-0.4.11|
|material-icon-theme|PKief|4.31.0|pkief.material-icon-theme-4.31.0|
|msbuild-project-tools|tintoy|0.4.9|tintoy.msbuild-project-tools-0.4.9|
|night-owl|sdras|2.0.1|sdras.night-owl-2.0.1|
|quicktype|quicktype|12.0.46|quicktype.quicktype-12.0.46|
|rainbow-csv|mechatroner|3.7.1|mechatroner.rainbow-csv-3.7.1|
|sync-scroll|dqisme|1.3.1|dqisme.sync-scroll-1.3.1|
|TabOut|albert|0.2.2|albert.tabout-0.2.2|
|vs-code-xml-format|fabianlauer|0.1.5|fabianlauer.vs-code-xml-format-0.1.5|
|vscode-azureappservice|ms-azuretools|0.25.1|ms-azuretools.vscode-azureappservice-0.25.1|
|vscode-azurefunctions|ms-azuretools|1.13.1|ms-azuretools.vscode-azurefunctions-1.13.1|
|vscode-azureresourcegroups|ms-azuretools|0.7.5|ms-azuretools.vscode-azureresourcegroups-0.7.5|
|vscode-azurestorage|ms-azuretools|0.15.3|ms-azuretools.vscode-azurestorage-0.15.3|
|vscode-base64|adamhartford|0.1.0|adamhartford.vscode-base64-0.1.0|
|vscode-cosmosdb|ms-azuretools|0.20.0|ms-azuretools.vscode-cosmosdb-0.20.0|
|vscode-dotnet-runtime|ms-dotnettools|1.8.1|ms-dotnettools.vscode-dotnet-runtime-1.8.1|
|vscode-thunder-client|rangav|2.13.5|rangav.vscode-thunder-client-2.13.5|
|vscodeintellicode|VisualStudioExptTeam|1.2.30|visualstudioexptteam.vscodeintellicode-1.2.30|
|vscodeintellicode-csharp|ms-dotnettools|0.1.26|ms-dotnettools.vscodeintellicode-csharp-0.1.26-win32-x64|;

</details>

Extension version: 2.6.24
VS Code version: Code - Insiders 1.84.0-insider (0c36b92c82064882a228487040187cfc13669c0f, 2023-10-16T05:35:39.577Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (13.54GB free)|
|Process Argv|--crash-reporter-id 362817d9-b661-4b35-92b7-fe18e5872851|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
vscrp:30624060
a9j8j154:30646983
showlangstatbar:30737417
ecj1e332:30687743
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30808721
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206
pythonmpsinfo:30859869
dsvsc015:30821418
pythontestfixt:30859590
pythonregdiag:30859652
pythonmypyd1:30859725
pythoncet0:30859736

```

</details>

**Comment by dibarbet** [comment]
@jtsom can you confirm if you're invoking the clean build via the terminal, or using build commands in vscode (if so let me know which ones)?

If using the terminal, does this reproduce without vscode opened?

**Comment by jtsom** [comment]
It happens both with the control-shift-b keystroke, and using the dotnet build command. Have not tried outside vscode but will and report back.

**Comment by marcpopMSFT** [comment]
Please see this breaking change document and the available workarounds: https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/rid-graph

**Comment by jtsom** [comment]
I read that article but the project has no RID specific stuff in it (this article is the first I've ever seen reference to it). The .csproj file is, other than using some outside packages, a standard .Net file. Compared to the .csproj file from a new application, there is little difference. I would have no idea how to deal with the "non-standard RID".

**Comment by jtsom** [comment]
I just went through and compared project files. It looks like this package is the problem:

<PackageReference Include="EfCore.SchemaCompare" Version="7.0.0" />

Removing that and the warning went away.

**Comment by dibarbet** [comment]
Closing as fixed
