### ISSUE TITLE
Old tests shown after renaming test folder/project

### ISSUE THREAD

**Issue by glen-84** [dotnet/vscode-csharp#6583]
Type: <b>Bug</b>

## Issue Description ##

![image](https://github.com/dotnet/vscode-csharp/assets/261509/e3fbbd78-478a-4f17-a71e-8fc15d050793)

## Steps to Reproduce ##

- Rename a test folder and project using the File Explorer. (in this example, I added `Glen84.` at the beginning)

## Expected Behavior ##

- The previous tests (without the `Glen84` prefix) are removed from the Testing view.

## Actual Behavior ##

- The previous tests remain in the Testing view, and are not removed after a refresh, rebuild, restart, etc.

Where is this information stored/cached? How can I delete it?

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>
        
### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.83.1
**C# Extension**: 2.7.25
**Using OmniSharp**: true

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   8.0.100-rc.2.23502.2
 Commit:    0abacfc2b6

Runtime Environment:
 OS Name:     debian
 OS Version:  11
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /home/glen/.dotnet/sdk/8.0.100-rc.2.23502.2/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-rc.2.23479.6
  Architecture: x64
  Commit:       0b25e38ad3

.NET SDKs installed:
  7.0.401 [/home/glen/.dotnet/sdk]
  8.0.100-rc.1.23463.5 [/home/glen/.dotnet/sdk]
  8.0.100-rc.2.23502.2 [/home/glen/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.11 [/home/glen/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.1.23421.29 [/home/glen/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.2.23480.2 [/home/glen/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.11 [/home/glen/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.1.23419.4 [/home/glen/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.2.23479.6 [/home/glen/.dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/home/glen/.dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|change-case|wmaurer|1.0.0|wmaurer.change-case-1.0.0|
|code-spell-checker|streetsidesoftware|3.0.1|streetsidesoftware.code-spell-checker-3.0.1|
|csdevkit|ms-dotnettools|0.5.150|ms-dotnettools.csdevkit-0.5.150-linux-x64|
|csharp|ms-dotnettools|2.7.25|ms-dotnettools.csharp-2.7.25-linux-x64|
|EditorConfig|EditorConfig|0.16.4|editorconfig.editorconfig-0.16.4|
|gitblame|waderyan|10.5.1|waderyan.gitblame-10.5.1|
|hexeditor|ms-vscode|1.9.12|ms-vscode.hexeditor-1.9.12|
|t4-support|zbecknell|0.7.0|zbecknell.t4-support-0.7.0|
|todo-tree|Gruntfuggly|0.0.226|gruntfuggly.todo-tree-0.0.226|
|toggle-hidden|adrianwilczynski|1.0.2|adrianwilczynski.toggle-hidden-1.0.2|
|trailing-spaces|shardulm94|0.4.1|shardulm94.trailing-spaces-0.4.1|
|vscode-commons|redhat|0.0.6|redhat.vscode-commons-0.0.6|
|vscode-dotnet-runtime|ms-dotnettools|1.8.1|ms-dotnettools.vscode-dotnet-runtime-1.8.1|
|vscode-highlight|fabiospampinato|1.9.0|fabiospampinato.vscode-highlight-1.9.0|
|vscode-sort-json|richie5um2|1.20.0|richie5um2.vscode-sort-json-1.20.0|
|vscode-yaml|redhat|1.14.0|redhat.vscode-yaml-1.14.0|
|vscodeintellicode-csharp|ms-dotnettools|0.1.26|ms-dotnettools.vscodeintellicode-csharp-0.1.26-linux-x64|;

</details>

Extension version: 2.7.25
VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-13600KF (20 x 3494)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (16.97GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Debian/home/glen/projects/libraries/amazon-s3-extended --remote=wsl+Debian|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|13th Gen Intel(R) Core(TM) i5-13600KF (20 x 3494)|
|Memory (System)|15.54GB (12.37GB free)|
|VM|0%|
</details>

**Comment by dibarbet** [comment]
Looks like a devkit issue.  Filed https://github.com/microsoft/vscode-dotnettools/issues/645 to track on the devkit side
