### ISSUE TITLE
Logpoint freezes on start

### ISSUE THREAD

**Issue by WardenGnaw** [dotnet/vscode-csharp#6585]
### Describe the Issue
Program.cs
```
for (int i = 0; i < 9; i++)
{	
	Console.WriteLine(i);
}
```

In 3rd line I've logpoint with "i = {i}" message, but after start debugging it's display in debug console first log point and frezes for like 10-15 seconds don't know why. 

### Steps To Reproduce

1. dotnet console app in .NET8.0
2. In debugging session with follwoing launch.json
```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": ".NET Core Launch (console)",
			"type": "coreclr",
			"request": "launch",
			"preLaunchTask": "build",
			"program": "${workspaceFolder}/bin/Debug/net8.0/Debug101.dll",
			"args": [],
			"cwd": "${workspaceFolder}",
			"stopAtEntry": false,
			"console": "internalConsole"
		}
	]
}
```

task.json

```
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "build",
			"command": "dotnet",
			"type": "process",
			"args": [
				"build",
				"${workspaceFolder}/Debug101.csproj"
			],
			"problemMatcher": "$msCompile"
		}
	]
}
```

### Expected Behavior

Debugging session should dont freeze after displaying first log message 

### Environment Information

I'm using windows 11 Pro version: 10.0.22621 compilation 22621 and newest vs code

-----------

Originally reported by @Xariif from https://github.com/microsoft/vscode-dotnettools/issues/601

**Comment by gregg-miskelly** [comment]
Fixed in the next version of the extension.
