### ISSUE TITLE
Dev Kit Not Working Properly With Workspaces disabling syntax highlighting on linux

### ISSUE THREAD

**Issue by thndgonz** [dotnet/vscode-csharp#6596]
## Issue Description ##
I have multiple .csproj in a workspace. When I first installed Dev Kit it seems to have processed only one folder in which it added a SLN file. 

The language server starts failing with the other folders.

## Steps to Reproduce ##
Not sure if it matters (as in OS oriented) 
Have ubuntu/any other distro.
Open Visual Studio Code
Add several project folders with their respective `csproj` file to your **workspace** (do not add any project with a SLN, for reproduction purposes)
Install C# Dev Kit.
Notice that Dev Kit will add only one SLN. 
Notice that the syntax highlighting and autocomplete starts failing when you switch over to different `*.cs` files in the editor.

## Expected Behavior ##
Dev Kit or the language server doesn't "choke" when each csproj doesn't have a SLN. Autocomplete and syntax highlighting works.

## Actual Behavior ##
Dev Kit enabled and/or SLN existing in a folder causes a lot of heartburns for the language server apparently. Disabling syntax highlighting and autocomplete.

### C# log ###
<details>Post the output from Output-->C# here</details>

### C# LSP Trace Logs ###
<details>Post the output from Output-->C# LSP Trace Logs here.  Requires `dotnet.server.trace` to be set to `Trace`</details>

## Environment information ##

**VSCode version**: 1.83.1
**C# Extension**: 2.7.25
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.113
 Commit:    e24ee34c8e

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.113/

Host:
  Version:      7.0.13
  Architecture: x64
  Commit:       3f73a2f186

.NET SDKs installed:
  7.0.113 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.13 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.13 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/share/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|blazorwasm-companion|ms-dotnettools|1.1.4|ms-dotnettools.blazorwasm-companion-1.1.4|
|codesnap|adpyke|1.3.4|adpyke.codesnap-1.3.4|
|csharp|ms-dotnettools|2.7.25|ms-dotnettools.csharp-2.7.25-linux-x64|
|es7-react-js-snippets|dsznajder|4.4.3|dsznajder.es7-react-js-snippets-4.4.3|
|gulptasks|nickdodd79|1.3.1|nickdodd79.gulptasks-1.3.1|
|html-entities|christopherstyles|1.1.2|christopherstyles.html-entities-1.1.2|
|isort|ms-python|2023.10.1|ms-python.isort-2023.10.1|
|lipsum-generator|MrAwesomeRocks|1.2.3|mrawesomerocks.lipsum-generator-1.2.3|
|mysql-syntax|jakebathman|1.3.1|jakebathman.mysql-syntax-1.3.1|
|nginx-formatter|raynigon|0.0.13|raynigon.nginx-formatter-0.0.13|
|npm-intellisense|christian-kohler|1.4.5|christian-kohler.npm-intellisense-1.4.5|
|path-intellisense|christian-kohler|2.8.5|christian-kohler.path-intellisense-2.8.5|
|php-debug|xdebug|1.33.1|xdebug.php-debug-1.33.1|
|powershell|ms-vscode|2023.8.0|ms-vscode.powershell-2023.8.0|
|python|ms-python|2023.18.0|ms-python.python-2023.18.0|
|remote-containers|ms-vscode-remote|0.315.1|ms-vscode-remote.remote-containers-0.315.1|
|remote-ssh|ms-vscode-remote|0.106.5|ms-vscode-remote.remote-ssh-0.106.5|
|remote-ssh-edit|ms-vscode-remote|0.86.0|ms-vscode-remote.remote-ssh-edit-0.86.0|
|remote-wsl|ms-vscode-remote|0.81.8|ms-vscode-remote.remote-wsl-0.81.8|
|remove-tabs-on-save|redlin|1.2.4|redlin.remove-tabs-on-save-1.2.4|
|tailwind-docs|austenc|2.1.0|austenc.tailwind-docs-2.1.0|
|tailwindshades|bourhaouta|0.0.5|bourhaouta.tailwindshades-0.0.5|
|vim|vscodevim|1.26.2|vscodevim.vim-1.26.2|
|vscode-docker|ms-azuretools|1.27.0|ms-azuretools.vscode-docker-1.27.0|
|vscode-dotnet-runtime|ms-dotnettools|1.8.1|ms-dotnettools.vscode-dotnet-runtime-1.8.1|
|vscode-edge-devtools|ms-edgedevtools|2.1.3|ms-edgedevtools.vscode-edge-devtools-2.1.3|
|vscode-eslint|dbaeumer|2.4.2|dbaeumer.vscode-eslint-2.4.2|
|vscode-gulp|tanato|0.0.4|tanato.vscode-gulp-0.0.4|
|vscode-intelephense-client|bmewburn|1.9.5|bmewburn.vscode-intelephense-client-1.9.5|
|vscode-mysql|formulahendry|0.5.0|formulahendry.vscode-mysql-0.5.0|
|vscode-nginx-conf|ahmadalli|0.3.2|ahmadalli.vscode-nginx-conf-0.3.2|
|vscode-pylance|ms-python|2023.10.40|ms-python.vscode-pylance-2023.10.40|
|vscode-react-native|msjsdiag|1.12.1|msjsdiag.vscode-react-native-1.12.1|
|vscode-sql-formatter|adpyke|1.4.4|adpyke.vscode-sql-formatter-1.4.4|
|vscode-tailwindcss|bradlc|0.10.1|bradlc.vscode-tailwindcss-0.10.1|
|vscode-todo-highlight|wayou|1.0.5|wayou.vscode-todo-highlight-1.0.5|
|vscode-xml|redhat|0.26.1|redhat.vscode-xml-0.26.1-linux-x64|
|vscode-yaml|redhat|1.14.0|redhat.vscode-yaml-1.14.0|;

</details>

**Comment by dibarbet** [comment]
Transferring this issue over to the devkit repo - devkit controls the project loading experience.
Track the issue here - https://github.com/microsoft/vscode-dotnettools/issues/651
