### ISSUE TITLE
Cannot generate assets to build and debug in a workspace anymore

### ISSUE THREAD

**Issue by claytonweaver** [dotnet/vscode-csharp#6605]
## Environment data
`dotnet --info` output:
.NET SDK:
 Version:   7.0.403
 Commit:    142776d834

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.403\

Host:
  Version:      7.0.13
  Architecture: x64
  Commit:       3f73a2f186

.NET SDKs installed:
  6.0.416 [C:\Program Files\dotnet\sdk]
  7.0.403 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

VS Code version: latest

C# Extension version: latest

## Steps to reproduce

1. Open a workspace with multiple dotnet projects
2. Run command "Generate assets to build and debug" 
3. See error

## Expected  behavior
This was supposed to create a .vscode folder with the launch settings for my dotnet project for the solution i'm currently on.

## Actual behavior
Just threw an error

## Additional context
![image](https://github.com/dotnet/vscode-csharp/assets/58234904/e2888bb8-7a7f-4776-94f9-7fc0ff6476b5)

I actually had another solution selected so it's trying to do it on the wrong solution it looks like.

**Comment by dibarbet** [comment]
A couple items -
1.  Can you clarify what you mean by having another solution selected?  Is qapp-orchestrator a project outside the solution that is currently loaded?  What kind of project is it?
2.  Mind sharing the C# output window logs with `dotnet.server.trace` set to `Trace`?  There likely won't be information directly related to the error - but it will show what solution / project the server thinks is loaded.

**Comment by dibarbet** [comment]
Closing, this is not actionable without the additional information requested. If you're still having issues on the latest versions of the extensions, feel free to re-open with the requested information.
