### ISSUE TITLE
C# file printing to console is not showing in the debug console when there is no new line

### ISSUE THREAD

**Issue by ayman1988** [dotnet/vscode-csharp#6615]
Type: <b>Bug</b>

When using Vs Code Insider...

When printing a file that contains
Console.Write("Hi, this is not showing");
Console.ReadLine();

But When I am printing like this:
Console.WriteLine("This is showing");
Console.ReadLine();

So, when printing with no new line,
And there is an enter any key the output not printing...
The output is not showing in the end...

Extension version: 2.8.23
VS Code version: Code - Insiders 1.84.0-insider (60182c7e1a666961ded4d0319c154f52d85daf30, 2023-10-30T23:41:49.215Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by gregg-miskelly** [comment]
Thanks for reporting this issue! The fix for https://github.com/dotnet/vscode-csharp/issues/6598 addresses this as well, so I am resolving it as a duplicate.
