### ISSUE TITLE
Dereference of a possibly null reference on a non-nullable property

### ISSUE THREAD

**Issue by doggy8088** [dotnet/vscode-csharp#6618]
## Is your feature request related to a problem? Please describe.

I have a buggy code. I want C# Dev Kit can be able to point out the warning in the right place.

Here is my code on a sample Razor Page project:

```html
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";

    ViewBag.ogUrl         = $"{Request.Scheme}://{Request.Host}{Request.Path}{Request?.QueryString}";
    ViewBag.ogImage       = $"{Request.Scheme}://{Request.Host}/assets/img/logo_default.png";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
```

![image](https://github.com/dotnet/vscode-csharp/assets/88981/010ebac6-61bd-4c91-8726-d6ccc87f26cd)

The warning is located at here (below screenshot):

![image](https://github.com/dotnet/vscode-csharp/assets/88981/b12845e0-1a8c-40fa-a7cc-e33d7b0eb1a9)

Actually, the `Request` is not a nullable property.

![image](https://github.com/dotnet/vscode-csharp/assets/88981/bd232466-d253-4a7d-a0c6-5a27c6632cf1)

Somehow there is a guy wrote a `?.` on the first line for the `Request` property. It turns out cause the warning on the second line of the `Request` which is misleading develop to debug.

## Describe the solution you would like

I think the warning should appear on the `Request?.` when someone wants to mark a not-nullable property to a nullable type.

## Applicable Scenarios
Many.

## Describe alternatives you've considered
N/A

## Additional context
N/A

**Comment by dibarbet** [comment]
Unfortunately this is just how C# works.  Because of the explicit `?` annotation on `Result`, the compiler assumes that you know more than it does and that from that point on the value is possibly null.

See also https://github.com/dotnet/roslyn/issues/39858
