### ISSUE TITLE
Syntax highlighter broken in unusual situation

### ISSUE THREAD

**Issue by solarfluxx** [dotnet/vscode-csharp#6631]
Type: <b>Bug</b>

## Issue Description ##
The syntax highlighter breaks when a string wrapped in parantheses has what resembles a lambda function in it.

## Steps to Reproduce ##
Write the following in a csharp file: `("() =>")`.

## Expected Behavior ##
The contents of the string should be highlighted like any other string.

![image](https://github.com/dotnet/vscode-csharp/assets/56509699/9d2ad88e-21f3-4c6a-9c40-636b7f8e58e4)

## Actual Behavior ##
The string highlighting falls apart both before and after the string.

![image](https://github.com/dotnet/vscode-csharp/assets/56509699/b6c8dc84-056e-48f4-a0ec-7e02de8b27bb)

## Environment information ##

**VSCode version**: 1.84.0
**C# Extension**: 2.9.20
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.402
 Commit:    791db8e2d8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.402\

Host:
  Version:      7.0.12
  Architecture: x64
  Commit:       4a824ef37c

.NET SDKs installed:
  7.0.402 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|code-spell-checker|streetsidesoftware|3.0.1|streetsidesoftware.code-spell-checker-3.0.1|
|csdevkit|ms-dotnettools|1.0.14|ms-dotnettools.csdevkit-1.0.14-win32-x64|
|csharp|ms-dotnettools|2.9.20|ms-dotnettools.csharp-2.9.20-win32-x64|
|github-vscode-theme|GitHub|6.3.4|github.github-vscode-theme-6.3.4|
|gitlens|eamodio|14.4.1|eamodio.gitlens-14.4.1|
|hexeditor|ms-vscode|1.9.12|ms-vscode.hexeditor-1.9.12|
|identical-sublime-monokai-csharp-theme-colorizer|maximetinu|1.2.3|maximetinu.identical-sublime-monokai-csharp-theme-colorizer-1.2.3|
|intellicode-api-usage-examples|VisualStudioExptTeam|0.2.8|visualstudioexptteam.intellicode-api-usage-examples-0.2.8|
|nasm-language-support|doinkythederp|1.2.0|doinkythederp.nasm-language-support-1.2.0|
|rust-analyzer|rust-lang|0.3.1713|rust-lang.rust-analyzer-0.3.1713-win32-x64|
|vscode-dotnet-runtime|ms-dotnettools|2.0.0|ms-dotnettools.vscode-dotnet-runtime-2.0.0|
|vscode-tailwindcss|bradlc|0.10.3|bradlc.vscode-tailwindcss-0.10.3|
|vscode-yaml|redhat|1.14.0|redhat.vscode-yaml-1.14.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.30|visualstudioexptteam.vscodeintellicode-1.2.30|
|vscodeintellicode-csharp|ms-dotnettools|0.1.26|ms-dotnettools.vscodeintellicode-csharp-0.1.26-win32-x64|
|vsliveshare|ms-vsliveshare|1.0.5892|ms-vsliveshare.vsliveshare-1.0.5892|;

</details>

Extension version: 2.9.20
VS Code version: Code 1.84.0 (d037ac076cee195194f93ce6fe2bdfe2969cc82d, 2023-11-01T11:29:04.398Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor              (16 x 3800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|127.91GB (109.01GB free)|
|Process Argv|--crash-reporter-id 10f50b79-0cb8-4ed9-b6b1-ad1d25dd80d9|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30880072
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pythonmypyd1:30879173
pythoncet0:30874138
pythontbext0:30879054

```

</details>

**Comment by JoeRobich** [comment]
@solarfluxx Is `editor.semanticHighlighting.enabled` set to `true` in your settings? Also, can you share a complete code file that demonstrates this behavior?

**Comment by solarfluxx** [comment]
Yes, `editor.semanticHighlighting.enabled = true`.

Here is a minimal example with this issue:

```
void main() {
    Console.WriteLine(( "() =>" ));
}
```


Here's what it looks like in VS Code:

![image](https://github.com/dotnet/vscode-csharp/assets/56509699/5b30f900-af26-4130-bfcb-d036f26b9981)

Without the extra parentheses it renders correctly:

![image](https://github.com/dotnet/vscode-csharp/assets/56509699/d1f17881-5b69-4bde-b52e-9fee3fbe2bf5)

But those parentheses are necessary for tuples:

![image](https://github.com/dotnet/vscode-csharp/assets/56509699/dbcc8275-1acb-4ba6-b36b-8c1025a44657)

**Comment by JoeRobich** [comment]
This seems to be an issue with the C# textmate grammar that ships with the current release version of VS Code.

![Image](https://github.com/dotnet/vscode-csharp/assets/611219/5cd9c137-fd5b-4a95-a2d7-b08dc388a0a8)

We can see that it is semantically classified as a string but the textmate grammar is returning a closed paranthesis scope.

Trying the same sample in the Insiders build of VS Code, we see that the string is given the proper scope.

![Image](https://github.com/dotnet/vscode-csharp/assets/611219/99151d14-e536-4520-a057-130c93a0e23a)

**Comment by solarfluxx** [comment]
Sounds like this is fixed in Insiders and will be released eventually.
