### ISSUE TITLE
references to godot custom signals highlighted as errors with roslyn

### ISSUE THREAD

**Issue by ana-rchy** [dotnet/vscode-csharp#6635]
Type: <b>Bug</b>

## Issue Description ##
when you reference a custom signal with `SignalName` with roslyn enabled rather than omnisharp, it complains that "`Node.SignalName` does not contain a definition for `Foo`", even though it compiles fine with godot
this also seemingly only happens on my laptop setup, and not my desktop

## Steps to Reproduce ##
1. define a custom godot signal (`[Signal] public delegate void FooEventHandler();`)
2. reference it with `SignalName` (`EmitSignal(SignalName.Foo)`)

## Expected Behavior ##
no error

## Actual Behavior ##
error

## Logs ##
[exthost.zip](https://github.com/dotnet/vscode-csharp/files/13265444/exthost.zip)

### C# log ###
<details>Post the output from Output-->C# here</details>

### C# LSP Trace Logs ###
<details>Post the output from Output-->C# LSP Trace Logs here.  Requires `dotnet.server.trace` to be set to `Trace`</details>

## Environment information ##

**VSCode version**: 1.84.0
**C# Extension**: 2.0.436
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>

Host:
  Version:      7.0.13
  Architecture: x64
  Commit:       3f73a2f186

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 7.0.13 [/home/ana/.config/VSCodium/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.13~x64/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/share/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|csharp|ms-dotnettools|2.9.20|ms-dotnettools.csharp-2.9.20-linux-x64|
|csharp|muhammad-sammy|2.0.436|muhammad-sammy.csharp-2.0.436-universal|
|godot-csharp-vscode|neikeq|0.2.1|neikeq.godot-csharp-vscode-0.2.1-universal|
|godot-dotnet-tools|woberg|0.1.21|woberg.godot-dotnet-tools-0.1.21|
|godot-files|alfish|0.0.6|alfish.godot-files-0.0.6|
|godot-tools|geequlim|1.3.1|geequlim.godot-tools-1.3.1|
|html-snippets|abusaidm|0.2.1|abusaidm.html-snippets-0.2.1-universal|
|mono-debug|ms-vscode|0.16.3|ms-vscode.mono-debug-0.16.3|
|vscode-clangd|llvm-vs-code-extensions|0.1.24|llvm-vs-code-extensions.vscode-clangd-0.1.24-universal|
|vscode-dotnet-runtime|ms-dotnettools|2.0.0|ms-dotnettools.vscode-dotnet-runtime-2.0.0|
|vscode-html-css|ecmel|1.13.1|ecmel.vscode-html-css-1.13.1-universal|
|vsshot-purple-final|undefined_publisher|0.0.1|undefined_publisher.vsshot-purple-final-0.0.1|;

</details>

Extension version: 2.0.436
VSCodium version: VSCodium 1.84.0 (695a9146b1347633e608f9f166c81b5b2843b492, 2023-11-02T15:23:23.641Z)
OS version: Linux x64 6.5.9-arch2-1
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 7730U with Radeon Graphics (16 x 3835)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|14.98GB (9.01GB free)|
|Process Argv|--ms-enable-electron-run-as-node --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|bspwm|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by jasonmalinowski** [comment]
@ana-rchy The bug shows you're running 2.0.436 which is a fairly old version; there's been a number of fixes which could lead to the issue you're seeing. Can you upgrade to the latest and try again?

**Comment by ana-rchy** [comment]
> @ana-rchy The bug shows you're running 2.0.436 which is a fairly old version; there's been a number of fixes which could lead to the issue you're seeing. Can you upgrade to the latest and try again?

i cant, there is no option to update
im using vscodium-bin from the AUR with vscodium-marketplace-bin also installed, tho no newer version appears than that

**Comment by jasonmalinowski** [comment]
Do you actually have two variants of the extension installed?

<img width="608" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/201340/b201dce4-2af9-49c5-8aad-aa796a3940dd">

Maybe uninstall the muhammad-sammy one? Or update that one too? It looks like that fork is pulling updates from us...

**Comment by ana-rchy** [comment]
> Do you actually have two variants of the extension installed?
> <img alt="image" width="608" src="https://user-images.githubusercontent.com/201340/280887817-b201dce4-2af9-49c5-8aad-aa796a3940dd.png">
> 
> Maybe uninstall the muhammad-sammy one? Or update that one too? It looks like that fork is pulling updates from us...

'c# tools for godot' depends on the muhammad-sammy version

**Comment by ana-rchy** [comment]
uninstalled the c# and godot extensions, reinstalled c# tools for godot, and it automatically installed the MS c# extension as a dependency, which fixes the issues
ill probs wanna look into getting it working with the muhammad-sammy version tho, just to make everything fully open source

**Comment by ana-rchy** [comment]
yeah reinstalled extensions again but after uninstalling `vscodium-bin-marketplace`, and the muhammad-sammy one is now v2.8.23
