### ISSUE TITLE
Solution explorer and entity framework core not loading

### ISSUE THREAD

**Issue by muneebusmani** [dotnet/vscode-csharp#6653]
Type: <b>Bug</b>

solution explorer is not loading

Extension version: 2.0.0
VS Code version: Code 1.84.1 (2b35e1e6d88f1ce073683991d1eff5284a32690f, 2023-11-06T12:35:59.022Z)
OS version: Windows 11 Pro

**Comment by dibarbet** [comment]
@muneebusmani can you share
1.  the contents of the 'C#' output window
2.  the contents of the 'C# Dev Kit' output window
3.  the contents of the 'Projects' output window

**Comment by muneebusmani** [comment]
<p>
<hr>
<h3>C# output:</h3>
<hr>

    Installing Razor Telemetry Version = 7.0.0-preview.23528.1...
    Platform: win32, x86_64

    Downloading package 'Razor Language Server Telemetry (Windows / x64)' (9395 KB).................... Done!
    Validating download...
    Integrity Check succeeded.
    Installing package 'Razor Language Server Telemetry (Windows / x64)'

    Finished

    Failed to find dotnet info from path, falling back to acquire runtime via ms-dotnettools.vscode-dotnet-runtime
    The architecture of the .NET runtime (x86) does not match the architecture of the extension (x64).
    Dotnet path: c:\Users\munee\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.13~x64\dotnet.exe
    Activating C# + C# Dev Kit + C# IntelliCode...
    waiting for named pipe information from server...
    [stdout] {"pipeName":"\\\\.\\pipe\\a1a52dc9"}
    received named pipe information from server
    attempting to connect client to server...
    client has connected to server
    [Info  - 1:54:25 AM] [Program] Language server initialized</p>
<hr>
<p>
<h3>C# Dev Kit output :</h3>
<hr>
    Starting Spawn .NET server...
    Starting Open a solution...
    Starting Open a solution with environment service...
    Starting Clear environment...
    Using local .NET runtime at "c:\Users\munee\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.13~x64\dotnet.exe"
    Using runtime installed in SDK.
    .NET server started and IPC established in 8295ms
    Completed Spawn .NET server (14026ms)
    Completed Clear environment (15439ms)
    Completed Open a solution with environment service (15572ms)
    Starting Restore solution...
    Completed Open a solution (15708ms)
    Starting NuGet restore for the solution.
    Starting command: "dotnet.exe" restore C:\Users\munee\RiderProjects\Fresh Start\Fresh Start.sln --interactive...
    Failed to listen to project initialization status: Error: Activating the "Microsoft.VisualStudio.ProjectSystem.ProjectInitializationStatusService (0.1)" service failed.
    Completed command: "dotnet.exe" restore C:\Users\munee\RiderProjects\Fresh Start\Fresh Start.sln --interactive (8190ms)
    Completed NuGet restore.
    Completed Restore solution (8197ms)
</p>
<p>
<hr>
<h3>when i expand the solution explorer, This error notification pops up:</h3>
<hr>
    Activating the "Microsoft.VisualStudio.CpsProjectIconSourceService (0.1)" service failed.
</p>
<br><br>
<hr>
<br><br>
<br><br>
i Tried using insiders versions but it still doesnt has this bug fixed, and there is also one more issue in vs code,
whenever i write code into my Program.cs file in an asp.net project, or any other project , it doesnt suggest available classes, methods etc

**Comment by muneebusmani** [comment]
<p>
<hr>
<h3>C# output:</h3>
<hr>

    Installing Razor Telemetry Version = 7.0.0-preview.23528.1...
    Platform: win32, x86_64

    Downloading package 'Razor Language Server Telemetry (Windows / x64)' (9395 KB).................... Done!
    Validating download...
    Integrity Check succeeded.
    Installing package 'Razor Language Server Telemetry (Windows / x64)'

    Finished

    Failed to find dotnet info from path, falling back to acquire runtime via ms-dotnettools.vscode-dotnet-runtime
    The architecture of the .NET runtime (x86) does not match the architecture of the extension (x64).
    Dotnet path: c:\Users\munee\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.13~x64\dotnet.exe
    Activating C# + C# Dev Kit + C# IntelliCode...
    waiting for named pipe information from server...
    [stdout] {"pipeName":"\\\\.\\pipe\\a1a52dc9"}
    received named pipe information from server
    attempting to connect client to server...
    client has connected to server
    [Info  - 1:54:25 AM] [Program] Language server initialized</p>
<hr>
<p>
<h3>C# Dev Kit output :</h3>
<hr>
    Starting Spawn .NET server...
    Starting Open a solution...
    Starting Open a solution with environment service...
    Starting Clear environment...
    Using local .NET runtime at "c:\Users\munee\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.13~x64\dotnet.exe"
    Using runtime installed in SDK.
    .NET server started and IPC established in 8295ms
    Completed Spawn .NET server (14026ms)
    Completed Clear environment (15439ms)
    Completed Open a solution with environment service (15572ms)
    Starting Restore solution...
    Completed Open a solution (15708ms)
    Starting NuGet restore for the solution.
    Starting command: "dotnet.exe" restore C:\Users\munee\RiderProjects\Fresh Start\Fresh Start.sln --interactive...
    Failed to listen to project initialization status: Error: Activating the "Microsoft.VisualStudio.ProjectSystem.ProjectInitializationStatusService (0.1)" service failed.
    Completed command: "dotnet.exe" restore C:\Users\munee\RiderProjects\Fresh Start\Fresh Start.sln --interactive (8190ms)
    Completed NuGet restore.
    Completed Restore solution (8197ms)
</p>
<p>
<hr>
<h3>when i expand the solution explorer, This error notification pops up:</h3>
<hr>
    Activating the "Microsoft.VisualStudio.CpsProjectIconSourceService (0.1)" service failed.
</p>
<br><br>
<hr>
<br><br>
<br><br>
i Tried using insiders versions but it still doesnt has this bug fixed, and there is also one more issue in vs code,
whenever i write code into my Program.cs file in an asp.net project, or any other project , it doesnt suggest available classes, methods etc

**Comment by dibarbet** [comment]
Thanks for the logs!
```
Failed to listen to project initialization status: Error: Activating the "Microsoft.VisualStudio.ProjectSystem.ProjectInitializationStatusService (0.1)" service failed.
```
and
```
Activating the "Microsoft.VisualStudio.CpsProjectIconSourceService (0.1)" service failed.
```

appear to be failures in the devkit extension.

```
The architecture of the .NET runtime (x86) does not match the architecture of the extension (x64).
```
I do notice that you may have a x86 installation of dotnet, generally if you're on an x64 machine you should also have an x64 version of dotnet.

I've created https://github.com/microsoft/vscode-dotnettools/issues/704 to track this issue on their side.  They may ask you for additional details on that issue.

**Comment by dibarbet** [comment]
Closing the issue here - please use https://github.com/microsoft/vscode-dotnettools/issues/704 instead
