### ISSUE TITLE
Tests with internal accessor are not discovered

### ISSUE THREAD

**Issue by sandy081** [dotnet/vscode-csharp#6658]
I have a test with `internal` accessor and this test is not discoverable anywhere. Visual Studio is able to discover it given that `xUnit` supports it.

**Comment by dtivel** [comment]
https://github.com/xunit/xunit/blob/7fa42eac4d7fc9dd83de6eabd0e535ee12206bc3/src/xunit.v3.core/Sdk/v3/Framework/XunitTestFrameworkDiscoverer.cs#L153

**Comment by dibarbet** [comment]
@sandy081 are you using C# devkit, or just the C# extension?

**Comment by sandy081** [comment]
I am using ms-dotnettools.csdevkit - C# devkit extension

**Comment by dibarbet** [comment]
Gotcha.  The C# extension is not involved in anything test related when using devkit.  Created https://github.com/microsoft/vscode-dotnettools/issues/725 to track this on the devkit side.
