### ISSUE TITLE
Unable to run and debug in vscode on ubuntu 22.04 (dotnet 8)

### ISSUE THREAD

**Issue by janusqa** [dotnet/vscode-csharp#6692]
## Environment data
```
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.71b9f198

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.100/

.NET workloads installed:
 Workload version: 8.0.100-manifests.71b9f198
There are no installed workloads to display.

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  8.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```
VS Code version: 1.84.2
C# DevKit Extension version: v1.0.14

## Steps to reproduce

1.  
```
sudo apt remove 'dotnet*' 'aspnet*' 'netstandard*'
```

2. 
$ sudo nano /etc/apt/preferences
add...
```
Package: dotnet* aspnet* netstandard*
Pin: origin "packages.microsoft.com"
Pin-Priority: 1001
```

3. 
Install repo and SDK
   1. sudo apt update
   2. sudo apt upgrade
   3. wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
   4. sudo dpkg -i packages-microsoft-prod.deb
   5. rm packages-microsoft-prod.deb
   6. sudo apt update
   7. sudo apt upgrade
   8. sudo apt-get install -y dotnet-sdk-8.0
   
4. Install C# Devkit plugin for vscode   

5. mkdir helloworld
   cd helloworld
   dotnet new console
   opent in vscode
   click debug and run and observe output in console
   
  ```
App: <some path>/playground/helloworld/bin/Debug/net8.0/helloworld
Architecture: x64
App host version: 8.0.0
.NET location: Not found

Learn more:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=linux-x64&os=ubuntu.22.04&apphost_version=8.0.0
The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
The program '[295154] helloworld' has exited with code 131 (0x83).
  
  ```

**Comment by gregg-miskelly** [comment]
This repo isn't the right home for this bug if you can repro it without VS Code. I believe you want: https://github.com/dotnet/runtime/issues

**Comment by janusqa** [comment]
I managed to solve it by 
activating the command pallet (crtl+shift+p) and typing in this ".NET: Generate Assets for Build and Debug", and running it.  That installed what was required to get the debugger configured and going.

**Comment by gregg-miskelly** [comment]
I am glad you found a work around! But to be clear, this isn't really a fix. It works when you use ".NET: Generate Assets for Build and Debug" due to a subtle difference in the launch configuration -- ".NET: Generate Assets for Build and Debug" will, by default, use the `dotnet` executable to host your project (in other words, it is running `dotnet <path-to-your-workspace>\bin\debug\<configuation>\<your-project>.dll`) will instead use the 'app host' executable  (in other words, it is running `<path-to-your-workspace>\bin\debug\<configuation>\<your-project>`). Your setup apparently adds `dotnet` to some directory on `PATH` so the former works, but whatever mechanism the apphost executable is using to find an installed .NET Runtime doesn't work.

**Comment by concesar12** [comment]
I ran into the same issue, I tried uninstalling different versions of the SDKs and vscode but nothing actually worked. The only way it worked for me is following @janusqa instructions, I think .NET debugger in linux still needs some maintenance.
