### ISSUE TITLE
Code navigation not recognizing symbol in my solution

### ISSUE THREAD

**Issue by timheuer** [dotnet/vscode-csharp#6704]
Type: <b>Bug</b>

clone the Aspire repo -- https://github.com/dotnet/aspire

Open src/Aspire.Hosting.Azure/AzureStorageResource.cs

Navigaet to the ctor of the class -- observe the inherited Resource, IAzureResource there.  Right click and choose goto definition.

EXPECT: navigation
ACTUAL: unable to find definition.

![image](https://github.com/dotnet/vscode-csharp/assets/4821/e0ab0f37-2de4-4d62-b3d9-3dcadf807f3c)

Extension version: 2.12.19
VS Code version: Code - Insiders 1.85.0-insider (b3b84b5239037a2f0ef8499306df9a3bacda4105, 2023-11-28T12:02:59.475Z)
OS version: Windows_NT x64 10.0.22635
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|127.92GB (105.88GB free)|
|Process Argv|--crash-reporter-id 961e68ed-cec6-437f-8e5f-e44a8abbf88f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
showlangstatbar:30737417
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
pythonmhint1:30901775
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30902439
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

**Comment by dibarbet** [comment]
@timheuer can you verify the solution is opened?  Just cloning and opening the solution I get this prompt because there is no default solution set.
![image](https://github.com/dotnet/vscode-csharp/assets/5749229/85f87bb8-798d-409b-a066-cbe4cf957d14)

Since we haven't loaded the project, I see the same no definition found.

However, once I pick a solution to open, everything loads and I'm able to go to def on `Resource`

**Comment by timheuer** [comment]
Ugh, PEBCAK.  Thanks @dibarbet
