### ISSUE TITLE
Support for .NET Aspire Orchestration

### ISSUE THREAD

**Issue by mwgustin** [dotnet/vscode-csharp#6705]
## Is your feature request related to a problem? Please describe.
Trying to debug an Aspire project only attaches to the orchestration project, not the child processes, so debugging fails to work on the actual application projects. 

## Describe the solution you would like
The .NET Aspire devs have documented a specification for handling IDE integration with Aspire here: https://github.com/dotnet/aspire/blob/main/docs/specs/IDE-execution.md

## Applicable Scenarios
Debugging projects utilizing Aspire's orchestration features. 

## Describe alternatives you've considered
I suspect it's probably possible to attach the debugger to a child process directly, but I haven't had luck with it in a quick test.

## Additional context
Related discussion in the Aspire repo: https://github.com/dotnet/aspire/issues/834#issuecomment-1837520811

**Comment by gregg-miskelly** [comment]
.NET Aspire has been supported for a while now through C# Dev Kit, so closing this issue.
