### ISSUE TITLE
`Attach to Unity` doesn't stop at breakpoints

### ISSUE THREAD

**Issue by COOLIRON2311** [dotnet/vscode-csharp#6710]
## Environment data
`dotnet --info` output: 
<details>
<summary>Output</summary>

```
ПАКЕТ SDK ДЛЯ .NET:
 Version:   7.0.403
 Commit:    142776d834

Среда выполнения:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.403\

Host:
  Version:      7.0.13
  Architecture: x64
  Commit:       3f73a2f186

.NET SDKs installed:
  7.0.403 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```
</details>

VS Code version: `1.84.2`
OS Version: `Windows 11 Home 23H2`
C# Extension: `2.12.19`
C# DevKit: `1.0.14`
Unity Extension: `0.9.3`
Unity: `2022.3.12f1`
Visual Studio Editor package: `2.0.22`

## Steps to reproduce

1. Open any Unity project in Visual Studio Code
2. It atomatically creates `launch.json` with the following contents:
``` json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to Unity",
            "type": "vstuc",
            "request": "attach",
        }
     ]
}
```
3. Switch to debug mode in Unity
4. Start `Attach to Unity` debug task
5. A list of threads is shown in vs code's debugger and "debugger attached" (blue bug) status is indicated by Unity editor.

## Expected  behavior
The debugger stops at breakpoints.

## Actual behavior
The debugger does not stop at breakpoints.

## Additional context
It does work without an issue if I attach the debugger via `Attach Unity Debugger` option in Command Palette.
I've tried different versions of all listed extensions with no success. `Attach to Unity` never managed to properly handle breakpoints. However I recall that it was able to do so about two months ago.

**Comment by WardenGnaw** [comment]
Moved to https://github.com/microsoft/vscode-dotnettools/issues/783

**Comment by jbevain** [comment]
@COOLIRON2311 hi! thanks for reporting this, the bug has been moved to a new repo where I've requested additional information. Thanks!
