### ISSUE TITLE
Tokenization is skipped for long lines for performance reasons. This can be configured via editor.maxTokenizationLineLength even though I edited the settings.json file

### ISSUE THREAD

**Issue by NCLnclNCL** [dotnet/vscode-csharp#6717]
with string too many line, it appear Tokenization is skipped for long lines for performance reasons. This can be configured via editor.maxTokenizationLineLength. even though I edited the settings.json file like   "editor.maxTokenizationLineLength": 50000,

**Comment by dibarbet** [comment]
I'm not sure what the issue is exactly, but the C# extension has nothing to do with `editor.maxTokenizationLineLength`.  If there are issues with it, you would need to file an issue on vscode itself.

**Comment by JoeRobich** [comment]
@NCLnclNCL You may need to specifically override `editor.maxTokenizationLineLength` for the csharp language. [You can see here](https://github.com/microsoft/vscode/blob/0ca618d59d3fd1ecadba54ce8f5ed7ea84a51eef/extensions/csharp/package.json#L17) that VSCode defaults the csharp value to only 2500 (the same default as typescript). Below is an example of what you would need to add to your settings.json.

```json
{
    "[csharp]": {
        "editor.maxTokenizationLineLength": 5000
    },
    "editor.fontFamily": "'Comic Mono', ..."
```
