### ISSUE TITLE
Debugger should use larger string truncation limit when evaluating from the Debug Console

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/vscode-csharp#6719]
## Steps to reproduce

1. Create a new C# Console app
2. Replace the content with below
3. Set a breakpoint where indicated
4. Start debugging
5. From the Debug Console, evaluate 'longString'

## Expected  behavior
The full value of `longString` should be displayed (up until a fairly large truncation value)

## Actual behavior
`longString` is truncated after 1024 characters

## Work around
Right click on the value in the Debug Console and invoke 'Copy'

## Content of the app
```C#
    public static void Main()
    {
        string longString = "[" + new string('*', 1024) + "]";
        Console.WriteLine(longString); // breakpoint here
    }
```

**Comment by isadorasophia** [comment]
Fixed with #6765
