### ISSUE TITLE
Not able to debug the Code in VsCode

### ISSUE THREAD

**Issue by D-Dharani** [dotnet/vscode-csharp#6728]
Type: <b>Bug</b>

In Vsode , i am not able to debug the code. Code is building but when start debugging no debugger points show up and it says activating extensions and stop , debug will not start there is no error also coming up. This performance issue is from last week ,previously i am able to debug code with no issues ,tried re-installing didn't work. Confirmed launch.json also it is correct.

Extension version: 2.13.10
VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:07.651Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (4.00GB free)|
|Process Argv|--crash-reporter-id 8508c490-ccf9-432a-abd3-c8330412dc37|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
282f8724:30602487
89544117:30613380
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019cf:30917260

```

</details>

**Comment by gregg-miskelly** [comment]
@D-Dharani What does your launch.json configuration look like?

**Comment by D-Dharani** [comment]
@gregg-miskelly ,please find my launch.json file below.

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        

        {
            "name": ".NET Core Launch (web)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceFolder}/bin/Debug/net6.0/ScottishWaterCrmAPI.dll",
            "args": [],
            "cwd": "${workspaceFolder}",
            "stopAtEntry": false,
            "serverReadyAction": {
                "action": "openExternally",
                "pattern": "\\bNow listening on:\\s+(https?://\\S+)"
            },
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            },
            "sourceFileMap": {
                "/Views": "${workspaceFolder}/Views"
            }
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach"
        }
    ]
}

**Comment by gregg-miskelly** [comment]
@D-Dharani I am not quite understanding what problem you are having, can you [enable logging](https://github.com/dotnet/vscode-csharp/wiki/Enabling-C%23-debugger-logging#using-launchjson) and hopefully the logging from that will make it more clear.

**Comment by D-Dharani** [comment]
@gregg-miskelly  i am trying to run vsdbg-ui , i am getting - 'vsdbd-ui' is not recognized as an internal or external command,
operable program or batch file. 

not able to run , can you help in this?


<img width="845" alt="Screenshot 2023-12-12 175728" src="https://github.com/dotnet/vscode-csharp/assets/91110247/8d038114-37b4-45c9-9ff9-74a3113ab8e1">

**Comment by D-Dharani** [comment]
see below screenshot , i tried run vsdbg- ui with below directory and start debugging in VS code with "debugServer": 4711 in launch.json file nothing came up in terminal @gregg-miskelly 

![Uploading Screenshot 2023-12-12 201833.png…]()

**Comment by gregg-miskelly** [comment]
@D-Dharani Can you try using the "Using launch.json" method instead of the "Full Method"? That is a lot easier to do.

**Comment by D-Dharani** [comment]
@gregg-miskelly ,I tried using launch.json method, still nothing showed up in terminal. please refer screenshot attached when i start debug or dotnet run command at bellow activating extensions will show up and stop after few seconds. after this no error or any action is occurring.

<img width="597" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/91110247/be7e856a-4d95-435f-aeeb-a22c6067ff63">

**Comment by gregg-miskelly** [comment]
I am not familiar with the 'Activating Extensions' link. If you open the 'Output' tab, and flip though the various pane's, do you see anything interesting? Is there a 'C#' pane? Does that show anything?

**Comment by D-Dharani** [comment]
@gregg-miskelly  in c# pane in output tab below info is coming.

<img width="955" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/91110247/7acd085e-8fee-406d-8163-3912e6fb6103">

**Comment by D-Dharani** [comment]
for # dev kit 

<img width="956" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/91110247/8798fba7-20c0-4741-b896-c18cbb713526">

**Comment by aaira-a** [comment]
I am having similar issue. After clicking ".NET Core Attach", I am no longer presented with a dropdown to choose processes from. I was able to

**Comment by D-Dharani** [comment]
when i debug code , debugger just on loop doesn't run and present with debugger points as per below screenshot.

<img width="918" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/91110247/9157edae-117b-4471-9916-ef9c556e38df">

**Comment by aaira-a** [comment]
Somehow I can debug again after installing .NET SDK 8.0. I dont know why it works as my project is based on 6.0, but my issue is resolved now. 

@D-Dharani I hope you could get yours resolved soon. I'm sorry for piggybacking your thread, as yours is the closest symptom to my issue. Good luck

**Comment by D-Dharani** [comment]
Yes, after installing .NET 8 version i can debug now.  same my project is based on 6.0 though. it is strange.

**Comment by gregg-miskelly** [comment]
Closing old issue.
