### ISSUE TITLE
Remote debugging with Docker doesn't work

### ISSUE THREAD

**Issue by AlexandrStarov** [dotnet/vscode-csharp#6735]
## Environment data
`dotnet --info` output: dotnet 6
VS Code version: 1.85
C# Extension version: 2.13.10

## Steps to reproduce

1. Create a new IoT Edge Solution according to the documentation https://learn.microsoft.com/en-us/azure/iot-edge/tutorial-develop-for-linux?view=iotedge-1.4&tabs=csharp&pivots=iotedge-dev-ext
2. Run edge solution locally
3. Try to attach to the remote process according to the documentation https://learn.microsoft.com/en-us/azure/iot-edge/debug-module-vs-code?view=iotedge-1.4&tabs=c&pivots=iotedge-dev-ext

## Expected  behavior
VS Code is attached to the remote process.

## Actual behavior

The VSDBG is not installed:
![image](https://github.com/dotnet/vscode-csharp/assets/14146298/41a15c45-4100-4ce7-8ea3-b4b9d04b8fcf)

The error appears:
> Starting: "docker" exec -i DataProcessor sh -c "~/vsdbg/vsdbg --interpreter=vscode"
> Error from pipe program 'docker': sh: 1: /home/moduleuser/vsdbg/vsdbg: not found
> The pipe program 'docker' exited unexpectedly with code 127.

## Additional context

Docker file:

> FROM mcr.microsoft.com/dotnet/runtime:6.0 AS base
> 
> RUN apt-get update && \
>     apt-get install -y --no-install-recommends unzip procps && \
>     rm -rf /var/lib/apt/lists/*
> 
> RUN useradd -ms /bin/bash moduleuser
> USER moduleuser
> RUN curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l ~/vsdbg
> 
> FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
> WORKDIR /app
> 
> COPY *.csproj ./
> RUN dotnet restore
> 
> COPY . ./
> RUN dotnet publish -c Debug -o out
> 
> FROM base
> WORKDIR /app
> COPY --from=build-env /app/out ./
> 
> ENTRYPOINT ["dotnet", "DataProcessor.dll"]

Launch config:

>           {
>             "name": "DataProcessor Remote Debug (.NET Core)",
>             "type": "coreclr",
>             "request": "attach",
>             "processId": "${command:pickRemoteProcess}",
>             "pipeTransport": {
>                 "pipeProgram": "docker",
>                 "pipeArgs": [
>                     "exec",
>                     "-i",
>                     "DataProcessor",
>                     "sh",
>                     "-c"
>                 ],
>                 "debuggerPath": "~/vsdbg/vsdbg",
>                 "pipeCwd": "${workspaceFolder}",
>                 "quoteArgs": true
>             },
>             "sourceFileMap": {
>                 "/app": "${workspaceFolder}/modules/DataProcessor"
>             },
>             "justMyCode": true
>         }

**Comment by gregg-miskelly** [comment]
I am not enough of a Docker expert to tell you why that doesn't work, but clearly there must be something wrong with that way of trying to run the getvsdbgsh script. Do docker verbose logs spit anything out? If you use `docker exec` after the fact, does that fail too?

**Comment by AlexandrStarov** [comment]
Unfortunately there are no errors.

VS Code logs:
![image](https://github.com/dotnet/vscode-csharp/assets/14146298/aca306cc-e51c-4255-81d2-4552dac5b436)

Docker Desktop logs:
![image](https://github.com/dotnet/vscode-csharp/assets/14146298/c1b01ac6-d55f-43f3-9024-1352efde25b9)

**Comment by gregg-miskelly** [comment]
You want to try something like this:

```
docker exec -it your-container-name-here /bin/sh
$ curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l ~/test
/bin/sh: 6: curl: not found
```

**Comment by AlexandrStarov** [comment]
Unfortunately, this does not help fix debugging issues.

**Comment by gregg-miskelly** [comment]
To be clear: the idea is this will hopefully tell you why the command is failing. If it passes when run from `docker exec` then you will need to figure out how to get docker image building to actually print failures. But hopefully this is an easy way to see failures.

**Comment by AlexandrStarov** [comment]
You are the best!

The following command helped to solve the issue:
`RUN apt-get -y update; apt-get -y install curl`

**Comment by gregg-miskelly** [comment]
Glad you got it working!
