### ISSUE TITLE
Nuget Package Manager tool for VS Code users

### ISSUE THREAD

**Issue by Anukkavishka** [dotnet/vscode-csharp#6745]
## Is your feature request related to a problem? Please describe.
Yes since the Visual Studio for Mac does not support .NET 8 I had to use VS code with C# Devkit which is pretty great. The only feature gap that I feel is when trying to manage a nuget package from the VS Code editor. There are extensions but they are not good and could end up with a corrupted .csproj file.
Also, the current alternative is to use dotnet CLI to add and remove nuget packages on Mac and it's very time-consuming and has minimal capabilities compared to the features we have in Visual Studio Package Manager.

## Describe the solution you would like
Would like a nuget package manager proper extension from Microsoft or better alternatives to the dotnet CLI to make this a bit easier

## Applicable Scenarios
When managing nuget packages from VS Code, adding, removing, upgrading

## Describe alternatives you've considered
All the extensions that I tried are not good and not reliable
dotnet CLI has very limited capabilities

## Additional context
NA

**Comment by dibarbet** [comment]
Looks like there's already an issue for this on the devkit side here - https://github.com/microsoft/vscode-dotnettools/issues/62

Closing this as a duplicate.
