### ISSUE TITLE
Nested code actions don't expose all choices

### ISSUE THREAD

**Issue by SeijiSuenaga** [dotnet/vscode-csharp#6763]
## Issue Description ##

The new nested code actions introduced in 2.12.19 by #6572 don't expose all available actions, and the choices shown in the command palette don't make sense.

### Example 1: Fully qualifying a type

When I have an ambiguous type reference, for example `ILogger` which is defined in `Microsoft.Extensions.Logging` as well as the 3rd-party `Amazon.Runtime.Internal.Util` and `Castle.Core.Logging` namespaces, the "Fully qualify 'ILogger'" action shows these confusing choices in the command palette:
- Amazon.Runtime.Internal.Util.ILogger
- Amazon.Runtime.Internal.Util.ILogger -> Castle.Core.Logging.ILogger
- Amazon.Runtime.Internal.Util.ILogger -> Castle.Core.Logging.ILogger -> Microsoft.Extensions.Logging.ILogger

which all produce the same result:
```c#
Amazon.Runtime.Internal.Util.ILogger
```

### Example 2: Wrapping method parameters

Previous versions of the extension had a code action to reformat inline parameters like this:
```c#
public void Foo(int a, int b, int c)
```
to this:
```c#
public void Foo(
    int a,
    int b,
    int c)
```

But now the "Wrap every parameter" action shows these confusing choices in the command palette:
- Align wrapped parameters
- Align wrapped parameters -> Indent all parameters
- Align wrapped parameters -> Indent all parameters -> Indent wrapped parameters

which all produce the same result:
```c#
public void Foo(int a
                int b
                int c)
```

## Steps to Reproduce ##

To reproduce behavior similar to example 1:

1. Define 2 classes called `Foo` in different namespaces `NamespaceA` and `NamespaceB`.
1. Define a class in `NamespaceC` with a field of type `Foo` (unqualified). The IDE should mark it with a red underline.
1. Press Ctrl+. to show code actions.
1. Select "Fully qualifiy 'Foo'".
1. Select one of the command palette choices, then undo and repeat, but select the other choice to confirm that they both produce the same result.

To reproduce example 2:

1. Define a method signature with multiple inline parameters.
1. Press Ctrl+. to show code actions.
1. Select "Wrap every parameter".
1. Select any of the command palette choices, which all do the same thing.

## Expected Behavior ##

Nested code actions should support all available choices and show them in the command palette clearly.

In example 1 above, I'd expect the choices to be:
- Amazon.Runtime.Internal.Util.ILogger
- Castle.Core.Logging.ILogger
- Microsoft.Extensions.Logging.ILogger

In example 2, it looks like the choices are supposed to be:
- Align wrapped parameters
- Indent all parameters
- Indent wrapped parameters 

## Logs ##

Let me know if logs are needed.

## Environment information ##

**VSCode version**: 1.85.1
**C# Extension**: 2.14.8
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.6c33ef20

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100\

.NET workloads installed:
 Workload version: 8.0.100-manifests.6c33ef20
There are no installed workloads to display.

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  8.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|Bookmarks|alefragnani|13.4.2|alefragnani.bookmarks-13.4.2|
|csharp|ms-dotnettools|2.14.8|ms-dotnettools.csharp-2.14.8-win32-x64|
|EditorConfig|EditorConfig|0.16.4|editorconfig.editorconfig-0.16.4|
|errorlens|usernamehw|3.15.0|usernamehw.errorlens-3.15.0|
|git-graph|mhutchie|1.30.0|mhutchie.git-graph-1.30.0|
|gitignore|codezombiech|0.9.0|codezombiech.gitignore-0.9.0|
|gitlab-workflow|GitLab|3.93.1|gitlab.gitlab-workflow-3.93.1|
|gitlens|eamodio|14.6.1|eamodio.gitlens-14.6.1|
|intellicode-api-usage-examples|VisualStudioExptTeam|0.2.8|visualstudioexptteam.intellicode-api-usage-examples-0.2.8|
|live-server|ms-vscode|0.4.13|ms-vscode.live-server-0.4.13|
|msbuild-project-tools|tintoy|0.5.3|tintoy.msbuild-project-tools-0.5.3|
|partial-diff|ryu1kn|1.4.3|ryu1kn.partial-diff-1.4.3|
|vscode-cfn-lint|kddejong|0.25.2|kddejong.vscode-cfn-lint-0.25.2|
|vscode-coverage-gutters|ryanluker|2.11.1|ryanluker.vscode-coverage-gutters-2.11.1|
|vscode-dotnet-runtime|ms-dotnettools|2.0.0|ms-dotnettools.vscode-dotnet-runtime-2.0.0|
|vscode-graphql-syntax|GraphQL|1.2.2|graphql.vscode-graphql-syntax-1.2.2|
|vscode-markdownlint|DavidAnson|0.53.0|davidanson.vscode-markdownlint-0.53.0|
|vscode-todo-highlight|jgclark|2.0.8|jgclark.vscode-todo-highlight-2.0.8|
|vscode-versionlens|pflannery|1.9.2|pflannery.vscode-versionlens-1.9.2|
|vscode-yaml|redhat|1.14.0|redhat.vscode-yaml-1.14.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.30|visualstudioexptteam.vscodeintellicode-1.2.30|;

</details>

**Comment by akhera99** [comment]
Fixed in https://github.com/dotnet/roslyn/pull/71456.
