### ISSUE TITLE
Formatter splits comments onto next line

### ISSUE THREAD

**Issue by james-white-x** [dotnet/vscode-csharp#6776]
Type: <b>Bug</b>

## Issue Description ##
If your comment makes the line too long, it is formatted onto 2 separate lines. When you are using // for the comment, it just makes the text live code as it is not on the same line anymore.

## Steps to Reproduce ##
Make line long enough to format, with comment at the end

## Expected Behavior ##
Do not format comments

## Actual Behavior ##
Splits comment creating errors in the code

### C# log ###
<details>Post the output from Output-->C# here</details>

### C# LSP Trace Logs ###
<details>Post the output from Output-->C# LSP Trace Logs here.  Requires `dotnet.server.trace` to be set to `Trace`</details>

## Environment information ##

**VSCode version**: 1.85.1
**C# Extension**: 2.14.8
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.114
 Commit:    b2a71039cd

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/lib/dotnet/sdk/7.0.114/

Host:
  Version:      7.0.14
  Architecture: x64
  Commit:       808851b07a

.NET SDKs installed:
  7.0.114 [/usr/lib/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.14 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.14 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|aspnetcorerazor-html-css-class-completion|kevin-chatham|1.0.3|kevin-chatham.aspnetcorerazor-html-css-class-completion-1.0.3|
|csharp|ms-dotnettools|2.14.8|ms-dotnettools.csharp-2.14.8-linux-x64|
|data-workspace-vscode|ms-mssql|0.5.0|ms-mssql.data-workspace-vscode-0.5.0|
|git-graph|mhutchie|1.30.0|mhutchie.git-graph-1.30.0|
|gitflow|vector-of-bool|1.2.1|vector-of-bool.gitflow-1.2.1|
|githistory|donjayamanne|0.6.20|donjayamanne.githistory-0.6.20|
|gitlens|eamodio|14.6.1|eamodio.gitlens-14.6.1|
|mssql|ms-mssql|1.22.0|ms-mssql.mssql-1.22.0|
|powershell|ms-vscode|2023.8.0|ms-vscode.powershell-2023.8.0|
|prettier-sql-vscode|inferrinizzard|1.6.0|inferrinizzard.prettier-sql-vscode-1.6.0|
|prettier-vscode|esbenp|10.1.0|esbenp.prettier-vscode-10.1.0|
|sql-bindings-vscode|ms-mssql|0.4.0|ms-mssql.sql-bindings-vscode-0.4.0|
|sql-database-projects-vscode|ms-mssql|1.4.1|ms-mssql.sql-database-projects-vscode-1.4.1|
|sqltools|mtxr|0.28.1|mtxr.sqltools-0.28.1|
|sqltools-driver-mssql|mtxr|0.4.2|mtxr.sqltools-driver-mssql-0.4.2|
|svg|jock|1.5.3|jock.svg-1.5.3|
|todo-tree|Gruntfuggly|0.0.226|gruntfuggly.todo-tree-0.0.226|
|vscode-color-picker|AntiAntiSepticeye|0.0.4|antiantisepticeye.vscode-color-picker-0.0.4|
|vscode-dotnet-pack|ms-dotnettools|1.0.13|ms-dotnettools.vscode-dotnet-pack-1.0.13|
|vscode-dotnet-runtime|ms-dotnettools|2.0.0|ms-dotnettools.vscode-dotnet-runtime-2.0.0|
|vscode-eslint|dbaeumer|2.4.2|dbaeumer.vscode-eslint-2.4.2|
|vscode-html-css|ecmel|1.14.1|ecmel.vscode-html-css-1.14.1|
|vscode-import-cost|wix|3.3.0|wix.vscode-import-cost-3.3.0|
|vscode-jest|Orta|5.2.3|orta.vscode-jest-5.2.3|
|vscode-lottie|lottiefiles|1.0.5|lottiefiles.vscode-lottie-1.0.5|
|vscode-markdownlint|DavidAnson|0.53.0|davidanson.vscode-markdownlint-0.53.0|
|vscode-nuget-gallery|patcx|0.0.24|patcx.vscode-nuget-gallery-0.0.24|
|vscode-pull-request-github|GitHub|0.78.1|github.vscode-pull-request-github-0.78.1|
|vscode-xml|redhat|0.26.1|redhat.vscode-xml-0.26.1-linux-x64|
|vscode-yaml|redhat|1.14.0|redhat.vscode-yaml-1.14.0|;

</details>

Extension version: 2.13.10
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 Microsoft Surface (R) Edition (16 x 1996)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.45GB (2.22GB free)|
|Process Argv|--crash-reporter-id f28b5a18-e7d9-4c97-873a-6695beca75bd|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.133.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 Microsoft Surface (R) Edition (8 x 1996)|
|Memory (System)|7.76GB (1.97GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
vsjup518:30340749
vshan820:30294714
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyonecf:30548226
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
962ge761:30917236
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30885898
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184c:30925681

```

</details>

**Comment by JoeRobich** [comment]
@james-white-x This surprises me because the Roslyn formatter shouldn't be splitting long lines (even comments). How long does a line have to be to be considered too long?

**Comment by dibarbet** [comment]
Indeed I wouldn't expect roslyn to be splitting this.  Would you mind sharing a before/after snippet or gif of the behavior?

**Comment by JoeRobich** [comment]
My current assumption is that this is occurring in a razor file (.razor or .cshtml). VS Code has a `html.format.wrapLineLength` setting for the html formatter which runs even in C# code "blocks".

```razor
@code {
    // This comment is in a razor file code section and is really long. In fact it is longer that the 120 character `html.format.wrapLineLength` setting that is the VS Code default.
    private bool collapseNavMenu = true;

    private string? NavMenuCssClass => collapseNavMenu ? "collapse" : null;

    private void ToggleNavMenu()
    {
        collapseNavMenu = !collapseNavMenu;
    }
}
```

**Comment by james-white-x** [comment]
You are exactly right, is in a .razor file. Thanks for looking into it, I will work round it

**Comment by dibarbet** [comment]
Tagging @davidwengier in case there is anything that can be done from the Razor side to make this better.

**Comment by davidwengier** [comment]
Have definitely seen this before, and the `wrapLineLength` setting should work, but you'd have to change it for all Html files. There is no way I know of to call out just Html files produced from Razor documents. That said, the way this manifests in Visual Studio is that people report that Razor formatting is not working, as we detect it and reject the format operation as a whole. I suspect the wrapping of the comment is a better user experience, as at least people can see what is going on and correct it. If format on save is enabled though, perhaps not.

This will be fixed eventually with https://github.com/dotnet/razor/issues/7564

**Comment by JoeRobich** [comment]
We could try talking the VS Code team into making the [html formatting settings](https://github.com/microsoft/vscode/blob/b69fb3a61bf0c51cb3210f1da71c0f4d3d0e509b/extensions/html-language-features/package.json#L76) scoped as "language-overridable" instead of "resource".
