### ISSUE TITLE
Allow go to external source in intellisense

### ISSUE THREAD

**Issue by Smoovsky** [dotnet/vscode-csharp#6784]
When debugging with just my code disabled + search Microsoft symbol server enabled(or adding my own symbol folder in symbol search paths), I can step into external source code. Can you extend this feature to intellisense? i.e. when the user performs "Go to Definition" action, the editor opens the external source code if the matching source is found in symbol server/path.  I believe such behavior is enabled in Rider by default, and Visual Studio can also be configured to navigate to external source.

**Comment by dibarbet** [comment]
We plan to add sourcelink support of some sort to C# at some point in the next couple of months (cc @mikadumont , we can use this issue for tracking).

**Comment by victorvhpg** [comment]
@dibarbet any update ? support for source link in C#/devkit

**Comment by rmannibucau** [comment]
any news? this would be a key feature IMHO and can avoid to have to clone dotnet/runtime

**Comment by vchirikov** [comment]
> We plan to add sourcelink support (for go to definition / references) to C# at some point in the next couple of months (cc @mikadumont , we can use this issue for tracking).

@dibarbet thanks for your work. Do we have a separate issue to subscribe for "Go To References" part in decompiled/source link?

**Comment by dibarbet** [comment]
This should be available in the next prerelease of C#.  It will require  C# DevKit, version `v1.10.6 (pre-release)` or higher.  Will reply here when the C# prerelease build is available.

**Comment by vchirikov** [comment]
> Are you looking for find references to work when invoked from inside a decompiled/source/metadata document? There should already be partial support for that (though due to lack of information in the metadata it won't have everything)

Exactly, it would be very useful to have a "Find Usages" inside already decompiled DLLs like Rider has.
