### ISSUE TITLE
Add new class or interface

### ISSUE THREAD

**Issue by bogdan-iuga** [dotnet/vscode-csharp#6796]
Type: <b>Feature Request</b>

Please add functionality to create new files (e.g. class/interface/view) with class names, namespaces and other added automatically.

Switching to VS Code I find that some basic features from VS/VS for Mac like adding a new class/interface from the context menu are missing. 
It would be nice to be able to add new files via context menu or a command.

 

Extension version: 2.14.8
VS Code version: Code 1.85.1 (Universal) (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:48:06.308Z)
OS version: Darwin arm64 23.2.0
Modes:

**Comment by Igorgro** [comment]
Another inspiration is class creation dialog from Android Studio 
![image](https://github.com/dotnet/vscode-csharp/assets/22894169/c0a9933b-3379-447c-947c-0358fc36af67)

**Comment by dibarbet** [comment]
A similar feature should already be present if you also have the C# devkit extension.  Right clicking the project in the solution explorer should show this context menu:
<img width="302" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/5749229/1d754e66-4091-4e7b-be5a-33db00d1604c">

If you're have issues or suggestions for improvements for the c# devkit feature, please file an issue at https://github.com/microsoft/vscode-dotnettools/issues 

We don't currently have plans to add this to the standalone C# extension.

**Comment by bogdan-iuga** [comment]
@dibarbet that was exactly what I was looking for. 
It seems to be adding the top-most namespace only, not scoped, but it's good enough.
To be honest, I did not see the solution explorer pane, as I think it is minified by default, having the Folders one expanded.

**Comment by alexalok** [comment]
> A similar feature should already be present if you also have the C# devkit extension. Right clicking the project in the solution explorer should show this context menu:

Hey @dibarbet, 

do you mind me asking if there is a keyboard shortcut for this?

**Comment by dibarbet** [comment]
@alexalok there is a '.NET: New File' command, however it looks like it doesn't give you any of the template options that the context menu item does.
If it works for you, you can bind it to a keyboard shortcut
![image](https://github.com/user-attachments/assets/8bb05559-48cb-457c-a6c2-243ab1a6d07c)

Otherwise, if you'd like the full context menu item with templates available, you'll probably need to file an issue at https://github.com/microsoft/vscode-dotnettools/issues
