### ISSUE TITLE
IntelliSense is not working

### ISSUE THREAD

**Issue by NandaPRomadhona** [dotnet/vscode-csharp#6800]
## Environment data
`dotnet --info` output:
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.6c33ef20

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.2
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   ~/.vscode-dotnet-sdk/.dotnet/sdk/8.0.100/

.NET workloads installed:
 Workload version: 8.0.100-manifests.6c33ef20
There are no installed workloads to display.

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  8.0.100 [~/.vscode-dotnet-sdk/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0 [~/.vscode-dotnet-sdk/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0 [~/.vscode-dotnet-sdk/.dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  arm64 [/usr/local/share/dotnet]
    registered at [/etc/dotnet/install_location_arm64]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

VS Code version:
Version: 1.85.1 (Universal)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:48:06.308Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.2.0

C# Extension version:
v2.14.8

### C# output
Installing Razor Telemetry Version = 7.0.0-preview.23528.1...
Platform: darwin, arm64

Downloading package 'Razor Language Server Telemetry (macOS ARM64)' (9091 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package 'Razor Language Server Telemetry (macOS ARM64)'

Finished

Dotnet path: /usr/local/share/dotnet/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
waiting for named pipe information from server...
[stdout] {"pipeName":"/var/folders/x3/r_gypsmj679gzk18xtyy86700000gn/T/8e81a94f.sock"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 4:51:48 PM] [Program] Language server initialized

### C# Dev Kit output
Starting Open a solution...
Starting Open a solution with environment service...
Starting Clear environment...
Starting Spawn .NET server...
Using local .NET runtime at "~/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.15~arm64/dotnet"
Using runtime installed in SDK.
.NET server started and IPC established in 2117ms
Completed Spawn .NET server (9126ms)
Completed Clear environment (9289ms)
Completed Open a solution with environment service (9355ms)
Starting Restore solution...
Completed Open a solution (9358ms)
Starting NuGet restore for the solution.
Starting command: "dotnet" restore ~/dotnet Projects/DotnetAPI/DotnetAPI.sln --interactive...
Completed command: "dotnet" restore ~/dotnet Projects/DotnetAPI/DotnetAPI.sln --interactive (588ms)
Completed NuGet restore.
Completed Restore solution (589ms)
[object Object]
[object Object]

### IntelliCode for C# Dev Kit
Inline Completions document change subscription registered.
Initializing IntelliCode Inline Completions
[Completions][2]: Completions worker with process id 60926 has been created
Inline Completions Initialized
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 0]  Entered provideInlineCompletionItems() try block
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 0] Starting request
[Completions][1]: [WorkerLineCompletionService.request() 1]  Entered
[Completions][2]: [Child process] Worker with pid 60926 has started
[Completions][2]: [Child process] Requested setting state for intellicode-completions.internal.defaultConfidenceThreshold = 0.39 (default is 0.39)
[Completions][2]: [Child process] Requested setting state for intellicode-completions.internal.defaultConfidenceThreshold = 0.39 (default is 0.39)
[Completions][2]: [Child process] Requested setting state for intellicode-completions.internal.defaultConfidenceThreshold = 0.39 (default is 0.39)
[Completions][2]: [Child process] Requested setting state for intellicode-completions.internal.defaultConfidenceThreshold = 0.39 (default is 0.39)
[Completions][2]: [Child process] Requested setting state for intellicode-completions.internal.defaultConfidenceThreshold = 0.39 (default is 0.39)
[Completions][2]: [Child process] Requested setting state for intellicode-completions.internal.defaultConfidenceThreshold = 0.39 (default is 0.39)
[Completions][2]: [Child process] Requested setting state for intellicode-completions.internal.defaultConfidenceThreshold = 0.39 (default is 0.39)
[Completions][4]: [Child process] Unhandled rejection error: Failed to parse URL from ~/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-0.1.26-darwin-arm64/dist/node_modules/@vsintellicode/completions-csharp/tree-sitter.wasm
[Completions][4]: [Child process] Unhandled rejection error stack: TypeError: Failed to parse URL from ~/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-0.1.26-darwin-arm64/dist/node_modules/@vsintellicode/completions-csharp/tree-sitter.wasm
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Completions][4]: [Child process] Unhandled rejection error: Failed to parse URL from ~/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-0.1.26-darwin-arm64/dist/node_modules/@vsintellicode/completions-csharp/blingfire.wasm
[Completions][4]: [Child process] Unhandled rejection error stack: TypeError: Failed to parse URL from ~/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-0.1.26-darwin-arm64/dist/node_modules/@vsintellicode/completions-csharp/blingfire.wasm
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Completions][2]: [inlineCompletionProvider.provideInlineCompletionItems() 0]  Recieved cancellation event, ran for 688.5884999632835
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 1]  Entered provideInlineCompletionItems() try block
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 1] Skipping request
[Completions][2]: [CompletionState.getLineCompletion()] : Best suffix
	First token score log confidence: 0 < -0.35667494393873245
	Suggestion: 
[Completions][2]: [inlineCompletionProvider.provideInlineCompletionItems() 1]  Candidate completion: 
[Completions][2]: [inlineCompletionProvider.provideInlineCompletionItems() 1]  Current line with candidate:

[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 1]  Completion was filtered out because Completion line is an empty string
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 2]  Entered provideInlineCompletionItems() try block
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 2] Starting request
[Completions][2]: [inlineCompletionProvider.provideInlineCompletionItems() 2]  Recieved cancellation event, ran for 191.09962499141693
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 3]  Entered provideInlineCompletionItems() try block
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 3] Skipping request
[Completions][2]: [CompletionState.getLineCompletion()] : Best suffix
	First token score log confidence: 0 < -0.35667494393873245
	Suggestion: 
[Completions][2]: [inlineCompletionProvider.provideInlineCompletionItems() 3]  Candidate completion: 
[Completions][2]: [inlineCompletionProvider.provideInlineCompletionItems() 3]  Current line with candidate:

[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 3]  Completion was filtered out because Completion line is an empty string
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 4]  Entered provideInlineCompletionItems() try block
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 4] Starting request
[Completions][2]: [inlineCompletionProvider.provideInlineCompletionItems() 4]  Recieved cancellation event, ran for 1257.6486250162125
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 5]  Entered provideInlineCompletionItems() try block
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 5] Starting request
[Completions][2]: [inlineCompletionProvider.provideInlineCompletionItems() 5]  Recieved cancellation event, ran for 6.781875014305115
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 6]  Entered provideInlineCompletionItems() try block
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 6] Starting request
[Completions][2]: [inlineCompletionProvider.provideInlineCompletionItems() 6]  Recieved cancellation event, ran for 502.8018749952316
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 7]  Entered provideInlineCompletionItems() try block
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 7] Starting request
[Completions][2]: [inlineCompletionProvider.provideInlineCompletionItems() 7]  Recieved cancellation event, ran for 122.37620800733566
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 8]  Entered provideInlineCompletionItems() try block
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 8] Starting request
[Completions][2]: [inlineCompletionProvider.provideInlineCompletionItems() 8]  Recieved cancellation event, ran for 110.75524997711182
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 9]  Entered provideInlineCompletionItems() try block
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 9] Starting request
[Completions][2]: [inlineCompletionProvider.provideInlineCompletionItems() 9]  Recieved cancellation event, ran for 359.57916700839996
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 10]  Entered provideInlineCompletionItems() try block
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 10] Starting request
[Completions][4]: [inlineCompletionProvider.provideInlineCompletionItems() 0]  Caught error when requesting inline completion: Error: Operation took longer than 5000ms.
[Completions][2]: [inlineCompletionProvider.provideInlineCompletionItems() 0] 
	Wait: 0.2937920093536377ms
	Full inference: 5001.033083021641
[Completions][4]: [inlineCompletionProvider.provideInlineCompletionItems() 0] Unexpected exception: Operation took longer than 5000ms.
Error: Operation took longer than 5000ms.
	at Timeout._onTimeout (~/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-0.1.26-darwin-arm64/dist/node_modules/@vsintellicode/completions-csharp/index.js:2:66913)
	at listOnTimeout (node:internal/timers:569:17)
	at process.processTimers (node:internal/timers:512:7)
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 2] Cancelled after 3757.290250003338ms wait
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 4] Cancelled after 3266.416792035103ms wait
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 5] Cancelled after 1930.9468330144882ms wait
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 6] Cancelled after 1844.8192920088768ms wait
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 7] Cancelled after 1263.0315830111504ms wait
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 8] Cancelled after 1062.2035840153694ms wait
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 9] Cancelled after 874.2863749861717ms wait
[Completions][1]: [WorkerLineCompletionService.request() 11]  Entered
[Completions][2]: [inlineCompletionProvider.provideInlineCompletionItems() 10]  Recieved cancellation event, ran for 729.8282089829445
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 11]  Entered provideInlineCompletionItems() try block
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 11] Starting request
[Completions][2]: [inlineCompletionProvider.provideInlineCompletionItems() 11]  Recieved cancellation event, ran for 354.4300840497017
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 12]  Entered provideInlineCompletionItems() try block
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 12] Starting request
[Completions][2]: [inlineCompletionProvider.provideInlineCompletionItems() 12]  Recieved cancellation event, ran for 2555.208708047867
[Completions][4]: [inlineCompletionProvider.provideInlineCompletionItems() 10]  Caught error when requesting inline completion: Error: Operation took longer than 5000ms.
[Completions][2]: [inlineCompletionProvider.provideInlineCompletionItems() 10] 
	Wait: 437.3709579706192ms
	Full inference: 5005.9149169921875
[Completions][4]: [inlineCompletionProvider.provideInlineCompletionItems() 10] Unexpected exception: Operation took longer than 5000ms.
Error: Operation took longer than 5000ms.
	at Timeout._onTimeout (~/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-0.1.26-darwin-arm64/dist/node_modules/@vsintellicode/completions-csharp/index.js:2:66913)
	at listOnTimeout (node:internal/timers:569:17)
	at process.processTimers (node:internal/timers:512:7)
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 11] Cancelled after 4636.702125012875ms wait
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 12] Cancelled after 4204.492082953453ms wait

## Steps to reproduce

1. Install VS Code for Silicon Mac
2. Install C# Dev Kit
3. Create new project
4. No Suggestion or AutoComplete(IntelliSense)

## Expected  behavior
Can provide appropriate suggestions, AutoComplete, or Predictions of up to a whole-line of code, along with ranking methods and properties in the IntelliSense list are available.

## Actual behavior
<img width="542" alt="Screenshot 2024-01-10 at 5 13 22 PM" src="https://github.com/dotnet/vscode-csharp/assets/17807283/1550982c-50a8-4343-9d2d-9f74e7e38d28">

If anyone has experienced the same thing, could you please write the solution here? Thank you

**Comment by dibarbet** [comment]
@NandaPRomadhona I see you have the x64 version of dotnet installed, but you're using an arm64 Mac.  Can you uninstall your current dotnet version and re-install the arm64 version of dotnet?

If that still doesn't work, some additional information would be useful:
1.  Do you see the project in the solution explorer in the left, e.g. 
<img width="388" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/5749229/fc098596-bd78-4205-bc03-82361cbe54c4">
2.  Can you paste the output of the 'Projects' output window?
3.  Can you paste the output of the 'C# Dev Kit' output window?

**Comment by NandaPRomadhona** [comment]
> @NandaPRomadhona I see you have the x64 version of dotnet installed, but you're using an arm64 Mac. Can you uninstall your current dotnet version and re-install the arm64 version of dotnet?
> 
> If that still doesn't work, some additional information would be useful:
> 
> 1. Do you see the project in the solution explorer in the left, e.g.
> 
> <img alt="image" width="388" src="https://private-user-images.githubusercontent.com/5749229/295737333-fc098596-bd78-4205-bc03-82361cbe54c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MjkwMjgsIm5iZiI6MTcwNDkyODcyOCwicGF0aCI6Ii81NzQ5MjI5LzI5NTczNzMzMy1mYzA5ODU5Ni1iZDc4LTQyMDUtYmMwMy04MjM2MWNiZTU0YzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTBUMjMxODQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTJjYWRiZTM1ZGNmMzdhNDNhZTcwNzMzZjBiMTY0MjQ4ZWVlN2QzOWNmMzljYmU4M2ExOWQ3NDFmMmMzODY4YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WJ2RAEkd2nymgZn5PuRnVW5wNBrV88yqzsjxwhKRM9w">
> 2. Can you paste the output of the 'Projects' output window?
> 3. Can you paste the output of the 'C# Dev Kit' output window?

Thank you @dibarbet. I re-installed .NET for arm64, and it's working now.  Just wanted to share that I used [this reference](https://devkimchi.com/2021/11/24/removing-dotnet-sdks-from-macos-manually/) to safely uninstall the old version.
