### ISSUE TITLE
VSCODE characters referenced by the outline show garbled

### ISSUE THREAD

**Issue by Haku326049** [dotnet/vscode-csharp#6804]
VSCODE When I open the c file directly and do nothing, the Chinese variable characters referenced by the outline show garbled.

**Comment by dibarbet** [comment]
@Haku326049 would you be able to provide a screenshot of what isn't working (and any reproduction steps if you have any)?

**Comment by dibarbet** [comment]
Closing, not actionable in the current state.  If you're able to provide more information please re-open with additional details.
