### ISSUE TITLE
Cannot Open Solution Explorer without having a previous csproj file

### ISSUE THREAD

**Issue by karl-gardner** [dotnet/vscode-csharp#6809]
When using vscode for learning C# or even developing in production code it is not possible to open the solution explorer without actually having a previous .sln file. Thus it is required to use the dotnet command line interface and create a console application. Only then we can start another project or solution with the solution explorer. It would be nice if we could just open the solution explorer somehow straight from vscode.

**Comment by dibarbet** [comment]
Solution explorer is managed by C# devkit, transferring over to their issues page.  Please track this here - https://github.com/microsoft/vscode-dotnettools/issues/865
