### ISSUE TITLE
Solution Explorer not opening after moving to the right side

### ISSUE THREAD

**Issue by karl-gardner** [dotnet/vscode-csharp#6811]
## Environment data
VS Code version:
Newest version available
C# Extension version:
Newest Version available

## Steps to reproduce

1. Download vscode and C# Dev Kit extension
2. Open existing C# projects/solution or create a new project with "dotnet new console" command.
3. Close vscode
4. Open folder containing c# project with vscode and notice the solution explorer pop up on the bottom left side (might need to sign in to microsoft to use c# dev kit):
<img width="1305" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/91646805/6d433c02-2bfe-44e0-8eac-56f22e2a0d4f">

5.  Drag the solution explorer over to the right side to be able to see it better instead of the bottom left side (outlined in red):

<img width="1336" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/91646805/22849b40-e2ae-4a1c-96e4-2b16129f330d">

6. Close vscode. Open same folder or any other folder containing c# project (csproj files). Now solution explorer is missing:

<img width="1312" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/91646805/0cca9e90-eb73-4a12-a343-c40c0b8d9e35">

## Expected  behavior
The solution explorer is supposed to show up in vs code when opening a c# project containing a csproj file. Preferably it will show up in the same location that it was left at like on the right side of the screen.

## Actual behavior
Does not even show up anywhere. 

## Additional context
Once the solution explorer is moved to the right side of the screen and vs code is closed it will not show up anywhere and I can't find where to open it again. Let me know if you are not able to recreate this. I have recreated it multiple times now.

**Comment by dibarbet** [comment]
Solution explorer is managed by the C# devkit extension - transferring this over to their issues page, please track it here - https://github.com/microsoft/vscode-dotnettools/issues/864
