### ISSUE TITLE
doesn't work on WLS

### ISSUE THREAD

**Issue by manbor** [dotnet/vscode-csharp#6815]
Type: <b>Bug</b>

There is a bug with C# and VS Code...

C# extension doesn't work well on VSCode when it is working on wsl ( Remote ). 
- CTRL+click on object doesn't work ( element isn't underlined and nothing do if i try to click)
- every time that i load vs code (wsl workspace), vs code generates the following error
- this window ( Issue Reporter ) doesn't open in "WSL mode" (it opens a popup window that say something like class.reportIssue not found"

Last working version of C# extension (on WLS) is 2.1.2.  I will revert to this one on WLS
On host machine everything works well  ( window 11 pro )
-----------------------------------------------------------------------------------------------

Using dotnet configured on PATH
Dotnet path: /usr/share/dotnet/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
Starting server at /home/manuele/.vscode-server/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.LanguageServer
Server arguments --debug --logLevel Trace --starredCompletionComponentPath /home/manuele/.vscode-server/extensions/ms-dotnettools.vscodeintellicode-csharp-0.1.26-linux-x64/components/starred-suggestions/node_modules/@vsintellicode/starred-suggestions-csharp --extension /home/manuele/.vscode-server/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslynDevKit/Microsoft.VisualStudio.LanguageServices.DevKit.dll --sessionId 7d4cecc3-55ac-456e-926e-62bc814bd0251705508931995 --telemetryLevel all --extensionLogDirectory /home/manuele/.vscode-server/data/logs/20240117T132254/exthost3/ms-dotnettools.csharp
waiting for named pipe information from server...
[stdout] crit: Program[0]
      Server started with process ID 49270
[stdout] crit: Program[0]
      Waiting 0:01:00 for a debugger to attach
[Error - 5:29:35 PM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
Error: Timeout. Named pipe information not received from server.
    at Function.<anonymous> (/home/manuele/.vscode-server/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/dist/extension.js:2:1290803)
    at Generator.next (<anonymous>)
    at s (/home/manuele/.vscode-server/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/dist/extension.js:2:1280740)
[stdout] trce: Program[0]
      .NET Runtime Version: .NET 8.0.0
[stdout] dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/manuele/.vscode-server/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.Features.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/manuele/.vscode-server/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.Remote.Workspaces.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/manuele/.vscode-server/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.CSharp.dll added to workspace.
[stdout] dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/manuele/.vscode-server/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/manuele/.vscode-server/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.ExternalAccess.AspNetCore.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/manuele/.vscode-server/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.Elfie.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/manuele/.vscode-server/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.Razor.Compiler.Mvc.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/manuele/.vscode-server/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.Razor.Compiler.Language.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/manuele/.vscode-server/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/manuele/.vscode-server/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.Workspaces.dll added to workspace.
[stdout] dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/manuele/.vscode-server/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.CSharp.Workspaces.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/manuele/.vscode-server/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.Workspaces.MSBuild.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/manuele/.vscode-server/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/manuele/.vscode-server/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.Razor.Compiler.Mvc.Version1_X.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/manuele/.vscode-server/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.CSharp.Features.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/manuele/.vscode-server/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.Razor.Compiler.CSharp.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/manuele/.vscode-server/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.Razor.Compiler.Mvc.Version2_X.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/manuele/.vscode-server/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.AnalyzerUtilities.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/manuele/.vscode-server/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.Scripting.dll added to workspace.
[stdout] {"pipeName":"/tmp/813b4c1d.sock"}
received named pipe information from server

Extension version: 2.15.30
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22635
Modes:
Remote OS version: Linux x64 5.15.137.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.68GB (2.16GB free)|
|Process Argv|--crash-reporter-id b3e68315-a427-4827-b01c-7a7f58d8bb8a|
|Screen Reader|no|
|VM|33%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.137.3-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|Memory (System)|7.60GB (4.66GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
azure-dev_surveyone:30548225
0bi6i642:30933247
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019acf:30933242

```

</details>

**Comment by dibarbet** [comment]
> Waiting 0:01:00 for a debugger to attach
[Error - 5:29:35 PM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
Error: Timeout. Named pipe information not received from server.

@manbor it looks like you might have the `dotnet.server.waitForDebugger` option checked - can you uncheck it and see if it works?  If you don't attach a debugger the client will time out waiting for the server to connect and nothing will work.

Should look like this:
<img width="915" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/5749229/380921eb-3b3a-4d18-880a-36445d28d183">

**Comment by manbor** [comment]
It appears to work now.
Thanks for support

**Comment by dibarbet** [comment]
Great, glad it works!
