### ISSUE TITLE
The problem still exists, has it been released to the official version?

### ISSUE THREAD

**Issue by whitecostume** [dotnet/vscode-csharp#6820]
The problem still exists, has it been released to the official version?

_Originally posted by @whitecostume in https://github.com/dotnet/vscode-csharp/issues/6420#issuecomment-1898636788_

**Comment by jasonmalinowski** [comment]
@whitecostume Your bug was closed as a duplicate; the original issue is still open. Did you have a different concern or do you think it wasn't correctly marked as a duplicate?

**Comment by whitecostume** [comment]
Okay, sorry, I thought that was resolved.
