### ISSUE TITLE
Primary Constructor parameters shown as null in debugger

### ISSUE THREAD

**Issue by JensWallgren** [dotnet/vscode-csharp#6827]
Type: <b>Bug</b>

## Steps to Reproduce ##
1. Set up a class that uses the C#12 primary constructors
2. Implement an async method that accesses parameters defined in the primary constructor
    (note that non-async methods work fine)
3. Set a breakpoint in the method
4. Inspect the primary constructor parameters. They show up as null

Here's a minimal project that reproduces the problem:
[Github repo](https://github.com/JensWallgren/vscode-csharp-debug-bugreport)

## Expected Behavior ##
Expecting that I can view the value of the primary constructor parameters.

## Actual Behavior ##
The value of the primary constructor parameters are always shown as null.

Screenshot showing how it looks in the debugger:
*(note that Message is null, while message can be watched):*

![async](https://github.com/dotnet/vscode-csharp/assets/29680165/686986e1-75c4-45d4-9f17-2eead6c408ec)

Screenshot of how a non-async method looks. This works fine and how I'd expect 
*(note that both Message and message can be watched):*

![non-async](https://github.com/dotnet/vscode-csharp/assets/29680165/2dc48dcc-50f0-4567-8b5e-5f898105f180)

### OmniSharp log ###
<details>(no log)</details>
        
### C# log ###
<details>(no log)</details>

## Environment information ##

**VSCode version**: 1.85.1
**C# Extension**: 2.15.30
**Using OmniSharp**: true

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:           8.0.101
 Commit:            6eceda187b
 Workload version:  8.0.100-manifests.69afb982

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.101\

.NET workloads installed:
 Workload version: 8.0.100-manifests.69afb982
There are no installed workloads to display.

Host:
  Version:      8.0.1
  Architecture: x64
  Commit:       bf5e279d92

.NET SDKs installed:
  6.0.126 [C:\Program Files\dotnet\sdk]
  7.0.115 [C:\Program Files\dotnet\sdk]
  8.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|app-studio-remote-access|SAPOSS|1.15.15|saposs.app-studio-remote-access-1.15.15|
|app-studio-toolkit|SAPOSS|1.15.19|saposs.app-studio-toolkit-1.15.19|
|atlascode|atlassian|3.0.9|atlassian.atlascode-3.0.9|
|azure-account|ms-vscode|0.11.6|ms-vscode.azure-account-0.11.6|
|azurite|Azurite|3.29.0|azurite.azurite-3.29.0|
|binary-plist|dnicolson|0.11.3|dnicolson.binary-plist-0.11.3|
|blue-forest|Amirabbas|1.5.7|amirabbas.blue-forest-1.5.7|
|blueberry-dark-theme|peymanslh|1.1.1|peymanslh.blueberry-dark-theme-1.1.1|
|cds|hudakf|0.7.2|hudakf.cds-0.7.2|
|copilot|GitHub|1.153.0|github.copilot-1.153.0|
|copilot-chat|GitHub|0.11.1|github.copilot-chat-0.11.1|
|csharp|ms-dotnettools|2.15.30|ms-dotnettools.csharp-2.15.30-win32-x64|
|dmn-vscode-extension|kie-group|0.32.0|kie-group.dmn-vscode-extension-0.32.0|
|gesper|ariondev|1.0.0|ariondev.gesper-1.0.0|
|groovy|MellowMarshmallow|1.0.0|mellowmarshmallow.groovy-1.0.0|
|hexeditor|ms-vscode|1.9.12|ms-vscode.hexeditor-1.9.12|
|integrations-vscode|ImplemaIntegrations|0.7.10|implemaintegrations.integrations-vscode-0.7.10|
|intellicode-api-usage-examples|VisualStudioExptTeam|0.2.8|visualstudioexptteam.intellicode-api-usage-examples-0.2.8|
|java|redhat|1.26.0|redhat.java-1.26.0-win32-x64|
|linux-themes|SolarLiner|1.0.1|solarliner.linux-themes-1.0.1|
|live-server|ms-vscode|0.4.13|ms-vscode.live-server-0.4.13|
|markdown-preview-bitbucket|hbrok|1.0.0|hbrok.markdown-preview-bitbucket-1.0.0|
|material-palenight-theme|whizkydee|2.0.3|whizkydee.material-palenight-theme-2.0.3|
|nord-visual-studio-code|arcticicestudio|0.19.0|arcticicestudio.nord-visual-studio-code-0.19.0|
|pdf|tomoki1207|1.2.2|tomoki1207.pdf-1.2.2|
|powershell|ms-vscode|2024.0.0|ms-vscode.powershell-2024.0.0|
|python|ms-python|2023.22.1|ms-python.python-2023.22.1|
|remote-explorer|ms-vscode|0.4.1|ms-vscode.remote-explorer-0.4.1|
|remote-ssh|ms-vscode-remote|0.107.1|ms-vscode-remote.remote-ssh-0.107.1|
|remote-ssh-edit|ms-vscode-remote|0.86.0|ms-vscode-remote.remote-ssh-edit-0.86.0|
|rest-client|humao|0.25.1|humao.rest-client-0.25.1|
|swf-vscode-extension|kie-group|0.32.0|kie-group.swf-vscode-extension-0.32.0|
|tokyo-night|enkia|1.0.6|enkia.tokyo-night-1.0.6|
|vesper|raunofreiberg|0.0.39|raunofreiberg.vesper-0.0.39|
|vesper-pp|Obstinate|2.0.0|obstinate.vesper-pp-2.0.0|
|vim|vscodevim|1.27.2|vscodevim.vim-1.27.2|
|vsc-community-material-theme|Equinusocio|1.4.7|equinusocio.vsc-community-material-theme-1.4.7|
|vsc-material-theme|Equinusocio|34.3.1|equinusocio.vsc-material-theme-34.3.1|
|vsc-material-theme-icons|equinusocio|3.4.0|equinusocio.vsc-material-theme-icons-3.4.0|
|vscode-abap|larshp|0.5.8|larshp.vscode-abap-0.5.8|
|vscode-abap-remote-fs|murbani|1.7.3|murbani.vscode-abap-remote-fs-1.7.3|
|vscode-azureappservice|ms-azuretools|0.25.1|ms-azuretools.vscode-azureappservice-0.25.1|
|vscode-azurefunctions|ms-azuretools|1.13.1|ms-azuretools.vscode-azurefunctions-1.13.1|
|vscode-azureresourcegroups|ms-azuretools|0.8.3|ms-azuretools.vscode-azureresourcegroups-0.8.3|
|vscode-base64|adamhartford|0.1.0|adamhartford.vscode-base64-0.1.0|
|vscode-bicep|ms-azuretools|0.24.24|ms-azuretools.vscode-bicep-0.24.24|
|vscode-bpmn-editor|yleflour|1.0.4|yleflour.vscode-bpmn-editor-1.0.4|
|vscode-dotnet-runtime|ms-dotnettools|2.0.0|ms-dotnettools.vscode-dotnet-runtime-2.0.0|
|vscode-edifact|DAXaholic|0.8.0|daxaholic.vscode-edifact-0.8.0|
|vscode-extension-dashbuilder-editor|redhat|0.32.0|redhat.vscode-extension-dashbuilder-editor-0.32.0|
|vscode-groovy-lint|NicolasVuillamy|3.2.0|nicolasvuillamy.vscode-groovy-lint-3.2.0|
|vscode-java-debug|vscjava|0.55.0|vscjava.vscode-java-debug-0.55.0|
|vscode-java-dependency|vscjava|0.23.3|vscjava.vscode-java-dependency-0.23.3|
|vscode-java-pack|vscjava|0.25.15|vscjava.vscode-java-pack-0.25.15|
|vscode-java-test|vscjava|0.40.1|vscjava.vscode-java-test-0.40.1|
|vscode-maven|vscjava|0.43.0|vscjava.vscode-maven-0.43.0|
|vscode-pylance|ms-python|2023.12.1|ms-python.vscode-pylance-2023.12.1|
|vscode-wasm|dtsvet|1.4.1|dtsvet.vscode-wasm-1.4.1|
|vscode-xml|redhat|0.26.1|redhat.vscode-xml-0.26.1-win32-x64|
|vscode-yaml|redhat|1.14.0|redhat.vscode-yaml-1.14.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.30|visualstudioexptteam.vscodeintellicode-1.2.30|
|winregistry|murbani|0.0.1|murbani.winregistry-0.0.1|;

</details>

Extension version: 2.15.30
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (0.79GB free)|
|Process Argv|--crash-reporter-id fc6457ea-6fa0-466b-91ce-9335124774a9|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
0bi6i642:30933247
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302

```

</details>

**Comment by gregg-miskelly** [comment]
I believe this is already fixed in the expression evaluator, but this extension isn't shipping a new enough version of that yet. Fix: https://github.com/dotnet/roslyn/pull/70587

We can use this issue to track updating.

**Comment by gregg-miskelly** [comment]
I am sorry, I thought that fix was a fix to the expression evaluator. It turns out it was actually a compiler fix. So, you just need to update your .NET SDK to 8.0.101.

**Comment by JensWallgren** [comment]
Good to know that it has been addressed! Thanks for the help!
