### ISSUE TITLE
Target process is terminated when attempting to set breakpoints/step into optimized code

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/vscode-csharp#6828]
Opening issue on behalf of @NC-RVSO. Original text:

Hello there!
I have been using the ability to attach the debugger in a running Docker container, and I have worked like a charm.
However, now after we have updated to .Net 8 the debugger just dies when I try to attach, is this a common known bug? It's kind of a showstopper :) 
I can't really give any error codes  from Visual Studio, I just says "The debug adapter exited unexpectedly."
In Visual Studio code it just seems like it attaches, and then it drops. 
Are there soon a new version coming? Or am I the only one with this problem?

**Comment by gregg-miskelly** [comment]
@NC-RVSO This doesn't sound like a known issue. 

Are you seeing this with a 'hello world' project? 
Can you tell us more about your Docker image? (ex: are you using one of the .NET base images? Which one? If not, what is your base?)

I suspect the debugger is crashing, so I am not sure if this will be useful, but you can enable logging in VS Code with these instructions: https://github.com/dotnet/vscode-csharp/wiki/Enabling-C%23-debugger-logging

If you would prefer Visual Studio, here are the instructions there: https://github.com/microsoft/VSDebugAdapterHost/wiki/Logging

**Comment by NC-RVSO** [comment]
Thanks for moving my issue to the correct place :)
I have not tested on a clean project, I will try that, this is the output from VS:
 1> DebugAdapterHost version: 17.6.10907.1 commit:6fef36f95dd1139788bfdde4ba25a71b4ccdc1aa
 1> Determining user folder on remote system...
 1> Checking for existing installation of debugging tools...
 1> Downloading debugger launcher...
 1> Creating debugger installation folder: //.vs-debugger
 1> Creating directory '//.vs-debugger'
 1> Copying debugger launcher to //.vs-debugger/GetVsDbg.sh
 1> Copying file: 'C:\Users\rvso\AppData\Local\Temp\tmp787F.tmp' -> '//.vs-debugger/GetVsDbg.sh'
 1> Failed: Failed to copy files.
 1> Executing command '[ -f "//.vs-debugger/GetVsDbg.sh" ]' with arguments ''
 1>   Command exited with code '0'
 1> Launching remote debugger...
 1> Starting '/bin/sh' with arguments '"//.vs-debugger/GetVsDbg.sh" -v vs2022 -u -l "//.vs-debugger/vs2022" -d vscode -a "/remote_debugger"'
 1> [DebugAdapter] --> C (initialize-1): {"type":"request","command":"initialize","arguments":{"pathFormat":"path","clientID":"visualstudio","clientName":"Visual Studio","adapterID":"coreclr","locale":"en-US","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsRunInTerminalRequest":true,"supportsMemoryReferences":true,"supportsProgressReporting":true,"SupportsMessageBox":true,"supportsHandshakeRequest":true,"supportsVsAdditionalBreakpointBinds":true,"supportsHitCountsChange":true,"supportsVsCustomMessages":true,"supportsVariableEnumerators":true},"seq":1}
 1> WARNING: Request 'initialize-1' has not received a response within 1000 ms!
 1> Debug adapter non-protocol standard output: Info: Last installed version of vsdbg is '17.8.11212.2'
Info: VsDbg is up-to-date
Info: Using vsdbg version '17.8.11212.2'
Using arguments
    Version                    : 'vs2022'
    Location                   : '//.vs-debugger/vs2022'
    SkipDownloads              : 'true'
    LaunchVsDbgAfter           : 'true'
        VsDbgMode              : 'vscode'
    RemoveExistingOnUpgrade    : 'true'
Info: Skipping downloads
Info: Launching vsdbg
 1> [DebugAdapter] <--   R (initialize-1) [1126 ms]: {"type":"response","request_seq":1,"success":true,"command":"initialize","body":{"supportsConfigurationDoneRequest":true,"supportsFunctionBreakpoints":true,"supportsConditionalBreakpoints":true,"supportsHitConditionalBreakpoints":true,"supportsEvaluateForHovers":true,"exceptionBreakpointFilters":[{"filter":"all","label":"All Exceptions","description":"Break when an exception is thrown. ","default":false,"supportsCondition":true},{"filter":"user-unhandled","label":"User-Unhandled Exceptions","description":"Break when an exception is caught in non-user code (system code) after having passed through user code. ","default":true,"supportsCondition":true}],"supportsSetVariable":true,"supportsGotoTargetsRequest":true,"supportsModulesRequest":true,"additionalModuleColumns":[{"attributeName":"vsLoadAddress","label":"Load Address","type":"string"},{"attributeName":"vsPreferredLoadAddress","label":"Preferred Load Address","type":"string"},{"attributeName":"vsModuleSize","label":"Module Size","type":"number"},{"attributeName":"vsLoadOrder","label":"Order","type":"number"},{"attributeName":"vsTimestampUTC","label":"Timestamp","type":"unixTimestampUTC"},{"attributeName":"vsIs64Bit","label":"64-bit","type":"boolean"},{"attributeName":"vsAppDomain","label":"AppDomain","type":"string"},{"attributeName":"vsAppDomainId","label":"AppDomainId","type":"number"}],"supportedChecksumAlgorithms":["MD5","SHA1","SHA256"],"supportsExceptionOptions":true,"supportsValueFormattingOptions":true,"supportsExceptionInfoRequest":true,"supportTerminateDebuggee":true,"supportsLogPoints":false,"supportsSetExpression":true,"supportsReadMemoryRequest":true,"supportsCancelRequest":true,"supportsClipboardContext":true,"supportsExceptionFilterOptions":true,"supportsAttachCompleteEvent":true,"supportsExceptionConditions":true,"supportsLoadSymbolsRequest":true,"supportsModuleSymbolSearchLog":true,"supportsDebuggerProperties":true,"supportsSetSymbolOptions":true,"supportsAuthenticatedSymbolServers":true,"supportsHitBreakpointIds":true,"supportsVsIndividualBreakpointOperations":true,"supportsVsBreakpointLanguage":true,"supportsSetHitCount":true,"supportsVsCustomMessages":true,"supportsEvaluationOptions":true,"supportsExceptionStackTrace":true,"memoryReferencesAreAddresses":true,"supportsObjectFavorites":true,"supportsObjectId":true,"supportsVariableEnumerators":true},"seq":1}
 1> [DebugAdapter] --> C (attach-2): {"type":"request","command":"attach","arguments":{"name":".NET Core Attach","type":"coreclr","request":"attach","processId":"1"},"seq":2}
 1> [DebugAdapter] <--   C (handshake-2): {"type":"request","command":"handshake","arguments":{"value":"OknnmzX3b7eRQiYegw9wNe53cHeYKBC2BhokLaA0gPU="},"seq":2}
 1> [DebugAdapter] --> R (handshake-2): {"type":"response","request_seq":2,"success":true,"command":"handshake","body":{"signature":"362EbdO4MKa5pyffa22d35rjJc1lsFEkzzLcVpYZxMHWQ8="},"seq":3}
 1> [DebugAdapter] <--   E (output): {"type":"event","event":"output","body":{"category":"console","output":"-------------------------------------------------------------------\nYou may only use the Microsoft .NET Core Debugger (vsdbg) with\nVisual Studio Code, Visual Studio or Visual Studio for Mac software\nto help you develop and test your applications.\n-------------------------------------------------------------------\n","severity":"ok"},"seq":3}
 1> [DebugAdapter] <--   R (attach-2) [50 ms]: {"type":"response","request_seq":2,"success":true,"command":"attach","seq":4}
 1> [DebugAdapter] <--   E (initialized): {"type":"event","event":"initialized","body":{},"seq":5}
 1> [DebugAdapter] --> C (setDebuggerProperty-4): {"type":"request","command":"setDebuggerProperty","arguments":{"AllowOutOfProcessSymbols":1},"seq":4}
 1> [DebugAdapter] --> C (setDebuggerProperty-5): {"type":"request","command":"setDebuggerProperty","arguments":{"DisableJITOptimization":0},"seq":5}
 1> [DebugAdapter] --> C (setDebuggerProperty-6): {"type":"request","command":"setDebuggerProperty","arguments":{"EnableAutomaticDecompilation":1},"seq":6}
 1> [DebugAdapter] --> C (setDebuggerProperty-7): {"type":"request","command":"setDebuggerProperty","arguments":{"EnableFastEvaluate":1},"seq":7}
 1> [DebugAdapter] --> C (setDebuggerProperty-8): {"type":"request","command":"setDebuggerProperty","arguments":{"InterpreterOptions":1},"seq":8}
 1> [DebugAdapter] --> C (setDebuggerProperty-9): {"type":"request","command":"setDebuggerProperty","arguments":{"JustMyCodeStepping":0},"seq":9}
 1> [DebugAdapter] --> C (setDebuggerProperty-10): {"type":"request","command":"setDebuggerProperty","arguments":{"Native.LoadExports":0},"seq":10}
 1> [DebugAdapter] --> C (setDebuggerProperty-11): {"type":"request","command":"setDebuggerProperty","arguments":{"NatvisComplexityLimit":100},"seq":11}
 1> [DebugAdapter] --> C (setDebuggerProperty-12): {"type":"request","command":"setDebuggerProperty","arguments":{"NatvisRecursionLimit":100},"seq":12}
 1> [DebugAdapter] --> C (setDebuggerProperty-13): {"type":"request","command":"setDebuggerProperty","arguments":{"StopOnExceptionCrossingManagedBoundary":0},"seq":13}
 1> [DebugAdapter] --> C (setDebuggerProperty-14): {"type":"request","command":"setDebuggerProperty","arguments":{"WarnIfNoUserCodeOnLaunch":0},"seq":14}
 1> [DebugAdapter] --> C (setDebuggerProperty-15): {"type":"request","command":"setDebuggerProperty","arguments":{"EnableStepFiltering":true},"seq":15}
 1> [DebugAdapter] --> C (setSymbolOptions-16): {"type":"request","command":"setSymbolOptions","arguments":{"symbolOptions":{"moduleFilter":{"mode":"loadAllButExcluded","excludedModules":[""]}}},"seq":16}
 1> [DebugAdapter] <--   R (setDebuggerProperty-4) [15 ms]: {"type":"response","request_seq":4,"success":true,"command":"setDebuggerProperty","body":{},"seq":6}
 1> [DebugAdapter] <--   R (setDebuggerProperty-5) [14 ms]: {"type":"response","request_seq":5,"success":true,"command":"setDebuggerProperty","body":{},"seq":7}
 1> [DebugAdapter] <--   R (setDebuggerProperty-6) [13 ms]: {"type":"response","request_seq":6,"success":true,"command":"setDebuggerProperty","body":{},"seq":8}
 1> [DebugAdapter] <--   R (setDebuggerProperty-7) [13 ms]: {"type":"response","request_seq":7,"success":true,"command":"setDebuggerProperty","body":{},"seq":9}
 1> [DebugAdapter] <--   R (setDebuggerProperty-8) [13 ms]: {"type":"response","request_seq":8,"success":true,"command":"setDebuggerProperty","body":{},"seq":10}
 1> [DebugAdapter] --> C (setFunctionBreakpoints-17): {"type":"request","command":"setFunctionBreakpoints","arguments":{"breakpoints":[]},"seq":17}
 1> [DebugAdapter] --> C (setBreakpoints-18): {"type":"request","command":"setBreakpoints","arguments":{"source":{"path":"c:\\Users\\rvso\\source\\repos\\star-modernisering\\apigateway\\Source\\Star.ApiGateway.Yarp\\Authentication\\StarCertificateAuthenticationEvents.cs","sources":[],"checksums":[{"algorithm":"MD5","checksum":"bfa90f0236f19b8680a60bd7f8c36566"},{"algorithm":"MD5","checksum":"599c20d977114d9d51993e1aa0645def"},{"algorithm":"SHA1","checksum":"67bfd417f336796c517c8c9900992dc0ca543478"},{"algorithm":"SHA1","checksum":"c638479403dcc8be7c2060a3f5925e57119b49bc"},{"algorithm":"SHA256","checksum":"2ba1635d4d1a85b1fc137454388239bdc2222a2850b764f100daaf0d10dfa0cd"},{"algorithm":"SHA256","checksum":"3b99ddab5afdf9ba22aae636a21bb714867cd836ec16dc2a8fbb1f40d2a68eca"}]},"breakpoints":[{"line":21,"column":9,"vsLanguageId":"{3f5162f8-07c6-11d3-9053-00c04fa302a1}"}],"lines":[21]},"seq":18}
 1> [DebugAdapter] <--   R (setDebuggerProperty-9) [53 ms]: {"type":"response","request_seq":9,"success":true,"command":"setDebuggerProperty","body":{},"seq":11}
 1> [DebugAdapter] <--   R (setDebuggerProperty-10) [53 ms]: {"type":"response","request_seq":10,"success":true,"command":"setDebuggerProperty","body":{},"seq":12}
 1> [DebugAdapter] <--   R (setDebuggerProperty-11) [53 ms]: {"type":"response","request_seq":11,"success":true,"command":"setDebuggerProperty","body":{},"seq":13}
 1> [DebugAdapter] <--   R (setDebuggerProperty-12) [53 ms]: {"type":"response","request_seq":12,"success":true,"command":"setDebuggerProperty","body":{},"seq":14}
 1> [DebugAdapter] <--   R (setDebuggerProperty-13) [53 ms]: {"type":"response","request_seq":13,"success":true,"command":"setDebuggerProperty","body":{},"seq":15}
 1> [DebugAdapter] <--   R (setDebuggerProperty-14) [53 ms]: {"type":"response","request_seq":14,"success":true,"command":"setDebuggerProperty","body":{},"seq":16}
 1> [DebugAdapter] <--   R (setDebuggerProperty-15) [54 ms]: {"type":"response","request_seq":15,"success":true,"command":"setDebuggerProperty","body":{},"seq":17}
 1> [DebugAdapter] <--   R (setSymbolOptions-16) [59 ms]: {"type":"response","request_seq":16,"success":true,"command":"setSymbolOptions","seq":18}
 1> [DebugAdapter] <--   R (setFunctionBreakpoints-17) [46 ms]: {"type":"response","request_seq":17,"success":true,"command":"setFunctionBreakpoints","body":{"breakpoints":[]},"seq":19}
 1> [DebugAdapter] <--   R (setBreakpoints-18) [44 ms]: {"type":"response","request_seq":18,"success":true,"command":"setBreakpoints","body":{"breakpoints":[{"id":1,"verified":false,"message":"The breakpoint is pending and will be resolved when debugging starts."}]},"seq":20}
 1> [DebugAdapter] --> C (setExceptionBreakpoints-19): {"type":"request","command":"setExceptionBreakpoints","arguments":{"filters":[],"exceptionOptions":[{"breakMode":"userUnhandled","path":[{"names":["CLR"]}]},{"breakMode":"unhandled","path":[{"names":["CLR"]},{"names":["System.AppDomainUnloadedException","System.Threading.ThreadAbortException"]}]},{"breakMode":"always","path":[{"names":["CLR"]},{"names":["System.Windows.Markup.XamlParseException","System.Reflection.MissingMetadataException","System.Reflection.MissingRuntimeArtifactException","System.NullReferenceException","Microsoft.UI.Xaml.Markup.XamlParseException"]}]},{"breakMode":"unhandled","path":[{"names":["MDA"]}]},{"breakMode":"always","path":[{"names":["MDA"]},{"names":["CallbackOnCollectedDelegate","ContextSwitchDeadlock","DateTimeInvalidLocalFormat","DisconnectedContext","FatalExecutionEngineError","InvalidFunctionPointerInDelegate","InvalidMemberDeclaration","InvalidVariant","LoaderLock","NonComVisibleBaseClass","PInvokeStackImbalance","RaceOnRCWCleanup","Reentrancy"]}]}]},"seq":19}
 1> [DebugAdapter] <--   R (setExceptionBreakpoints-19) [13 ms]: {"type":"response","request_seq":19,"success":true,"command":"setExceptionBreakpoints","seq":21}
 1> [DebugAdapter] --> C (configurationDone-20): {"type":"request","command":"configurationDone","arguments":{},"seq":20}
 1> [DebugAdapter] <--   E (output): {"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/ProcessCreate","data":{"VS.Diagnostics.Debugger.vsdbg.Distribution.Version":"3.18.5","VS.Diagnostics.Debugger.vsdbg.TargetArchitecture":"AMD64","VS.Diagnostics.Debugger.vsdbg.Distribution.Name":"75f5c57e","VS.Diagnostics.Debugger.vsdbg.OSFamily":"Linux","VS.Diagnostics.Debugger.vsdbg.Version":"17.8.11212.2 commit:8245b0ea19bf9efd5e14a30aa11f59ead3ba97b1"}},"seq":22}
 1> [DebugAdapter] <--   E (telemetryDetails): {"type":"event","event":"telemetryDetails","body":{"telemetryEventName":"vs/diagnostics/debugger/process/context","telemetryProperties":{"VS.Diagnostics.Debugger.AD7Process.Architecture":"AMD64"}},"seq":23}
 1> [DebugAdapter] <--   E (process): {"type":"event","event":"process","body":{"name":"/usr/share/dotnet/dotnet","systemProcessId":1,"startMethod":"attach","pointerSize":64},"seq":24}
 1> [DebugAdapter] <--   E (output): {"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/Attach","data":{"VS.Diagnostics.Debugger.vsdbg.Attach.Duration":390,"VS.Diagnostics.Debugger.vsdbg.SourceFileMappings":0,"VS.Diagnostics.Debugger.vsdbg.VisualizerFileUsed":false,"VS.Diagnostics.Debugger.vsdbg.TargetType":"Live","VS.Diagnostics.Debugger.vsdbg.AdapterId":"coreclr","VS.Diagnostics.Debugger.vsdbg.Distribution.Version":"3.18.5","VS.Diagnostics.Debugger.vsdbg.Distribution.Name":"75f5c57e","VS.Diagnostics.Debugger.vsdbg.OSFamily":"Linux","VS.Diagnostics.Debugger.vsdbg.Version":"17.8.11212.2 commit:8245b0ea19bf9efd5e14a30aa11f59ead3ba97b1"}},"seq":25}
 1> [DebugAdapter] <--   R (configurationDone-20) [283 ms]: {"type":"response","request_seq":20,"success":true,"command":"configurationDone","seq":26}
 1> [DebugAdapter] <--   E (breakpoint): {"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":1,"verified":false,"message":"No symbols have been loaded for this document."}},"seq":27}
 1> [DebugAdapter] <--   E (module): {"type":"event","event":"module","body":{"reason":"new","module":{"id":1000,"name":"System.Private.CoreLib.dll","path":"/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.1/System.Private.CoreLib.dll","isOptimized":true,"isUserCode":false,"version":"8.00.123.58001","symbolStatus":"Cannot find or open the PDB file.","vsLoadAddress":"140705232781312","vsPreferredLoadAddress":"140705232781312","vsModuleSize":13094912,"vsLoadOrder":0,"vsIs64Bit":true,"vsAppDomain":"clrhost","vsAppDomainId":1},"vsMessage":"Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.1/System.Private.CoreLib.dll'. Cannot find or open the PDB file."},"seq":28}
 1> [DebugAdapter] <--   E (module): {"type":"event","event":"module","body":{"reason":"new","module":{"id":1001,"name":"Star.ApiGateway.Yarp.dll","path":"/app/Star.ApiGateway.Yarp.dll","isOptimized":true,"isUserCode":false,"version":"1.00.0.0","symbolStatus":"Symbols loaded.","symbolFilePath":"/app/Star.ApiGateway.Yarp.pdb","vsLoadAddress":"140707371057152","vsPreferredLoadAddress":"140707371057152","vsModuleSize":59392,"vsLoadOrder":1,"vsIs64Bit":true,"vsAppDomain":"clrhost","vsAppDomainId":1},"vsMessage":"Loaded '/app/Star.ApiGateway.Yarp.dll'. Symbols loaded."},"seq":29}
 1> Debug adapter process exited.
 1> Debug adapter non-protocol standard output: Unknown debugger event type: 0x258

 1> ERROR: The debug adapter exited unexpectedly.
 1> WARNING: Cannot send message when the protocol dispatcher is not running.

**Comment by gregg-miskelly** [comment]
Thanks! I believe I see what is going wrong.

I will see if I can get you a better work around, but for an immediate one, I believe this is caused by a new feature in .NET 8 + recent versions of the .NET debugger where the debugger can deoptimize methods on the fly. I think you could work around by either avoiding debugging optimized code. You could do that with either:
1. Re-enable JustMyCode and make sure you are using debug builds of whatever you want to debug
-or-
2. Ensure that everything is deoptimized up front by --
   * Leave Just My Code disabled as you have it
   * Enable the option to Suppress JIT optimizations on module load
   * Configuring the environment of the target process to launch with then environment variable `"COMPlus_ReadyToRun": "0"` set

More complete instructions for 'option 2' in VS Code can be found [in the wiki](https://github.com/dotnet/vscode-csharp/wiki/Debugging-into-the-.NET-Framework-itself).

**Comment by gregg-miskelly** [comment]
The underlying cause: https://github.com/dotnet/runtime/issues/97461

**Comment by NC-RVSO** [comment]
Could not make option 2 work, but 1. worked like a charm, and as all the code is my code I did not need to Re-enable JustMyCode (but I see why you told me to as it would remove potential crashes).
Keep me posted when a real fix is implemented :)

**Comment by gregg-miskelly** [comment]
This issue is now fixed. In full Visual Studio (and any other remote debugging scenario using https://aka.ms/getvsdbgsh or https://aka.ms/getvsdbgps1) this is fixes as soon as the debugger is next automatically updated. In VS Code C# extension scenarios, this will be fixed with the next release of the C# extension, which I believe is 2.18.0.

**Comment by NC-RVSO** [comment]
Amazing! Thank you so much 🥇
