### ISSUE TITLE
A serous error for the file show. Can not show the error file.

### ISSUE THREAD

**Issue by Hoper-Q** [dotnet/vscode-csharp#6833]
### The child won`t make error tip on vscode when I change parent.
![image](https://github.com/microsoft/vscode/assets/52480108/ce0085bd-0384-4166-a6e2-5ff65f6c27e4)
![image](https://github.com/microsoft/vscode/assets/52480108/8043b9ad-e70c-44d1-8663-e4ce1a9126ac)
![image](https://github.com/microsoft/vscode/assets/52480108/4e1c07bf-4a13-4fd9-828c-edc288ae68d5)
![image](https://github.com/microsoft/vscode/assets/52480108/902dc084-9474-47d1-989c-be7f596dd090)

### But when I Choose the file, it will show the error.
![image](https://github.com/microsoft/vscode/assets/52480108/6946bd43-9a63-43d4-8192-eb3b723ed8e7)
![image](https://github.com/microsoft/vscode/assets/52480108/cddcd5ca-dc7a-480e-ab31-1d6f78009625)

**I want to know how to fix it. Make it show the error at the first time!**

There are my C#.
![image](https://github.com/dotnet/vscode-csharp/assets/52480108/5c91686f-ce87-40ea-bba6-94e08b80d0d0)
![image](https://github.com/dotnet/vscode-csharp/assets/52480108/ccddca35-b93b-4b59-b27a-a53c6312b54c)
![image](https://github.com/dotnet/vscode-csharp/assets/52480108/dd186af3-ef4e-48a0-bf8f-cd75bed3d026)

**Comment by dibarbet** [comment]
@Hoper-Q By default diagnostics are only reported for open files, since Child.cs is not open when you change the interface, the diagnostic is not reported.

You can change the behavior to report diagnostics in closed files by setting `dotnet.backgroundAnalysis.compilerDiagnosticsScope` to `fullSolution`.  But note it will have a performance impact on large solutions.
<img width="500" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/5749229/6ccbf0f0-5fcc-4de9-a1ec-a607b8f53680">

**Comment by Hoper-Q** [comment]
> @Hoper-Q By default diagnostics are only reported for open files, since Child.cs is not open when you change the interface, the diagnostic is not reported.
> 
> You can change the behavior to report diagnostics in closed files by setting `dotnet.backgroundAnalysis.compilerDiagnosticsScope` to `fullSolution`. But note it will have a performance impact on large solutions. <img alt="image" width="500" src="https://private-user-images.githubusercontent.com/5749229/300951544-6ccbf0f0-5fcc-4de9-a1ec-a607b8f53680.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MzU0NDEsIm5iZiI6MTcxMTkzNTE0MSwicGF0aCI6Ii81NzQ5MjI5LzMwMDk1MTU0NC02Y2NiZjBmMC01ZmNjLTRkZTktYTFlYy1hNjA3YjhmNTM2ODAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDFUMDEzMjIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWY0Zjg0ZDBmYTQ1MmY3OGVhZjFkYjRkODE2NmIxOGQ5ODZiODlhNjhhMDQyZTQzZDQ5ZjA4MDdmZDM4NDg3NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jZ6FN-ORXnczT78KboMKAa5RHkSekr_JBZzlNpzjaSI">

It doesn't work. I change this two to full solution.
