### ISSUE TITLE
C# debugger: run to cursor trips on breakpoints

### ISSUE THREAD

**Issue by vadi2** [dotnet/vscode-csharp#6843]
Type: <b>Bug</b>

Run to cursor isn't skipping breakpoints in the way as it should be.

Extension version: 2.15.30
VS Code version: Code 1.85.2 (Universal) (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:32.531Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 6, 6|
|Memory (System)|32.00GB (0.66GB free)|
|Process Argv|--crash-reporter-id cf673bf1-bab8-4420-845a-3dfaff0b46a4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
0bi6i642:30951795
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019b:30953937
3ef8e399:30949928

```

</details>

**Comment by gregg-miskelly** [comment]
This is "by design" from the C# debugger's perspective. Full Visual Studio has this feature in the [Force Run to Cursor command](https://devblogs.microsoft.com/visualstudio/debug-with-force-run-to-cursor/). But Visual Studio Code doesn't offer a similar feature.

I opened the following feature request on your behalf for this: https://github.com/microsoft/vscode/issues/204007
