### ISSUE TITLE
Mylog

### ISSUE THREAD

**Issue by together320** [dotnet/vscode-csharp#6850]
Type: <b>Bug</b>

Using dotnet configured on PATH
Dotnet path: C:\Program Files\dotnet\dotnet.exe
Activating C# standalone...
Starting server at c:\Users\SG\.vscode\extensions\ms-dotnettools.csharp-2.16.24-win32-x64\.roslyn\Microsoft.CodeAnalysis.LanguageServer.exe
Server arguments --logLevel Trace --telemetryLevel all --extensionLogDirectory c:\Users\SG\AppData\Roaming\Code\logs\20240203T181531\window1\exthost\ms-dotnettools.csharp
waiting for named pipe information from server...
[stdout] trce: Program[0]
      .NET Runtime Version: .NET 7.0.13
[stdout] dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\SG\.vscode\extensions\ms-dotnettools.csharp-2.16.24-win32-x64\.roslyn\Microsoft.CodeAnalysis.AnalyzerUtilities.dll added to workspace.
[stdout] dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\SG\.vscode\extensions\ms-dotnettools.csharp-2.16.24-win32-x64\.roslyn\Microsoft.CodeAnalysis.CSharp.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\SG\.vscode\extensions\ms-dotnettools.csharp-2.16.24-win32-x64\.roslyn\Microsoft.CodeAnalysis.CSharp.Features.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\SG\.vscode\extensions\ms-dotnettools.csharp-2.16.24-win32-x64\.roslyn\Microsoft.CodeAnalysis.CSharp.Workspaces.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\SG\.vscode\extensions\ms-dotnettools.csharp-2.16.24-win32-x64\.roslyn\Microsoft.CodeAnalysis.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\SG\.vscode\extensions\ms-dotnettools.csharp-2.16.24-win32-x64\.roslyn\Microsoft.CodeAnalysis.Elfie.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\SG\.vscode\extensions\ms-dotnettools.csharp-2.16.24-win32-x64\.roslyn\Microsoft.CodeAnalysis.ExternalAccess.AspNetCore.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\SG\.vscode\extensions\ms-dotnettools.csharp-2.16.24-win32-x64\.roslyn\Microsoft.CodeAnalysis.Features.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\SG\.vscode\extensions\ms-dotnettools.csharp-2.16.24-win32-x64\.roslyn\Microsoft.CodeAnalysis.Razor.Compiler.CSharp.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\SG\.vscode\extensions\ms-dotnettools.csharp-2.16.24-win32-x64\.roslyn\Microsoft.CodeAnalysis.Razor.Compiler.Language.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\SG\.vscode\extensions\ms-dotnettools.csharp-2.16.24-win32-x64\.roslyn\Microsoft.CodeAnalysis.Razor.Compiler.Mvc.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\SG\.vscode\extensions\ms-dotnettools.csharp-2.16.24-win32-x64\.roslyn\Microsoft.CodeAnalysis.Razor.Compiler.Mvc.Version1_X.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\SG\.vscode\extensions\ms-dotnettools.csharp-2.16.24-win32-x64\.roslyn\Microsoft.CodeAnalysis.Razor.Compiler.Mvc.Version2_X.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\SG\.vscode\extensions\ms-dotnettools.csharp-2.16.24-win32-x64\.roslyn\Microsoft.CodeAnalysis.Remote.Workspaces.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\SG\.vscode\extensions\ms-dotnettools.csharp-2.16.24-win32-x64\.roslyn\Microsoft.CodeAnalysis.Scripting.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\SG\.vscode\extensions\ms-dotnettools.csharp-2.16.24-win32-x64\.roslyn\Microsoft.CodeAnalysis.Workspaces.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\SG\.vscode\extensions\ms-dotnettools.csharp-2.16.24-win32-x64\.roslyn\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\SG\.vscode\extensions\ms-dotnettools.csharp-2.16.24-win32-x64\.roslyn\Microsoft.CodeAnalysis.Workspaces.MSBuild.dll added to workspace.
[stdout] {"pipeName":"\\\\.\\pipe\\d7214ceb"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 11:34:04 PM] [Program] Language server initialized
[LanguageServerHost] [02:34:04.667][Start]initialize
[LanguageServerHost] [02:34:04.813][End]initialize
[LanguageServerHost] [02:34:04.819][Start]initialized
[LanguageServerHost] [02:34:04.932][End]initialized
[LanguageServerHost] [02:34:04.935][Start]solution/open
[Info  - 11:34:04 PM] [LanguageServerProjectSystem] Loading e:\my_works\cvc_project\CVC_Local\CVC.sln...
[LanguageServerHost] [02:34:04.963][Start]workspace/diagnostic
[LanguageServerHost] PublicWorkspacePullDiagnosticsHandler(category: , source: ) started getting diagnostics
[LanguageServerHost] previousResults.Length=0
[LanguageServerHost] Processing 0 documents
[BuildHost PID 68680] Message from Process: info: Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.Program[0]
[BuildHost PID 68680] Message from Process:       BuildHost Runtime Version: .NET 7.0.13
[BuildHost PID 68680] Message from Process: info: Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.BuildHost[0]
[BuildHost PID 68680] Message from Process:       Registered MSBuild instance at C:\Program Files\dotnet\sdk\6.0.418
[Microsoft.CodeAnalysis.MSBuild.BuildHostProcessManager] Choosing a build host of type NetFramework for e:\my_works\cvc_project\CVC_Local\CVC.BusinessServices\CVC.BusinessServices.csproj.
[Microsoft.CodeAnalysis.MSBuild.BuildHostProcessManager] Choosing a build host of type NetFramework for e:\my_works\cvc_project\CVC_Local\CVC.PLC\CVC.PLC.csproj.
[Microsoft.CodeAnalysis.MSBuild.BuildHostProcessManager] Choosing a build host of type NetFramework for e:\my_works\cvc_project\CVC_Local\CVC.MDB\CVC.MDB.csproj.
[Microsoft.CodeAnalysis.MSBuild.BuildHostProcessManager] Choosing a build host of type NetFramework for e:\my_works\cvc_project\CVC_Local\CVC.Data\CVC.Data.csproj.
[Microsoft.CodeAnalysis.MSBuild.BuildHostProcessManager] Choosing a build host of type NetFramework for e:\my_works\cvc_project\CVC_Local\CVC.License\CVC.License.csproj.
[Microsoft.CodeAnalysis.MSBuild.BuildHostProcessManager] Choosing a build host of type NetFramework for e:\my_works\cvc_project\CVC_Local\CVC.SiemensS7Net\CVC.SiemensS7Net.csproj.
[Microsoft.CodeAnalysis.MSBuild.BuildHostProcessManager] Choosing a build host of type NetFramework for e:\my_works\cvc_project\CVC_Local\CVC.OpcUaClient\CVC.OpcUaClient.csproj.
[Microsoft.CodeAnalysis.MSBuild.BuildHostProcessManager] Choosing a build host of type NetFramework for e:\my_works\cvc_project\CVC_Local\CVC.ViewModels\CVC.ViewModels.csproj.
[Microsoft.CodeAnalysis.MSBuild.BuildHostProcessManager] Choosing a build host of type NetFramework for e:\my_works\cvc_project\CVC_Local\CVC.AlarmWindowsService\CVC.AlarmWindowsService.csproj.
[Microsoft.CodeAnalysis.MSBuild.BuildHostProcessManager] Choosing a build host of type NetFramework for e:\my_works\cvc_project\CVC_Local\CVC\CVC.Web.csproj.
[BuildHost PID 82216] Message from Process: info: Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.Program[0]
[BuildHost PID 82216] Message from Process:       BuildHost Runtime Version: .NET Framework 4.8.4042.0
[BuildHost PID 82216] Message from Process: info: Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.BuildHost[0]
[BuildHost PID 82216] Message from Process:       Registered MSBuild instance at C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin
[BuildHost PID 82216] Message from Process: info: Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.BuildHost[0]
[BuildHost PID 82216] Message from Process:       Loading e:\my_works\cvc_project\CVC_Local\CVC.ViewModels\CVC.ViewModels.csproj
[BuildHost PID 82216] Message from Process: info: Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.BuildHost[0]
[BuildHost PID 82216] Message from Process:       Loading e:\my_works\cvc_project\CVC_Local\CVC.PLC\CVC.PLC.csproj
[BuildHost PID 82216] Message from Process: info: Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.BuildHost[0]
[BuildHost PID 82216] Message from Process:       Loading e:\my_works\cvc_project\CVC_Local\CVC.SiemensS7Net\CVC.SiemensS7Net.csproj
[BuildHost PID 82216] Message from Process: info: Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.BuildHost[0]
[BuildHost PID 82216] Message from Process:       Loading e:\my_works\cvc_project\CVC_Local\CVC.Data\CVC.Data.csproj
[BuildHost PID 82216] Message from Process: info: Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.BuildHost[0]
[BuildHost PID 82216] Message from Process:       Loading e:\my_works\cvc_project\CVC_Local\CVC.MDB\CVC.MDB.csproj
[BuildHost PID 82216] Message from Process: info: Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.BuildHost[0]
[BuildHost PID 82216] Message from Process:       Loading e:\my_works\cvc_project\CVC_Local\CVC.OpcUaClient\CVC.OpcUaClient.csproj
[BuildHost PID 82216] Message from Process: info: Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.BuildHost[0]
[BuildHost PID 82216] Message from Process:       Loading e:\my_works\cvc_project\CVC_Local\CVC.AlarmWindowsService\CVC.AlarmWindowsService.csproj
[BuildHost PID 82216] Message from Process: info: Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.BuildHost[0]
[BuildHost PID 82216] Message from Process:       Loading e:\my_works\cvc_project\CVC_Local\CVC.License\CVC.License.csproj
[BuildHost PID 82216] Message from Process: info: Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.BuildHost[0]
[BuildHost PID 82216] Message from Process:       Loading e:\my_works\cvc_project\CVC_Local\CVC.BusinessServices\CVC.BusinessServices.csproj
[BuildHost PID 82216] Message from Process: info: Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.BuildHost[0]
[BuildHost PID 82216] Message from Process:       Loading e:\my_works\cvc_project\CVC_Local\CVC\CVC.Web.csproj
[LanguageServerHost] Closing workspace/diagnostics request
[LanguageServerHost] Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.Public.PublicWorkspacePullDiagnosticsHandler finished getting diagnostics
[LanguageServerHost] [02:34:12.151][End]workspace/diagnostic
[LanguageServerProjectSystem] Project e:\my_works\cvc_project\CVC_Local\CVC.ViewModels\CVC.ViewModels.csproj now has 25 source file(s).
[LanguageServerProjectSystem] Project e:\my_works\cvc_project\CVC_Local\CVC.MDB\CVC.MDB.csproj now has 4 source file(s).
[LanguageServerProjectSystem] Project e:\my_works\cvc_project\CVC_Local\CVC.ViewModels\CVC.ViewModels.csproj now has 12 reference(s).
[LanguageServerProjectSystem] Project e:\my_works\cvc_project\CVC_Local\CVC.MDB\CVC.MDB.csproj now has 12 reference(s).
[Warn  - 11:34:12 PM] [LanguageServerProjectSystem] Project e:\my_works\cvc_project\CVC_Local\CVC.MDB\CVC.MDB.csproj has unresolved dependencies
[Warn  - 11:34:12 PM] [LanguageServerProjectSystem] Project e:\my_works\cvc_project\CVC_Local\CVC.ViewModels\CVC.ViewModels.csproj has unresolved dependencies
[LanguageServerProjectSystem] Project e:\my_works\cvc_project\CVC_Local\CVC.Data\CVC.Data.csproj now has 120 source file(s).
[LanguageServerProjectSystem] Project e:\my_works\cvc_project\CVC_Local\CVC.Data\CVC.Data.csproj now has 13 reference(s).
[Warn  - 11:34:12 PM] [LanguageServerProjectSystem] Project e:\my_works\cvc_project\CVC_Local\CVC.Data\CVC.Data.csproj has unresolved dependencies
[Info  - 11:34:12 PM] [LanguageServerProjectSystem] Successfully completed load of e:\my_works\cvc_project\CVC_Local\CVC.ViewModels\CVC.ViewModels.csproj
[Info  - 11:34:12 PM] [LanguageServerProjectSystem] Successfully completed load of e:\my_works\cvc_project\CVC_Local\CVC.MDB\CVC.MDB.csproj
[Info  - 11:34:12 PM] [LanguageServerProjectSystem] Successfully completed load of e:\my_works\cvc_project\CVC_Local\CVC.Data\CVC.Data.csproj
[LanguageServerProjectSystem] Project e:\my_works\cvc_project\CVC_Local\CVC.BusinessServices\CVC.BusinessServices.csproj now has 17 source file(s).
[LanguageServerProjectSystem] Project e:\my_works\cvc_project\CVC_Local\CVC.BusinessServices\CVC.BusinessServices.csproj now has 31 reference(s).
[Warn  - 11:34:12 PM] [LanguageServerProjectSystem] Project e:\my_works\cvc_project\CVC_Local\CVC.BusinessServices\CVC.BusinessServices.csproj has unresolved dependencies
[Info  - 11:34:12 PM] [LanguageServerProjectSystem] Successfully completed load of e:\my_works\cvc_project\CVC_Local\CVC.BusinessServices\CVC.BusinessServices.csproj
[LanguageServerProjectSystem] Project e:\my_works\cvc_project\CVC_Local\CVC.License\CVC.License.csproj now has 51 source file(s).
[LanguageServerProjectSystem] Project e:\my_works\cvc_project\CVC_Local\CVC.License\CVC.License.csproj now has 34 reference(s).
[Warn  - 11:34:13 PM] [LanguageServerProjectSystem] Project e:\my_works\cvc_project\CVC_Local\CVC.License\CVC.License.csproj has unresolved dependencies
[Info  - 11:34:13 PM] [LanguageServerProjectSystem] Successfully completed load of e:\my_works\cvc_project\CVC_Local\CVC.License\CVC.License.csproj
[LanguageServerProjectSystem] Project e:\my_works\cvc_project\CVC_Local\CVC.AlarmWindowsService\CVC.AlarmWindowsService.csproj now has 8 source file(s).
[LanguageServerProjectSystem] Project e:\my_works\cvc_project\CVC_Local\CVC.AlarmWindowsService\CVC.AlarmWindowsService.csproj now has 20 reference(s).
[Warn  - 11:34:13 PM] [LanguageServerProjectSystem] Project e:\my_works\cvc_project\CVC_Local\CVC.AlarmWindowsService\CVC.AlarmWindowsService.csproj has unresolved dependencies
[Info  - 11:34:13 PM] [LanguageServerProjectSystem] Successfully completed load of e:\my_works\cvc_project\CVC_Local\CVC.AlarmWindowsService\CVC.AlarmWindowsService.csproj
[LanguageServerProjectSystem] Project e:\my_works\cvc_project\CVC_Local\CVC.PLC\CVC.PLC.csproj now has 7 source file(s).
[LanguageServerProjectSystem] Project e:\my_works\cvc_project\CVC_Local\CVC.PLC\CVC.PLC.csproj now has 11 reference(s).
[Warn  - 11:34:13 PM] [LanguageServerProjectSystem] Project e:\my_works\cvc_project\CVC_Local\CVC.PLC\CVC.PLC.csproj has unresolved dependencies
[Info  - 11:34:13 PM] [LanguageServerProjectSystem] Successfully completed load of e:\my_works\cvc_project\CVC_Local\CVC.PLC\CVC.PLC.csproj
[LanguageServerProjectSystem] Project e:\my_works\cvc_project\CVC_Local\CVC.SiemensS7Net\CVC.SiemensS7Net.csproj now has 3 source file(s).
[LanguageServerProjectSystem] Project e:\my_works\cvc_project\CVC_Local\CVC.SiemensS7Net\CVC.SiemensS7Net.csproj now has 13 reference(s).
[Warn  - 11:34:13 PM] [LanguageServerProjectSystem] Project e:\my_works\cvc_project\CVC_Local\CVC.SiemensS7Net\CVC.SiemensS7Net.csproj has unresolved dependencies
[Info  - 11:34:13 PM] [LanguageServerProjectSystem] Successfully completed load of e:\my_works\cvc_project\CVC_Local\CVC.SiemensS7Net\CVC.SiemensS7Net.csproj
[LanguageServerProjectSystem] Project e:\my_works\cvc_project\CVC_Local\CVC.OpcUaClient\CVC.OpcUaClient.csproj now has 4 source file(s).
[LanguageServerProjectSystem] Project e:\my_works\cvc_project\CVC_Local\CVC.OpcUaClient\CVC.OpcUaClient.csproj now has 175 reference(s).
[Warn  - 11:34:13 PM] [LanguageServerProjectSystem] Project e:\my_works\cvc_project\CVC_Local\CVC.OpcUaClient\CVC.OpcUaClient.csproj has unresolved dependencies
[LanguageServerHost] [02:34:14.157][Start]workspace/diagnostic
[LanguageServerHost] PublicWorkspacePullDiagnosticsHandler(category: , source: ) started getting diagnostics
[LanguageServerHost] previousResults.Length=0
[LanguageServerHost] Processing 0 documents
[LanguageServerHost] Closing workspace/diagnostics request
[LanguageServerHost] Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.Public.PublicWorkspacePullDiagnosticsHandler finished getting diagnostics
[LanguageServerHost] [02:34:14.171][End]workspace/diagnostic
[Info  - 11:34:15 PM] [LanguageServerProjectSystem] Successfully completed load of e:\my_works\cvc_project\CVC_Local\CVC.OpcUaClient\CVC.OpcUaClient.csproj
[LanguageServerProjectSystem] Project e:\my_works\cvc_project\CVC_Local\CVC\CVC.Web.csproj now has 833 source file(s).
[LanguageServerProjectSystem] Project e:\my_works\cvc_project\CVC_Local\CVC\CVC.Web.csproj now has 231 reference(s).
[Warn  - 11:34:15 PM] [LanguageServerProjectSystem] Project e:\my_works\cvc_project\CVC_Local\CVC\CVC.Web.csproj has unresolved dependencies
[LanguageServerHost] [02:34:16.180][Start]workspace/diagnostic
[LanguageServerHost] PublicWorkspacePullDiagnosticsHandler(category: , source: ) started getting diagnostics
[LanguageServerHost] previousResults.Length=0
[LanguageServerHost] Processing 0 documents
[LanguageServerHost] Closing workspace/diagnostics request
[LanguageServerHost] Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.Public.PublicWorkspacePullDiagnosticsHandler finished getting diagnostics
[LanguageServerHost] [02:34:16.180][End]workspace/diagnostic
[Warn  - 11:34:17 PM] [LanguageServerProjectSystem] Warning while loading e:\my_works\cvc_project\CVC_Local\CVC\CVC.Web.csproj: Resolved file has a bad image, no metadata, or is otherwise inaccessible. An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B) ..\packages\Microsoft.VisualStudio.Web.CodeGeneration.Design.3.1.3\lib\net461\dotnet-aspnet-codegenerator-design.exe
[LanguageServerHost] [02:34:17.035][Start]workspace/_roslyn_restore
[Info  - 11:34:17 PM] [Microsoft.CodeAnalysis.LanguageServer.DotnetCliHelper] Using dotnet executable configured on the PATH
[Microsoft.CodeAnalysis.LanguageServer.DotnetCliHelper] Running dotnet CLI command at C:\Program Files\dotnet\dotnet.exe in directory e:\my_works\cvc_project\CVC_Local\CVC.BusinessServices with arguments System.String[]
[Microsoft.CodeAnalysis.LanguageServer.DotnetCliHelper] Running dotnet CLI command at C:\Program Files\dotnet\dotnet.exe in directory e:\my_works\cvc_project\CVC_Local\CVC.AlarmWindowsService with arguments System.String[]
[LanguageServerHost] [02:34:18.184][Start]workspace/diagnostic
[LanguageServerHost] PublicWorkspacePullDiagnosticsHandler(category: , source: ) started getting diagnostics
[LanguageServerHost] previousResults.Length=0
[LanguageServerHost] Processing 0 documents
[LanguageServerHost] Closing workspace/diagnostics request
[LanguageServerHost] Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.Public.PublicWorkspacePullDiagnosticsHandler finished getting diagnostics
[LanguageServerHost] [02:34:18.184][End]workspace/diagnostic
[Microsoft.CodeAnalysis.LanguageServer.DotnetCliHelper] Running dotnet CLI command at C:\Program Files\dotnet\dotnet.exe in directory e:\my_works\cvc_project\CVC_Local\CVC.License with arguments System.String[]
[Microsoft.CodeAnalysis.LanguageServer.DotnetCliHelper] Running dotnet CLI command at C:\Program Files\dotnet\dotnet.exe in directory e:\my_works\cvc_project\CVC_Local\CVC.ViewModels with arguments System.String[]
[Microsoft.CodeAnalysis.LanguageServer.DotnetCliHelper] Running dotnet CLI command at C:\Program Files\dotnet\dotnet.exe in directory e:\my_works\cvc_project\CVC_Local\CVC.MDB with arguments System.String[]
[LanguageServerHost] [02:34:20.189][Start]workspace/diagnostic
[LanguageServerHost] PublicWorkspacePullDiagnosticsHandler(category: , source: ) started getting diagnostics
[LanguageServerHost] previousResults.Length=0
[LanguageServerHost] Processing 0 documents
[Microsoft.CodeAnalysis.LanguageServer.DotnetCliHelper] Running dotnet CLI command at C:\Program Files\dotnet\dotnet.exe in directory e:\my_works\cvc_project\CVC_Local\CVC.OpcUaClient with arguments System.String[]
[Microsoft.CodeAnalysis.LanguageServer.DotnetCliHelper] Running dotnet CLI command at C:\Program Files\dotnet\dotnet.exe in directory e:\my_works\cvc_project\CVC_Local\CVC with arguments System.String[]
[Microsoft.CodeAnalysis.LanguageServer.DotnetCliHelper] Running dotnet CLI command at C:\Program Files\dotnet\dotnet.exe in directory e:\my_works\cvc_project\CVC_Local\CVC.Data with arguments System.String[]
[Microsoft.CodeAnalysis.LanguageServer.DotnetCliHelper] Running dotnet CLI command at C:\Program Files\dotnet\dotnet.exe in directory e:\my_works\cvc_project\CVC_Local\CVC.SiemensS7Net with arguments System.String[]
[Microsoft.CodeAnalysis.LanguageServer.DotnetCliHelper] Running dotnet CLI command at C:\Program Files\dotnet\dotnet.exe in directory e:\my_works\cvc_project\CVC_Local\CVC.PLC with arguments System.String[]
[LanguageServerHost] [02:34:25.325][End]workspace/_roslyn_restore
[Info  - 11:34:25 PM] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:19.8065812
[BuildHost PID 82216] Sending a Shutdown request to the BuildHost.
[BuildHost PID 82216] Message from Process: info: Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.Program[0]
[BuildHost PID 82216] Message from Process:       RPC channel closed; process exiting.
[BuildHost PID 82216] Process shut down.
[BuildHost PID 68680] Sending a Shutdown request to the BuildHost.
[BuildHost PID 68680] Process shut down.
[LanguageServerHost] [02:34:25.362][End]solution/open
[LanguageServerHost] [02:34:25.364][Start]workspace/debugConfiguration
[LanguageServerHost] [02:34:25.379][End]workspace/debugConfiguration

        
### C# log ###
<details>Post the output from Output-->C# here</details>

### C# LSP Trace Logs ###
<details>Post the output from Output-->C# LSP Trace Logs here.  Requires `dotnet.server.trace` to be set to `Trace`</details>

## Environment information ##

**VSCode version**: 1.85.2
**C# Extension**: 2.16.24
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.418
 Commit:    21f869269c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.418\

Host:
  Version:      7.0.13
  Architecture: x64
  Commit:       3f73a2f186

.NET SDKs installed:
  3.1.100 [C:\Program Files\dotnet\sdk]
  6.0.321 [C:\Program Files\dotnet\sdk]
  6.0.418 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|chatgpt-gpt4-gpt3-vscode|EasyCodeAI|1.2.4|easycodeai.chatgpt-gpt4-gpt3-vscode-1.2.4|
|cmake|twxs|0.0.17|twxs.cmake-0.0.17|
|cpptask|kaysonwu|0.0.1|kaysonwu.cpptask-0.0.1|
|cpptools|ms-vscode|1.19.2|ms-vscode.cpptools-1.19.2-win32-x64|
|cpptools-extension-pack|ms-vscode|1.3.0|ms-vscode.cpptools-extension-pack-1.3.0|
|cpptools-themes|ms-vscode|2.0.0|ms-vscode.cpptools-themes-2.0.0|
|csdevkit|ms-dotnettools|1.2.7|ms-dotnettools.csdevkit-1.2.7-win32-x64|
|csharp|ms-dotnettools|2.16.24|ms-dotnettools.csharp-2.16.24-win32-x64|
|csharpextensions|kreativ-software|1.7.3|kreativ-software.csharpextensions-1.7.3|
|vscode-dotnet-runtime|ms-dotnettools|2.0.1|ms-dotnettools.vscode-dotnet-runtime-2.0.1|
|vscode-html-css|ecmel|2.0.9|ecmel.vscode-html-css-2.0.9|
|vscode-lldb|vadimcn|1.10.0|vadimcn.vscode-lldb-1.10.0|
|vscodeintellicode-csharp|ms-dotnettools|0.1.26|ms-dotnettools.vscodeintellicode-csharp-0.1.26-win32-x64|;

</details>

Extension version: 2.16.24
VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.18363
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|11.91GB (1.54GB free)|
|Process Argv|--crash-reporter-id 5da49f03-2b5b-4366-a7e2-74a23aafc444|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
0bi6i642:30951795
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019b:30953937
7j2b6412:30949929
bg6jg535:30956215

```

</details>

**Comment by dibarbet** [comment]
Can you provide more details on what behavior you're seeing that isn't working (screenshots are always helpful), how you expect it to work, etc?

**Comment by dibarbet** [comment]
Closing, not actionable.
