### ISSUE TITLE
Error s not working

### ISSUE THREAD

**Issue by ghost** [dotnet/vscode-csharp#6858]
Type: <b>Bug</b>

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>
        
### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.86.0
**C# Extension**: 2.15.30
**Using OmniSharp**: true

<details><summary>Dotnet Information</summary>

Host:
  Version:      7.0.15
  Architecture: x64
  Commit:       8f4568cdaa

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 7.0.15 [/Users/user/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.15~x64/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|code-runner|formulahendry|0.12.1|formulahendry.code-runner-0.12.1|
|code-spell-checker|streetsidesoftware|3.0.1|streetsidesoftware.code-spell-checker-3.0.1|
|codesnap|adpyke|1.3.4|adpyke.codesnap-1.3.4|
|csdevkit|ms-dotnettools|1.2.7|ms-dotnettools.csdevkit-1.2.7-darwin-x64|
|csharp|ms-dotnettools|2.15.30|ms-dotnettools.csharp-2.15.30-darwin-x64|
|csharpextension|bard83|1.10.0|bard83.csharpextension-1.10.0|
|dart-code|Dart-Code|3.82.0|dart-code.dart-code-3.82.0|
|debugpy|ms-python|2024.0.0|ms-python.debugpy-2024.0.0-darwin-x64|
|flutter|Dart-Code|3.82.0|dart-code.flutter-3.82.0|
|html-snippets|abusaidm|0.2.1|abusaidm.html-snippets-0.2.1|
|intellicode-api-usage-examples|VisualStudioExptTeam|0.2.8|visualstudioexptteam.intellicode-api-usage-examples-0.2.8|
|LiveServer|ritwickdey|5.7.9|ritwickdey.liveserver-5.7.9|
|material-icon-theme|PKief|4.33.0|pkief.material-icon-theme-4.33.0|
|prettier-vscode|esbenp|10.1.0|esbenp.prettier-vscode-10.1.0|
|pretty-formatter|mblode|0.2.4|mblode.pretty-formatter-0.2.4|
|python|ms-python|2024.0.0|ms-python.python-2024.0.0|
|synthwave-vscode|RobbOwen|0.1.15|robbowen.synthwave-vscode-0.1.15|
|targetframeworksswitcher|yamachu|1.1.0|yamachu.targetframeworksswitcher-1.1.0|
|vim|vscodevim|1.27.2|vscodevim.vim-1.27.2|
|vscode-dotnet-runtime|ms-dotnettools|2.0.1|ms-dotnettools.vscode-dotnet-runtime-2.0.1|
|vscode-html-css|ecmel|2.0.9|ecmel.vscode-html-css-2.0.9|
|vscode-lldb|vadimcn|1.10.0|vadimcn.vscode-lldb-1.10.0|
|vscode-markdownlint|DavidAnson|0.54.0|davidanson.vscode-markdownlint-0.54.0|
|vscode-pylance|ms-python|2023.12.1|ms-python.vscode-pylance-2023.12.1|
|vscodeintellicode|VisualStudioExptTeam|1.2.30|visualstudioexptteam.vscodeintellicode-1.2.30|
|vscodeintellicode-csharp|ms-dotnettools|0.1.26|ms-dotnettools.vscodeintellicode-csharp-0.1.26-darwin-x64|
|vsliveshare|ms-vsliveshare|1.0.5905|ms-vsliveshare.vsliveshare-1.0.5905|;

</details>

Extension version: 2.15.30
VS Code version: Code 1.86.0 (Universal) (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:29:15.765Z)
OS version: Darwin x64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 4, 3|
|Memory (System)|16.00GB (0.36GB free)|
|Process Argv|--crash-reporter-id c208f074-f46e-42da-a5aa-eaac21fd4203|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
0bi6i642:30951795
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019bcf:30953938
b5d27386:30958190
7j2b6412:30949929
e3gdj431:30958358

```

</details>

**Comment by dibarbet** [comment]
Can you provide any more information?  For example 
1.  Screenshots of what you're seeing, and what isn't working
2.  Logs from the 'C#' output window
3.  Logs from the 'Projects' output window

**Comment by dibarbet** [comment]
Closing, this is not actionable without the additional information requested.
