### ISSUE TITLE
intellisense for c#

### ISSUE THREAD

**Issue by vinay098** [dotnet/vscode-csharp#6862]
## Is your feature request related to a problem? Please describe.
i am creating a web api project in dotnet 7 but there is no errors showing in the code and i am not able to get if i am writing my syntax right or wrong
## Describe the solution you would like
please update this issue of intellisense for dot net
## Applicable Scenarios
In what scenarios would the feature apply?

**Comment by dibarbet** [comment]
The general scenario you described should work.  Can you provide more information?  For example
1.  Screenshots of what you're seeing, and detailed info on what you expect to see
2.  Logs from the 'C#' output window
3.  If you're using C# devkit, logs from the 'Projects' output window.

**Comment by dibarbet** [comment]
Closing, this is not actionable without the additional information requested.  If you're able to still reproduce this issue on the latest version of the extension, please re-open and include the requested information.
