### ISSUE TITLE
`COMPlus_EnableDiagnostics=0` breaks debugging

### ISSUE THREAD

**Issue by oldshensheep** [dotnet/vscode-csharp#6883]
Type: <b>Bug</b>

## Issue Description ##
Debugger not working on Windows, but on Linux It works fine. If I set a breakpoint, it won't stop when run through it.

## Steps to Reproduce ##
1. Create a HelloWorld 
2. Set a breakpoint
3. press F5 to debug

## Expected Behavior ##
If I use WSL2 to open this project and debugging, debugger works.

https://github.com/dotnet/vscode-csharp/assets/29306733/f18b6451-c171-4884-8131-fed6af4b3ae2

## Actual Behavior ##

https://github.com/dotnet/vscode-csharp/assets/29306733/658184b9-40cd-4ded-bd2a-dc987f291897

### C# log ###
[C#.log](https://github.com/dotnet/vscode-csharp/files/14256034/C.log)

### C# LSP Trace Logs ###
[C#LSP_Track_Log.log](https://github.com/dotnet/vscode-csharp/files/14256027/C.LSP_Track_Log.log)

### vsdbg-ui --server --consoleLogging ###
[vsdbg.log](https://github.com/dotnet/vscode-csharp/files/14256124/vsdbg.log)

## Environment information ##

**VSCode version**: 1.86.1
**C# Extension**: 2.15.30
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:           8.0.101
 Commit:            6eceda187b
 Workload version:  8.0.100-manifests.69afb982

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22635
 OS Platform: Windows
 RID:         win-x64
 Base Path:   E:\apps\Scoop\apps\dotnet-sdk\current\sdk\8.0.101\

.NET workloads installed:
 Workload version: 8.0.100-manifests.69afb982
There are no installed workloads to display.

Host:
  Version:      8.0.1
  Architecture: x64
  Commit:       bf5e279d92

.NET SDKs installed:
  8.0.101 [E:\apps\Scoop\apps\dotnet-sdk\current\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.1 [E:\apps\Scoop\apps\dotnet-sdk\current\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.1 [E:\apps\Scoop\apps\dotnet-sdk\current\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.1 [E:\apps\Scoop\apps\dotnet-sdk\current\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [E:\apps\Scoop\apps\dotnet-sdk\current]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|csdevkit|ms-dotnettools|1.3.10|ms-dotnettools.csdevkit-1.3.10-win32-x64|
|csharp|ms-dotnettools|2.15.30|ms-dotnettools.csharp-2.15.30-win32-x64|
|debugpy|ms-python|2024.0.0|ms-python.debugpy-2024.0.0-win32-x64|
|jupyter|ms-toolsai|2023.10.1003070148|ms-toolsai.jupyter-2023.10.1003070148-win32-x64|
|jupyter-keymap|ms-toolsai|1.1.2|ms-toolsai.jupyter-keymap-1.1.2|
|jupyter-renderers|ms-toolsai|1.0.17|ms-toolsai.jupyter-renderers-1.0.17|
|python|ms-python|2023.20.0|ms-python.python-2023.20.0|
|vscode-dotnet-runtime|ms-dotnettools|2.0.1|ms-dotnettools.vscode-dotnet-runtime-2.0.1|
|vscode-jupyter-cell-tags|ms-toolsai|0.1.8|ms-toolsai.vscode-jupyter-cell-tags-0.1.8|
|vscode-jupyter-slideshow|ms-toolsai|0.1.5|ms-toolsai.vscode-jupyter-slideshow-0.1.5|
|vscode-pylance|ms-python|2023.10.50|ms-python.vscode-pylance-2023.10.50|
|vscodeintellicode-csharp|ms-dotnettools|0.1.26|ms-dotnettools.vscodeintellicode-csharp-0.1.26-win32-x64|;

</details>

Extension version: 2.15.30
VS Code version: Code 1.86.1 (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:08:20.941Z)
OS version: Windows_NT x64 10.0.22635
Modes:

### Additional information

launch.json
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            // Use IntelliSense to find out which attributes exist for C# debugging
            // Use hover for the description of the existing attributes
            // For further information visit https://github.com/dotnet/vscode-csharp/blob/main/debugger-launchjson.md
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            // If you have changed target frameworks, make sure to update the program path.
            "program": "${workspaceFolder}/ConsoleApp1/bin/Debug/net8.0/ConsoleApp1.dll",
            "args": [],
            "cwd": "${workspaceFolder}/ConsoleApp1",
            // For more information about the 'console' field, see https://aka.ms/VSCode-CS-LaunchJson-Console
            "console": "internalConsole",
            "stopAtEntry": false,
            "logging": {
                "diagnosticsLog": {
                    "protocolMessages": true
                }
            },
            // "debugServer": 4711
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach"
        }
    ]
}

```

**Comment by oldshensheep** [comment]
Just noticed on Linux Debug Console will print this, but on windows it doesn't. Looks like on Windows it doesn't load symbols.
`Loaded '/mnt/e/code/DotnetTest/ConsoleApp1/bin/Debug/net8.0/ConsoleApp1.dll'. Symbols loaded.`
```
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.1/System.Private.CoreLib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/mnt/e/code/DotnetTest/ConsoleApp1/bin/Debug/net8.0/ConsoleApp1.dll'. Symbols loaded.
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.1/System.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.1/System.Console.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.

```
and VS code settings on Windows and WSL are the same... so...?

**Comment by gregg-miskelly** [comment]
What seems to be going on is that the .NET Runtime is never raising an event to the debugger to indicate that it is started. Do you have any `DOTNET_` or `COMPlus_` environment variables set?

**Comment by oldshensheep** [comment]
output of `set DOTNET_`
```
DOTNET_CLI_TELEMETRY_OPTOUT=1
DOTNET_ROOT=E:\apps\Scoop\apps\dotnet-sdk\current
DOTNET_TELEMETRY_OPTOUT=1
```

output of `set COMPlus_ `
```
COMPlus_EnableDiagnostics=0
```

**Comment by gregg-miskelly** [comment]
Remove `COMPlus_EnableDiagnostics=0` and your problem should be fixed.
