### ISSUE TITLE
Incorrect language strings for Razor Language Server Trace configuration

### ISSUE THREAD

**Issue by rsandbach** [dotnet/vscode-csharp#6893]
When #6770 was merged, the translation files may have been overlooked. The `Shared` output in vscode is reporting:

```
0000-00-00 00:00:00.000 [warning] [csharp]: Couldn't find message for key configuration.razor.server.trace.
```

_package.json_ was updated with the new resource string:
https://github.com/dotnet/vscode-csharp/blob/bb2134804be15ae64b715cc7a29b06eed82cdbc5/package.json#L1767

_package.nls.json_ still has the old key:
https://github.com/dotnet/vscode-csharp/blob/bb2134804be15ae64b715cc7a29b06eed82cdbc5/package.nls.json#L75

[These](https://github.com/search?q=repo%3Adotnet%2Fvscode-csharp+configuration.razor.trace&type=code) translation files still have the wrong key. I can throw together a pull request if desired, but am not sure if anything __else__ needs to be updated.

**Comment by dibarbet** [comment]
Resolved by https://github.com/dotnet/vscode-csharp/pull/6894, thanks!
