### ISSUE TITLE
Cannot debug simple hello world console app

### ISSUE THREAD

**Issue by sscata** [dotnet/vscode-csharp#6897]
Type: <b>Bug</b>

Scenario:
Install Rapberry PI OS (64 bit) on PI5.
Install dotnet 8.0.201 and update path on .profile, relogon
sudo apt-get install code
install c# DevKit
Create Console App

Failure:
"dotnet run " successfully run the app, where as any attempt to debug with vscode fails with:
Architecture: arm64
App host version:8.0.2
.Net location: Not found

**Comment by gregg-miskelly** [comment]
@sscata Please include details of what the failure was

**Comment by sscata** [comment]
Dear gregg,

I am sorry. I just found that the problem was the missing 

export DOTNET_ROOT = $HOME/.dotnet

Now it works.


`

**Comment by promisebella** [comment]
6897
