### ISSUE TITLE
Extension wont work for me

### ISSUE THREAD

**Issue by BengaCodes** [dotnet/vscode-csharp#6904]
Type: <b>Bug</b>

Using dotnet configured on PATH
Dotnet path: /usr/local/share/dotnet/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
Starting server at /Users/olugbengaolasebikan/.vscode/extensions/ms-dotnettools.csharp-2.15.30-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.LanguageServer.dll
Server arguments /Users/olugbengaolasebikan/.vscode/extensions/ms-dotnettools.csharp-2.15.30-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.LanguageServer.dll --logLevel Trace --starredCompletionComponentPath /Users/olugbengaolasebikan/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-0.1.26-darwin-x64/components/starred-suggestions/node_modules/@vsintellicode/starred-suggestions-csharp --extension /Users/olugbengaolasebikan/.vscode/extensions/ms-dotnettools.csharp-2.15.30-darwin-arm64/.roslynDevKit/Microsoft.VisualStudio.LanguageServices.DevKit.dll --sessionId 1a3f1306-b31a-40b8-bfaf-8045a20293141708291474054 --telemetryLevel all --extensionLogDirectory /Users/olugbengaolasebikan/Library/Application Support/Code/logs/20240218T204846/window4/exthost/ms-dotnettools.csharp
waiting for named pipe information from server...
[stdout] trce: Program[0]
      .NET Runtime Version: .NET 7.0.14
[stdout] dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /Users/olugbengaolasebikan/.vscode/extensions/ms-dotnettools.csharp-2.15.30-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /Users/olugbengaolasebikan/.vscode/extensions/ms-dotnettools.csharp-2.15.30-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.Razor.Compiler.Mvc.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /Users/olugbengaolasebikan/.vscode/extensions/ms-dotnettools.csharp-2.15.30-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.Remote.Workspaces.dll added to workspace.
[stdout] dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /Users/olugbengaolasebikan/.vscode/extensions/ms-dotnettools.csharp-2.15.30-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.CSharp.Workspaces.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /Users/olugbengaolasebikan/.vscode/extensions/ms-dotnettools.csharp-2.15.30-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.Razor.Compiler.Mvc.Version2_X.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /Users/olugbengaolasebikan/.vscode/extensions/ms-dotnettools.csharp-2.15.30-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.CSharp.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /Users/olugbengaolasebikan/.vscode/extensions/ms-dotnettools.csharp-2.15.30-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /Users/olugbengaolasebikan/.vscode/extensions/ms-dotnettools.csharp-2.15.30-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.Razor.Compiler.Language.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /Users/olugbengaolasebikan/.vscode/extensions/ms-dotnettools.csharp-2.15.30-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.Scripting.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /Users/olugbengaolasebikan/.vscode/extensions/ms-dotnettools.csharp-2.15.30-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.Razor.Compiler.Mvc.Version1_X.dll added to workspace.
[stdout] dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /Users/olugbengaolasebikan/.vscode/extensions/ms-dotnettools.csharp-2.15.30-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.Workspaces.MSBuild.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /Users/olugbengaolasebikan/.vscode/extensions/ms-dotnettools.csharp-2.15.30-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.Elfie.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /Users/olugbengaolasebikan/.vscode/extensions/ms-dotnettools.csharp-2.15.30-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /Users/olugbengaolasebikan/.vscode/extensions/ms-dotnettools.csharp-2.15.30-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.ExternalAccess.AspNetCore.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /Users/olugbengaolasebikan/.vscode/extensions/ms-dotnettools.csharp-2.15.30-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.CSharp.Features.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /Users/olugbengaolasebikan/.vscode/extensions/ms-dotnettools.csharp-2.15.30-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.Workspaces.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /Users/olugbengaolasebikan/.vscode/extensions/ms-dotnettools.csharp-2.15.30-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.Razor.Compiler.CSharp.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /Users/olugbengaolasebikan/.vscode/extensions/ms-dotnettools.csharp-2.15.30-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.AnalyzerUtilities.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /Users/olugbengaolasebikan/.vscode/extensions/ms-dotnettools.csharp-2.15.30-darwin-arm64/.roslyn/Microsoft.CodeAnalysis.Features.dll added to workspace.
[stdout] {"pipeName":"/var/folders/gl/1pzn2t5j7b98m3gcthyd7sy40000gn/T/6ae03ce7.sock"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 21:24:35] [Program] Language server initialized
[LanguageServerHost] [09:24:35.317][Start]initialize
[LanguageServerHost] [09:24:35.349][End]initialize
[LanguageServerHost] [09:24:35.352][Start]initialized
[LanguageServerHost] [09:24:35.373][End]initialized
[LanguageServerHost] [09:24:35.380][Start]workspace/diagnostic
[LanguageServerHost] PublicWorkspacePullDiagnosticsHandler(category: , source: ) started getting diagnostics
[LanguageServerHost] previousResults.Length=0
[LanguageServerHost] Processing 0 documents
[LanguageServerHost] [09:24:36.192][Start]workspace/didChangeConfiguration
[LanguageServerHost] [09:24:36.206][End]workspace/didChangeConfiguration
[LanguageServerHost] [09:24:36.206][Start]workspace/didChangeConfiguration
[LanguageServerHost] [09:24:36.208][End]workspace/didChangeConfiguration
[LanguageServerHost] [09:24:36.393][Start]workspace/didChangeConfiguration
[LanguageServerHost] [09:24:36.395][End]workspace/didChangeConfiguration
[LanguageServerHost] [09:24:59.842][Start]workspace/buildOnlyDiagnosticIds
[LanguageServerHost] [09:24:59.845][End]workspace/buildOnlyDiagnosticIds

Extension version: 2.15.30
VS Code version: Code 1.86.1 (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:08:57.920Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (11 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|18.00GB (0.40GB free)|
|Process Argv|--crash-reporter-id 97c137d9-e623-4e6b-a1ad-2083e993b60c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyonecf:30548226
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30959801
7j2b6412:30964151
e3gdj431:30958358

```

</details>

**Comment by dibarbet** [comment]
Can you provide some more information about what exactly isn't working? 

It looks like you're using devkit, and a solution wasn't opened, so you might not be getting the proper intellisense.  Can you make sure you have a solution opened (e..g shows up in the solution explorer window)?
![image](https://github.com/dotnet/vscode-csharp/assets/5749229/ffebc4b4-a118-4562-a6dd-8b7ea51e8674)

**Comment by dibarbet** [comment]
Closing, this is not actionable without the additional information requested.
