### ISSUE TITLE
Last version that supports Windows 7

### ISSUE THREAD

**Issue by alexandrehtrb** [dotnet/vscode-csharp#6927]
Hello,

I would like to use the C# extension for VS Code on Windows 7 with .NET 6, but the extension doesn't work and shows the error below:

```
The language client requires VS Code version ^1.77.0 but received version 1.70.3
```

What is the last version that still works on Windows 7?

**Comment by alexandrehtrb** [comment]
I managed to get it working with version 1.26.0

![Code_56QXEBa9qc](https://github.com/dotnet/vscode-csharp/assets/27026741/e8ea6422-4039-4c07-94a5-5ea039307b2b)

**Comment by JoeRobich** [comment]
Hi @alexandrehtrb, The 1.x version of the extension uses OmniSharp to provide language services. Even through there will not be any new releases of 1.x, you can use the `omnisharp.path` setting to pull in a [newer release](https://github.com/OmniSharp/omnisharp-roslyn/releases) or even the latest nightly build of O#.

Setting description:
> Specifies the path to OmniSharp. When left empty the OmniSharp version pinned to the C# Extension is used. This can be the absolute path to an OmniSharp executable, a specific version number, or \"latest\". If a version number or \"latest\" is specified, the appropriate version of OmniSharp will be downloaded on your behalf. Setting \"latest\" is an opt-in into latest beta releases of OmniSharp.
