### ISSUE TITLE
Support Code Server usage

### ISSUE THREAD

**Issue by sgayda2** [dotnet/vscode-csharp#6957]
## Is your feature request related to a problem? Please describe.
I am unable to install this extension (does not show up when searching) while using code server and a web browser editor.

## Describe the solution you would like
It would be great to use the c# tooling provided by this extension while using code server through a web interface.

## Applicable Scenarios
Anytime you want to use c# with code server

## Describe alternatives you've considered
There are a few other extensions that might provide some of the functionality but not likely everything.

## Additional context
I don't believe this makes a difference but I am running code-server in a docker container (Ubuntu host), based on this image:
https://docs.linuxserver.io/images/docker-code-server/ and am accessing it through a web browser on a different machine on the same local network.

I did a quick search of the open issues and was not able to find a matching request, I am sorry if I missed it.

**Comment by ZeroAurora** [comment]
Official C# extension uses non-free components. For third-party usage I would recommend https://github.com/muhammadsammy/free-vscode-csharp
