### ISSUE TITLE
Notification Settings not respected using C# Extension

### ISSUE THREAD

**Issue by garrettlondon1** [dotnet/vscode-csharp#6977]
Type: <b>Bug</b>

## Issue Description ##
<img width="465" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/3959577/ce4e247a-3746-4de1-b2e0-6136204f3095">

## Expected Behavior ##
Expected behavior is the error does not show.

## Actual Behavior ##
The error shows, even though I disabled notifications from this extension

Makes it really hard to work on C# in VS Code, it's OK if there are errors in the language server, but it constantly spams the bottom right, and is incredibly distracting. Even in Zen Mode
### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>
        
### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.87.2
**C# Extension**: 2.22.3
**Using OmniSharp**: true

<details><summary>Mono Information</summary>
    Unable to find Mono. Ensure that Mono's '/bin' folder is added to your environment's PATH variable.</details>
<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:           8.0.203
 Commit:            5e1ceea679
 Workload version:  8.0.200-manifests.a7f084b6

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.1
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.203/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.3
  Architecture: arm64
  Commit:       9f4b1f5d66

.NET SDKs installed:
  8.0.203 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|azure-account|ms-vscode|0.11.6|ms-vscode.azure-account-0.11.6|
|copilot|GitHub|1.174.0|github.copilot-1.174.0|
|copilot-chat|GitHub|0.13.1|github.copilot-chat-0.13.1|
|csharp|ms-dotnettools|2.22.3|ms-dotnettools.csharp-2.22.3-darwin-arm64|
|data-workspace-vscode|ms-mssql|0.5.0|ms-mssql.data-workspace-vscode-0.5.0|
|dotnet-test-explorer|formulahendry|0.7.8|formulahendry.dotnet-test-explorer-0.7.8|
|hide-files|roonie007|1.0.3|roonie007.hide-files-1.0.3|
|mssql|ms-mssql|1.22.1|ms-mssql.mssql-1.22.1|
|sql-database-projects-vscode|ms-mssql|1.4.1|ms-mssql.sql-database-projects-vscode-1.4.1|
|tailwind-documentation|alfredbirk|0.1.15|alfredbirk.tailwind-documentation-0.1.15|
|tailwind-fold|stivo|0.1.0|stivo.tailwind-fold-0.1.0|
|vscode-azureappservice|ms-azuretools|0.25.2|ms-azuretools.vscode-azureappservice-0.25.2|
|vscode-azureresourcegroups|ms-azuretools|0.8.4|ms-azuretools.vscode-azureresourcegroups-0.8.4|
|vscode-azurestorage|ms-azuretools|0.15.3|ms-azuretools.vscode-azurestorage-0.15.3|
|vscode-dotnet-runtime|ms-dotnettools|2.0.2|ms-dotnettools.vscode-dotnet-runtime-2.0.2|
|vscode-nuget-package-manager|jmrog|1.1.6|jmrog.vscode-nuget-package-manager-1.1.6|
|vscode-pull-request-github|GitHub|0.82.0|github.vscode-pull-request-github-0.82.0|
|vscode-tailwindcss|bradlc|0.10.5|bradlc.vscode-tailwindcss-0.10.5|;

</details>

Extension version: 2.22.3
VS Code version: Code 1.87.2 (Universal) (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:21:31.043Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (11 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|36.00GB (1.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by dibarbet** [comment]
So here the server hits an exception and the vscode client displays a notification toast for it.  We don't control that display, so I filed https://github.com/microsoft/vscode-languageserver-node/issues/1449

**Comment by garrettlondon1** [comment]
@dibarbet what is the outcome of this, the ticket above was closed as completed.. so it is not possible to ignore at all?

In this case, how do we move this forward?

**Comment by garrettlondon1** [comment]
@dibarbet any update? Huge accessibility issue for me :(

**Comment by dibarbet** [comment]
I added an option to suppress LSP error toasts, will be available in next weeks prerelease

**Comment by garrettlondon1** [comment]
@dibarbet still getting errors for Request textDocument/semanticTokens/range failed.

When using the suppressLspErrorToasts setting. What happens on unrecoverable errors? There is no way to turn that off?

**Comment by garrettlondon1** [comment]
Hi team, still getting tons of error popups in vscode when developing blazor, C#, F# applications.. it is very distracting and even zen mode doesn't fix.
