### ISSUE TITLE
Minimized groups in the "Problems" pane expand after opening the file again

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/vscode-csharp#6978]
From vscode-dotnettools created by [codymullins](https://github.com/codymullins): microsoft/vscode-dotnettools#940  

Type: <b>Bug</b>

1. Have at least two c# razor code behind files (may happen with regular c# files too) with errors in them
2. Minimize the error list for one of the files
3. Navigate away from the file where you minimized the group
4. Click back to the file, it will re-expand the group

Extension version: 1.4.2
VS Code version: Code 1.86.2 (Universal) (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:42:13.651Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Max (16 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|8, 7, 7|
|Memory (System)|128.00GB (51.20GB free)|
|Process Argv|--crash-reporter-id c7185779-22e5-42a6-9068-2ef7d45dce79|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww1:30959800
edj9j583:30969295
7j2b6412:30969109

```

</details>

Screenshots:
<img width="569" alt="Screenshot 2024-02-21 at 2 44 23 PM" src="https://github.com/microsoft/vscode-dotnettools/assets/1738479/f55608c6-6ff7-41f5-aa29-632c4a878571">
<img width="429" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/1738479/60de3544-9703-4919-9e79-a01642a550eb">

**Comment by dibarbet** [comment]
The C# extension doesn't control the behavior of the problems list, this would need to be handled on the vscode side I believe. We just push errors and VSCode is responsible for rendering.
