### ISSUE TITLE
Language feature loss on C# only extension on Ubuntu

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/vscode-csharp#6986]
This tracks https://github.com/microsoft/vscode-dotnettools/issues/799#issuecomment-1963666428
 
![image](https://github.com/dotnet/vscode-csharp/assets/60013978/7fe8a64d-1522-476e-81d8-9ed6b95ecfac)

**Comment by MarkusRodler** [comment]
I would like to add, that most of the problems also occurs on WSL: https://github.com/microsoft/vscode-dotnettools/issues/814

**Comment by El-vi-art** [comment]
Necesito ayuda, de ninguna forma me quiere funcionar la extension, especialmente intellisense, he intentado de todo.
A sido asi desde que cambie para ubuntu y .NET 8
La salida me pone lo siguiente.
Using dotnet configured on PATH
Dotnet path: /snap/dotnet-sdk/239/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
waiting for named pipe information from server...
[stderr] Failed to load /snap/dotnet-sdk/239/shared/Microsoft.NETCore.App/8.0.3/libcoreclr.so, error: /lib/x86_64-linux-gnu/libpthread.so.0: version `GLIBC_PRIVATE' not found (required by /snap/core20/current/lib/x86_64-linux-gnu/librt.so.1)
[Error - 4:07:23 a. m.] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
Error: Timeout. Named pipe information not received from server.
    at Function.<anonymous> (/home/victor/.vscode/extensions/ms-dotnettools.csharp-2.22.5/dist/extension.js:2:1291663)
    at Generator.next (<anonymous>)
    at s (/home/victor/.vscode/extensions/ms-dotnettools.csharp-2.22.5/dist/extension.js:2:1281535)

**Comment by dibarbet** [comment]
> Necesito ayuda, de ninguna forma me quiere funcionar la extension, especialmente intellisense, he intentado de todo. A sido asi desde que cambie para ubuntu y .NET 8 La salida me pone lo siguiente. Using dotnet configured on PATH Dotnet path: /snap/dotnet-sdk/239/dotnet Activating C# + C# Dev Kit + C# IntelliCode... waiting for named pipe information from server... [stderr] Failed to load /snap/dotnet-sdk/239/shared/Microsoft.NETCore.App/8.0.3/libcoreclr.so, error: /lib/x86_64-linux-gnu/libpthread.so.0: version `GLIBC_PRIVATE' not found (required by /snap/core20/current/lib/x86_64-linux-gnu/librt.so.1) [Error - 4:07:23 a. m.] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server. Error: Timeout. Named pipe information not received from server. at Function. (/home/victor/.vscode/extensions/ms-dotnettools.csharp-2.22.5/dist/extension.js:2:1291663) at Generator.next () at s (/home/victor/.vscode/extensions/ms-dotnettools.csharp-2.22.5/dist/extension.js:2:1281535)

I recommend uninstalling the snap version of the .NET SDK and installing manually (via the .NET install script).  The snap version has a few known issues with the extension.

**Comment by dibarbet** [comment]
Closing this issue - there isn't anything actionable here at the moment.  If there are specific launch issues, please file a new issue with C# logs (ideally with `dotnet.server.trace` set to `Trace` in vscode settings).
