### ISSUE TITLE
Please keep changelogs up to date

### ISSUE THREAD

**Issue by lonix1** [dotnet/vscode-csharp#6988]
Often the changelog shown in vscode and the CHANGELOG file on the repo don't show relevant info. Also, they are not in sync.

I realise it's a bother to update the changelog, but given how many bugs there are in this extension, and how fast it's being developed, it's important for us to know what is in the new version before updating. And if something goes awry, it's important to be able to track down the problem.

Please keep the changelogs up to date? Or at least one of them.

For example, I'm on 2.22.3 and I've been offered 2.22.5 but there's no info for that in either changelog.

Thanks.

**Comment by dibarbet** [comment]
2.22.5 was a hotfix that we missed the changelog for.  We can't update the changelog shown in vscode for that version (its already released), but we've updated the changelog here - https://github.com/dotnet/vscode-csharp/pull/6997

We plan to work on automation for changelog generation, but currently its all manual, so occasionally something will slip through.
