### ISSUE TITLE
blazor not working since v2.15.30

### ISSUE THREAD

**Issue by clarity99** [dotnet/vscode-csharp#6990]
## Issue Description ##
since v2.15.30 Blazor razor views open, but no intellisense, no go to definition/implementations
## Steps to Reproduce ##

create a new blazor web app, open the solution in vs code

## Expected Behavior ##
intellisense and the rest should be working

## Actual Behavior ##
seems that only vs code text based completion is working

**Comment by clarity99** [comment]
logs:
[Archive.zip](https://github.com/dotnet/vscode-csharp/files/14742952/Archive.zip)

**Comment by dibarbet** [comment]
Should be fixed by https://github.com/dotnet/razor/pull/10133 - @ryzngard was this inserted last week?

**Comment by ryzngard** [comment]
@dibarbet The fix hasn't been inserted yet, we'll need to do another razor insertion. I can get that going soon

**Comment by ryzngard** [comment]
This is currently fixed, tested on `2.25.7`
