### ISSUE TITLE
Intellisense slow, last 2 releases

### ISSUE THREAD

**Issue by CoderJason123** [dotnet/vscode-csharp#6999]
v 2.22.5
I will get more info when i figure out how to get it, debugging flags or whatever.  I have tested in 2 different macs, latest vs code and latest c# extension.  Intellisense is taking about 3 or more seconds to fill things, even simple variable names.

I do not have copilot on my machine.  How can i get you more info to tell me why it's slow the last few weeks, on multiple machines?

It's bad enough I have to not use VScode for my work.  thank you.

**Comment by dibarbet** [comment]
Some initial info that would be useful, we may need to collect a trace eventually but we can start with the following:
1.  Set `dotnet.server.trace` to `Trace` in vscode settings and reload the window.  Attach the logs from the C# output window and the C# LSP trace logs output window
2.  Are you also using C# devkit?  If so attach the contents of the 'Projects' output window.  Also keep an eye on the 'Projects' counter at the bottom left of the vscode window to see if intellisense is still slow even after the spinner stops and updates the project count.

**Comment by CoderJason123** [comment]
FWIW - i took the drastic step of deleting all local vscode files / directories.  First i used the build in developer commands for clean up, but that didn't help.  If there is some type of cache somewhere or database that I can delete locally, or know where it is, that would perhaps be helpful.  But, after all of this deletion ... things sped up quite a bit.  In all the years of using vscode, I have never done this so maybe it's coincidence or maybe there was some local file issue.
