### ISSUE TITLE
Policy: DevKit should not take a required dependency on `.200+` SDK features

### ISSUE THREAD

**Issue by richlander** [dotnet/vscode-csharp#7006]
Linux distros that offer .NET (as a general rule) only offer `.1xx` feature band SDK versions. We've put a lot of effort into making Linux distros successful with source build. Source build is `.1xx` only. We want people to be happy and satisfied with using the .NET that is available in RHEL, Ubuntu, and friends.

As a result, we need a policy that any DevKit features that rely on `.2xx+` functionality fail gracefully when using a `.1xx` SDK.

**Comment by timheuer** [comment]
Kamino closed and cloned this issue to [microsoft/vscode-dotnettools](https://github.com/microsoft/vscode-dotnettools/issues/1033)
