### ISSUE TITLE
How to use DOTNET SDK with portable vsCode

### ISSUE THREAD

**Issue by danyooo** [dotnet/vscode-csharp#7021]
I'm trying to run c# on a flash drive with vsCode, and it's telling me I need to download the dotnet SDK. The problem is that I'm on a restricted system and I can't download it on the computer. Is there a way I can download it from another device and unload it on the flashdrive to be accessible on the device? or download it without the prerequisite permissions on the restricted device?

**Comment by danyooo** [comment]
Nevermind. Found out a way.

**Comment by Rinfra90** [comment]
@danyooo can you report what you did? I'm struggling to find a totally portable solution and it does not work correctly
