### ISSUE TITLE
C# LSP does not respect `EditorBrowsable` attribute values. 

### ISSUE THREAD

**Issue by ShreyasJejurkar** [dotnet/vscode-csharp#7032]
As we know we can hide members from Intellisense via `EditorBrowsable` attribute. This works in Visual Studio but looks like C# Roslyn-based LSP does not respect that attribute value. Check the below screenshot. 

![image](https://github.com/dotnet/vscode-csharp/assets/17148381/7b1e1d6f-b560-4d5c-93e8-68d96972cb23)

As we can see I have decorated `InternalId` property with `[EditorBrowsable(EditorBrowsableState.Never)]`, but when I create the object of that class and hit dot, I still see `InternalId` in intellisense which should not be there. 

## Environment information ##

**VSCode version**: 1.88.0
**C# Extension**: 2.24.17
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:           8.0.200
 Commit:            438cab6a9d
 Workload version:  8.0.200-manifests.5638171e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.26100
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.200\

.NET workloads installed:
 [aspire]
   Installation Source: VS 17.10.34607.79
   Manifest Version:    8.0.0-preview.3.24105.21/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.0.0-preview.3.24105.21\WorkloadManifest.json
   Install Type:              Msi

Host:
  Version:      8.0.2
  Architecture: x64
  Commit:       1381d5ebd2

.NET SDKs installed:
  7.0.404 [C:\Program Files\dotnet\sdk]
  8.0.100 [C:\Program Files\dotnet\sdk]
  8.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|codespaces|GitHub|1.16.18|github.codespaces-1.16.18|
|copilot|GitHub|1.178.810|github.copilot-1.178.810|
|copilot-chat|GitHub|0.14.2024032901|github.copilot-chat-0.14.2024032901|
|csdevkit|ms-dotnettools|1.5.10|ms-dotnettools.csdevkit-1.5.10-win32-x64|
|csharp|ms-dotnettools|2.24.17|ms-dotnettools.csharp-2.24.17-win32-x64|
|deep-default-dark-vscode-theme|danmeeusen|0.1.4|danmeeusen.deep-default-dark-vscode-theme-0.1.4|
|EditorConfig|EditorConfig|0.16.4|editorconfig.editorconfig-0.16.4|
|errorlens|usernamehw|3.16.0|usernamehw.errorlens-3.16.0|
|gitlens|eamodio|2024.4.805|eamodio.gitlens-2024.4.805|
|material-icon-theme|PKief|4.34.0|pkief.material-icon-theme-4.34.0|
|prettier-vscode|esbenp|10.4.0|esbenp.prettier-vscode-10.4.0|
|remote-containers|ms-vscode-remote|0.354.0|ms-vscode-remote.remote-containers-0.354.0|
|remote-wsl|ms-vscode-remote|0.88.0|ms-vscode-remote.remote-wsl-0.88.0|
|vscode-conventional-commits|vivaxy|1.25.0|vivaxy.vscode-conventional-commits-1.25.0|
|vscode-dotnet-runtime|ms-dotnettools|2.0.3|ms-dotnettools.vscode-dotnet-runtime-2.0.3|
|vscode-eslint|dbaeumer|2.4.4|dbaeumer.vscode-eslint-2.4.4|
|vscode-jest|Orta|6.2.3|orta.vscode-jest-6.2.3|;

</details>

**Comment by dibarbet** [comment]
Apologies, this is actually not a bug and by design.  EditorBrowseable will only hide members from metadata - if it is defined in your project or referenced project then it shows up.  See https://github.com/dotnet/roslyn/issues/66843
