### ISSUE TITLE
Can't create a new Project

### ISSUE THREAD

**Issue by YokiXml** [dotnet/vscode-csharp#7041]
### Describe the bug.

After install in Ubuntu Ubuntu 22.04.4 LTS, can not create a new project. The error say: Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server. Source C#

### Please attach log file(s) here if you have any.

The log file location should be copied to your clipboard if you came from VS Code.

### Reproduction Steps

Create a new C# project

### Expected Behavior

Crate a new C# project

### .NET Install Tool Version

8.0.204

### Your operating system? Please provide more detail, such as the version and or distro above.

N/A

### VS Code Version

1.88.1

**Comment by dibarbet** [comment]
Closing, not reproducible without the requested additional information.  Please re-open if you're able to provide it.
