### ISSUE TITLE
Go to definition problem.

### ISSUE THREAD

**Issue by everLEEst** [dotnet/vscode-csharp#7058]
Type: <b>Bug</b>

## Issue Description ##

I know, this issue was reported so many times  and I had look others but can not resolve my issue so please help me.

I work on some framework project, which has several big cs project in an single solution.
my working environment is ubuntu 20.04
Solution load very well. I can see all the projects in the solution.
go to defintion works very well in an single csproject.
but they cannot find the definition out of their project even though it is in the same solution.
Funny part is,
It cannot find the definition of System classes such as Dictionary, List, etc.

I tried latest version and pre-released version but both have same problem.

when we use Omnisharp, this was works very well, but after Dev Kit, it all broken.

## Steps to Reproduce ##
After Load Solution,
Go to Definition only works in single csproj,
others can not find the definition.

## Expected Behavior ##
should find definition well in same solution classes, or system classes.

## Actual Behavior ##
Not works.

### C# log ###
<details>Post the output from Output-->C# here</details>

### C# LSP Trace Logs ###
<details>Post the output from Output-->C# LSP Trace Logs here.  Requires `dotnet.server.trace` to be set to `Trace`</details>

## Environment information ##

**VSCode version**: 1.88.1
**C# Extension**: 2.26.13
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>

Host:
  Version:      8.0.4
  Architecture: x64
  Commit:       2d7eea2529
  RID:          linux-x64

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 8.0.4 [/home/sh10233lee/.config/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/8.0.4~x64/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|better-cpp-syntax|jeff-hykin|1.17.2|jeff-hykin.better-cpp-syntax-1.17.2|
|ccpp-extension-pack|LeoJhonSong|2.1.0|leojhonsong.ccpp-extension-pack-2.1.0|
|clang-format|xaver|1.9.0|xaver.clang-format-1.9.0|
|cmake|twxs|0.0.17|twxs.cmake-0.0.17|
|cmake-tools|ms-vscode|1.17.17|ms-vscode.cmake-tools-1.17.17|
|code-extension-manager|code|1.0.3|code.code-extension-manager-1.0.3|
|code-i|code-i|1.7.0|code-i.code-i-1.7.0|
|cpptools|ms-vscode|1.19.9|ms-vscode.cpptools-1.19.9-linux-x64|
|cpptools-extension-pack|ms-vscode|1.3.0|ms-vscode.cpptools-extension-pack-1.3.0|
|cpptools-themes|ms-vscode|2.0.0|ms-vscode.cpptools-themes-2.0.0|
|csdevkit|ms-dotnettools|1.5.14|ms-dotnettools.csdevkit-1.5.14-linux-x64|
|csharp|ms-dotnettools|2.26.13|ms-dotnettools.csharp-2.26.13-linux-x64|
|dart-code|Dart-Code|3.86.0|dart-code.dart-code-3.86.0|
|doxdocgen|cschlosser|1.4.0|cschlosser.doxdocgen-1.4.0|
|empty-indent|DmitryDorofeev|0.2.0|dmitrydorofeev.empty-indent-0.2.0|
|flutter|Dart-Code|3.86.0|dart-code.flutter-3.86.0|
|include-autocomplete|ajshort|0.0.4|ajshort.include-autocomplete-0.0.4|
|indent-one-space|usernamehw|1.0.0|usernamehw.indent-one-space-1.0.0|
|indent-rainbow|oderwat|8.3.1|oderwat.indent-rainbow-8.3.1|
|makefile-tools|ms-vscode|0.9.10|ms-vscode.makefile-tools-0.9.10|
|markdown-preview-github-styles|bierner|2.0.4|bierner.markdown-preview-github-styles-2.0.4|
|non-breaking-space-highlighter|viktorzetterstrom|0.0.3|viktorzetterstrom.non-breaking-space-highlighter-0.0.3|
|trailing-spaces|shardulm94|0.4.1|shardulm94.trailing-spaces-0.4.1|
|vscode-clangd|llvm-vs-code-extensions|0.1.28|llvm-vs-code-extensions.vscode-clangd-0.1.28|
|vscode-dotnet-runtime|ms-dotnettools|2.0.3|ms-dotnettools.vscode-dotnet-runtime-2.0.3|;

</details>

Extension version: 2.26.13
VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:34:12.840Z)
OS version: Linux x64 5.15.0-102-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz (16 x 2500)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|31.07GB (24.58GB free)|
|Process Argv|--unity-launch --crash-reporter-id 22d0ba17-874a-47d3-b999-07847f99adf3|
|Screen Reader|yes|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31022790

```

</details>

**Comment by JoeRobich** [comment]
@everLEEst Are you still encountering this issue? If so, can you please update the issue description with the C# log from the Output pane?

**Comment by cnzgray** [comment]
Ive got the same issue on Windows 10

**Comment by dibarbet** [comment]
Unfortunately this isn't actionable without the additional requested information.  Closing this issue.  If you're still having problems, please reopen this issue and include the following details:
1.  Check that the solution explorer shows the solution with the expected projects.  
2.  Set `dotnet.server.trace` to `Trace` in vscode settings, reload the window, then Attach the 'Projects' output window logs and 'C#' output window logs so we can diagnosis what is going wrong.

**Comment by Riki-Du** [comment]
same
