### ISSUE TITLE
method intelliSense is wrong in Parallel.For action

### ISSUE THREAD

**Issue by mypursuit** [dotnet/vscode-csharp#7071]
Environment:
    版本: 1.88.1 (system setup)
    提交: e170252f762678dec6ca2cc69aba1570769a5d39
    日期: 2024-04-10T17:41:02.734Z
    Electron: 28.2.8
    ElectronBuildId: 27744544
    Chromium: 120.0.6099.291
    Node.js: 18.18.2
    V8: 12.0.267.19-electron.0
    OS: Windows_NT x64 10.0.22631
    C# Dev Kit: v1.4.29

---
input `new Dictionary`,but   intelliSense is Parallel.For  method,like this:

![image](https://github.com/dotnet/vscode-csharp/assets/10861805/de66f7f9-f33c-43a9-97e7-3f3198ceb6d3)
---
code like this
```
 Parallel.For(0, 200, async (index) =>
  {
      new Dictionary()
  });
```

**Comment by dibarbet** [comment]
The starred suggestions are provided by the 'IntelliCode for C# Dev Kit' extension, which promotes certain items in the list based on what you likely might pick.  It isn't guaranteed to pick exactly what you want every time, but it should pick reasonable things.

In this case, promoting index inside the list doesn't seem unreasonable to me (the variable is in scope).

If you're consistently seeing strange suggestions, file an issue on the intellicode side here - https://github.com/MicrosoftDocs/intellicode/issues
