### ISSUE TITLE
Add Collapse Folders button in the Solution explorer pane

### ISSUE THREAD

**Issue by shusann01116** [dotnet/vscode-csharp#7085]
It would be great to have the same feature as the Folder pane does in Solution Explorer.

![image](https://github.com/dotnet/vscode-csharp/assets/26602565/95a8923c-9271-45ac-bd6f-9bf51244b030)

**Comment by dibarbet** [comment]
duplicate of https://github.com/microsoft/vscode-dotnettools/issues/612
