### ISSUE TITLE
error c#

### ISSUE THREAD

**Issue by FrddySign** [dotnet/vscode-csharp#7094]
We have written the needed data into your clipboard because it was too large to send. Please 
Type: <b>Bug</b>

Using dotnet configured on PATH
Dotnet path: C:\Program Files\dotnet\dotnet.exe
Activating C# + C# Dev Kit...
waiting for named pipe information from server...
[stdout] {"pipeName":"\\\\.\\pipe\\cece7761"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 1:04:33 PM] [Program] Language server initialized

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>
        
### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.89.0
**C# Extension**: 2.23.15
**Using OmniSharp**: true

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:           8.0.204
 Commit:            c338c7548c
 Workload version:  8.0.200-manifests.9f663350

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.204\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.4
  Architecture: x64
  Commit:       2d7eea2529

.NET SDKs installed:
  8.0.204 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|auto-rename-tag|formulahendry|0.1.10|formulahendry.auto-rename-tag-0.1.10|
|beautify|HookyQR|1.5.0|hookyqr.beautify-1.5.0|
|blackbox|Blackboxapp|1.3.18|blackboxapp.blackbox-1.3.18|
|bootstrap-intellisense|hossaini|1.1.10|hossaini.bootstrap-intellisense-1.1.10|
|bracket-pair-color-dlw|BracketPairColorDLW|0.0.6|bracketpaircolordlw.bracket-pair-color-dlw-0.0.6|
|code-runner|formulahendry|0.12.2|formulahendry.code-runner-0.12.2|
|console-ninja|WallabyJs|1.0.319|wallabyjs.console-ninja-1.0.319|
|copilot|GitHub|1.186.0|github.copilot-1.186.0|
|copilot-chat|GitHub|0.15.0|github.copilot-chat-0.15.0|
|csdevkit|ms-dotnettools|1.4.29|ms-dotnettools.csdevkit-1.4.29-win32-x64|
|csharp|ms-dotnettools|2.23.15|ms-dotnettools.csharp-2.23.15-win32-x64|
|css-minify|DiegoMolina|0.1.13|diegomolina.css-minify-0.1.13|
|debugpy|ms-python|2024.6.0|ms-python.debugpy-2024.6.0-win32-x64|
|emoji-snippets|devzstudio|1.5.3|devzstudio.emoji-snippets-1.5.3|
|errorlens|usernamehw|3.17.0|usernamehw.errorlens-3.17.0|
|es7-react-js-snippets|dsznajder|4.4.3|dsznajder.es7-react-js-snippets-4.4.3|
|es7-react-js-snippets|rodrigovallades|1.9.3|rodrigovallades.es7-react-js-snippets-1.9.3|
|htmltagwrap|bradgashler|1.0.0|bradgashler.htmltagwrap-1.0.0|
|htmx-tags|otovo-oss|0.0.8|otovo-oss.htmx-tags-0.0.8|
|indent-rainbow|oderwat|8.3.1|oderwat.indent-rainbow-8.3.1|
|intellicode-api-usage-examples|VisualStudioExptTeam|0.2.8|visualstudioexptteam.intellicode-api-usage-examples-0.2.8|
|isort|ms-python|2023.10.1|ms-python.isort-2023.10.1|
|JavaScriptSnippets|xabikos|1.8.0|xabikos.javascriptsnippets-1.8.0|
|jupyter|ms-toolsai|2024.4.0|ms-toolsai.jupyter-2024.4.0-win32-x64|
|jupyter-keymap|ms-toolsai|1.1.2|ms-toolsai.jupyter-keymap-1.1.2|
|jupyter-renderers|ms-toolsai|1.0.17|ms-toolsai.jupyter-renderers-1.0.17|
|live-sass|glenn2223|6.1.2|glenn2223.live-sass-6.1.2|
|LiveServer|ritwickdey|5.7.9|ritwickdey.liveserver-5.7.9|
|material-icon-theme|PKief|5.1.0|pkief.material-icon-theme-5.1.0|
|path-intellisense|christian-kohler|2.8.5|christian-kohler.path-intellisense-2.8.5|
|polacode|pnp|0.3.4|pnp.polacode-0.3.4|
|prettier-vscode|esbenp|10.4.0|esbenp.prettier-vscode-10.4.0|
|python|ms-python|2024.6.0|ms-python.python-2024.6.0|
|quokka-vscode|WallabyJs|1.0.637|wallabyjs.quokka-vscode-1.0.637|
|Splash|Jonas|1.0.2|jonas.splash-1.0.2|
|vercel-vscode|haydenbleasel|1.0.29|haydenbleasel.vercel-vscode-1.0.29|
|vscode-css-peek|pranaygp|4.4.1|pranaygp.vscode-css-peek-4.4.1|
|vscode-docker|ms-azuretools|1.29.1|ms-azuretools.vscode-docker-1.29.1|
|vscode-dotnet-runtime|ms-dotnettools|2.0.3|ms-dotnettools.vscode-dotnet-runtime-2.0.3|
|vscode-env-selector|andricdev|0.3.0|andricdev.vscode-env-selector-0.3.0|
|vscode-eslint|dbaeumer|2.4.4|dbaeumer.vscode-eslint-2.4.4|
|vscode-google-translate|funkyremi|1.4.13|funkyremi.vscode-google-translate-1.4.13|
|vscode-icons|vscode-icons-team|12.7.0|vscode-icons-team.vscode-icons-12.7.0|
|vscode-jupyter-cell-tags|ms-toolsai|0.1.9|ms-toolsai.vscode-jupyter-cell-tags-0.1.9|
|vscode-jupyter-slideshow|ms-toolsai|0.1.6|ms-toolsai.vscode-jupyter-slideshow-0.1.6|
|vscode-language-pack-es|MS-CEINTL|1.89.2024050109|ms-ceintl.vscode-language-pack-es-1.89.2024050109|
|vscode-pylance|ms-python|2024.4.1|ms-python.vscode-pylance-2024.4.1|
|vscode-tailwindcss|bradlc|0.10.5|bradlc.vscode-tailwindcss-0.10.5|
|vscode-thunder-client|rangav|2.22.1|rangav.vscode-thunder-client-2.22.1|;

</details>

Extension version: 2.23.15
VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:09:22.859Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|3.91GB (0.37GB free)|
|Process Argv|--crash-reporter-id 4fbb942d-04f1-4488-8cea-a3bfb14d1ca7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
666c4381:30973075
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31022790
a69g1124:31038041
dwnewjupytercf:31035177

```

</details>

paste.

**Comment by dibarbet** [comment]
@FrddySign are you able to provide more details on what went wrong?  For example what you saw, what you expected to happen, and any logs + screenshots of the incorrect behavior.

**Comment by FrddySign** [comment]
Hello, good afternoon, I hope this is well resolved.

greetings.

**Comment by dibarbet** [comment]
Closing.  Without additional information this is not actionable.  Feel free to re-open if you're able to provide the requested information.
