### ISSUE TITLE
CONTRIBUTING.md - Building - Step 3 - gulp installDependencies fails with error TS7006: Parameter 'pr' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by gautaz** [dotnet/vscode-csharp#7128]
## Environment data

`dotnet --info` output:
```console
.NET SDK:
 Version:   7.0.408
 Commit:    03a0111c2e

Runtime Environment:
 OS Name:     nixos
 OS Version:  24.05
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /nix/store/8ycn4yw0lc02dlziirqjs9islr03nar1-dotnet-sdk-7.0.408/sdk/7.0.408/

Host:
  Version:      7.0.18
  Architecture: x64
  Commit:       544c7e6eb3

.NET SDKs installed:
  7.0.408 [/nix/store/8ycn4yw0lc02dlziirqjs9islr03nar1-dotnet-sdk-7.0.408/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.18 [/nix/store/8ycn4yw0lc02dlziirqjs9islr03nar1-dotnet-sdk-7.0.408/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.18 [/nix/store/8ycn4yw0lc02dlziirqjs9islr03nar1-dotnet-sdk-7.0.408/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```
VS Code version: 1.89.1
C# Extension version: current main, commit 745d6efcb96f0e10a3b744273e1e2dac2a022bf3

## OmniSharp log
N/A

## Steps to reproduce

1. Follow the extension build steps available in CONTRIBUTING.md
2. On step 3 of the Building section, `gulp installDependencies` fails with the following message:

```console
❯ gulp installDependencies
[10:55:39] Requiring external module ts-node/register
tasks/localizationTasks.ts:130:36 - error TS7006: Parameter 'pr' implicitly has an 'any' type.

130     if (listPullRequest.data.some((pr) => pr.title === title)) {
```

Current gulp version used:

```console
❯ gulp --version
CLI version: 2.3.0
Local version: 4.0.2
```

## Expected  behavior

The extension build process should succeed.

## Actual behavior

The extension build process fails.

## Additional context

None that I can think of, feel free to ask for any missing detail.

**Comment by dibarbet** [comment]
@gautaz what node version do you have?

**Comment by gautaz** [comment]
Hello @dibarbet, here it is:
```console
❯ node --version
v22.0.0
```

Looking back at the contributing guide, v18 is recommended, I inferred that subsequent major versions would stiil work, seems this is not the case.
Perhaps recommended should be replaced by mandatory?

**Comment by dibarbet** [comment]
> Looking back at the contributing guide, v18 is recommended, I inferred that subsequent major versions would stiil work, seems this is not the case.
Perhaps recommended should be replaced by mandatory?

I can update the wording - we don't explicitly block newer versions, so if a newer version works then its absolutely fine to use it.  But we do not test other versions and there are often changes that make things not work properly.
