### ISSUE TITLE
An error when trying to clean the solution

### ISSUE THREAD

**Issue by ArianeBouchardConformit** [dotnet/vscode-csharp#7130]
Type: <b>Bug</b>

In the solution explorer, right click the main folder, Clean.

An error shows up that asks me to report it:

The error generated by VSCode was too long for GitHub. Here's a Pastebin.

https://pastebin.com/EWSfXArj

**Comment by dibarbet** [comment]
I wasn't able to reproduce this on any of my solutions locally, @ArianeBouchardConformit would you mind sending some additional logs?
1.  Set `dotnet.server.trace` to `Trace` in vscode settings, reload the window.  Then attach the 'C#' output window contents here?
2.  Run the 'open extension logs folder command, and zip up the ms-dotnettools.csdevkit folder in there and attach
![image](https://github.com/dotnet/vscode-csharp/assets/5749229/27c89228-8603-49c2-beaa-25e7b0c534ba)

**Comment by dibarbet** [comment]
Closing - not actionable without the additional requested information.  If you're able to provide it, please re-open with the requested details.
