### ISSUE TITLE
color theme

### ISSUE THREAD

**Issue by xandudex** [dotnet/vscode-csharp#7131]
Hello! 

Will you improve current color themes? I use light one, but check the dark and it is the same, the color for keyword, types and so on often are limited compare to vs comunity, will you try to improve them? If the answer is mb later then link me to topics where can I find how to separate member in json of theme, like enums, generic, class and so on, I will try my own. 

That is the only thing which keeps me in vs community, I've tried a lot of themes (especially light ones), and thay are limited for c#, sadly

**Comment by dibarbet** [comment]
@xandudex which light/dark themes specifically are you using?  I would generally recommend the 'Visual Studio 2019 Dark' or 'Visual Studio 2019 Light' themes for use with the extension.  Those should be pretty similar to what VS has by default.

If you don't like the colors for keywords and other items in the themes, it isn't too hard to customize it either.  See https://code.visualstudio.com/docs/getstarted/themes#_editor-semantic-highlighting

For example, if you wanted to change the color of enums, you would first find the semantic token type for enum using the 'Developer: Inspect Editor Tokens and Scopes' command.
![image](https://github.com/dotnet/vscode-csharp/assets/5749229/a3ec2820-6892-4335-b198-3d3b27c1dae3)

Then in your settings.json you could add additional customizations for the 'enum' token type
```
"editor.semanticTokenColorCustomizations": {
        "rules": {
            "enum": {
                "foreground": "#e30c0c",
                "bold": true
            }
        }
    }
```

**Comment by JoeRobich** [comment]
@xandudex If you are still having trouble, please reopen and provide the requested information.
