### ISSUE TITLE
All C# compiler or analyzer warnings are duplicated

### ISSUE THREAD

**Issue by rjgotten** [dotnet/vscode-csharp#7156]
Type: <b>Bug</b>

## Issue Description ##
All warnings resulting from `dotnet.backgroundAnalysis.analyzerDiagnosticsScope` and/or `dotnet.backgroundAnalysis.compilerDiagnosticsScope` are duplicated.

Switching the VSCode `Problems` panel into tabular mode shows that the source of each first instance is
`WorkspaceDocumentsAndProject`, while the source of each second instance is an anonymous `_generated_diagnostic_collection_name_#3`.

## Steps to Reproduce ##

Open project which worked fine under the previous installed `2.28.11` version of the C# extension, with the new `2.30.28` version of the extension installed.

## Expected Behavior ##

Warnings and errors from background analysis are only reported once.

## Actual Behavior ##

Warnings and errors from background analysis are reported twice.

## Environment information ##

**VSCode version**: 1.88.1
**C# Extension**: 2.30.28
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:           8.0.205
 Commit:            3e1383b780
 Workload version:  8.0.200-manifests.818b3449

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.205\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.5
  Architecture: x64
  Commit:       087e15321b

.NET SDKs installed:
  8.0.205 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|csdevkit|ms-dotnettools|1.6.8|ms-dotnettools.csdevkit-1.6.8-win32-x64|
|csharp|ms-dotnettools|2.30.28|ms-dotnettools.csharp-2.30.28-win32-x64|
|material-icon-theme|PKief|5.3.0|pkief.material-icon-theme-5.3.0|
|vscode-dotnet-runtime|ms-dotnettools|2.0.5|ms-dotnettools.vscode-dotnet-runtime-2.0.5|
|vscode-eslint|dbaeumer|2.4.4|dbaeumer.vscode-eslint-2.4.4|
|vscode-stylelint|stylelint|1.4.0|stylelint.vscode-stylelint-1.4.0|
|vscode-yaml|redhat|1.14.0|redhat.vscode-yaml-1.14.0|;

</details>

Extension version: 2.30.28
VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by dibarbet** [comment]
Can repro - related to the recent XAML intellisense work.  If you're not using XAML intellisense, as a temporary workaround you can uncheck the `dotnet.enableXamlTools` setting
![image](https://github.com/dotnet/vscode-csharp/assets/5749229/dade2a9f-2776-4623-a5dd-84b01e183a13)

**Comment by rjgotten** [comment]
@dibarbet 
Thanks for the workaround. Awesome ❤️

**Comment by dibarbet** [comment]
This should be fixed as of the latest 2.33.13 prerelease (going into the release channel this week).
