### ISSUE TITLE
Element with id <solution> is already registered

### ISSUE THREAD

**Issue by davidfowl** [dotnet/vscode-csharp#7164]
I get this error randomly while using devkit and it breaks the solution explorer.

<img width="1198" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/95136/1c234aa0-49a2-42e0-b09e-560757e164d6">

**Comment by davidfowl** [comment]
This happens really often when navigating to different VS code windows and back to the solution view. I have some logs captured but not sure which level this error happens at.

**Comment by jasonmalinowski** [comment]
@davidfowl Do you have the logs handy to look at?

**Comment by dibarbet** [comment]
Issues is on the devkit side, duplicate of https://github.com/microsoft/vscode-dotnettools/issues/1349
