### ISSUE TITLE
Group Nuget Files Under Nuget Directory in Solution Explorer

### ISSUE THREAD

**Issue by adnanalbeda** [dotnet/vscode-csharp#7166]
## Is your feature request related to a problem? Please describe.

I have a project depending on QuestPDF nuget package, and it has many font files. 
They are taking a huge space in solution explorer and make the explorer looks ugly.

## Describe the solution you would like

Group all of Nuget files under Nuget Folder then sub folders per Nuget Package same way as VS Solution Explorer, so it looks like this:

```
Explorer: Solution
|_ Project
| |_ Dependencies
| | |_ Nuget Packages
| | | |_ QuestPDF
| | | | |_ ...
```

and don't show these files in all other depending projects.

## Applicable Scenarios

Solutions loaded and browsed by solution explorer panel.

## Describe alternatives you've considered

N/A

## Additional context

Current Behavior:
![Screenshot_Panel](https://github.com/dotnet/vscode-csharp/assets/31453856/123f2f8f-7f18-4b00-9e62-37f1a4600eb9)

**Comment by dibarbet** [comment]
Solution explorer is owned on the C# Dev Kit side, please use this issue for tracking: https://github.com/microsoft/vscode-dotnettools/issues/1215
