### ISSUE TITLE
View template generations

### ISSUE THREAD

**Issue by ImRLopezAG** [dotnet/vscode-csharp#7168]
## Is your feature request related to a problem? Please describe.

As in VS IDE we have a view generation to MVC projects we need a  easy way to generate our views from the controller.

## Describe the solution you would like

Could add an option like right click on the controller method or (cmd,ctrl) + . and in the panel  show the option "Add View" it could be a dropdown with the diferent templates as we have in VS IDE 
(LIST, CREATE, DELETE, DETAILS).
## Applicable Scenarios
- Create a quick Demo
- Easy forms

## Describe alternatives you've considered

I've found an extension who partially implement this feature the name of the extension is [ASP.NET Core Switcher](https://github.com/AdrianWilczynski/AspNetCoreSwitcher)

![image](https://github.com/dotnet/vscode-csharp/assets/88790737/1d13edc6-594e-49de-9103-2aa6354c357f)

But instead of a single option could be a dropdown or select option.

**Comment by dibarbet** [comment]
Unfortunately we don't have easy access to the information required to do this in the standalone version of the C# extension.  However it may be possible to do in C# Dev Kit.  I've created https://github.com/microsoft/vscode-dotnettools/issues/1216 to track this request on their side.
