### ISSUE TITLE
Reordering classes, methods and so on using Outline window

### ISSUE THREAD

**Issue by OlegKarasik** [dotnet/vscode-csharp#7174]
## Is your feature request related to a problem? Please describe.
I do a lot of reordering within the code files (rearranging classes, methods and so on) and currently in vs code I have to cut and paste them to actually move something.

## Describe the solution you would like
It would be great to have Outline window to support reordering, so I can drag and drop a method into a new place (between other methods) using the window.

## Applicable Scenarios
Reordering methods, classes and so on.

## Describe alternatives you've considered
Copy and Paste

## Additional context
None

**Comment by dibarbet** [comment]
This requires support in VSCode itself.  See https://github.com/microsoft/vscode/issues/49925
