### ISSUE TITLE
[MacOS] Unable to display source file when debugging .net dll compiled on Windows with portable pdb format and published as nuget

### ISSUE THREAD

**Issue by jspelletier** [dotnet/vscode-csharp#7209]
## Issue Description ##

I have a application .net 6 application compiled on Windows with portable pdb format and published as nuget in an internal company nuget server.

When executing the application in the VSCode debugger on a Mac I am able to put breakpoints and the execution stops when reaching the breakpoints BUT the debugger is unable to display the source file.

Instead it displays a message such as the following one:

Could not load source 'd:\b\0\193178\Sharpmake\Sharpmake\DebugProjectGenerator.cs': Incorrect format of 'source' message..

If I compile the application locally on the mac, the breakpoints works as expected

## Steps to Reproduce ##

- Compile an application with portable pdb format on Windows, publish it in a nuget package.

- Install the nuget package on the mac
- Get the source code for the app on the mac
- Setup a launch.json for debugging the app on the mac
- Put some breakpoint in the app source code
- Run the the app the vscode debugger.
- When reaching a breakpoint, it should display a message such as: 
Could not load source 'd:\b\0\193178\Sharpmake\Sharpmake\DebugProjectGenerator.cs': Incorrect format of 'source' message..

## Expected Behavior ##
Debugger should transform the paths so that a corresponding file can be found on the mac in the current workspace. Maybe transform backslashes in slashes and ignore all paths or part of it.

### C# log ###
<details>Post the output from Output-->C# here</details>

### C# LSP Trace Logs ###
<details>Post the output from Output-->C# LSP Trace Logs here.  Requires `dotnet.server.trace` to be set to `Trace`</details>

## Environment information ##

**VSCode version**: 1.90.0
**C# Extension**: 2.31.19
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:           8.0.301
 Commit:            1a0e9c0300
 Workload version:  8.0.300-manifests.f6879a9a
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.5
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.301/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.6
  Architecture: arm64
  Commit:       3b8b000a0e

.NET SDKs installed:
  6.0.422 [/usr/local/share/dotnet/sdk]
  6.0.423 [/usr/local/share/dotnet/sdk]
  7.0.410 [/usr/local/share/dotnet/sdk]
  8.0.301 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.30 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.31 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.30 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.31 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]
    registered at [/etc/dotnet/install_location_x64]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|csdevkit|ms-dotnettools|1.6.8|ms-dotnettools.csdevkit-1.6.8-darwin-arm64|
|csharp|ms-dotnettools|2.31.19|ms-dotnettools.csharp-2.31.19-darwin-arm64|
|remote-explorer|ms-vscode|0.4.3|ms-vscode.remote-explorer-0.4.3|
|remote-ssh|ms-vscode-remote|0.110.1|ms-vscode-remote.remote-ssh-0.110.1|
|remote-ssh-edit|ms-vscode-remote|0.86.0|ms-vscode-remote.remote-ssh-edit-0.86.0|
|vscode-dotnet-runtime|ms-dotnettools|2.0.5|ms-dotnettools.vscode-dotnet-runtime-2.0.5|
|vscode-xml|redhat|0.27.1|redhat.vscode-xml-0.27.1-darwin-arm64|;

</details>

**Comment by WardenGnaw** [comment]
@jspelletier Can you add a `sourceFileMap` section to your `launch.json`?
```json
{
   "program": ....,
   "sourceFileMap": {
      "d:\\b\\0\\193178\\Sharpmake\\Sharpmake\\": "<Path-to-Sharpmake-on-macOS>"
   }
}
```

This will help the debugger map from the Windows path to the macOS path. 

Let me know if this fixes your issue.

![image](https://github.com/dotnet/vscode-csharp/assets/3953714/24e15122-c664-4749-8fe5-4c0aab3a4f26)

**Comment by jspelletier** [comment]
Hi,
The following works perfectly:
            "sourceFileMap": {
      "d:\\b\\0\\193178\\": "/Users/jspelletier/gitlab/sharpmakeextended"
            }
            
Thanks a lot!

**Comment by jspelletier** [comment]
@WardenGnaw Even if I closed it, I would like to know if we can specify wildcards or something like that in the left part of the path.
