### ISSUE TITLE
IntelliSense and code analysis broken with 2.33.17

### ISSUE THREAD

**Issue by austin-beer** [dotnet/vscode-csharp#7231]
Type: <b>Bug</b>

## Issue Description ##
After upgrading to 2.33.17, Intellisense and code analysis appears to be broken for all of my C# projects. The error occurs at some point while the language server is processing my workspace, since some code has obviously been analyzed and some has not.

Downgrading to the previous version fixes the issue.

## Logs ##
I turned on dotnet.server.trace, restarted VS Code, and loaded one of my C# workspaces. The associated logs are here: [20240613T074614.zip](https://github.com/user-attachments/files/15818718/20240613T074614.zip).

## Environment information ##

**VSCode version**: 1.90.0
**C# Extension**: 2.33.17
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:           8.0.300
 Commit:            326f6e68b2
 Workload version:  8.0.300-manifests.818b3449
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.300\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.5
  Architecture: x64
  Commit:       087e15321b

.NET SDKs installed:
  8.0.204 [C:\Program Files\dotnet\sdk]
  8.0.205 [C:\Program Files\dotnet\sdk]
  8.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|cmake|twxs|0.0.17|twxs.cmake-0.0.17|
|cmake-tools|ms-vscode|1.18.42|ms-vscode.cmake-tools-1.18.42|
|cpptools|ms-vscode|1.20.5|ms-vscode.cpptools-1.20.5-win32-x64|
|cpptools-extension-pack|ms-vscode|1.3.0|ms-vscode.cpptools-extension-pack-1.3.0|
|cpptools-themes|ms-vscode|2.0.0|ms-vscode.cpptools-themes-2.0.0|
|csdevkit|ms-dotnettools|1.7.25|ms-dotnettools.csdevkit-1.7.25-win32-x64|
|csharp|ms-dotnettools|2.33.17|ms-dotnettools.csharp-2.33.17-win32-x64|
|debugpy|ms-python|2024.6.0|ms-python.debugpy-2024.6.0-win32-x64|
|gitlens|eamodio|15.1.0|eamodio.gitlens-15.1.0|
|hexeditor|ms-vscode|1.10.0|ms-vscode.hexeditor-1.10.0|
|intellicode-api-usage-examples|VisualStudioExptTeam|0.2.8|visualstudioexptteam.intellicode-api-usage-examples-0.2.8|
|java|redhat|1.31.0|redhat.java-1.31.0-win32-x64|
|javadoc-tools|madhavd1|1.6.0|madhavd1.javadoc-tools-1.6.0|
|jupyter-keymap|ms-toolsai|1.1.2|ms-toolsai.jupyter-keymap-1.1.2|
|plantuml|jebbs|2.18.1|jebbs.plantuml-2.18.1|
|powershell|ms-vscode|2024.2.2|ms-vscode.powershell-2024.2.2|
|pylint|ms-python|2023.10.1|ms-python.pylint-2023.10.1|
|python|ms-python|2024.8.0|ms-python.python-2024.8.0|
|rainbow-csv|mechatroner|3.12.0|mechatroner.rainbow-csv-3.12.0|
|remote-containers|ms-vscode-remote|0.369.0|ms-vscode-remote.remote-containers-0.369.0|
|remote-explorer|ms-vscode|0.4.3|ms-vscode.remote-explorer-0.4.3|
|remote-server|ms-vscode|1.5.1|ms-vscode.remote-server-1.5.1|
|remote-ssh|ms-vscode-remote|0.110.1|ms-vscode-remote.remote-ssh-0.110.1|
|remote-ssh-edit|ms-vscode-remote|0.86.0|ms-vscode-remote.remote-ssh-edit-0.86.0|
|remote-wsl|ms-vscode-remote|0.88.2|ms-vscode-remote.remote-wsl-0.88.2|
|rewrap|stkb|1.16.3|stkb.rewrap-1.16.3|
|sonarlint-vscode|SonarSource|4.6.0|sonarsource.sonarlint-vscode-4.6.0-win32-x64|
|vim|vscodevim|1.27.3|vscodevim.vim-1.27.3|
|vscode-better-align|chouzz|1.4.2|chouzz.vscode-better-align-1.4.2|
|vscode-docker|ms-azuretools|1.29.1|ms-azuretools.vscode-docker-1.29.1|
|vscode-dotnet-runtime|ms-dotnettools|2.0.6|ms-dotnettools.vscode-dotnet-runtime-2.0.6|
|vscode-java-debug|vscjava|0.57.0|vscjava.vscode-java-debug-0.57.0|
|vscode-java-dependency|vscjava|0.23.6|vscjava.vscode-java-dependency-0.23.6|
|vscode-java-pack|vscjava|0.27.0|vscjava.vscode-java-pack-0.27.0|
|vscode-java-test|vscjava|0.41.1|vscjava.vscode-java-test-0.41.1|
|vscode-maven|vscjava|0.44.0|vscjava.vscode-maven-0.44.0|
|vscode-pylance|ms-python|2024.6.1|ms-python.vscode-pylance-2024.6.1|
|vscode-remote-extensionpack|ms-vscode-remote|0.25.0|ms-vscode-remote.vscode-remote-extensionpack-0.25.0|
|vscodeintellicode|VisualStudioExptTeam|1.3.1|visualstudioexptteam.vscodeintellicode-1.3.1|
|vscodeintellicode-csharp|ms-dotnettools|2.1.11|ms-dotnettools.vscodeintellicode-csharp-2.1.11-win32-x64|;

</details>

Extension version: 2.33.17
VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.76GB (41.66GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/austin.beer/Documents/openspace/openspace-service-ocs --crash-reporter-id 0c6b83c6-0278-4f0a-8c4c-af4a645e9c74|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870

```

</details>

**Comment by skyshaver** [comment]
Me too, worked fine all day yesterday today I just have walls of yellow and red lines on a project that builds and runs without errors, this constant churn of functionality is incredibly frustrating

**Comment by ikrammert** [comment]
I have the same problem, I change back the version and works fine.

**Comment by chpoit** [comment]
The pre-release (2.34.10) version seems to fix this too

**Comment by dibarbet** [comment]
A couple followup questions to anyone hitting this
1.  Is this occuring in all your solutions, or just certain ones?  If only in certain ones, would you be able to share them?  My microsoft email is dabarbet@microsoft.com if you'd prefer to share privately.
2.  Are you using C# Dev Kit, or C# standalone?  If using DevKit, are you seeing all your projects loaded correctly in the sln explorer?
3.  Would you mind sharing info on what additional errors/warnings you're seeing?  E.g. a screenshot of the new error details

**Comment by Jaswanth-Sriram-Veturi** [comment]
+1. I am using C# Dev Kit (v1.7.27) and experienced same problem. Rolling back to previous version fixed the issue.

**Comment by babula38** [comment]
Same here but the version is different.

Working: 2.34.10
Not working version: 2.34.12, 2.35.15

**Comment by babula38** [comment]
> A couple followup questions to anyone hitting this
> 
> 1. Is this occuring in all your solutions, or just certain ones?  If only in certain ones, would you be able to share them (and what kind of projects are they)?  My microsoft email is [dabarbet@microsoft.com](mailto:dabarbet@microsoft.com) if you'd prefer to share privately.
> 2. Are you using C# Dev Kit, or C# standalone?  If using DevKit, which version, and are you seeing all your projects loaded correctly in the sln explorer?
> 3. Would you mind sharing info on what additional errors/warnings you're seeing?  E.g. a screenshot of the new error details

Below are my points for my issue:
1) It is happing for a typical 3 tier asp Netcore 7 web Api application.
2) With C# Dev Kit.
3) Giving random error like "Method not found", "Task<> not found etc", Unbale to detect all the methods of any interface.

**Comment by babula38** [comment]
I got the below logs when I restart 

![image](https://github.com/dotnet/vscode-csharp/assets/4153708/233ea896-8d07-45b5-b26d-83ab75762b3a)

**Comment by dibarbet** [comment]
This is most likely fixed by https://github.com/dotnet/roslyn/pull/74189 .  I will reply back here once it hits the marketplace.

**Comment by babula38** [comment]
Is this fix released @dibarbet?

**Comment by dibarbet** [comment]
> Is this fix released @dibarbet?

Not yet, will post as soon as it is available.  Having some integration issues, but hopefully next week's release will have it.

**Comment by dibarbet** [comment]
2.39.28 prerelease version of the C# extension is now available which should fix this issue.  Please try it out and let me know if you still have issues

**Comment by babula38** [comment]
I confirm it is working for me now with the above release.
