### ISSUE TITLE
MSB4057 error

### ISSUE THREAD

**Issue by manishgupta31286** [dotnet/vscode-csharp#7235]
Type: <b>Bug</b>

I am trying to start debugging in VS Code C# project. My project has this sln with A.B.C.sln.
However, dotnet build command in the start debugging is converting . to _ and generating this command as below
Notice how it is converting target . to _

dotnet build A.B.C.sln /target:A_B_C_API /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary /p:Configuration=Debug /p:Platform="Any CPU"

so this is causing error message 

error MSB4057: The target "A_B_C_API" does not exist in the project.

Please fix and let me know if I am missing any settings. This issue started from yesterday.

Extension version: 2.33.17
VS Code version: Code 1.90.1 (611f9bfce64f25108829dd295f54a6894e87339d, 2024-06-11T21:01:24.262Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupyter:31046869
newcmakeconfigv2:31071590

```

</details>

**Comment by AlexanderInova** [comment]
Same issue here. I don't get the whole point of the issued command. Why should "building a project" try to build the whole solution and specifying a target with the name the project to start? It seems quite obvious that this target will at least not exist in any other project...

**Comment by WardenGnaw** [comment]
Closing this issue as https://github.com/microsoft/vscode-dotnettools/issues/1195 has been resolved.

Please update the C# Dev Kit extension to either the v1.7.27 release or v1.8.6 prerelease.
