### ISSUE TITLE
Microsoft.CodeAnalysis.LanguageServer Client: Couldn't create connection with server

### ISSUE THREAD

**Issue by AbdulRahman-Muhammad** [dotnet/vscode-csharp#7242]
I have error in VS Code for Windows 10 with Dotnet C# 8,

### Installed extensions:
C# Dev Kit
C#
And other dependencies

Platform: **Windows 10**
## dotnet path in whole program is one: **C:/Program Files (x86)/dotnet/**

**All extensions are activated.**
**In some issues i saw that pipe got after error, but it won't in my case.**

**Comment by johnslander** [comment]
Im having this same error, did you fix it?

**Comment by AbdulRahman-Muhammad** [comment]
> Im having this same error, did you fix it?

Yes, in settings of C# extension, i have deleted the text in dotnet server path, then opened internet and the .NET Install Tool has installed the lsp after one minute approximately the server responded with the pipe.

(Optional) In output i have to take the path of installed server, then put it in the dotnet server path.

**Comment by johnslander** [comment]
> > Im having this same error, did you fix it?
> 
> Yes, in settings of C# extension, i have deleted the text in dotnet server path, then opened internet and the .NET Install Tool has installed the lsp after one minute approximately the server responded with the pipe.
> 
> (Optional) In output i have to take the path of installed server, then put it in the dotnet server path.

I fixed it last night thanks to this video, https://www.youtube.com/watch?v=sIvffun8ueo
