### ISSUE TITLE
project.json file schema warnings

### ISSUE THREAD

**Issue by 5cover** [dotnet/vscode-csharp#7243]
### Describe the bug.

I understand that a file named `project.json` may have some significance if the extension enforces a schema on it, but an option to disable this behavior would be nice.

I have a file named `project.json` that is not related to .NET in any way in my workspace and the extension creates false positive warnings on it.

### Please attach log file(s) here if you have any.

(no logs)

### Reproduction Steps

Create a file named project.json in the current workspace which does not respect the expected schema.

### Expected Behavior

No warning is shown

### Exceptions & Errors (if any)

JSON schema warnings on the file such as `incorrect. "object" expected`

### .NET Install Tool Version

v2.0.5

### Your operating system? Please provide more detail, such as the version and or distro above.

Linux

### VS Code Version

1.90.0

**Comment by nagilson** [comment]
Your feedback is certainly valued, just need to make sure it goes to the right place ;)

**Comment by dibarbet** [comment]
The warnings appear to be enabled by this - https://github.com/dotnet/vscode-csharp/blob/main/package.json#L1868

I don't see a way for an extension to conditionally enable these unfortunately.  However I don't think `project.json` is supported anymore so maybe we can just remove this...
