### ISSUE TITLE
Couldn't find .NET SDK

### ISSUE THREAD

**Issue by fhchina** [dotnet/vscode-csharp#7263]
Failed to find dotnet info from path, falling back to acquire runtime via ms-dotnettools.vscode-dotnet-runtime
Error running dotnet --info: Error: Command failed: dotnet --info
/bin/sh: dotnet: command not found

/bin/sh: dotnet: command not found

找不到 .NET Core SDK 的位置：Error running dotnet --info: Error: Command failed: dotnet --info
/bin/sh: dotnet: command not found

/bin/sh: dotnet: command not found
。将不会启用 .NET Core 调试。请确保已安装 .NET Core SDK 且该 SDK 位于路径上。
Dotnet path: /Users/fanghao/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/8.0.6~x64/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
waiting for named pipe information from server...
[stdout] {"pipeName":"/var/folders/04/c4nd13y54pl5mg5wh_m9ymsm0000gn/T/aba24618.sock"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 11:02:08] [Program] Language server initialized

## Environment data
`dotnet --info` output:
.NET SDK:
 Version:           8.0.302
 Commit:            ef14e02af8
 Workload version:  8.0.300-manifests.8baf0524
 MSBuild version:   17.10.4+10fbfbf2e

运行时环境:
 OS Name:     Mac OS X
 OS Version:  14.2
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.302/

已安装 .NET 工作负载:
没有要显示的已安装工作负载。

Host:
  Version:      8.0.6
  Architecture: x64
  Commit:       3b8b000a0e

.NET SDKs installed:
  2.2.207 [/usr/local/share/dotnet/sdk]
  6.0.417 [/usr/local/share/dotnet/sdk]
  7.0.201 [/usr/local/share/dotnet/sdk]
  7.0.400 [/usr/local/share/dotnet/sdk]
  8.0.100 [/usr/local/share/dotnet/sdk]
  8.0.203 [/usr/local/share/dotnet/sdk]
  8.0.302 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.25 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.25 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

VS Code version:

版本: 1.90.1 (Universal)
提交: 611f9bfce64f25108829dd295f54a6894e87339d
日期: 2024-06-11T21:02:41.372Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin x64 23.2.0

C# Extension version:

## Steps to reproduce

Open any C# project with Visual Studio Code, don't need to do anything.

## Additional context

I am using zsh. but I aslo configured bash's bash_profile for PATH,

**Comment by fhchina** [comment]
I can use dotnet cli correctly. But C# Dev Kit doesn't work in Visual Studio Code.

**Comment by fhchina** [comment]
C# Dev Kit version: v1.7.27

**Comment by fhchina** [comment]
Now jump to definiton doesn't work.

**Comment by elir-castro** [comment]
same here, dev kit just stopped working
