### ISSUE TITLE
Error when Building C# Extension in VS Code on Windows with Node v20.14

### ISSUE THREAD

**Issue by YogiCoder8888** [dotnet/vscode-csharp#7282]
I am having problems compiling and debugging the extension in VS Code using the "Launch Extension" config.

I am running Windows 11 with VS Code 1.90.2 with node version 20.14.0

I get the following error.

```
Error: bad export type for `tree_sitter_tsx_external_scanner_create`: undefined
    at reportUndefinedSymbols (D:\codium\vscsharp\main\node_modules\web-tree-sitter\tree-sitter.js:1:19748)
    at postInstantiation (D:\codium\vscsharp\main\node_modules\web-tree-sitter\tree-sitter.js:1:17027)
    at D:\codium\vscsharp\main\node_modules\web-tree-sitter\tree-sitter.js:1:17752
    at async D:\codium\vscsharp\main\node_modules\@vscode\l10n-dev\dist\cli.js:335:10
```

Any help will be appreciated. TIA

**Comment by WardenGnaw** [comment]
I also ran into this, one workaround I had was to downgrade using `nfm` to Node v18.20.3
```
# installs fnm (Fast Node Manager)
winget install Schniz.fnm
# download and install Node.js
fnm use --install-if-missing 18
# verifies the right Node.js version is in the environment
node -v # should print `v18.20.3`
# verifies the right NPM version is in the environment
npm -v # should print `10.7.0`
```
See https://nodejs.org/en/download/package-manager

**Comment by dibarbet** [comment]
Yes, please us 18.20 for development.  See https://github.com/dotnet/vscode-csharp/blob/main/CONTRIBUTING.md#prerequisites-for-development

I expect we will move to 20 at some point, but it hasn't happened yet.  Closing this for now.
