### ISSUE TITLE
active debug config changes after .Net Aspire AppHost exits unexpectedly

### ISSUE THREAD

**Issue by burtonrodman** [dotnet/vscode-csharp#7388]
Type: <b>Bug</b>

1.  add several project repos to a vscode workspace
2.  add a .Net Aspire project repo to the workspace (AppHost and ServiceDefaults)
3.  add project references to the AppHost and configure projects in AppHost/Program.cs
4.  add a MigrationService project (ala https://learn.microsoft.com/en-us/dotnet/aspire/database/ef-core-migrations) and reference it in AppHost/Program.cs
5.  select the Aspire project debug config and start debugging
6.  the MigrationService exits, the AppHost dies and debugging mode exits
7.  make some code changes (to prevent the MigrationService from exiting)
8.  hit F5, and realize it has started debugging another random debug profile (not the Aspire AppHost).  sigh.

Extension version: 2.39.29
VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22635
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (11.08GB free)|
|Process Argv|. --crash-reporter-id 1a93c41b-7666-47c2-a630-9537bdc67cc3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31101459
pythonrstrctxtcf:31093870
wkspc-onlycs-c:31102393

```

</details>

**Comment by WardenGnaw** [comment]
@burtonrodman I am moving this issue to https://github.com/microsoft/vscode-dotnettools/issues/1307 as .NET Aspire is mostly handled by the C# Dev Kit extension.
