### ISSUE TITLE
[BUG] customRequest stackTrace does not return correct value

### ISSUE THREAD

**Issue by WardenGnaw** [dotnet/vscode-csharp#7397]
### Describe the Issue

Calling `debug.activeDebugSession.customRequest('stackTrace')` fails with ```message =
'Incorrect format of stacktrace message.'
name =
'CodeExpectedError'```

![image](https://github.com/user-attachments/assets/d668946b-73e9-474b-af74-6a4cd8c94178)

Left - example extension that wants to request the stack trace 
Right - example code to debug.

1. 

### Steps To Reproduce

1. Start a debug session
2. Inside an extension, use debug.activeDebugSession.customRequest('stackTrace', [...])
3. Error gets thrown.

Example Extension code:

```typescript
export function activate(context: ExtensionContext) {
  debug.onDidChangeActiveStackItem(async () => {
    try {
      const stack = await debug.activeDebugSession?.customRequest('stackTrace', { threadId: debug.activeStackItem?.threadId ?? 1 });
      console.log(stack);
    } catch (error: any) {
      window.showErrorMessage("Error " + error);
    }
  });
}
```

### Expected Behavior

I can query the stack trace without issues.

### Environment Information

Windows (wsl/ubuntu and native)
--------------
Originally by @K0IN at https://github.com/microsoft/vscode-dotnettools/issues/1316

**Comment by K0IN** [comment]
might also be related to https://github.com/dotnet/vscode-csharp/issues/4842

**Comment by gregg-miskelly** [comment]
I believe you can work around this by specifying `"startFrame":0`

**Comment by K0IN** [comment]
I will try, but I still think it's a bug since the official dap documentation, states

```  
/**
   * The index of the first frame to return; if omitted frames start at 0.
   */
  startFrame?: number;
```

**Comment by K0IN** [comment]
Okay when supplying, startFrame = 0 it seems to work as expected, thank you for the quick help @gregg-miskelly.

Although i think this should still be fixed.

**Comment by gregg-miskelly** [comment]
Agreed. I am not sure why our code requires `startFrame`, but I am guessing it is just because VS Code always provides it and this code was written before the `customRequest` API even existed.
