### ISSUE TITLE
Unable to get working directory for project Miscellaneous Files

### ISSUE THREAD

**Issue by Kjarar** [dotnet/vscode-csharp#7404]
I am currently working with VSCode on Windows. I have one folder opened in my workspace which contains several projects. Since we build the projects for net8.0 AND net481, I use the setting `"dotnet.preferCSharpExtension": true` for my workspace. I have not changed any other settings (neither for user, workspace or folder). I have C# extension v2.39.29 installed.

In my test projects, which use MSTest, I can click the little buttons `Run all tests`/`Debug all tests`/`Run test`/`Debug test` and they work - i.e. after clicking them the projects needed for these tests are built, then the tests are run/debugged.

In order to nail down some issue, I wanted to make a copy of a given test project, then remove content subsequentially. So I copied the test project folder, put it in the main folder, gave it a new name. I can run the new test project with dotnet test. But when I click any of the little run/debug buttons, I just get the output

`Error: Unable to get working directory for project Miscellaneous Files - file RunTestsHandler.cs line 124`

in my .NET Test log.

I already tried restarting the language server, closing and reopening VScode, restarting Windows, uninstalling and reinstalling C# Dev Kit. None helped.

What else can I do?

---

I noticed that the colors in the code differ between the working test project (left) and the new non-working one (right). I can hover over the greenish text and get some popup. In the non-working one I have less greenish text. This indicates that something was not loaded.

![pB43pQjf](https://github.com/user-attachments/assets/d4181ecf-4770-45bb-9084-8acbc54bd94f)

---

Here is the information asked for in a [similar issue](https://github.com/dotnet/vscode-csharp/issues/6019#issuecomment-1703651633):
1. See [log.txt](https://github.com/user-attachments/files/16424303/log.txt).
2. see above.
3. Does not apply.

In the log in lines 553-568, projects are loaded. That lists consists of all projects that were inside my main folder before
- I created the new test project (TestTest) as a copy of a given one (Update2Test) and
- deleted some project folders that are not relevant here (e.g. UpdateData).
So it loads projects that do not exist (because I moved their folder to trash) but does not load projects that exist. So it clearly does not use the current file situation for determining what to load, but something else.

In fact, the ones that are loaded are exactly the ones inside my `.sln` file in the main folder. Is that the issue? Does the C# extension consider the `.sln` file? I thought `.sln` files are just for Visual Studio and VScode/C# only considers `.csproj` files.

---

See also [StackOverflow](https://stackoverflow.com/questions/78810115) (same issue posted there).

**Comment by Kjarar** [comment]
> In fact, the ones that are loaded are exactly the ones inside my .sln file in the main folder. Is that the issue? Does the C# extension consider the .sln file? I thought .sln files are just for Visual Studio and VScode/C# only considers .csproj files.

Yes, that seems to be the issue. If I add the new project to the solution and restart VScode (or Language Server), everything gets loaded and I can test/debug the new test project.

It seems I missed something - when I started using VScode, I could read everywhere that `.sln` files were a Visual-Studio-only thing and that it'd be a good thing VScode moved away from that concept and only considered `.csproj` files. So I just dragged along the `.sln` file for my colleagues who prefer Visual Studio, but never gave it any thought since I moved to VSCode.

**Comment by JoeRobich** [comment]
Hi @Kjarar, It is by design that the C# extension uses a solution file when one is present. In the absence of a solution file, the C# extension will load project files but there is not a way to enable that behavior when a solution file is present. 

We do have an issue on the backlog to support "Load projects on demand" which would ignore a solution file and instead open project files. You can track that feature at https://github.com/dotnet/vscode-csharp/issues/6008
