### ISSUE TITLE
Use diff test explorer rendering on assert failures

### ISSUE THREAD

**Issue by rmannibucau** [dotnet/vscode-csharp#7410]
## Is your feature request related to a problem? Please describe.
When running a test (xunit or nunit) the assert failures are poorly readable when one liners and impossible to use when > 1 line.

## Describe the solution you would like
There is a new vscode API to show the "diff" side by side so it would be neat to use that instead of just the runner output (see https://github.com/microsoft/vscode-java-test/issues/1070 for the kind of view which could help).

## Applicable Scenarios
Anytime an assert fails comparing two values.

## Describe alternatives you've considered
Rewrite all the asserts to extract the two values (either in files or in debug mode).

(indeed it is not satisfying)

**Comment by dibarbet** [comment]
@rmannibucau are you using C# DevKit, or just the C# extension standalone?

**Comment by rmannibucau** [comment]
@dibarbet dev kit is installed

**Comment by dibarbet** [comment]
Got it- I filed https://github.com/microsoft/vscode-dotnettools/issues/1330 to track this request on the DevKit side since it is responsible for the test explorer and running tests.
