### ISSUE TITLE
Roslyn LSP isn't reporting CS8019 (Unused Usings)

### ISSUE THREAD

**Issue by jeremy-allocate** [dotnet/vscode-csharp#7416]
Type: <b>Bug</b>

1. Ensure the C# extension is installed, the C# Dev Kit extension is NOT installed, and that you have `"dotnet.server.useOmnisharp": false` set in your settings to ensure the Roslyn LSP will be used.
2. Open any class and add an unused using.  Optionally save the file.
3. Notice the unused using is never grayed out, even if you restart vscode.

Extension version: 2.39.29
VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12800H (20 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.67GB (6.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|12th Gen Intel(R) Core(TM) i7-12800H (20 x 0)|
|Memory (System)|15.62GB (12.54GB free)|
|VM|0%|
</details>

**Comment by JoeRobich** [comment]
@jeremy-allocate Can you please share the C# log from the output pane?

**Comment by jeremy-allocate** [comment]
Absolutely, here's what I see in the log when I start with an empty log and then add the unused using (the first project load) and then save the file (the second project load):

> [Info  - 7:48:07 PM] [LanguageServerProjectSystem] Successfully completed load of /[snipped].Web.Api.csproj
> [Info  - 7:48:07 PM] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:04.3638689
> [Info  - 7:48:14 PM] [LanguageServerProjectSystem] Successfully completed load of /[snipped].Web.Api.csproj
> [Info  - 7:48:14 PM] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:03.6864735

Here's what the log had otherwise: [c#-log.txt](https://github.com/user-attachments/files/16476808/c.-log.txt)

Nothing interesting in the C# LSP trace log fwiw, just a lot of `Extension X does not contribute csharpExtensionLoadPaths` messages.

**Comment by JoeRobich** [comment]
@jeremy-allocate If you hover or click on the `{ }` next to the C# in the status bar you should see a pop-up that shows the Active File Context. Is the context for the file where you are seeing this not being reported, the project which you expect it to belong to?


![Image](https://github.com/user-attachments/assets/3cf3f728-f1d3-44e5-9a03-7b05abd1e053)

**Comment by jeremy-allocate** [comment]
Yes, the project I see here contains the file I'm editing, and that's the same project as shown in the two log messages in the comment above.

**Comment by JoeRobich** [comment]
Does your solution use an .editorconfig and can you share it?

**Comment by jeremy-allocate** [comment]
Our solution doesn't have an .editorconfig file.

**Comment by JustPlayground** [comment]
For me, it will report IDE0005 rather than CS8019.
![image](https://github.com/user-attachments/assets/8f556a58-20ca-4784-82ac-b740a88cafff)
I dont't know whether it's a feature and it's a bug.

**Comment by jeremy-allocate** [comment]
After much digging here, I seem to have found the problematic user setting I had set somewhere along the way:

    "dotnet.backgroundAnalysis.analyzerDiagnosticsScope": "none"

As soon as I removed this, I started seeing the unused usings grayed out as ccc described above.  But I agree with their statement about not understanding if the switch from CS8019 to IDE0005 is intentional or what the background is there.

I recently started maintaining an extension called "[C# Organize Usings](https://marketplace.visualstudio.com/items?itemName=jeremycaron.csharp-organize-usings)", so I'll update that extension to also handle IDE0005 for Roslyn LSP compatibility.  Thanks to you both.

**Comment by JoeRobich** [comment]
@jeremy-allocate I know Roslyn intentionally substitutes the compiler diagnostic for a code style diagnostic. I am not sure the history on why that is though. 

There are so many ways to disable different diagnostics that it can be difficult to determine why one shows and not another. Glad you got to the bottom of it.
