### ISSUE TITLE
Autocomplete parentheses in intellisense for method call

### ISSUE THREAD

**Issue by ziaulhasanhamim** [dotnet/vscode-csharp#7453]
Most language extensions autocomplete parentheses in vscode. But C# lacks this feature. It would make developers more productive if the Intellisense also added parenthesis and angle brackets while autocompleting methods like rust, go, and other languages.

**Comment by JoeRobich** [comment]
@ziaulhasanhamim Just to be sure that I understand the ask, since parentheses are already in the list of autocompleted brace pairs, when taking the completion item `WriteLine` for `Console.WriteL$` you would like the resulting code to be `Console.WriteLine()`.

**Comment by ziaulhasanhamim** [comment]
Yes. When auto completing a method it should add parentheses and reposition the cursor between the parenthases.

**Comment by JoeRobich** [comment]
This feature is being tracked by the Roslyn issue https://github.com/dotnet/roslyn/issues/55085.

**Comment by JoeRobich** [comment]
Closing as duplicate of https://github.com/dotnet/roslyn/issues/55085.
