### ISSUE TITLE
Projects not loading using pre-release extensions

### ISSUE THREAD

**Issue by spouliot** [dotnet/vscode-csharp#7455]
Type: <b>Bug</b>

## Steps to Reproduce ##

git clone https://github.com/yeahg-dev/VSCodeWorkspaceTaskTest
code VSCodeWorkspaceTaskTest

## Expected Behavior ##

Projects are loaded.

note: this works with the current stable release of the extensions
* C# Extension: 'ms-dotnettools.csharp' version 2.39.29
* C# Dev Kit Extension: 'ms-dotnettools.csdevkit' version 1.9.55

## Actual Behavior ##

The "Projects:" label (on the status bar) keeps spinning (when using the latest pre-release extensions)
* C# Extension: 'ms-dotnettools.csharp' version 2.43.16
* C# Dev Kit Extension: 'ms-dotnettools.csdevkit' version 1.10.6

### ~~OmniSharp~~ C# DevKit log ###

There's no OmniSharp logs available (DevKit mode)

<details>
Starting Spawn .NET server...
Starting opening a solution...
Starting processing the solution file "/Users/poupou/git/external/yeahg-dev/VSCodeWorkspaceTaskTest/DrawerControlSafeAreaTest.Mobile/DrawerControlSafeAreaTest.Mobile.sln" in Dev Kit server...
#getSession: Failed to running method. Error: 'Canceled: Canceled'
#getSession: Failed to running method. Error: 'Canceled: Canceled'
#getSession: Failed to running method. Error: 'Canceled: Canceled'
Using preinstalled .NET runtime at "/usr/local/share/dotnet/dotnet" to load Dev Kit processes.
Found installed dotnet location "/usr/local/share/dotnet/dotnet" to load projects.
Project system hosting process will use runtime installed in SDK.
.NET server started and IPC established in 1373ms
Completed Spawn .NET server (1707ms)
Completed processing the solution file "/Users/poupou/git/external/yeahg-dev/VSCodeWorkspaceTaskTest/DrawerControlSafeAreaTest.Mobile/DrawerControlSafeAreaTest.Mobile.sln" in Dev Kit server (2149ms)
Starting restoring NuGet packages...
Selected configuration: <Default>, active configuration: Debug|Any CPU
Completed opening a solution (2150ms)
Starting command: "dotnet" restore /Users/poupou/git/external/yeahg-dev/VSCodeWorkspaceTaskTest/DrawerControlSafeAreaTest.Mobile/DrawerControlSafeAreaTest.Mobile.sln --interactive...
Completed command: "dotnet" restore /Users/poupou/git/external/yeahg-dev/VSCodeWorkspaceTaskTest/DrawerControlSafeAreaTest.Mobile/DrawerControlSafeAreaTest.Mobile.sln --interactive (2203ms)
Completed restoring NuGet packages (2204ms)
</details>
        
### C# log ###
<details>
Using dotnet configured on PATH
Dotnet path: /usr/local/share/dotnet/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
waiting for named pipe information from server...
[stdout] {"pipeName":"/var/folders/w_/zfvfxj_x3nbd8wlj9p4ck3xc0000gn/T/74e521ad.sock"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 10:50:33 AM] [Program] Language server initialized
[Info  - 10:50:36 AM] [WorkspaceProjectFactoryService] Project /Users/poupou/git/external/yeahg-dev/VSCodeWorkspaceTaskTest/DrawerControlSafeAreaTest.Mobile/DrawerControlSafeAreaTest.Mobile.csproj loaded by C# Dev Kit
[Info  - 10:50:36 AM] [WorkspaceProjectFactoryService] Project /Users/poupou/git/external/yeahg-dev/VSCodeWorkspaceTaskTest/DrawerControlSafeAreaTest.Mobile/DrawerControlSafeAreaTest.Mobile.csproj loaded by C# Dev Kit
Using dotnet configured on PATH
</details>

## Environment information ##

**VSCode version**: 1.92.2
**C# Extension**: 2.43.16
**Using OmniSharp**: true

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:           9.0.100-preview.6.24328.19
 Commit:            ef4c241666
 Workload version:  9.0.100-manifests.34ad842f
 MSBuild version:   17.11.0-preview-24318-05+4a45d5633

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.6
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/9.0.100-preview.6.24328.19/

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [ios]
   Installation Source: SDK 9.0.100-preview.6
   Manifest Version:    17.2.9714-net9-p6/9.0.100-preview.6
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/9.0.100-preview.6/microsoft.net.sdk.ios/17.2.9714-net9-p6/WorkloadManifest.json
   Install Type:        FileBased

 [android]
   Installation Source: SDK 9.0.100-preview.6
   Manifest Version:    34.99.0-preview.6.340/9.0.100-preview.6
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/9.0.100-preview.6/microsoft.net.sdk.android/34.99.0-preview.6.340/WorkloadManifest.json
   Install Type:        FileBased

 [wasm-tools-net8]
   Installation Source: SDK 9.0.100-preview.6
   Manifest Version:    9.0.0-preview.6.24327.7/9.0.100-preview.6
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/9.0.100-preview.6/microsoft.net.workload.mono.toolchain.net8/9.0.0-preview.6.24327.7/WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      9.0.0-preview.6.24327.7
  Architecture: arm64
  Commit:       static

.NET SDKs installed:
  6.0.100 [/usr/local/share/dotnet/sdk]
  6.0.101 [/usr/local/share/dotnet/sdk]
  6.0.200 [/usr/local/share/dotnet/sdk]
  6.0.201 [/usr/local/share/dotnet/sdk]
  6.0.202 [/usr/local/share/dotnet/sdk]
  6.0.203 [/usr/local/share/dotnet/sdk]
  6.0.300 [/usr/local/share/dotnet/sdk]
  6.0.301 [/usr/local/share/dotnet/sdk]
  6.0.402 [/usr/local/share/dotnet/sdk]
  6.0.403 [/usr/local/share/dotnet/sdk]
  6.0.406 [/usr/local/share/dotnet/sdk]
  7.0.100-rc.2.22477.23 [/usr/local/share/dotnet/sdk]
  7.0.100 [/usr/local/share/dotnet/sdk]
  7.0.103 [/usr/local/share/dotnet/sdk]
  7.0.305 [/usr/local/share/dotnet/sdk]
  7.0.400 [/usr/local/share/dotnet/sdk]
  7.0.401 [/usr/local/share/dotnet/sdk]
  8.0.100-preview.3.23178.7 [/usr/local/share/dotnet/sdk]
  8.0.100-preview.5.23303.2 [/usr/local/share/dotnet/sdk]
  8.0.100-preview.7.23376.3 [/usr/local/share/dotnet/sdk]
  8.0.100 [/usr/local/share/dotnet/sdk]
  8.0.101 [/usr/local/share/dotnet/sdk]
  8.0.201 [/usr/local/share/dotnet/sdk]
  8.0.300 [/usr/local/share/dotnet/sdk]
  9.0.100-preview.4.24267.66 [/usr/local/share/dotnet/sdk]
  9.0.100-preview.6.24328.19 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.14 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-rc.2.22476.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.3.23177.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.5.23302.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.7.23375.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.4.24267.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.6.24328.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-rc.2.22472.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.3.23174.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.5.23280.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.7.23375.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.4.24266.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.6.24327.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]
    registered at [/etc/dotnet/install_location_x64]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|better-cpp-syntax|jeff-hykin|1.27.1|jeff-hykin.better-cpp-syntax-1.27.1|
|blazorwasm-companion|ms-dotnettools|1.1.4|ms-dotnettools.blazorwasm-companion-1.1.4|
|code-spell-checker|streetsidesoftware|3.0.1|streetsidesoftware.code-spell-checker-3.0.1|
|codesnap|adpyke|1.3.4|adpyke.codesnap-1.3.4|
|cpptools|ms-vscode|1.21.6|ms-vscode.cpptools-1.21.6-darwin-arm64|
|cpptools-extension-pack|ms-vscode|1.3.0|ms-vscode.cpptools-extension-pack-1.3.0|
|cpptools-themes|ms-vscode|2.0.0|ms-vscode.cpptools-themes-2.0.0|
|csdevkit|ms-dotnettools|1.10.6|ms-dotnettools.csdevkit-1.10.6-darwin-arm64|
|csharp|ms-dotnettools|2.43.16|ms-dotnettools.csharp-2.43.16-darwin-arm64|
|debugpy|ms-python|2024.0.0|ms-python.debugpy-2024.0.0-darwin-arm64|
|doxdocgen|cschlosser|1.4.0|cschlosser.doxdocgen-1.4.0|
|github-markdown-preview|bierner|0.3.0|bierner.github-markdown-preview-0.3.0|
|gitlens|eamodio|15.2.3|eamodio.gitlens-15.2.3|
|hexeditor|ms-vscode|1.10.0|ms-vscode.hexeditor-1.10.0|
|ilspy-vscode|icsharpcode|0.19.0|icsharpcode.ilspy-vscode-0.19.0|
|intellicode-api-usage-examples|VisualStudioExptTeam|0.2.8|visualstudioexptteam.intellicode-api-usage-examples-0.2.8|
|isort|ms-python|2023.10.1|ms-python.isort-2023.10.1|
|logcat|abhiagr|0.0.7|abhiagr.logcat-0.0.7|
|markdown-checkbox|bierner|0.4.0|bierner.markdown-checkbox-0.4.0|
|markdown-emoji|bierner|0.3.0|bierner.markdown-emoji-0.3.0|
|markdown-footnotes|bierner|0.1.1|bierner.markdown-footnotes-0.1.1|
|markdown-mermaid|bierner|1.23.1|bierner.markdown-mermaid-1.23.1|
|markdown-preview-github-styles|bierner|2.0.4|bierner.markdown-preview-github-styles-2.0.4|
|markdown-yaml-preamble|bierner|0.1.0|bierner.markdown-yaml-preamble-0.1.0|
|mono-debug|ms-vscode|0.16.3|ms-vscode.mono-debug-0.16.3|
|powershell|ms-vscode|2024.2.2|ms-vscode.powershell-2024.2.2|
|prettier-vscode|esbenp|10.4.0|esbenp.prettier-vscode-10.4.0|
|python|ms-python|2024.0.1|ms-python.python-2024.0.1|
|remote-containers|ms-vscode-remote|0.369.0|ms-vscode-remote.remote-containers-0.369.0|
|remote-explorer|ms-vscode|0.4.3|ms-vscode.remote-explorer-0.4.3|
|remote-server|ms-vscode|1.5.2|ms-vscode.remote-server-1.5.2|
|remote-ssh|ms-vscode-remote|0.113.1|ms-vscode-remote.remote-ssh-0.113.1|
|remote-ssh-edit|ms-vscode-remote|0.86.0|ms-vscode-remote.remote-ssh-edit-0.86.0|
|test-adapter-converter|ms-vscode|0.1.9|ms-vscode.test-adapter-converter-0.1.9|
|vscode|unoplatform|0.15.6|unoplatform.vscode-0.15.6|
|vscode-commons|redhat|0.0.6|redhat.vscode-commons-0.0.6|
|vscode-dash|deerawan|2.4.0|deerawan.vscode-dash-2.4.0|
|vscode-dotnet-runtime|ms-dotnettools|2.1.2|ms-dotnettools.vscode-dotnet-runtime-2.1.2|
|vscode-edit-csv|janisdd|0.9.2|janisdd.vscode-edit-csv-0.9.2|
|vscode-eslint|dbaeumer|3.0.10|dbaeumer.vscode-eslint-3.0.10|
|vscode-il|soltys|0.0.1|soltys.vscode-il-0.0.1|
|vscode-javascript-repl|achil|0.7.4|achil.vscode-javascript-repl-0.7.4|
|vscode-jupyter-cell-tags|ms-toolsai|0.1.8|ms-toolsai.vscode-jupyter-cell-tags-0.1.8|
|vscode-jupyter-slideshow|ms-toolsai|0.1.5|ms-toolsai.vscode-jupyter-slideshow-0.1.5|
|vscode-markdownlint|DavidAnson|0.55.0|davidanson.vscode-markdownlint-0.55.0|
|vscode-nuget-gallery|patcx|1.2.0|patcx.vscode-nuget-gallery-1.2.0|
|vscode-pylance|ms-python|2024.2.2|ms-python.vscode-pylance-2024.2.2|
|vscode-remote-extensionpack|ms-vscode-remote|0.25.0|ms-vscode-remote.vscode-remote-extensionpack-0.25.0|
|vscode-tailscale|Tailscale|1.0.0|tailscale.vscode-tailscale-1.0.0|
|vscode-test-explorer|hbenl|2.21.1|hbenl.vscode-test-explorer-2.21.1|
|vscode-thunder-client|rangav|2.24.13|rangav.vscode-thunder-client-2.24.13|
|vscode-yaml|redhat|1.15.0|redhat.vscode-yaml-1.15.0|
|vscodeintellicode|VisualStudioExptTeam|1.3.1|visualstudioexptteam.vscodeintellicode-1.3.1|
|vscodeintellicode-csharp|ms-dotnettools|2.1.11|ms-dotnettools.vscodeintellicode-csharp-2.1.11-darwin-arm64|
|xml-format|mikeburgh|1.1.3|mikeburgh.xml-format-1.1.3|;

</details>

Extension version: 2.43.16
VS Code version: Code 1.92.2 (Universal) (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|5, 5, 4|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by JoeRobich** [comment]
This is an issue in the C# DevKit project system which is responsible for solution restore. It was introduced in v1.10.6. I have opened https://github.com/microsoft/vscode-dotnettools/issues/1391 to track.

Closing as this is not a C# extension issue.
