### ISSUE TITLE
Blazor web app doesn't hot-reload

### ISSUE THREAD

**Issue by K2adir** [dotnet/vscode-csharp#7461]
## Issue Description ##
Hot-reload doesn't work with Blazor web app, dotnet 8.
## Steps to Reproduce ##

<ul>
    @if (inventories is not null && inventories.Count > 0)
    {
        foreach (var inv in inventories)
        {
            <li>@inv.InventoryName - @inv.Quantity - @inv.Price</li>
<li>place holder</li>
        }
    }
</ul>

I'm adding a placeholder right below the first <li> hitting save, and it doesn't display the new <li> below. I need to restart the server, and dotnet run to see my changes. refreshing the browser doesn't work either.

However, this process works perfectly fine on Visual Studio 2022, which is surprising because VS is known to be garbage with hot reload.. 

## Expected Behavior ##
The second <li> tag should render below the first li after hitting save, but it doesn't
## Actual Behavior ##
The second li tag doesn't render. 
### C# log ###
<details>Post the output from Output-->C# here</details>

### C# LSP Trace Logs ###
<details>Post the output from Output-->C# LSP Trace Logs here.  Requires `dotnet.server.trace` to be set to `Trace`</details>

## Environment information ##

**VSCode version**: 1.92.2
**C# Extension**: 2.39.29
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:           8.0.401
 Commit:            811edcc344
 Workload version:  8.0.400-manifests.56cd0383
 MSBuild version:   17.11.4+37eb419ad

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.401\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [aspire]
   Installation Source: VS 17.11.35208.52
   Manifest Version:    8.1.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.1.0\WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      8.0.8
  Architecture: x64
  Commit:       08338fcaa5

.NET SDKs installed:
  8.0.400 [C:\Program Files\dotnet\sdk]
  8.0.401 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|auto-close-tag|formulahendry|0.5.15|formulahendry.auto-close-tag-0.5.15|
|auto-complete-tag|formulahendry|0.1.0|formulahendry.auto-complete-tag-0.1.0|
|auto-rename-tag|formulahendry|0.1.10|formulahendry.auto-rename-tag-0.1.10|
|cmake|twxs|0.0.17|twxs.cmake-0.0.17|
|cmake-tools|ms-vscode|1.18.44|ms-vscode.cmake-tools-1.18.44|
|code-runner|formulahendry|0.12.2|formulahendry.code-runner-0.12.2|
|continue|Continue|0.8.46|continue.continue-0.8.46-win32-x64|
|csdevkit|ms-dotnettools|1.9.55|ms-dotnettools.csdevkit-1.9.55-win32-x64|
|csharp|ms-dotnettools|2.39.29|ms-dotnettools.csharp-2.39.29-win32-x64|
|csharpextensions|kreativ-software|1.7.3|kreativ-software.csharpextensions-1.7.3|
|csharpier-vscode|csharpier|1.8.0|csharpier.csharpier-vscode-1.8.0|
|data-workspace-vscode|ms-mssql|0.5.0|ms-mssql.data-workspace-vscode-0.5.0|
|dotnet-interactive-vscode|ms-dotnettools|1.0.5229040|ms-dotnettools.dotnet-interactive-vscode-1.0.5229040|
|es7-react-js-snippets|dsznajder|4.4.3|dsznajder.es7-react-js-snippets-4.4.3|
|html-end-tag-labels|anteprimorac|1.0.0|anteprimorac.html-end-tag-labels-1.0.0|
|icons|tal7aouy|3.8.0|tal7aouy.icons-3.8.0|
|jupyter|ms-toolsai|2024.7.0|ms-toolsai.jupyter-2024.7.0-win32-x64|
|jupyter-keymap|ms-toolsai|1.1.2|ms-toolsai.jupyter-keymap-1.1.2|
|jupyter-renderers|ms-toolsai|1.0.19|ms-toolsai.jupyter-renderers-1.0.19|
|live-sass|glenn2223|6.1.2|glenn2223.live-sass-6.1.2|
|LiveServer|ritwickdey|5.7.9|ritwickdey.liveserver-5.7.9|
|mssql|ms-mssql|1.23.0|ms-mssql.mssql-1.23.0|
|one-monokai|azemoh|0.5.2|azemoh.one-monokai-0.5.2|
|prettier-vscode|esbenp|11.0.0|esbenp.prettier-vscode-11.0.0|
|remote-wsl|ms-vscode-remote|0.88.2|ms-vscode-remote.remote-wsl-0.88.2|
|rest-client|humao|0.25.1|humao.rest-client-0.25.1|
|sql-bindings-vscode|ms-mssql|0.4.0|ms-mssql.sql-bindings-vscode-0.4.0|
|sql-database-projects-vscode|ms-mssql|1.4.3|ms-mssql.sql-database-projects-vscode-1.4.3|
|sqlite-viewer|qwtel|0.5.11|qwtel.sqlite-viewer-0.5.11|
|vscode-counter|uctakeoff|3.5.0|uctakeoff.vscode-counter-3.5.0|
|vscode-dotnet-pack|ms-dotnettools|1.0.13|ms-dotnettools.vscode-dotnet-pack-1.0.13|
|vscode-dotnet-runtime|ms-dotnettools|2.1.5|ms-dotnettools.vscode-dotnet-runtime-2.1.5|
|vscode-firefox-debug|firefox-devtools|2.9.10|firefox-devtools.vscode-firefox-debug-2.9.10|
|vscode-html-css|ecmel|2.0.10|ecmel.vscode-html-css-2.0.10|
|vscode-jupyter-cell-tags|ms-toolsai|0.1.9|ms-toolsai.vscode-jupyter-cell-tags-0.1.9|
|vscode-jupyter-slideshow|ms-toolsai|0.1.6|ms-toolsai.vscode-jupyter-slideshow-0.1.6|
|vscode-nuget-gallery|patcx|1.2.1|patcx.vscode-nuget-gallery-1.2.1|
|vscode-react-typescript|infeng|1.3.1|infeng.vscode-react-typescript-1.3.1|
|vscode-scss-formatter|sibiraj-s|3.0.0|sibiraj-s.vscode-scss-formatter-3.0.0|
|vscode-sqlite|alexcvzz|0.14.1|alexcvzz.vscode-sqlite-0.14.1|
|vscode-theme-onedark|akamud|2.3.0|akamud.vscode-theme-onedark-2.3.0|
|vscode-typescript-next|ms-vscode|5.7.20240820|ms-vscode.vscode-typescript-next-5.7.20240820|
|vscodeintellicode-csharp|ms-dotnettools|2.1.11|ms-dotnettools.vscodeintellicode-csharp-2.1.11-win32-x64|;

</details>

**Comment by JoeRobich** [comment]
Thanks for reporting. Blazor hot-reload not working is being tracked by https://github.com/microsoft/vscode-dotnettools/issues/724

Closing as this is a C# DevKit bug with a tracking issue.
