### ISSUE TITLE
Introduce local variable refactoring should allow var keyword

### ISSUE THREAD

**Issue by rossbeehler** [dotnet/vscode-csharp#7475]
When utilizing the [Introduce local variable for expression](https://code.visualstudio.com/docs/csharp/refactoring#_introduce-local-variable-for-expression) refactoring, it should create the local variable with the `var` keyword.  I would lobby this should be the default behavior, but a configuration to allow the user to switch between the explicit type and `var` would also work.

**Comment by dibarbet** [comment]
@rossbeehler this should work as long as you have the right settings in your .editorconfig, see https://github.com/dotnet/roslyn/issues/55698#issuecomment-903382357

![use_var_local](https://github.com/user-attachments/assets/f15a0895-dd98-4168-8093-581bbd559e16)

**Comment by dibarbet** [comment]
Closing as by design, please re-open if you have issues with it.
