### ISSUE TITLE
VSCode - ARM Snapdragon X Elite - dotnet ARM vs x64

### ISSUE THREAD

**Issue by ValerioFG** [dotnet/vscode-csharp#7492]
Hi All,
I've recently switched to an ARM Snapdragon Processor and VScode is trying to make me insane. 

I'm usually working with azure , functions , c# , bicept etcc.

I'm trying to use the .net SDK (6 and 8) but when I install the ARM version of it it doesn't let me run anything, says that is expecting a ARM process.

I've installed NET 6 x64 and it started working. Now after adding version 8 says that the SDK is installed but the debugger cannot find the files in the folder where they are supposed to be. Found .NET SDK, but did not find dotnet.dll at c:\programFiles\dotnet\

While trying to make sense of it, I've noticed that under c:\programFiles\dotnet there is a new folder called \x64 where the dotnet files are beging installed for (x64) 

How Can I set this new location for the C# dev kit? 

c:\Program Files\dotnet>dotnet --version
6.0.425

c:\Program Files\dotnet\x64>dotnet --version
8.0.401

c:\Program Files\dotnet>dotnet --list-sdks
6.0.425 [c:\Program Files\dotnet\sdk]

c:\Program Files\dotnet\x64>dotnet --list-sdks
6.0.425 [c:\Program Files\dotnet\x64\sdk]
8.0.401 [c:\Program Files\dotnet\x64\sdk]

C# Dev Kit v1.9.55

VS Code version: 1.92.2

I would love to use omnisharp as well but that just doesn't work anymore (Even if I active modern NET in C# extention and remove C# dev kit)

Thank you for your help.

**Comment by dibarbet** [comment]
Generally, if you're on an ARM system, and are using the ARM version of VSCode, you will need the ARM version of dotnet as well.

> I'm trying to use the .net SDK (6 and 8) but when I install the ARM version of it it doesn't let me run anything, says that is expecting a ARM process.

Can you let me know the exact error you're hitting?  This should be the correct way to go.

> I would love to use omnisharp as well but that just doesn't work anymore (Even if I active modern NET in C# extention and remove C# dev kit)

It should work if you also set `dotnet.server.useOmnisharp` to true and reload VSCode (make sure C# DevKit is either uninstalled or disabled).

**Comment by ValerioFG** [comment]
hi dibarbet, 
Thank you for your help with this.
I've unistalled everything and re-installed the ARM version only of Vscode dotnet 6 and 8 , looks like is working now, not sure why wasn't working when I've first tried. 

Omnisharp is working as well.

**Comment by dibarbet** [comment]
@ValerioFG looks like that error is reported by the .NET CLI, and likely related to your project configuration (C# extension isn't involved in the CLI restore).

If you just installed .NET 8, you may need to restart the terminal to ensure the path updates take effect.  Other things that can cause this is if you have a global.json locking your project to the .NET6 SDK (and have some project targeting .NET 8).

See https://learn.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1045 for more possibilities on why you might be seeing that error.

I'm going to close this issue as it sounds like the C# extension is working now.

**Comment by ValerioFG** [comment]
Hi Dibarbet, sorry for reopening.
Today Vscode updated itself and it's not working anymore: 

"Failed to attach to process: The .NET debugger can only debug ARM64 processes."

![image](https://github.com/user-attachments/assets/05583202-042e-486a-936b-e1bd193fb74e)
![image](https://github.com/user-attachments/assets/73850a36-4314-4b0d-b2a3-491367e7bc3d)

PS C:\Devops\ELCI v2\ELCI\Modules\RHIS\ELCI Module Interface API> dotnet --version
8.0.401
PS C:\Devops\ELCI v2\ELCI\Modules\RHIS\ELCI Module Interface API> dotnet --list-sdks
6.0.425 [C:\Program Files\dotnet\sdk]
8.0.401 [C:\Program Files\dotnet\sdk]

Everything was working till this morning
