### ISSUE TITLE
[BUG] Launch adds hyphen and breaks path 

### ISSUE THREAD

**Issue by WardenGnaw** [dotnet/vscode-csharp#7504]
Originally from https://github.com/microsoft/vscode-dotnettools/issues/1425 by @georg-eckert-zeiss 
----------------

### Describe the Issue

When adding a configuration and trying to run it a hyphen ("-") is added to the executable. Therefore I get an error that the file cannot be found.

![image](https://github.com/user-attachments/assets/e6edbad2-e2f8-47e7-9e1b-c2bc68cec8ef)

### Steps To Reproduce

1. in ubuntu linux clone a C# project like nuget-inspector
2. install the C# dev kit extension in vs code
3. create a launch.json
4. add a new configuration ".NET: launch executable file (Console)"
5. launch it

### Expected Behavior

file is launched

instead a hyphen is added and changes the path from

`/bin/Debug/net6.0/linux-x64/nuget-inspector.dll`
to
`/bin/Debug/net6.0/linux-x64/-nuget-inspector.dll`

### Environment Information

- OS: Ubuntu 22.04
- VS Code version: 1.92.2 azure snap
- Extension version: v1.9.55

**Comment by WardenGnaw** [comment]
@georg-eckert-zeiss does the binary exist at `/home/georg/app/niz/src/bin/Debug/net6.0/linux-x64/nuget-inspector.dll`?

I was unable to reproduce the issue with:
OS: Ubuntu 22.04
VS Code: 1.92.2
C# Extension: v2.39.29
C# Dev Kit: v1.9.55

The `launch.json` that worked for me was:
```json
        {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "program": "${workspaceFolder}/src/nuget-inspector/bin/Debug/net6.0/linux-x64/nuget-inspector.dll",
            "args": [],
            "cwd": "${workspaceFolder}",
            "stopAtEntry": false,
            "console": "internalConsole"
        }
```

**Comment by gregg-miskelly** [comment]
It has been several months without a response, so I am closing the issue.
