### ISSUE TITLE
VSCode - Snapdragon x ELITE - ARM -  Failed to attach to process: The .NET debugger can only debug ARM64 processes. 

### ISSUE THREAD

**Issue by ValerioFG** [dotnet/vscode-csharp#7520]
I'm having this issue with some azure functions and I cannot understand where the issue is.
Some project works some not, they are all net 6. 
SDK for ARM is installed .

"Failed to attach to process: The .NET debugger can only debug ARM64 processes."

![image](https://github.com/user-attachments/assets/5cb1d602-77e9-46f8-a0cc-265389818f3c)
![image](https://github.com/user-attachments/assets/e3d797f4-a11a-406d-a776-3e30317cdf4d)

PS C:\Devops\ELCI v2\ELCI\Modules\RHIS\ELCI Module Interface API> dotnet --version
8.0.401
PS C:\Devops\ELCI v2\ELCI\Modules\RHIS\ELCI Module Interface API> dotnet --list-sdks
6.0.425 [C:\Program Files\dotnet\sdk]
8.0.401 [C:\Program Files\dotnet\sdk]

Version: 1.93.0 (user setup)
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
Date: 2024-09-04T13:02:38.431Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT arm64 10.0.26100

If I switch to another function that has similar settings it works, what can be causing this?

**Comment by gregg-miskelly** [comment]
What do you get from `where dotnet.exe` and `dotnet --info`?

**Comment by gregg-miskelly** [comment]
Wait sorry, I missed that this is Azure functions. The problem is that something needs to tell the debugger to use the X64 debugger for Azure Functions. What does your launch.json look like?

**Comment by gregg-miskelly** [comment]
This is probably the issue you are running into: https://github.com/microsoft/vscode-azurefunctions/issues/3005

**Comment by ValerioFG** [comment]
{
  "profiles": {
    "API_InvokePerson": {
      "commandName": "Project",
      "commandLineArgs": "--port 7230",
      "launchBrowser": false
    }
  }
}

**Comment by gregg-miskelly** [comment]
That is your launchSettings.json I am assuming? You want your .vscode\launch.json.

**Comment by gregg-miskelly** [comment]
If you don't have one, how are you starting debugging?

**Comment by ValerioFG** [comment]
Sorry, I've edited the original reply

**Comment by ValerioFG** [comment]
I've added "targetArchitecture": "x86_64" and it works. 


![image](https://github.com/user-attachments/assets/d55e6467-cca3-4a6a-bab5-83de3abc8695)
This is not supported in windows. 

When vscode builds .vscode assets, it's automatically omitted.  Anywhere I can ask to add it when creating new functions?
