### ISSUE TITLE
Ctrl + Click to view the definition is not working in Mac.

### ISSUE THREAD

**Issue by prashanth-g** [dotnet/vscode-csharp#7532]
## Environment data
`dotnet --info` output:

.NET SDK:
 Version:           8.0.303
 Commit:            29ab8e3268
 Workload version:  8.0.300-manifests.c915c39d
 MSBuild version:   17.10.4+10fbfbf2e

Version: 1.93.0 (Universal) 
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3 
Date: 2024-09-04T13:02:38.431Z (4 days ago) 
Electron: 30.4.0 ElectronBuildId: 10073054
Chromium: 124.0.6367.243 Node.js: 20.15.1 V8: 12.4.254.20-electron.0 
OS: Darwin arm64 23.6.0

## Steps to reproduce

1. Open any C# project. A very simple project with a Program.cs file with some dependencies.
2. Open the Program.cs file and Click on the imported class. In first CTRL + Click it is opening the definition. Then the link itself is gone.

## Expected  behavior
Ctrl + Click should open the definition

## Actual behavior
First time it works after that the class names become non clickable.

**Comment by eqpoqpe** [comment]
Install specific version 🥲

**Comment by prashanth-g** [comment]
Tried uninstalling, installing the extension but it did not help

**Comment by eqpoqpe** [comment]
Install specific version c# dev kit

**Comment by dibarbet** [comment]
We should be uploading a new version of the C# extension in a day or two with a fix.  Downgrading to a lower version of the C# extension should workaround this issue for now.
