### ISSUE TITLE
Debugging failed. Missing brokeredServicePipeName

### ISSUE THREAD

**Issue by pennisiandrea** [dotnet/vscode-csharp#7533]
Type: <b>Bug</b>

## Issue Description ##
After click on Start Debugging button, the system opens a message box with the error "Start debugging failed. Provided launch or attach configuration is missing required property brokeredServicePipeName" (also reported in the debug console).

## Steps to Reproduce ##
Install v2.45.20 and start debugging. Downgrading to v2.39.29 solved the issue.

### OmniSharp log ###
No entries in the Omnisharp log.
        
### C# log ###
No entries in the C# Output.

## Environment information ##

**VSCode version**: 1.90.2
**C# Extension**: 2.45.20
**Using OmniSharp**: true

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:           8.0.401
 Commit:            811edcc344
 Workload version:  8.0.400-manifests.b6724b7a
 MSBuild version:   17.11.4+37eb419ad

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.401\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
There are no installed workloads to display.

Host:
  Version:      8.0.8
  Architecture: x64
  Commit:       08338fcaa5

.NET SDKs installed:
  8.0.100-rc.2.23502.2 [C:\Program Files\dotnet\sdk]
  8.0.401 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0-rc.2.23480.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.2.23479.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-rc.2.23479.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|csdevkit|ms-dotnettools|1.10.16|ms-dotnettools.csdevkit-1.10.16-win32-x64|
|csharp|ms-dotnettools|2.45.20|ms-dotnettools.csharp-2.45.20-win32-x64|
|material-icon-theme|PKief|5.10.0|pkief.material-icon-theme-5.10.0|
|vscode-dotnet-runtime|ms-dotnettools|2.1.5|ms-dotnettools.vscode-dotnet-runtime-2.1.5|
|vscode-innosetup|chouzz|1.9.3|chouzz.vscode-innosetup-1.9.3|
|xml|DotJoshJohnson|2.5.1|dotjoshjohnson.xml-2.5.1|;

</details>

Extension version: 2.45.20
VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (4.47GB free)|
|Process Argv|--crash-reporter-id 958b51e0-3cd1-41c1-b6cf-0bddc92e94e8|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31119336
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
ei213698:31121563

```

</details>

**Comment by WardenGnaw** [comment]
@pennisiandrea Do you have the C# Dev Kit extension installed? If so, it may be related to https://github.com/microsoft/vscode-dotnettools/issues/1432

If its just only the C# Extension, can you share the type of project you are trying to debug and `launch.json` that you are using?

**Comment by pennisiandrea** [comment]
Hi Warden, 
yes, I have C# Dev Kit installed. I posted the error here due to this [comment](https://github.com/microsoft/vscode-dotnettools/issues/1432#issuecomment-2336609212) which makes me think that the issue might be related to C# instead of C# Dev Kit.

I have a workspace with two projects. One is a Console application, the another is a WPF. With v2.45.20 of C# extension the issue is on both and it appears to be unrelated to C# Dev Kit extension. This is my launch.json:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch ASTools.Core",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "Build ASTools.Core",
            "program": "${workspaceFolder}/ASTools.Core/bin/Debug/net8.0-windows/ASTools.Core.dll",
            "args": ["templates","--list"],
            "cwd": "${workspaceFolder}/ASTools.Core",
            "stopAtEntry": false,
            "console": "internalConsole",
            "internalConsoleOptions": "openOnSessionStart",
            "launchBrowser": {
                "enabled": false
            },
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            }
        },
        {
            "name": ".NET Core Launch ASTools.UI",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "Build ASTools.UI",
            "program": "${workspaceFolder}/ASTools.UI/bin/Debug/net8.0-windows/ASTools.UI.dll",
            "args": ["--page","templates","--working-dir","C:\\Data\\test\\test\\Logical"],
            "cwd": "${workspaceFolder}/ASTools.UI",
            "stopAtEntry": false,
            "console": "internalConsole",
            "internalConsoleOptions": "openOnSessionStart",
            "launchBrowser": {
                "enabled": false
            },
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            }
        }
    ]
}
```

Maybe I just have to add the property brokeredServicePipeName (as written in the error message), in this case could you please help me providing some documentation?

**Comment by jojorne** [comment]
I'm pretty sure this is an error and it will be fixed soon, that said you can add it:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "brokeredServicePipeName": "A",
            [...]
        }
    ]
}
```

"A"? well, it wants something, so... lol

**Comment by jojorne** [comment]
I'm pretty sure this is just an error and it will be fixed soon, that said you can add this:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "brokeredServicePipeName": "A",
            [...]
        }
    ]
}
```

"A"? well, it wants something, so... lol

**Comment by jojorne** [comment]
I'm pretty sure this is just an error and it will be fixed soon, that said you can add it:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "brokeredServicePipeName": "undefined",
            [...]
        }
    ]
}
```

**Comment by WardenGnaw** [comment]
The issue was the debug configuration resolver was injecting a debugger option that should appear in the `dotnet` debug configuration that the C# Dev Kit provides. This should not affect the `coreclr` debugging scenarios.

Thank you to everyone for reporting and providing additional information on this issue.
