### ISSUE TITLE
Any FixAll CodeFix does not work anymore.

### ISSUE THREAD

**Issue by ThierryRosseau** [dotnet/vscode-csharp#7535]
## Issue Description ##
Any FixAll CodeFIx does not work anymore.

Need to revert to previous C# Extension version!

Exception: 

JSON deserialization for type 'Microsoft.CodeAnalysis.LanguageServer.Handler.CodeActions.RoslynFixAllCodeAction' was missing required properties, including the following: title

### C# log ###
[Error - 09:31:49] [LanguageServerHost] System.Text.Json.JsonException: JSON deserialization for type 'Microsoft.CodeAnalysis.LanguageServer.Handler.CodeActions.RoslynFixAllCodeAction' was missing required properties, including the following: title
   at System.Text.Json.ThrowHelper.ThrowJsonException_JsonRequiredPropertyMissing(JsonTypeInfo parent, BitArray requiredPropertiesSet)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](JsonElement element, JsonSerializerOptions options)
   at Microsoft.CommonLanguageServerProtocol.Framework.SystemTextJsonLanguageServer`1.DeserializeRequest[TRequest](Object serializedRequest, RequestHandlerMetadata metadata) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/SystemTextJsonLanguageServer.cs:line 50
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.TryDeserializeRequest[TRequest](AbstractLanguageServer`1 languageServer, RequestHandlerMetadata requestHandlerMetadata, Boolean isMutating, TRequest& request) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 117
Error making codeAction/resolveFixAll request: JSON deserialization for type 'Microsoft.CodeAnalysis.LanguageServer.Handler.CodeActions.RoslynFixAllCodeAction' was missing required properties, including the following: title

### C# LSP Trace Logs ###
<details>Post the output from Output-->C# LSP Trace Logs here.  Requires `dotnet.server.trace` to be set to `Trace`</details>

## Environment information ##

**VSCode version**: 1.93.0
**C# Extension**: 2.45.20
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:           8.0.401
 Commit:            811edcc344
 Workload version:  8.0.400-manifests.b6724b7a
 MSBuild version:   17.11.4+37eb419ad

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.6
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.401/

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
There are no installed workloads to display.

Host:
  Version:      8.0.8
  Architecture: x64
  Commit:       08338fcaa5

.NET SDKs installed:
  3.1.426 [/usr/local/share/dotnet/sdk]
  5.0.408 [/usr/local/share/dotnet/sdk]
  6.0.417 [/usr/local/share/dotnet/sdk]
  7.0.410 [/usr/local/share/dotnet/sdk]
  8.0.401 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.25 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.25 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|atom-icons|emroussel|1.2.0|emroussel.atom-icons-1.2.0|
|code-spell-checker|streetsidesoftware|3.0.1|streetsidesoftware.code-spell-checker-3.0.1|
|code-spell-checker-dutch|streetsidesoftware|0.5.1|streetsidesoftware.code-spell-checker-dutch-0.5.1|
|code-spell-checker-french|streetsidesoftware|0.4.1|streetsidesoftware.code-spell-checker-french-0.4.1|
|copilot|GitHub|1.229.1094|github.copilot-1.229.1094|
|copilot-chat|GitHub|0.21.2024090602|github.copilot-chat-0.21.2024090602|
|cscodepolisher|HedgehogNSK|0.0.4|hedgehognsk.cscodepolisher-0.0.4|
|csdevkit|ms-dotnettools|1.10.16|ms-dotnettools.csdevkit-1.10.16-darwin-x64|
|csharp|ms-dotnettools|2.45.20|ms-dotnettools.csharp-2.45.20-darwin-x64|
|data-workspace-vscode|ms-mssql|0.5.0|ms-mssql.data-workspace-vscode-0.5.0|
|debug-in-titlebar|EverlastEngineering|1.0.8|everlastengineering.debug-in-titlebar-1.0.8|
|EditorConfig|EditorConfig|0.16.4|editorconfig.editorconfig-0.16.4|
|file-icons-mac|wayou|1.0.1|wayou.file-icons-mac-1.0.1|
|git-graph|mhutchie|1.30.0|mhutchie.git-graph-1.30.0|
|hexeditor|ms-vscode|1.10.0|ms-vscode.hexeditor-1.10.0|
|icons-carbon|antfu|0.2.6|antfu.icons-carbon-0.2.6|
|json-color-token|yechunan|1.3.3|yechunan.json-color-token-1.3.3|
|live-sass|glenn2223|6.1.2|glenn2223.live-sass-6.1.2|
|LiveServer|ritwickdey|5.7.9|ritwickdey.liveserver-5.7.9|
|markdown-preview-github-styles|bierner|2.0.4|bierner.markdown-preview-github-styles-2.0.4|
|mssql|ms-mssql|1.24.0|ms-mssql.mssql-1.24.0|
|powershell|ms-vscode|2024.2.2|ms-vscode.powershell-2024.2.2|
|prettier-vscode|esbenp|11.0.0|esbenp.prettier-vscode-11.0.0|
|quill-icons|cdonohue|0.0.2|cdonohue.quill-icons-0.0.2|
|remote-containers|ms-vscode-remote|0.384.0|ms-vscode-remote.remote-containers-0.384.0|
|rose-pine|mvllow|2.10.0|mvllow.rose-pine-2.10.0|
|sql-database-projects-vscode|ms-mssql|1.4.3|ms-mssql.sql-database-projects-vscode-1.4.3|
|stardust|undefined_publisher|0.0.1|undefined_publisher.stardust-0.0.1|
|syntax-visualizer-csharp|ypyl|0.1.11|ypyl.syntax-visualizer-csharp-0.1.11|
|toggle-excluded-files|amodio|2.0.0|amodio.toggle-excluded-files-2.0.0|
|typelens|kisstkondoros|1.10.0|kisstkondoros.typelens-1.10.0|
|user-secrets|adrianwilczynski|2.0.1|adrianwilczynski.user-secrets-2.0.1|
|vidyano-extension|vidyano-extension|2.1.2|vidyano-extension.vidyano-extension-2.1.2|
|vscode-commands|fabiospampinato|2.0.2|fabiospampinato.vscode-commands-2.0.2|
|vscode-docker|ms-azuretools|1.29.2|ms-azuretools.vscode-docker-1.29.2|
|vscode-dotnet-runtime|ms-dotnettools|2.1.5|ms-dotnettools.vscode-dotnet-runtime-2.1.5|
|vscode-eslint|dbaeumer|3.0.10|dbaeumer.vscode-eslint-3.0.10|
|vscode-jest|Orta|6.2.5|orta.vscode-jest-6.2.5|
|vscode-markdownlint|DavidAnson|0.55.0|davidanson.vscode-markdownlint-0.55.0|
|vscode-scss-formatter|sibiraj-s|3.0.0|sibiraj-s.vscode-scss-formatter-3.0.0|
|vscode-todo-highlight|jgclark|2.0.8|jgclark.vscode-todo-highlight-2.0.8|
|vscodeintellicode-csharp|ms-dotnettools|2.1.11|ms-dotnettools.vscodeintellicode-csharp-2.1.11-darwin-x64|
|xml|DotJoshJohnson|2.5.1|dotjoshjohnson.xml-2.5.1|;

</details>

**Comment by dibarbet** [comment]
We'll be uploading a new version of the C# extension in a day or two with a fix. Downgrading to a lower version of the C# extension should work as a temporary workaround.
