### ISSUE TITLE
'Quick fix' takes a lot of time

### ISSUE THREAD

**Issue by NikiforovAll** [dotnet/vscode-csharp#7557]
Type: <b>Bug</b>

Open any C# code and press 'ctrl+ .'

Quick fix takes a lot of time (+10 sec) to load. Reproduces in vscode insiders also.

Extension version: 2.45.20
VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.50GB (10.94GB free)|
|Process Argv|--crash-reporter-id c6168c79-8947-43a3-ab8f-f37682ad5b9a --inspect-extensions=34631 --crash-reporter-id c6168c79-8947-43a3-ab8f-f37682ad5b9a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
autoexpandse:31133494
ei213698:31121563

```

</details>

**Comment by HenriqueSabino** [comment]
I'm also having the same issue

**Comment by NikiforovAll** [comment]
@HenriqueSabino for me it was "Sonar" extension, I found the reason accidentally. I downgraded the version to the previous one and now it works better. 

It would be great to have tools to troubleshoot this kind of scenario.

**Comment by HenriqueSabino** [comment]
> @HenriqueSabino for me it was "Sonar" extension, I found the reason accidentally. I downgraded the version to the previous one and now it works better.
> 
> It would be great to have tools to troubleshoot this kind of scenario.

Thanks! it fixed to me!

**Comment by JoeRobich** [comment]
Thanks for reporting. It sounds like this particular issue has been resolved by taking a fixed version of the "Sonar" analyzer package. Closing.
