### ISSUE TITLE
Microsoft.CodeAnalysis.LanguageServer has excessively high cpu usage

### ISSUE THREAD

**Issue by operation404** [dotnet/vscode-csharp#7571]
.NET SDK:
 Version:           8.0.303
 Commit:            29ab8e3268
 Workload version:  8.0.300-manifests.34944930
 MSBuild version:   17.10.4+10fbfbf2e

Windows 10.0.19045
VSCode version: 1.93.1
C# Extension: 2.45.25
CPU: Intel i9-9900K CPU @ 4.60GHz
Memory: 31.93gb

## Steps to reproduce
1. Open a .NET project.
2. Start typing.

## Expected  behavior
The LSP functions normally.

## Actual behavior
The `Microsoft.CodeAnalysis.LanguageServer.exe` process cpu usage rises from <0.1% idle to over 50%, with peaks above 70%, for the duration of the typing.

## Additional context
I have a relatively small workspace with a single .csproj file and a few hundred C# files. I switched from using Omnisharp a few days ago. The extension functions correctly, but when monitoring the LSP process I can see it consistently at >50% of my entire workstation's cpu usage. I have background analysis set to only opened files. Disabling it completely helps bring cpu usage down to around >30%, but then I'm missing most of the functionality I need from the extension. Other settings seemed to have no impact. 

I've looked around for potential solutions to my performance problems including reading through the github issues. I thought it might be related to #5733 but I've had no issues with memory consumption, I've never seen the LSP use more than 3gb of memory. Aside from whatever default extension settings were disabled due to using Omnisharp, I've changed nothing else about my setup. I've tried playing around with various combinations of settings, but nothing aside from outright disabling the extension is doing much to improve performance. I'd like to continue using the new LSP as it fixes some intellisense bugs I've had, but unfortunately the excessive cpu usage is impacting the rest of my work flow.

**Comment by dibarbet** [comment]
@operation404 would you mind collecting a perf trace and emailing it to me (dabarbet@microsoft.com).

You can find instructions here - https://github.com/dotnet/roslyn/blob/876ea36bec34b276340100a5e0ef435d448a6725/docs/wiki/Recording-performance-traces-with-PerfView.md#common-scenarios

**Comment by operation404** [comment]
Sent.

I've experimented a bit more since writing this, and while I haven't solved the issue I have at least made it manageable. Downgrading extension versions didn't seem to help, but I did delete every C# related extension I had and manually reinstalled them all, and that seems to have _potentially_ helped.

I've noticed that how fast I'm typing directly affects the cpu strain of the lsp, which I guess isn't too surprising. When typing at my normal speed for writing code it'll sit in the 30-50% usage range, only going above every now and then. It seems the largest spikes mostly happen when I'm writing comments as I tend to type faster when commenting.

If I ensure I don't have other cpu heavy processes running I don't get any slowdown. I can still hear my computer fans spin up and down as I start and stop typing, which isn't ideal, but it's something I can tolerate.

Hopefully this is a configuration or other user error on my end that I can resolve quickly.

**Comment by dibarbet** [comment]
@operation404 got your mail - thanks!  Will take a look shortly.

**Comment by dibarbet** [comment]
@operation404 a super initial peek seems to indicate a fair amount of CPU usage in a source generator, `Godot.SourceGenerators`.  I would be curious if you hit the same CPU usage issues in projects not using that source generator.

**Comment by operation404** [comment]
Hm, that's an important observation and really helpful. The project I've been working on is for the Godot engine, and whenever I build and run my project it has source generators for providing interop between my code and the engine native code. Is there any way I can restrict these from being analyzed?

**Comment by dibarbet** [comment]
Unfortunately the only way to prevent the generator from running today is for the project to not reference the generator.  

However, there was a new mode added to Visual Studio recently to run generators only on explicit commands (e.g. build) instead of typing.  This work needs to be ported to VSCode as well, this issue tracks that work - https://github.com/dotnet/roslyn/issues/75152

**Comment by operation404** [comment]
Hm. I don't know if I can avoid referencing them while also still having full functionality when working with the engine, I'll have to look into it. But that VS feature is good to know about, that seems like it would perfectly solve my situation. Thanks for letting me know.

**Comment by dibarbet** [comment]
I'm going to close this issue - this should be resolved once https://github.com/dotnet/roslyn/issues/75152 is completed, which I hope to do in the next couple of weeks.
