### ISSUE TITLE
 Intellisense is not reflecting the latest code changes in referenced projects

### ISSUE THREAD

**Issue by Andi-Re** [dotnet/vscode-csharp#7609]
## Issue Description ##

I have a project that references another project, and when a method name changes, IntelliSense doesn't immediately flag the code using the old name as an error. However, with OmniSharp enabled, this issue is resolved and the errors are correctly displayed.

## Steps to Reproduce ##

The following reproducer is written using .NET 8.0 however this behavior is also present using .NET Framework 4.7.2

I have this dummy library:

```namespace ClassLibrary1;

public class Class1
{
    public static void SomeFunc1()
    {
        Console.WriteLine("Hello, World!");
    }
}
```

And this dummy console application:

```ClassLibrary1.Class1.SomeFunc1();```

This is my ConsoleApp1.csproj

```<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../ClassLibrary1/ClassLibrary1.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
```

1. Change the name of SomeFunc1 to SomeFunc2 in the Class Library
2. See that Intellisense is not aware that this method name has changed.
3. Restart Language Server and see that this also does not help.
4. Reload Window and see that now the Intellisense is working with the correct information.

## Expected Behavior ##

If I change a method name it should be noticed by the language server.

## Actual Behavior ##

It only notices the changes after reloading the window

## Environment information ##

**VSCode version**: 1.93.0
**C# Extension**: 2.49.25
**C# Dev Kit**: v1.10.18
**Using OmniSharp**: false

**Comment by tverboon** [comment]
It will probably also start working when you do a build. Omnisharp by default does solution wide analysis when you have less than 1000 files.

The default now with C# is only `openFiles`.  What is currently your setting value of: `dotnet.backgroundAnalysis.compilerDiagnosticsScope`? The value `fullSolution` might improve your experience. But beware, on larger solutions this will impact performance and you probably want to revert to `openFiles`.

**Comment by Andi-Re** [comment]
@tverboon: Thanks alot for your response.

So the problem still exists after doing a build. Also setting **dotnet.backgroundAnalysis.compilerDiagnosticsScope** doesn't change the behavior in my case. Also having both files (library.cs and main.cs) opened doesn't help. It seems only reloading the window gets the Intellisense updated.

**Comment by dibarbet** [comment]
@Andi-Re would you mind sharing a screenshot of the solution explorer window?  Would be good to know what projects C# Dev Kit thinks is loaded.

Additionally - would be good to know if adding a solution file explicitly and loading that (via the .net open sln command) helps.  You can do that via the CLI (`dotnet new sln` and `dotnet sln add <proj>`)

**Comment by Andi-Re** [comment]
Hi dibarbet,
it seems you are right, If I add my project "ClassLibrary1" to my solution, then it will show in C# Dev Kits Solution Explorer and it updates to "ClassLibrary1" will be detected by IntelliSense immediately.

Solution explorer with problem:

![image](https://github.com/user-attachments/assets/a45352a8-c5b2-49cb-b5ae-ee44109f10c3)

Solution explorer without problem:

![image](https://github.com/user-attachments/assets/f2645e50-47d3-4b2f-8e3f-c2ffb350ea87)

However the problem also exists when referencing Dlls (not projects). With OmniSharp, updates of these Dlls will be regarded by IntelliSense, with the current Language Server not.

**Comment by Andi-Re** [comment]
@dibarbet: Is this information i provided you with helping you understanding the problem?

**Comment by dibarbet** [comment]
@Andi-Re yup thanks.  Currently C# Dev Kit requires the project to be part of the solution in order to be properly loaded.  See also https://github.com/microsoft/vscode-dotnettools/issues/474

No action from the C# extension side currently, this feature would need to be supported by C# Dev Kit
