### ISSUE TITLE
Excessive logging in "Temp\servicehub\logs"

### ISSUE THREAD

**Issue by glen-84** [dotnet/vscode-csharp#7617]
Type: <b>Bug</b>

## Issue Description ##

There is an excessive amount of logging in the "Temp\servicehub\logs" directory. Easily 6+ GBs.

![image](https://github.com/user-attachments/assets/05b1dd41-8cad-4af5-b763-6649d4d554ef)

## Steps to Reproduce ##

Just use the extension.

## Expected Behavior ##

No logging (or minor logging) unless I opt into it.

## Actual Behavior ##

Excessive logging.

File patterns:

- `*-Microsoft.VisualStudio.ProjectSystem.Query.Remoting.QueryExecutionService-*-*-*`
- `*-Microsoft.VisualStudio.TestWindow.VSCode.Service-*-*-*`
- `*-Microsoft.VisualStudio.ProjectSystem.Query.Remoting.QueryExecutionService-*-*-*`
- `*-Microsoft.VisualStudio.ProjectSystem.CompositionService-*-*-*`
- `*-Microsoft.VisualStudio.LaunchConfigurationService-*-*-*`
- etc.

### C# log ###
<details>Post the output from Output-->C# here</details>

### C# LSP Trace Logs ###
<details>Post the output from Output-->C# LSP Trace Logs here.  Requires `dotnet.server.trace` to be set to `Trace`</details>

## Environment information ##

**VSCode version**: 1.93.1
**C# Extension**: 2.45.25
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:           9.0.100-rc.1.24452.12
 Commit:            81a714c6d3
 Workload version:  9.0.100-manifests.8c1650e0
 MSBuild version:   17.12.0-preview-24422-09+d17ec720d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-rc.1.24452.12\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
There are no installed workloads to display.

Host:
  Version:      9.0.0-rc.1.24431.7
  Architecture: x64
  Commit:       static

.NET SDKs installed:
  6.0.425 [C:\Program Files\dotnet\sdk]
  7.0.410 [C:\Program Files\dotnet\sdk]
  8.0.402 [C:\Program Files\dotnet\sdk]
  9.0.100-rc.1.24452.12 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-rc.1.24452.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-rc.1.24431.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0-rc.1.24452.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|auto-close-tag|formulahendry|0.5.15|formulahendry.auto-close-tag-0.5.15|
|change-case|wmaurer|1.0.0|wmaurer.change-case-1.0.0|
|code-spell-checker|streetsidesoftware|3.0.1|streetsidesoftware.code-spell-checker-3.0.1|
|copilot|GitHub|1.234.0|github.copilot-1.234.0|
|copilot-chat|GitHub|0.20.3|github.copilot-chat-0.20.3|
|csdevkit|ms-dotnettools|1.10.18|ms-dotnettools.csdevkit-1.10.18-win32-x64|
|csharp|ms-dotnettools|2.45.25|ms-dotnettools.csharp-2.45.25-win32-x64|
|dotenv|mikestead|1.0.1|mikestead.dotenv-1.0.1|
|EditorConfig|EditorConfig|0.16.4|editorconfig.editorconfig-0.16.4|
|eml|leighlondon|0.4.0|leighlondon.eml-0.4.0|
|gitblame|waderyan|11.0.1|waderyan.gitblame-11.0.1|
|hexeditor|ms-vscode|1.10.0|ms-vscode.hexeditor-1.10.0|
|JavaScriptSnippets|xabikos|1.8.0|xabikos.javascriptsnippets-1.8.0|
|markdown-mermaid|bierner|1.25.0|bierner.markdown-mermaid-1.25.0|
|mermaid-markdown-syntax-highlighting|bpruitt-goddard|1.6.6|bpruitt-goddard.mermaid-markdown-syntax-highlighting-1.6.6|
|msbuild-project-tools|tintoy|0.6.5|tintoy.msbuild-project-tools-0.6.5|
|remote-explorer|ms-vscode|0.4.3|ms-vscode.remote-explorer-0.4.3|
|remote-ssh|ms-vscode-remote|0.114.3|ms-vscode-remote.remote-ssh-0.114.3|
|remote-ssh-edit|ms-vscode-remote|0.86.0|ms-vscode-remote.remote-ssh-edit-0.86.0|
|remote-wsl|ms-vscode-remote|0.88.4|ms-vscode-remote.remote-wsl-0.88.4|
|render-crlf|medo64|1.8.1|medo64.render-crlf-1.8.1|
|t4-support|zbecknell|0.7.0|zbecknell.t4-support-0.7.0|
|Theme-TomorrowKit|ms-vscode|0.1.4|ms-vscode.theme-tomorrowkit-0.1.4|
|todo-tree|Gruntfuggly|0.0.226|gruntfuggly.todo-tree-0.0.226|
|toggle-hidden|adrianwilczynski|1.0.2|adrianwilczynski.toggle-hidden-1.0.2|
|trailing-spaces|shardulm94|0.4.1|shardulm94.trailing-spaces-0.4.1|
|volar|Vue|2.1.6|vue.volar-2.1.6|
|vscode-commons|redhat|0.0.6|redhat.vscode-commons-0.0.6|
|vscode-dotnet-runtime|ms-dotnettools|2.1.6|ms-dotnettools.vscode-dotnet-runtime-2.1.6|
|vscode-github-actions|github|0.27.0|github.vscode-github-actions-0.27.0|
|vscode-graphql-syntax|GraphQL|1.3.6|graphql.vscode-graphql-syntax-1.3.6|
|vscode-highlight|fabiospampinato|1.9.0|fabiospampinato.vscode-highlight-1.9.0|
|vscode-markdownlint|DavidAnson|0.56.0|davidanson.vscode-markdownlint-0.56.0|
|vscode-sort-json|richie5um2|1.20.0|richie5um2.vscode-sort-json-1.20.0|
|vscode-svg-previewer|vitaliymaz|0.7.0|vitaliymaz.vscode-svg-previewer-0.7.0|
|vscode-yaml|redhat|1.15.0|redhat.vscode-yaml-1.15.0|;

</details>

Extension version: 2.45.25
VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-13600KF (20 x 3494)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|127.83GB (107.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by dibarbet** [comment]
tracked in https://github.com/microsoft/vscode-dotnettools/issues/1505
