### ISSUE TITLE
A single _ (underscore/discard) gets auto-completed to something else

### ISSUE THREAD

**Issue by detzt** [dotnet/vscode-csharp#7623]
Type: <b>Bug</b>

When I want to use a discard in a C# project, I type _ usually followed by a space or comma, which triggers the auto-completion.
For other words this is fine, but a single underscore is not part of the autocompletion list, so it gets completed to some public class name that contains an underscore.
Can you add the discard character to that autocompletion list?

Extension version: 2.45.25
VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor              (12 x 3693)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.95GB (15.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ARKye03** [comment]
+1 annoying issue, trying to set up a discard like:

```csharp
_ = ReturnIntMethod();
```
After typing `_` and pressing space it ends up in a random thing containing `_`.
For example:
```csharp
SHA3_256 = ReturnIntMethod();
```

**Comment by dibarbet** [comment]
Not 100% sure yet, but potentially related to https://github.com/microsoft/language-server-protocol/issues/1791
We're getting an 'invoked' trigger kind which may be causing us to hard select the item (including space as a commit char).  Still investigating

**Comment by detzt** [comment]
Thank you! It works perfectly and never got in the way since the update 👍🏼
