### ISSUE TITLE
Can't find my OmniSharp logs in VSCode (Unity6 preview)

### ISSUE THREAD

**Issue by ProgrammingLife** [dotnet/vscode-csharp#7627]
## Environment data
**VSCode version**: 1.93.1
**C# Extension**: 2.45.25
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:           8.0.108
 Commit:            665a05cea7
 Workload version:  8.0.100-manifests.109ff937

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.108/

.NET workloads installed:
 Workload version: 8.0.100-manifests.109ff937
There are no installed workloads to display.

Host:
  Version:      8.0.8
  Architecture: x64
  Commit:       08338fcaa5

.NET SDKs installed:
  8.0.108 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

<summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|codeium|Codeium|1.16.18|codeium.codeium-1.16.18|
|csdevkit|ms-dotnettools|1.10.18|ms-dotnettools.csdevkit-1.10.18-linux-x64|
|csharp|ms-dotnettools|2.45.25|ms-dotnettools.csharp-2.45.25-linux-x64|
|defold-vscode-build|ts-defold|0.1.6|ts-defold.defold-vscode-build-0.1.6|
|github-vscode-theme|GitHub|6.3.4|github.github-vscode-theme-6.3.4|
|numbered-bookmarks|alefragnani|8.5.0|alefragnani.numbered-bookmarks-8.5.0|
|savebackup|purplestone|0.0.4|purplestone.savebackup-0.0.4|
|spaces-inside-braces|AiryShift|0.4.0|airyshift.spaces-inside-braces-0.4.0|
|theme-dracula|dracula-theme|2.25.1|dracula-theme.theme-dracula-2.25.1|
|vim|vscodevim|1.28.1|vscodevim.vim-1.28.1|
|vscode-dotnet-runtime|ms-dotnettools|2.1.6|ms-dotnettools.vscode-dotnet-runtime-2.1.6|
|vscode-eslint|dbaeumer|3.0.10|dbaeumer.vscode-eslint-3.0.10|
|vscode-theme-darcula|rokoroku|1.2.3|rokoroku.vscode-theme-darcula-1.2.3|
|vscode-theme-onedark|akamud|2.3.0|akamud.vscode-theme-onedark-2.3.0|
|vstuc|visualstudiotoolsforunity|1.0.4|visualstudiotoolsforunity.vstuc-1.0.4|;

</details>

## OmniSharp log
No such item in VSCode logs

## Steps to reproduce

1. Go to Bottom VSCode panel to find the OutputTab
2. When I look at dropdown list placed in Output tab, there's no anything that associated with Omnisharp name so I can't even see the OmniSharp logs

## Expected  behavior
Trying to fix my C# syntax formatting with OmniSharp.

## Actual behavior
Default formatting, looks no rules from json configs accepted

## Additional context
I opened my project from Unity3D it installed all plugins successfully. Looks like omnisharp was installed too.
Autocompletion works fine. I see all the Unity3D hints for functions and methods.
```bash
$ find ~/.vscode/extensions/ -iname 'ms-*' 
/home/user/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-2.1.6
/home/user/.vscode/extensions/ms-dotnettools.csdevkit-1.10.18-linux-x64
/home/user/.vscode/extensions/ms-dotnettools.csharp-2.45.25-linux-x64
```

When I look at dropdown list placed in Output tab, there's no anything that associated with Omnisharp name. That's the first problem. And the second one is ignoring omnisharp formatting settings by Omnisharp which were placed here:
```bash
~/.omnisharp/omnisharp.json
<project>/omnisharp.json
<project>/.editorconfig
```
All files with the same contents. No one of those file worked.

Tried to change `"omnisharp.enableEditorConfigSupport"` - nothing works. And I even don't see the logs again.
In my vscode settings.json I have settings:
```
	"omnisharp.loggingLevel": "debug",

	"razor.format.enable": true,
	"csharp.format.enable": true,
	"omnisharp.useModernNet": false,
	"omnisharp.monoPath": "/usr/bin/mono",
	"omnisharp.enableEditorConfigSupport": false,
	"omnisharp.useEditorFormattingSettings": true
```

Even if I press: ctrl+shift+p looking for `restart omnisharp` - I don't even see anything associated with omnisharp text.

```
$ dotnet --version
8.0.108

$ mono --version
Mono JIT compiler version 6.12.0 (makepkg/0cbf0e290c3 Sat Mar  9 11:37:33 UTC 2024)
```

In the Output tab -> "C#" I see such logs:
```
Using dotnet configured on PATH
Dotnet path: /usr/share/dotnet/dotnet
Activating C# + C# Dev Kit...
waiting for named pipe information from server...
[stdout] {"pipeName":"/tmp/854d4bc4.sock"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 1:58:27 PM] [Program] Language server initialized
[Info  - 1:58:31 PM] [WorkspaceProjectFactoryService] Project /home/user/projects/unity/MyFirstTry_3d/Assembly-CSharp.csproj loaded by C# Dev Kit
```

What steps should I check to find out what went wrong?

`Arch Linux, VSCode 1.93.1, Unity3D 6 Preview.`

**Comment by JoeRobich** [comment]
Hi @ProgrammingLife, The 2.x version of the C# extension defaults to using the Roslyn LSP. You need to set `dotnet.server.useOmnisharp` to `true` in your settings.

<img width="902" alt="image" src="https://github.com/user-attachments/assets/6768c973-60a5-46d2-b500-e42401de2f95">

**Comment by JoeRobich** [comment]
@ProgrammingLife Do you have the C# DevKit installed? If so, the extension will not use OmniSharp until you disable that extension.
<img width="451" alt="image" src="https://github.com/user-attachments/assets/69e2e988-f230-48a2-9156-0cb1dffd0e98">

**Comment by JoeRobich** [comment]
Ah, did not see your extension list because it got folded into the DotNet Information section. You cannot use OmniSharp with the C# DevKit enabled.

<img width="902" alt="image" src="https://github.com/user-attachments/assets/6768c973-60a5-46d2-b500-e42401de2f95">

**Comment by JoeRobich** [comment]
Closing this as answered.
