### ISSUE TITLE
[SUGGESTION] 'Implement interface' quick fix generates the code with NotImplementedException

### ISSUE THREAD

**Issue by dibarbet** [dotnet/vscode-csharp#7640]
Copied from https://github.com/microsoft/vscode-dotnettools/issues/1116
### Describe the feature you'd like

When using the 'Implement interface' quick fix on a missing interface property, the generated code declares the property with both getter and setter throwing NotImplementedException.

### Alternatives considered

 In most cases, it'd be more common to declare the property simply with `{get;set;}`.

**Comment by dibarbet** [comment]
this option should be exposed in vscode
https://github.com/dotnet/roslyn/issues/56847#issuecomment-930393682

**Comment by JoeRobich** [comment]
It is configurable via .editorconfig now https://github.com/dotnet/roslyn/pull/74376
