### ISSUE TITLE
@category 

### ISSUE THREAD

**Issue by Yopoto** [dotnet/vscode-csharp#7715]
Type: <b>Bug</b>

Shshsjdjwuwiwiwiwiwiwiwiwiw

Extension version: 2.50.27
VS Code version: Code - Insiders 1.96.0-insider (54d1a4d6f395e73204ce0b5999439b267aec3fef, 2024-10-31T10:29:28.944Z)
OS version:   
Modes:

System Info: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by dibarbet** [comment]
Closing - no information - if you're experiencing an issue please re-open and describe the problem with repro steps.  Thanks!
