### ISSUE TITLE
Code violations such as IDE1006 are not shown as problems

### ISSUE THREAD

**Issue by gayanper** [dotnet/vscode-csharp#7763]
Type: <b>Bug</b>

## Issue Description ##
Give the code
```
public record ColumnInfo(string Name, string type, int Length = 0, bool IsNullable = false, bool IsPrimaryKey = false,
                         bool IsIdentity = false, bool IsUnique = false, bool IsForeignKey = false,
                         bool IsComputed = false);
```
The violation for `string type` is not shown as a problem in the problem list in vscode.

## Steps to Reproduce ##
Create a file with the following code in it.
```
public record ColumnInfo(string Name, string type, int Length = 0, bool IsNullable = false, bool IsPrimaryKey = false,
                         bool IsIdentity = false, bool IsUnique = false, bool IsForeignKey = false,
                         bool IsComputed = false);
```

## Expected Behavior ##
To appear as a problem in the Problem List. 

## Actual Behavior ##
Right now only a quick action is provided.

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>
        
### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.95.2
**C# Extension**: 2.55.21
**Using OmniSharp**: true

<details><summary>Mono Information</summary>
    Unable to find Mono. Ensure that Mono's '/bin' folder is added to your environment's PATH variable.</details>
<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:           8.0.201
 Commit:            4c2d78f037
 Workload version:  8.0.200-manifests.3097af8b

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  15.1
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.201/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.2
  Architecture: arm64
  Commit:       1381d5ebd2

.NET SDKs installed:
  8.0.201 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|azure-account|ms-vscode|0.12.0|ms-vscode.azure-account-0.12.0|
|ballerina|wso2|4.7.8|wso2.ballerina-4.7.8|
|bash-ide-vscode|mads-hartmann|1.43.0|mads-hartmann.bash-ide-vscode-1.43.0|
|code-spell-checker|streetsidesoftware|3.0.1|streetsidesoftware.code-spell-checker-3.0.1|
|continue|Continue|0.8.56|continue.continue-0.8.56-darwin-arm64|
|cpptools-themes|ms-vscode|2.0.0|ms-vscode.cpptools-themes-2.0.0|
|csharp|ms-dotnettools|2.55.21|ms-dotnettools.csharp-2.55.21-darwin-arm64|
|debugpy|ms-python|2024.12.0|ms-python.debugpy-2024.12.0-darwin-arm64|
|docs-view|bierner|0.1.0|bierner.docs-view-0.1.0|
|EditorConfig|EditorConfig|0.16.4|editorconfig.editorconfig-0.16.4|
|extension-test-runner|ms-vscode|0.0.12|ms-vscode.extension-test-runner-0.0.12|
|file-properties-viewer|brunnerh|1.2.0|brunnerh.file-properties-viewer-1.2.0|
|gap-vscode-maven-xml|undefined_publisher|0.0.1|undefined_publisher.gap-vscode-maven-xml-0.0.1|
|github-vscode-theme|GitHub|6.3.5|github.github-vscode-theme-6.3.5|
|gitlens|eamodio|15.6.3|eamodio.gitlens-15.6.3|
|go|golang|0.42.1|golang.go-0.42.1|
|go-struct-tag-autogen|maxnatchanon|1.1.2|maxnatchanon.go-struct-tag-autogen-1.1.2|
|helidon|Oracle|3.0.0-SNAPSHOT|oracle.helidon-3.0.0-SNAPSHOT|
|kotlin|fwcd|0.2.35|fwcd.kotlin-0.2.35|
|live-server|ms-vscode|0.4.15|ms-vscode.live-server-0.4.15|
|makefile-tools|ms-vscode|0.11.13|ms-vscode.makefile-tools-0.11.13|
|markdown-mermaid|bierner|1.26.0|bierner.markdown-mermaid-1.26.0|
|msbuild-project-tools|tintoy|0.6.6|tintoy.msbuild-project-tools-0.6.6|
|ng-template|Angular|19.0.1|angular.ng-template-19.0.1|
|plantuml|jebbs|2.18.1|jebbs.plantuml-2.18.1|
|prettier-vscode|esbenp|11.0.0|esbenp.prettier-vscode-11.0.0|
|python|ms-python|2024.18.1|ms-python.python-2024.18.1-darwin-arm64|
|remote-containers|ms-vscode-remote|0.388.0|ms-vscode-remote.remote-containers-0.388.0|
|sonarlint-vscode|SonarSource|4.12.0|sonarsource.sonarlint-vscode-4.12.0-darwin-arm64|
|spectral|stoplight|1.1.2|stoplight.spectral-1.1.2|
|toml|be5invis|0.6.0|be5invis.toml-0.6.0|
|tsl-problem-matcher|amodio|0.6.2|amodio.tsl-problem-matcher-0.6.2|
|vscode-azurefunctions|ms-azuretools|1.15.4|ms-azuretools.vscode-azurefunctions-1.15.4|
|vscode-azureresourcegroups|ms-azuretools|0.9.9|ms-azuretools.vscode-azureresourcegroups-0.9.9|
|vscode-docker|ms-azuretools|1.29.3|ms-azuretools.vscode-docker-1.29.3|
|vscode-dotnet-runtime|ms-dotnettools|2.2.2|ms-dotnettools.vscode-dotnet-runtime-2.2.2|
|vscode-eslint|dbaeumer|3.0.10|dbaeumer.vscode-eslint-3.0.10|
|vscode-git-cruise|GuodongSun|0.2.4|guodongsun.vscode-git-cruise-0.2.4|
|vscode-github-actions|github|0.27.0|github.vscode-github-actions-0.27.0|
|vscode-gradle|vscjava|3.16.4|vscjava.vscode-gradle-3.16.4|
|vscode-js-profile-flame|ms-vscode|1.0.9|ms-vscode.vscode-js-profile-flame-1.0.9|
|vscode-kubernetes-tools|ms-kubernetes-tools|1.3.18|ms-kubernetes-tools.vscode-kubernetes-tools-1.3.18|
|vscode-markdown-plantuml-preview|myml|0.0.2|myml.vscode-markdown-plantuml-preview-0.0.2|
|vscode-openapi|42Crunch|4.29.2|42crunch.vscode-openapi-4.29.2|
|vscode-pylance|ms-python|2024.11.1|ms-python.vscode-pylance-2024.11.1|
|vscode-selfhost-test-provider|ms-vscode|0.3.25|ms-vscode.vscode-selfhost-test-provider-0.3.25|
|vscode-spotless-gradle|richardwillis|1.3.230731194758|richardwillis.vscode-spotless-gradle-1.3.230731194758|
|vscode-xml|redhat|0.27.2024110808|redhat.vscode-xml-0.27.2024110808-darwin-arm64|
|vscode-yaml|redhat|1.15.0|redhat.vscode-yaml-1.15.0|;

</details>

Extension version: 2.55.21
VS Code version: Code 1.95.2 (Universal) (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Darwin arm64 24.1.0
Modes:

**Comment by gayanper** [comment]
In Omnisharp LS this works as expected when switched to use OMnisharp in configuration with `"dotnet.server.useOmnisharp": true`

**Comment by dibarbet** [comment]
@gayanper with the C# extension, an [editorconfig](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-files#editorconfig) must be used to configure naming style rules.  With the following configuration I'm able to see errors in the problems list for IDE1006.  Note - we do not currently show 'info' level diagnostics in the problems list - they must be either warnings or errors (see https://github.com/dotnet/vscode-csharp/issues/7064)

do you have an .editor config configuring the naming style rules - and severity do you have it configured to be?  With the following .editorconfig configuration I am able to see errors in the problems list for IDE1006
```
dotnet_naming_rule.properties_should_be_pascal_case.severity = error
dotnet_naming_rule.properties_should_be_pascal_case.symbols = parameters
dotnet_naming_rule.properties_should_be_pascal_case.style = pascal_style
dotnet_naming_symbols.parameters.applicable_kinds = property
dotnet_naming_style.pascal_style.capitalization = pascal_case
```

**Comment by gayanper** [comment]
Yes adding a editorconfig and making IDE1006 to warning level start to who me warning in the problem list. Thanks. Should i close this ?

**Comment by dibarbet** [comment]
Thanks - closing.
