### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by aymandarwish** [dotnet/vscode-csharp#7808]
- Issue Type: `Performance`
- Extension Name: `csharp`
- Extension Version: `2.55.29`
- OS Version: `Windows_NT x64 10.0.22621`
- VS Code version: `1.95.3`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/adarwish/AppData/Local/Temp/ms-dotnettools.csharp-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by dibarbet** [comment]
@aymandarwish I don't think the cpu profile got attached correctly - would you mind adding it?

**Comment by dibarbet** [comment]
closing, not enough info.
