### ISSUE TITLE
Is vsdbg available for win-arm64?

### ISSUE THREAD

**Issue by l0hn** [dotnet/vscode-csharp#7847]
Is vsdbg available for Windows Arm64? If so how do you install it?

**Comment by gregg-miskelly** [comment]
To make sure I understand your question, are you asking because you are trying to remote debug to Windows ARM64?

If so, you can use the following command (make sure to replace `<folder-to-install-to>`) --
```
powershell -NoProfile -ExecutionPolicy RemoteSigned -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; &([scriptblock]::Create((Invoke-WebRequest -useb 'https://aka.ms/getvsdbgps1')))  -Version latest -RuntimeID win10-arm64 -InstallPath <folder-to-install-to>"
```

**Comment by l0hn** [comment]
@gregg-miskelly 

That's perfect thank you!

I was attempting to use "win-arm64" which was failing and didn't think to try "win10-arm64".
